### ISSUE TITLE
No fzf#run function?

### ISSUE THREAD

**Issue by george-b** [junegunn/fzf.vim#1]
Steps to reproduce.

```sh
% /usr/bin/vim -u NONE -c 'source fzf.vim' -c 'Files'

Error detected while processing function <SNR>1_files..<SNR>1_fzf:
line    1:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(extend(a:opts, a:bang ? {} : get(g:, 'fzf_window', s:default_window)))
```

This function does not appear to be defined in this plugin unlike that in the [fzf repo] (https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L101-L152).

Is this expected to be user defined?

**Comment by junegunn** [comment]
As noted in [the installation instruction](https://github.com/junegunn/fzf.vim#installation), this repository currently depends on the main fzf repository which contains the implementation of `fzf#run` function. I haven't decided if I should duplicate the code here, so this repository can be used independently.

**Comment by george-b** [comment]
Ah sorry skipped over that as I don't use plug.

**Comment by jedateach** [comment]
I don't use vim-plug either. @junegunn do you think the README could be updated to explain how to depend on the main fzf repo?

**Comment by junegunn** [comment]
I don't think we need to suggest more difficult options when the easier one is available, and it should be straightforward to the users who manually manage their plugins (pathogen) or who decided to use more advanced plugin manager (neobundle). And vundle users should really switch to vim-plug ;)

**Comment by jrhorn424** [comment]
To me, the confusion was that I needed to either use the `vim-plug` configuration, OR `set rtp+=~/.fzf`. So, to make `fzf.vim` function correctly with vim-plug, you'll still need `set rtp+=~/.fzf` in your `.vimrc`.

It's obvious to me now, but it wasn't obvious three days ago.

**Comment by jrhorn424** [comment]
You may not want to copy code, but would it be out of place to copy instructions into this README? Happy to make a PR.

**Comment by luqasz** [comment]
Hi. 

I do not use vim-plug. I use pathogen and manage my plugins with git submodules. 
What I've done to make fzf.vim work (partially):

* manually downloaded https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim and placed it in `~/.vim/bundle/fzf-main/plugin/fzf.vim`. 
* bwer install fzf

fzf.vim commands work in vim (terminal) but they silently discard in macvim gui. How can I fix that. Please note that vim-plug is not the only plugin manager. How can I make it work in both vim and mvim ?

**Comment by luqasz** [comment]
Got it in fzf [README](https://github.com/junegunn/fzf#usage-as-vim-plugin).
```
Note: To use fzf in GVim, an external terminal emulator is required.
```
Maybe display a warning/error to gui users ?

**Comment by amigrave** [comment]
Every time I make a new config I get bitten by this weird setup because I have time to forget about it :)

Would it be possible to somehow merge/move/rename/whatever `<fzf>/plugin/fzf.vim` into `<fzf.vim>/plugin/fzf.vim` in order to make it easy to setup a vim instance so you just need the `fzf` binary + the single `fzf.vim` plugin ?

**Comment by tonny-sofijan** [comment]
Just scratching my head for few days to resolve this problem. I'll post my way, hopefully can benefit others that has same problem.

1. Create **git** and **.vim/autoload** folder in our home directory.
2. In **git** folder, `git clone https://github.com/junegunn/fzf`
3. cd to **fzf** folder, then run `./install`
4. with `sudo`, drop executable **fzf** to **/bin**, then drop **plugin/fzf.vim** to **.vim/autoload**

**Comment by kleinjm** [comment]
Definitely not the right way to do things but @tonny-sofijan answer worked for me. Thanks!

**Comment by fdobad** [comment]
Kind of embarrassing but maybe helps:  
Switched from cloning and `~/.fzf/install` to `apt install fzf`, took me a while to realize that the vimrc line `set rtp+=~/fzf` no longer makes sense, so on the package description [page](https://packages.debian.org/buster/amd64/fzf/filelist) I found `/usr/share/doc/fzf/README.Debian` that got my missing reference:
```bash
echo "source /usr/share/doc/fzf/examples/key-bindings.bash">> ~/.bashrc
echo "source /usr/share/doc/fzf/examples/fzf.vim">>.vim/vimrc
echo 'export FZF_DEFAULT_OPTS="--tabstop=4 --multi --border --preview='head -$LINES {}' --preview-window=right:33%"'>>.bashrc
```
The last one is a personal preference...

**Comment by 92hackers** [comment]
I solve the problem successfully. follow the answer from @fdobad, below is the summary:

Notes:  I use  ubuntu 21.04

1. Install  fzf:   `sudo apt install fzf`
2. Insall fzf vim plugin with vundle:  `Plugin junegunn/fzf.vim`
3. Add `source /usr/share/doc/fzf/examples/fzf.vim` to `.vimrc`。

Besides,  `apt-cache show fzf` will tells a lot.

**Comment by dreamalligator** [comment]
According to https://github.com/junegunn/fzf/issues/2072#issuecomment-778745037, the Aptitude package is very old. Installing via Github clone instructions hopefully helps y'all.

**Comment by iamxiaojianzheng** [comment]
use Packer install fzf，also echo "Unknow function :fzf#run". I don't know how to solve it.

**Comment by pmatulis** [comment]
This definitely needs a better install method. What I did based on [92hackers](https://github.com/junegunn/fzf.vim/issues/1#issuecomment-860325978):

``` text
sudo apt install fzf
git submodule add https://github.com/junegunn/fzf.vim ~/.vim/pack/plugins/start/fzf
```

Then add `source /usr/share/doc/fzf/examples/fzf.vim` to `~/.vimrc`.
