### ISSUE TITLE
Sort :Buffers by most recently accessed

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#100]
It would be neat to sort `:Buffers` by the most recently used buffer. I know `:History` exists, but when having multiple neovim instances open it shares files between those instances. Is it possible to add an option for sorting the buffers this way?

**Comment by flybayer** [comment]
YES YES YES! This is exactly what I need to. This was the behavior of Ctrl-P, and I greatly prefer it!

**Comment by junegunn** [comment]
While the suggestion itself is valid and makes sense, I feel like I should mention this first; you can switch to the previous buffer with <kbd>CTRL</kbd><kbd>6</kbd>. It's something I use everyday, but to my surprise, I recently realized that some users aren't aware of it.

**Comment by danihodovic** [comment]
I am aware of it and I use it regularly. The problem arises when you want to switch between the last 3-4 active buffers.

**Comment by danihodovic** [comment]
@junegunn you are the man!!!

**Comment by flybayer** [comment]
:clap:

**Comment by evmorov** [comment]
@junegunn, is there a way to use `:Buffers` without sorting by last used? I want it to be sorted by name

**Comment by mcchrish** [comment]
For anyone who's here, it might be possible to optimize the current implementation by accessing `lastused` info from `getbufinfo` instead of manually tracking it via autocmd.
See related discussion: https://github.com/ibhagwan/fzf-lua/issues/208

**Comment by junegunn** [comment]
Thanks for the tip. It will be much simpler to use `getbufinfo`. But `lastused` field was added to it [relatively recently](52410575be50d5c40bbe6380159df48cfc382ceb), so we'll have to drop support for Vim versions older than 8.1.2225, and I'm not quite sure if it's worth it at the moment.

**Comment by mcchrish** [comment]
I was thinking the same.

Btw how do you know what version vim added the feature? Is it by looking through the git history or is there a simpler way?

**Comment by mikesmithgh** [comment]
> While the suggestion itself is valid and makes sense, I feel like I should mention this first; you can switch to the previous buffer with CTRL6. It's something I use everyday, but to my surprise, I recently realized that some users aren't aware of it.

Over 6 years later, and you just taught me CTRL-^ / CTRL-6 😂 👍

**Comment by ruizhaogit** [comment]
Does anyone know how to preserve the sorted buffer order after reload from a vim session file?
