### ISSUE TITLE
Is it possible to have history only from current git project?

### ISSUE THREAD

**Issue by eyaleizenberg** [junegunn/fzf.vim#1000]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

When I use the History command I get files from all across my computer. I would like to get the recently open files but only from the current git project. Somewhat of a combination of History and GFiles.

I saw that I can expand function, however, it looks like the fzf#vim#history does not receive a directory and it looks at all files. Is there another solution or am I missing something?

Thanks.

**Comment by junegunn** [comment]
No, it's not supported.

**Comment by domi91c** [comment]
I don't have the scripting knowledge, but I imagine this should be possible by filtering `History`'s source by the contents of `GFiles` or `Files`.

**Comment by peter-subsplash** [comment]
Perhaps in a similar manner as this? https://github.com/junegunn/fzf.vim/commit/7e868c49ac650270884bf46618277bae7077d661

**Comment by peter-subsplash** [comment]
Apparent solution: https://github.com/junegunn/fzf.vim/issues/1013#issuecomment-627707622
