### ISSUE TITLE
fzf won't open quickfix window anymore

### ISSUE THREAD

**Issue by mrassili** [junegunn/fzf.vim#1003]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello,
Opening the quickfix window from fzf Files doesn't work anymore, I usually tab through a few files and hit Enter and it goes to quickfix window w/ ability to `:cn` `:cp` but now it does nothing, and when I try `:cn` I get `No errors`

- [x] Reproducible on a minimal vim config

**Comment by vkaracic** [comment]
@mrassili I have the same issue. Did you close this issue because you found a fix? What is the fix?

**Comment by mrassili** [comment]
not really, it just happens randomly, sometimes it work sometimes it doesn't :/

**Comment by junegunn** [comment]
Files command, unlike Ag and Rg, doesn't put the selected entries to quickfix list. Use `:bn` and `:bp` instead.
