### ISSUE TITLE
:Rg not working

### ISSUE THREAD

**Issue by pyrr** [junegunn/fzf.vim#1005]
I've also tried this with the minimal config and I'm not sure what more info to provide.

`    [Command failed: rg --column --line-number --no-heading --color=always --smart-case '']
`

**Comment by junegunn** [comment]
Have you tried running the shown command on your shell?

**Comment by pyrr** [comment]
Yes. The output is nothing.

**Comment by junegunn** [comment]
You mean the `rg` command is not working on your system?

**Comment by pyrr** [comment]
```
% rg
error: The following required arguments were not provided:
    <PATTERN>

USAGE:

    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help

% rg --column --line-number --no-heading --color=always --smart-case ''
%
```

**Comment by junegunn** [comment]
fzf simply calls the command, and it looks like the command is failing with a non-zero exit status. You'll need to fix that; e.g. upgrade ripgrep.

**Comment by pyrr** [comment]
```
% rg --version
ripgrep 12.0.1
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```
I'm already on the latest version.

**Comment by pyrr** [comment]
Actually my bad. Sorry. 
I thought ripgrep included hidden files  by default.

**Comment by andrescuco** [comment]
In my case, `brew install ripgrep` did the trick.

**Comment by ttkingdom** [comment]
> Removing --smart-case helped me.

This works for me, but do you know the reason why?

**Comment by n8jhj** [comment]
I got here by comparing output with someone who had aliased `rg` to `rg -i`. How insensitive.
