### ISSUE TITLE
Neovim terminal detection

### ISSUE THREAD

**Issue by tpict** [junegunn/fzf.vim#101]
Would it be possible to create a split in Neovim and display fzf in it when fzf is invoked from a shell running in a Neovim terminal outside of tmux?

**Comment by nhooyr** [comment]
this would be pretty simple, check for `$NVIM_LISTEN_ADDRESS` and then use https://github.com/mhinz/neovim-remote to create the split and display fzf. If `$NVIM_LISTEN_ADDRESS` is empty, just do it normally.

Here is an example script https://github.com/nhooyr/neoman.vim/blob/master/scripts/neovim.zsh

**Comment by motdef** [comment]
Thanks, that's a good starting point. Thinking it over, I think this issue should belong in the main fzf repo. The line in ```completion.*sh``` that detects tmux needs an extra evaluation to check ```$NVIM_LISTEN_ADDRESS``` (and the presence of nvr in case the user hasn't installed it). Then you'd need a script to replicate the functionality of fzf-tmux using Neovim splits and :terminal. I don't quite understand how the fzf-tmux script works though.

**Comment by junegunn** [comment]
I currently don't use neovim, so I don't think I'm going to work on this soon-ish. Feel free to take a stab at it and share your solution.
