### ISSUE TITLE
Globally disabling previews doesn't affect `:GFiles?`

### ISSUE THREAD

**Issue by jesseleite** [junegunn/fzf.vim#1010]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Globally disabling previews doesn't seem to affect `:GFiles?`

```vim
let g:fzf_preview_window = ''
```

![image](https://user-images.githubusercontent.com/5187394/80996070-38fc4f80-8e0d-11ea-800f-d161f01e9962.png)

**Comment by yujinyuz** [comment]
It seems to be working fine for me

**Comment by jesseleite** [comment]
Something I've noticed...  `let g:fzf_preview_window = ''` in vim seems to disable the preview fine, **IF** I export global preview window settings for fzf like this in my .zshrc:

```zsh
export FZF_DEFAULT_OPTS='--preview-window right:50%:noborder:hidden --color "preview-bg:234" --bind "alt-p:toggle-preview"'
```

However without that zsh export, `let g:fzf_preview_window = ''` does nothing in vim.  Not sure why this is the case 🤔

**Comment by Frederick888** [comment]
I can confirm this issue using NeoVim 0.4.4, Zsh 5.8.

Without `FZF_DEFAULT_OPTS`, `g:fzf_preview_window` still works but only for some of the commands, e.g. `Files`, `Rg`, `Buffers`, `GFiles`, etc. `GFiles?`, `Commits`, `BCommits` just always place preview window on the right (which iirc is the default).

With `FZF_DEFAULT_OPTS`, `g:fzf_preview_window` still has no effect on `GFiles?`, `Commits` or `BCommits` and they always follow the environment variable.

**Comment by Frederick888** [comment]
I think the problem (at least in the case of `GFiles?`) is that `s:p()` in `plugin/fzf.vim`, where `g:fzf_preview_window` is processed, is not used in some cases, e.g. https://github.com/junegunn/fzf.vim/blob/4145f53f3d343c389ff974b1f1a68eeb39fba18b/plugin/fzf.vim#L53

...when `<q-args> == "?"`, an empty `{}` is used as extra options later in `s:fzf()`.
