### ISSUE TITLE
:CwdHistory implementation?

### ISSUE THREAD

**Issue by jesseleite** [junegunn/fzf.vim#1013]
Not sure if you'd consider implementing `:CwdHistory` natively in fzf.vim here?  I've implemented it locally ([see my dotfiles commit here](https://github.com/jesseleite/dotfiles/commit/9d4745479e69ed86327e5ed6449eb73c044dd8ee)) and it works well.  Basically, I just needed to filter by this custom `s:file_is_in_cwd()` function...

```vim
function! s:file_is_in_cwd(file)
  return filereadable(a:file) && match(a:file, getcwd() . '/') == 0
endfunction
```

The rest of the code is copy and paste, because so many of your functions are `s:` script local, so it's hard to extend locally without copying a whack of stuff.  Anyway, thoughts?

---

- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by jesseleite** [comment]
Or maybe even `:GHistory` (git files history), kind of like what `:GFiles` is to `:Files`?

**Comment by junegunn** [comment]
Thanks, but I've decided not to add features that I don't actually need/use. I just don't have the mental bandwidth to deal with all the different requirements.

I could make `s:all_files` function public if that's gonna help in your case.

**Comment by jesseleite** [comment]
That's fair.  Making `s:all_files()` public would indeed help a lot!  It's a weird name for what it does though.  Might make more sense if it was made public and renamed to something like `recent_files()`... Thoughts?

**Comment by jesseleite** [comment]
...Also in a [more recent commit](https://github.com/jesseleite/dotfiles/commit/1dc673472ad9225985735c7084fd7c6025840d56), I also had to copy `s:preview()` from [plugin/fzf.vim](https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L42-L48).  Would it be worth making `s:preview()` public as well?  I think anybody who is building their own fzf extensions with previews would find that one helpful.

**Comment by jesseleite** [comment]
Submitted PRs, if that helps 🙂

**Comment by jesseleite** [comment]
Thanks again @junegunn for considering my PR's, and merging that `_recent_files()` one specifically ❤️

[This is what I made](https://github.com/jesseleite/dotfiles/blob/c75ae5ebd0589361e1fe84a912f1580a9b1f9a15/vim/plugin-config/fzf.vim#L44-L86) with it.  I especially love the `:PHistory` command there, which is basically `:History`, but scoped to the project's git root.  I was finding myself doing a lot of project switching, and would end up opening similarly named files from the wrong project fairly often.  With `:PHistory` being scoped to the project's git root, I'm only looking at relevant project files 🙂

Anyway thank you again, and take care!

**Comment by peter-subsplash** [comment]
@jesseleite , thanks for sharing your dotfiles. I've been interested in scoping fzf-history like you did. However, I'm getting this error when using that section of your code on Neovim 0.7.0. Thoughts?
```

Error detected while processing function <SNR>13_preview[3]..fzf#vim#with_preview:
line   68:
E730: using List as a String
Press ENTER or type command to continue
```

**Comment by mapperr** [comment]
Just to share an ugly approach:

if you open a project on its root dir like me,
then a quick and dirty command can be

```vim
command! -bang FzfHistoryPseudoLocal call fzf#run({
  \ 'source': fzf#vim#_recent_files(),
  \ 'sink': 'e',
  \ 'options': [
  \   '--query', '!^~ !^/ !^.git/ ',
  \   '--prompt', 'FileHist> ',
  \   '--multi',
  \ ]}, <bang>0)

nnoremap <leader>h :FzfHistoryPseudoLocal<CR>
```

it just pre-populate fzf query to filter out things

**Comment by owallb** [comment]
For future travelers, here's another solution that worked well enough for me, just filtering out non-relative paths:

```vimscript
command! -bang CwdHistory call fzf#run(fzf#wrap({
            \ 'source': filter(
            \   fzf#vim#_recent_files(),
            \   'v:val !~ "^\\~\\?/"'
            \ )}))
```
