### ISSUE TITLE
Dynamically show preview based off width within a custom command

### ISSUE THREAD

**Issue by nwaywood** [junegunn/fzf.vim#1015]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

From the readme:

> If the width of the screen is wider than 120 columns, some commands will show the preview window on the right.

Is it possible to replicate this behavior in a custom command? For example, I have the following command which currently shows a preview all the time. However, I would like it to only show the preview when the screen is wider than 120 columns, just like the default commands.

```vim
command! -bang -nargs=? -complete=dir FzfFiles
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline'], 'window': {'width': 0.9, 'height': 0.6, 'yoffset':0.5,'xoffset': 0.5, 'highlight': 'TODO', 'border': 'sharp'}}), <bang>0)
```

**Comment by junegunn** [comment]
So you don't want to wrap your spec dictionary with `fzf#vim#with_preview` on a narrow screen. Something like this should work.

```vim
command! -bang -nargs=? -complete=dir FzfFiles
    \ call fzf#vim#files(<q-args>, call(&columns > 120 ? 'fzf#vim#with_preview' : 'copy', [{'options': ['--layout=reverse', '--info=inline'], 'window': {'width': 0.9, 'height': 0.6, 'yoffset':0.5,'xoffset': 0.5, 'highlight': 'TODO', 'border': 'sharp'}}])), <bang>0)
```

Same, but easier to read:

```vim
function! PreviewIfWide(spec)
  return &columns > 120 ? fzf#vim#with_preview(a:spec) : a:spec
endfunction

command! -bang -nargs=? -complete=dir FzfFiles
    \ call fzf#vim#files(<q-args>, PreviewIfWide({'options': ['--layout=reverse', '--info=inline'], 'window': {'width': 0.9, 'height': 0.6, 'yoffset':0.5,'xoffset': 0.5, 'highlight': 'TODO', 'border': 'sharp'}})), <bang>0)
```
