### ISSUE TITLE
Question: Can I change the mappings for Buffers/Files navigation? 

### ISSUE THREAD

**Issue by lifeBalance** [junegunn/fzf.vim#1016]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

As the title says, I would like to know if it's possible to change the **shortcuts** for navigating the lists of **files** or **buffers** once they're open.

**Comment by junegunn** [comment]
It's possible with `--bind` option (see `man fzf`). You can apply the option in your global $FZF_DEFAULT_OPTS, or you can only redefine Files and Buffers to use the option as shown in the README page.
