### ISSUE TITLE
Allow sorting results using custom function

### ISSUE THREAD

**Issue by anstadnik** [junegunn/fzf.vim#1017]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi, I would like to sort results by distance like it's done [here](https://github.com/jonhoo/proximity-sort#usage).
It's very useful as, for example, I have multiple tools in one git repo, and usually, I need to find a file in the same folder (or close to) the current one.
I think one solution would be to copy-paste the whole `GFiles` code and insert the sorting command [here](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L558), but for obvious reasons, it's not the best idea (I'll have to update the code when fzf will be updated, also I duplicate the code and enlarge my own dotfiles).
One possible solution might be adding an additional parameter `sorting_command` to the function, and if that is set, use it on the files. It will allow users to implement their own custom sorting functions.

**Comment by junegunn** [comment]
I suggest that you consider writing your own command instead of trying to persuade me to add options that I don't need (see https://github.com/junegunn/fzf.vim#rationale).

https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun should get you started.
