### ISSUE TITLE
Slow startup in nvim

### ISSUE THREAD

**Issue by rbhanot4739** [junegunn/fzf.vim#1020]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

FZF Version `0.21.1 (334a4fa)`
fzf.vim `3925db8`

Hello I am using Neovim 0.4.3 on MacOs catalina 10.15.4 with latest fzf and fzf plugin versions with zsh as my shell.

On the command line running `fzf` or `ctrl-c` is instant and list all the files within a second. 

 `FZF_CTRL_T_COMMAND` is set to `fd --type file --hidden --follow .` 

However when I run `:FZF` or `:Files` inside nvim I instantly get `E363: pattern uses more memory than 'maxmempattern'`, to fix this I set `mmp=2000` and now when I run `FZF` or `:Files` again, the fzf window opens but it is really slow, takes around ~3 seconds to load, typing the fuzzy string is really laggy.

I have tested this with directories containing as less as 50 files.

I have also tested this by loading nvim without any settings and just the plugins and I get the same issue. 

Please let me know if more information is required in order to troubleshoot or debug this issue.

**Comment by rbhanot4739** [comment]
Any updates pls?

**Comment by rbhanot4739** [comment]
Any update on this issue?

**Comment by junegunn** [comment]
I've never experience the problem so I can't help you here. And this seems to be an issue of Neovim, not fzf.

**Comment by rbhanot4739** [comment]
But the error is only triggred when I run `FZF` from neovim and not otherwise so seems to sometihng that is triggred by FZF which is being handled by Neovim.

**Comment by zx1986** [comment]
any further infomation?
I got this issue too:
- NVIM v0.6.1
- MacOS 12.1 (21C52)
- vim.bootstrap original

**Comment by danijar** [comment]
+1
