### ISSUE TITLE
how to permanatley remap :History to <nmap <C-H> :History<CR>

### ISSUE THREAD

**Issue by TanishBansal** [junegunn/fzf.vim#1021]
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [ x] I have searched through the existing issues

Even if I remap using in nmap <C-H> :History<CR>, :History is still being triggered by backspace. Am i missing somethng here?

**Comment by junegunn** [comment]
Ctrl-H is backspace. Also, this is not an issue of fzf or fzf.vim, but a general question regarding Vim.
