### ISSUE TITLE
How to remap CTRL-X to CTRL-S

### ISSUE THREAD

**Issue by loustak** [junegunn/fzf.vim#1022]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I would like to remap CTRL-X (open in split) to CTRL-S. It seems a bit vague in the documentation any idea how I can archieve this?

I have the latest version fzf and fzf.vim.

**Comment by 3vilStar** [comment]
This should do the trick

```vim
let g:fzf_action = {
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-s': 'split',
      \ 'ctrl-v': 'vsplit'
  \ }
```

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration

**Comment by TeenagerPeng** [comment]
Hi, I have an an question, how to set ctrl-v as past,
