### ISSUE TITLE
Give fzf buffer a name

### ISSUE THREAD

**Issue by tpict** [junegunn/fzf.vim#103]
Currently fzf uses the default buffer name ```term:// ... /.fzf/bin/fzf ...``` which makes it difficult to target with plugins like [lightline.vim](https://github.com/itchyny/lightline.vim). For example, Gundo uses ```__Gundo__```.

**Comment by junegunn** [comment]
I'm not an expert on this topic. Please see: https://github.com/junegunn/fzf/pull/264

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/pull/264#issuecomment-111716472
