### ISSUE TITLE
Proposal: Change Rg to Rgz

### ISSUE THREAD

**Issue by eduardoarandah** [junegunn/fzf.vim#1030]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Proposal to change `Rg` command to `Rgz`**

`Rg`  `Ag` and all wrapped external command would become an easy mnemonic adding a **z** in the end

- RipGrep fuZzy
- Ag fuZzy

For bare `Rg` commands exists other tools, for other purposes. 

For example, this other `Rg` command is super useful for refactoring, where you search and get all results in quickfix:

https://github.com/jremmen/vim-ripgrep

**Comment by junegunn** [comment]
I won't change names not to break backward compatibility. You can easily redefine the command in different names if you have conflicting plugins.

**Comment by TamaMcGlinn** [comment]
If you want non-fuzzy search, just prepend a single quote. For example, searching for `'foo br` will match foobar, fooboor but not froobar.

On the other hand, moving the results into a quickfix buffer would be a really useful feature to add to fzf.vim (that's why I came to this issue)

**Comment by junegunn** [comment]
> moving the results into a quickfix buffer

Press ALT-A to select all the matches and press enter.
