### ISSUE TITLE
How to move search input line to the bottom of the window ?

### ISSUE THREAD

**Issue by drjosephliu** [junegunn/fzf.vim#1033]
- [x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x ] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

Working on a new computer and installed the latest versions of fzf (0.21.1), ripgrep(12.1.0) and fzf.vim.

I'm use to have the search input line at the bottom of the window, but for some reason, on my new computer it's at the top. It's also now showing the preview window too even though I didn't configure it to. Any reason for these features?

Pic related:

<img width="1066" alt="Screenshot 2020-05-19 at 3 16 15 PM" src="https://user-images.githubusercontent.com/22230085/82296871-73a4e100-99e4-11ea-8651-e60e78c37eb6.png">

`.vimrc` settings:
```
" fzf and ripgrep settings
set rtp+=/usr/local/opt/fzf
let g:fzf_action = {
    \ 'ctrl-t': 'tab split',
    \ 'ctrl-i': 'split',
    \ 'ctrl-s': 'vsplit'
    \ }
nnoremap <C-p> :Files<CR>
nnoremap <S-f> :Rg<CR>

```

`.bash_profile` settings:
`export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
`

**Comment by DanilaMihailov** [comment]
You can disable preview window by setting option `let g:fzf_preview_window = ''"` in your vimrc.

As for your question, have you looked at `--layout` option? I tried to set it to `--layout=reverse-list
` and it worked in terminal.

**Comment by junegunn** [comment]
> on my new computer it's at the top.

The default layout (`--layout=default`) shows the prompt on the bottom. It looks like you have custom `FZF_DEFAULT_OPTS` in one of your configuration files.
