### ISSUE TITLE
Preview window encoding

### ISSUE THREAD

**Issue by sjhgz** [junegunn/fzf.vim#1034]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

------------------
Hello, how can I change the encoding of preview window? When file encoding with non-utf8 such as gbk, preview window output is garbled.

![](https://user-images.githubusercontent.com/26674559/79071331-bb618a00-7d0d-11ea-94be-ea4a4997f34f.jpg)

Can someone help me? Thanks a lot !

**Comment by junegunn** [comment]
fzf only supports UTF-8. You might want to convert your data using something like iconv.

**Comment by sjhgz** [comment]
> fzf only supports UTF-8. You might want to convert your data using something like iconv.

Thanks.
