### ISSUE TITLE
Ripgrep/Grep sink implementation can't handle Windows paths

### ISSUE THREAD

**Issue by habamax** [junegunn/fzf.vim#1037]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Ripgrep/Grep sink implementation can't handle Windows paths.

I have implemented HelpRg command that is helpgrep like command but for FZF.

While it works in my WSL environment it fails to open help files in Windows.

```
"" HelpRg command -- like helpgrep but with FZF and ripgrep
let g:helppaths = uniq(sort(split(globpath(&runtimepath, 'doc/', 1), '\n')))
command! -bang -nargs=* HelpRg
            \ call fzf#vim#grep(
            \   'rg --column --line-number --no-heading --color=always --smart-case -g "*.txt" "" '. join(g:helppaths), 1,
            \   {}, <bang>0)

```

The issue is in:

https://github.com/junegunn/fzf.vim/blob/7a655179a43cd431862a2bf5d297d9e55fd3f814/autoload/fzf/vim.vim#L672

After the split of the line `C:/Users/maksim.kim/vimfiles/pack/minpac/opt/fzf/doc/fzf.txt:30:2` instead of "filename" parts[0] has `C`.

![vim-fzf-sink-issue](https://user-images.githubusercontent.com/234774/82810335-da1f7880-9e96-11ea-8231-7bf1fbde7de5.gif)

**Comment by habamax** [comment]
And the fix might be to use `matchlist` funcion to capture all needed details:

```
function! s:ag_to_qf(line, has_column)
  let parts = matchlist(a:line, '\(.*\):\(\d\+\):\(\d\+\):\(.*\)')
  let text = parts[4]
  let dict = {'filename': &acd ? fnamemodify(parts[1], ':p') : parts[1], 'lnum': parts[2], 'text': parts[4]}
  if a:has_column
    let dict.col = parts[3]
  endif
  return dict
endfunction
```

@janlazo does it make sense? Should I create PR?

**Comment by justrajdeep** [comment]
Hi 

How is it different than `:Helptags`?

**Comment by habamax** [comment]
> Hi
> 
> How is it different than `:Helptags`?

`:Helptags` uses grep and perl to search help tag files. My example uses ripgrep to search help text files.

Btw, I have also reimplemented Helptags to use ripgrep only:

```
    func! FZFHelp(...)
        let tags = uniq(sort(split(globpath(&runtimepath, 'doc/tags', 1), '\n')))
        return fzf#run(fzf#wrap({
                    \ 'source':  'rg --no-filename ".*" '.join(map(tags, 'fzf#shellescape(v:val)')),
                    \ 'sink': function('s:helptag_sink')}))
    endfunc
```

It is not that pretty as I do not preprocess results with perl but hey, it only needs rg:

![image](https://user-images.githubusercontent.com/234774/83042075-e26be500-a049-11ea-9490-e9c031be8222.png)
