### ISSUE TITLE
Bad script in windows

### ISSUE THREAD

**Issue by dakom** [junegunn/fzf.vim#1039]
Might be recent, e.g. [this commit](https://github.com/junegunn/fzf.vim/commit/7a655179a43cd431862a2bf5d297d9e55fd3f814)

Windows, without WSL, tries to use bash and fails. The exact error message is:

> Error detected while processing function <SNR>25_p[3]..fzf#vim#with_preview:
> line 3:
> E605: Exception not caught: bash is not in PATH
> Error detected while procesing function <SNR>25_p:
> line 3:
> E171: Missing :endif

**Comment by dakom** [comment]
I'd imagine that installing WSL will fix it, since it will find bash - but I actually don't want it to use WSL even if it exists since the file searching will be slower (unless the project is in the WSL directory)

Anyway - disabling the preview window fixes for now :)

```
let g:fzf_preview_window = ''
```

**Comment by halfnhalf** [comment]
Hitting same issue

**Comment by Doooogan** [comment]
Also having same issue

**Comment by junegunn** [comment]
Hope 16e3efb helps.
