### ISSUE TITLE
Always opens in fullscreen

### ISSUE THREAD

**Issue by glortho** [junegunn/fzf.vim#104]
Great plugin! But I can't get it to do anything except open in fullscreen. I've tried lots of layout settings, including the one I have in there right now:
```
let g:fzf_layout = { 'down': '~30%' }
```
But it always opens in full-screen no matter what.

Command: `:FZF` (or anything)
Vim: 7.4.826 (terminal)

What else can I provide or try to figure it out? Thank you!

**Comment by junegunn** [comment]
You have to be on tmux, or using neovim.

**Comment by glortho** [comment]
Okay thx

**Comment by vitaly-zdanevich** [comment]
But I want to open it in fullscreen in Neovim, how to do that?
