### ISSUE TITLE
BLines with unsaved buffer does not work but Lines does

### ISSUE THREAD

**Issue by dagadbm** [junegunn/fzf.vim#1041]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hey junegunn,

I know this issue has been brought up before, when you are using BLines and the buffer you are on is not saved (even with set hidden option) fzf throws up an error, the current workaround is to save the file so you can search it aftewards.

However, if I use the Lines command instead and I go to the same unsaved buffer it works... Wouldn't it be possible to just re-use the Lines implementation on the BLines but just reduce the list of the open buffers to the one that is currently selected?
It seems the implementations are wildly different, BLines for some reason uses the quickfix list from what I saw.

I can't really program vim script but theoretically, at least in my head, it makes sense what I am saying and it should fix the problem right?

**Comment by junegunn** [comment]
> fzf throws up an error

Which error?

**Comment by dagadbm** [comment]
![image](https://user-images.githubusercontent.com/16737095/83270319-3698d580-a1c0-11ea-8c2e-215b80908873.png)

**Comment by junegunn** [comment]
I can't reproduce the problem. Have you tried testing it with the minimal config suggested in the issue template?

https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md

**Comment by dagadbm** [comment]
Gah maybe this is a conflict of some other of the dozens of plugins I
have... FML..
How the hell do you debug these kinds of issue? Any suggestions?

**Comment by junegunn** [comment]
Well, there's no elegant way to do it. Comment out plugins and settings until you don't see the error.

**Comment by dagadbm** [comment]
I have finally figured it out!
It is actually a problem with one of fzf configs..

let g:fzf_action = {
\  'ctrl-t': 'tab split',
\  'ctrl-s': 'split',
\  'ctrl-v': 'vsplit',
\  'enter': 'edit',
\}

as soon as i deleted this code everything started working again.

**Comment by dagadbm** [comment]
I have no idea why though.. kind of weird. Btw would you consider changing
the default Ctrl-x to actually be ctrl-s which is actually the vim default

**Comment by dagadbm** [comment]
Actually the problem is this line only:
\  'enter': 'edit',
