### ISSUE TITLE
Vim 8.1's floating window fails to open when using custom command to support extra rg flags (such as filtering by file type)

### ISSUE THREAD

**Issue by nickjj** [junegunn/fzf.vim#1042]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x]  I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi, I'm using the latest version of fzf and fzf along with Vim 8.1.

I added this custom command:

```vim
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case " . <q-args>, 1, <bang>0)
```

Which allows you to run things like `:Rg hello -g '*.py'` to limit searches to .py files or `:Rg "Bug fix" -g '*.md'` for multi-word filtered searches.

Functionality wise this works. I only just updated to Vim 8.1 today which means I never saw the floating window until today. While experimenting I removed my command and noticed the amazing floating window with fzf.

But filtering for file types is important too. I tried looking at the source code to see if I need to modify something in the command, but after a bit of trial and error I couldn't get something that worked.

How would you adjust that command to support floating windows to see a preview of the result?

**Comment by dagadbm** [comment]
there is a plugin called vim-agriculture that helps on this

**Comment by junegunn** [comment]
Are you sure you're running Vim 8.1? Because floating window support requires Vim 8.2.

https://github.com/junegunn/fzf/blob/f81feb1e69e5cb75797d50817752ddfe4933cd68/plugin/fzf.vim#L655-L657

Given that you have the right Vim version, your command will run in pop-up without a problem if you have properly set up `g:fzf_layout`.

```vim
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

**Comment by nickjj** [comment]
I am running 8.1, but perhaps this feature I'm speaking about isn't a floating window. It's similar to what you did with git commits and showing extra info on the right.

**Comment by nickjj** [comment]
I checked there, but when I do this:

```vim
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case " . <q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)
```

It does the same thing as not adding the options. The search results are shown but the preview is never shown.
