### ISSUE TITLE
Colorscheme not applied on preview window

### ISSUE THREAD

**Issue by CristoAMH** [junegunn/fzf.vim#1043]
- [X ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ X] I have read through the manual page of fzf (`man fzf`)
- [ X] I have searched through the existing issues

![image](https://user-images.githubusercontent.com/39212295/83287642-ed557f80-a1d9-11ea-933b-cc8a26e821ba.png)

*my problem:* as you can see the right side doesn't have any color. 
I tried 3 different schemes: night-owl, ayu and onedark. No one of these seems to work and I also put and remove this with every colorscheme;
`let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }`

I am missing something?

**Comment by junegunn** [comment]
We use [an external program](https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh) to render the preview window and it does not respect `g:fzf_colors`.

1. Install [`bat`](https://github.com/sharkdp/bat) and the preview script will use it to syntax-highlight the code
2. Configure `BAT_THEME` if you want to change the colors.

**Comment by williamsmj** [comment]
@junegunn Have you considered taking advantage of the popup feature (new in vim 8.2) to provide the preview? That will give you vim's syntax coloring (and optionally line numbers) out of the box. Possibly too basic for you, but I found [this video from the author of quickpeek.vim](https://www.youtube.com/watch?v=1AOhfnokacE&feature=youtu.be) a useful introduction.

**Comment by junegunn** [comment]
fzf is an external program that you can run on your terminal rather than a native Vim plugin, so that's not an option.

**Comment by jayywolff** [comment]
i dont know how but the [onedark](https://github.com/joshdick/onedark.vim) vim theme works out of the box with syntax highlighting matching the vim colorscheme for the preview window in fzf.vim so it is possible.

when i use other themes like [nightfox](https://github.com/EdenEast/nightfox.nvim), the syntax highlighting does not match my colorscheme
