### ISSUE TITLE
How to call Rg to search for a pattern in a specific file

### ISSUE THREAD

**Issue by anoop1005** [junegunn/fzf.vim#1049]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by anoop1005** [comment]
Currently Rg searches to all the files. Can i limit Rg to search a pattern for a specific file.

**Comment by jasoneveleth** [comment]
I think you might be looking for this
:Rg <pattern> -g '*.py'

source: https://youtu.be/fP_ckZ30gbs?t=1434

**Comment by jasoneveleth** [comment]
You should probably check out ripgrep documentation

**Comment by jcliftonlee** [comment]
The default Rg doesn't work that way. You need to add some customization to make it pass the additional arguments:
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \ "rg --column --line-number --no-heading --color=always --smart-case " .
  \ <q-args>, 1, fzf#vim#with_preview(), <bang>0)
```

**Comment by nbfhscl** [comment]
This code works for me. Basically consistent with `rg` in the command line
1. `RG` search in current dir.
2. `RG <pattern>` search in current dir.
3. `RG <pattern> <dir/file>` search in specific dir/file.
```
function! RG(fullscreen, ...)
        let l:pat = ''
        let l:dir = expand("%:p:h")
        if a:0 > 0
            let l:args = split(a:1)
            let l:pat = l:args[0]
            if len(l:args) > 1
                let l:dir = l:args[1]
            endif
        endif
    let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
    let initial_command = printf(command_fmt, l:pat.' '.l:dir)
    let reload_command = printf(command_fmt, '{q}'.' '.l:dir)
    let spec = {'options': ['--phony', '--query', l:pat, '--bind', 'change:reload:'.reload_command]}
    call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction
command! -bang -nargs=? -complete=dir RG call RG(<bang>0, <f-args>) 
```
