### ISSUE TITLE
Lines command opens selected line in left-most window only

### ISSUE THREAD

**Issue by zhimsel** [junegunn/fzf.vim#105]
Let's say I have two vsplits open for the same buffer. The right vsplit is active (cursor is in that one). If I run `:Lines` and select the line I want to jump to, it'll jump to the line in the left window instead of the active one (the right one). 

Any ideas? I'm running a pretty minimal setup regarding fzf:

```vim
let g:fzf_layout = { 'window': 'new', 'below': '12' }
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

My entire vimrc is viewable here: https://github.com/zhimsel/dotfiles/blob/master/vimrc

This happens with both `:Lines` and `:BLines`.

**Comment by junegunn** [comment]
Not reproducible for me, probably something in your .vimrc. See if it's still reproducible with a minimal vimrc like follows:

```vim
source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugins')
Plug '~/.fzf'  " fzf is not just for vim, so it's managed externally
Plug 'junegunn/fzf.vim'
call plug#end()
```

By the way, `{ 'below': '12' }` is not a valid expression, it'll be simply ignored.

**Comment by zhimsel** [comment]
I just realized that this only happens in neovim, not vim. 

I tested your minimal vimrc on both, with the following results:

neovim: `:BLines` seems to work correctly; `:Lines` moves both windows (same buffer)
vim: `:BLines` works fine, as done `:Lines`

With further testing, it seems that it's actually switching to the leftmost pane *before* moving to the selected file. If I run any of fzf.vim's commands (`:[B]Lines`, `:Buffers`, `:Files`) and hit escape (i.e. not selecting anything), it switches to the leftmost pane any time. This behavior is not present in the minimal vimrc. So it's gotta be something with my config. I'll try to narrow it down.

> By the way, { 'below': '12' } is not a valid expression, it'll be simply ignored.
Ah, thanks :)

**Comment by zhimsel** [comment]
Testing further, I discovered this actually still happens if I disable `fzf.vim` and call `:FZF` and hit escape. So it doesn't seem related to this plugin.

**Comment by junegunn** [comment]
I can't reproduce the problem even on Neovim. Do you have the latest version of Neovim, fzf and its vim plugin?

**Comment by zhimsel** [comment]
```
$ nvim --Version
NVIM 0.1.2
Build type: RelWithDebInfo
```

```
$ vim --Version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 28 2016 14:41:15)
MacOS X (unix) version
Included patches: 1-1655
Compiled by Homebrew
```

**Comment by zhimsel** [comment]
And yes, fzf and fzf.vim are at `master/HEAD`

**Comment by junegunn** [comment]
Hmm, I have the same version of Neovim but it's not reproducible for me.

**Comment by zhimsel** [comment]
Hm. It seems it only happens on the "first" usage of `:[B]Lines`. Once I
run `:Lines` and open a file, the next time (and all further calls) work
normally...


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by zhimsel** [comment]
Correction: happens once per "set" of windows. If I add a new split, it
occurs again for the first run.


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net
