### ISSUE TITLE
Suggestion: include snippet descriptions in fuzzy search

### ISSUE THREAD

**Issue by katonori** [junegunn/fzf.vim#1050]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Why Snippets command searches words only in trigger words of snippets?
I think it's better to search words in snippet descriptions in addition to trigger words.

I modified the plugin like below by myself and it seems to work fine for me.

```
$ git diff 8f1e73b598d27d78dfb5843be19a73b6a3b222b1
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index 501101d..7706d49 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -914,7 +914,7 @@ function! fzf#vim#snippets(...)
   let colored = map(aligned, 's:yellow(v:val[0])."\t".v:val[1]')
   return s:fzf('snippets', {
   \ 'source':  colored,
-  \ 'options': '--ansi --tiebreak=index +m -n 1 -d "\t"',
+  \ 'options': '--ansi --tiebreak=index +m',
   \ 'sink':    s:function('s:inject_snippet')}, a:000)
 endfunction
```

Would you mind to change the default behavior to this or add an option to switch the behavior ?
I think many people likes this behavior better than current one.

**Comment by junegunn** [comment]
I no longer use ultisnips so I don't have any opinion on it and I don't know if it's the right call to change the current behavior. I'll revisit the issue when there are more demands. But please note that just like any other commands in fzf.vim, you can easily override the default options like so:

```vim
command! -bar -bang Snippets
  \ call fzf#vim#snippets({'options': '--ansi --tiebreak=index +m'}, <bang>0)
```

**Comment by MushiTheMoshi** [comment]
Hi @katonori, did you happen to workaround this problem? , I would like to know how to achieve this as well. BTW @junegunn  awesome work done with fzf, really productive tool. _
