### ISSUE TITLE
Rg hides filename on long result

### ISSUE THREAD

**Issue by Racle** [junegunn/fzf.vim#1051]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Filename is hidden on longer result.
Is there any way to always show filename on search results?

You can see my problem here (using floating window with neovim)
![image](https://user-images.githubusercontent.com/759091/84483587-38739600-aca2-11ea-9aee-4ce9b48f8dee.png)

On shorter result it works just fine: 
![image](https://user-images.githubusercontent.com/759091/84483771-8092b880-aca2-11ea-953a-5c668803b4c8.png)

My fzf and Rg settings can be found here: https://github.com/Racle/dotfiles/blob/master/neovim/.config/nvim/plug-config/fzf.vim#L8-L13

**Comment by junegunn** [comment]
You can work around the problem by redefining Rg command in your configuration file. I can think of a few approaches.

### Preview window is shown on the right by default, CTRL-/ disables it

```vim
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1,
  \   fzf#vim#with_preview('right', 'ctrl-/'), <bang>0)
```

### Preview window hidden by default

```vim
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1,
  \   fzf#vim#with_preview('right:hidden', 'ctrl-/'), <bang>0)
```

### Preview window on top

```vim
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1,
  \   fzf#vim#with_preview('up', 'ctrl-/'), <bang>0)
```

### Preview window on top + opens in fullscreen (even without `!`)

```vim
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1,
  \   fzf#vim#with_preview('up', 'ctrl-/'), 1)
```

**Comment by Racle** [comment]
Thanks for that! 

I'll have to try and configure with your configurations, and modify for my liking :) (in finnish layout Ctrl+/ is actually ctrl+shift+7, so that I might change at least)

Didn't even know/think about that you could toggle preview window.

So toggling preview might be good alternative. I still think there might be few longer lines that fails, but most of the time that should be OK. 

Unless there is option to show maximum of 10-20 character before and after result, or something like that, it would "fix" longer lines. Didn't saw anything like that there when I was looking manual.

**Comment by abenz1267** [comment]
Hi,
I don't want to open up in a new issue, since it kinda falls into the same category:

is it possible to NOT show the Rg result? As in: only show the filename, but NOT the actual content. If you use a preview window i find that pretty noisy and useless, i'd much rather just see the filename:line:col. I always end up not seeing the filenames anymore...

Would be also nice to be have matches within the same file not produce another result, but rather show it as "filename (number of results)" or so, but i assume that's something ripgrep has to implement, right?

Regards

**Comment by you-n-g** [comment]
@junegunn 
The latest version doesn't work in my config. 
I want to use rg to grep files **without grep filename**. 

Here is my config
```
command! -bang -nargs=* Rgc
     \ call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'ctrl-/'), <bang>0)
```
neovim will echo `invalid preview window: ctrl-/` when I press `ctrl-/`

**Comment by junegunn** [comment]
@you-n-g 

https://github.com/junegunn/fzf.vim/blob/0fe8e198a3a501b54dbc4f9587526c097599f95a/autoload/fzf/vim.vim#L77-L78

The current implementation of `fzf#vim#with_preview` doesn't allow you to skip the second argument. Try something like `fzf#vim#with_preview({ ... }, 'right', 'ctrl-/')`

**Comment by you-n-g** [comment]
@junegunn  It works now. Thanks!

**Comment by iamaamir** [comment]
> Hi, I don't want to open up in a new issue, since it kinda falls into the same category:
> 
> is it possible to NOT show the Rg result? As in: only show the filename, but NOT the actual content. If you use a preview window i find that pretty noisy and useless, i'd much rather just see the filename:line:col. I always end up not seeing the filenames anymore...
> 
> Would be also nice to be have matches within the same file not produce another result, but rather show it as "filename (number of results)" or so, but i assume that's something ripgrep has to implement, right?
> 
> Ripgrep has the '-c' flag that seems to be the appropriate solution. It works as expected in terminal, but i can't search filecontent when set in Fzf. Only filenames.
> 
> Regards

i want the same thing but for :Ag (Silver Search)

**Comment by arisolt** [comment]
I am finding a lot of situations (when searching in documents with long paragraphs) that even when toggling the preview window off, the filename still isn't visible. Has anyone found a better solution in the meantime?

**Comment by chcore** [comment]
@junegunn is there a workaround for this that does not involve manipulating the preview window? Is there a way to have it always show the file name, or even *just* the file name (while keeping the preview window as-is)?

Same as others in here, I use vim to write plaintext documents with long paragraphs. Searching for a group of words will result in many hits across many files, and not being able to tell immediately which files I am looking at reduces fzf's effectiveness for me (still works amazingly well for code though).

**Comment by junegunn** [comment]
@chcore No.

**Comment by mcauley-penney** [comment]
> Hi, I don't want to open up in a new issue, since it kinda falls into the same category:
> 
> is it possible to NOT show the Rg result? As in: only show the filename, but NOT the actual content. If you use a preview window i find that pretty noisy and useless, i'd much rather just see the filename:line:col. I always end up not seeing the filenames anymore...
> 
> Would be also nice to be have matches within the same file not produce another result, but rather show it as "filename (number of results)" or so, but i assume that's something ripgrep has to implement, right?
> 
> Ripgrep has the '-c' flag that seems to be the appropriate solution. It works as expected in terminal, but i can't search filecontent when set in Fzf. Only filenames.
> 
> Regards

@abenz1267 I'm doing this using `rg -o -r '' --column --no-heading --color=never --smart-case`

The important parts are `-o` and `-r ''`.

**Comment by hood** [comment]
Any news on this? I’d love to be able to only see the results’ filenames since I’m using a preview window too. Even just making sure that filenames neve get out of sight when text gets truncated and the focus goes to the matched segment instead would be alright.

**Comment by arisolt** [comment]
I've switched to https://github.com/dyng/ctrlsf.vim. Far from being equivalent, but for my needs it works.

**Comment by junegunn** [comment]
In the latest version of fzf.vim, you can toggle preview window by pressing `CTRL-/`. No custom definition is required.

@hood 

> I’d love to be able to only see the results’ filenames since I’m using a preview window too.

You can't search text inside the preview window, so no secondary fuzzy filtering, it will make `Rg` less useful IMO.

> Even just making sure that filenames neve get out of sight when text gets truncated

In that case, you do need to redefine the command. What you need is to add `--no-hscroll`.

```vim
" Default definition of Rg as of May 2024
" command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".fzf#shellescape(<q-args>), fzf#vim#with_preview(), <bang>0)

" Rg with --no-hscroll
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".fzf#shellescape(<q-args>), fzf#vim#with_preview({'options': '--no-hscroll'}), <bang>0)
```

Refer to https://github.com/junegunn/fzf.vim/blob/269c08641ed5a842a19c03ca14e3eac3ac7ea74b/plugin/fzf.vim#L53-L78 for the default definitions of the commands.

**Comment by hood** [comment]
> In that case, you do need to redefine the command. What you need is to add `--no-hscroll`.

That’s a starter, but if file paths are too long, I can still lose my filename. It’d be cool to truncate file paths left (or even just have the filename showing) when they overflow the max width.
