### ISSUE TITLE
Preview scroll not working

### ISSUE THREAD

**Issue by kernelheap** [junegunn/fzf.vim#1053]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Preview scroll is not working in neovim  on ubuntu 18.04 when :Files is executed. The same configuration works on Mac. 

Preview scroll is also working fine outside neovim on ubuntu 18.04. The problem is the same regardless of whether its vim or neovim. It also works in terminal mode in vim & neovim. Its just not working inside when opened with :Files. Not sure whats wrong. 

Problem is the same even with the minimal configuration.

**Comment by Rodrigo-Barros** [comment]
Hi,  faced this issue too, but in my case I can scroll the lines when file have a "//" inside, I don't know why, but if the file haven't this the scroll not works, I'm on linux mint 19.3 cinnamon.
I tested with a php file, I don't know if make any diffence.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh script, which is used to generate preview content for most of the commands this project provides, cuts off the lines that go beyond the preview window, so the scrolling is not possible. See https://github.com/junegunn/fzf.vim/issues/751

**Comment by kernelheap** [comment]
preview.sh is not being used at all for some reason. I manually removed the preview.sh file from fzf repo and previews are still generated and I can still scroll outside vim but not within vim. What might be wrong if previews are working without the preview.sh script present in fzf repo.

**Comment by Rodrigo-Barros** [comment]
> https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh script, which is used to generate preview content for most of the commands this project provides, cuts off the lines that go beyond the preview window, so the scrolling is not possible. See #751. For now, you can edit the script to allow scrolling.

Thanks for the tip, now I can scroll the file.

**Comment by kernelheap** [comment]
Works now. Thanks
