### ISSUE TITLE
Running FZF in popup window changes Alacritty cursor style

### ISSUE THREAD

**Issue by jaywonchung** [junegunn/fzf.vim#1059]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am using the Alacritty terminal with the cursor style 'Beam', where the cursor shape becomes a pipe(|), not a block.
I have configured fzf.vim such that it runs in a popup window.

The problem is that the moment I invoke any sort of fzf command, e.g. :Files, :Buffers, the cursor shape reverts to the block-shape, never to return before I restart Alacritty.

This can be reproduced under the following environments and procedure:

- OS: Ubuntu 18.04.4
- Vim: 8.2
- Terminal: Alacritty 0.4.2, `cursor: style: Beam` in `~/.config/alacritty/alacritty.yml`
- Latest (2020/06/26) fzf and fzf.vim

```
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
:q 
:let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }
:Files
```

Thanks.

**Comment by jaywonchung** [comment]
This could be Alacritty's fault, but honestly, I have no idea how this happened. Using fzf outside of vim (in `zsh`) or *without* popup windows causes no problem.

**Comment by FIGBERT** [comment]
For the record, I am currently having the same problem. Running macOS Big Sur 11.1.0 not on Apple Silicon.

**Comment by jaywonchung** [comment]
I'm currently on Kitty and Neovim, and I found that entering terminal mode always changes the cursor shape to a block. I haven't found a solution yet, but I'm almost certain that this isn't an issue of fzf. Closing.

**Comment by nickjj** [comment]
I'm noticing this is happening with the Microsoft Terminal but it only started to happen after using zsh instead of bash and it only happens when I spawn fzf inside of Vim (regular Vim not neovim).

**Comment by elijahberscheid** [comment]
> I'm noticing this is happening with the Microsoft Terminal but it only started to happen after using zsh instead of bash and it only happens when I spawn fzf inside of Vim (regular Vim not neovim).

I'm having this exact same issue.

**Comment by hasanpasha** [comment]
have the exact issue using vim in xubuntu 22.10, with both xfce4-terminal and gnome-terminal.

**Comment by m-GDEV** [comment]
Having this issue with Sakura terminal and bash
