### ISSUE TITLE
Let Tags command use all tag files in tagfiles() list

### ISSUE THREAD

**Issue by hejersbo** [junegunn/fzf.vim#106]
For larger projects I usually have multiple tag files in different directories. I.e. a tag search will be using all the tag files. However, the fzf#vim#tags() function will only use the first tag in the tagfiles() list. So if for example I have two directories d1 and d2 each including separate tag files. Then since the tagfiles() list as default includes './tags' as its first element, I will only search d1 tags when in that directory. And likewise for d2. In d1 the d2 tags will not be searched and vice versa.

It would be beneficial (at least for me) if the Tags command would use all the tag files in the tagfiles() list. I am not particularly aware of the inner plumbings of the fzf plugin to know if it is the intention to let this kind of functionality be done by user defined extensions. But if so, I could definitely use a little guidance. But actually I think this feature could be useful as a general extension of the native fzf#vim#tags() function. Anyway, I enjoy using fzf.

**Comment by junegunn** [comment]
It was previously discussed here:
https://github.com/junegunn/fzf.vim/issues/5#issuecomment-134963133

I'm not against the idea. It's just that the use of relative paths in tags files adds some difficulty in implementation. I'll take a look at it when I get some time (and motivation). I'm also open to pull requests.

**Comment by hejersbo** [comment]
OK thanks. I may have a look at this.
