### ISSUE TITLE
:Rg is giving [Command Failed: ...] error

### ISSUE THREAD

**Issue by jasoneveleth** [junegunn/fzf.vim#1061]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I ran the vim command to do minimal configuration, and when I run :Rg it gives this error:
[Command failed: rg --column --line-number --no-heading --color=always --smart-case -- '']
<img width="829" alt="Screen Shot 2020-07-02 at 6 12 32 AM" src="https://user-images.githubusercontent.com/51368643/86346697-4c6c4100-bc2b-11ea-835e-e9bd8a2bf513.png">
Here is a picture.

I am running this on the normal Terminal.app on MacOS 10.15.5. I have the latest of fzf and fzf.vim installed. I used home-brew to install fzf. I'm not sure what the error means, and I couldn't find specific reference to my problem online. There were a couple questions but they were about customization and I am only looking for :Rg to work. If you have time to help me debug or if you need more information that would be wonderful. Thank you so much.

**Comment by jasoneveleth** [comment]
Okay, so I installed rg on brew, and I made fzf use it (in my zshrc I put: export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'). And somehow that fixed it. I don't understand why.

**Comment by junegunn** [comment]
> [Command failed: rg --column --line-number --no-heading --color=always --smart-case -- '']

Which states that the rg command failed, and to understand why, you run the exact command on your shell, and you realize that you don't have `rg` installed on your system. So you install it and it now works.
