### ISSUE TITLE
Preview windows color is different from using `bin/preview.sh` directly

### ISSUE THREAD

**Issue by rainzm** [junegunn/fzf.vim#1065]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi.
My env is maxos+iTerm2+neovim.
I saw #969 . And I have added `set termguicolors` in my init.vim and `export COLORTERM="truecolor"` in my zshrc.
I found that the colorscheme of preview window generated by using `bin/preview.sh` in neovim terminal buffer is different from that generated by using `Rg`. The former is same with that in normal terminal which i want.

Command in neovim terminal buffer:
```shell
 ~/.vim/plugged/fzf.vim/bin/preview.sh pkg/multicloud/esxi/host.go
```
Result:
![image](https://user-images.githubusercontent.com/22927169/87510295-e4dfd800-c6a5-11ea-853f-09bc1149cd96.png)

Use `Rg` in neovim. Result:
![image](https://user-images.githubusercontent.com/22927169/87512392-7f8de600-c6a9-11ea-84ed-453d2c536be9.png)

If you look closely, the colors are obviously different, especially the colors of strings and ordinary text. It is more obvious in actual use.

What I want to know is whether there are other things exclude `bin/preview.sh` in fzf.vim that affect preview windows rendering.

Thanks in advance.

**Comment by smartding** [comment]
I have the same problem using gruvbox theme.
The color rendered by preview.sh seems to be the same as the result I get by running bat directly from command line.

**Comment by nikita-tkachov** [comment]
I have the same issue, but I'm using the Dracula Theme.

Using "bat" from the preview window:
![2020-08-29_10-30](https://user-images.githubusercontent.com/34717219/91639173-d0039d80-e9e2-11ea-9372-cbf3d6868cbb.png)

And using "bat", but just from the terminal window:
![2020-08-29_10-30_1](https://user-images.githubusercontent.com/34717219/91639184-db56c900-e9e2-11ea-8793-98180c46f706.png)

Truecolor support is also enabled for me. It seems that bat is being forced to use 256 colors instead of truecolor?

**Comment by pawel-szopinski** [comment]
I think I have a solution for you all. I found it in bat's issues. Read @sharkdp's post: https://github.com/sharkdp/bat/issues/634#issuecomment-524525661.

**Comment by smartding** [comment]
> I think I have a solution for you all. I found it in bat's issues. Read @sharkdp's post: [sharkdp/bat#634 (comment)](https://github.com/sharkdp/bat/issues/634#issuecomment-524525661).

adding COLORTERM=truecolor to preview.sh did solve the problem.
thanks

**Comment by ranelpadon** [comment]
This is my workaround for now to avoid editing the `preview.sh` and to avoid upgrading to Neovim's nightly builds. I've put it in my `init.vim`. Basically, inserted the `COLORTERM=truecolor` envvar in the preview command. This works as intended on my end (Mac + Alacritty + Tmux): 
```vim
let $FZF_PREVIEW_COMMAND="COLORTERM=truecolor bat --style=numbers --color=always --line-range :500 {}"
```

**Comment by rainzm** [comment]
Thank you all. For me, this problem has been effectively resolved. I think it’s time to close this issue.
