### ISSUE TITLE
Possible to show search highlighting for :BLines?

### ISSUE THREAD

**Issue by himat** [junegunn/fzf.vim#1069]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I remapped the default vim in-buffer search `/` to use `:BLines` from fzf.
But I was using incsearch before for `/` and I liked how it would show the highlights of what you search for.

Is it possible to show a similar highlighting of the matching text in fzf BLines search? 
Or is it possible to modify incsearch somehow to support fuzzy searching via fzf?

**Comment by junegunn** [comment]
I don't think it's readily possible. I think you're better off with plugins like https://github.com/haya14busa/incsearch-fuzzy.vim
