### ISSUE TITLE
--prompt in $FZF_DEFAULT_OPTS not working

### ISSUE THREAD

**Issue by numToStr** [junegunn/fzf.vim#1073]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

So I was configuring `fzf.vim` and found out that `--prompt` flag was not working. It's only happening inside vim but In my terminal, it is working fine.

## Configuration
**This configuration is not working with `fzf.vim`**
```vim
let $FZF_DEFAULT_OPTS="--prompt '|> ' --color=dark --layout=reverse --margin=1,1 --color=fg:15,bg:-1,hl:1,fg+:#ffffff,bg+:0,hl+:1 --color=info:0,pointer:12,marker:4,spinner:11,header:-1"
```
**For prompt to work I have to customize the command**
```vim
let $FZF_DEFAULT_OPTS="--color=dark --layout=reverse --margin=1,1 --color=fg:15,bg:-1,hl:1,fg+:#ffffff,bg+:0,hl+:1 --color=info:0,pointer:12,marker:4,spinner:11,header:-1"

command! -bang -nargs=? -complete=dir Files                                                                                                                                                                  
     \ call fzf#vim#files(<q-args>, { 'options': "--prompt '|> '"}, <bang>0)
```

**Comment by junegunn** [comment]
The commands in fzf.vim overrides `--prompt`. (e.g. `Buf>` for Buffers, `Lines>` for Lines, etc.)

So if you really want to see your custom prompt, then what you did above is the only way to do it.
