### ISSUE TITLE
yanks

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf.vim#108]
I have been using fzf for a while, but only recently I tried the official fzf.vim plugin.

I've been trying to ditch my own versions and rely on those provided by fzf.vim instead, one glaring omission is yank handling. I have a FZFYanks that will display a list of the 10 previously yanked snippets, and lets me choose which one to paste. Is there interest in considering a cleaned up version of this for inclusion in fzf.vim?

PS: I have a couple of other vim use cases of FZF, but only the yank list seems to be generic enough to be of interest to a wider audience.

**Comment by junegunn** [comment]
So how does it look like and how does it work?

**Comment by acornejo** [comment]
tricky question. How does it look:

[0] oldest paste content
[1] some other paste content
...
[9] most recent paste content

How does it work:

you either fuzzy match on the content, or you navigate with ctrl-p/ctrl-n, either way when you select one match it pastes the content in the current cursor position.

**Comment by junegunn** [comment]
I see, it can also be an insert-mode map. Let me see your code.

**Comment by acornejo** [comment]
if it helps here are the relevant bits of the trivial implementation I have now, but I would polish this up for a PR (and make it match the style guide used in fzf.vim, plus use any available helpers, etc..).

```viml
function! s:yank_list()
  return reverse(['0 ' . @0, '1 ' . @1, '2 ' . @2, '3 ' . @3, '4 ' . @4, '5 ' . @5, '6 ' . @6, '7 ' . @7, '8 ' . @8, '9 ' . @9])
endfunction

function! s:yank_handler(reg)
  if empty(a:reg)
    echo "aborted register paste"
  else
    let token = split(a:reg, ' ')
    execute 'normal! "' . token[0] . 'p'
  endif
endfunction
```

**Comment by junegunn** [comment]
Hmm, numbered registers except for `@0` are not updated on yank, am I missing something?

Excerpt from `:help quote_number`:

```
   Numbered register 0 contains the text from the most recent yank command,
unless the command specified another register with ["x].
   Numbered register 1 contains the text deleted by the most recent delete or
change command, unless the command specified another register or the text is
less than one line (the small delete register is used then).

...

   With each successive deletion or change, Vim shifts the previous contents
of register 1 into register 2, 2 into 3, and so forth, losing the previous
contents of register 9.

```

**Comment by acornejo** [comment]
ahh, I think this is useless without the other plugin I was using then.

this means this has no place in fzf.vim :(

For reference, here is the yank version for the easyclip plugin:

https://github.com/svermeulen/vim-easyclip/issues/62

**Comment by acornejo** [comment]
Closed this issue, sorry for wasting your time. I now remember why I used he easyclip plugin, also this is an entertaining post by drew neil about this numbered register issue:

http://vimcasts.org/blog/2013/11/registers-the-good-the-bad-and-the-ugly-parts/

**Comment by junegunn** [comment]
No problem, thanks for the links. I think I'm going to check out easyclip.

**Comment by acornejo** [comment]
yup, easyclip has some nice ideas, although I ended up disabling the blackhole redirect thing because 'dd' is en-grained in my vim workflow to deeply.

let g:EasyClipShareYanks = 1
let g:EasyClipEnableBlackHoleRedirect = 0
