### ISSUE TITLE
Regular expression search not working with FZF & Rg

### ISSUE THREAD

**Issue by anoop1005** [junegunn/fzf.vim#1081]
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [ x] I have searched through the existing issues

Ripgrep allows pattern searches in regular expression. I am unable to pass a raw query to fzf#vim#grep to search for a regular expression.

For eg: to search for strings string1 & string2 in files log1.txt & log2.txt, we can use the below command in ripgrep.
rg 'string1|string2'  log1.txt log2.txt

Is there a way to customize the fzf#vim#grep query to do this?

**Comment by arren-ru** [comment]
Not sure, but I have got regexp working in integration of FZF + Ripgrep
![image](https://user-images.githubusercontent.com/828187/89293154-9eb7dc00-d687-11ea-919b-77ac342f5982.png)

**Comment by junegunn** [comment]
`:Rg foo.*bar` passes the regular expression to the rg process, fzf receives the output list from the process, holds it in memory, and works as the secondary filter with its [own search syntax](https://github.com/junegunn/fzf#search-syntax). To use a regular expression you have to pass it to the underlying rg process.

@arren-ru You probably have redefined `:Rg` command to restart rg process every time you update the query string on fzf.

See https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration
