### ISSUE TITLE
:FZFRg stopped working

### ISSUE THREAD

**Issue by prankousky** [junegunn/fzf.vim#1083]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi,

I mapped `nnoremap <leader>F <c-u>:FZFRg<CR>`. It used to work fine until recently. Now when I run the command manually (`:FZFRg`) or use my mapping, I get 

```
E117: unknown function: fzf_preview#p
E116: invalid arguments for function fzf#vim#grep
```

(my output is German, but this is what it should translate to)

I am running the latest versions of `nvim`, `fzf`, all plugins, and `rg`. This worked fine before. Is there a way to debug this?

I tried using the minimal config from the template provided as well, however, it only provided `FZF` as a command, not `FZFRg`, so I wasn't able to figure out if anything in my config my be responsible. The regular `FZF` runs fine with my config.

What can I do to fix this? Thank you for your help.

**Comment by junegunn** [comment]
> it only provided FZF as a command, not FZFRg

There should be `:Rg`

**Comment by prankousky** [comment]
Thank you! When I remap to `:Rg` it works again.
