### ISSUE TITLE
Can I unmap :W?

### ISSUE THREAD

**Issue by J053Fabi0** [junegunn/fzf.vim#1084]
I sometimes type :W instead of :w for saving, so that's why I want to unmap :W or map it to :w.

- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues searching for "unmap"

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/issues/981

**Comment by kaldown** [comment]
To help someone else:
https://vi.stackexchange.com/questions/27785/disable-command-but-allow-to-write-in-command-mode
