### ISSUE TITLE
BLines and Lines behaviour: first marks lines and populates quickfix list, the second does not?

### ISSUE THREAD

**Issue by cpkio** [junegunn/fzf.vim#1085]
I'm using fzf.vim in Windows, and it works great. But I see unconsistent behaviour: `:Lines` and `:BLines` from the manual seem to be working in same manner, but `:Lines` does not provide marking lines by Tab and populating a quickfix list by Enter key.

Is this the supposed behaviour? And if so, can `:Lines` be made to work in the same manner as `:BLines`?

- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Version of fzf: 0.21.0 (b0673c3).
Version fzf.vim: cloned from repo right now.
Reproducible with no user .vimrc

**Comment by junegunn** [comment]
The support for "tagging" was added in https://github.com/junegunn/fzf.vim/pull/694 only for BLines. I don't think there's any reason we shouldn't do the same for Lines.
