### ISSUE TITLE
Feature request: Expand <cword> et. al in ex commands

### ISSUE THREAD

**Issue by Grazfather** [junegunn/fzf.vim#1086]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

No bug here, Just a feature request.

I was just trying to make a command that is like an improved `*` (search under cursor) that would search across all my open buffers. We can use `:grep <cword>` for this, but it doesn't work for `:Lines`. Searching around, apparently `<cword>` has to be explicitly supported. See [here](https://vi.stackexchange.com/questions/16090/trouble-using-cword-in-mapping).

This would allow something like `:nmap <leader>* :Lines <cword><CR>` which would search for the word under the cursor across all open buffers.

**Comment by junegunn** [comment]
```vim
nnoremap <leader>* :Lines <c-r><c-w><cr>
```
