### ISSUE TITLE
Easy question: Go through fzf history

### ISSUE THREAD

**Issue by vegerot** [junegunn/fzf.vim#1087]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

This is a really simple question, but searching through the existing issues has not helped me.  I want to know how to go through my fzf search history.  So for example, if I search for a file with `:Ag`, go to the file, and make some changes, I now enter `:Ag` again, how can I go back to that previous search term?

**Comment by junegunn** [comment]
See `History` section of the man page.
