### ISSUE TITLE
Error when running :Buffers

### ISSUE THREAD

**Issue by gitabaz** [junegunn/fzf.vim#1090]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am getting the following error when running :Buffers. Other commands like :Files, :GFiles work fine. The error still occurs with the minimal configuration. This is on neovim 0.43

`Error running cat '/tmp/nvimpQFlFE/2'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '.../plugins/start/fzf.vim/bin/preview.sh'\'' {1}' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimpQFlFE/1`

---

Seems like I was running fzf version 0.20 instead of the latest 0.22

**Comment by fpereira1** [comment]
upgrading to latest 0.22 fixes it

**Comment by dom-k** [comment]
I use fzf (0.22.0) and fzf.vim (master) but still get the same error message for the `:Buffers` command. Am I missing something?
