### ISSUE TITLE
How to implement Rg command with preview window on Window 7/10?

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf.vim#1094]
Hello,

My laptop is runing on Windows 10 environment. The Vim and plugin version I have used are as following:
fzf : 0.22.0
Vim: 8.2.1328
bat: 0.15.4

I have read the example of "Example: Rg command with preview window" at website https://github.com/junegunn/fzf.vim, but I have found it only can work at Linux system. For Windows 7/10, it can't directly run preview.sh which will be invoked by fzf#vim#preview.

For command Files, I have try to modified from the example to like this:

![image](https://user-images.githubusercontent.com/20179047/90361233-3d810700-e090-11ea-8688-9c375e21ede5.png)

It work correctly, and I can see the preview windows and bat no report error.

But if I modified the Rg command from example to like this:

![image](https://user-images.githubusercontent.com/20179047/90360954-97cd9800-e08f-11ea-8d85-909b0cccd587.png)

Rg command can show preview windows but bat report an '[bat error]'. I'm no so familar with bat command. I think there is something wrong with the 'option' I gived inside the function fzf#vim#grep. How to fix this so that it can support preview windows on Windows 7/10?

**Comment by jiangjianshan** [comment]
Hi all,

    Previously I have trying to implement a powersheel script which function is similar as preview.sh inside fzf.vim. But I have just find a simple solution to solve this problem. I have just putted the bash.exe where can from Git installed path, e.g. D:\Program Files\Git\bin to the PATH. I really don't want to install WSL in Windows because I have already has dual system where in other partiton.

**Comment by lordherp** [comment]
I have a very similar issue, may I know how you solved the problem?
