### ISSUE TITLE
:Buffers command closes immediately in vim and neovim

### ISSUE THREAD

**Issue by fwy** [junegunn/fzf.vim#1097]
- [x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x ] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

After updating fzf.vim late last week to the latest commit, I find that the :Buffers command no longer works correctly.  I can see the window that displays the buffer list open and close in a flash, but it is not usable.  The :Files, :Lines, and :Maps commands (the other ones I use most frequently) work fine.  This problem exists on my Windows 10 workstation in both vim and neovim.

The problem only started with the latest update, and based on reviewing the commits I think it was probably introduced by the most recent one 'Use native preview scroll of fzf 0.22.0' (https://github.com/junegunn/fzf.vim/commit/4145f53f3d343c389ff974b1f1a68eeb39fba18b).

I tried the suggested minimal configuration in an msys2 bash console ...

vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

... and did not reproduce the error, although when testing :Buffers, :Files, :Lines, and :Maps a separate shell window was opened outside of the vim window (don't know if that is expected).

**Comment by drk-mtr** [comment]
Thanks for identifying the commit. It means I can add this to .vimrc to work around it temporarily... I'm lost without <leader>b ha.

`Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim, { 'commit': '2115cae' }`

**Comment by junegunn** [comment]
Upgrade fzf.
