### ISSUE TITLE
Rg with preview and multiple options not working

### ISSUE THREAD

**Issue by hector-sab** [junegunn/fzf.vim#1101]
So the issue I am currently facing is that  I want to use ripgrep with the preview with `{'options': ['--layout=reverse', '--info=inline']}` and also I want to use `{'options': '--delimiter : --nth 2..'}`. However, when combining them it results in the error below.

```bash
Error running '/home/hector/.local/share/nvim/plugged/fzf/bin/fzf' '--color=bg+:#3c3836,bg:#282828,spinner:#fabd2f,hl:#fabd2f,fg:#ebdbb2,header:#665c54,info:#83a598,pointer:#83a598,marker:#fe8019,fg+:#ebdbb2,prompt:#a89984,hl+:#fabd2f'
'--ansi' '--prompt' 'Rg> ' '--multi' '--bind' 'alt-a:select-all,alt-d:deselect-all' '--delimiter' ':' '--preview-window' '+{2}-5' '--color' 'hl:4,hl+:12' '--delimiter : --nth 2..' '--layout=reverse'
'--info=inline' '--preview' ''\''/home/hector/.local/share/nvim/plugged/fzf.vim/bin/preview.sh'\'' {}' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimLveIqU/2
```

If I run this command directly in my terminal, it will work (minus the preview for each result).
```bash
rg ""| /home/hector/.local/share/nvim/plugged/fzf/bin/fzf --color="bg+:#3c3836,bg:#282828,spinner:#fabd2f,hl:#fabd2f,fg:#ebdbb2,header:#665c54,info:#83a598,pointer:#83a598,marker:#fe8019,fg+:#ebdbb2,prompt:#a89984,hl+:#fabd2f" --ansi --prompt 'Rg>' --multi --bind alt-a:select-all,alt-d:deselect-all --delimiter : --preview-window +{2}-5 --color hl:4,hl+:12 --delimiter : --nth 2.. --layout=reverse --info=inline --preview ''\''/home/hector/.local/share/nvim/plugged/fzf.vim/bin/preview.sh'\'' {}' --no-height --expect=ctrl-v,ctrl-x,ctrl-t
```

This is what I am trying to add to my vim. Using only the delimiter or the layout+info work. It's just the combination of all that results in the issue.
```vim
command! -bang -nargs=* Rg
    \ call fzf#vim#grep('rg --column --line-number --no-heading --color=always --smart-case '
    \ . (len(<q-args>) > 0 ? <q-args> : '""'), 0,
    \ fzf#vim#with_preview({'options': ['--delimiter : --nth 2..', '--layout=reverse', '--info=inline']}), <bang>0)
```
For further debugging I am a little lost after here. So I would appreciate any help.

- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by junegunn** [comment]
If you pass fzf options as a list, each element of the list is recognized as a separate command-line argument. So writing `['--delimiter : --nth 2..', '--layout=reverse', '--info=inline']` is same as running fzf like so

```sh
fzf "--delimiter : --nth 2.." "--layout=reverse" "--info=inline"
```

which should of course fail.

Try one of these:

- `{'options': ['--delimiter', ':', '--nth', '2..', '--layout=reverse', '--info=inline']}`
- `{'options': ['--delimiter=:', '--nth=2..', '--layout=reverse', '--info=inline']}`
- `{'options': '--delimiter : --nth 2.. --layout=reverse --info=inline'}`
