### ISSUE TITLE
Change up/down behavior for Rg?

### ISSUE THREAD

**Issue by fzf** [junegunn/fzf.vim#1103]
I am hoping that this is an easy fix. I would like to change the behavior from `ctrl-j` and `ctrl-k` for up/down arrows to `ctrl-h` and `ctrl-t` because I type dvorak. I would think that the following would do the trick:

```
let g:fzf_action = {'ctrl-t': 'up', 'ctrl-h': 'down'}
```

With `:FZF` this will throw this error `Not an editor command: down` and it seems to do nothing when using `:Rg`

- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by junegunn** [comment]
```vim
" Non-default version of g:fzf_action. Replaced ctrl-t to alt-t.
let g:fzf_action = {
  \ 'alt-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

let $FZF_DEFAULT_OPTS = '--bind ctrl-t:up,ctrl-h:down'
```
