### ISSUE TITLE
No Rg preview in Windows 10

### ISSUE THREAD

**Issue by lordherp** [junegunn/fzf.vim#1104]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello,

My laptop is running on Windows 10 and I'm on Neovim v0.5.0. My issue is I can only see the preview window in the :Files command , but nothing shows up in :Ag or :Rg or in any of the other commands even when i use fzf#vim#with_preview() function. 

Is there anyway I can enable the preview window in Rg, Buffers and in the other commands? The problem persists in minimal config as well. 

These are the options i'm using in my vimrc. :Files works fine but :Rg doesnt. 

`
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview','bat --color=always --style=header,grid --line-range :300 {}']}, <bang>0)`

`command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case -- '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)`

**Comment by ayushxx7** [comment]
+1 This issue started happening with me as well. It used to work, then one day it stopped working. I have been looking for the answer today and finally decided to raise the issue. 

I tried checking the error message. [This error is shown](https://prnt.sc/u6f430) when I type `:echo errmsg` after running `:Rg`. However, this error message also appears after running `:Files` (which is working correctly).

**Comment by ayushxx7** [comment]
@lordherp @junegunn @janlazo 
It is working on this commit hash: 23dda8602f138a9d75dd03803a79733ee783e356.
[Rg Preview](https://prnt.sc/u6fek7) 
[Buffers Preview](https://prnt.sc/u6fgef)

Temporary Fix:
Change this: 
```Plug 'junegunn/fzf.vim'```
to:
```Plug 'junegunn/fzf.vim', { 'commit': '23dda8602f138a9d75dd03803a79733ee783e356'} " fzf mappings.```

Thanks, Junegunn for this [PR](https://github.com/junegunn/vim-plug/pull/316). and associated tests, looking at which I came to know how to install a plugin on a specific commit hash.

**Comment by lordherp** [comment]
Hi, may I know whats your default terminal inside Vim? also which version of bash you are using on your system (for preview.sh)?

**Comment by michal-h21** [comment]
I think [a similar issue](https://github.com/michal-h21/vim-zettel/issues/58) happened with [Vim-zettel](https://github.com/michal-h21/vim-zettel). I couldn't reproduce this issue on my home machine, but then I experienced it on another machine that was not updated for some time. I also found that examples in FZF.vim's README that use preview window didn't work. 

I've found that it started with 4145f53f3d343c389ff974b1f1a68eeb39fba18b, specifically with this change on line 747:

      '--delimiter', ':', '--preview-window', '+{2}-5',

Searching started to work when I commented it out. 

Later I found that FZF version 21 was installed on that machine, and update to the version 22 fixed the issue for me. One user still reports this issue even with FZF 22 though.

**Comment by ayushxx7** [comment]
@lordherp I am using Command Prompt. I don't have any bash setup other than Git bash but it is not picked up by my Vim installation. I use Gvim. I don't think bash is needed. See this [screenshot](https://prnt.sc/u84ar2). Here, I get a warning: `bash in not found in path`. 
I guess I'll try adding it in the path and see if it makes a difference.

**Comment by ayushxx7** [comment]
I added the Git bash executable in Path. This is what it looks like now: https://prnt.sc/u84g7q. 
No error message, but the bash path is eating up my screen without any significant benefit. Is that how it is supposed to look like?

**Comment by lordherp** [comment]
[
![image](https://user-images.githubusercontent.com/67761173/91644309-0ec54200-ea3b-11ea-916a-120885a64d02.png)
](url)

Mine looks like this. No preview. I have Bash in path.

**Comment by ayushxx7** [comment]
Hi, looks like you don't have the properly vimrc configuration. 
```
let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Todo', 'border': 'sharp' } } 
" popup window config

" let g:fzf_layout = { 'window': 'vs' } 
" split-screen config
```
- Popup window config: This one will give you a proper popup window, but the latest version of Vim must be installed. (I used chocolatey to install the latest version of Vim last night, and now my preview window shows up as a popup. 
![image](https://user-images.githubusercontent.com/16764027/91653790-542c5280-eac1-11ea-8179-e917edbffc03.png)

- Split-Screen config will look like my previously shared screenshots. 


# Adding my full config for fzf below:
```
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Enable per-command history.
" CTRL-N and CTRL-P will be automatically bound to next-history and
" previous-history instead of down and up. If you don't like the change,
" explicitly bind the keys to down and up in your $FZF_DEFAULT_OPTS.
let g:fzf_history_dir = '~/.local/share/fzf-history'

map <C-f> :Files<CR>
map <leader>b :Buffers<CR>
nnoremap <leader>g :Rg<CR>


let g:fzf_tags_command = 'ctags -R'
" Border color
let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Todo', 'border': 'sharp' } }
" let g:fzf_layout = { 'window': 'vs' }
let $FZF_DEFAULT_OPTS = '--layout=reverse --info=inline'
let $FZF_DEFAULT_COMMAND="rg --files --hidden"


" Customize fzf colors to match your color scheme
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

"Get Files
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)


" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

" Git grep
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)
""""""""""""""
```

**Comment by Mte90** [comment]
Just as hint on debian sid I have 0.20.
I fixed the issue going on `/.vim/bundle/fzf/bin/` where I had fzf 0.17, removed that file and downloaded new binary from https://github.com/junegunn/fzf-bin/releases/tag/0.22.0 and put in that folder.
This didn't require and plugin change or commit.

**Comment by lordherp** [comment]
[
<img width="960" alt="Screenshot_56" src="https://user-images.githubusercontent.com/67761173/91750936-3562b480-ebc4-11ea-8cb8-060ad251f85b.png">
](url)

Ok I'm happy to report that I solved my issue. The problem was in the preview.sh, bash complains if there are too many spaces in that file. After deleting all spaces and fixing a EOF error in preview.sh the preview works fine now. Thanks everyone who helped.

**Comment by ayushxx7** [comment]
@lordherp are you using the latest version or are you using the commit hash?

**Comment by lordherp** [comment]
I'm using the commit hash. The latest will probably work too but I'm not eager to find out :D

**Comment by ayushxx7** [comment]
@lordherp since you are using the commit hash, it would be better to keep this issue open, so that it can be fixed in a later version of the plugin.

**Comment by junegunn** [comment]
@ayushxx7 What's your `fzf --version`? (see https://github.com/junegunn/fzf.vim#dependencies)

**Comment by ayushxx7** [comment]
@junegunn thanks, I was using fzf v0.21. 
I have updated to v0.22:  `choco upgrade fzf` 
Updated plug-config: `Plug 'junegunn/fzf.vim'`

All working well now!

**Comment by JasonMFry** [comment]
fwiw, updated to nvim 0.5 yesterday, today I noticed `:Ag` wasn't working, was getting this error in the preview window: `invalid preview window layout: +{2}-5`.

In the command line I was getting this error `Error running '/Users/j/.fzf/bin/fzf'  '--ansi' '--prompt' 'Ag> ' '--multi' '--bind' 'alt-...,ctrl-x,ctrl-t --no-height > /var/folders/p6/a/bunch/of/junk`, but this fixed it for me:

> Temporary Fix:
> Change this:
> `Plug 'junegunn/fzf.vim'`
> to:
> `Plug 'junegunn/fzf.vim', { 'commit': '23dda8602f138a9d75dd03803a79733ee783e356'}`

**Comment by junegunn** [comment]
Please open another issue if you still have the problem even after you make sure that you have fzf 0.22.0
