### ISSUE TITLE
g:fzf_buffers_jump doesn't jump buffers

### ISSUE THREAD

**Issue by jsit** [junegunn/fzf.vim#1105]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

### Reproducing:

1. Start Vim with a minimal configuration:
    `vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`
1. Execute `:let g:fzf_buffers_jump=1`
1. Execute `:Files` and open a file
1. Open a new tab
1. Execute `:Files` and open a second file (different from the first)
1. Execute `:Files` and open the first file again
1. The first file is opened in the second tab; you now have two tabs open, each with a window on the same buffer. **Expected behavior:** opening the first file again should jump you to the first tab, with the window on the buffer with the first file.

Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug  2 2020 00:45:48)
macOS version
Included patches: 1-1350
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
```

**Comment by junegunn** [comment]
`g:fzf_buffers_jump` only applies to `Buffers` command as noted on the documentation.

**Comment by jsit** [comment]
Ah, my mistake:

```
" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1
```

I didn't realize `[Buffers]` meant this was limited to this command, only that it concerned buffers.
