### ISSUE TITLE
undefined variable error on :Files command

### ISSUE THREAD

**Issue by dfontenot** [junegunn/fzf.vim#1106]
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [ x] I have searched through the existing issues

fzf 0.22.0 (built from that tag on the repo)
fzf.vim latest from git
NVIM v0.4.3
Ubuntu 20.04
ag is installed
bat is installed

I am getting some errors when I invoke the :Files command

```
Error detected while processing function <SNR>81_p[3]..fzf#vim#with_preview:
line   44:
E117: Unknown function: fzf#shellescape
E15: Invalid expression: fzf#shellescape(s:bin.preview)
line   46:
E121: Undefined variable: preview_cmd
E15: Invalid expression: ['--preview', preview_cmd.' '.placeholder]
Error detected while processing function fzf#vim#files[15]..<SNR>126_fzf[18]..<SNR>126_wrap:
line   12:
E117: Unknown function: fzf#wrap
E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#files[15]..<SNR>126_fzf:
line   18:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(s:wrap(a:name, merged, bang))
```

**Comment by junegunn** [comment]
Please read through https://github.com/junegunn/fzf.vim#installation
