### ISSUE TITLE
Add hidden files to specific custom :Files command

### ISSUE THREAD

**Issue by lyndhurst** [junegunn/fzf.vim#1107]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi,

Even though I am not fluent at all in Vim, I did search and spend a lot of time working on many `fzf` configurations, and I managed to get everything I wanted working so far.

I have a few `fzf#vim#files` custom commands, but I cannot figure out how to pass `fzf` command options. For example, I have a command like this:
```
command! -bang -nargs=? -complete=dir ConfFiles
     \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'dir': '~/Projects/conf'}), <bang>0)
```
I cannot figure out how to list hidden files and directories. With `fzf#vim#grep`, it is easy, since the `rg` command is passed to the custom command.

I have set `let $FZF_DEFAULT_COMMAND='fdfind --exclude .git --type f --hidden'`, and it is working fine, but, by design applies to all other `fzf` commands. It is not an ideal solution for me since, I have other custom commands that are better off not showing hidden files.

Is there a way to apply this `--hidden` flag to specific commands only?

**Comment by junegunn** [comment]
You can add `source` command to your spec dictionary.

https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

**Comment by lyndhurst** [comment]
I had read that part a few times, and did not figure it out myself. That made me feel dumb, but everything works fine now.
Sorry to have wasted your time, and thank you for your patience.
