### ISSUE TITLE
[Feature request]: Integration of pdfgrep

### ISSUE THREAD

**Issue by codemeleon** [junegunn/fzf.vim#1108]
Hi,
Could you please integrate [pdfgrep](https://pdfgrep.org/) as part of fzf, to search text inside PDF files directly from VIM, like Ag and Rg? It will be really useful for research document writing.

Thank you.

**Comment by junegunn** [comment]
You can write your own commands using the functions provided by fzf and fzf.vim. Please read through the documentation.
