### ISSUE TITLE
files open in new buffer but spawn new split window

### ISSUE THREAD

**Issue by babygau** [junegunn/fzf.vim#1109]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

hi, i wanna open new file in current buffer window and got it work with the follow
```
" default fzf layout
" - down / up / left / right
let g:fzf_layout = { 'down': '~40%' }
let g:fzf_action = { 'enter': 'e' }
" jump to existing buffer if possible
let g:fzf_buffers_jump = 1
```
however, whenever file is opened using `enter` key, fzf spawns/creates a new split window along. i had to close that window with `<c-w>c` everytime opening files from `fzf`. how to fix that?

**Comment by junegunn** [comment]
Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

And why did you add `let g:fzf_action = { 'enter': 'e' }`?

**Comment by babygau** [comment]
@junegunn thank you for your reply, because i had that weird issue so i put `let g:fzf_action = { 'enter': 'e' }` to force open it however it didn't help

for your information, i coudln't produce the issue anymore, strange that it only happened to `fzf`. have you got any idea what setting could give me this bug? i used `vim-grepper` and that worked as expected to me, i also remove `set sb spr` just in case but no luck

**Comment by babygau** [comment]
i think i found the culprit

```
 " neovim terminal settings
 if has('nvim')
 	autocmd TermOpen * setlocal modifiable
 	autocmd TermClose * buffer #
 endif
```
remove this give `fzf` to normal behavior.
