### ISSUE TITLE
Up and down not working in :Buffer selection

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [junegunn/fzf.vim#1110]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

---

Inside the buffer (`:Buffer`) window keys it's not possible to select the buffer with up and down keys. 
This isn't the case for `:Files`. 

## Steps to reproduce

```
wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod 755 nvim.appimage

cat > init.vim << EOF
call plug#begin('./plugins')
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
call plug#end()
EOF

./nvim.appimage -u init.vim --headless +PlugInstall +qa

# Start nvim
./nvim.appimage -u init.vim
   :e buffer1
   :e buffer2
   :Buffer
   # The menu pops up but pressing the arrow keys doesn't change anything
```

![bug](https://user-images.githubusercontent.com/1640260/91715389-d71adf00-eb8d-11ea-854b-0baf9f6eaad0.gif)

**Comment by junegunn** [comment]
That's because there is no point of running `Buffers` command to select the current buffer. By disallowing the first item, which is the current buffer, we can easily switch between two buffers using `Buffers` without having to press up arrow every time.
