### ISSUE TITLE
Buffers gives error after updating the plugin

### ISSUE THREAD

**Issue by SalahuddinAsh** [junegunn/fzf.vim#1115]
Everything was working until I run `:PlugUpdate`. While updating I got this error at the end:

`Post-update hook for fzf .. Failed to download fzf: /home/user/.vim/plugged/fzf/install --bin`

Then when I run `:Buffers` it gives me the following error

```
Error running cat '/tmp/vABPtBs/76'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n' '2,1..2' '--prompt' 'Buf> ' '--query' '' '--preview-window' '+{2}-5' '--preview-window' 'right' '--previ
ew' ''\''/home/nt0x/.vim/plugged/fzf.vim/bin/preview.sh'\'' {1}' --expect=ctrl-v,ctrl-x,ctrl-q,ctrl-t --height=24 > /tmp/vABPtBs/75 
```

I'm running on `Debian 9` using `Vim 8.2`

**Comment by junegunn** [comment]
Upgrade your fzf to 0.22.0.
