### ISSUE TITLE
Neovim floating window issue when using the combination of fzf.vim and fern.vim

### ISSUE THREAD

**Issue by bluz71** [junegunn/fzf.vim#1118]
Hello,

Issue happens with the Neovim 0.4.4 and 0.5 HEAD.

This is a minimal `init.vim` Neovim configuration to trigger the issue:

```viml
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

set mouse=a

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'lambdalisue/fern.vim'
call plug#end()

let g:fzf_layout = { 'window': {
            \ 'width': 0.9,
            \ 'height': 0.7,
            \ 'border': 'sharp' } }
```

Steps to produce the issue:

1) `:Fern . -drawer -width=35`

2) `:Files`

This will be the result, notice the fzf border is not rendering correctly:

![Neovim](https://user-images.githubusercontent.com/11382509/92350701-1e204b80-f11d-11ea-91ea-8bee90df8038.png)

Interesting if one changes focus away from the fern file drawer and into the main window, the issuing of `:Files` will now render correctly:

![Neovim_2](https://user-images.githubusercontent.com/11382509/92350766-4ad46300-f11d-11ea-9797-3b01d9cc3a4e.png)

Notice the full border around fzf this time.

Is this a bug with [fern.vim](https://github.com/lambdalisue/fern.vim) or maybe Neovim? I don't know, I am coming here first since fern.vim is interacting weirdly with fzf.vim and causing it to sometimes not render the floating window border correctly.

**Comment by dbatten5** [comment]
did you manage to get this fixed? i've also got an issue with my preview window not showing borders 
![image](https://user-images.githubusercontent.com/17271241/100443576-dbc63500-30a1-11eb-93ba-1dc797b5d610.png)
although i don't have fern.vim installed

**Comment by bluz71** [comment]
No fix at the moment, sorry.

**Comment by bluz71** [comment]
Upgraded to Neovim 0.5 and upgraded all plugins.

I am not seeing this issue any more.

Resolving.
