### ISSUE TITLE
:Buffers gives Error running cat '/tmp/nvimktGzMR/7'|'fzf' ...

### ISSUE THREAD

**Issue by mangelozzi** [junegunn/fzf.vim#1119]
- [x] I have fzf 0.22.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Notes:
- I install FZF via apt (`sudo apt install fzf`)
- In Neovim `:!which fzf` prints out `/usr/bin/fzf`
- `echo $FZF_DEFAULT_OPTS` and `echo $FZF_DEFAULT_COMMAND` both print nothing.

# Start Vim with a minimal configuration

```
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```
...works but this does not:
```
    let plugdir = fnamemodify($MYVIMRC, ":p:h") . "/tmp/vim-plug"
    call plug#begin(plugdir)
    Plug 'junegunn/fzf'
    Plug 'junegunn/fzf.vim'
    call plug#end()    
```
`/tmp/vim-plug ` has 777 permissions (recursively).

# The Error
Commands like `:Files`, `:GFiles`, and `:Lines` work for me.
However with `:Buffers` I get the error (the FZF windows pops up for a split seconds then disappears):
```
Error running cat '/tmp/nvimktGzMR/7'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n' '2,1..2' '--prompt' 'Buf> ' '--query' '' '--preview-window' '+{2}-5' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimktGzMR/6
```

The following works in bash (trimmed off about half the args):
```
'/tmp/nvimktGzMR/7'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n' '2,1..2'
```

This does not work in bash (added back the `--prompt` option):
```
'/tmp/nvimktGzMR/7'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n' '2,1..2' '--prompt'
```

If I try the full command in bash (as `root`):
```
'/tmp/nvimktGzMR/7'|'fzf'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n' '2,1..2' '--prompt' 'Buf> ' '--query' '' '--preview-window' '+{2}-5' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimktGzMR/6
ERROR:
-bash: /tmp/nvimktGzMR/7: Permission denied
invalid preview window layout: +{2}-5
```
I checked the permissions:
```
root@dev:/home/me# ll /tmp/nvimktGzMR/7
-rw-rw-r-- 1 me me 193 Sep  8 19:27 /tmp/nvimktGzMR/7
```

`echom g:fzf#vim#buffers` prints out (for example):
```
{'1': 12360.018428, '3': 12811.011122, '4': 12355.656257, '10': 12821.987763, '6': 12784.822246, '14': 12889.25095, '78': 12815.698232}
```

Any ideas of things to try or look into?

**Comment by junegunn** [comment]
> I have fzf 0.22.0 or above

You sure about this?

**Comment by mangelozzi** [comment]
> > I have fzf 0.22.0 or above
> 
> You sure about this?

Oh man, that was it. Thanks so much! I have spent to much time on it. I re-installed it the same day before posting this, so I thought it would be the latest. I forgot the Ubuntu repo could be out of date. Is there a way to update the debian/ubuntu package version?

**Comment by junegunn** [comment]
I recommend that you just follow the official instruction which guarantees that you have the latest binary.

https://github.com/junegunn/fzf.vim#using-vim-plug
