### ISSUE TITLE
Certain colours in :Buffers and :Lines not customisable

### ISSUE THREAD

**Issue by colepeters** [junegunn/fzf.vim#112]
Hi there — thanks so much for your work on FZF and FZF.vim, great work! I’ve only just started exploring it tonight, but I’m loving how fast it is compared to some CTRL-P and other fuzzy finders.

There’s a small issue I can't seem to resolve. When running `:Buffers` or `:Lines`, there are two columns of text which I cannot seem to customise, even through the `FZF_DEFAULT_OPS`:

- The first column's number (which is always `1`, I’m not sure what this is) is always a dark blue, which is hard to read on darker backgrounds.
- The second number (the line number) is always a very bright yellow which is reeeeally bright ;)

<img width="1440" alt="screen shot 2016-04-05 at 22 37 15" src="https://cloud.githubusercontent.com/assets/1713932/14298823/f955c3a4-fb7e-11e5-9c02-92df2cc43043.png">

These colours also aren't coming from my iTerm colour scheme (as far as I’m aware, at least — neither of these colours are specified in it).

For what it’s worth, I’m working in Neovim and iTerm2 2.9.x on OS X 10.11.4. iTerm is setup as `xterm-256color`.

Do you have any idea how I might be able to configure these colours? (And also, what is that first column's number representing?)

Thanks very much in advance.

**Comment by colepeters** [comment]
Update: Apologies, but this may be related to the same issue brought up [here in #76](https://github.com/junegunn/fzf.vim/issues/76#issuecomment-180771902).

**Comment by junegunn** [comment]
I'll look into it when I get some time. The idea is to use the colors of the current color scheme is possible instead of using one from the basic 16 ansi color palette.

**Comment by junegunn** [comment]
> what is that first column's number representing?

Buffer number.

**Comment by colepeters** [comment]
@junegunn Thanks! I definitely like this idea of using the current Vim colour scheme if possible. Will be sure to follow that issue as well.

**Comment by junegunn** [comment]
I updated the code to pick colors from the current color scheme, it's not actually configurable yet, but it should look better than before.

**Comment by colepeters** [comment]
@junegunn Thanks for the update. I’ve added the bit of Vimscript mentioned in the readme, however I’m not seeing any difference in the colours. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/1713932/14403721/1db0e14c-fe5a-11e5-9a4e-3cf2c844f3f4.png)

**Comment by junegunn** [comment]
`g:fzf_colors` is optional, you don't need to add it for the problem discussed here. Can you show me the output of `:hi linenr`?

**Comment by colepeters** [comment]
Sure thing:

```
:hi linenr
LineNr         xxx ctermfg=11 guifg=#455A64
```

**Comment by colepeters** [comment]
@junegunn Based on the above, I’m thinking now that this might be a result of my colourscheme setting some `ctermfg` / `ctermbg` fallbacks for `guifg` / `guibg` improperly. I’m guessing FZF.vim doesn’t make use of `gui` colours?

**Comment by junegunn** [comment]
Hmm, fzf is a terminal program that supports 256 ansi colors. I expected `synIDattr(synIDtrans(hlID('linenr')), 'fg')` to return a numeric ansi code, and it does so on Vim, but it looks like on neovim with truecolor enbled it returns the color in `#RRGGBB` form. We can at best approximate the color in 256-color palette. I think about it.

For the time being consider setting up a better color scheme for your terminal:
https://github.com/mbadolato/iTerm2-Color-Schemes

**Comment by colepeters** [comment]
Interesting! Thanks very much for looking into this. :)

**Comment by junegunn** [comment]
Please check if 513ed1f helps.

**Comment by colepeters** [comment]
@junegunn Looks like it has! (See screenshot below.) Thanks a lot!
![image](https://cloud.githubusercontent.com/assets/1713932/14461792/04d9783c-00bc-11e6-846c-13c0d3d2e00e.png)

**Comment by junegunn** [comment]
Line numbers still are not shown in the color used in the buffer. That's probably because the color scheme you use only defines GUI colors.

**Comment by colepeters** [comment]
@junegunn Indeed — I’ve opened an issue with the colour scheme’s maintainer to investigate why the colours aren’t being set correctly. Thanks for you help on this!

**Comment by junegunn** [comment]
A GUI color scheme doesn't necessarily have to set cterm colors (from the limited 256-color palette). So we can't fault it.

**Comment by colepeters** [comment]
Yup, agreed. :)
