### ISSUE TITLE
what is this????

### ISSUE THREAD

**Issue by tamis-laan** [junegunn/fzf.vim#1123]
When I use the `:FZF` command I get a weird string in the search results (see attached image).
![whatisthis](https://user-images.githubusercontent.com/3178666/92992745-7bd1e080-f4ed-11ea-934f-3fd69973bb9f.png)
Not sure where this is coming from, wondering if it is related to FZF itself?

I'm using FZF version: 0.21.0 (b0673c3)

- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

> - Make sure that you have the latest version of fzf and fzf.vim

Installed through vim `PlugUpdate fzf` returns `- fzf: Already up to date.` 

> - Check if your problem is reproducible with a minimal configuration

Using the following configuration:
```
" [ PLUGINS ] 
call plug#begin('~/.vim/plugged')
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }         "Install fzf
    Plug 'junegunn/fzf.vim'                                     "Install fzf for vim 
call plug#end()

" [ PLUG-IN fzf ]
let g:fzf_layout = {'window':{'width':0.9,'height':0.9}}
let g:fzf_buffers_jump = 1 " Jump to the existing window if possible
let $FZF_DEFAULT_COMMAND = 'ag --ignore .git --ignore node_modules -l -g ""'
```
Using the command `:FZF` generates the same problem.

**Comment by tamis-laan** [comment]
Hope this helps!

**Comment by junegunn** [comment]
> I'm using FZF version: 0.21.0 (b0673c3)

You should use the latest version, not that one.

**Comment by tamis-laan** [comment]
I'm unable to install the latest version using: 
`    
Plug 'junegunn/fzf', { 'do': './install --bin' }
`
Plug tells me fzf is up to date, but a `fzf --version` tells me I'm on 0.21. I removed fzf and installed it through package management, now I'm on version 0.22.0 (latest if I'm correct). Still the problem persists. I also tried:
`vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`
and that works, using `:FZF` the problem goes away.

**Comment by tamis-laan** [comment]
I have also tried removing `~/.vim/*` and `~/.local/share/nvim/*` in order to start with a clean slate. Installed Plug and a minimal FZF setup, however the problem persists. 

Strange given that `vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)` does work.

**Comment by junegunn** [comment]
Then you'll have to find a setting in your configuration file that's causing the problem.

https://github.com/junegunn/fzf/issues/1415 might be related.

**Comment by tamis-laan** [comment]
Thanks for that ( junegunn/fzf#1415 ) it was the exact same problem!
