### ISSUE TITLE
Can't exit floating preview window

### ISSUE THREAD

**Issue by thekenu** [junegunn/fzf.vim#1126]
- [x] I have fzf 0.22.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

With the latest fzf.vim, I found out that the default layout for preview window is "floating" rather than a "vertical split". The problem I have with the new floating window is that if you open it _twice_, there seems to be no way to exit it cleanly.

I was able to reproduce it on two machines:

1. Enter `:Files` to open a preview window
2. Press Esc to go to visual mode
3. Enter `:Files` to open another preview window
4. Press Esc to go to visual mode, and type `:q` to exit the preview window
5. You've now closed the second preview window, but the first one is still there and there's no way I know of to close it (short of a complete restart of neovim)

I would like to know how to close the redundant preview window, or how to change the preview window back to a split rather than floating.

**Comment by Aljendro** [comment]
I''m having the same problem. You can add the following to vimrc to get previous behaviour

`let g:fzf_layout = { 'down': '~40%' }`

**Comment by Aljendro** [comment]
Managed to trace it back to my own autocommand. Check your TermClose autocommands. In my case I was trying to remove the terminal buffer as soon as the terminal was closed.

**Comment by subnut** [comment]
@thekenu Can't reproduce. Pressing <kbd>Esc</kbd> Closes the popup window completely

**Comment by thekenu** [comment]
Changing it back to `'down'` is sufficient for my use-case. Thanks all.
