### ISSUE TITLE
Disable popup in favor of location window

### ISSUE THREAD

**Issue by ldelossa** [junegunn/fzf.vim#1128]
- [x] I have fzf 0.22.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello, 

Seems like recently fzf.vim began using popup window as default. There are no docs explaining how to disable this and return to the location list previous used. Is this possible?

**Comment by junegunn** [comment]
Did you actually read https://github.com/junegunn/fzf/blob/master/README-VIM.md?

**Comment by ldelossa** [comment]
yeah, those docs show "use a window dictionary", but my vim has no window dictionary defined. 

```
" FZF configuration
map <C-G> :GFiles <CR>
map <C-F> :Files <CR>
nmap <C-B> :Buffers<cr>
nmap <C-S> :Tags<cr>
nmap ; :Buffers<cr>
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Visual'],
  \ 'fg+':     ['fg', 'Visual'],
  \ 'bg+':     ['bg', 'Visual'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

**Comment by junegunn** [comment]
I believe you can find the answer in the document.

**Comment by keathley** [comment]
For anyone else who ends up on this issue, the line in the docs that you're looking for is this:

```
let g:fzf_layout = { 'down': '40%' }
```

**Comment by eugene-komar-bmll** [comment]
It would be really helpful if `g:fzf_layout` description/examples would be present in https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt
