### ISSUE TITLE
Question: How to best implement "pre filter"

### ISSUE THREAD

**Issue by rgrinberg** [junegunn/fzf.vim#113]
I'd like something like `:Files` but one where I can specify an initial list of extensions to accept. For example: `:Files .js`. What would be the correct way to do this? Wrap `fzf#vim#files` myself I'm assuming?

Should I provide the extensions to filter in `-q`?

**Comment by junegunn** [comment]
Hmm, how about simply typing in `.js$ ` after starting the command? If you want to define a variation of the command, you might want to check out `fzf#vim#files(dir, options)` function.

```vim
" Pass initial query
call fzf#vim#files('', {'down': '40%', 'options': '-q".js$ "'})

" Different source command
call fzf#vim#files('', {'down': '40%', 'source': 'find . -type f -name "*.txt" | sed s/^..//'})
```

I recommend that you familiarize yourself with [the basic `fzf#run()` function](https://github.com/junegunn/fzf/wiki/Examples-(vim)), if you aren't already so.

**Comment by rgrinberg** [comment]
Thanks for the prompt reply. Definitely helps. The reason why I just won't type it because there are actually many extensions applicable to some of the filetypes I want to define this command preset for.
