### ISSUE TITLE
Cannot disable preview in `:Buffers`, `:Rg` and similar commands

### ISSUE THREAD

**Issue by bravoecho** [junegunn/fzf.vim#1130]
- [x] I have fzf 0.22.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

The preview is disabled:

*  globally in Vim (`let g:fzf_preview_window = ''`)
* globally in the shell (`FZF_DEFAULT_OPTIONS="... --preview-window=:hidden ..."`)

It's not shown in the shell nor in vim when executing `:Files`, but it's still shown for all the other fzf Vim commands.

I've read a lot of existing issues, and some of them seem to be similar, but none has a resolution that works in my case, even though a couple of them sound related:

* #1010 
* #799 

Below a verbatim extract of my configuration.

Any help or pointers will be greatly appreciated.

**vimrc**

```vim
let g:fzf_layout = { 'down': '~30%' }
let g:fzf_tags_command = 'ctags -R'
let g:fzf_preview_window = ''
let g:fzf_buffers_jump = 0
nmap <C-p> :Files<CR>
noremap <Leader>b :Buffers<CR>
```

**shell** (zsh)

```bash
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--extended --history=$HOME/.fzf_history --color=light --ansi --reverse --info=inline --bind 'ctrl-/:toggle-preview' --preview-window=:hidden --preview='[ -f {} ] && head -n 200 {}'"
[ -n "$(command -v fd)" ] && export FZF_DEFAULT_COMMAND="fd --type file --hidden --follow --color=always --exclude .git --no-ignore-vcs"
[ -n "${FZF_DEFAULT_COMMAND}" ] && export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
FZF_COMPLETION_TRIGGER='~~'
```

This is the output of `:command Buffers` in Vim:

```vim
      Name              Args Address Complete    Definition
 !|  Buffers           ?            buffer      call fzf#vim#buffers(<q-args>, s:p(<bang>0, { "placeholder": "{1}" }), <bang>0)
```

**Comment by junegunn** [comment]
Fixed in master.
You might want to use a setting like this to get optional preview window you can dynamically enable.

```vim
" Preview window on the right side of the window,
" hidden by default, ctrl-/ to toggle
let g:fzf_preview_window = ['right:hidden', 'ctrl-/']
```

**Comment by junegunn** [comment]
And I do not recommend setting preview options in your FZF_DEFAULT_OPTS. See https://github.com/junegunn/fzf#preview-window
