### ISSUE TITLE
`g:fzf_action` is only used by the basic sink function for simple file paths that is injected to the options dictionary by `fzf#wrap`. When you specify a custom sink command or function, the variable is simply ignored. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap for clarification.

### ISSUE THREAD

**Issue by rohanghige** [junegunn/fzf.vim#1131]
`g:fzf_action` is only used by the basic sink function for simple file paths that is injected to the options dictionary by `fzf#wrap`. When you specify a custom sink command or function, the variable is simply ignored. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap for clarification.

_Originally posted by @junegunn in https://github.com/junegunn/fzf.vim/issues/379#issuecomment-414204351_

The specified fzfwrap README doesn't mention about 'fzf_action' being ignored. It would be really helpful to have this as limitation mentioned in README or in a form of warning.

**Comment by junegunn** [comment]
Thanks, I updated the document.
