### ISSUE TITLE
Howto include symlink filenames in fzfFiles output

### ISSUE THREAD

**Issue by yamsu** [junegunn/fzf.vim#1136]
- [X] I have fzf 0.22.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

On Linux systems, is there a way to include symlink file in the fzfFiles search? For example with Ag the '-f' flag allows ag to search through symlinks.
I don't even need fzfFiles to traverse symlink directories but at least symlink files should show up in the search. 
fzf_files_options variable is available but i can't find figure out if this can be updated to include symlinks

**Comment by junegunn** [comment]
As noted on https://github.com/junegunn/fzf.vim#commands, `:Files` simply runs `$FZF_DEFAULT_COMMAND`.

Also see https://github.com/junegunn/fzf#environment-variables.

**Comment by yamsu** [comment]
Thanks it was really obvious when I relooked at the links you provided.
```
export FZF_DEFAULT_COMMAND='fd --follow --type f'
```
This is a great plugin/commandline tool, great job!
