### ISSUE TITLE
Unhelpful error message causing a lot of noise

### ISSUE THREAD

**Issue by bratekarate** [junegunn/fzf.vim#1137]
```
# autoload/fzf/vim.vim
------------------------
14: call s:warn('Preview window not supported (bash not found in PATH)')
```
Is it possible to mute that error message? I don't see a benefit in displaying a message that has to be confirmed every time I startup vim. Especially because I followed the recommended way of the documentation to turn off the preview window with `let g:fzf_preview_window = ''`.

There should not be a (popup with GUI)  warning that warns me about a feature that was purposefully disabled. Might as well get rid o the warning entirely and only document that bash must be in the path.

**Comment by junegunn** [comment]
Do you call `fzf#vim#with_preview` function in your configuration? The message shouldn't appear if you don't do that.

**Comment by bratekarate** [comment]
@junegunn Ah, so this is not the default behaviour. But I don't call it myself. Here is the relevant config:
```vim
...
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf'
...
let $FZF_DEFAULT_COMMAND = 'fd --type f --hidden --follow --exclude .git'
let g:fzf_preview_window = ''
```
Maybe it's the `coc-fzf` plugin, I will try it out in a sec. My apologies if it's not called from fzf itself. I was very puzzled why this function is called. Thanks for your help and the great plugin/program!

**Comment by junegunn** [comment]
> displaying a message that has to be confirmed every time
> There should not be a (popup with GUI) warning that warns me about a feature

I'm confused. It just echoes the message once on the bottom of the page. No confirmation action is required.

**Comment by bratekarate** [comment]
@junegunn Have you tested it with gvim? I am running gvim on windows, and it's a popup.

**Comment by junegunn** [comment]
No, I don't use Gvim so I didn't know about that. That's awful.

**Comment by bratekarate** [comment]
Yes, it's terrible :) I usually don't use gvim at all, but I am forced to use windows at work now...so I'm using gvim because terminal vim on windows seemed harder to setup.
