### ISSUE TITLE
Preview window in Neovim on Windows:  fzf.vim//bin//preview.sh: line 11: syntax error: unexpected redirection

### ISSUE THREAD

**Issue by andis-spr** [junegunn/fzf.vim#1138]
- [X] I have fzf 0.22.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Error message seen in fzf preview window instead of the file preview:
```
C://Users//LOREMI~1//AppData//Local//nvim//plugged//fzf.vim//bin//preview.sh: line 11: syntax: unexpected redirection
```

Corresponding line in `preview.sh`:
```
IFS=':' read -r -a INPUT <<< "$1"
```

Neovim version:
```
C:\Users\LoremIpsum>nvim --version
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

**Comment by andis-spr** [comment]
Environment details to add to this issue:
The `preview.sh` file in this config is interpreted by `bash` provided as a part of `busybox` installed via `scoop` package manager.
https://github.com/ScoopInstaller/Main/blob/master/bucket/busybox.json

I tried yet tried to know if other `bash` implementations for Windows would also fail to work with this script.

**Comment by andis-spr** [comment]
Got a clue on this!
Top - git bash (it works), bottom busybox bash (it doesn't).
https://i.imgur.com/qdAORRm.png

**Comment by andis-spr** [comment]
Resolved!
Steps:
1. Uninstalled `busybox` I had installed via `scoop` (that subsequently removed it's `bash` from Windows `PATH`)
2. Installed `git` & `git-bash` for Windows with selecting option of it's included command-line tools (incl. `bash`) to be exposed in Windows `PATH`

Previews happily work again.
https://i.imgur.com/2O4E1KK.png

Those who also use `chocolatey` package manager can install the 'right' `bash` using:
```choco install git.install --params "/GitAndUnixToolsOnPath"```

**Comment by junegunn** [comment]
Thanks for sharing your solution.

**Comment by lbaiao** [comment]
Hi. After setting the git bash in neovim, I get the following error. Sorry it is portuguese, but I think you can get it. Do you have any idea what may be happing? I already verified that git-bash comes with fzf and ag pre-installed.

BASH SETUP ON INIT.VIM
```
if has("win32")
 let &shell='C:\Program Files\Git\bin\bash.exe'
 let &shellcmdflag = '-c'
 let &shellredir = '>%s 2>&1'
 set shellquote= shellxescape=
 " set noshelltemp
 set shellxquote=
 let &shellpipe='2>&1| tee'
 let $TMP="/tmp"
endif
```

ERROR MESSAGE:
Erro detectado ao processar C:\Users\lucas\AppData\Local\nvim\plugged\fzf.vim\autoload\fzf\vim.vim:
linha   41:
E684: índice da lista fora dos limites: 0
E15: Expressão inválida: split(system('for %A in ("'.s:bin.preview.'") do @echo %~sA'), "\n")[0]
Erro detectado ao processar function fzf#vim#ag[8]..fzf#vim#ag_raw[4]..fzf#vim#grep[24]..<SNR>132_fzf[1]..
<SNR>132_check_requirements:
linha   14:
E605: Exceção não interceptada: Failed to run "fzf --version": []

**Comment by andis-sprinkis** [comment]
Hey @lbaiao , can you try adding Git Bash to path like this in your init.vim?
`let $PATH = "C:\\Program\ Files\\Git\\usr\\bin;" . $PATH`

BTW to followup on solution I wrote above - it's probably not even needed to remove other 3rd party shells from the system if Git Bash is the first `bash` in PATH.

**Comment by lbaiao** [comment]
Hey @andis-sprinkis! It worked! Thanks a lot! Maybe the git bash was not the first bash in my path.

**Comment by hungpham3112** [comment]
Git-bash is already in my path but fzf still said no Bash for preview window. I'm install git with `scoop install git`

**Comment by kesavanm** [comment]
@andis-sprinkis  - adding the following in my `.vimrc` works for `GVim 8.2` on Windows 10!

`let $PATH = "C:\\path\\to\\Git\\usr\\bin;" . $PATH`
