### ISSUE TITLE
Issue opening files/directories with dollar signs in name

### ISSUE THREAD

**Issue by williamho** [junegunn/fzf.vim#114]
```sh
mkdir -p app/dir\$with\$dollar\$signs
echo "hello" > app/dir\$with\$dollar\$signs/hello\$dollar.txt
```

trying to open the above file using fzf.vim ends up opening `app/dir/hello.txt` instead of `app/dir$with$dollar$signs/hello$dollar.txt`, presumably because the dollar signs aren't escaped and are being interpreted as environment variables.

**Comment by netei** [comment]
Some characters have special meaning : (`$`, `|` , `'` ` `) in fzf .

They can't be escaped for now (See https://github.com/junegunn/fzf/issues/444)

**Comment by netei** [comment]
Oh, no you're right, it has to do with vim I think

**Comment by junegunn** [comment]
Thanks for the report. Should be fixed now.
