### ISSUE TITLE
Some Windows issues

### ISSUE THREAD

**Issue by medwatt** [junegunn/fzf.vim#1141]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am using FZF on neovim-qt running on Windows 10. I decided to upgrade the fzf plugin today and noticed that there's something wrong with the color highlighting when searching for file. Please have a look [here](https://i.imgur.com/rpKKYkV.png). I am still using the same theme but the colors have changed for the worse. In the past, the file under the cursor was highlighted in yellow. Now, it's white and not so distinct. Also, matched letters are in light green, which is hard to see.

There are also two other issues that I would like to mention:

1. If I type `Files D:` to scan through the files in my D drive, for some reason, when I open a document, the file path has two backslashes such as D:\\\\ while only one backslash for the rest of the path. I don't understand why this is the case.

2. Sometimes, when I search for a file such as a pdf file from within vim using fzf, I would like to open the file on a dedicated PDF application. I have added an extra trigger as shown below to open the file on the default external application. This works fine except when the path has a space. For example, if the path is `D:\folder1\folder2\file.pdf`, pressing <c-q> works fine. However, if the path is `D:\folder 1\folder2\file.pdf`, it doesn't work.

```vim
let g:fzf_action = {
  \ 'ctrl-q': '!start',
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

Any ideas how to fix these 3 issues ?

**Comment by kelleyma49** [comment]
24-bit color support was added to the Windows version of fzf in https://github.com/junegunn/fzf/pull/2156. tcell was updated to a version that supports 24-bit color.

Try setting the environment variable `TCELL_TRUECOLOR` to `disable` in a shell. Then run the neovim-qt app from that shell so it sees that environment variable and report back to us how the colors look.

**Comment by junegunn** [comment]
> Now, it's white and not so distinct. Also, matched letters are in light green, which is hard to see

Actually, those colors are the default ones, which means, you were seeing the wrong colors in the past, and the latest version fixed the problem. Have you tried running fzf in your shell?

**Comment by junegunn** [comment]
A command in `g:fzf_action` entry expects a regular Vim ex command, and it performs escaping that only works in that context using `fnameescape` function. But for an external command, you should use `shellescape` function, so I believe that's why it doesn't work with files with spaces. See if this works:

```vim
let g:fzf_action = {
  \ 'ctrl-q': { files -> map(files, { _, file -> execute('!start ' . shellescape(file)) }) },
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

**Comment by medwatt** [comment]
> A command in `g:fzf_action` entry expects a regular Vim ex command, and it performs escaping that only works in that context using `fnameescape` function. But for an external command, you should use `shellescape` function, so I believe that's why it doesn't work with files with spaces. See if this works:
> 
> ```viml
> let g:fzf_action = {
>   \ 'ctrl-q': { files -> map(files, { _, file -> execute('!start ' . shellescape(file)) }) },
>   \ 'ctrl-t': 'tab split',
>   \ 'ctrl-x': 'split',
>   \ 'ctrl-v': 'vsplit' }
> ```

Thanks for your reply. This doesn't seem to work. This just opens the terminal (cmd).

**Comment by junegunn** [comment]
I don't have a Windows PC to test it. But you get the idea. You should write your own function for proper escaping.
(You don't have to use a one-line lambda function as above. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#examples)

**Comment by medwatt** [comment]
> I don't have a Windows PC to test it. But you get the idea. You should write your own function for proper escaping.
> (You don't have to use a one-line lambda function as above. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#examples)

@junegunn I've managed to get this to work. But there remains one of the issues I described above that causes some problems. At the moment, when I load a file using the `Files` command, there's a double backslash just after the colon. For example, if I have a file `file.txt` located inside a folder called folder01 in the C drive as: `C:\folder01\file.txt`, when I open it via the `Files`, it gets opened as `C:\\folder01\file.txt`. This causes issues when I try to pass the file name to an external application such as in `!python %`. Is this a bug that `C:\folder01\file.txt`  becomes `C:\\folder01\file.txt` ?

**Comment by junegunn** [comment]
Does this patch fix your problem?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 14d0276..5fa555a 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -283,7 +283,8 @@ function! s:common_sink(action, lines) abort
     let cwd = exists('w:fzf_pushd') ? w:fzf_pushd.dir : expand('%:p:h')
     for item in a:lines
       if item[0] != '~' && item !~ (s:is_win ? '^[A-Z]:\' : '^/')
-        let item = join([cwd, item], (s:is_win ? '\' : '/'))
+        let sep = s:is_win ? '\' : '/'
+        let item = join([cwd, item], cwd[len(cwd)-1] == sep ? '' : sep)
       endif
       if empty
         execute 'e' s:escape(item)
```

**Comment by medwatt** [comment]
> ```diff
> +        let sep = s:is_win ? '\' : '/'
> +        let item = join([cwd, item], cwd[len(cwd)-1] == sep ? '' : sep)
> ```

Yes, it does. Thanks!

**Comment by junegunn** [comment]
Thanks for the confirmation. Patch pushed to master.
