### ISSUE TITLE
Neovim on Windows, fzf 0.23.1: check_requirements error

### ISSUE THREAD

**Issue by andis-spr** [junegunn/fzf.vim#1145]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

After installing the fzf.vim update using Plug
```
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
```
it shows error when checking for fzf executable availability (v. 0.23.1 installed)
https://i.imgur.com/8Oft3xC.png

**Comment by junegunn** [comment]
Possibly related:
- https://github.com/junegunn/fzf/issues/2219

What's the exact output of `:echo string(systemlist('fzf --version'))`?

**Comment by andis-spr** [comment]
> What's the exact output of `:echo string(systemlist('fzf --version'))`?

https://imgur.com/O3hCFbN

**Comment by junegunn** [comment]
8b3ab78 should make things clearer.

**Comment by rpuntaie** [comment]
With regard to https://github.com/junegunn/fzf/issues/2219, note that

```
set shellcmdflag=-ic
echo string(system('echo -n foo'))
echo v:shell_error
```

produce 0 for `v:shell_error`.

`system()` can produce extra output depending on the `shellcmdflag`.
 In the example above this is `(eval):1: can't change option: zle`.
If changing `shellcmdflag` temporarily to `-c` this can be avoided.

**Comment by drazik** [comment]
I had the same error, and when checking the output of `:echo string(systemlist('fzf --version'))`, I saw that it returned an array with a message from my shell (a deprecation warning) and the fzf version (which was higher than 0.23.0).

Making my shell not outputing the deprecation warning fixed the problem for me.

Hope it helps if somebody has the same issue.

**Comment by junegunn** [comment]
@drazik Thanks for sharing your experience. Now bd3a021ec11617c56e6aa95578fee619445b029d should help in such cases.
