### ISSUE TITLE
Execute alt-a on RipGrep term with function

### ISSUE THREAD

**Issue by Moshem123** [junegunn/fzf.vim#1148]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I'm trying to remap `:Rg` to either accept a word or search word under cursor.
```
function s:RipGrepCWORD(...) abort
  let search_word = a:1
  if search_word == ""
    let search_word = expand("<cword>")
  endif
  echom "Searching for " . search_word
  execute "Rg " . search_word
  startinsert
  \<a-a>
  stopinsert
endfunction
command -nargs=? RipGrepCWORD call <SID>RipGrepCWORD("<args>")
nnoremap <c-f> :RipGrepCWORD
```

I want after executing `Rg` to select all matches and open a quickfix window, however the `<a-a>` is not executed.
Is there a normal mode ex-command I can call to select all files?
Thanks.

**Comment by Moshem123** [comment]
Got it working by:
```
function s:RipGrepCWORD(...) abort
  let search_word = a:1
  if search_word == ""
    let search_word = expand("<cword>")
  endif
  echom "Searching for " . search_word
  execute "Rg " . search_word
  sleep 100 m
  call feedkeys("\<c-a>", "n")
endfunction
command -nargs=? RipGrepCWORD call <SID>RipGrepCWORD("<args>")
nnoremap <c-f> :RipGrepCWORD
```

the `sleep` seems a bit like a workaround.
Is there a reliable way to wait for fzf to finish loading the `terminal` window?

**Comment by junegunn** [comment]
No. But if I understood correctly, you should just use the basic `:grep` with `grepprg` setting.

See https://github.com/BurntSushi/ripgrep/issues/425#issuecomment-381446152
