### ISSUE TITLE
Extend BCommits with options

### ISSUE THREAD

**Issue by neerajbadlani** [junegunn/fzf.vim#1149]
- [ X ] I have fzf 0.23.0 or above
- [ X ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ X ] I have read through the manual page of fzf (`man fzf`)
- [ X ] I have searched through the existing issues

I currently use following to override default options : 
```
command! -bang -nargs=* FuzzyMaps
\ call fzf#vim#maps(<q-args>, {'options': ['--no-preview']},<bang>0)
```
However , I cant do same for BCommits and throws an error . 
Is it possible to provide options to Bcommits to override defaults . 

Thanks

**Comment by junegunn** [comment]
```vim
call fzf#vim#buffer_commits({'options': '--no-preview'})
```

works for me.

The good news is that 7d45724fdd323d5eb7d39c8caa2e38e63c5e84a7 will make Commits and BCommits support `g:fzf_preview_window` option and by default, you can toggle their preview windows by hitting `CTRL-/`.

**Comment by neerajbadlani** [comment]
Thanks for quick turnaround , but this doesnt work . I was actually looking for list of options to be available , so i can put in bindings and works . 

```
command! -bang -nargs=* FuzzyBCommits
  \ call fzf#vim#buffer_commits({'options': ['--preview', '--preview-window=right:70%']})
```
Above one doesnt work .

**Comment by junegunn** [comment]
Ugh, that shouldn't work at all. Because you're not passing a preview command:

```sh
# Nope
fzf --preview --preview-window=right:70%
```

**Comment by junegunn** [comment]
Anyway, passing options to `fzf#vim#buffer_commits ` works.

**Comment by neerajbadlani** [comment]
My Bad .. Sorry it works! . Thanks
