### ISSUE TITLE
fzf 0.24 does not work with latest fzf.vim

### ISSUE THREAD

**Issue by runbmp** [junegunn/fzf.vim#1150]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

My .vimrc
```
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
```

My brew:

```
❯ brew info fzf
fzf: stable 0.24.0 (bottled), HEAD
Command-line fuzzy finder written in Go
https://github.com/junegunn/fzf
/usr/local/Cellar/fzf/0.24.0 (17 files, 3.7MB) *
  Poured from bottle on 2020-10-27 at 12:06:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fzf.rb
License: MIT
```

My vim status when invoking `:Files`
`E605: Exception not caught: You need to upgrade fzf. Found:  (/usr/local/Cellar/fzf/0.24.0/bin/fzf). Required: 0.23.0 or above.`

I think the culprit is below. Obviously (brew) is not a valid version number
```
❯ fzf --version
 (brew)
```

```
❯ which fzf
/usr/local/bin/fzf
```

**Comment by alindeman** [comment]
homebrew sets the revision as `brew`, which breaks this check: https://github.com/Homebrew/homebrew-core/blob/6aff73d492351f644ac6f79b750c3b5b890776d3/Formula/fzf.rb#L22

**Comment by junegunn** [comment]
Hmm, right. Homebrew formula needs to be updated like so.

```diff
diff --git a/Formula/fzf.rb b/Formula/fzf.rb
index 286a7cc371..e81938c512 100644
--- a/Formula/fzf.rb
+++ b/Formula/fzf.rb
@@ -19,7 +19,7 @@ class Fzf < Formula
 
   def install
     ENV["GOPATH"] = HOMEBREW_CACHE/"go_cache"
-    system "go", "build", "-o", bin/"fzf", "-ldflags", "-X main.revision=brew"
+    system "go", "build", "-o", bin/"fzf", "-ldflags", "-X main.version=#{version} -X main.revision=brew"
 
     prefix.install "install", "uninstall"
     (prefix/"shell").install %w[bash zsh fish].map { |s| "shell/key-bindings.#{s}" }
```

**Comment by oxysoft** [comment]
I have this issue but am on Linux and do not use brew.

```
> fzf --version
0.24.0 (0d5f862)

> which fzf
/home/nuck/Repositories/fzf/bin/fzf
```

**Comment by natw** [comment]
The latest homebrew version seems to break checks in both the bundled plugin and this one.

For a quick stopgap, bypass the check [here](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L63) (I just added a `return` to the beginning of that func) and [here](
https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L185) (I just commented out that whole `if` block).

Sorry that's not very helpful in the long run, but hopefully that gets someone up and running in the meantime

**Comment by sofubi** [comment]
I also have this issue on Linux, not using brew.

When running `fzf --version` I get nothing back from the command just an empty line.

Which fzf shows that it's in /usr/bin/fzf.

My output in vim is as follows.

```
Error detected while processing function fzf#vim#gitfiles[6]..<SNR>77_fzf[1]..<SNR>77_check_requirements:             
line   14:                                                                                                            
E605: Exception not caught: Failed to run "fzf --version": []                                                         
Error detected while processing function fzf#vim#gitfiles:                                                            
line    6:                                                                                                            
E171: Missing :endif
```

**Comment by junegunn** [comment]
@sofubi It looks like you have to report the issue to the package maintainer. The latest fzf needs to be built with a proper `-ldflags` with version information like so

https://github.com/junegunn/fzf/blob/0d5f862daf45336c12c2f540736b3d7ca396c78d/.goreleaser.yml#L15-L16

In the mean time, I'll find a way to prevent building fzf without a version information.

**Comment by junegunn** [comment]
Homebrew formula is fixed now. But I suspect there are other packages from different distros with the same problem. If you run into this problem, please report it to the package maintainers of your choosing.

**Comment by esn89** [comment]
What about the fzf being installed/built from vim?
```Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }```

This is what I have in my vimrc and it doesn't seem to work

**Comment by junegunn** [comment]
@esn89 

>  it doesn't seem to work

Error message?

**Comment by esn89** [comment]
@junegunn 

Here it is:

```
Error detected while processing function fzf#vim#files[15]..<SNR>44_fzf[1]..<SNR>44_check_requirements:                                                                                      
line   14:                                                                                                                                                                                   
E605: Exception not caught: Failed to run "fzf --version": ['panic: Invalid build: version information missing', '', 'goroutine 1 [running]:', 'main.main()', '^I/Users/esn89/.fzf/main.go:13 
+0x8b']                                                                                                                                                                                      
Press ENTER or type command to continue
```

**Comment by junegunn** [comment]
@esn89 I don't know how you end up with the binary.

- What is the output of `:echo fzf#exec()`?
- Does it help to run `:PlugInstall!` (don't miss `!` at the end)?

**Comment by esn89** [comment]
@junegunn 

I just ran your last command of PlugUpdate! fzf, that fixed it!   Thanks a million.

**Comment by junegunn** [comment]
@esn89 You seem to be on macOS and I'm still curious how you ended up with that `go get` route. Maybe the installer downloaded the binary but, macOS moved it to trash bin for a security reason? 🤔

**Comment by mufasa71** [comment]
On Linux you can downgrade to 0.23

`sudo pacman -U /var/cache/pacman/pkg/fzf-0.23.1-1-x86_64.pkg.tar.zst`

fzf.vim will download new version, and it will start to work again

**Comment by tlvince** [comment]
[Arch Linux bug report](https://bugs.archlinux.org/task/68450).

**Comment by meredrica** [comment]
``fzf --version`` returns an empty string on arch linux, installed via pacman. that doesn't seem right

**Comment by abcalphabet** [comment]
When downgrading `fzf` back to 0.23.1-2, I got the error that 0.24 is required by `fzf.vim`. Should anyone else encounter this problem it can be fixed by updating your .vimrc/init.vim to use commit `4145f53f3d343c389ff974b1f1a68eeb39fba18b` instead of the latest one. If you're using `vim-plug`:

`Plug 'junegunn/fzf.vim', {'commit': '4145f53f3d343c389ff974b1f1a68eeb39fba18b'}`

**Comment by dsifford** [comment]
**Arch Linux users:**

1. Download the PKGBUILD from the commuity repo [here](https://github.com/archlinux/svntogit-community/blob/packages/fzf/trunk/PKGBUILD)
2. Save PKGBUILD.diff (below) to the same directory.
3. Run `patch PKGBUILD PKGBUILD.diff` in that directory.
4. Run `makepkg -si` in that directory.
5. Profit

<details>
<summary>PKGBUILD.diff</summary>
<pre>
diff --git a/trunk/PKGBUILD b/trunk/PKGBUILD
index 50d5e91..aeee79a 100644
--- a/trunk/PKGBUILD
+++ b/trunk/PKGBUILD
@@ -31,7 +31,7 @@ build() {
 	export CGO_CPPFLAGS="${CPPFLAGS}"
 	export CGO_CXXFLAGS="${CXXFLAGS}"
 	export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
-	go build -o fzf .
+	go build -o fzf -ldflags "-X main.version=$pkgver -linkmode external -extldflags \"${LDFLAGS}\""
 }
 
 check() {
</pre>
</details>

**Comment by rodamaral** [comment]
@dsifford it works! But I had to use the [diff file linked](https://bugs.archlinux.org/task/68448?getfile=19374) in Arch's [issue](https://bugs.archlinux.org/task/68448). Your snippet removes the extra white space required in the diff and adds an empty line at the end, which makes the diff command throw:

`patch: **** malformed patch at line 13: check() {`

**Comment by dsifford** [comment]
Whoops! Added the whitespace in.

**Comment by junegunn** [comment]
This will be fixed when they make a new release (even if they don't pass a proper `-ldflags` when building the binaries, see https://github.com/junegunn/fzf/commit/b5e0e29ec6a149fa948c0399af34572d450d3dda)

**Comment by edkv** [comment]
If somebody needs a temporary fix for this while waiting for a new fzf release to be available on your distro, here is a simple wrapper script that does the job for me (name it `fzf` and place somewhere on your `PATH`):

```
#!/bin/bash

if [[ "$1" == "--version" ]]; then
    echo "0.24.0"
else
    /usr/bin/fzf "$@"
fi
```

**Comment by meredrica** [comment]
I personally removed the fzf plugins from vim and downgraded FZF, works again

**Comment by tami5** [comment]
`Error running cat '/tmp/nvim6eHdl4/11'|'fzf'  --prompt "Maps (n)> " --ansi --no-hscroll --nth 1,.. --color prompt:12 --no-height --border=soft --color=border:#282828 > /tmp/nvim6eHdl4/10
`
@junegunn  I'm getting this error after upgrading both fzf and fzf.vim

**Comment by F-star** [comment]
My OS is Windows 10.

```sh
fzf --version
0.23.1 (fc7630a)
```

I debugged the `vim.vim` file and found that the variable `fzf_version`  is empty, so I changed it and script worked:

```vim
let fzf_version = '0.23.1' " matchstr(output[-1], '[0-9.]\+')
```

I guess the regexp had something wrong. Maybe my answer can help you.

**Comment by joaqo** [comment]
Upgrading with vim plug doesn't work also. Keeps downloading version 0.18.0 for some reason.
