### ISSUE TITLE
Where to set FZF border with advanced ripgrep preview? init.vim or .zshrc?

### ISSUE THREAD

**Issue by huyvohcmc** [junegunn/fzf.vim#1154]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

zshrc:
```
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --smart-case --glob "!{.git,node_modules,flow-typed}"'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse'
```

I use advanced ripgrep integration in init.vim:
```
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)
```

The thing is, my fzf popup is always a rectangle shape even though the default value of border is rounded. No matter what I tried for example `--border=sharp`, the popup is always like this:

<img width="1384" alt="Screen Shot 2020-10-29 at 9 34 23 PM" src="https://user-images.githubusercontent.com/17645203/97588032-a68cdf80-1a2e-11eb-8306-64c74c5abb32.png">

I don't think they are rounded or sharp at all.

- fzf: 0.24.1 (brew)
- nvim: 0.5 nightly

**Comment by junegunn** [comment]
Looks round to me, but I can't be sure. Have you tested the option on your shell?

```sh
# Rounded preview border
fzf --height 50% --preview 'cat {}'
# Rounded preview border + Rounded border around fzf
fzf --height 50% --preview 'cat {}' --border
# Rounded preview border + Sharp border around fzf
fzf --height 50% --preview 'cat {}' --border sharp
# Sharp preview border + Sharp border around fzf
fzf --height 50% --preview 'cat {}' --border sharp --preview-window sharp
```

**Comment by huyvohcmc** [comment]
Thanks @junegunn this issue should be closed now. I've never seen a rounded border before so I thought the border radius should be bigger.
