### ISSUE TITLE
Override preview argument

### ISSUE THREAD

**Issue by blayz3r** [junegunn/fzf.vim#1156]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

When I run

```vim
echo fzf#vim#with_preview({'options': ['--color', 'hl:68,hl+:110', '--preview-window', 'sharp', '--preview', 'bat --style=numbers --color=always {}']})
```
I get
```vim
{'options': ['--color', 'hl:68,hl+:110', '--preview-window', 'sharp', '--preview', 'bat --style=numbers --color=always {}', '--preview', 'bash /mnt/c/Users/Me/VIM~1/bundle/fzf.vim/bin/preview.sh {}']}
```
Is it possible to override the preview argument
see https://github.com/junegunn/fzf.vim/issues/975

**Comment by junegunn** [comment]
Any reason you want to apply `fzf#vim#with_preview` even when you provide your own preview command? Looks like you want it to do nothing, and I don't see the point.

**Comment by blayz3r** [comment]
So basically I want to change the preview command for the function below(Rg), my preview script preview.sh seems to always use 
cat...

All the other FZF functions the default options below which is working fine

```vim
let $FZF_DEFAULT_OPTS = "--bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-f:preview-down,ctrl-b:preview-up --preview 'bat --style=numbers --color=always --theme=TwoDark --line-range :500 {} '"
```


```vim
command! -bang -nargs=* Rg
            \ call fzf#vim#grep(
            \ 'rg --column --color=always --line-number --colors "match:fg:white" --colors "match:bg:red" --colors "column:fg:57,143,229" --colors "path:fg:134,204,133" --colors "line:fg:128,128,128" --colors "line:style:bold" '.<q-args>, 1, 
            \   fzf#vim#with_preview({'options': ['--color', 'hl:68,hl+:110', '--preview-window', 'sharp', '--preview', 'bat --style=numbers --color=always {}']}),
            \   <bang>0)
```

**Comment by junegunn** [comment]
> my preview script preview.sh seems to always use
cat...

Any idea why? It works on my system.

**Comment by blayz3r** [comment]
I am not sure bat fine works in the terminal

The command below produces(Windows BTW)
```vim
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'bash /mnt/c/Users/Me/.vim/bundle/fzf.vim/bin/preview.sh {}']}, <bang>0)
```
![image](https://user-images.githubusercontent.com/12205650/97797773-c6b6cd00-1bed-11eb-9ef9-5864a360831f.png)

Only clue is 
![image](https://user-images.githubusercontent.com/12205650/97797780-db936080-1bed-11eb-9eaa-b427764a81c4.png)

**Comment by junegunn** [comment]
No, I mean you'll have to debug preview.sh in this project if it's not working as expected. Since the problem is not reproducible on my side, I can't help you with that.

**Comment by blayz3r** [comment]
I managed to solve the issue, you can't use bat when it is installed via cargo/rust(wsl doesn't source bashrc/zshrc etc)....

I installed bat from apt and sim-linked as per:
![image](https://user-images.githubusercontent.com/12205650/97799159-3cc13100-1bfa-11eb-890a-906b81b52443.png)
