### ISSUE TITLE
API call: Buffer is not 'modifiable'

### ISSUE THREAD

**Issue by yuriescl** [junegunn/fzf.vim#1157]
```
$ nvim --version                                                    
NVIM v0.4.4
$ fzf --version
0.23.1 (fc7630a)
```

NVim init.vim I'm using:
https://gist.github.com/yuriescl/9a1141306e562f1aedff24147ccb73ea

**How to reproduce:**

```
nvim -M
:Files
```

**Expected behavior:**
A small terminal window opens in the middle of the window and allows browsing the results.

**Current behavior:**
This message is displayed as an error:
```
Error detected while processing function fzf#vim#files[15]..<SNR>66_fzf[20]..fzf#run[58]..
<SNR>14_execute_term[3]..<SNR>14_split[14]..<SNR>14_popup[47]..<SNR>14_create_popup:      
line    8:                                                                                
E5555: API call: Buffer is not 'modifiable'                                               
Press ENTER or type command to continue 
```

That error doesn't happen with this approach:
```
nvim -MNu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
:Files
```

**Comment by junegunn** [comment]
You'll have to bisect your configuration and find which part of it is causing the issue.

**Comment by yuriescl** [comment]
Apparently this was fixed recently.
I deleted `~/.local/share/nvim`, changed my `init.vim` to:
```
call plug#begin(stdpath('data') . '/plugged')
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
```
then reinstalled the plugins.

Using the latest versions of fzf and fzf.vim fixed the issue.
