### ISSUE TITLE
`:Windows` doesn't focus the selected window

### ISSUE THREAD

**Issue by meribold** [junegunn/fzf.vim#116]
e9187959bae0b0579f102ee3116314d97cb98371 seems to have broken the `:Windows` command on my system.  The fzf buffer itself works but when I hit Return the selected window isn't focused.  When I checkout 1ed70a995d3c03b66b96c726a29d0219f059f4a1 I don't have that issue.

I tested this with Neovim 0.1.2 and Vim 7.4.

**Comment by junegunn** [comment]
Thanks.
