### ISSUE TITLE
ctrl-z during :Rg doesn't work and gives problems.

### ISSUE THREAD

**Issue by DZ84** [junegunn/fzf.vim#1161]
ctrl-z during :Rg gives problems. I get into an empty overlayed window/modal where I cannot do anything other than type. I can exit the empty window with ctrl-w ctrl-c.

I have the latest fzf and fzf.vim. I tried it with a minimal vimrc.

**Comment by DZ84** [comment]
Is it me, or is this fixed?

**Comment by junegunn** [comment]
I believe https://github.com/junegunn/fzf/commit/474c1f5e32cc56653b1a1be697abf92537e4e28f fixed this by simply not allowing CTRL-Z.
