### ISSUE TITLE
fzf#install() does not install fzf binary

### ISSUE THREAD

**Issue by horseinthesky** [junegunn/fzf.vim#1163]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Manual install with `PlugInstall` says
```
Running fzf installer ...
Post-update hook for fzf ... OK
```
but does not install the binary and shell completion files.

My config:
```
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
```

Old way works:
```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
```

NVIM 0.4.3 in Ubuntu 20.04.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf#as-vim-plugin

> `fzf#install()` makes sure that you have the latest binary

It only downloads the latest binary under `bin` directory of the plugin, and it doesn't do anything beyond that. It's equivalent to `./install --bin`. On the other hand, `./install --all` downloads the binary and changes the shell configuration. You can still use the old way if you want vim-plug to install fzf on your system.
