### ISSUE TITLE
Request: Is there a way to make fzf remember the query buffer for the next invocation?

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf.vim#1165]
Sometimes I blow through the process too fast and select the wrong file to open, or assume that what i will type will pick the right one when it doesn't (barely), and I have to reopen and re-type again. I wish there was a way to set up another bind that will recall the state of what was typed for the query.

**Comment by junegunn** [comment]
Yes.

**Comment by unphased** [comment]
My bad for ignoring the template. The answer is this is bound to ctrl+P. Glad I finally realized that this is possible.
