### ISSUE TITLE
Limit number of lines and center content in preview window

### ISSUE THREAD

**Issue by savchenko** [junegunn/fzf.vim#1169]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

As we are passing `$CENTER` and size of the preview window is known, it might be possible to:
1. Limit number of lines to the size of the preview window.
2. Center the `$CENTER` (no pun intented).

Ideally, make this optional.

**Comment by junegunn** [comment]
I haven't paid attention to the code path as I have `bat` installed. I'll see if the code is still working as expected when I get a chance. Having said that, install bat and you'll have much better results.

**Comment by savchenko** [comment]
Thanks for your reply. I do have `bat` installed and was thinking about utilising its `--line-range <N:M>` to limit the range.

_Example:_
1. User has searched for "blah" which was found at line №20.
2. With current parameters, preview window is estimated to fit 30 lines.
3. Pass `--line-range <10:30>` to the `bat` with line №20 centered vertically.

**Comment by junegunn** [comment]
Do you have the latest version? It sets the scroll offset so that the focused line is displayed at the center of the windows.

**Comment by savchenko** [comment]
> Do you have the latest version? It sets the scroll offset so that the focused line is displayed at the center of the preview window.

You are right, I've had an old one sourced by mistake.
