### ISSUE TITLE
why the height in options not effect?

### ISSUE THREAD

**Issue by zdmgmail** [junegunn/fzf.vim#1170]
- [√] I have fzf 0.23.0 or above
- [√] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [√] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [√] I have read through the manual page of fzf (`man fzf`)
- [√ ] I have searched through the existing issues

```
let g:fzf_preview_window = 'right:60%'
let g:fzf_commits_log_options = '--graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"'
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.7 } }

command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--height=94%']}, <bang>0)
```

I tried this `--height=94%` , seems not work,  how to change `Files` command height?

**Comment by junegunn** [comment]
`--height` option is ignored since Vim decides the size of the terminal window for fzf, and fzf uses the whole estate of it.

```vim
call fzf#vim#files(<q-args>, {'options': [ ... ], 'window': { 'width': 0.9, 'height': 0.94 }})
```


Reference: https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun
