### ISSUE TITLE
Feature request: abbreviate long paths

### ISSUE THREAD

**Issue by tami5** [junegunn/fzf.vim#1171]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hey @junegunn , 

I'm facing hard time dealing with long paths, I just can't see what I'm searching for.
Here is my function.

```viml
fu! s:fzfgrep(...)
  if a:0 < 1 | let l:q = '' | else | let l:q = a:1 | endif
  if a:0 < 2 | let l:dir = getcwd() | else | let l:dir = a:2 | endif
  if a:1 < 3
    let l:cmd = 'rg --column --line-number --no-heading --color=always --smart-case -- %s'
  else
    let l:cmd = a:3
  end
  let l:initial = printf(l:cmd, shellescape(l:q)).' '.shellescape(l:dir)
  let l:reload = printf(l:cmd, '{q}').' '.shellescape(l:dir)
  let l:spec = {'options': ['--phony', '--query', l:q, '--bind', 'change:reload:'.l:reload]}
  call fzf#vim#grep(l:initial, 0, fzf#vim#with_preview(l:spec), 0)
endf

fu! s:grep_packer(...)
  packadd fzf fzf.vim
  packadd fzf.vim
  if a:0 < 1 | let l:q = '' | else | let l:q = a:1 | endif
  let l:dir = expand('~/.local/share/nvim/site/pack/packer/')
  call s:fzfgrep(l:q, l:dir)
endf
```

I'd like to abbreviate those long paths. It would be a cool feature .

Thanks @junegunn

**Comment by noboruma** [comment]
I use these commands to abbreviate long paths:
```
    command! -bang -nargs=* -complete=dir Files
                \ call fzf#vim#files(<q-args>, {'options': ['--delimiter', '/', '--with-nth', '-2..', '--preview', 'echo {};echo;~/.vim/bundle/fzf.vim/bin/preview.sh {}']}, <bang>0)
```
The `--with-nth -2..` means only display the last directory & filename.
You can apply the same strategy for `ag`, `buffer` and `history`.

**Comment by tami5** [comment]
Nice thanks a lot I’ll try it

**Comment by tami5** [comment]
That solves my issue. Thanks a lot @noboruma

**Comment by fabOnReact** [comment]
Unfortunately, that doesn't work for me. 

```
command! -bang -nargs=* -complete=dir CustomGFiles
      \ call fzf#vim#files(<q-args>, {'window': { 'width': 0.7, 'height': 0.5, 'yoffset': 0.4}, 'options': ['--layout=reverse', '--preview-window=hidden', '--with-nth=3..4']} , <bang>0)
```

then I search EditText in this repo https://github.com/facebook/react-native

<img width="1496" alt="Screenshot 2024-08-15 at 11 03 09 AM" src="https://github.com/user-attachments/assets/68d61392-b80c-4db7-8a08-e1bb89a0fe55">

while the result should be the one below, but only show the last 2 folders

```
command! -bang -nargs=* -complete=dir CustomGFiles
      \ call fzf#vim#files(<q-args>, {'window': { 'width': 0.7, 'height': 0.5, 'yoffset': 0.4}, 'options': ['--layout=reverse', '--preview-window=hidden']} , <bang>0)
```
<img width="1496" alt="Screenshot 2024-08-15 at 11 04 07 AM" src="https://github.com/user-attachments/assets/56499091-2344-41c2-9582-eb064d6ecb6e">

I believe the command changes the search results.

Thanks a lot
