### ISSUE TITLE
Cursor not set at match when control characters and characters that take up double spaces present before match.

### ISSUE THREAD

**Issue by DZ84** [junegunn/fzf.vim#1174]
Bringing the cursor to the exact location of match doesn't work correctly when control characters and/or characters that take up double spaces are in place.

For example, with utf-8[unix] settings in Vim searching for "llllllllll" with Ag in the following line wouldn't result in the cursor being set at the correct position:

url = git@github.ë u y l э け へ げ f せ æ œ ぺ ㄟ u y é' è ål å ė , , ê. 		wwK ê ě ㄣ べ v c x l ë " K q わ d わ s s g l こ j ほ 			 com:junegunn/fzf.vim.git llllllllll 		 ë  <-- this one fails

And the same is true with control characters.

Perhaps/probably some Vim settings will affect this also.

**Comment by junegunn** [comment]
Thanks for the report. Fixed on master.
