### ISSUE TITLE
How can I do a filter of selected lines, and then replace the selection?

### ISSUE THREAD

**Issue by benlieb** [junegunn/fzf.vim#1183]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I often do the following with grep which will replace the lines selected with those matching.

![image](https://user-images.githubusercontent.com/634562/99774036-25bb8380-2ac2-11eb-96dc-6b24a58c4f3f.png)

Is it possible to do something similar with fzf or fzf-vim? It also occurs to me that I don't know how to open the contents of the found information in another window, but I do know how to open the file found itself. 

When I do the following, it just hangs:

![image](https://user-images.githubusercontent.com/634562/99774378-8e0a6500-2ac2-11eb-9875-faf4c06e34cc.png)

**Comment by junegunn** [comment]
Have you tried passing an array containing the lines as the `source` for `fzf#run`?

**Comment by benlieb** [comment]
@junegunn I'm not quite sure what that would mean. The context is a visual selection in vim, no really a scripting context.

So basically I'm working with the command

`'<,'>!fzf ...` 

Do you have a suggested version or variation of this that might work?

**Comment by junegunn** [comment]
I asked that because you checked `I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md`.

fzf is an interactive program and it renders its UI using STDERR, so `:!` or `system()` cannot be used to start fzf, just like you can't do `:!vim` or `:echo system('vim')`

You have to use `fzf#run` function.

**Comment by benlieb** [comment]
It sounds like you're saying there is no way to do what I'm asking out of the box, i.e. "filter selected lines, and then replace the selection"?

I tried `'<,'>FZF` and get "no range allowed". 

But perhaps if I knew vimscript I could write a function that would take the selection as input, and then pass it to `fzf#run` that might work?

**Comment by junegunn** [comment]
> It sounds like you're saying there is no way to do what I'm asking out of the box

Correct. There's no easy alternative to `:!`. `:!` is not for interactive programs.

> But perhaps if I knew vimscript I could write a function that would take the selection as input, and then pass it to fzf#run that might work?

Correct. This might help you get started.

```vim
function s:foo_sink(lines)
  call append(0, map(a:lines, { _, line -> toupper(line) }))
endfunction

function s:foo_impl(lines) range
  call fzf#run(fzf#wrap({
        \ 'source': a:lines,
        \ 'sink*': function('s:foo_sink'),
        \ 'options': ['--multi', '--reverse', '--prompt', 'Foo> ']}))
endfunction

command! -range Foo call s:foo_impl(getline(<line1>, <line2>))
```
