### ISSUE TITLE
Systemlist used in vim.vim everywhere else it's been updated to split(system...

### ISSUE THREAD

**Issue by rquintana2008** [junegunn/fzf.vim#1184]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am forced to run an older os and vim I was receiving errors that systemlist does not exist. Everywhere else it looks like system + split has been used instead. 

let output = systemlist(exec . ' --version') (line 75) 

Update to 
let output = system(split(exec . '--version'), "\n")

**Comment by junegunn** [comment]
There is no guarantee that this project will work correctly on older versions of Vim. But if changing `systemlist` to `system` is enough for your use case, we can do that.
