### ISSUE TITLE
E190: Cannot open "/Users/MCotocel/.local/share/nvim/view"

### ISSUE THREAD

**Issue by MCotocel** [junegunn/fzf.vim#1185]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

When running `:Files`, and then pressing Return, Control-C, Control-T, etc. I get the following error message:

```
Error detected while processing BufWinLeave Autocommands for "?*":
E190: Cannot open "/Users/MCotocel/.local/share/nvim/view/term:=+=+~=+=+569:'=+Users=+MCotocel=+.vim=+plugged=+fzf=+bin=+fzf'  '-m' '--prompt' '~=+' '--preview-window' 'right' '--previ
ew' ''\''=+Users=+MCotocel=+.vim=+plugged=+fzf.vim=+bin=+preview.sh'\'' {}' '--bind' 'ctrl-=+:toggle-preview' --expect==ctrl-v,ctrl-x,ctrl-t --no-height --border==rounded > =+var=+f
olders=+7w=+0cj35b794cz_gbl6bzhm4lw80000gn=+T=+nvimZyMWXA=+4;#FZF=" for writing
```

This does not happen with a minimal configuration or with Vim, only neovim

**Comment by MCotocel** [comment]
Fixed by commenting out:

```
augroup remember_folds
  autocmd!
  autocmd BufWinLeave ?* mkview
  autocmd BufWinEnter ?* silent! loadview
augroup END
```

in my vimrc

**Comment by timmyjose** [comment]
> Fixed by commenting out:
> 
> ```
> augroup remember_folds
>   autocmd!
>   autocmd BufWinLeave ?* mkview
>   autocmd BufWinEnter ?* silent! loadview
> augroup END
> ```
> 
> in my vimrc

How is this a fix though? This is removing functionality to avoid the error. What is the root cause of this issue?

**Comment by MCotocel** [comment]
I have no idea what the root cause is. This worked for me, and I assumed that, since I didn't find any issues related to my problem, it was a problem with my configuration and/or environment,

**Comment by timmyjose** [comment]
I think that the problem is with Neovim. Like you said yourself, the fold code works fine on Vim (so also for me). Also, when moving through symbols using `gf`, there is no issue whereas the issue comes up when using fzf. I found a similar (in an oblique way) issue on the nvim repo - https://github.com/neovim/neovim/issues/2194.

I'm having the same issue, but I don't have the time to investigate deeper as well. I'll see if I can log an issue with nvim sometime soon, or you could do it too if you get the time. Very annoying behaviour!

**Comment by RasmusJohns** [comment]
Also curious about this one! Did you ever fix it @timmyjose?

**Comment by nguyentritai2906** [comment]
To anyone stumble upon this in the future, just ignore the error message by adding `sillent!` when call `mkview`

```
augroup remember_folds
  autocmd!
  autocmd BufWinLeave ?* silent! mkview
  autocmd BufWinEnter ?* silent! loadview
augroup END
```
