### ISSUE TITLE
How to search under specific directory

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf.vim#1188]
Hello,

 I'm using Vim 8.2.2054 with fzf which version 0.24.3 on Windows 10. My _vimrc configuration for fzf is here:

" ---------------------------------------------- start --------------------------------------------------
let g:fzf_tags_command = 'ctags -R'
let g:fzf_preview_window = 'right:60%'

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit'
\}

let g:fzf_history_dir = '$HOME/.local/share/fzf-history'

let $FZF_DEFAULT_COMMAND = 'rg --files --ignore-case --hidden'
let $FZF_DEFAULT_OPTS = '--bind ?:toggle-preview --bind ctrl-j:down --bind ctrl-k:up --bind ctrl-d:half-page-down --bind ctrl-u:half-page-up'

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8 } }

" Customize fzf colors to match your color scheme
let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment']
\}

" Get Files
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), \<bang>0)

" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(\<q-args>), 1,
  \   fzf#vim#with_preview(), \<bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(\<q-args>, \<bang>0)

noremap \<silent> \<leader>p :Files\<CR> 
noremap \<silent> \<leader>f :Rg \<C-R>\<C-W>\<CR> 

" ---------------------------------------------- end --------------------------------------------------

As I know the default search path for fzf is current working directory the opened file. how to search files under specific directory? I have the issue #338 has the nearly same requirement from me.  Everytime I have to use ":Foo" command with the argument of the path of directory, and then use ":Files" with argument of file name to search the file I want?

" --------------------------------- start -----------------------------------
" Reloading source on CTRL-P. Requires fd command.
function! Foo(dir)
  let tf = tempname()
  call writefile(['.'], tf)

  call fzf#vim#files(a:dir, {'source': 'fd', 'options': ['--bind', printf('ctrl-p:reload:base="$(cat %s)"/..; echo "$base" > %s; fd . "$base"', shellescape(tf), shellescape(tf))]})
endfunction

command! -nargs=* Foo call Foo(<q-args>)
" --------------------------------- end -----------------------------------

I'm not familar with vimscript and still looking for how to change the _vimrc setting to make it work one command.

**Comment by junegunn** [comment]
> the default search path for fzf is current working directory

Yes.

> the opened file

The current working directory is not changed when you open a file, unless you have `autochdir` option set.

> Everytime I have to use ":Foo" command with the argument of the path of directory, and then use ":Files" with argument of file name to search the file I want?

I do not understand what you mean. `:Files DIRECTORY_NAME` isn't enough for you?

**Comment by jiangjianshan** [comment]
@junegunn , the command ':Files DIRECTORY_NAME' is work. Previous question is I press '<leader>p' to invoke ':Files<CR>', and also press '<leader>f' to invoke command ':Rg <C-R><C-W><CR>', this two commands only start from current working directory but can't specfied the different directory. So I have to press command ':Files DIRECTORY_NAME' or 'Rg WORD_TO_SEARCH DIRECTORY'? The WORD_TO_SEARCH may be contain a long characters. Is it possible when I press '<leader>p' and then allow me to input the directory name? And I press '<leader>f' and then allow me to just input the directory name but no need to input the word which is under cursor and may be a long character?

**Comment by jiangjianshan** [comment]
Due to I'm not familar with vimscript, so that I have just remove the line 'set autochdir' in _vimrc or .vimrc, then the directory will keep the one I enter first time.
