### ISSUE TITLE
24 bit true color support

### ISSUE THREAD

**Issue by zackhsi** [junegunn/fzf.vim#119]
Using Neovim with `NVIM_TUI_ENABLE_TRUE_COLOR=1` is great, but fzf doesn't seem to play nicely with it. Is there configuration that I'm missing? Or is this on the roadmap?

<img width="532" alt="fzf vim 24 bit true color" src="https://cloud.githubusercontent.com/assets/806101/14468046/ef36d976-0092-11e6-9570-6a4b7c2bdb57.png">

Thanks!

**Comment by junegunn** [comment]
The colors are from ag, the default ones. I guess there are ag options you can use to customize some colors, but even if you configure it to output 24-bit ansi codes (haven't checked if it's possible), fzf is limited to 256 colors due to the limitation of ncurses.

**Comment by zackhsi** [comment]
Any way to use 24 bit for everything except fzf?

**Comment by junegunn** [comment]
Such as?

**Comment by zackhsi** [comment]
I have no idea :(

**Comment by s-taylor** [comment]
I have the same issue also, the colours look perfect other than Ag output and configuring the colors as per https://github.com/junegunn/fzf.vim/issues/76 doesn't fix it. Turning off TRUE_COLOR in vim does work, but then breaks my theme. Also using gruvbox theme.
