### ISSUE TITLE
Preview window not working correctly

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf.vim#1190]
Hello,

The following version I'm using on Windows 10:
1. fzf version is 0.24.3
2. Vim version is 8.2.2061
3. bat version is 0.17.1

The _vimrc configuration for fzf.vim is here:

" ------------------------------------------ start---------------------------------------------------
let g:fzf_tags_command = 'ctags -R'
let g:fzf_preview_window = ['right:50%', 'ctrl-/']

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit'
\}

let g:fzf_history_dir = '$HOME/.local/share/fzf-history'

let $FZF_DEFAULT_COMMAND = 'rg --files --ignore-case --hidden'
let $FZF_DEFAULT_OPTS = '--bind ?:toggle-preview --bind ctrl-j:down --bind ctrl-k:up --bind ctrl-d:half-page-down --bind ctrl-u:half-page-up'

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8 } }

" Customize fzf colors to match your color scheme
let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment']
\}

" Get Files
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), \<bang>0)

" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(\<q-args>), 1,
  \   fzf#vim#with_preview(), \<bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(\<q-args>, \<bang>0)

noremap \<silent> \<leader>p :Files\<CR>
noremap \<silent> \<leader>f :Rg \<C-R>\<C-W>\<CR>
" ------------------------------------------ end ---------------------------------------------------
The preview window is not correctly invoked  from fzf.vim. For example, I press ":Files", it will look like below:

![image](https://user-images.githubusercontent.com/20179047/100488151-6f057600-3147-11eb-89b1-19f5304a56dc.png)

There are empty line between each line and many same line on bottom of preview window, e.g. 7/7(0). But at my another operation system linux on same laptop, which fzf version is still 0.24.3 and bat version is 0.17.1 also, but Vim version is 8.2.1913, the preview window invoked by fzf.vim is working correctly. Could you help to check the reason?

**Comment by junegunn** [comment]
See if adding `--no-unicode` to `$FZF_DEFAULT_OPTS` helps.

**Comment by jiangjianshan** [comment]
@junegunn , thanks for your solution, it work for the issue I meet.

**Comment by junegunn** [comment]
So your Vim is incapable of displaying Unicode box-drawing characters correctly. What's the output of `:version`?
