### ISSUE TITLE
Weird control characters

### ISSUE THREAD

**Issue by eymlo** [junegunn/fzf.vim#1193]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am getting a weird issue with vim fzf where control characters are being shows as weird characters. Control commands works like ctrl-c works everywhere else within vim and the terminal, except FZF

![image](https://user-images.githubusercontent.com/2066611/100802630-c7fb3580-33f7-11eb-972a-2bcb4b8fa973.png)

**Comment by pchang211** [comment]
I've been running into the same thing - it seems to happen only when I issue a ctrl-<something> command (e.g. ctrl-k to scroll or ctrl-t), the arrow and enter keys seem to work fine.

**Comment by eymlo** [comment]
Looks like it was an iterm2 issue on mac. The latest iterm2 resolved it.
