### ISSUE TITLE
Files command doesn't work properly when specific mapping is used

### ISSUE THREAD

**Issue by MatanHamilis** [junegunn/fzf.vim#1194]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

The issue:
When adding the following mapping in neovim and vim:
`tnoremap <C-m> <C-\><C-n>:bprevious<cr>`
Steps to reproduce in vim:
1. Use the clean setup of vim with fzf support:
`vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`
2. Add the mapping 
`tnoremap <C-m> <C-\><C-n>:bprevious<cr>`.
3. Type the `:Files` command and select a file.
The floating window should remain after selecting a file and the contents are not presented.

Adding a GIF with the aforementioned steps in my shell:

![render1606982872727](https://user-images.githubusercontent.com/2960109/100981980-2dfad080-3550-11eb-8a6c-478c7d36565c.gif)

**Comment by junegunn** [comment]
fzf is an external program and opens in a terminal window. So that tnoremap will simply prevent you from selecting an entry in fzf using enter key. What's the purpose of the mapping?

**Comment by MatanHamilis** [comment]
I've been using this (C-m) key-combination to move between buffers and created this mapping so I don't have to type the escape-sequnce of <C-\><C-n> while in terminal-mode to move to the next buffer. 
If I understand the documentation in `man fzf`, both key combinations ctrl-m and return keys are synonyms to the "enter" key which is bound to the event of "accept". So when the fzf program is notified that the "return" or the "ctrl-m" keys were typed - it triggers the "accept" event.
But here we had something different - the fzf program (which is the only entity that is aware of the fact the ctrl-m == return) received a notification of the "return" key being pressed and instead of triggering the "accept" event, it somehow triggered the mapping in vim for the ctrl-m combo.
I may have missed the part in the documentation which clarifies why this kind of behavior should occur.

**Comment by junegunn** [comment]
> which is the only entity that is aware of the fact the ctrl-m == return

CTRL-M **is** the return key in the standard terminal. You can't distinguish between the two.

```vim
" You'll see the message when you hit enter and when you hit ctrl-m
nnoremap <c-m> :echom "enter and c-m are the same"<cr>
```

fzf runs in a terminal buffer, so your mapping intercepts the key and switches the buffer, so fzf never gets it.

**Comment by MatanHamilis** [comment]
Oh I see now! Thank you very much for the distinction! Keep up with the great work.
Closing.
