### ISSUE TITLE
Nothing happens when I issue the commands

### ISSUE THREAD

**Issue by ronakg** [junegunn/fzf.vim#12]
Tried all the commands but nothing happens. I don't get any error or output.

Vim 7.4 running on a Linux box under Tmux.

What information should I capture to find out what's wrong?

Here is my dotfiles setup - https://github.com/ronakg/dotfiles

**Comment by junegunn** [comment]
I have no clue. Does `:FZF` command or `:call fzf#run({})` from the main repo work?

**Comment by ronakg** [comment]
Yeah, I had main fzf repo so far, which works fine. I was using it for file searching in vim and Ctrl-r in bash.

These are my options in bash -

```
export FZF_DEFAULT_COMMAND='if [ -e cscope.files ]; then cat cscope.files; else find ./ -type f ; fi'                                                                       
export FZF_COMPLETION_OPTS='+c -x'
export FZF_TMUX=1
export FZF_DEFAULT_OPTS='--extended-exact --bind ctrl-f:page-down,ctrl-b:page-up --color fg:252,bg:233,hl:67,fg+:252,bg+:235,hl+:121 --color info:144,prompt:161,spinner:135,pointer:135,marker:118'
```

And I have this mapping in vimrc

```
nnoremap <silent> <C-p> :FZF<CR> 
```

**Comment by junegunn** [comment]
`fzf --version` ?

**Comment by ronakg** [comment]
```
0.10.3
```

**Comment by junegunn** [comment]
Hmm, the latest version is 0.10.5, but there was no new option since 0.10.3, so updating it probably will not solve the issue you're having, but you're encouraged to upgrade it anyway.

What about bang-versions? e.g `:Files!`, `:Colors!`. Do they work?

**Comment by ronakg** [comment]
Yes, bang-versions are working in 0.10.3.

After updating to 0.10.5, normal versions are also working.

Thanks.

**Comment by netei** [comment]
I think I had the same issue at 0.10.3, it worked after updating to 0.10.5
