### ISSUE TITLE
Function fzf#vim#with_preview() is not callable on new instance of Neovim

### ISSUE THREAD

**Issue by ojroques** [junegunn/fzf.vim#1201]
- [x] I have fzf 0.23.0 or above (`v0.24.3`)
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I'm developing a plugin that checks that the function `fzf#vim#with_preview()` exists before calling it like so:
```vim
if exists('*fzf#vim#with_preview')
...
endif
```
However when I open a new instance of neovim this check fails and `:echo exists('*fzf#vim#with_preview')` indeed returns 0. It's only after I've run `:Files` at least once that the check passes.

I'd like to know if this is an expected behavior and if so, if there's a good way to detect that fzf.vim is installed on the user-side? Thanks in advance.

I'm using Neovim v0.4.4 and I can reproduce this issue with this minimal config:
```vimrc
call plug#begin()
Plug 'junegunn/fzf', {'do': {-> fzf#install()}}
Plug 'junegunn/fzf.vim'
call plug#end()
```

**Comment by junegunn** [comment]
It's an autoload function, so we don't know if it exists until the first invocation of it triggers the load.
You could call the function in a try-catch block and see it if returns a value without an exception. But the approach seems a bit crude. I'll add `g:loaded_fzf_vim` to the plugin file so you can see it to determine if this plugin is loaded.

**Comment by ojroques** [comment]
That's exactly what I needed. Thanks!
