### ISSUE TITLE
GF? with delta

### ISSUE THREAD

**Issue by crivotz** [junegunn/fzf.vim#1202]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Could there be a possibility to use [delta](https://github.com/dandavison/delta) in the `GStatus?` to do the diff?

I've seen some examples using [fzf-preview.vim](https://github.com/yuki-ycino/fzf-preview.vim) but I think it could be convenient to have it directly in `fzf.vim` without having to install other plugins

Here the example that I found:
```
let g:fzf_preview_git_status_preview_command =
    \ "[[ $(git diff --cached -- {-1}) != \"\" ]] && git diff --cached --color=always -- {-1} | delta || " .
    \ "[[ $(git diff -- {-1}) != \"\" ]] && git diff --color=always -- {-1} | delta || " .
    \ g:fzf_preview_command
```
Update:
Modifying line 629 I was able to get the result but it is not conservative if someone does not use delta.
```
  \ 'options': ['--ansi', '--multi', '--nth', '2..,..', '--tiebreak=index', '--prompt', 'GitFiles?> ', '--preview', 'sh -c "(git diff --color=always -- {-1} | delta) | head -1000"']
```
Thanks for your help

**Comment by junegunn** [comment]
> GStatus?

You mean `:GF?` (or `:GFiles?`), right? I fixed the title.

How about this?

```diff
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index cebb2fe..0eda8d6 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -623,10 +623,14 @@ function! fzf#vim#gitfiles(args, ...)
   " Here be dragons!
   " We're trying to access the common sink function that fzf#wrap injects to
   " the options dictionary.
+
+  let preview = executable('delta')
+        \ ? 'sh -c "git diff -- {-1} | delta"'
+        \ : 'sh -c "git diff --color=always -- {-1} | sed 1,4d; cat {-1}"'
   let wrapped = fzf#wrap({
   \ 'source':  'git -c color.status=always status --short --untracked-files=all',
   \ 'dir':     root,
-  \ 'options': ['--ansi', '--multi', '--nth', '2..,..', '--tiebreak=index', '--prompt', 'GitFiles?> ', '--preview', 'sh -c "(git diff --color=always -- {-1} | sed 1,4d; cat {-1}) | head -1000"']
+  \ 'options': ['--ansi', '--multi', '--nth', '2..,..', '--tiebreak=index', '--prompt', 'GitFiles?> ', '--preview', preview]
   \})
   call s:remove_layout(wrapped)
   let wrapped.common_sink = remove(wrapped, 'sink*')
```

**Comment by crivotz** [comment]
Yes I mean `GFiles?`, sorry for the mistake.
Great modification 👍🏻 I have to learn vimscript

**Comment by crivotz** [comment]
@junegunn thanks for change but very is a problem, I get the following messages `sh: 1: [[: not found`
Thanks

**Comment by junegunn** [comment]
Oh yeah, `[[` may not be supported on `sh` depending on what it is. 65b6cdb0f28de2629b6266b51d307d75d8c5c68c should fix it.

**Comment by crivotz** [comment]
> Oh yeah, `[[` may not be supported on `sh` depending on what it is. [65b6cdb](https://github.com/junegunn/fzf.vim/commit/65b6cdb0f28de2629b6266b51d307d75d8c5c68c) should fix it.

Fixed, thanks 😃
