### ISSUE TITLE
Fzf does not work in MacVim when launched from the dock

### ISSUE THREAD

**Issue by yurimalheiros** [junegunn/fzf.vim#1204]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello, I am using MacVim. When I launch MacVim from terminal (iTerm2) Fzf plugin works all ok. However, when I launch MacVim from the dock icon, it does not work. 

I searched and it seems that the command ran when I click on the icon is different from the `mvim` command that launch MacVim from terminal. But I am not one hundred percent sure about this. 

Is there any way to configure Fzf to work when I use the dock icon? I really appreciate some help on this issue.

Thank you in advance, and keep up the good work, your projects are really well done and useful!

**Comment by junegunn** [comment]
It works for me with MacVim installed by `brew cask install macvim`.

> it does not work

Can you be more specific? Any error message? Which command did you run?

**Comment by yurimalheiros** [comment]
> Can you be more specific? Any error message? Which command did you run?

I ran :FZF, but other commands failed too (e.g., :Files)

The messages are in Portuguese, so I will try to translate:

```
Error to process function <SNR>53_cmd[15]...fzf#wrap[30]..<SNR>53_default_layout:
line 1:
E806: Float used as String
Error to process function <SNR>53_cmd[15]...fzf#wrap[30]..<SNR>53_validate_layout:
line1:
E715: dictionary required
E714: list required

...
```

There are more messages, if you need, I can translate more.

> Everything works as expected for me on MacVim installed by brew cask install macvim.

I am going to try to reinstall MacVim using brew cask.

**Comment by yurimalheiros** [comment]
> I am going to try to reinstall MacVim using brew cask.

It works after reinstall! Thank you.
