### ISSUE TITLE
Add custom options to delta or add "--no-gitconfig" to the parameters

### ISSUE THREAD

**Issue by gfanto** [junegunn/fzf.vim#1205]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Thanks for having added delta as diff command, i've just a little request, like in the title, is it possible in some way to add the `--no-gitconfig` flag? Because i use delta as a git diff command with the `--side-by-side` option, but in the context of vim where the window it's much smaller i woul'd like to have the default options.
If that is not possible or shuld't be done, it's not a problem of course.

**Comment by junegunn** [comment]
I added the options. Let's see if anyone complains :)

We'll eventually need to add an option for customizing the diff formatter (some may prefer diff-so-fancy, etc.), but I think this is good for now.

**Comment by kevinhwang91** [comment]
@junegunn `--no-gitconfig` option made my elaborate style gone.

**Comment by junegunn** [comment]
Well, that was quick :)

I updated the code to only unset `--side-by-side`. Hope this helps.

**Comment by junegunn** [comment]
Hmm, no, unlike fzf, `+s` doesn't disable `-s`. I'll think about the options.

**Comment by gfanto** [comment]
Yeah, that was quick :) i'm sorry about that. I tought about the configurations, and i don't want you to lose your time adding 300 or more lines for stupid configurations, it's much easier for me removing 1 line from my config than for you adding the options code.
Thaks anyway!
