### ISSUE TITLE
:FZF works, but :Files does not

### ISSUE THREAD

**Issue by vicecaycedo** [junegunn/fzf.vim#1210]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Using neovim (NVIM v0.4.4) on Windows 10.
Using Git Bash shell on Windows Terminal.
Using vim-plug.

Installed fzf and ripgrep.
Confirmed both are installed:
```
> fzf --version
0.24.4 (00a3610)
```
```
> rg --version
ripgrep 12.1.1 (rev 7cb211378a)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```
Installed both plugins in init.vim
```
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
```

Full init.vim located [here](https://github.com/vicecaycedo/config/blob/main/init.vim)

Getting several problems:
1. When running `:PlugInstall`, it shows an X as if the install failed and shows a prompt to retry. However, when I retry, it says the plugins are already installed and indeed they are.
2. When running `:PlugClean`, it asks to remove directories and after entering Y, it says it successfully removed them, but they're still there. It also shows this error:
```
Error detected while processing function <SNR>2_clean[13]..<SNR>2_git_validate:
line   36:
E688: More targets than List items
E688: More targets than List items
E688: More targets than List items
E688: More targets than List items
E688: More targets than List items
E688: More targets than List items
```
3. Running `:FZF` works, but running `:Files` fails with this error:
```
Error detected while processing C:\Users\myusername\AppData\Local\nvim-data\plugged\fzf.vim\autoload\fzf\vim.vim:
line   41:
E684: list index out of range: 0
E15: Invalid expression: split(system('for %A in ("'.s:bin.preview.'") do @echo %~sA'), "\n")[0]
Error detected while processing function fzf#vim#files[15]..<SNR>62_fzf[1]..<SNR>62_check_requirements:
line   14:
E605: Exception not caught: Failed to run "fzf --version": []
```
4. Running `:Rg` fails with the error:
```
Error detected while processing function fzf#vim#grep[24]..<SNR>62_fzf[1]..<SNR>62_check_requirements:
line   14:
E605: Exception not caught: Failed to run "fzf --version": []
```

Let me know if you need more information. I appreciate the help - been working on this all day.

**Comment by vicecaycedo** [comment]
Using PowerShell instead of Git Bash seems to have fixed these issues.

**Comment by vicecaycedo** [comment]
Finally resolved the issue. 

It was using bash from WSL and not Git for Windows.

Solutions for the problems in this thread:
1. Use PowerShell, not Git Bash.
2. Make sure Git for Windows is before any WSL stuff in your PATH.

**Comment by ndavidpsi** [comment]
@vicecaycedo I have the same problem, unfortunately that didn't solve it for me.
Do you also have the following in your init.vim/vimrc? (it's the recommended way according to the docs)
```
let &shell = has('win32') ? 'powershell' : 'pwsh'
set shellquote= shellpipe=\| shellxquote=
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellredir=\|\ Out-File\ -Encoding\ UTF8
```
Also, the bash in my PATH is Git one.
I then have the following in my init.vim:
```
command! -bang -nargs=? -complete=dir Files
      \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options':
      \ ['--layout=default', '--info=inline']}), <bang>0)
```

But when I do `:Files` I get the following: `/c/windows/system32/At: /c/windows/system32/At: cannot execute binary file`
