### ISSUE TITLE
:Buffers doesn't let me select alternate buffer

### ISSUE THREAD

**Issue by paddor** [junegunn/fzf.vim#1211]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I'm learning to work with buffers in Vim. Sometimes I open the Vim documentation in a split and later accidentally close the other window. I could do `:vsp #`, but I have a nice key binding for `:Buffers`. Unfortunately `:Buffers` won't let me select the bottom-most buffer in the list, which means I can't Ctrl-V to reopen in a split.

Any ideas?

**Comment by junegunn** [comment]
Most of the time, the bottom-most item is the current buffer, not the alternate buffer. We use `--header-lines=1` option of fzf to disallow selecting the current buffer so it's easier to switch between two buffers.

What you're experiencing here is an exceptional case where the current buffer is an unlisted buffer (i.e. vim help) so it does not appear on the list, but we still apply `--header-lines=1` when we shouldn't. I can fix this.

**Comment by paddor** [comment]
Thanks. It seems to work!
