### ISSUE TITLE
FZF window does not disappear after <Esc>

### ISSUE THREAD

**Issue by paddor** [junegunn/fzf.vim#1213]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

The FZF window does not visually close after hitting `<Esc>`. It lingers and the cursor is trapped in its bounding box until I `:q`. That makes it disappear. Confirmed with `:Files` and `:Maps`.

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by paddor** [comment]
The issue disappears with the minimal vimrc.

The culprit is this mapping which I added to be able to escape from NeoTerm:
```
tnoremap <Esc> <C-\><C-n>
```

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/1393#issuecomment-426576577

**Comment by paddor** [comment]
Thanks a lot
