### ISSUE TITLE
Question: Is there a way to only display files with a certain extension/list of extensions?

### ISSUE THREAD

**Issue by ndavidpsi** [junegunn/fzf.vim#1214]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

### Question 
I want to query a list of extensions such as [.c$,.cpp$,.cs$] so that when I search something it will only list files with those extensions. So it's essentially a long query but I want to have my search bar free when searching (which doesn't happen with normal queries).

It's something like the `:Colors` command which only displays colorschemes but I want to create a command which only displays files with certain extensions.

**Comment by junegunn** [comment]
>  I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
> I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md

Please read through the documentation and learn how to define custom commands. All the information you need is there.

**Comment by ndavidpsi** [comment]
I did read it but I wasn't able to get an answer

**Comment by ndavidpsi** [comment]
I have done so... 
In order to define a command I would do something like this:
command Foo call fzf#run('sink': 'e')
I just can't find the parameter I need to display only the file extensions (or custom pattern) I want. I thought about prefix but it just enters it into the search bar
