### ISSUE TITLE
Switching to a terminal buffer with :Buffers in Neovim automatically starts terminal mode

### ISSUE THREAD

**Issue by gadkadosh** [junegunn/fzf.vim#1216]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

As the title states, in Neovim when switching to a terminal buffer with :Buffers puts you in terminal mode, even though last mode was normal. This is different to Neovim's behaviour. It also seems to be different in Vim itself. I feel like :Buffers should behave like the normal :buffer command.
The implementation in fzf seems to just execute :buffer, so I'm probably missing something somewhere, or else I don't know why the behaviour would be different.

**Comment by ojroques** [comment]
I'm running into the same issue. To reproduce:
```vim
call plug#begin()
Plug 'junegunn/fzf', {'do': {-> fzf#install()}}
Plug 'junegunn/fzf.vim'
call plug#end()

set hidden
tnoremap <ESC> <C-\><C-n>
```
1. Open Neovim with any file
2. Run `:term`
3. Run `:Buffers` and swith to the opened file
4. Again run `:Buffers` and go back to terminal

We enter the terminal buffer in terminal mode instead of normal mode.
