### ISSUE TITLE
Fix delta preview width

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf.vim#1219]
- [X] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I found a solution
https://github.com/dandavison/delta/issues/368#issuecomment-751668990
that could be applied directly there (instead of gitconfig).

With `delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}'` _side-by-side_ view is displayed correctly.

Without this fix this view occupies only part of width:
![image](https://user-images.githubusercontent.com/11404453/103835057-79d7f280-5085-11eb-8654-727bcffdef8b.png)

**Comment by sleewoo** [comment]
can confirm it works perfect, but only if not piping to `sed`

got it working correctly by replacing

![Screenshot_20210310_164203](https://user-images.githubusercontent.com/74734701/110646149-487fbe00-81bf-11eb-9f3b-6d441b7a885a.png)

with this

```
git diff -- {-1} | delta --file-style=omit --width=${FZF_PREVIEW_COLUMNS:-$COLUMNS}
```

@junegunn is this an acceptable patch?
should we open a pull request?

**Comment by fanliver** [comment]
@sleewoo 
That solution does not really work for me

![image](https://user-images.githubusercontent.com/6322508/118485193-4fd4c200-b742-11eb-8728-0d29c9dd2596.png)

My change in fzf.vim source code

![image](https://user-images.githubusercontent.com/6322508/118485258-667b1900-b742-11eb-8e33-4eeb13fe580c.png)
