### ISSUE TITLE
`:Files` command always lists zero results when opening vim with `vim -` (read from STDIN)

### ISSUE THREAD

**Issue by robenkleene** [junegunn/fzf.vim#122]
When I open vim with `echo "test" | vim -` the `:Files` and `:FZF` commands always return zero results.

When I open vim with `vim` (or `vim .`) in the same directory the commands work fine.

`pwd` returns the same directory in all cases.

**Comment by junegunn** [comment]
Thanks for the report, but I can't reproduce the problem. Make sure to use the latest version of Vim and fzf, and try again with a minimal vimrc like follows.

```vim
echo "test" | vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc) -
```

**Comment by robenkleene** [comment]
Thanks for taking a look, I can't reproduce either now. Cheers! -Roben
