### ISSUE TITLE
Insert text from file

### ISSUE THREAD

**Issue by mb720** [junegunn/fzf.vim#1220]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi and thanks a lot for fzf!

I'd like to insert email addresses after selecting them with fzf. My user agent is Mutt.

The format of my `~/docs/contacts/email_addresses`:

    # Friends & Family
    alias Anni_Borg Anni Borg <a.borg@example.com>
    alias Charlie_Dorn Charlie Dorn <charlie@dorn.com>
    alias Emily_Forte Emily Forte <emily.forte@example.com>

What I'd like to enter into the buffer is, for example:

    Charlie Dorn <charlie@dorn.com>

I feel I'm pretty close with this mapping:

    nmap <leader>a :call fzf#run(fzf#wrap({'source': 'grep ^alias ~/docs/contacts/email_addresses \| cut -d" " -f 3-', 'sink': 'norm a'}))<CR>

The issue I have is that the string is escaped, I get

    Charlie\ Dorn\ \<charlie@dorn.com>

instead of

    Charlie Dorn <charlie@dorn.com>

Is there a way to improve my mapping and avoid having the string escaped?

**Comment by TamaMcGlinn** [comment]
By giving fzf a funcref you can do this:

```
function Insert_Contact(name) abort
  call append(line('.'), a:name)
endfunction

nmap <leader>a :call fzf#run(fzf#wrap({'source': 'grep ^alias ~/docs/contacts/email_addresses \| cut -d" " -f 3-', 'sink': function("Insert_Contact")}))<CR>
```

If you want to insert multiple contacts, you want `sink*` instead of sink, and I don't know how but you need to modify Insert_Contact to accept a list of names then I guess put them together with ';' in between. That way, you can <tab> each contact you wanted to add. Also, I'm not sure that what I wrote works with mutt but you can tinker with the Insert_Contact function until it does.

**Comment by junegunn** [comment]
@TamaMcGlinn Thanks for the comment.

`fzf#run` by default escapes the line before passing it as an argument to a command given in string-typed `sink`. (e.g. `e`, `tabedit`, etc.) 

If you don't want the escaping, you need to use a funcref sink as @TamaMcGlinn suggested. You can use a lambda expression if you use the Vim 8.0 or above like so.

```vim
nnoremap <leader>a :call fzf#run(fzf#wrap({'source': 'cat ~/.bashrc \| cut -d" " -f 3-', 'sink': { line -> execute('normal! a' .. line) }}))<CR>
```
