### ISSUE TITLE
Pass fzf window height to preview command

### ISSUE THREAD

**Issue by IngoMeyer441** [junegunn/fzf.vim#1222]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hey and thanks for fzf and this awesome vim plugin. :smile: 
A preview for the `:Tags` command is still missing, so I created a litte preview script which feeds the ex command of the ctags file into vim's ex mode to get a line number and uses this for a preview with `bat`. I would like to contribute this script to fzf.vim but I have still some problems which should be fixed first. Oll the other previews (like for buffer tags) use the scroll feature of fzf for the preview window. Unfortunately, this seems not possible for general tags because the line number must be known before fzf is called (but it is only calculated in my preview script). My current workaround for this problem is a fixed height value in the preview script which is used to pass a line range to the `bat` command so the line of interest is centered but no scrolling is possible. So my question is: Is it possible to get the fzf preview window height in a preview command to get rid of my hard coded value? Of course it would be better to enable the scroll feature but I don't see any way to achieve this.

**Comment by junegunn** [comment]
You can refer to `$FZF_PREVIEW_LINES` and `$FZF_PREVIEW_COLUMNS`.

```sh
fzf --preview 'echo Window size: $FZF_PREVIEW_LINES x $FZF_PREVIEW_COLUMNS'
```

**Comment by IngoMeyer441** [comment]
Ah perfect, didn't know about them, thanks!
