### ISSUE TITLE
Configuring the `ag` options used by `:Ag`

### ISSUE THREAD

**Issue by davidstosik** [junegunn/fzf.vim#1225]
- [x] I have fzf 0.23.0 or above _(0.25.0)_
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Preliminary note: I'll admit that I've pushed my research deeper while I was writing this, to make sure I was not _too wrong_. I've never written Vim script (except for copy-pasted snippets that I put in my `.vimrc`), so I may not be getting everything right. I eventually found a work-around that is not too bad for my usage, but I wish there was a bit more flexibility.

Here is how to reproduce my initial problem:

```shell
mkdir /tmp/test && cd /tmp/test
echo "Hello" > .my_fidden_file

export FZF_DEFAULT_COMMAND='ag --hidden -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# This finds the hidden file properly (no alias interference)
\ag --hidden -g my

# This too
\ag --hidden Hello

# Starting a minimal Vim
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```
`:Files` will show `.my_hidden_file`, however, `:Ag Hello`, which I would expect to show the file as well, will not, and instead shows the following error:
`[Command failed: ag --nogroup --column --color  -- 'Hello'] `

Of course, `:Ag` did not use my `FZF_DEFAULT_COMMAND`! 💡 

Looking into the documentation and issues, I found something that could be interesting, a way to redefine `:Ag`, so I tried it:

```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, $AG_DEFAULT_OPTIONS, <bang>0)
```
I have previously defined the `$AG_DEFAULT_OPTIONS` environment variable, and confirmed that, in Vim `:echo $AG_DEFAULT_OPTIONS` displays `--hidden --path-to-ignore /Users/david-stosik/.ignore` (see [the Silver Searcher's _Advanced Usage - .ignore_ documentation](https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage#ignore))

This seems to work. At least `:Ag Hello` now returns `.my_hidden_file`, as expected. However, I have now lost the file preview.

Digging a bit in the code, I understand that the call to `s:p()` [here](https://github.com/junegunn/fzf.vim/blob/1fcdee55cc5975d67248b2f8ea5fbac9aa628b7c/plugin/fzf.vim#L69) eventually [calls](https://github.com/junegunn/fzf.vim/blob/1fcdee55cc5975d67248b2f8ea5fbac9aa628b7c/plugin/fzf.vim#L57) `fzf#vim#with_preview` providing proper arguments (and defaults).

I know very little of Vim scripting, so forgive me if anything I'm writing is wrong, but I would like to have a `.vimrc` that configures Vim the way I'd like it to work, while keeping custom code that I need to maintain to its minimal. While I understand it's not possible, and was happy to redefine the `:Ag` command the way I did above, I'd like to avoid having to copy-paste more code into my `.vimrc`, or to duplicate stuff. For example, I imagine this may work:

```vim
" Copy-pasted from https://github.com/junegunn/fzf.vim/blob/1fcdee55cc5975d67248b2f8ea5fbac9aa628b7c/plugin/fzf.vim#L47-L58
function! s:fzf_p(...)
  let preview_args = get(g:, 'fzf_preview_window', ['right', 'ctrl-/'])
  if empty(preview_args)
    return { 'options': ['--preview-window', 'hidden'] }
  endif

  " For backward-compatiblity
  if type(preview_args) == type('')
    let preview_args = [preview_args]
  endif
  return call('fzf#vim#with_preview', extend(copy(a:000), preview_args))
endfunction

" Use my default AG options for :Ag
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, $AG_DEFAULT_OPTIONS, s:fzf_p(), <bang>0)
```

Ideally, I would like to be able to reuse the `s:p()` [function](https://github.com/junegunn/fzf.vim/blob/1fcdee55cc5975d67248b2f8ea5fbac9aa628b7c/plugin/fzf.vim#L47-L58) the way it is defined, without having to duplicate it.

I also guessed that I don't have to use it, and that I could instead do the following:
```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, $AG_DEFAULT_OPTIONS, call('fzf#vim#with_preview', ['right', 'ctrl-/']), <bang>0)
```
However, that would duplicate the preview window settings (position, ratio and toggle binding) in two places.

Eventually, I think I'll settle with the following:

```vim
let g:fzf_preview_window = ['right:50%', 'ctrl-_']
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, $AG_DEFAULT_OPTIONS, call('fzf#vim#with_preview', g:fzf_preview_window), <bang>0)
```

I'm very thankful for the `fzf.vim` plugin, and how it provided me with great commands out of the box, and I appreciate the difficulty to satisfy everyone and provide such a flexible system, but I wish `fzf` (and/or `fzf.vim`) gave me a simple way to **configure the default `ag` options that get passed to the `ag` command equally in all contexts**.

**Comment by junegunn** [comment]
> Ideally, I would like to be able to reuse the s:p() function the way it is defined, without having to duplicate it.

I removed `s:p()` in the latest commit. `fzf#vim#with_preview` will handle `g:fzf_preview_window`.

```vim
let g:fzf_preview_window = ['right:50%', 'ctrl-_']
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, $AG_DEFAULT_OPTIONS, fzf#vim#with_preview(), <bang>0)
```

> a simple way to configure the default ag options that get passed to the ag command equally in all contexts

I assume you mean something like `g:fzf_ag_opts` (like the one in https://github.com/junegunn/fzf.vim#command-local-options). The problem with the approach is that then we have two ways to achieve the same requirement and it can lead to more user confusion (*"Which one should I use? Do I have to set up both?"*), less consistency across the commands (*"Why `Colors` command doesn't have g:fzf_colors_xxx?"*), and more maintenance burden.
