### ISSUE TITLE
Tag preview doesn't work if tags outside source tree

### ISSUE THREAD

**Issue by achilleas-k** [junegunn/fzf.vim#1228]
https://github.com/junegunn/fzf.vim/blob/1fcdee55cc5975d67248b2f8ea5fbac9aa628b7c/bin/tagpreview.sh#L13

The linked line assumes that the `tags` file is in the root of the source tree or in the current directory.  Plugins and user options can change the location of the tags file(s) (e.g., gutentags).  I personally like to keep tags in a single location under `~/.cache`.

I'm not sure what the general solution is here.  In my case, removing the linked line and using the `$FILE` as is works, but I suspect that might break the default case.

**Comment by IngoMeyer441** [comment]
I did some test with gutentags (I also use it for tag generation) and for me the filepaths in the generated tag file are relative to the tag file as long as it is stored somewhere within the project (for example in the `.git` directory). Which configuration of gutentags do you use exactly?

**Comment by achilleas-k** [comment]
> Which configuration of gutentags do you use exactly?

I have tags stored in a common directory under `~/.cache`.  I set:
```vim
let g:gutentags_cache_dir = '~/.cache/vim/tags'
```
which creates a separate file for each project in that directory (the filename is the path to the project with `/` replaced with `-`).
As a concrete example, with a project at:
```
/home/achilleas/projects/osbuild/osbuild-composer
```
`:set tags` prints
```
tags=~/.cache/vim/tags/home-achilleas-projects-osbuild-osbuild-composer-tags,./tags,./TAGS,tags,TAGS
```

The preview script then fails with:
```
File not found /home/achilleas/.cache/vim/tags//home/achilleas/projects/osbuild/osbuild-composer/cmd/osbuild-composer/main.go
```

**Comment by IngoMeyer441** [comment]
Ah I see, but in this case we could use an easy fix by detecting that the `$FILE` is already an absolute path and leave it as is. I can prepare a patch.

**Comment by achilleas-k** [comment]
Right.  That's reasonable.  I wasn't sure where the `$FILE` comes from, but now see it's from the `tags` file itself, so it's either absolute or relative to that file.

Perfect!  Thanks for the help @IngoMeyer441!
