### ISSUE TITLE
:Files default to vim-rooter

### ISSUE THREAD

**Issue by Skyfold** [junegunn/fzf.vim#123]
:Files by default starts in the directory you are currently in, which often is not the directory you want to be searching files in. Is it possible to change the default to call something like FindRootDirectory() from vim-rooter?

I would do this myself, but my vim foo is not good enough...

**Comment by tweekmonster** [comment]
This is outside of fzf.vim's scope.  vim-rooter only works when a file is opened.  I assume you're talking about invoking `:Files` when there aren't files already opened?  If so, here's my setup for dealing with this:

```vim
let g:rooter_patterns = ['.vimroot', '.git/', '.python-version']

augroup vimrc_rooter
    autocmd VimEnter * :Rooter
augroup END
```
`.vimroot` is something I made up for directories that don't have language-specific files/directories to define a project.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795

**Comment by Skyfold** [comment]
That solved my problem, perfectly! 

Would it be possible to put the `augroup` in the readme somewhere for the next person?

Thanks for taking the time to help
