### ISSUE TITLE
E994 when running: vim -c 'Rg failed'

### ISSUE THREAD

**Issue by MaxGyver83** [junegunn/fzf.vim#1231]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I try to start vim with a 'Rg' search given as command line parameters:

```sh
vim -c 'Rg failed'
```

This gives me these errors:

```
Error detected while processing VimEnter Autocommands for "*"..function <SNR>15_VimEnter:
line    4:
E994: Not allowed in a popup window
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*"..function <SNR>15_VimEnter:
line    5:
E994: Not allowed in a popup window
Press ENTER or type command to continue
```

Tested with the latest versions:

* vim 8.2.2398
* fzf 0.25.0
* fzf.vim 36de5db

This error message doesn't show up in Neovim v0.4.4.

**Comment by michaelorr** [comment]
@MaxGyver83 I was running into this same issue with `fzf.vim`+`Ag` and I came up with a hacky workaround that works for me and will probably work for you.

From the issue linked by @lacygoill, it seems like Vim really doesn't want to allow popups until after the `VimEnter` event is fired and any `vim -c` commands happen prior to `VimEnter`

My first attempt was to hook `VimEnter` directly via:
`vi -c "autocmd VimEnter * Ag $1"` but that did not work and caused other problems that were even more opaque

**BUT** vim8+ can invoke a closure via async timers and it seems like using `au VimEnter *` to schedule an invocation of the `Ag` command after `VimEnter` has happened makes everything happy:
 
`vi -c "autocmd VimEnter * call timer_start(0, {->execute('Ag $1')})"`

NOTE: it works for me with a delay of `0`ms, which tells me that its less about the delay and more about which thread of execution is invoking the popup.

That's a bit gnarly to write out, but in my case, it'll be wrapped by a helper. Hopefully this works for you and `Rg` also.

**Comment by lacygoill** [comment]
Yes, this solution should work.  Alternatively, someone should contact the maintainer of the netrw plugin [by mail](https://github.com/vim/vim/blob/ba98fb54aefada4c36390add4c7dd90b93e7e5bb/runtime/plugin/netrwPlugin.vim#L4), so that they include the patch that I mentioned in https://github.com/vim/vim/issues/7742, or implement any other fix they consider to be appropriate.

**Comment by michaelorr** [comment]
I have emailed the maintainer and linked him to https://github.com/vim/vim/issues/7742
It looks like he made updates to `netrw` as recently as 2 months ago (though not yet merged to the upstream vim repo), so hopefully he will be able to assist.

**Comment by MaxGyver83** [comment]
@michaelorr : Thanks for you reply! I got the same recommendation in my [stackexchange](https://vi.stackexchange.com/questions/28874/start-vim-with-ex-command-and-append-it-to-vims-command-history) question.

There is one problem with this solution:
When I run `vi -c "autocmd VimEnter * call timer_start(0, {->execute('Ag test')})"`, I can't open any matches with the `Enter` key.

Thanks for emailing the maintainer of the netrw plugin. I hope he fixes this.

**Comment by michaelorr** [comment]
That's strange. On my end, I have to hit `<enter>` twice to get it to register, but it does work. Sorry that its not working for you :/

**Comment by EelVex** [comment]
I didn't run on this issue until *after I uninstalled `justinmk/vim-dirvish`*. So apparently this line from dirvish:

```
autocmd VimEnter * if exists('#FileExplorer') | exe 'au! FileExplorer *' | endif
```

was masking ("fixing") this issue.

**Comment by MaxGyver83** [comment]
Indeed, this works! Thanks a lot!

**Comment by lacygoill** [comment]
Fixed in the last update of the runtime files: https://github.com/vim/vim/commit/89a9c159f23fb7b3e24e6d09068adfc24a73afcb

**Comment by MaxGyver83** [comment]
It looks like I forgot to close this.
