### ISSUE TITLE
"I" character getting inserted when calling fzf.run() on sink 

### ISSUE THREAD

**Issue by JoeHFB** [junegunn/fzf.vim#1235]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello!

Could someone please help me narrow down whether this issue is coming from vim or fzf.vim?  Problem description, behavior, environment setup, and steps I took listed below. 

## Problem
I am seeing the `I` character get automatically inserted when I invoke `fzf#run({'sink': 'e', ...` or `fzf#run({'sink': 'tabedit'` via my custom mappings... But **only on one environment**!

This was NOT happening on older versions of vim.  It's a relatively a recent thing.

## What am I doing?
I have mapped `<C-o>` to  `fzf#run({'sink': 'e', ...`  and `<C-t>` to `fzf#run({'sink': 'tabedit'`.  When I press either of the key combos, the fzf window opens up... with `I` character pre-inserted.

I compile vim from source every once in a blue moon based on https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source.  I can supply the exact configuration if you'd like.

When I noticed this happening about a week or two ago, I rebuilt my vim from the previous version I was on in case it was a vim regression.  But I tried again today and it's still there ☹️ 

The bizarre thing is that it's only happening on certain newest versions of vim... ONLY on my linux mint environment though?? 

EDIT: Forgot to mention:
```
$ fzf --version
0.25.0 (8c533e3)
```

### Linux Mint 20 vim 8.2.2425: this issue happens 😭 
![image](https://user-images.githubusercontent.com/60893676/106324802-c7d8b400-6247-11eb-9ec6-6527b2bf82af.png)

### Linux Mint 20 vim 8.2.2340 this issue DOES NOT happen 🤔 
![image](https://user-images.githubusercontent.com/60893676/106325243-8268b680-6248-11eb-9dab-904dd76e2672.png)

### Ubuntu 20.04 in WSL 2 8.2.2425: this issue DOES NOT happen 🤔 
![image](https://user-images.githubusercontent.com/60893676/106325128-4f262780-6248-11eb-9d02-b98eb44bf2b6.png)

## Minimal vimrc I made to reproduce this issue
(yes I'm a vimscript noob 😆 )
```
" Migrate to Vim-Plug based on https://github.com/junegunn/vim-plug/wiki/tips
" Passing in ~/.vim/bundle/ to avoid reinstalling plugins as suggested by wiki
call plug#begin('~/.vim/bundle')

" Fuzzy Finder - use this for searching file content & opening files
Plug 'junegunn/fzf', { 'dir': '~/.vim/bundle/fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
" Syntax highlight with Sublime's Monokai theme
Plug 'ErichDonGubler/vim-sublime-monokai'

call plug#end()

set nocompatible

syntax on
set background=dark
set termguicolors
colorscheme sublimemonokai
let g:sublimemonokai_term_italic = 1

if executable('rg')
    set grepprg=rg\ --smart-case\ --vimgrep\ --hidden
    set grepformat^=%f:%l:%c:%m
endif

let rglistfiles = 'rg --files --hidden --glob "!*.class" --glob "!.idea/*" --glob "!**/.idea/*" --glob "!.git/*" --glob "!**/.git/*" --glob "!*.swp"'

let g:fzf_layout = { 'down': '40%'  }

let fzfopenfilesopts = "--multi --reverse --preview '([[ \$(file --mime {}) =~ binary  ]] && echo {} is a binary) || (pygmentize -O style=emacs,bg=dark -g {} | head -n 50)'"

let rgsearchfiles = 'rg --column --line-number --no-heading --fixed-strings --ignore-case --hidden --glob "!*.class" --glob "!.idea/*" --glob "!*/.idea/*" --glob "!.Private/*" --glob "!*/.git/*" --glob "!.git/*" --color "always" '

command! -bang -nargs=* Find
    \ call fzf#vim#grep(
    \ rgsearchfiles .shellescape(<q-args>),
    \ 1,
    \<bang>0 ?
        \fzf#vim#with_preview({'options': '--delimiter : --nth 4.. --no-hscroll'}, 'up:60%') :
        \fzf#vim#with_preview({'options': '--delimiter : --nth 4.. --no-hscroll'}, 'right:50%:hidden', '?'),
    \<bang>0)
nnoremap <silent> <C-f> :Find <cr>

" Map ctrl-o to open file with FZF in current tab, ctrl-o for new tab
command! -bang -nargs=* FuzzyOpenFiles call fzf#run({'sink': 'e', 'source': rglistfiles, 'options': fzfopenfilesopts })
command! -bang -nargs=* FuzzyTabFiles call fzf#run({'sink': 'tabedit', 'source': rglistfiles, 'options': fzfopenfilesopts })
nnoremap <silent> <C-o> :FuzzyOpenFiles <cr>
nnoremap <silent> <C-t> :FuzzyTabFiles <cr>
```

**Comment by JoeHFB** [comment]
I noticed something bizarre today while playing around with this - adding a layout option like `'up': '90%'` makes the `I` character not get inserted. 

Ex:
- Set the command to this: `command! -bang -nargs=* FuzzyOpenFiles call fzf#run({'sink': 'e', 'source': rglistfiles, 'up': '90%', 'options': fzfopenfilesopts })`
- Trigger via `<C-o>` - note the lack of `I` character 
![image](https://user-images.githubusercontent.com/60893676/106958774-cefc3800-6707-11eb-8d69-d6c71cba7615.png)

But I noticed that this is noticeably slower opening and also escaing via `esc`.

Did I screw up my settings somewhere else?  I don't get why adding a layout option would affect this. 😕

**Comment by junegunn** [comment]
* I recommend that you always use `fzf#wrap` so that global configs (such as `g:fzf_layout`) are universally applied. (See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap)
* To set up previewer, I recommend that you use `fzf#vim#with_preview`. (If you're not using it because you prefer `pygmentize` over `bat`, that's fair)

```vim
let rglistfiles = 'rg --files --hidden --glob "!*.class" --glob "!.idea/*" --glob "!**/.idea/*" --glob "!.git/*" --glob "!**/.git/*" --glob "!*.swp"'

" You don't need to set up --preview option (fzf#vim#with_preview injects a preview option that uses "bat")
" You don't need separate commands to open files in different ways
"   - Press enter to open file
"   - Press CTRL-T to open in a new tab
"   - Press CTRL-X to open in a horizontal split, CTRL-V vertical split
"   - (This is all made possible by fzf#wrap)
command! -bang -nargs=* FuzzyOpenFiles call fzf#run(fzf#vim#with_preview(fzf#wrap({'source': rglistfiles, 'options': '--multi --reverse'})))
nnoremap <silent> <C-o> :FuzzyOpenFiles<cr>
```
* (By the way, I would not map it to CTRL-O, because CTRL-O is a pretty useful key in Vim.)
* Have you tried without `let g:fzf_layout = { 'down': '40%' }`? Did you set it because you don't like the default pop-up layout?
* fzf runs in a different mode if you use the `down` layout. It renders fzf *below* Vim, while the other layouts runs fzf in a terminal buffer inside Vim. So you not having the problem when you use `up` layout indicates that this is an issue with the exceptional `down` layout.
* Because of this discrepancy, I've been considering making `down` layout also use a terminal buffer.
* The extra ESC delay you experience with non-`down` layout can be adjusted by reducing `timeoutlen` (see `:help timeoutlen`)

Having said that, I couldn't reproduce the problem with this command with minimal config.

```sh
command vim -Nu <(cat << EOF
call plug#begin('~/.vim/bundle')
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()
let rglistfiles = 'rg --files --hidden --glob "!*.class" --glob "!.idea/*" --glob "!**/.idea/*" --glob "!.git/*" --glob "!**/.git/*" --glob "!*.swp"'
" let g:fzf_layout = { 'down': '40%' }
command! -bang -nargs=* FuzzyOpenFiles call fzf#run(fzf#vim#with_preview(fzf#wrap({'source': rglistfiles, 'options': '--multi --reverse' })))
nnoremap <silent> <C-o> :FuzzyOpenFiles<cr>
EOF
)
```

**Comment by pylbrecht** [comment]
I'm also experiencing this, although I did not configure anything, except for `export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'` in my `.zshrc`.
Running fuzzy finding commands in fullscreen mode (`:Files!`, `:GFiles!`, etc.) results in the capital "I" being inserted by default.

Here's my `.vimrc`:
```
" auto-install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs 
     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

set nocompatible
set hidden

call plug#begin('~/.vim/plugged')


Plug 'arcticicestudio/nord-vim'
Plug 'dense-analysis/ale'
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'junegunn/fzf.vim'
Plug 'ludovicchabant/vim-gutentags'
Plug 'majutsushi/tagbar'
Plug 'mattn/calendar-vim'
Plug 'mhinz/vim-startify'
Plug 'morhetz/gruvbox'
Plug 'rust-lang/rust.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vimwiki/vimwiki'
call plug#end()

filetype plugin indent on

" gVim related settings
if has('gui_running')
    set guioptions-=m  "remove menu bar
    set guioptions-=T  "remove toolbar
    set guioptions-=r  "remove right-hand scroll bar
    set guioptions-=L  "remove left-hand scroll bar
    set guifont=SauceCodePro\ Nerd\ Font\ Medium\ 12
endif

" auto-wrap long lines for markdown files
augroup Markdown
  autocmd!
  autocmd FileType markdown set wrap
augroup END

" open splits more naturally
set splitright
set splitbelow

" set backup/swap dir
set backupdir=~/.vim/backup
set directory=~/.vim/swap

" copy everything to system's clipboard
set clipboard=unnamed

" map leader to SPACE
let mapleader = " "

" remap yank inconsistency
nnoremap Y y$

" backspace
set backspace=indent,eol,start

" encoding
set encoding=utf-8

" clear last search pattern
nnoremap <BACKSPACE> :noh<CR>

" highlight current line
set cursorline

" show line numbers
set number
set relativenumber

" tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_autofocus = 1

" split motion
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" easier moving code blocks
vnoremap < <gv
vnoremap > >gv

" keep 5 lines on top/bottom while scrolling
set scrolloff=5

" colorscheme
set t_Co=256
set background=dark
let g:gruvbox_italic=0
colors nord

" syntax highlighting
syntax on

" indentation
set tabstop=4
set shiftwidth=4
set expandtab

" search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

" vimwiki
let g:vimwiki_list = [{
	\ 'path': '~/notes',
	\ 'template_path': '~/.config/vimwiki/templates',
	\ 'template_default': 'default',
	\ 'syntax': 'markdown',
	\ 'ext': '.md',
	\ 'path_html': '~/notes/html/',
	\ 'custom_wiki2html': 'vimwiki_markdown',
    \ 'html_filename_parameterization': 1,
	\ 'template_ext': '.html'}]

" fzf mappings
map <Leader>f :GFiles!<Cr>
map <Leader><Leader>f :Files!<Cr>
map <Leader>b :Buffers!<Cr>
map <Leader>g :Rg!<Cr>
map <Leader>l :Lines!<Cr>

" Use ripgrep as grep prog
set grepprg=rg\ -S\ --vimgrep
set grepformat^=%f:%l:%c:%m

" nord theme
let g:nord_cursor_line_number_background = 1
let g:nord_bold = 1
let g:nord_italic = 1
let g:nord_italic_comments = 1
let g:nord_underline = 1

" vim-airline
let g:airline#extensions#cursormode#enabled = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" disable hunks/branch
let g:airline_section_b = ''
let g:airline_section_y = ''

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.linenr = ''

" startify
let g:startify_change_to_dir = 0

" ALE
let g:airline#extensions#ale#enabled = 1
let g:ale_completion_enabled = 1

let g:ale_python_pyls_config = {
      \   'pyls': {
      \     'plugins': {
      \       'pycodestyle': {
      \         'enabled': v:false
      \       }
      \     }
      \   },
      \ }
let g:ale_python_flake8_options = '--ignore=Q000'
let g:ale_python_bandit_options = '--skip B101'
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_save = 1
let g:ale_sign_error = '●'
let g:ale_sign_warning = '.'
map <Leader>d :ALEGoToDefinition<CR>
map <Leader>r :ALEFindReferences<CR>
```

**Comment by JoeHFB** [comment]
Hi @junegunn -

Thanks for the detailed response here.  My responses below:

> (By the way, I would not map it to CTRL-O, because CTRL-O is a pretty useful key in Vim.)

Hah, an old habit before I started using the jumplist... I remapped jumplist to `CTRL-J` and `CTRL-K` because of this + custom `Tab` remap and `CTRL-I` conflicting, but should really find another solution. Thanks for the reminder. 😄 

> Having said that, I couldn't reproduce the problem with this command with minimal config.

Huh, if you don't mind my asking, what kind of machine do you have and what vim version are you running?  Note that I couldn't reproduce this problem on my second machine where I have WSL 2 - I was only able to reproduce it on my Linux Mint 20 machine running vim 8.2.2425 - but even on that mint machine this issue doesn't happen on vim 8.2.2340.

> Have you tried without let g:fzf_layout = { 'down': '40%' }? Did you set it because you don't like the default pop-up layout?

Yes sir.  Looking at the comments that I had made on my vimrc, I remember that I wasn't a fan of the popup window and instead preferred to have the full screen fzf window.
```
" Disable fzf defaulting to pop up window in vim
" Source: https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48
let g:fzf_layout = { 'down': '40%'  }
```
The weird thing is that I remember that without `let g:fzf_layout = { 'down': '40%'  }` vim would open fzf in a floating popup back then, but now even when I disable this it doesn't seem to do that anymore. 🤔 But it still pre-inserts the `I` character. 

If I change my command to use your example (I installed `bat`), then it now shows a pop up if I don't use `let g:fzf_layout = { 'down': '40%'  }`.   Note that this doesn't pre-insert the `I` character.  It still has the delay with `ESC` character though.
![image](https://user-images.githubusercontent.com/60893676/107070737-b5afc600-67b1-11eb-8677-e6381fdd6e27.png)

On a whim I tried a few different things: 

### 1. Use your recommendation, but without the call to `fzf#wrap`:
`command! -bang -nargs=* FuzzyOpenFiles call fzf#run(fzf#vim#with_preview({'source': rglistfiles, 'options': '--multi --reverse'}))`
This still has the issue of pre-inserting the `I` character, and note that in both cases fzf is fullscreen - regardless of `let g:fzf_layout = { 'down': '40%'  }`  This also does **NOT have the delay with** `ESC`

With `let g:fzf_layout = { 'down': '40%'  }`:
![image](https://user-images.githubusercontent.com/60893676/107071364-949ba500-67b2-11eb-8531-aed9d26b416f.png)

Without `let g:fzf_layout = { 'down': '40%'  }`:
![image](https://user-images.githubusercontent.com/60893676/107071391-9e250d00-67b2-11eb-8e75-3206317cbd44.png)

### 2. Since you were thinking the problem might be with the `down` layout, putting `down` in the command without the fzf layout option.
1. remove `let g:fzf_layout = { 'down': '40%'  }`
2. Change to `command! -bang -nargs=* FuzzyOpenFiles call fzf#run(fzf#vim#with_preview({'source': rglistfiles, 'options': '--multi --reverse', 'down': '40%'}))`
3. This actually **fixes the problem** with `I` character getting pre-inserted.
4. This also immediately exits when I hit `ESC` as opposed to having a delay. 
![image](https://user-images.githubusercontent.com/60893676/107072430-1b04b680-67b4-11eb-8859-0b8f2f2388e5.png)
5. Using `'down': '100%'` here instead of `40%` makes it open fullscreen

Eh, kind of a hack, but it works for now I guess...

Is there anything else I can provide to help you narrow down the potential causes for the issue?

**Comment by rkmiec** [comment]
I can see, that issue was introduced within this commit in src/term.c file (if I remove added code it works properly again):
```
681fc3fa782e99fe69ed2c83c3e29109d2d61e1a is the first bad commit
commit 681fc3fa782e99fe69ed2c83c3e29109d2d61e1a
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Jan 14 17:35:21 2021 +0100

    patch 8.2.2345: no focus events in a terminal
    
    Problem:    No focus events in a terminal.
    Solution:   Add the t_fd and t_fe termcap entries and implement detecting
                focus events. (Hayaki Saito, Magnus Groß, closes #7673,
                closes #609, closes #5526)

 runtime/doc/term.txt | 14 +++++++++
 src/optiondefs.h     |  2 ++
 src/term.c           | 88 +++++++++++++++++++++++++++++++++++++++++++++++++++-
 src/term.h           |  8 +++--
 src/version.c        |  2 ++
 5 files changed, 111 insertions(+), 3 deletions(-)
```
I can reproduce (happens in 90% tries) the issue in gnome-terminal, but I couldn't reproduce it in alacritty (`$TERM=alacritty`) nor in xterm.
I use manjaro in VM, fish shell.

**Comment by nathan9sanders** [comment]
I started getting plagued by this issue recently (using vim and the kitty terminal emulator on OSX), and the fix was just to uninstall this obsolete plugin: https://github.com/tmux-plugins/vim-tmux-focus-events

Posting this here hoping that this may save someone a few hours of fiddling around with their environment.

**Comment by rkmiec** [comment]
> I started getting plagued by this issue recently (using vim and the kitty terminal emulator on OSX), and the fix was just to uninstall this obsolete plugin: https://github.com/tmux-plugins/vim-tmux-focus-events

For sure it was not the case in my setup. I never used tmux or such plugin.
I switched to neovim some time ago and the issue doesn't exist there.

**Comment by donsuhr** [comment]
I have had this issue for a long time. For me it is related to fullscreen fzf preview (perhaps the bang) and tmux (3.2a) with `set -g focus-events on`. Removing the focus-events from tmux resolves the issue in iTerm / terminal.app. I use focus-events with `christoomey/vim-tmux-navigator` so I live with it.
[https://github.com/junegunn/fzf/issues/434](fzf#434)
```
if executable('rg') && (exists(':Rg') != 2)
  " fzf#vim#with_preview([[options to wrap], [preview window expression], [toggle-preview keys...]])
  command! -bang -nargs=* Rg
        \ call fzf#vim#grep(
        \   'rg --column --line-number --no-heading --color=always --hidden --smart-case '.(len(<q-args>) > 0 ? <q-args> : '""'), 1,
        \   <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%', 'ctrl-/')
        \           : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%', 'ctrl-/'),
        \   <bang>0)
  nnoremap <Leader>zg :Rg!<CR>
endif
```

**Comment by mihaigalos** [comment]
Still reproducible on `Alpine 3.15` with `vim 8.2 2019 Dec 12, compiled Apr 28 2022 19:03:08` in `tmux 3.2a`.

**Comment by 097115** [comment]
@junegunn, @JoeHFB 

This ticket really shouldn't be closed: the problem does exist, and no workaround is available.

**Comment by mihaigalos** [comment]
> For me it is related to fullscreen fzf preview (perhaps the bang) and tmux (3.2a) with `set -g focus-events on`

Confirmed working with `.tmux.conf` in `tmux 3.3`:
```diff
-set -g focus-events on
+set -g focus-events off
```
I am not sure if this is fzf-specific.

**Comment by 097115** [comment]
@mihaigalos 

It's not an actual solution, though: many things need `focus-events` (like Vim's `FocusGained`, `FocusLost` autocommand events, etc).

**Comment by mihaigalos** [comment]
> @mihaigalos
> 
> It's not an actual solution, though: many things need `focus-events` (like Vim's `FocusGained`, `FocusLost` autocommand events, etc).

I agree. I however cannot pinpoint it to fzf, as it may be something zsh, tmux, vim or terminal-specific.

**Comment by 097115** [comment]
Or the Moon phase, too? :) You tried with `bash` may be? With some other terminal? You say you can't pinpoint, but did you actually tried first? And since you didn't, then what's the point of such statements?

`fzf` obviously fails to work correctly with this very common `tmux` option. So, I'd start with it, not the other way around.

**Comment by mihaigalos** [comment]
I am not sure why you're hating so much. Please go ahead and try to understand the problem and contribute something meaningful.
I'm not selling you anything, I think I have spent enough time replying.

If any of the actual contributors to this project need any input from me, please reach out and I would definitely help.

**Comment by 097115** [comment]
@mihaigalos 

Just don't spam issues with meaningless comments, and there will be no hate. You confirmed the erroneous behaviour? Good, no need to re-type the halfway crutch solution from the above comments. And certainly no need for baseless statements just to cloud the problem.

**Comment by nomme** [comment]
I started seeing this issue too. Wiping my whole vimrc except for fzf and fzf.vim made it disappear. Tracked it down to this line.
```vim
set term=xterm
```
I'm not sure why I have that set. It's been in my config since forever. I've removed it, the bug is gone, and I haven't experienced any other side effects. It seems to be automatically set to `tmux-245color`, which I assume is a better value anyway.

**Comment by Kellen275** [comment]
Seeing this except with two `I`s getting inserted.
* Vim 8.2
* fzf 0.54.1

Only line in .vimrc
```
set rtp+=~/.fzf
```

Command that produces inserted `I`s
```
vim -c "call fzf#run({'source': 'find'})"
```
![Screenshot from 2024-07-21 21-06-44](https://github.com/user-attachments/assets/539fd46c-1346-41cb-9013-6047ad66f37d)

**Comment by theposey** [comment]
> I started seeing this issue too. Wiping my whole vimrc except for fzf and fzf.vim made it disappear. Tracked it down to this line.
> 
> ```viml
> set term=xterm
> ```
> 
> I'm not sure why I have that set. It's been in my config since forever. I've removed it, the issue is gone, and I haven't experienced any other side effects. It seems to be automatically set to `tmux-256color`, which I assume is a better value anyway.

@hogklint this also "fixed" the issue for me. really weird, I don't have that set in my vimrc but ghostty is apparently setting it to a default of `xterm-ghostty`. Running ":set term=tmux-256color" like you have above resolves it. Seems pretty weird!

Another point of reference might be that this is only happening with `:Files!` for me for some reason. `:Buffers!` is ok. Pretty puzzling
