### ISSUE TITLE
Is it possible to set the default argument to fzf#vim#with_preview?

### ISSUE THREAD

**Issue by akawashiro** [junegunn/fzf.vim#1245]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Because I write the following setting in my `init.vim`, I can get a nice preview window as in the first image. However, I want to set some default argument (e.g. "foobaa") from a vim register to this preview window when I launch it such as in the second image. Is it possible?
Although I found the undocumented `placeholder` option of `fzf#vim#with_preview`, it didn't work for me.
```
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number -- '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0], 'options': '--delimiter : --nth 3..'}), <bang>0)
  ```
![current](https://user-images.githubusercontent.com/3770618/107645640-460f6e80-6cbc-11eb-852c-0c9f7e4162a4.png)
![want](https://user-images.githubusercontent.com/3770618/107645646-4871c880-6cbc-11eb-9198-71f00160308d.png)

**Comment by junegunn** [comment]
`fzf#vim#with_preview` is a decorator function that augments an `fzf#run` spec with more settings for enabling previewed.

```vim
:echo fzf#vim#with_preview({'options': '--reverse'})
:echo fzf#wrap(fzf#vim#with_preview({'options': '--reverse'}))

:call fzf#run({'options': '--reverse'})
:call fzf#run(fzf#wrap({'options': '--reverse'}))
:call fzf#run(fzf#wrap(fzf#vim#with_preview({'options': '--reverse'})))
```

So you need to learn how to use `fzf#run` function in the first place.

* https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

Try setting `--query` option of fzf like so

```vim
'options': ['--delimiter=:', '--nth=3..', '--query', some_variable_or_register]
```
(We used `options` in a list form not to deal with escaping issues)

**Comment by akawashiro** [comment]
Thank you for your detailed answer.

**Comment by akawashiro** [comment]
`command! -bang -nargs=* GCGrep call fzf#vim#grep('git grep --line-number -- '.shellescape(expand(<q-args>)), 0, fzf#vim#with_preview({'options': ['--query', expand('<cword>')], 'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)`  works well, thank you.
