### ISSUE TITLE
respect layout option on startup

### ISSUE THREAD

**Issue by fdietze** [junegunn/fzf.vim#125]
I have set the layout option in my vimrc:
```vim
 let g:fzf_layout = { 'down': '100%' }
```
This works when calling for example ```:Files``` from within vim.

But when I run
```sh
vim -c Files
```
I get the default layout.

(I'm using neovim)

**Comment by fdietze** [comment]
I just found that I can trigger fullsrceen with a ```!```. This also works from the command line, so this is solved for me.

**Comment by junegunn** [comment]
Okay, I can't reproduce the issue. Even if I start neovim with `-c Files`, the setting is respected.

Anyway, `let g:fzf_layout = {}` (no layout, while the default is down ~40%) is a way to tell fzf to always open in full screen.
