### ISSUE TITLE
Function fzf#shellescape, fzf#run and fzf#vim#files not found

### ISSUE THREAD

**Issue by dr3apap** [junegunn/fzf.vim#1252]
- [x ] I have fzf 0.23.0 or above
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [ x] I have searched through the existing issues

I have read all the formal issues and solution but none of them is related to my issue. I have fzf installed through my distro app manager. Fzf is located in /usr/bin/fzf  I installed fzf.vim through vim packages and it's located in ~/.vim/vim/pack/plugins/start/fzf.vim this was checked via script-names and it was loaded, I also brought in fzf to my vimrc rtp+= /usr/bin/fzf and I checked via echo &rumtimepath it  shows up. 

However when I called fzf through my mapping which was mapped to nnoremap <leader> pf :Files <CR> I got the above error. Error detected while processing function fzf#vim#with_preview, unknown function  fzf#shellescape, undefined variable preview_cmd, Error detected while processing function fzf#vim#files. Seem like the fzf binary whose define all those function is not been source or loaded as vim plugin. Pls advise. I have search all over the net for the solution also read some similar prob on reddit with zero solutiion.

**Comment by junegunn** [comment]
`/usr/bin/fzf` is a binary not a Vim plugin file, so adding it to `rtp` has no effect. You need to find where your package manager installs the Vim plugin file.

* e.g. If it installs the file as `/usr/local/opt/fzf/plugin/fzf.vim`, `set rtp+=/usr/local/opt/fzf`

But I recommend that you just follow the official instruction especially if you're not familiar with Vim plugin ecosystem. https://github.com/junegunn/fzf.vim#using-vim-plug

**Comment by timnovinger** [comment]
@junegunn `fzf.vim` is a file. When I cloned this repo it cloned it into `/home/tnovinger/.janus/fzf.vim/plugin/fzf.vim` but just in case the name of the directory was confusing things, I renamed it to `/home/tnovinger/.janus/fzf/plugin/fzf.vim`.

**Comment by junegunn** [comment]
Nope, it's the wrong file.

See https://github.com/junegunn/fzf.vim#installation

> you need to set up both "fzf" and "fzf.vim" on Vim.

**Comment by timnovinger** [comment]
@junegunn oh gotcha. So in my case because I'm using Pathogen, I simply need to clone BOTH repos into `/home/tnovinger/.janus`. That got it working, thanks! I think the confusion was because I added fzf.vim to my vim setup and installed the binary - this led me to think that I was done.
