### ISSUE TITLE
FZF colors defined in FZF_DEFAULT_OPTS.

### ISSUE THREAD

**Issue by kwinczek** [junegunn/fzf.vim#126]
How to make fzf.vim use colors defined in environment variable FZF_DEFAULT_OPTS?

**Comment by junegunn** [comment]
It does respect the options given that you correctly exported the variable.

**Comment by kwinczek** [comment]
I can't see how it wouldn't be exported correctly. Cmd fzf respects variable and settings presented in it. I am not sure why fzf.vim would ignore that.

**Comment by junegunn** [comment]
It works for me.

```sh
FZF_DEFAULT_OPTS='--color info:176,prompt:226' vim +Files
```

**Comment by kwinczek** [comment]
![fzf](https://cloud.githubusercontent.com/assets/796021/14604710/ad9be430-057d-11e6-91d4-28e236745536.gif)



Please have a look above for fg+ and pointer. It is different although the other settings seems OK.

**Comment by junegunn** [comment]
Maybe it's an issue of neovim terminal? I can't reproduce though.
Do you have the same issue with color codes greater than 15?

https://en.wikipedia.org/wiki/File:Xterm_256color_chart.svg

**Comment by kwinczek** [comment]
Spot on! No problems behind 15. That's why other codes work as expected.

**Comment by junegunn** [comment]
The appearances of the colors up to 15 are usually decided by the color scheme of the terminal. Not sure why it looks different on Neovim in your case.

**Comment by kwinczek** [comment]
Ah, had custom g:terminal_color_* colors specified! Apologies, did not suspect these things being connected. Thanks!

**Comment by junegunn** [comment]
Alright, I didn't know about those.
