### ISSUE TITLE
Preview.sh treats textual file with a single non-printable char as binary

### ISSUE THREAD

**Issue by vatosarmat** [junegunn/fzf.vim#1264]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

```
~/.local/share/nvim/site/plugged/fzf.vim/bin$ echo "Hello ^V" > file.txt
~/.local/share/nvim/site/plugged/fzf.vim/bin$ ./preview.sh file.txt
file.txt: application/octet-stream; charset=binary
```

**Comment by iiey** [comment]
I also have the same problem by grep function (using `fzf#vim#with_preview`) inside a file which has special character.
Preview window shows nothing but above message.
version: `fzf 0.27.2`, `fzf.vim e34f6c1 2021-05-25`

**Comment by timtyrrell** [comment]
Noticed this myself. I have no solution but this is the code that exits, I believe: https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh#L53

**Comment by timtyrrell** [comment]
@junegunn Verified the fix, bravo, thank you 🙇
