### ISSUE TITLE
preview.sh in Windows: newline ff problems

### ISSUE THREAD

**Issue by gilbh** [junegunn/fzf.vim#1270]
Hi

The preview.sh threw 4 errors until I ran
```
set ff=unix
```

and re-saved it. Otherwise, bash was not able to run. 

I am not sure if this is only a problem on my WSL but you might consider addressing.

Thanks
Gil

**Comment by dakyskye** [comment]
👍 thanks, I got preview working. Has to be fixed.

**Comment by gsuuon** [comment]
Fixed preview for me in windows as well, not using WSL
