### ISSUE TITLE
Passing arguments with spaces in placeholder

### ISSUE THREAD

**Issue by faisal-shah** [junegunn/fzf.vim#1275]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I'm trying to filter the result of taglist() and show the files in the preview window - at the proper tag offset within the file.

Here is what I have so far:

```
function! s:test() abort
    let results = []
    for tr in taglist(expand('<cword>'))
        call add(results, tr['filename'] . "\t" . tagfiles()[0] . "\t" . tr['cmd'])
    endfor
    echom (results)
    call fzf#run(fzf#wrap(fzf#vim#with_preview({
        \ 'source': results,
        \ 'sink': 'e',
        \ "placeholder": "--tag {1}:{2}:{3}",
        \ 'window': {'height': 0.9, 'width': 0.9},
        \ })))
endfunction
command! TestTagJump call s:test()
```

Below is the test .c file.
```
static int testA (void) {}
static int testA (int param) {}
testA();
```

... and the corresponding tag file generated
```
testA tmp.c /^static int testA (int param) {}$/;" f typeref:typename:int file:
testA tmp.c /^static int testA (void) {}$/;" f typeref:typename:int file:
```

My understanding is that tagpreview.sh expects an arguments like this for each match:
```
tmp.c:tag:/^static int testA (int param) {}$/;"
tmp.c:tag:/^static int testA (void) {}$/;"
```

I put the following in tagpreview.sh to see what was being passed to the script:
```
printf "FILE=$FILE\nTAGFILE=$TAGFILE\nEXCMD=$EXCMD\n\n"
```

I noticed that the EXCMD argument was being truncated after the space. This resulted in the following being passed to tagpreview.sh

```
tmp.c:tag:/^static
tmp.c:tag:/^static
```

The file shows up in the preview, but as we can predict from the above params being passed to tagpreview.sh, the correct line isn't highlighted/centered. Any clues what I'm doing wrong here?

**Comment by junegunn** [comment]
Adding `'options': ["--delimiter", "\t"]` to your run spec might help.

**Comment by faisal-shah** [comment]
> 'options': ["--delimiter", "\t"]

Thanks man, that worked!

How does the :Tags command do it? What delimiter is used to make sure the EXCMD is passed completely? Like, what if a \t shows up in the tag itself?

**Comment by junegunn** [comment]
I haven't really given much thought to the issue.
Maybe we should change the "placeholder" expression to `"--tag {1}:{2}:{3..}`?

**Comment by faisal-shah** [comment]
Is there a way to escape the delimiter in your field index expression parsing? What does the tags perl script use, because apparently that is robust to space and tabs?

Looking at the ctags format, it seems that the ex cmd field is terminated with a ". Maybe {3.."} would be a pragmatic solution.

In any case the white space handling/escaping has to be impedance matched between ctags, vim, shell, and preview.sh

**Comment by faisal-shah** [comment]
Also, {3..} wouldn't work if the field containing the delimiter occurred in the middle of {} .

**Comment by junegunn** [comment]
> Like, what if a \t shows up in the tag itself?

I don't think a tag can contain `\t`.

Tags command will fail if a file path contains `\t`, but let's be real. That is extremely unlikely in any sane project. I've never seen any project with a file with `\t` in its name.

**Comment by junegunn** [comment]
> > Like, what if a \t shows up in the tag itself?

> I don't think a tag can contain \t.

If you meant EXCMD (not tag), the trick here is to put the file path at the end of each line (which is what tags.pl does),

https://github.com/junegunn/fzf.vim/blob/caf7754b2636eabdf1bc11d30daccc5de66951ef/bin/tags.pl#L10

and to extract the last token from the selected line.

https://github.com/junegunn/fzf.vim/blob/caf7754b2636eabdf1bc11d30daccc5de66951ef/autoload/fzf/vim.vim#L907

So it doesn't matter if EXCMD contains `\t`.

**Comment by faisal-shah** [comment]
So I was wrong, :Tags is not immune to having \t in the function declaration (which ends up in the ex cmd). It is able to jump to the correct file, and preview the correct file for the reasons you outlined above. However, it doesn't jump to the correct line or preview the correct line due to the delimiter occurring within the field (as you can see below). I think the only way out of this is for the field index expression parsing to respect escape characters ..

![image](https://user-images.githubusercontent.com/37458679/116709839-af874b00-a996-11eb-819e-06dcb44929d6.png)
