### ISSUE TITLE
:Tags preview doesn't work properly when field delimiter present in ex command

### ISSUE THREAD

**Issue by faisal-shah** [junegunn/fzf.vim#1278]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

For example, if there is a tab character in a function declaration, the preview window in :Tags is unable to automatically scroll to the position of the tag. This is because the ex cmd used to jump to the appropriate line is truncated when it is passed to the preview.sh script. See below image for an example.

I propose a robust solution to this would need the field index expression parsing to be able to understand escape characters - so that the field separator character can be properly escaped in the {} string.

Related issues:
https://github.com/junegunn/fzf.vim/issues/1258
https://github.com/junegunn/fzf.vim/issues/1275 (closed without addressing the preview not working due to truncated ex command)

![image](https://user-images.githubusercontent.com/37458679/116747908-3a326f00-a9c4-11eb-8496-558bd8d87c0d.png)

**Comment by junegunn** [comment]
Using `{3..}` fixes the issue. We could use `{3..-2}`, but since EXCMD ends with `"` making Vim ignore the rest of the line, `{3..}` is good enough.
