### ISSUE TITLE
Breaks splits when used with { 'window': 'enew' }

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/fzf.vim#128]
Hello when I have,

`let g:fzf_layout = { 'window': 'enew' }`

enabled, after I perform a search using FZF my splits resize incorrectly. see images below for example:

1) Normal Layout
2) How I expect it to look
3) How it looks after fzf search in window

[![enter image description here][1]][1]
[![enter image description here][2]][2]
[![enter image description here][3]][3]

  [1]: http://i.stack.imgur.com/9XilV.png
  [2]: http://i.stack.imgur.com/m7DmL.png
  [3]: http://i.stack.imgur.com/dtMGX.png

**Comment by junegunn** [comment]
Is it still reproducible with this minimal configuration?

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
call plug#end()
let g:fzf_layout = { 'window': 'enew' }
```

**Comment by CrashyBang** [comment]
Hey @junegunn will test tonight and let you know.

Cheers,
Otis.

**Comment by CrashyBang** [comment]
Hey @junegunn,

Using:

```vim
call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'

call plug#end()

nnoremap <leader>f :Files <cr>'

nnoremap <leader>b :Buffers <cr>

let NERDTreeShowHidden=1

autocmd vimenter * NERDTree
```

I still get the error.

Steps to reproduce:

* `nvim file.name` (Open file)
* `ctrl + w - LeftArrow` (Navigate from NERDTree to main window)
* `:vsp` (This works fine)
* `:Files` (Search for and select a random file)
* `ctrl + w - LeftArrow` (Navigate to left most split)
* `:q` (Close left most split and enter split I previous did fzf search in)
* `:vsp` (Splits now broken)

I have attached a demoing gif I hope this helps.

![desktop-animation](https://cloud.githubusercontent.com/assets/2978850/14663741/f810b14e-0717-11e6-87ea-2e35950ce278.gif)

**Comment by junegunn** [comment]
Yeah, I could reproduce the problem. Thanks.
Please update the main fzf repo and it'll work fine.

By the way, you have a trailing `'` after `:Files <cr>`.

**Comment by CrashyBang** [comment]
Hey @junegunn,

Woop woop thank you!!!

The `'` is intentional I almost always use the exact match functionality.

Cheers,
Otis.
