### ISSUE TITLE
GitFiles: option to include untracked files

### ISSUE THREAD

**Issue by fdietze** [junegunn/fzf.vim#129]
Hi, would it be possible to include untracked files in ```GitFiles```?

```Files``` is not sufficient for me, because it also lists all the ignored files in the repository. And while working and creating new files, I cannot select them with ```GitFiles```.

**Comment by fdietze** [comment]
oh, actually ```Files``` takes care of .gitignore.

sorry!

**Comment by fdietze** [comment]
This is what I was looking for: https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795

**Comment by junegunn** [comment]
> oh, actually Files takes care of .gitignore.

Not by default, I guess you use ag as your `$FZF_DEFAULT_COMMAND`?

```sh
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
```

**Comment by fdietze** [comment]
Yes, thats it! Thanks for pointing it out.

**Comment by tnguyen14** [comment]
Is there a way to find files that are hidden files (`.bash_profile` for example) that is also gitignored?

I tried `export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'`, but that didn't find these files.

**Comment by tnguyen14** [comment]
Not sure if it's the right fix, but this did the trick for me
```
export FZF_DEFAULT_COMMAND='ag --hidden -U --ignore .git -g ""'
```

**Comment by john-kurkowski** [comment]
> Not by default, I guess you use ag as your `$FZF_DEFAULT_COMMAND`?

Is there a way to override the FZF command for _only_ `GitFiles`?

**Comment by junegunn** [comment]
@john-kurkowski `GitFiles` does not use `$FZF_DEFAULT_COMMAND`.

**Comment by john-kurkowski** [comment]
Ah, I misread. Your point in [the quoted comment](https://github.com/junegunn/fzf.vim/issues/129#issuecomment-211928402) was, the OP was already using ag for `Files` without knowing it.

So, `Files` and overriding `$FZF_DEFAULT_COMMAND` turned out to be sufficient for the OP.

**Comment by john-kurkowski** [comment]
What if I want to keep `Files`' behavior and only show untracked files for `GitFiles`? Any option there?

**Comment by junegunn** [comment]
`:GFiles --cached --others`

**Comment by john-kurkowski** [comment]
The command takes args! Got it! Thanks!

I saw `Files` had an options variable `g:fzf_files_options`. Guess that's not the case for `GitFiles`.

**Comment by john-kurkowski** [comment]
In addition to `--cached --others`, you may be interested in `--exclude-standard`.

**Comment by rdlugosz** [comment]
Came here to open a similar issue... For consistency with the output you'd get from `git status` and as a replacement for things like the CtrlP plugin, it would be better if the `GFiles` command used: `git ls-files --exclude_standard --cached --others` by default. 

In my experience, the additional output of `--others` is just the handful of new files you've created in a session and you'd typically want those to appear in the list of options to select from.

Thanks for a great piece of software!

**Comment by junegunn** [comment]
> For consistency with the output you'd get from git status

For `git status`, we now have `:GF?` (the full command is `:GFiles?` but it's okay to write only the prefix if there's no conflict).


Also please note that it's easy to define your own commands, so don't limit yourself to the stock commands.

```vim
command! MyGF call fzf#run(fzf#wrap({'source': 'git ls-files --exclude-standard --cached --others'}))
```

**Comment by rdlugosz** [comment]
Thx for the reply. I've already updated [my mapping for `C-P`](https://github.com/rdlugosz/dotfiles/blob/master/vimrc#L624); just thought that including the untracked files in the GF output was a more sensible default.

Am I correct in thinking that GF is the most likely thing ppl are using to replace other finders like CtrlP? I guess the drawback to GF is that you can't use it outside of git directories...

**Comment by junegunn** [comment]
> Am I correct in thinking that GF is the most likely thing ppl are using to replace other finders like CtrlP?

I don't know. I just use a customized version of `:Files` with `$FZF_DEFAULT_COMMAND` set to `rg --files`.

```vim
" Files with preview
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

" I use space leader, so it's space+space
nnoremap <silent> <expr> <Leader><Leader> (expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '').":Files\<cr>"
```

**Comment by rdlugosz** [comment]
> I don't know. I just use a customized version of :Files with $FZF_DEFAULT_COMMAND set to rg --files.

Wow - thanks for this tip... While setting up FZF I had missed the advantages of configuring ripgrep as the FZF command... It's way faster than the alternatives. Now that I have FZF set to use rg I'm just mapping `c-p` to `Files` instead of `GFiles`... works great whether or not I'm in a git repo.

**Comment by juanibiapina** [comment]
Regardless, the default option for GFiles should include `--cached --others --exclude-standard`.

**Comment by PezCoder** [comment]
Thanks guys, the mapping works like a charm. Can somebody mind explaining what these option means ?
From what I know:
`--others` : shows the untracked files
`--exclude-standard`: makes sure .gitignore is respected
`--cached`: no freaking clue how this help ?

**Comment by john-kurkowski** [comment]
> `--cached`: no freaking clue how this help ?

Try `git help ls-files`.

Looking at the blame of its docs [here](https://github.com/git/git/blame/v2.16.2/Documentation/git-ls-files.txt#L37), `--cached` has been the default for at least 10 years. I guess it doesn't help in this case!

**Comment by dakom** [comment]
> command! MyGF call fzf#run(fzf#wrap({'source': 'git ls-files --exclude-standard --cached --others'}))

This is great, but it's also showing deleted files, how would one _not_ list those?

**Comment by JoshMcguigan** [comment]
At least on my machine, running git 2.23.0, it seems `--cached` is not the default, despite the manual saying it is.

Running `git ls-files --others --exclude-standard` shows only non-committed files, but if I also include the `--others` flag I also see existing files.

**Comment by tony** [comment]
I got this working by using `&` in bash to combine outputs.

`git ls-files --recurse-submodules & git ls-files --exclude-standard --others`

This will give the normal, cached staged files, including submodule, and also append unstaged files (while respecting gitignore). However, it won't detect unstaged files in submodules.

While I'm here, I also have an `FZF_DEFAULT_COMMAND` that can ignore file extensions and globs, and fall back to `find`. If you'd like to take a peek: https://github.com/tony/.dot-config/blob/92de1834f8f204c279ba25e71107c5c435dba0cf/.zshrc#L91-L127

I'm able to open up FZF in my home directory and sanely lookup files with minimal junk/cruft.

`git ls-files` was always lightening fast though
