### ISSUE TITLE
How to close fzf windov

### ISSUE THREAD

**Issue by crozbo** [junegunn/fzf.vim#1291]
- [ x] I have fzf 0.23.0 or above
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [ x] I have searched through the existing issues

I have simple question: how to close fzf preview window? When I invoke any fzf command i can't exit/close window with Esc, I need to select something to close it. And before I use Ctrl-J and Ctrl-K to move on list, now that doesn't work?

**Comment by junegunn** [comment]
(I corrected the title to avoid confusion: `fzf preview window` -> `fzf window`.)

ESC should work. You can also hit CTRL-C to close fzf.

CTRL-J/K also should work as expected.

You might want to check if you have `tnoremap`s that override the keys.
Related: https://github.com/junegunn/fzf.vim/issues/1213

**Comment by crozbo** [comment]
I had `tnoremap`, and deleting that resolve my issue. Also I have Ctrl-j/k bindings, so after I delete it everything work. So all issues are on my side. Thank for helping me resolving this.
