### ISSUE TITLE
Status line was duplicate when popup window open.

### ISSUE THREAD

**Issue by gh-liu** [junegunn/fzf.vim#1293]
![image](https://user-images.githubusercontent.com/46311996/120260269-21b9bb00-c2c8-11eb-9470-569e2cdc21a7.png)

**Comment by bruhtus** [comment]
From https://github.com/junegunn/fzf/blob/master/README-VIM.md#hide-statusline:
> When fzf starts in a terminal buffer, the file type of the buffer is set to fzf. So you can set up FileType fzf autocmd to customize the settings of the window.

So you can temporarily disable statusline by using autocmd like this:
```vim
autocmd! FileType fzf set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
```

**Comment by gh-liu** [comment]
thx
