### ISSUE TITLE
getting output of git diff master into fzf

### ISSUE THREAD

**Issue by fakeharxy** [junegunn/fzf.vim#1294]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I have been searching and reading for literally hours, sorry if this is the wrong place to request help. All I am trying to do is pump something like `git diff --name-status master` into a fzf preview window so I can see at a glance what files are different from master and open them within vim. I've tried a lot of things but couldn't get anything to work; I have also tried just using fzf without the .vim plugin but couldn't get that to work either. It feels like it should be easy to do but either way, I've failed.

**Comment by junegunn** [comment]
Have you tried `:GF?` command (short for `:GFiles?`)?

**Comment by fakeharxy** [comment]
Thanks for replying so quicky! 

That command is great for staged changes and what not. What I'm looking for is: even if I have staged and commit, the files that are different from master...

**Comment by junegunn** [comment]
This will get your started.

```vim
function! s:list_branches(typed, ...)
  let branches = systemlist('git branch | cut -c 3-')
  if empty(a:typed)
    return branches
  endif
  return filter(branches, { idx, val -> stridx(val, a:typed) >= 0 })
endfunction

function! s:diff_branch(branch)
  let branch = len(a:branch) ? a:branch : 'master'
  let source = 'git diff --name-status ' .. branch
  let preview = 'git diff --color=always devel -- {-1}'
  let spec = { 'source': source, 'options': ['--preview', preview] }
  function spec.sink(match)
    execute 'e' split(a:match, "\t")[-1]
  endfunction

  call fzf#run(fzf#wrap(spec))
endfunction

command! -nargs=? -complete=customlist,s:list_branches DiffBranch call s:diff_branch(<q-args>)
```

**Comment by fakeharxy** [comment]
Yes! This is basically working (thank you!) but the preview is saying: fatal: bad revision 'devel'

is there something wrong with the line below?

`let preview = 'git diff --color=always devel -- {-1}'`

**Comment by junegunn** [comment]
Yeah, updated the above code.

**Comment by fakeharxy** [comment]
ah, should have spotted that myself :( all working, many thanks.
