### ISSUE TITLE
Command failed: rg --column --line-number --no..

### ISSUE THREAD

**Issue by bsde1234** [junegunn/fzf.vim#1297]
- [x] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I installed fzf in vim with vim-plug using 
```
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }                             
Plug 'junegunn/fzf.vim' 
```
Somewhere I heard Rg is shipped with fzf.vim. Do I need to install ripgrep in my system to work `:Rg` command?

**Comment by junegunn** [comment]
Yes.
