### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf.vim#13]
http://junegunn.kr/2015/03/browsing-git-commits-with-fzf/

**Comment by simonweil** [comment]
Nice!
I changed my git_log alias to your function :)
Maybe add `--no-ext-diff` to `git diff`, I needed it to prevent my default diff tool to run.

**Comment by junegunn** [comment]
Added `Commits` command. You can see the contents of the selected commits with <kbd>Enter</kbd>, <kbd>CTRL-X</kbd>, <kbd>CTRL-V</kbd>, <kbd>CTRL-T</kbd>, diff against the current file with <kbd>CTRL-D</kbd> :)
