### ISSUE TITLE
Lines command has input prompt at top in contrast to other commands

### ISSUE THREAD

**Issue by ronakg** [junegunn/fzf.vim#130]
The title says it all. The Lines command show input prompt at the top, whereas other commands have input at bottom. It just breaks the flow.

Is this intended behavior or just an inconsistency that got in.

**Comment by junegunn** [comment]
It's intentional. `BTags` also works the same.
Without `--reverse` option, the lines in the files will be shown in the reverse order (bottom-up) and I felt it was very awkward. If you don't like this default, you can redefine the command using `fzf#vim#lines()` function.

```vim
call fzf#vim#lines({'down': '~40%', 'options': '--no-reverse'})
```
