### ISSUE TITLE
:Files gives error [Command failed: cat '/tmp/v8STSj8/13']

### ISSUE THREAD

**Issue by manaskarekar** [junegunn/fzf.vim#1301]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am new to fzf.vim and it has changed my life. Thank you for this.

I'm using it pretty much as it came except for some shortcuts.

- gvim [VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)].
- Lubuntu 18.04LTS
- bat 0.15.4 (I was a bat user already, I did not touch anything after installing fzf, nor did I configure fzf to use `bat`).
- fzf binary version 0.27.3
- fzf.vim installed through Vundle, latest.
- Seen this issue on two different computers running the same version of softwares/OS.

(I did not try the minimal configuration yet, because the problem arises after some time when tmp files are cleared. Although I will leave an instance running to try and replicate the issue).

I looked through issues #996, #260, #642, and some more without a clear answer.

----------
So the issue is that `:Files` command works great for some time. After some amount of use though, when I try to use `:Files`, it fails with a failure to `cat` some now-cleared tmp file.

`[Command failed: cat '/tmp/v8STSj8/13']`

When I go to the `tmp` folder and check, the file is indeed missing and there's usually a different file, like some higher number than 13 in this case.

As expected, restarting vim fixes the issue but only till the next time it fails. Once it has failed, it is not possible to get it to work without restarting vim.

Any help appreciated!

Thank you.

**Comment by junegunn** [comment]
> After some amount of use

How much time? Maybe your system is clearing up temp directories Vim was using every few days.

```sh
cat /usr/lib/tmpfiles.d/tmp.conf
```

**Comment by jreybert** [comment]
I encounter the same issue.

With vim 7.4, I get the following behavior.

* I open one or multiple files
* I type the command `:Buffers`
* it shows the openeds files
* I press Escape or ^C
* I get the following error:
```
Error detected while processing function fzf#vim#buffers..<SNR>79_fzf..fzf#run:
line   75:
E488: Trailing characters
```
* Any following `:Files` command will produce this error:
`[Command failed: cat '/tmp/vvVAe5V/5']`

With vim 8.0, the behavior is sighlty different:

* I open one or multiple files
* I type the command `:Buffers`
* The following error appears briefly:
```
Error detected while processing function fzf#vim#buffers..<SNR>79_fzf..fzf#run:
line   75:
E488: Trailing characters
```
* it shows the openeds files
* I press Escape or ^C
* Any following `:Files` command will produce this error:
`[Command failed: cat '/tmp/vvVAe5V/5']`

Anyway, I just use `:Files` command, I don't get any errors.

**Comment by jreybert** [comment]
in fzf (not fzf.vim), reverting to junegunn/fzf@7411da8d5a37b94b2171920c82c0dafe6f9115b6~1 seems to fix the issue. junegunn/fzf@7411da8d5a37b94b2171920c82c0dafe6f9115b6 seems to be the culprit here.

**Comment by manaskarekar** [comment]
> > After some amount of use
> 
> How much time? Maybe your system is clearing up temp directories Vim was using every few days.
> 
> ```shell
> cat /usr/lib/tmpfiles.d/tmp.conf
> ```

Sorry I didn't see your post until now. I thought that may be the case, but it didn't seem to happen after a set amount of time. It happens, as @jreybert mentioned, after using the buffers command and then trying to use the files command.

**Comment by wendx** [comment]
I also encountered the same problem. 
After executing the command :BTags<cr>
and then executing :FZF<cr>
this error occurred:
[command failed: cat '/tmp/vYylukm/10']

Rolling back to junegunn/fzf@7411da8 also can not solve the exception。

**Comment by jreybert** [comment]
@wendx you must roll back to junegunn/fzf@7411da8~1 (1 commit before) which is 3f75a8369f63f2bd6ac3686fc5d88f2bc128e610

**Comment by wendx** [comment]
> @wendx you must roll back to [junegunn/fzf@7411da8](https://github.com/junegunn/fzf/commit/7411da8)~1 (1 commit before) which is [junegunn/fzf@3f75a83](https://github.com/junegunn/fzf/commit/3f75a8369f63f2bd6ac3686fc5d88f2bc128e610)

@jreybert Rolling back to junegunn/fzf@3f75a83 is still abnormal. Do I need other operations after the rollback?

**Comment by jreybert** [comment]
No other operation on my side. It works and improve things on two different setups (vim 7.4 and vim 8.0)

**Comment by jw-mcgrath** [comment]
Thanks @jreybert this worked for me!

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by wendx** [comment]
> I can't reproduce the problem. Can you check if you still have the issue with the following minimal vimrc?
> 
> ```shell
> vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
> ```
> 
> (https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

There are still exceptions when using this .vimrc. The operation process is as follows:
(1) open file  : FZF 
(2) jump to function  : BTags （A prompt message appears：Vim(unlet):E488: Trailing characters）
(3) encountered an exception while trying to open another file  : FZF （A prompt message appears：[Command failed: cat '/tmp/vsirqvi/10']）

**Comment by SelvamArul** [comment]
rolling back to junegunn/fzf@3f75a83 solves the issue for me

**Comment by junegunn** [comment]
What's your `$SHELL` and `&shell`?

```vim
:echo &shell
:echo $SHELL
```

If you get `/some/shell`, does `/some/shell -c "cat '/some/file'"` work as expected?

**Comment by junegunn** [comment]
> execute ": q" to close the file, and it will automatically open the file

I think you're confused here. The file is already opened in a different "tab" before you close the current buffer on the current tab with `:q`. You can hit `gt` to move between the tabs.

**Comment by junegunn** [comment]
So two things to check:

1. What does `:echo $FZF_DEFAULT_COMMAND` report after you run into the problem?
2. Which version of Vim or Neovim are you running? Have you tried upgrading it?

**Comment by wendx** [comment]
> So two things to check:
> 
> 1. What does `:echo $FZF_DEFAULT_COMMAND` report after you run into the problem?
> 2. Which version of Vim or Neovim are you running? Have you tried upgrading it?

1.`:echo $FZF_DEFAULT_COMMAND` report：cat '/tmp/vhYEigb/17'
2.My current version VIM is：version 7.4.1689，I use VIM on our company's server and do not have administrator rights, so I cannot upgrade it.

**Comment by wendx** [comment]
> Okay, it looks like `unlet $FZF_DEFAULT_COMMAND` doesn't work at all on Vim 7.4.
> 
> * [`:unlet $FOOBAR` vim/vim#1116](https://github.com/vim/vim/issues/1116) (added in Vim 8)
> 
> Can you test this patch?
> 
> ```diff
> diff --git a/plugin/fzf.vim b/plugin/fzf.vim
> index 4190e0e..b17361d 100644
> --- a/plugin/fzf.vim
> +++ b/plugin/fzf.vim
> @@ -519,7 +519,8 @@ finally
>      if len(prev_default_command)
>        let $FZF_DEFAULT_COMMAND = prev_default_command
>      else
> -      execute 'unlet $FZF_DEFAULT_COMMAND'
> +      let $FZF_DEFAULT_COMMAND = ''
> +      silent! execute 'unlet $FZF_DEFAULT_COMMAND'
>      endif
>    endif
>    let [&shell, &shellslash, &shellcmdflag, &shellxquote] = [shell, shellslash, shellcmdflag, shellxquote]
> ```

This patch can fix the issue.
BTW：I tested it on the VIM version 8.0.1453, and the exception also exists. Rolling back to: 3f75a8369f63f2bd6ac3686fc5d88f2bc128e610
can solve the problem.
@jreybert  also mentioned earlier that he tested it on vim8.
