### ISSUE TITLE
Floating window in a not closable state 

### ISSUE THREAD

**Issue by jakecastelli** [junegunn/fzf.vim#1303]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

First of all, thanks for the amazing work 🚀 

**The way to reproduce is:**
1. Open any window, in my case I opened `GFiles`
2. Press `C-\` + ` n` then press `C-w` + `j`
3. At this time you will notice that you are outside of floating window, but you will not be able to come back and the window will floating there in a not closable state.

**Comment by EdwarKenedy** [comment]
hi, did you  try using ```<c-w>w```

**Comment by jakecastelli** [comment]
Hi @EdwarKenedy `<C-w>w` will be able to get me back to the floating window, thanks 👍
