### ISSUE TITLE
Ripgrep matching is inconsistent

### ISSUE THREAD

**Issue by Rheisen** [junegunn/fzf.vim#1315]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Within the README there exists a section dedicated to Ripgrep. I've added the RipgrepFzf function to my init.vim, but I've noticed that the RipgrepFzf function does not return all of the matches that the default Rg command finds (in a golang codebase it appears to find function definitions, but not function usage for example). Function for context:

```
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, shellescape('{q}'))
  let spec = {'options': ['--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

nnoremap <leader>ft :RG<cr> 
```
* Slightly modified from the excerpt from the README in my attempts to fix it

I've also found that using the updated Rg command supplied by the README works well, but it requires me to source my init.vim file when I open Neovim in order for the command to not act like the default Rg command (with no preview window). Command for context:

```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case -- '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

nnoremap <leader>ft :Rg<cr> 
```

I don't actually have both of these nnoremap statements in my init.vim file at play at the same time (they are in each code block for context).

It would be great if someone could explain why the RipgrepFzf function isn't finding the same matches, or how the override of the Rg command could be applied immediately (e.g. not require sourcing my init.vim file each time I open nvim).

**Comment by bruhtus** [comment]
> * Slightly modified from the excerpt from the README in my attempts to fix it
> 
> I've also found that using the updated Rg command supplied by the README works well, but it requires me to source my init.vim file when I open Neovim in order for the command to not act like the default Rg command (with no preview window). Command for context:
> 
> ```
> command! -bang -nargs=* Rg
>   \ call fzf#vim#grep(
>   \   'rg --column --line-number --no-heading --color=always --smart-case -- '.shellescape(<q-args>), 1,
>   \   fzf#vim#with_preview(), <bang>0)
> 
> nnoremap <leader>ft :Rg<cr> 
> ```
> 
> I don't actually have both of these nnoremap statements in my init.vim file at play at the same time (they are in each code block for context).
> 
> It would be great if someone could explain why the RipgrepFzf function isn't finding the same matches, or how the override of the Rg command could be applied immediately (e.g. not require sourcing my init.vim file each time I open nvim).

Have you tried `:command Rg` before and after you source init.vim and see the command?

From the source code: https://github.com/junegunn/fzf.vim/blob/b1afeca8cc02030f450bf1feee015d40988f86e3/plugin/fzf.vim#L57

I don't need to configure the command and the preview window already appear for me, so I'm not sure what's the difference.

Maybe you can make a simpler version of your init.vim that only contain fzf and see how that goes.

**Comment by junegunn** [comment]
> RipgrepFzf function does not return all of the matches that the default Rg command finds

Because they are different. In the default Rg, ripgrep process returns the matches for the initial query (which can be an empty string), and fzf performs the secondary fully filtering over the matches. In RipgrepFzf, there is no fuzzy matching, ripgrep process is restarted every time you update the query string on fzf. You might want to read the section again. https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration

Related: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration

**Comment by Rheisen** [comment]
@bruhtus When I run :command Rg initially, It is set to :call s:Rg(<q-args>). After I source my init.vim again it gets set to the override I have in place

**Comment by bruhtus** [comment]
> @bruhtus When I run :command Rg initially, It is set to :call s:Rg(<q-args>). After I source my init.vim again it gets set to the override I have in place

@Rheisen That is indeed weird, now try using `:verb command Rg` to see where the last time `Rg` command got set. The output have this kind of pattern:
```
<the-command-info> (command name, args address complete, definition)
Last set from path/to/directory/the-filename <line-number>
```
