### ISSUE TITLE
How to change the Rg preview window color scheme?

### ISSUE THREAD

**Issue by gor-bit** [junegunn/fzf.vim#1317]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

On my terminal (iTerm2), the current color scheme of the default Rg preview window currently makes the line numbers very difficult to read. The screenshot below shows what this looks like using the Vim minimal configuration.

I'd like to update the Rg preview window (I believe it uses `bat`) to use the `base64` color scheme.

i.e. Set `bat --theme=base16` instead of the current `bat`.

How can I update the vim plugin to do this? I can't find where `bat` is called anywhere within the code.

Thanks!

<img width="1239" alt="Screen Shot 2021-08-22 at 11 31 48 pm" src="https://user-images.githubusercontent.com/68799734/130357116-a98acc56-da10-4041-8e50-8fa898224e21.png">

**Comment by savchenko** [comment]
Add `'--preview',  'bat --some_bat_parameter'` to the `fzf#vim#grep` options. `fzf_opt_rg` in the example below:
```vim
command! -bang -nargs=* Rg call fzf#vim#grep(fzf_cmd_rg .shellescape(<q-args>), 1, fzf#vim#with_preview({'options': fzf_opt_rg}), <bang>0)
```

**Comment by junegunn** [comment]
Put `export BAT_THEME=base16` in your shell configuration file or `let $BAT_THEME = 'base16'` in your Vim configuration file.
