### ISSUE TITLE
[Question] How do I implement `:Files` in my `.vimrc`?

### ISSUE THREAD

**Issue by paniash** [junegunn/fzf.vim#1318]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Hi! I have fzf installed and love using the utilities in fzf.vim. However, I noticed that I really only use the `:Files` command from fzf.vim and was wondering how I can implement the command in my own `.vimrc`.

Thanks!

**Comment by bruhtus** [comment]
Is implement here means key binding/keyboard shortcut?

If it is, you can do something like this:
```vim
nnoremap <leader>f :Files<CR>
```

If you press your leader key and f, it will execute `:Files` command.

**Comment by paniash** [comment]
@bruhtus I didn't mean keybinding. What I meant was, instead of installing the entire plugin `fzf.vim`, I'd like to just implement `:Files` command in my `.vimrc` and call the fzf binary within vim.

**Comment by junegunn** [comment]
You might want to read though README-VIM.md again. It should give you enough hint on how to define custom commands.

This isn't identical to the stock :Files, but you get the idea.

```vim
command! -bang -complete=dir -nargs=? Files
    \ call fzf#run(fzf#wrap({'dir': <q-args>, 'options': ['--preview', 'bat --color=always {}']}, <bang>0))
```

**Comment by paniash** [comment]
@junegunn Thank you!
