### ISSUE TITLE
Search only file contents not filename

### ISSUE THREAD

**Issue by TamaMcGlinn** [junegunn/fzf.vim#1319]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I'm using the `:Rg` command which calls `fzf#vim#grep()`, and has this unexpected behaviour; it returns results that match on the filename and line number inside that file. For instance, if you search for `'42` (the literal number 42), you get every single file that has at least 42 lines as a match.

**Comment by bruhtus** [comment]
You might want to read this: https://github.com/junegunn/fzf.vim/issues/714#issuecomment-428802659
