### ISSUE TITLE
YAML field completer guidance

### ISSUE THREAD

**Issue by boulderob** [junegunn/fzf.vim#1321]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

This isn't so much an issue as just a question for guidance.  I'm trying to customize  `fzf#vim#complete` to work but i obviously don't understand what the `source` needs to be because the following code is telling me it's an "Invalid source type".  I'm trying to mimic the examples given in the project documentation as my only source of reference here.

My goal is to create a "known" yaml field completer with a list of values tied to given predefined fields which i declare in a  dictionary here.  I actually thought something like this would already exist (and probably does) but I couldn't find it after literally searching all of yesterday and today online with nothing even close to a solution.  I figured I might be able to roll my own with vim-fzf.  Hopefully it's easy to gather the intent from my pasted code here.   The code functionality is obviously not complete because i just want to make sure i can find a single 'ctry' and get my source lookup on the prefix correct before it gets any more complicated.   Actually the regex check is probably not accurate for vimscript syntax either but you get the gist.

I'm running a simple test just sourcing this scriptfile on it's own.

```vim
function! Fzfyml(prefix)
  let compL = {
        \ 'ctry' : [ 
        \    "France" ,
        \    "Italy" ,
        \    "Italy" ,
        \    "Spain" 
        \  ],
        \ 'reg' : [ 
        \    "rega" ,
        \    "regb" ,
        \    "regC" ,
        \    "regD" 
        \  ],
        \ 'sub1' : [ 
        \    "subreg1" ,
        \    "subreg2" ,
        \    "subreg3" 
        \  ]
        \ }

  for [key, value] in items(compL)
    if key == a:prefix
      return items.key
    endif
  endfor

  "return []
endfunction

inoremap <expr> <c-x><c-s> fzf#vim#complete({
  \ 'prefix': '^ctry.*: ',
  \ 'source':  function('Fzfyml'),
  \ 'options': '--multi --reverse --margin 15%,0',
  \ 'left':    20})
```
Here's a simple text file to test against

```
ctry: <cursor here or similar>
reg:
sub1:
sub2:
```

Any help greatly appreciated.   If another way to do this exists I'm all ears.  It would seem a pretty common thing to do but you have to be able to specify the dataset to complete with.

**Comment by junegunn** [comment]
To be honest, I don't think `fzf#vim#complete` function is capable enough for implementing such context-aware completions. But anyway, here's a modified version that kind of works.

```vim
function! Fzfyml(prefix)
  let compL = {
        \ 'ctry' : [
        \    "France" ,
        \    "Italy" ,
        \    "Italy" ,
        \    "Spain"
        \  ],
        \ 'reg' : [
        \    "rega" ,
        \    "regb" ,
        \    "regC" ,
        \    "regD"
        \  ],
        \ 'sub1' : [
        \    "subreg1" ,
        \    "subreg2" ,
        \    "subreg3"
        \  ]
        \ }

  let line = getline('.')[0:col('.')]
  for [key, values] in items(compL)
    if stridx(line, key .. ': ') >= 0
      return values
    endif
  endfor

  return []
endfunction

inoremap <expr> <c-x><c-s> fzf#vim#complete({
  \ 'source':  function('Fzfyml'),
  \ 'options': '--multi --reverse --margin 15%,0',
  \ 'reducer': { lines -> len(lines) > 1 ? string(lines) : lines[0] },
  \ 'left':    20})
```
