### ISSUE TITLE
Automatic Insert Mode Instead of Normal Mode

### ISSUE THREAD

**Issue by sozoalvin** [junegunn/fzf.vim#1323]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Dear all, Im having an erratic behavior with my set up I think. 

Trying all commands such as , :FZF :Files, :Rg etc and selecting to open any buffer would create the buffer in **insert** mode. Can I check if this is the default behavior? 

If yes, are there any ways to change the behavior to a normal mode instead after a buffer has been selected to open? 

Ive tried searching for answers across several channels without any avail. Any help would be greatly appreciated

**Comment by sozoalvin** [comment]
i should add that this is my config in ~/.vimrc file

```" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Enable per-command history.
" CTRL-N and CTRL-P will be automatically bound to next-history and
" previous-history instead of down and up. If you don't like the change,
" explicitly bind the keys to down and up in your $FZF_DEFAULT_OPTS.
let g:fzf_history_dir = '~/.local/share/fzf-history'

nmap <C-f> :Files<CR>
nmap <leader>b :Buffers<CR>
nnoremap <leader>g :Rg<CR>
nnoremap <leader>t :Tags<CR>
nnoremap <leader>m :Marks<CR>

let g:fzf_tags_command = 'ctags -R'
" Border color
let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Todo', 'border': 'sharp' } }

let $FZF_DEFAULT_OPTS = '--layout=reverse --info=inline'
let $FZF_DEFAULT_COMMAND="rg --files --hidden"

" FZF uses bat as the previewer. Without bat, your preview has no colors.

" Customize fzf colors to match your color scheme
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

"Get Files
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)


" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

" Git grep
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)

**Comment by sozoalvin** [comment]
I apologize for bringing up this issue. 

Finally found this piece of coding hiding in init.config in nvim while i spent hours searching in.vimrc instead. 

```au TermClose * call feedkeys("i")```

I had this code somewhere that enables an embedded neomvim terminal window to exit automatically to the previous buffer without having the need to press any other key. Never knew the "i" key was pressed.

I changed it to "d" and my fzf , rg files etc now opens buffers in normal mode instead of insert. The "i" key must be messing with throwing buffers in insert mode. 

Will close it now. Thank you for your help, development and powering the shell/ vim users who user fzf for all kinds of things. 

Hope my findings in this comment can help somebody.

**Comment by sdondley** [comment]
Thanks for writing up this issue. You have saved me a lot of time tracking this down.

I was having the same exact problem. I had:

```
autocmd TermOpen * startinsert
au TermClose * call feedkeys("i")
```

Since I only needed these commands when editing text files, doing this fixed things up nicely:

```
autocmd TermOpen *.txt startinsert
au TermClose *.txt call feedkeys("i")
```
