### ISSUE TITLE
What does ctrl-i hot key standing for?

### ISSUE THREAD

**Issue by IzaGz** [junegunn/fzf.vim#1333]
when searching in bottom panel moving between foundings and pressing ctrl+i there appears pink arrow or magenta colored at left side of the file path/name , what does it mean? where is it in documentation?

**Comment by junegunn** [comment]
[CTRL-I is tab](https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode). Tab key is used to multi-select items.

* https://github.com/junegunn/fzf#usage
