### ISSUE TITLE
Having trouble using Ag

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/fzf.vim#135]
Hey so I have `Ag` installed and when I run `:Ag` on my smaller projects it works fine and indexes everything, when I run on larger projects `:Ag` has only indexed a few files, is this the expected behaviour I am new to `Ag` had never heard of it before looking through the docs so please let me know if I am simply using it wrong.

I did look through all the issues and do some Googling to try and resolve my issue but couldn't find anything really relevant.

Cheers.

**Comment by junegunn** [comment]
> is this the expected behaviour 

Nope. Check if `ag KEYWORD` on the shell has the same issue. ag is basically a faster version of grep.

https://github.com/ggreer/the_silver_searcher

**Comment by CrashyBang** [comment]
Hey @junegunn,

> ag is basically a faster version of grep

That was my understanding, in that case no my `fzf.vim` is returning far less results than `ag` on the shell.

What would be the way to capture the results to demo this to you?

Cheers,
Otis.

**Comment by junegunn** [comment]
```sh
cd /tmp
git clone --depth 1 https://github.com/vim/vim
cd vim

# Remember the number of matches (over 44K)
ag --nogroup --column vim | wc -l

# Is the number the same?
vim +'Ag vim'
```

If not, please post the screenshot, and you can try again with this minimal vim configuration

https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/1d7fd214124da32c8f652ba1f68e0ad3cb4151cd/vimrc

```sh
vim -u <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/1d7fd214124da32c8f652ba1f68e0ad3cb4151cd/vimrc)
```

**Comment by CrashyBang** [comment]
Hey @junegunn shit I am so sorry it was to do with `ag` default behaviour I knew it could skip over files in the `.gitignore` but didn't realise it did this by default so I thought my `bower_components` etc... would be indexed I now realise this is not the case, so sorry to waste your time, could I potentially submit a PR with some extended docs on the `ag` functionality to help reduce problems like mine?

**Comment by junegunn** [comment]
No problem. I don't think extra doc is necessary. Most users already know that ag handles gitignore, and many of them [use it just for that reason](https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore).
