### ISSUE TITLE
wired first line (prefixed with some wired characters and full path)

### ISSUE THREAD

**Issue by limboy** [junegunn/fzf.vim#1351]
- [ x ] I have fzf 0.23.0 or above
- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

<img width="380" alt="image" src="https://user-images.githubusercontent.com/35974/147667581-51a219b8-4dda-4583-a3c9-6cdf6dfb410c.png">

- reinstall `fzf` / `fzf.vim` didn't help
- both vim and Neovim has this problem
- this line exists every time no matter in which folder
- this line represents a file, but is prefixed some unnecessary characters and full path.
- run pure `fzf` command don't have this problem (`.vim/plugged/fzf/bin/fzf`)
- had searched google but without luck
- when selected and enter, output this message

<img width="647" alt="image" src="https://user-images.githubusercontent.com/35974/147667779-882c31d4-1c47-489b-9c8b-6ce414dc5036.png">

this plugin is so convenient, but this problem is driving me nuts, hope anyone can give me a clue. many thanks!

**Comment by junegunn** [comment]
Please post the output of the following commands:

```sh
:echo $SHELL
:echo &shell
```

**Comment by limboy** [comment]
> Please post the output of the following commands:
> 
> ```shell
> :echo $SHELL
> :echo &shell
> ```

the result are both `/bin/zsh`

**Comment by junegunn** [comment]
Ok, then run this command and see if you see anything other than "hello"

```sh
vim <(/bin/zsh -c 'echo hello')
```

**Comment by limboy** [comment]
> Ok, then run this command and see if you see anything other than "hello"
> 
> ```shell
> vim <(/bin/zsh -c 'echo hello')
> ```

yes, the "magic" characters appear!

https://user-images.githubusercontent.com/35974/147725370-acd11669-391b-4a39-82b2-79404ac37ab1.mov

**Comment by junegunn** [comment]
So that's not cool, and you have to fix your zsh configuration so that those magic stuff are not printed in non-interactive sessions. (i.e. `[[ -o interactive ]]`)

* https://unix.stackexchange.com/a/600541/62171

**Comment by limboy** [comment]
thanks for @junegunn point to the right direction. after some dig, it turns out `~/.oh-my-zsh/lib/termsupport.zsh` is THE FILE that caused the wired behavior.

to get around the problem, just create an empty file named `termsupport.zsh` under `~/.oh-my-zsh/custom/lib`, so that omz will load this file instead of the builtin one.
