### ISSUE TITLE
Files command not working with cmd, may be shell escape issue (but FZF is working)

### ISSUE THREAD

**Issue by icthus56** [junegunn/fzf.vim#1371]
- [ X ] I have fzf 0.23.0 or above
- [ X ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ X ] I have read through the manual page of fzf (`man fzf`)
- [ X ] I have searched through the existing issues

In gvim when launching fzf via files, the following external command is executed:
<b>C:\WINDOWS\system32\cmd.exe /c (^(C:\Users\leessy\vimfiles\bundle\fzf/bin/fzf --version --no-height^) >C:\Users\leessy\AppData\Local\Temp\VIo13CB.tmp 2>^&1</b>

There seems to be an issue with the "2>^&1" as passing "2>&1" directly to the gvim command line results in a successful execution. The full path to fzf binary is given, so that is not the issue.

See below for the error that results from the "Files" command:

![image](https://user-images.githubusercontent.com/78613367/155063569-122c7d92-a977-47b8-b8cf-6bf53e1a981c.png)

**Comment by gmonein** [comment]
I had the same issue, after checking https://github.com/junegunn/fzf.vim/issues/1368

I figured that my issue was there because I had a custom shell:
`$HOME/.config/nvim/init.vim`
```
set shell=mycustonshell
```

`~/.local/bin/mycustomshell`
```
#!/bin/zsh
# ... Some strange hackery code
zsh
```

I fixed my issue by setting shell to zsh
`$HOME/.config/nvim/init.vim`
```
set shell=zsh
```

**Comment by icthus56** [comment]
I wonder if there is an issue with the shell detection and escaping. Unfortunately I cannot set my shell to zsh as I am in Windows. I'm perplexed that it seems like I'm the only one with the issue though....

**Comment by icthus56** [comment]
@junegunn do you have any idea where this escaping issue comes from or what I can modify to get FZF working under Win10? Thanks.

**Comment by jrudel** [comment]
@icthus56 I am on Win10 and the same thing was happening to me. I had set my shell to `powershell` instead of the default of `C:\Windows\system32\cmd.exe`. Once I reverted back to the default shell, I was able to get `:Files` to work. You can see the current value of your shell by typing `:echo &shell` in vim. Hope this helps.

**Comment by icthus56** [comment]
@jrudel Thanks, your comment helped to find my issue. It turned out that shellxescape was set somwhere deep. Thanks for your help.
