### ISSUE TITLE
C-T new tab ergonomics

### ISSUE THREAD

**Issue by ds2606** [junegunn/fzf.vim#1378]
- [ x] I have fzf 0.23.0 or above
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

Is there a way to change the C-T new-tab binding (to say, for example, TAB)? I use it frequently and it feels pretty awkward. I'd like to change it in line with vim's ethos of ergonomic keymaps. I tried editing my local source but couldn't find the binding definition.

**Comment by bruhtus** [comment]
Did you mean open the file in new tab? If that's the case then you can use `g:fzf_action` like this:
```vim
let g:fzf_action = {
  \ 'tab': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```
put that in your vimrc or something similar.

For more example, you can check this: https://github.com/junegunn/fzf/blob/master/README-VIM.md#examples

**Comment by ds2606** [comment]
awesome, thanks!!
