### ISSUE TITLE
Preview doesn't work when running Rg on specific file

### ISSUE THREAD

**Issue by tonebender** [junegunn/fzf.vim#1379]
- [ x ] I have fzf 0.23.0 or above
- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

If I search with **:Rg "my search pattern" /path/file/to/search.txt**, and results are found, the results (lines) will be listed in the left box as usual, but the preview window on the right will only say "File not found 1", where "1" is the line number where the match was found in the file (!).

If I do the same search without specifying an explicit path to Rg, like this: **:Rg "my search pattern"**, it will find the match(es) and the preview will work as usual.

I have this custom Rg setup in my ~/.vimrc:
`command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".<q-args>, 1, fzf#vim#with_preview(), <bang>0)`

Any ideas why the preview doesn't work with Rg calls with path/file specified?

**Comment by junegunn** [comment]
Because when you pass a file name to `rg`, it stops printing the filename. The solution is to add `--with-filename`.

```sh
$ rg --column --line-number --no-heading --color=always --smart-case foo | grep man1
man/man1/fzf.1:966:21:     INITIAL_QUERY="foobar"
$ rg --column --line-number --no-heading --color=always --smart-case foo man/man1/fzf.1
966:21:     INITIAL_QUERY="foobar"
$ rg --column --line-number --no-heading --color=always --smart-case --with-filename foo man/man1/fzf.1
man/man1/fzf.1:966:21:     INITIAL_QUERY="foobar"
```

**Comment by tonebender** [comment]
Great, that certainly makes sense! Thanks so much for the quick response!
