### ISSUE TITLE
The right half of the floating window does not show the ruled line

### ISSUE THREAD

**Issue by shiomiyan** [junegunn/fzf.vim#1382]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

environment

- Windows 10 19041.1566
- Neovim v0.6.1
- fzf version 0.29.0

In Neovim on Windows 10, when I use `:FZF` to display a floating window, the right-hand border does not appear.

I have done post-install on Windows sandbox and the same problem is happening.

Unfortunately, we have not been able to determine the cause.

![image](https://user-images.githubusercontent.com/35842766/161368157-a5a85634-dd51-475a-b5e5-3cee1d4a9a44.png)

My simple init.vim here.

```
call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()
```

**Comment by ajin153** [comment]
+1，I have the same problem in neovim 0.7.0 on windows  10 21H2. But if I use neovim 0.7.0 on windows 10 1809，everything seems be OK.
