### ISSUE TITLE
Question: is it possible to change the default <Tab>/<S-Tab> mappings for multi-select mode?

### ISSUE THREAD

**Issue by Integralist** [junegunn/fzf.vim#1386]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I have another plugin https://github.com/gelguy/wilder.nvim for which I'm unable to use <Tab> and <S-Tab> as I believe they're being overridden by FZF.

I'm interested to know if I could change FZF's default mapping to some other special key(s) but I couldn't find anything in any of the reference material to suggest this is possible.

**Comment by junegunn** [comment]
fzf is a standalone terminal program you can run outside of Vim and it does not set up any Vim mappings, so it shouldn't conflict with any other Vim plugins.

To answer the questions, see `KEY/EVENT BINDINGS` section of the man page.
