### ISSUE TITLE
Cannot open temporary file / folder when opening fzf on new MacBook after sleep

### ISSUE THREAD

**Issue by ayroblu** [junegunn/fzf.vim#1392]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

On my new MacBook, after sleeping, and waking, then trying to open fzf, I get this kind of error 

NeoVim:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/4915682/166570781-703d45ab-ef9b-4bbd-baed-86af510e066a.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/4915682/166570894-61206017-752e-4172-b5b7-aa5ebdc5e893.png">

Vim:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/4915682/166571134-967989b8-bc48-4d0e-9e4b-e085c01323fa.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/4915682/166571070-587cbf64-7dbf-4430-9f43-b1f0f872ea04.png">

I know it's a new MacBook or related issue / feature because I also use https://github.com/xolox/vim-session and that throws an error when trying to save a session after sleeping too, and that worked fine for ages, and hasn't been updated in 7 years.

Anyways, seems like the tmp folder goes missing after sleeping, so would be great to make a new one or something?

**Comment by ayroblu** [comment]
I did some investigation on this, and it's kind of a vim thing with tempname()?

Some resources and temporary workaround:
```vim
" Recreate tmpdir if deleted while sleeping
" https://github.com/neovim/neovim/pull/11284
" https://groups.google.com/g/vim_use/c/qgRob9SWDv8/m/FAOFVVcDTv0J
command! Mktmpdir call mkdir(fnamemodify(tempname(),":p:h"),"",0700)
nnoremap <leader>mk :Mktmpdir<cr>
```

**Comment by junegunn** [comment]
Thanks for the report and the investigation. This is clearly an issue of Vim itself, so it's not clear fzf should try to work around the problem because when it happens, many other plugins will also not work (any plugin that runs an external command using `system()` will fail).
