### ISSUE TITLE
:Files showing not an editor command

### ISSUE THREAD

**Issue by Dev-Lohit** [junegunn/fzf.vim#1396]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I have recently installed fzf on my system and vim but while running :Files to use the functionality of the same i caught an error saying not an editor command.
Please help me with the issue.
The following image contains info about my .vimrc file too.

![Screenshot_20220523_123852](https://user-images.githubusercontent.com/77717835/169763186-313d247f-480f-4630-ab08-dd2eacfe6d0d.png)

**Comment by junegunn** [comment]
I'm seeing two `junegunn/fzf`s instead of `junegunn/fzf` **and** `junegunn/fzf.vim`.

**Comment by Dev-Lohit** [comment]
Thanks @junegunn this solves my issue .
