### ISSUE TITLE
Problem with :Files

### ISSUE THREAD

**Issue by marcaddeo** [junegunn/fzf.vim#14]
I'm having an issue with the `:Files` command. I'm not 100% how to replicate it, but sometimes when I hit `,f` (which is mapped to `:Files`) and hit enter on a file to open it... it doesn't open. This happens fairly frequently, but usually after I've used `:Files` to open 1-2 files.

It says at the bottom the file name, as if it opened it but the buffer doesn't seem to appear. Then, once I hit another key the buffer appears to flash and disappear.

Now, I am using neovim so that could be the issue but would love some input on how to resolve the issue as I'm really liking fzf so far!

**Comment by junegunn** [comment]
The terminal emulator of neovim had issues for the past months:

https://github.com/junegunn/fzf/issues?q=label%3Aneovim+is%3Aclosed

But most issues are resolved recently. So try rebuilding neovim from the latest source and see if it helps.

**Comment by marcaddeo** [comment]
Thanks for the quick response! I'm surprised, but reinstalling seems to help! I'm surprised because I only started using neovim last week!

But seems to be all good now.

**Comment by junegunn** [comment]
Yeah, they were finally resolved just a few days ago.
