### ISSUE TITLE
[feature request]  display the full path first in preview window, then display the content

### ISSUE THREAD

**Issue by zhuzhzh** [junegunn/fzf.vim#1403]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I always open the makefiles from the different directory. These directory paths are always long and similar. It's hard for me to use Files/History command in fzf.vim.

but I found vim-clap displays the complate full path in the preview windows first. This is one good idea.
Could fzf.vim provide the same feature to resolve the long-path issue?

Thanks!

**Comment by junegunn** [comment]
Preview script uses [bat](https://github.com/sharkdp/bat), if you have it installed, you can configure the output style via `BAT_STYLE` environment variable.

For example, put this in your shell configuration file

```sh
export BAT_STYLE=full
```

Or you can put it in your .vimrc like so

```sh
let $BAT_STYLE = 'full'
```

**Comment by zhuzhzh** [comment]
Thanks a lot! It works as wanted.
