### ISSUE TITLE
Open file in wrong buffer when used with MiniBufExpl

### ISSUE THREAD

**Issue by cenk** [junegunn/fzf.vim#141]
Steps to reproduce:
* Install https://github.com/weynhamz/vim-plugin-minibufexpl
* Make sure MiniBufExpl is visible with ```:MBEToggle```
* Open a file with ```:Files```

The file is opened in wrong buffer.

**Comment by junegunn** [comment]
Tried it but I can't reproduce the problem. It's probably caused by some autocmd in your configuration.
