### ISSUE TITLE
Wrong path scheme on windows

### ISSUE THREAD

**Issue by grappas** [junegunn/fzf.vim#1411]
- [ x ] I have fzf 0.30.0 or above
- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

I have recently got back on Windows, fired PlugInstall and all of the sudden I cannot run fzf anymore. Seems like plugin uses slashes in path instead of backslashes.
Running neovim 0.7.2 on Windows 11.
![obraz](https://user-images.githubusercontent.com/1036957/181834511-fb5b8ccd-818f-46dd-870d-091055f2b400.png)

**Comment by junegunn** [comment]
Are you running the latest version of the main repo?

Is this patch included in your copy?
https://github.com/junegunn/fzf/commit/d083f01d2225b68d62ca7b2057fb7f0fe2708cb7

**Comment by grappas** [comment]
> Are you running the latest version of the main repo?
Installed with vim-plug, so yes I think so.
![obraz](https://user-images.githubusercontent.com/1036957/181885767-0275256a-323a-4b48-89fd-0de2bbcc0d0e.png)

> Is this patch included in your copy?
It's not seems to be there

![obraz](https://user-images.githubusercontent.com/1036957/181890361-c0b86c16-2c59-4b56-ad73-918e02ee8b61.png)

**Comment by junegunn** [comment]
> It not seems to be there

Strange. Why `git pull` is not fetching the latest commits? What does `git show-ref HEAD` show in `plugged/fzf` directory?

**Comment by grappas** [comment]
> What does git show-ref HEAD show in plugged/fzf directory?

![obraz](https://user-images.githubusercontent.com/1036957/181902722-723902f7-f187-4739-b0c8-4cb472d3938e.png)

**Comment by junegunn** [comment]
Then you have the latest version. A few questions:

* Inside Vim, what is your 
* `:echo &shell`?
* `:echo fzf#exec()`
* `:echo system(fzf#exec() . ' --version')`
* `:echo system(shellescape(fzf#exec()) . ' --version')`
* `:echo system('&' . shellescape(fzf#exec()) . ' --version')`

**Comment by grappas** [comment]
> :echo &shell?
 
![obraz](https://user-images.githubusercontent.com/1036957/181903820-b7b5acba-0095-4f94-9d17-7123eebd7148.png)

> :echo fzf#exec()

![obraz](https://user-images.githubusercontent.com/1036957/181903836-7b4635b5-e79c-4be6-9cd5-60be82debf56.png)

> :echo system(fzf#exec() . ' --version')

![obraz](https://user-images.githubusercontent.com/1036957/181903845-0ca935e3-09e9-4dca-baba-6d9d7f01258a.png)

> :echo system(shellescape(fzf#exec()) . ' --version')

![obraz](https://user-images.githubusercontent.com/1036957/181903864-5ba4e7d8-7749-45f0-bc25-e96633df6942.png)

> :echo system('&' . shellescape(fzf#exec()) . ' --version')

![obraz](https://user-images.githubusercontent.com/1036957/181903880-1bcf65bf-3590-4586-947d-20279b3be235.png)

**Comment by grappas** [comment]
`if has('win64')
    set shell=powershell.exe
    set shellxquote=
    let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command '
    let &shellquote   = ''
    let &shellpipe    = '| Out-File -Encoding UTF8 %s'
    let &shellredir   = '| Out-File -Encoding UTF8 %s'
endif`

in init.vim

**Comment by junegunn** [comment]
Can you try applying this patch to the main fzf repo and see if it helps?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 6fada6c..4dd7ece 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -164,7 +164,7 @@ function s:get_version(bin)
   if has_key(s:versions, a:bin)
     return s:versions[a:bin]
   end
-  let command = (&shell == 'powershell' ? '&' : '') . shellescape(a:bin) . ' --version --no-height'
+  let command = (&shell =~ 'powershell' ? '&' : '') . shellescape(a:bin) . ' --version --no-height'
   let output = systemlist(command)
   if v:shell_error || empty(output)
     return ''
```

**Comment by grappas** [comment]
Yep - it done the trick.

Have a 🍺 :)

**Comment by junegunn** [comment]
Thanks for the confirmation, I've pushed to fix to master.
