### ISSUE TITLE
I want to split the window vertically instead of horizontally after doing ctrl-d .

### ISSUE THREAD

**Issue by whxcode** [junegunn/fzf.vim#1416]
After executing: BCommits, I want to change the behavior of ctrl-D from the default horizontal split window to a vertical split window when comparing file differences. This makes it easier for me to compare the differences between the files.
I define the code in my .vimrc file, but it doesn't seem to work.
     let g:fzf_action = {
       \ 'ctrl-t': 'tab split',
       \ 'ctrl-x': 'split',
       \ 'ctrl-v': 'vsplit',
       \ 'ctrl-d': 'vsplit',
}
What should I do?

![image](https://user-images.githubusercontent.com/44012914/183817682-d55098d7-e7a7-4112-a629-5a7cfbdc3ad4.png)

**Comment by junegunn** [comment]
It uses `:Gdiffsplit` command of vim-fugitive, which splits the window according to your `diffopt`. Add `vertical` to it, for example,

```vim
set diffopt=internal,filler,closeoff,vertical
```

**Comment by whxcode** [comment]
> It uses `:Gdiffsplit` command of vim-fugitive, which splits the window according to your `diffopt`. Add `vertical` to it, for example,
> 
> ```viml
> set diffopt=internal,filler,closeoff,vertical
> ```
thanks your help.
