### ISSUE TITLE
Is it able to include filename when select item on Rg command candidate results?

### ISSUE THREAD

**Issue by lilx2018** [junegunn/fzf.vim#1419]
- [X] I have fzf 0.30.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I use Rg command to search word in files, after search done, then I will continue hit some keys to narrow down candidates from too many files. I hope it can filter by specifying the filename, but Rg command  seem only support to filter by text line, not  support to filter by filename.

**Comment by lilx2018** [comment]
I find Rg support to filter by filename but often priority is too low which not on show.

**Comment by junegunn** [comment]
Yeah, a trick would be to append `:` to your search query. e.g. `pathfragment:`, `pathfragment:contentfragment`.
