### ISSUE TITLE
layout question

### ISSUE THREAD

**Issue by jabbalaci** [junegunn/fzf.vim#142]
When I open a file in split mode, the newly opened file is positioned up (with split) and left (with vsplit). I would prefer the opposite: with split, put the new file down, and with vsplit put the new file to the right. How to achieve it? Thanks.

**Comment by junegunn** [comment]
`set splitbelow splitright` will do. Or you can set up `g:fzf_layout` with `rightbelow split` and `rightbelow vsplit`.

**Comment by jabbalaci** [comment]
Thanks a lot, works well.
