### ISSUE TITLE
set the file name as the sticky header at the top of preview

### ISSUE THREAD

**Issue by ccshao** [junegunn/fzf.vim#1433]
- [X] I have fzf 0.30.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I use the following snippets to search a particular folder.
```
  command! -bang -nargs=* ORg
    \ call fzf#vim#grep(
    \   'rg --column --line-number --with-filename --no-heading --color=always --smart-case '
    \   .shellescape(<q-args>), 1, fzf#vim#with_preview({'dir': 'vaults',
    \                                                   'options': ['--preview-window', '+{2}-5']},
    \                                                   'right:50%', 'ctrl-/'), <bang>0)

```

It works quite nicely, however, when there are lots of match and file paths are long, I get lost on which files the match is found.
How to set a sticky header at the top of preview window? Many thanks!

**Comment by junegunn** [comment]
Given that you installed `bat`, you can set `$BAT_STYLE` to display the name of the file and add something like `~3` to `--preview-window` option like so.

```sh
let $BAT_STYLE = 'header-filename,numbers,grid'

command! -bang -nargs=* ORg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --with-filename --no-heading --color=always --smart-case '
  \   .shellescape(<q-args>), 1, fzf#vim#with_preview({'options': ['--preview-window', '+{2}-5,~3']},
  \                                                   'right:50%', 'ctrl-/'), <bang>0)
```

<img width="1617" alt="image" src="https://user-images.githubusercontent.com/700826/195225956-6ac517ce-62bd-49c7-bb11-319b5f479bbd.png">

**Comment by ccshao** [comment]
Thanks very much for the quick solution!
