### ISSUE TITLE
Error detected while processing function fzf#vim#files[15]..<SNR>92_fzf[1]..<SNR >92_check_requirements[11]..fzf#exec[31]..function fzf#vim#files[15]..<SNR>92_fz f[1]..<SNR>92_check_requirements[11]..fzf#exec:

### ISSUE THREAD

**Issue by theanh031** [junegunn/fzf.vim#1438]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I install this plugin after that I see this error: 
Error detected while processing function fzf#vim#files[15]..<SNR>92_fzf[1]..<SNR
>92_check_requirements[11]..fzf#exec[31]..function fzf#vim#files[15]..<SNR>92_fz
f[1]..<SNR>92_check_requirements[11]..fzf#exec:
line   31:
E605: Exception not caught: Failed to run "/home/theanh/.fzf/bin/fzf --version"
Press ENTER or type command to continue

I want to receive your response soon. Thank you !

**Comment by jsvisa** [comment]
Meet the similar issue when I update `bash` in mac, restart iTerm can fix this issue.

**Comment by klesh** [comment]
Running into the same issue, upgraded bash and restarting iTerm didn't help.
@theanh031 Did you solve the problem?
