### ISSUE TITLE
Fzf.vim wants to use WSL even if bat.exe is available.

### ISSUE THREAD

**Issue by avysk** [junegunn/fzf.vim#1457]
Hello, thanks for the great plugin! I miss something and would appreciate any pointers.

- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I run Windows 11, and I have native (Windows exe) `fzf`, `bat`, `ag`, `rg`. However, whenever fzf.vim wants to show a preview, it executes `batcat` in WSL. I was not able to inform fzf.vim that I have `bat.exe` without overriding fzf.vim's commands. Do I miss something?

**Comment by junegunn** [comment]
That's probably because of this code:

https://github.com/junegunn/fzf.vim/blob/a50c2640b9de23b10b3927873b519930cb8a7984/bin/preview.sh#L58-L63

So you have batcat, but prefer to use bat? Then I can change the code to use `$BATNAME` if it's defined.

```diff
diff --git a/bin/preview.sh b/bin/preview.sh
index 3c11dec..3c12dbd 100755
--- a/bin/preview.sh
+++ b/bin/preview.sh
@@ -56,10 +56,12 @@ if [ -z "$CENTER" ]; then
 fi
 
 # Sometimes bat is installed as batcat.
-if command -v batcat > /dev/null; then
-  BATNAME="batcat"
-elif command -v bat > /dev/null; then
-  BATNAME="bat"
+if [[ -z "$BATNAME" ]]; then
+  if command -v batcat > /dev/null; then
+    BATNAME="batcat"
+  elif command -v bat > /dev/null; then
+    BATNAME="bat"
+  fi
 fi
 
 if [ -z "$FZF_PREVIEW_COMMAND" ] && [ "${BATNAME:+x}" ]; then
```

And you set `let $BATNAME = 'bat'` in your configuration file.

**Comment by junegunn** [comment]
Let's name it `$BATCAT` to be more clear. i.e. `let $BATCAT = 'bat'`
