### ISSUE TITLE
how select a buffer in Buffers

### ISSUE THREAD

**Issue by zeminzhou** [junegunn/fzf.vim#1463]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I want to use ctrl-j/ctrl-k to select buffer in Buffers, but failed. Does fzf.vim not support？
![image](https://user-images.githubusercontent.com/50103576/227729646-33c2d986-0d08-403a-9ea8-189335cfdaf9.png)

**Comment by junegunn** [comment]
Open more than 2 buffers then you can move your cursor between the items except the first one, which is the current buffer.

More explanation: https://github.com/junegunn/fzf.vim/issues/1211#issuecomment-752645124

**Comment by zeminzhou** [comment]
thanks！
