### ISSUE TITLE
Port bin/preview.sh to sh

### ISSUE THREAD

**Issue by jvoisin** [junegunn/fzf.vim#1464]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Since not every platform (Like [Alpine]( https://gitlab.alpinelinux.org/alpine/aports/-/issues/14746 ) and a couple of BSD) is using bash as its shell, it would be nice to port [bin/preview.sh]( https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh ) to `sh`.

**Comment by junegunn** [comment]
Are you interested in contributing?

**Comment by jvoisin** [comment]
I can give it a try, sure.
