### ISSUE TITLE
Replace command called by `:files`

### ISSUE THREAD

**Issue by miguel9554** [junegunn/fzf.vim#1468]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Is there a way to replace the comand used by `:Files`?

What I mean, instead of using fzf, using another fuzzy filter, like https://github.com/natecraddock/zf

**Comment by junegunn** [comment]
Changing the source command: `$FZF_DEFAULT_COMMAND`, using a different filter program: no.

**Comment by skrattaren** [comment]
Is it possible to configure `$FZF_DEFAULT_COMMAND` within (neo)vim config?  I'd like to keep the behaviour consistent, and with Wayland/X11/multiple GUI sessions/terminal vim it's a bit of a pain these days.
