### ISSUE TITLE
Command Tags changes working directory in all tabs

### ISSUE THREAD

**Issue by Perlence** [junegunn/fzf.vim#147]
I'm using minimal neovim configuration. Steps to reproduce the problem:

- Start neovim

- Check working directory
  ```
  :pwd
  /home/sviatoslav/bug
  ```

- Create new tab:
  ```
  :tabnew
  ```

- Change local working directory:
  ```
  :lcd some/path
  ```

- Show tags:
  ```
  :Tags
  ```

- Switch to previous tab:
  ```
  gT
  ```

- Check working directory again:
  ```
  :pwd
  /home/sviatoslav/bug/some/path
  ```

This happens both if there is tags file in some/path directory, and if it is generated by fzf.vim. Also it happens whether you use `:lcd` or `:tcd`.

<hr>

- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

**Comment by junegunn** [comment]
Fixed in https://github.com/junegunn/fzf/commit/412c2116556204d64d1f40afeb995cae1c5bfdcb.
Thanks for the report.

**Comment by Perlence** [comment]
Thank you once again!
