### ISSUE TITLE
Lua equivalent of the FZF git grep example.

### ISSUE THREAD

**Issue by farazshaikh** [junegunn/fzf.vim#1472]
```
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number -- '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)
```

 @junegunn in your README you have the above git grep example.  I recently migrated vim scripts to LUA and was not able to find or conver the above snippet to LUA.  Think you can help here ?

Thanks
Faraz

**Comment by junegunn** [comment]
I don't use Neovim so I can't help you with it.
