### ISSUE TITLE
[Question] How to configure live grep with `--glob` support?

### ISSUE THREAD

**Issue by linrongbin16** [junegunn/fzf.vim#1473]
Hi,

I want to configure live grep (just like fzf-lua and telescope.nvim) with `--glob` support.
Because search text with filetype filter is a big needs to me, how could I do that?

There're two relate plugins support this mode:
1. [fzf-lua - live_grep_glob](https://github.com/ibhagwan/fzf-lua#search)
2. [telescope-live-grep-args.nvim](https://github.com/nvim-telescope/telescope-live-grep-args.nvim)

**Comment by crvdgc** [comment]
You can define a new function similar to the built-in `:Rg` and pass the glob pattern to the `rg` command.

Concretely, notice the `:Rg` [definition](https://github.com/junegunn/fzf.vim/blob/1dcdb21db618055134cd611f4f5918f6d00a5df0/plugin/fzf.vim#L57): `fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), fzf#vim#with_preview(), <bang>0)`. You can break up the `<q-args>` to use the first as the glob pattern and the rest to `fzf#vim#grep`. See `:help <q-args>`.

Alternatively, from Lua, you can abstract the glob as a function argument and call `fzf#vim#grep` with `vim.fn` like [this](https://github.com/crvdgc/nix-darwin-config/blob/ea627383caaa14315e0f5191ed486d0e80b785c3/neovim/lean.lua#L44-L48). (Note the glob pattern is not abstracted in the example and the second argument `has_column` [is deprecate](https://github.com/junegunn/fzf.vim/commit/fd812b5710482df6c22858e673d6d3d674f54adf). You might need to change it according to your version of `fzf.vim`.)

**Comment by linrongbin16** [comment]
https://github.com/linrongbin16/fzfx.vim

finally support in this plugin

**Comment by junegunn** [comment]
Also notice that we now have `grep2`.

https://github.com/junegunn/fzf.vim/commit/87b60bb133032056fda105e0ce6f5d64436926dd
