### ISSUE TITLE
Feature request: please add the ability to search for the word under the cursor

### ISSUE THREAD

**Issue by vitaly-zdanevich** [junegunn/fzf.vim#1474]

**Comment by junegunn** [comment]
```vim
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
xnoremap <silent> <Leader>ag y:Ag <C-R>"<CR>
```

**Comment by vitaly-zdanevich** [comment]
Thanks, it works for Neovim, but not for Vim :(

**Comment by junegunn** [comment]
I'm a Vim user.

**Comment by vitaly-zdanevich** [comment]
Oops, that was some interference with some another plugin - because nothing for Go, but works for `.vim` file, thanks.

**Comment by vitaly-zdanevich** [comment]
Hm, in Vim 9 I got error:

> Command failed: ag --nogroup --column --color  -- 'my_word_under_cursor'
