### ISSUE TITLE
Have <C-n> and <C-p> cycle through the top and bottom

### ISSUE THREAD

**Issue by psygo** [junegunn/fzf.vim#1475]
- [X] I have fzf 0.30.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Is there a way of having <kbd>C-n</kbd> or <kbd>C-p</kbd> not stop at the bottom or top and cycle through the list of results? I also feel like this is a more natural default.

**Comment by junegunn** [comment]
Add `--cycle` to your `$FZF_DEFAULT_OPTS`.

**Comment by psygo** [comment]
Thank you!
