### ISSUE TITLE
Feature Request: let preview command highlight line

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf.vim#1489]
- [ X] I have fzf 0.30.0 or above
- [ X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ X] I have read through the manual page of fzf (`man fzf`)
- [X ] I have searched through the existing issues

I've set FZF_PREVIEW_COMMAND, which is used in fzf.vim/bin/tagpreview.sh.

tagpreview.sh highlights a line by reversing it which has the unfortunate effect of making it look like kitchy Christmas tree.

![screenshot_2023-07-17_01-10-08](https://github.com/junegunn/fzf.vim/assets/45409/6cb1d989-bdac-4fab-829c-f1dbd6b62440)

Fzf --preview gets more information, the line, the size of the window, ... Those could be used in the external viewer highlight  the line and the match. In my case it would also allow the preview command to render just the part needed in the preview (since there's no possibility to scroll in the preview window, right?)

**Comment by junegunn** [comment]
Why don't you unset `FZF_PREVIEW_COMMAND`, install bat, and let the script uses it? I'll look better because it uses `--highlight-line` option of bat instead of reversing the colors of the line.

> since there's no possibility to scroll in the preview window, right?

FYI, unlike tagpreview.sh, preview.sh feeds the entire file to fzf, properly setting the scroll offset using `+N` expression, so you can scroll upwards and downwards.

https://github.com/junegunn/fzf.vim/blob/1dcdb21db618055134cd611f4f5918f6d00a5df0/autoload/fzf/vim.vim#L866

(Used in `:Rg`, and the likes)

**Comment by nkh** [comment]
I have bat installed, and that's a good default, but I prefer to use my own which uses vim so I get a consistent preview.

I will use $CENTER to highlight the line, but the the AWK code would still reverse it. 

So far I've modified preview.sh, to replace $REVERSE with a simple ">>" tag, but I'd prefer not to modify it.

Is the pane size set somewhere? If the line to be shown is at the top of the file, not rendering 2000 lines but just the necessary lines is faster. I'm considering adding a cache the preview are not re-rendered at all.

I don't see any bindings to scroll the preview window in the documentation, did I miss it?

**Comment by junegunn** [comment]
> Is the pane size set somewhere?

`$FZF_PREVIEW_LINES`. Please refer to tha man page for more info.





> I don't see any bindings to scroll the preview window in the documentation, did I miss it?

Using your mouse. By scrolling over the area or dragging the area.
