### ISSUE TITLE
How to pass word being completed to fzf completer?

### ISSUE THREAD

**Issue by rgrinberg** [junegunn/fzf.vim#149]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I see that you can define a completion source from the result a shell command like this:

```
inoremap <expr> <c-x><c-k> fzf#complete('cat /usr/share/dict/words')
```

Is it possible to pass the completion prefix somehow into this command?

**Comment by junegunn** [comment]
With some black magic.

```vim
function! CompletionSource(prefix)
  return 'echo '.a:prefix
endfunction
inoremap <expr> <c-x><c-k> fzf#complete({'source': function('CompletionSource')})
```

**Comment by rgrinberg** [comment]
Hmm this isn't quite what I'm looking for. I have a shell script that I'd like to call `run.sh <completion prefix>` and use the stdout of executing this shell script as the completion candidates.

**Comment by junegunn** [comment]
Replace `echo` to your script.

**Comment by rgrinberg** [comment]
@junegunn Thanks. I'm slow today -_-
