### ISSUE TITLE
Customizing colors?

### ISSUE THREAD

**Issue by fortes** [junegunn/fzf.vim#15]
The colors for commands like `:Ag` end up unreadable on my dark terminal. Is there a way to customize these?

**Comment by junegunn** [comment]
There is no elegant/simple way at the moment. There are many commands in this plugin, and I do not want to introduce a whole bunch of configuration parameters that most users will ignore, so yeah.

Anyway, with the above commit, you can now try something like this.

```vim
autocmd VimEnter * command! -bang -nargs=* Ag
    \ call fzf#vim#ag(<q-args>, {'down': '40%', 'options': '--color hl:220,hl+:196'})
```

The `options` you provide will be appended to the default options set by the function.

**Comment by fortes** [comment]
Hm, I'm not having any luck with this:

```
command! -bang -nargs=* Ack call fzf#vim#ag(<q-args>, {'down': '40%', 'options': '--nocolor'})
```

The screen flashes briefly, but I see no search UI. However, this works (as does your example above):

```
command! -bang -nargs=* Ack call fzf#vim#ag(<q-args>, {'down': '40%', 'options': ''})
```

Am I doing something wrong? I don't really need to control exact colors, I just don't want dark text on a dark background.

**Comment by junegunn** [comment]
`--no-color`

**Comment by fortes** [comment]
D'oh, thanks :)

**Comment by fortes** [comment]
Out of curiosity, why is it `--no-color`? For plain `ag` it is `--nocolor`.

**Comment by junegunn** [comment]
In fzf every option has its `--no-` counterpart. There's no hard rule about the naming and it's a matter of preference but I'm more familiar with `--no-` convention. e.g. curl, grep, git, configure scripts.
