### ISSUE TITLE
custom fzf_action behaviour have been broken by recent commit

### ISSUE THREAD

**Issue by SolaWing** [junegunn/fzf.vim#1505]
- [ ] I have fzf 0.30.0 or above
- [ ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [ ] I have searched through the existing issues

 
same as title, [commit](https://github.com/junegunn/fzf.vim/commit/832a090870a79d8be87d8856c821806512a45b23) introduce a change as following

<img width="685" alt="图片" src="https://github.com/junegunn/fzf.vim/assets/3897953/31a0616e-ffa2-4488-88ec-13028e456c54">

so now action will execute directly, without concat file after it. this will break custom function like tab drop, function(arg), etc.

**Comment by junegunn** [comment]
Thanks for the report. This was my oversight, unfortunately, it's unclear how to reconcile the old behavior and the new behavior introduced by the commit. I'll look into it.

**Comment by junegunn** [comment]
I tried my best to address the issue while not breaking the new behavior regarding the quickfix list. Please let me know if you still see unexpected behaviors.
