### ISSUE TITLE
"Tab drop" no longer works as fzf action for jumping to existing tab

### ISSUE THREAD

**Issue by lukelbd** [junegunn/fzf.vim#1508]
Check all that apply [x]:

- [x ] I have fzf 0.30.0 or above
- [x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x ] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

Before submitting
=================

- Make sure that you have the latest version of fzf and fzf.vim (yes)
- Check if your problem is reproducible with a minimal configuration (yes)

Issue description
======================================

Thanks for maintaining this awesome plugin.

Previously I used the following configuration to have `:Tags`, `:Ag`, and `:Rg` switch to existing tabs:

```
let g:fzf_action = {
  \ 'ctrl-m': 'tab drop', 'ctrl-t': 'tab drop',
  \ 'ctrl-i': 'silent!', 'ctrl-x': 'split', 'ctrl-v': 'vsplit'
  \ }  " have file search, grep open to existing window if possible
```

  However your commit that added support for multiple selection also meant that this no longer works (832a090). The new `s:open()` effectively triggers an empty `:tab drop` command which always opens a new tab. Is there any way you could add back support for `:tab drop` without dropping support for multiple selections?

**Comment by junegunn** [comment]
Have you tested the latest revision which contains https://github.com/junegunn/fzf.vim/commit/fe362d413a0286b1474c1d235c6eb1d0cd6ae8a4?

**Comment by lukelbd** [comment]
Sorry my mistake -- that fixes it! Thanks for the quick response
