### ISSUE TITLE
FZF Preview and Light themes colors not looking ok

### ISSUE THREAD

**Issue by lucasgrvarela** [junegunn/fzf.vim#1509]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

![image](https://github.com/junegunn/fzf.vim/assets/37870368/91d0df68-b7f2-4bbd-b8f7-5f775eb5f94e)

I tried to define g:fzf_colors and FZF_DEFAULT_OPTS --color options, none of them worked. Looks like all the Light themes are broken with the Preview text always in White color no matter what I define. My end goal is to get Gruvbox Light Medium working but I tried all the defaults vim color schemes and the polar.vim, in all the cases the Light versions are broken while the Dark versions are Ok.

I could do a workaround defining the preview-bg to something like a dark color like #282828 so dark bg on white text works but then I have a very bad and ugly preview that doesn't match at all my theme. The desired behaviour is to have the original bg color #fbf1c7 from gruvbox light theme being used in the preview-bg and be able to read the text/code.

![image](https://github.com/junegunn/fzf.vim/assets/37870368/c6e5592f-2faa-490a-9a85-0089d2995e5d)

Not sure if one default color is being defined wrong in the code or anything like that. I disabled all my plugins and the behavior was the same.

```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 25 2023 21:38:53)
Included patches: 1-1943
```

**Comment by junegunn** [comment]
Do you have bat installed on your system? Because the previewer will use it if it's available and you can customize the colors of it by setting `BAT_THEME`.

An example config:

```vim
colo gruvbox
set background=light
let $BAT_THEME = 'gruvbox-light'
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

And this is what it looks like:

<img width="1728" alt="image" src="https://github.com/junegunn/fzf.vim/assets/700826/4b706319-ae93-4096-abcb-606d87c7fc75">

**Comment by lucasgrvarela** [comment]
@junegunn I don't have. 

```
$ bat
bash: bat: command not found
```

minimal vimrc with only fzf and gruvbox and the same configurations as you:
```
let mapleader = " "
nnoremap <leader>e :E<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :RG<CR>
nnoremap <leader>s :G<CR>
nnoremap <leader><space> :Buffers<CR> 

set clipboard=unnamedplus

call plug#begin('~/.vim.plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'morhetz/gruvbox'
call plug#end()

colo gruvbox
set background=light
let $BAT_THEME = 'gruvbox-light'
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

Result:

![image](https://github.com/junegunn/fzf.vim/assets/37870368/da01f21e-f3ce-4ce4-9841-73ee4ff4a85d)

In this case do you believe there is something wrong in my side/my terminal anything like that?

**Comment by lucasgrvarela** [comment]
I installed BAT to test the configs, this is the result:

![image](https://github.com/junegunn/fzf.vim/assets/37870368/e348056a-1442-49ac-8238-3c0eaec32a4c)

**Comment by lucasgrvarela** [comment]
Tried to use different terminals, like alacritty and kitty same result.. I saw this https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim and gave it a try, then the colors changed a bit they are more readable but still not ok.

![image](https://github.com/junegunn/fzf.vim/assets/37870368/9515483f-d706-4663-8f0e-0351c29cce2a)

**Comment by lucasgrvarela** [comment]
Using a different vim version also changed the colors..
```
$ /usr/bin/vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)
Included patches: 1-1378, 1499
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
```

![image](https://github.com/junegunn/fzf.vim/assets/37870368/ae3d5308-d0e1-4940-8b1b-e229b4386d0d)

**Comment by junegunn** [comment]
The last screenshot clearly shows that the configs are picked up. Can you double-check if they are properly set?

```vim
:echo $BAT_THEME
:echo g:fzf_colors
```

* Also, what is the output of `:echo fzf#wrap()` (you should see some color codes if `g:fzf_colors` is set)
* Is `&termguicolors` set? `:echo &termguicolors`

**Comment by lucasgrvarela** [comment]
![image](https://github.com/junegunn/fzf.vim/assets/37870368/cc456e0c-681e-4357-afdd-fe8681761e80)

```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct  4 2023 09:48:24)
Included patches: 1-1976
```

Thank you for the help in the end updating the vim for the latest version, plus installing bat and setting it to `let $BAT_THEME = 'gruvbox-light'` worked!

Tested with and without g:fzf_colors and in both cases it is working fine now.

**Comment by juanMarinero** [comment]
Topic related.

I could barely read the file-path nor the line produced by `:RG` (left panel). So I edited them directly with `--colors \"path:fg:blue\" --colors \"line:fg:22\"`:

```vimrc
command! -bang -nargs=* RG
            \ call fzf#vim#grep(
            \ "rg --column --line-number --no-heading --color=always --colors \"path:fg:blue\" --colors \"line:fg:22\" --smart-case ".shellescape(<q-args>), 
            \ 1, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}), <bang>0)
```
Note: rest of code explained in [#346](https://github.com/junegunn/fzf.vim/issues/346)

My previous approach is a workaround. I think a more solid way is related to edit [autoload/fzf/vim.vim](https://github.com/junegunn/fzf.vim/blob/1fff637559f29d5edbdb05e03327954a8cd9e406/autoload/fzf/vim.vim#L294), maybe something related to: `let s:ansi = {'black': 30, 'red': 31, 'green': 32, [...] 'cyan': 36}`. But Idk.

Another posible solution is to identify  the group and edit the highlight: `:help highlight`.
