### ISSUE TITLE
Errors when running 'History:' and 'History/' commands

### ISSUE THREAD

**Issue by akdevservices** [junegunn/fzf.vim#1512]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

There are errors when running `History:` and `History/` commands with empty command and search history. The bug cannot be reproduced with a minimal config because commands should be run with hot keys to preserve empty history.
`.vimrc`:
```
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync

let mapleader="\<space>"
nnoremap <leader>f/ :History/<cr>
nnoremap <leader>f: :History:<cr>
```
![20231026_14h30m36s_grim](https://github.com/junegunn/fzf.vim/assets/29972256/a8de8b40-f797-4844-8e9c-506bdf527690)
![20231026_14h30m49s_grim](https://github.com/junegunn/fzf.vim/assets/29972256/9a0d415e-ad31-4980-834d-4e9ec78c2e43)

**Comment by junegunn** [comment]
Thanks, it should be fixed now.
