### ISSUE TITLE
How to get fzf.vim to index files at startup?

### ISSUE THREAD

**Issue by michaelmaitland** [junegunn/fzf.vim#1515]
I do work on a very large mono-repo, so when I do :Files, there is always some indexing that takes place. Sometimes I type in the search string I wan't, but I have to wait for the indexing to find the file I want before results show up. This can take up to a minute sometimes, and it needs to re-index every time I call `:Files`. I would like this indexing to begin when I open vim and do it in the background. Is this possible?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/issues/366 and https://github.com/junegunn/fzf/issues/3500.

In short, you can write your own script or program that implements some caching/indexing mechanism and let `:Files` use it by setting it as `$FZF_DEFAULT_COMMAND`.
