### ISSUE TITLE
override fzf_history_dir option CTRL-P and CTRL-N mappings

### ISSUE THREAD

**Issue by zigius** [junegunn/fzf.vim#1522]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hey, 

I saw in https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration
that you can set `fzf_history_dir` to enable history navigation. 
However, setting the fzf_history_dir global flag overrides the CTRL-P and CTRL-N mappings
to search through the history navigation. Is there a way to change the history mapping keys to something else? 
I would like to have history navigation and also keep the behavior where CTRL-P and CTRL-N navigate the results.

Thanks :)

**Comment by junegunn** [comment]
The remapping can be prevented by explicitly mapping ctrl-n and ctrl-p to `down` and `up` in your `FZF_DEFAULT_OPTS`.

So something like this should work.

```sh
export FZF_DEFAULT_OPTS='--bind ctrl-n:down,ctrl-p:up,alt-n:next-history,alt-p:prev-history'
```

Or if you prefer to put it in your Vim configuration file.

```sh
let $FZF_DEFAULT_OPTS = '--bind ctrl-n:down,ctrl-p:up,alt-n:next-history,alt-p:prev-history'
```
