### ISSUE TITLE
Add the option for Rg command to search the word under the cursor

### ISSUE THREAD

**Issue by PlasmaHH** [junegunn/fzf.vim#1527]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

For a long time now I have been using vim-ripgreps Rg command to search for stuff mostly because it provides one nice feature that is missing from fzf.vim Rg/RG commands: When started without parameters, it will use the word under the cursor.

For that to work probably plugin/fzf.vim command definition of Rg would have to call some special other function instead of shellescape that uses expand("<cword>") when <q-args> is empty. 

Really cool would be if additionally this could detect if a visual selection was being done and use that

(Btw. is there a reason why RG doesn't use shellescape?)

**Comment by asheidan** [comment]
Isn't it possible to do this already by including `<C-r><C-w>` (insert the word under the cursor) in your mapping?

Since I'm not sure how you invoke the command you might have to tweak this a little bit.

**Comment by PlasmaHH** [comment]
I usually dislike re-creating commands from plugins with my own changes as then when it updates in the plugin I will miss those changes usually... also thought that it might be intresting as a feature in general for others...

**Comment by junegunn** [comment]
No, what @asheidan is saying is that you can define your own mappings that do that in your Vim configuration file.


```sh
nnoremap <silent> <Leader>rg       :Rg <C-R><C-W><CR>
nnoremap <silent> <Leader>RG       :Rg <C-R><C-A><CR>
xnoremap <silent> <Leader>rg       y:Rg <C-R>"<CR>
```

You should be able to define similar commands that call `:Rg` in a similar fashion.

**Comment by PlasmaHH** [comment]
> You should be able to define similar commands that call `:Rg` in a similar fashion.
And my point was to add a feature to `:Rg` to use it as `:Rg` the way I have been from another plugin as I thought it would be useful for others too.
