### ISSUE TITLE
Unknown function reltimefloat 

### ISSUE THREAD

**Issue by cdwills** [junegunn/fzf.vim#153]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

After upgrading this morning I cannot do anything without the error:

Error detected while processing BufWinEnter Auto commands for "*":
E117: Unknown function: reltimefloat
E15: Invalid expression: reltimefloat(reltime())

I believe it is related to the most recent commit https://github.com/junegunn/fzf.vim/pull/152

I am on OS X, Neovim  and was able to repro with minimal config

**Comment by rosshadden** [comment]
Happens on Linux, too.

**Comment by junegunn** [comment]
Hmm, I just realized that `reltimefloat` was added to Vim pretty recently. Updated the code to fall back to `localtime`. Thanks for the report.
