### ISSUE TITLE
vim.ui.select wrapper for fzf.vim

### ISSUE THREAD

**Issue by 231tr0n** [junegunn/fzf.vim#1531]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello and thank you for this wonderful plugin. After using this plugin extensively I found out that I had to rely on external plugins to create vim.ui.select wrapper in neovim. So my question is how do i create a vim.ui.select wrapper and make it use fzf instead of relying on plugins like dressing.nvim if possible. Is there any existing functionality to do that.

**Comment by junegunn** [comment]
I'm a regular Vim user so I'm not familiar with the concepts. This is probably not the best place to look for the information. Thanks.

**Comment by GopherJ** [comment]
I also want this~  so that I can use nvim-dap to pick process
