### ISSUE TITLE
fzf Doesn't load all Helptags before showing entries when runnign `nvim +Helptags` from bash 

### ISSUE THREAD

**Issue by MikeLemo1** [junegunn/fzf.vim#1532]
- [x ] I have fzf 0.30.0 or above
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x ] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

Basically the title is self explanatory, when running `nvim +Helptags` in bash nvim open helptags fzf with 14K entries, closing and refreshing it manually gives around 15K.
Any idea how to make fzf wait for all helptags to load before displaying `:Helptags` from bash or reloading it dynamically?

**Comment by junegunn** [comment]
Have you set up "lazy-loading" of your plugins using your plugin manager? That's probably why.

**Comment by MikeLemo1** [comment]
Huh yeah also forgot to mention I use lazy.
Is there a simple straight forward way to load / disable this feature per this command or would I have to make somewhat of a global sacrifice to make this Helptags feature work properly?
All I'm trying to achieve is access to full nvim helptags list with a keyboard shortcut from bash

**Comment by MikeLemo1** [comment]
And loading it with `nvim +Helptags!` also don't work from [this issue](https://github.com/folke/lazy.nvim/issues/135)

**Comment by junegunn** [comment]
I'm not familiar with "lazy" and I'm not even a Neovim user, so I can't be of much help. But if it provides an API to load plugins that are not yet loaded, you can write your own command that

1. loads all plugins
2. then runs `Helptags`
