### ISSUE TITLE
[Rg] Is there a way to open the file and navigate to a line without having paths and line numbers in the output?

### ISSUE THREAD

**Issue by mqrris** [junegunn/fzf.vim#1537]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues
---
![rg](https://github.com/junegunn/fzf.vim/assets/71521628/c4ca92c5-6948-4c7e-b19d-d66ba645faff)

![rg-error](https://github.com/junegunn/fzf.vim/assets/71521628/4673046d-45a5-48aa-a0fd-c72cb6ff341b)

To reproduce screenshots:
```
command! -bang -nargs=* Rg call fzf#vim#grep("rg -I -N --trim --color=always --smart-case ".shellescape(<q-args>), 1, <bang>0)
```

```
let $FZF_DEFAULT_OPTS="--color='gutter:#000000,bg+:#000000,prompt:#000000' --prompt='' --pointer=' ' --no-info --no-scrollbar --no-separator --reverse"
```
---
I'd also liked to know how to remove "Rg>" prompt from `Rg` and  "~/" from `FZF`. 

As well as this padding: 

![fzf-rg-space](https://github.com/junegunn/fzf.vim/assets/71521628/0ec0ea2f-963a-47a1-ba30-45a5dbd43e01)
---
The only reason I'm doing this is to save my screen estate.
I know it's probably unfeasible, but I'm gonna ask anyway.

**Comment by junegunn** [comment]
fzf needs to know the filename and the line number to go to the position, so you can't use a `rg` command that doesn't print them. However, you can hide the parts using `--with-nth` option like so.

```vim
" command (string), [spec (dict)], [fullscreen (bool)]
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".fzf#shellescape(<q-args>), { 'options': '--with-nth 4..' }, <bang>0)
```

You should note that `--with-nth` makes fzf slower.

> As well as this padding:

Nope, not possible. One column is for "pointer" and another is for "marker" (for `--multi` selection).
