### ISSUE TITLE
Ignore currently opened files in buffers when fuzzy finding

### ISSUE THREAD

**Issue by megalithic** [junegunn/fzf.vim#154]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I was wondering if there is a way to ignore files in the list that are presently opened in buffers. Say, i fuzzy find and open a file, 'foo.js';  i'd expect that if i were to fuzzy find 'foo', that i'd not see 'foo.js' in the fuzzy find list.

Let me know if you need more info on this, or if my question isn't making sense. Thanks June, for all your great contributions. :)

**Comment by junegunn** [comment]
I suppose you're talking about `:Files` command. `:Files` command uses `find` command (or `FZF_DEFAULT_COMMAND`) that is external to Vim, which means we should find a way to pass the list of open files (which can be many) to the external command. It is possbile, but it's not going to be a one-liner.

**Comment by megalithic** [comment]
@junegunn 

I apologize for not including snippets of my vimrc..

Here's how I presently have fzf.vim setup:

```vim
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'

let g:fzf_buffers_jump = 1
let g:fzf_filemru_bufwrite = 1
let g:fzf_layout = { 'down': '~30%' }
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'enter': 'vsplit'
  \ }

nnoremap <silent> <leader>m :exe 'Files ' . <SID>fzf_root()<CR>
nnoremap <silent> <leader>a :execute 'Ag ' . input('Ag/')<CR>

" " Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)
imap <expr> <c-x><c-f> fzf#vim#complete#path('git ls-files $(git rev-parse --show-toplevel)')

function! s:fzf_root()
  let path = finddir(".git", expand("%:p:h").";")
  return fnamemodify(substitute(path, ".git", "", ""), ":p:h")
endfunction
```

**Comment by junegunn** [comment]
`set rtp+=~/.fzf` is not necessary, as vim-plug does that for you.

> Is there a "better way" than ...

You mean the `<leader>m` mapping you have? I don't see anything wrong with the approach. `nnoremap <silent> <leader>a :execute 'Ag ' . input('Ag/')<CR>` can be greatly simplified to `nnoremap <leader>a :Ag<space>` though.

Back to your original question: you'll have to write a Vim function that collects the list of open files, and an external command or shell script that reads the list (maybe via a temporary file) and excludes the matches from the result. Like I said, it's possible, but it requires some work.
