### ISSUE TITLE
:Tags<cr>Query behaves differently from :Tags Query<cr>

### ISSUE THREAD

**Issue by JonnyRa** [junegunn/fzf.vim#1540]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi,

The issue I'm having is that `:Tags Blah` doesn't find any content but using `:Tags`, pressing enter and then typing the same query does find content.  
I have a keybinding that does Tags for the current word which isn't currently usable because of this
```
nnoremap <C-_> :execute "Tags ".expand('<cword>')<cr>
```

This did previously work but I'm not exactly sure when it stopped working.
I've confirmed that the issue isn't my binding as I can reproduce when using :Tags command directly.
I also tried in the minimal config and found the same.

Interestingly when doing `:Tags Blah<cr> ` if I then delete the query then no tags are shown at all which is presumably why the query fails - I think something about using the command that way is causing the tags to not be read at all, whereas if I type `:Tags<cr>` then I see lots of tags and typing queries by hand works

I'm on
```
fzf --version
0.50.0 (f97d275)
```

and latest version of fzf-vim

Cheers

Jonny

**Comment by JonnyRa** [comment]
I notice perl is mentioned for Tags.

I'm on
```
perl --version

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
```

**Comment by junegunn** [comment]
A tags file can be enormous so we recently changed `:Tags` command to pre-filter the list using `readtags` if a query string is specified.

* #1524 
* https://github.com/junegunn/fzf.vim/commit/0b3e015ad88a3d9e71b0c85ed2e19d414ad498f4

What do you see when you run `readtags -t tags -e -p Blah` on your shell? No result?

**Comment by JonnyRa** [comment]
Thanks for the quick response.
I don't have readtags installed which explains why it wasn't working! I didn't realise universal-ctags was a dependency - I'm using something called fast-tags to generate mine for haskell

Just double checked and it doesn't mention it in the dependencies bit of the readme

I've installed the package and things are now working :tada: thanks for your help

**Comment by junegunn** [comment]
I see, thanks for the confirmation. I'll consider making the script not use `readtags` if it's not found on the system.

**Comment by JonnyRa** [comment]
Maybe having a message to prompt installation of the package might be good? although I suppose might be annoying if someone couldn't/didn't want to install for some reason.  Perhaps you could flag whether to warn or not?

Fast is good though so I'm glad I ran into this and installed the extra dependency, just silently using the slower option might stop people feeling the benefit of the improved method.

Anyway thanks for your help and thanks for building/maintaining the tool, it definitely smooths off a few rough edges in vim and saves a lot of extra typing :smile:

**Comment by junegunn** [comment]
Thanks, `Tags PREFIX` will now tell the users to install universal ctags.
