### ISSUE TITLE
[bug] :Commands command do not fuzzy find in windows

### ISSUE THREAD

**Issue by DanSM-5** [junegunn/fzf.vim#1542]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I found that the `:Commands` (fzf#vim#commands()) command do not fuzzy find under windows. I made some tests and I found it is related to the `-d` (delimiter flag) that is being added.

I can reproduce the behavior directly in the command line with the the generated command by `fzf#vim#commands`:
```powershell
type C:\Users\daniel\tmp\test-commands.txt | fzf --border  --border "--color=bg+:237,bg:235,spinner:214,hl:214,fg:223,header:241,info:109,pointer:109,marker:208,fg+:223,prompt:246,hl+:214" --ansi --expect ctrl-x --tiebreak=index --header-lines 1 -x --prompt "Commands> " --nth="2,3,2..3" -d  --no-height
```

File source used for test:
[test-commands.txt](https://github.com/junegunn/fzf.vim/files/15241211/test-commands.txt)

In powershell:
https://github.com/junegunn/fzf.vim/assets/49035812/12f28813-8dd6-415e-842c-4dcfc660a63e

In WSL:
https://github.com/junegunn/fzf.vim/assets/49035812/d039dfec-a203-4763-a7bc-0144b303ae12

**NOTE**: I wasn't sure if fill this issue here as a bug in the fzf.vim plugin in case windows should not use that flag or should have a specific value or in [`fzf`](https://github.com/junegunn/fzf/issues) repo as a bug for windows with `-d` flag as I haven't used that option before. I understand is to set a delimiter but none was being used in either windows or linux (wsl). Let me know and I'll move the issue appropriately. 

```bash
fzf --version
0.51.0-devel (c5fb0c4)
```

**Comment by junegunn** [comment]
It should work now.

**Comment by junegunn** [comment]
The problem was the non-breaking space character which we used as a delimiter (`-d NBS`) was not properly passed to the Windows command. I was able to fix it by replacing the use of it with tab and with `--tabstop=1`.
