### ISSUE TITLE
fzf#complete does nothing

### ISSUE THREAD

**Issue by mbudde** [junegunn/fzf.vim#155]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim (7.3.429-2ubuntu2.1)
    - [x] Neovim (0.1.4ubuntu1+git201606051226+2573+20~ubuntu12.04.1)

`:call fzf#complete('ls -1')` seems to do absolutely nothing and gives no errors. From the documentation I would expect it would start fzf with the filenames from the current directory. Reproducible with minimal configuration in both vim and nvim.

**Comment by junegunn** [comment]
It only works in insert mode. Test it with an insert mode map like follows.

```vim
inoremap <expr> <c-x><c-x> fzf#complete('ls -1')
```

**Comment by mbudde** [comment]
Ahh, of course! Thank you :)
