### ISSUE TITLE
rfv works in vim

### ISSUE THREAD

**Issue by zeminzhou** [junegunn/fzf.vim#1551]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

[rfv](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode) is a very useful script, can it works in vim?

**Comment by junegunn** [comment]
That's `:RG` (all caps).
