### ISSUE TITLE
support skim/fzy as fzf is really too slow

### ISSUE THREAD

**Issue by GopherJ** [junegunn/fzf.vim#1554]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by junegunn** [comment]
Nope. https://github.com/lotabout/skim/issues/317

And that was when fzf was much slower than it is now.

**Comment by GopherJ** [comment]
@junegunn do you have a guess on why my fzf starts to be super slow recently? I use the following command and it's super slow in a 50k lines rust repo

**Comment by junegunn** [comment]
Please provide the exact steps to reproduce the problem you're experiencing. What version did you use? What command did you use on what environment? What exactly was slow, loading of the list, or filtering of the list? What query pattern did you use? A screen recording of the situation would be helpful.

The plonky2 repository only has 290 files, and I don't think any of the programs will show any noticeable delay in processing such a tiny list.

**Comment by GopherJ** [comment]
@junegunn the latest version of fzf and loading the list have been slow, all I'm saying is running:

```
fzf
```

directly, it took around 2seconds I'm not sure what happened

**Comment by junegunn** [comment]
How about `find . -type f | fzf`?

**Comment by GopherJ** [comment]
@junegunn hi, I have FZF_DEFAULT_COMMAND 

> @junegunn do you have a guess on why my fzf starts to be super slow recently? I use the following command and it's super slow in a 50k lines rust repo
> 
> ```
> fd --type f --exclude .git --exclude node_modules --exclude .cache --exclude third-party --exclude vendor --exclude target --exclude Cargo.lock --exclude yarn.lock --exclude package-lock.json --exclude .zig-cache --follow --hidden
> ```
> 
> for example you can use https://github.com/0xPolygonZero/plonky2 repo
> 
> in this example, fzf is noticeable twice slow than skim, much slower than fzy. To be more specific, fzf took ~2s, skim took ~1s, fzy is instant

**Comment by GopherJ** [comment]
@junegunn I observed a wierd thing, I reinstalled fzf from apt and it turns out to be much faster than before, not sure what happened on the installation process

a week or so I did an update using vim-plug, then fzf becomes noticeable slow

**Comment by junegunn** [comment]
> How about `find . -type f | fzf`?

**Comment by GopherJ** [comment]
@junegunn

```
find . -type f | fzf
```
do you have a way to benchmark? After reinstalling, sk and fzf perform quite similar in a 60k codebase, but fzf took longer to scan larger dataset (124GB)


My current fzf version is:

```
0.29 (devel)
```

**Comment by GopherJ** [comment]
I tried also telescope + fzf native and they are quite fast but they have bugs.

**Comment by junegunn** [comment]
> fzf => 2s
> sk => 1s
> find . -type f | fzy => instant

I was referring to this. You said fzy is fastest and sk is faster based on this observation. So I asked you how `find . -type f | fzf` works. Is it instant, or is it still 2 seconds? Because you said you have `$FZF_DEFAULT_COMMAND`, if it's instant, 
 it hints that there's something wrong with your shell configuration, and you'll likely experience the same amount of delay when you do `time $SHELL -c "$FZF_DEFAULT_COMMAND" > /dev/null`, and it has nothing to do with fzf's performance.

> 0.29 (devel)

That's extremely outdated. The current version is 0.54.1.

**Comment by junegunn** [comment]
FYI, https://www.reddit.com/r/neovim/s/ZegekRoLvP

**Comment by GopherJ** [comment]
hi @junegunn sorry I was quite busy and didn't get time to reply, I think you can forget this issue for now. after reinstall + switching versions etc. It works quite fast now.

So I think we just keep what it is should be good. Telescope has more bugs than fzf, I love the stability you provide, thanks for you hard work!
