### ISSUE TITLE
tagpreview.sh - preview error with  awk syntax error

### ISSUE THREAD

**Issue by georgexsh** [junegunn/fzf.vim#1555]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.2 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

tag preview stopped working with following error message:

```
 ~/.vim/bundle/fzf.vim/bin/tagpreview.sh: line 38: Fuzzy        bool
 415: syntax error in expression (error token is "bool
 415")
 awk: syntax error at source line 0
  context is
         {     if (NR >= 1 && NR <= 10) {         if (NR ==         Fuzzy        bool >>>
  <<<
 awk: illegal statement at source line 0
 awk: illegal statement at source line 0
         missing ]
```

`awk` is the one shipped with macos:

```
$ which -a awk
/usr/bin/awk

$ /usr/bin/awk --version
awk version 20200816
```

`vim` version is `VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jul 18 2024 18:40:28)`.
`fzf.vim` version is f7c7b44.
`ctags` version is `Universal Ctags 6.1.0, Copyright (C) 2015-2023 Universal Ctags Team`.

----

update: if I remove `--excmd=number` from ctags config, the preview window opens without error but doesn't focus on the correct line.

**Comment by fh2ctm** [comment]
Having the same issue here with `bat`. 
`fzf` version `0.54.2 (brew)`. 
`bat` version `0.24.0`. 

Example error output, when previewing `!` in `change.txt`: 
```
~/.vim/plugged/fzf.vim/bin/tagpreview.sh: line 38: *!* 576: syntax error: operand expected (error token is "*!* 576")
[bat error]: invalid digit found in string
```

**Comment by junegunn** [comment]
I can reproduce, and it seems like it was caused by a recent change in Vim.

It doesn't work with Vim 9.1, but with Vim 9.0.

```diff
diff --git a/bin/tagpreview.sh b/bin/tagpreview.sh
index e00bc2c..93acfa2 100755
--- a/bin/tagpreview.sh
+++ b/bin/tagpreview.sh
@@ -22,7 +22,7 @@ fi
 
 # If users aren't using vim, they are probably using neovim
 if command -v vim > /dev/null; then
-  VIMNAME="vim"
+  VIMNAME="/usr/bin/vim"
 elif command -v nvim > /dev/null; then
   VIMNAME="nvim"
 else
```

**Comment by junegunn** [comment]
For some reason, the recent version of Vim ignores `-s` (silent) flag for `-e` (ex mode) when executing `/.../`.

```sh
/usr/bin/vim -R -i NONE -u NONE -e -m -s <(seq 10) -c '/5/' -c q

vim -R -i NONE -u NONE -e -m -s <(seq 10) -c '/5/' -c q
```

Don't know why, but we can fix the problem by prepending `silent` or adding `tail -1` to the command.
