### ISSUE TITLE
Read a file to current buffer (like :r <filename>)

### ISSUE THREAD

**Issue by zirho** [junegunn/fzf.vim#156]
- Category
    - [x ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

Hi, 

I'd like to read a file and put it in current buffer.

Just like the command 
`:r ~/.vimrc `
something like this.

I've gone through the docs and issues including closed ones but couldn't figure out how.

Can you please give me a hint?

Thanks for the awesome plugins.

**Comment by junegunn** [comment]
```vim
call fzf#run({'sink': 'read'})
```
See https://github.com/junegunn/fzf#fzfrunoptions for the details. Alternatively, we can consider defining an expression-mapping for command-line:

```vim
cnoremap <expr> <C-X><C-F> join(fzf#vim#files(''), ' ')
```

But it does not work on Neovim (unless you disable [neovim terminal](https://github.com/junegunn/fzf/pull/593)).

**Comment by zirho** [comment]
Thank you!
