### ISSUE TITLE
abbreviate long paths with --with-nth chages search results

### ISSUE THREAD

**Issue by fabOnReact** [junegunn/fzf.vim#1561]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.2 (b896e0d)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

Thanks a lot. I'm doing OpenSource full time so I may be interested in helping you out. The library is amazing.

Related issue https://github.com/junegunn/fzf.vim/issues/1171

The `--with-nth` command changes the search results of fzf.vim.

I want to display only the last two folders in my search results. I use with `--with-nth` option with git#files. 
- The preview shows the file as `..react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput
/ReactEditText.java`
- I want to see the file as `../views/textinput/ReactEditText.java` 

**TEST CASE**
The repo where I'm using the command is https://github.com/facebook/react-native. I search the file `EditText.java`.

**EXPECTED RESULT**
Searching `EditText.java` displays a list of files is `..react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput
/ReactEditText.java` ([file](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java)).

```
command! -bang -nargs=* -complete=dir CustomGFiles
      \ call fzf#vim#files(<q-args>, {'window': { 'width': 0.7, 'height': 0.5, 'yoffset': 0.4}, 'options': ['--layout=reverse', '--preview-window=hidden']} , <bang>0)
```

Screenshot

<img width="1496" alt="Screenshot 2024-08-15 at 11 04 07 AM" src="https://github.com/user-attachments/assets/56499091-2344-41c2-9582-eb064d6ecb6e">

**TEST CASE**
I add `--with-nth=3..4` and I search for `EditText.java`.

**EXPECTED RESULT**
Searching `EditText.java` displays a list of files is `../textinput/ReactEditText.java`.

**ACTUAL RESULT**
The search result changes. The files from in directory `react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput
/ReactEditText` are excluded from the search. The first result is another file. 

```
command! -bang -nargs=* -complete=dir CustomGFiles
      \ call fzf#vim#files(<q-args>, {'window': { 'width': 0.7, 'height': 0.5, 'yoffset': 0.4}, 'options': ['--layout=reverse', '--preview-window=hidden', '--with-nth=3..4']} , <bang>0)
```

then I search EditText in this repo 

<img width="1496" alt="Screenshot 2024-08-15 at 11 03 09 AM" src="https://github.com/user-attachments/assets/68d61392-b80c-4db7-8a08-e1bb89a0fe55">

**Comment by junegunn** [comment]
* fzf doesn't tokenize words in an item around `/` unless you set `--delimiter=/`
* `--with-nth=3..4` is also strange. Unless each item consists of exactly 4 path element, this strategy won't work

So, you need `--delimiter=/` and `--with-nth=-2..` (2nd to the last element to the end), and this is what was [suggested](https://github.com/junegunn/fzf.vim/issues/1171#issuecomment-727270769) in the linked issue.

Having said that, there are alternatives.

* `--wrap` option will wrap long lines, so you can always see the entire path
    * By default wrapping can be toggled via `ALT-/`
* `--keep-right` is another option if you're interested in the right end part of the item.
