### ISSUE TITLE
fzf#wrap does not fire sink for empty list

### ISSUE THREAD

**Issue by Konfekt** [junegunn/fzf.vim#1563]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.3

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

How to make below function `Handler` fire, that is, output `No Items selected`, after running `:RunWrap` when no item was selected on Vim 9.1.686 on Ubuntu 22.04?

```vim
set nocompatible

let &rtp = '~/.vim/plugged/fzf/' . ',' . &rtp
let &rtp = '~/.vim/plugged/fzf.vim/' . ',' . &rtp

filetype plugin indent on
syntax on

function! Handler(selected)
  if empty(a:selected)
    echoerr "No items selected"
  else
    echoerr "Selected items: " . join(a:selected, ', ')
  endif
endfunction

command! -nargs=* -bang RunWrap
      \ call fzf#run(fzf#wrap({
      \ 'sink*': function('Handler'),
      \ 'source': [],
      \ 'options': '--prompt "Select an item> "'
      \ }))
```

**Comment by junegunn** [comment]
Related? https://github.com/junegunn/fzf/commit/8cb59e6fcac3dce8dfa44b678fdc94cf81efa11b#commitcomment-145744765
