### ISSUE TITLE
Question regarding command preview for fzf#vim#grep

### ISSUE THREAD

**Issue by liona24** [junegunn/fzf.vim#1564]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.3 (Fedora)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

Hey. I am currently re-using some functions for a remote search which has a rather lengthy invocation. This looks something like this in my `init.vim`:

```vim
command! -bang -nargs=* SomeCommand call fzf#vim#grep2("some very long command which mirrors --a grep --on --a server ", <q-args>, fzf#vim#with_preview(), <bang>0)
```

Problem is that the default abbreviation logic seems to fold all the args until the first `-`, i.e. the preview window looks something like this:

```
someverylongcommandwhichmirrors> ...
```

Is it somehow possible to either set the name directly or work around the abbreviation logic?

**Comment by DanSM-5** [comment]
Try passing the command as the `source` of the spec

```vim
command! -bang -nargs=* SomeCommand call fzf#vim#grep2("name-for-history", <q-args>, fzf#vim#with_preview({ 'source': 'some very long command which mirrors --a grep --on --a server' }), <bang>0)
```

**Comment by liona24** [comment]
Thanks, this appears to be working for the `fzf#vim#grep` variant at least. The `fzf#vim#grep2` variant however does not like this. It tries to execute `name-for-history` in that case anyway

**Comment by liona24** [comment]
Perfect, thanks. That is exactly what I was looking for!
