### ISSUE TITLE
FZF Vim Plugin on Windows Produces Error E282: "Cannot read from..."

### ISSUE THREAD

**Issue by mjklemm** [junegunn/fzf.vim#1566]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

n/a, gives error, FZF 0.55.0 installed

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Problem / Steps to reproduce

When trying to use FZF via the fzf.vim plugin, I'm getting the error shown in the screenshot below.  This happens with commands like `:Files`, etc.

![image](https://github.com/user-attachments/assets/c06d243e-8ac6-467c-a27b-7ac4283e7a01)

**Comment by junegunn** [comment]
> n/a, gives error

What's the error message?

**Comment by mjklemm** [comment]
It's pretty much the same root cause as with the main issue: E282

![image](https://github.com/user-attachments/assets/2357476f-28ab-41d5-8221-d3ca77513193)

**Comment by mjklemm** [comment]
Note sure, if it helps, but I dug a bit deeper into `vim.vim`.  The issues seems to come from the invocation of `system` in `s:winpath()`.  I seem to be able to reproduce this simply using `:echo system('dir')` in Vim.

**Comment by junegunn** [comment]
`set shell=...` is usually the culprit.

**Comment by mjklemm** [comment]
That was indeed the issue! Too bad that Vim does not produce a useful error message in that case.

The one weird thing, but that's how cmd.exe behaves is that it opens a window the first time you type :Files. I'll dig a bit to figure out if that can be avoided somehow.

Thanks for the remote four-eye debugging. Opening this issue was helpful in making me look deeper into this.
