### ISSUE TITLE
with grep_multi_line, quickfix text contains "file:line"

### ISSUE THREAD

**Issue by tomtomjhj** [junegunn/fzf.vim#1568]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.55.0 (fc69308)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

repro.vim
```vim
if &compatible | set nocompatible | endif
set runtimepath^=~/.fzf
set runtimepath^=~/.vim/plugged/fzf.vim

let g:fzf_vim = {}
let g:fzf_vim.grep_multi_line = 1
```

In the fzf.vim directory, run
```
vim --clean -u repro.vim
```
Then run `:RG grep`, select all (`<M-a>`), then confirm (`<CR>`). The quickfix list is populdated as follows. 
![image](https://github.com/user-attachments/assets/e273f784-07c9-48b9-af48-9f9f0f5bdb14)
Note that the text contains stuff like `README.md:78:25:`. This only happens with `g:fzf_vim.grep_multi_line = 1`.

Additional info on environment
* vim 9.1.709
* Ubuntu 22.04 (perl v5.34.0)

**Comment by junegunn** [comment]
Thanks, should be fixed now.
