### ISSUE TITLE
Completion keeps first characters of string

### ISSUE THREAD

**Issue by hbpasti** [junegunn/fzf.vim#157]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I'm trying to add a custom dictionary completion and when I choose the match it doesn't replace the whole string (word), but keeps a few characters before adding the chosen word.
I tracked this behavior down to the `virtualedit` option: when set to `all` or `onemore` it causes this behavior. But when I attempted to create my own function to call `fzf#complete` the behavior was back.

Here's what I've done:

```VimL
inoremap <expr> <c-x><c-l> fzf#vim#complete({ 'source':  'cat /usr/share/dict/words' })

function! MyCompletion()
call fzf#vim#complete({ 'source':  'cat /usr/share/dict/words' })
endfunction
inoremap <expr> <c-x><c-k> MyCompletion()
```

The first mapping (<kbd>ctrl</kbd>+<kbd>x</kbd>, <kbd>ctrl</kbd>+<kbd>l</kbd>) here works just fine. The second (<kbd>ctrl</kbd>+<kbd>x</kbd>, <kbd>ctrl</kbd>+<kbd>k</kbd>) prints the first two characters before the string.

If I add `set virtualedit=all`, then both mappings get broken: the first prints the first two characters and a space, and the last prints the first character and a space.

What am I doing wrong?

**Comment by junegunn** [comment]
I can reproduce the problem with `set virtualedit=all`, I'll look into it.

**Comment by junegunn** [comment]
c65e2ea is supposed to fix the issue (temporarily unsets `virtualedit`). Let me know if it still doesn't work as expected.
