### ISSUE TITLE
Windows defender detects as: Trojan:Script/Sabsik.FL.A!ml

### ISSUE THREAD

**Issue by oliverhr** [junegunn/fzf.vim#1576]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.56.0 (ff16877)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Problem / Steps to reproduce

Upon update `:PlugUpdate` Windows Security detected `file: C:\Users\USERNAME\AppData\Local\Temp\fzf.zip` as a Trojan

![Screenshot 2024-11-11 204738](https://github.com/user-attachments/assets/33cd28f9-8fdc-4867-b95d-44093dc1b5fb)

Vim version
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Apr 26 2024 22:26:03)
MS-Windows 64-bit console version
Included patches: 1-374
```

**Comment by junegunn** [comment]
Thanks, but it's a false positive. See https://github.com/junegunn/fzf/issues?q=is%3Aissue+trojan+is%3Aclosed

Also https://go.dev/doc/faq#virus

**Comment by oliverhr** [comment]
Hey @junegunn thank you, yeah you right, weird thing only happened to me when updating, I removed the plugin, the installed again after, PlugClean then PlugInstall and Windows Security didn't complain about it.
