### ISSUE TITLE
Colors issue when defining a custom command with --preview

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf.vim#158]
- Category
    - [x] Bug?
- OS
    - [x] Mac OS X
- Vim
    - [x] Neovim

As mentioned [here](https://github.com/junegunn/fzf/issues/596#issuecomment-225989174) I'm having a problem with colors after defining my own `Files` custom function

```vim
autocmd VimEnter * command! Files
   \ call fzf#vim#files('', { 'window': 'aboveleft 20new', 'options': $FZF_CTRL_T_OPTS })
```

The `$FZF_CTRL_T_OPTS` is actually `--preview "[ -f "{}" ] && pygmentize -g {}" --color light --bind ?:toggle-preview`

Here is a with and without the custom command

**With**
<img width="1680" alt="after" src="https://cloud.githubusercontent.com/assets/63876/16087342/fb2ad7f6-3322-11e6-9388-2cfe8ba2c823.png">

**Without**
<img width="1680" alt="before" src="https://cloud.githubusercontent.com/assets/63876/16087343/fb2ed900-3322-11e6-966a-4f7757dc4ebf.png">

**Comment by junegunn** [comment]
It looks like the result of `--color light`.

**Comment by ahmedelgabri** [comment]
That's embarrassing, sorry for the hassle & thanks for the help.

**Comment by junegunn** [comment]
No problem.
