### ISSUE TITLE
How to open files in a new window

### ISSUE THREAD

**Issue by oskarrough** [junegunn/fzf.vim#160]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, when searching for a file and pressing <enter> the file opens in the same window. Is there any way to make the default behavior open the file in a new window? I'm using a window manager which makes this desirable.

Thank you very much for this plugin! It's extremely fast.

**Comment by junegunn** [comment]
You can open the file in a vertical or horizontal split or in a new tab by pressing <kbd>CTRL-V</kbd>, <kbd>CTRL-X</kbd>, or <kbd>CTRL-T</kbd>. You can even customize the keys, see https://github.com/junegunn/fzf.vim#global-options. Does this answer your question?

**Comment by oskarrough** [comment]
Thank you but I was looking for a way to open in an entirely new window, not a vim split or tab, if possible?

**Comment by junegunn** [comment]
Yes, but opening a "window" is beyond the scope of this project and you have to write your own function/command for that.

- https://github.com/junegunn/fzf#fzfrunoptions
- https://github.com/junegunn/fzf/wiki/Examples-(vim)
- https://github.com/junegunn/fzf/wiki/Examples

**Comment by clockworkpc** [comment]
> You can open the file in a vertical or horizontal split or in a new tab by pressing CTRL-V, CTRL-X, or CTRL-T. You can even customize the keys, see https://github.com/junegunn/fzf.vim#global-options. Does this answer your question?

Champion!

**Comment by catalinux17** [comment]
> You can open the file in a vertical or horizontal split or in a new tab by pressing CTRL-V, CTRL-X, or CTRL-T. You can even customize the keys, see https://github.com/junegunn/fzf.vim#global-options. Does this answer your question?

wow! great

**Comment by kkzhang** [comment]
ctrl-T can open a new tab, but will dismiss current PopupWindow. It is intolerable in large project (open a pop takes very long time)
