### ISSUE TITLE
Avoid the extra Enter or Return key in Commands?

### ISSUE THREAD

**Issue by varmanishant** [junegunn/fzf.vim#162]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Is it possible to avoid hitting extra <kbd>Enter</kbd> or <kbd>Return</kbd> key in `:Commands`? I know certain commands needs arguments but many like tabnew, tabclose etc doesn't need that. So it is possible to make the commands without arguments work without the extra key? Has this already been addressed? As vim users we have an obession with less keys!

**Comment by junegunn** [comment]
It's possible to add an extra key binding that directly executes the command. How about `CTRL-X` (X for "eXecute)?

**Comment by varmanishant** [comment]
+1. Should be fine I guess or probably even `Spacebar` if I can make it bind for this buffer only. Vim users need single key bindings :)

**Comment by junegunn** [comment]
Update and try `let g:fzf_commands_expect = 'space'`
