### ISSUE TITLE
Alignment issues in Command

### ISSUE THREAD

**Issue by varmanishant** [junegunn/fzf.vim#163]
- Category
    - [ ] Question
    - [x] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I really love Sublime Text's command fuzzy search feature, and found fzf.vim when I checked for a an alternative in (neo)vim. It is pretty nice. Been using fzf for long but didn't know a wrapper plugin exists!

I find that few things still needs more polish but it is not clear if its FZF Commands problem or not. I can see that `:Commands` shows the function called explicitly and some of them are really not left aligned correclty. Here is the [screenshot](http://imgur.com/UANWmSy) of the issue. Why is this so and can this be addressed?

If FZF is causing this problem, is it trying to do a tabular arrangement? I can see that long commands are having this problem, while shorter titles are not. Maybe it can dropped if it is hard to show external commands in tabular fomat since column size depends on the maximum item's length? Alternative, tabular arrangement can be avoided because of the complexity involved.

**Comment by junegunn** [comment]
It simply uses the output of the built-in `:command` command, and I'm just too lazy to try to make it prettier.

**Comment by varmanishant** [comment]
Okies I was guessing that. Proably will check it sometime.

**Comment by junegunn** [comment]
Okay, thanks.
