### ISSUE TITLE
show fzf menu in current window (viz `:Unite -no-split`)

### ISSUE THREAD

**Issue by sunaku** [junegunn/fzf.vim#167]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hello,

Is there a way to show the fzf menu in the current window (instead of always splitting a new window for it)?  For example, [Shougo's unite.vim](https://github.com/Shougo/unite.vim) provides a `-no-split` option to achieve this effect:

[![Demo GIF courtesy of Christopher Sexton](http://www.codeography.com/images/unite-modal-c.gif)](http://www.codeography.com/2013/06/17/replacing-all-the-things-with-unite-vim.html)

If not, could we add it? :innocent:

Thanks for your consideration.

**Comment by junegunn** [comment]
Have you tried `let g:fzf_layout = { 'window': 'enew' }`?

**Comment by sunaku** [comment]
That's perfect! :joy_cat: Thanks :+1:

**Comment by yevhen-m** [comment]
If I use `let g:fzf_layout = { 'window': 'enew' }` each time I use fzf alternate vim buffer is lost. Is there any way to fix this issue?
