### ISSUE TITLE
Question: How to run commands on selected files in a split

### ISSUE THREAD

**Issue by zdenekkostal** [junegunn/fzf.vim#168]
- Category
    - [x] Question
- OS
    - [x] Mac OS X
- Vim
    - [x] Neovim

Hi,
first of all - thank you for this project, it raised my productivity a lot!

I didn't find any answer for my question - is it possible to run vim commands on selected files in fzf split view?

My usecase - I want to search through the files (with `Ag` command), select some of them and run `substitute` command. I tried to use following configuration, but the split view closes itself when I try to run the command.
```
let g:fzf_action = {
  \ 'ctrl-s': 'substitute',
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

Is it possible? Or do I have to use raw `Ag` command with combination of recently added `cdo`?
Thanks!

**Comment by junegunn** [comment]
The commands in `g:fzf_action` are for determining the viewport for the selected files, and they apply to only a subset of the commands this plugin provides. e.g. they are irrelevant to `:Colors` command .

> Or do I have to use raw Ag command with combination of recently added cdo?

Yes. It seems like the best option. And I don't think `substitute` without search pattern and replacement string really makes sense, right? Anyway if you know some vimscript you can write your own functions and commands using `fzf#run()` function. See:
- https://github.com/junegunn/fzf#fzfrunoptions
- https://github.com/junegunn/fzf/wiki/Examples-(vim)
