### ISSUE TITLE
Run FZF on a different directory

### ISSUE THREAD

**Issue by caneta** [junegunn/fzf.vim#169]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hello, a simple one: how can I make fzf to search in files of a specified directory?
I have a directory in which I would like to search for my files or my Java classes, but is not a subdir of my current directory...how to deal with it?

Thank you.

**Comment by junegunn** [comment]
`:Files` command (as well as `:FZF`) takes a directory argument, have you tried it?

```vim
Files
Files ..
Files ~/.vim
```

**Comment by caneta** [comment]
Now I've tried and it works. Sorry, I missed that hint in the documentation.
