### ISSUE TITLE
BTags does not work with C++

### ISSUE THREAD

**Issue by walkingsparrow** [junegunn/fzf.vim#17]
BTags works for my Python files, but on C++ files, I got "Failed to extract tags".

**Comment by junegunn** [comment]
- See the output of `:echo &filetype` from vim, it should be `python`
- Check if `ctags -f - --sort=no --excmd=number --language-force=python FILENAME` works

**Comment by walkingsparrow** [comment]
Not sure why you want me to check Python. Python works. But C++ does not
work.

2015年9月28日星期一，Junegunn Choi <notifications@github.com> 写道：

**Comment by junegunn** [comment]
Yeah, I misread the comment. Looks like `cpp` is not a valid type for ctags command.

```
ctags -f - --sort=no --excmd=number --language-force=cpp FILENAME
ctags: Unknown language "cpp" in "language-force" option
```

**Comment by walkingsparrow** [comment]
I see. It seems one possible  solution would be to force ctags to use c
tags for c++.

2015年9月28日星期一，Junegunn Choi <notifications@github.com> 写道：

**Comment by junegunn** [comment]
Hmm, I just decided to not use the option, ctags seems to do good enough job inferring the right type for the file, even checking the she-bang line.

http://ctags.sourceforge.net/ctags.html
```
Unless the −−language−force option is specified, the language of each source file is automatically selected based upon a mapping of file names to languages. The mappings in effect for each language may be display using the −−list−maps option and may be changed using the −−langmap option. On platforms which support it, if the name of a file is not mapped to a language and the file is executable, the first line of the file is checked to see if the file is a "#!" script for a recognized language.
```

**Comment by vpshastry** [comment]
Instead of providing cpp provide c++ in generating ctags.
--language-force=c++ that should work.

**Comment by vpshastry** [comment]
making it --language-force=auto solved it for me.

`ctags -f - --sort=no --excmd=number --language-force=auto %s', expand('%:S')`

**Comment by JohanChane** [comment]
Work for me.

`printf('ctags -f - --sort=yes --excmd=number --language-force=%s %s 2> %s %s', &filetype == 'cpp' ? 'c++' : &filetype, escaped, null, sort)`
