### ISSUE TITLE
how to prevent pane from shifting up

### ISSUE THREAD

**Issue by kyhy** [junegunn/fzf.vim#171]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible for the pane not to shift up when opening fzf? When the cursor is at the top of the pane, the pane doesn't move. However, when the cursor is anywhere in the middle of a screen, opening fzf would shift the pane upwards...

![fzf](https://cloud.githubusercontent.com/assets/4664197/16514198/38adeb42-3f1f-11e6-826d-868dcf8ca730.gif)

**Comment by kyhy** [comment]
One major issue was that calling `:FZF` didn't use the `let g:fzf_layout` for some reason. However, `:Files` does use `let g:fzf_layout`.

I maybe fundamentally not understanding how things are rendered in terminal... At any rate, `let g:fzf_layout = {'window': 'enew'}` works with `:Files` and that's good enough for me as it doesn't shift every split panes.

**Comment by junegunn** [comment]
There's nothing special about the way fzf splits the screen. In essence, it splits and starts terminal there.

- `botright new`: Open a new buffer at the bottom
- `terminal`: Start terminal emulator

The command you specify in `g:fzf_layout` is used to open the viewport for fzf.

```vim
" Open a new tab before the current tab
let g:fzf_layout = { 'window': '-tabnew' }

" Or split the screen vertically
let g:fzf_layout = { 'window': 'vertical new' }
```

So if you can find or write a custom command using Vimscript that preserves the relative screen offset after splitting the window, you can use it, but I suppose it's going to be a little tricky as you have to change the position of the cursor and find a way to restore the cursor position after fzf window is closed.
