### ISSUE TITLE
window: enew and %bd bug

### ISSUE THREAD

**Issue by kyhy** [junegunn/fzf.vim#173]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

How to reproduce:
1. add this line to vimrc `let g:fzf_layout = { 'window': 'enew' }`
2. open fzf then close
3. type this command `:%bd`
4. E89 error
```E89: term://.//74913:ag -g ""|"/Users/kyhy/.fzf/bin/fzf" -m  --prompt '/U/k/c/n/cs_ui'/ --expect=ctrl-v,ctrl-x,ctrl-t > /var/folders/07/1j2fkzls6sbg877tt9t45w8c0000gn/T/nvimqdufY0/1 will be killed(add ! t
o override```

Not sure how to fix this...

**Comment by junegunn** [comment]
`bufhidden=wipe` doesn't seem to work with terminal buffers.

```sh
vim foobar +'enew | b #'

# E86: Buffer 1 does not exist (expected)
vim foobar +'set bufhidden=wipe | enew | b #'

# No error
nvim +"call termopen('sh') | set bufhidden=wipe | enew | b #"
```

Yeah, there's an open issue: https://github.com/neovim/neovim/issues/2368
I'll see if we can manually remove it with `BufHidden` autocmd.

/cc @justinmk

**Comment by kyhy** [comment]
Work around: if you start vim and make a split, error from above doesn't occur, as long as fzf isn't opened in single pane view there after.

**Comment by junegunn** [comment]
Hi, this should be fixed now.

**Comment by kyhy** [comment]
sweet thank you!
