### ISSUE TITLE
fzf.vim with fzf already in system

### ISSUE THREAD

**Issue by KuoE0** [junegunn/fzf.vim#174]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it necessary to add `Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }` in vimrc if I already install fzf by homebrew (`brew install fzf`)? If the answer is yes, I just want to know why for curiosity.

**Comment by junegunn** [comment]
This plugin depends on the basic Vim plugin shipped with the main fzf repository. If you installed fzf using homebrew, either of the following will work.
1. `set rtp+=/usr/local/opt/fzf` (manually adding fzf directory to `&rtp`)
2. `Plug '/usr/local/opt/fzf'` (using vim-plug)

**Comment by KuoE0** [comment]
Thank you for the answer! I found I can use the following line to make it work! Inspired by your answer!! 😄

```
Plug 'junegunn/fzf.vim' | Plug '/usr/local/opt/fzf'
```

**Comment by junegunn** [comment]
Sounds good. I think I'm going to update the installation instructions for homebrew users. Thanks.
