### ISSUE TITLE
statusline gets reset when using g:fzf_layout = { 'window': 'enew' }

### ISSUE THREAD

**Issue by sunaku** [junegunn/fzf.vim#175]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hello,

I'm using `g:fzf_layout = { 'window': 'enew' }` to show the FZF menu in current window (per #167).

When my (Neo)Vim starts up,  my status line is:

```
:set statusline?
  statusline=%!airline#statusline(1)
```

When I press `<Return>` to select an item from `:GFiles`, the status line is being reset:

```
:set statusline?
  statusline=
```

This causes all vim-airline decorations to disappear in that _particular_ window.  Thankfully, new split windows opened afterwards are not affected by this bug: they retain the original vim-airline status line correctly.

Thanks for your consideration.

**Comment by sunaku** [comment]
Correction: this only seems to occur in NeoVim (I'm using version 0.1.4) and not in regular Vim (7.4).

**Comment by junegunn** [comment]
Should be fixed now. Let me know if you still see the problem. Thanks.

**Comment by sunaku** [comment]
Awesome! :+1: Works great now, thanks! :bow:
