### ISSUE TITLE
command "namespace"

### ISSUE THREAD

**Issue by justinmk** [junegunn/fzf.vim#18]
Thanks for this plugin, it's great.

I'm here to make my [usual request](https://github.com/chrisbra/vim-diff-enhanced/issues/4) :) The plugin defines a bunch of commands like `History` and `Lines`. But for most users the "namespace pollution" is not worth it because fzf actions are generally bound to normal-mode commands.

For the case where a user wants to try something from the command line, "namespacing" helps the user discover the available commands. This can be done either by prefixing all fzf.vim commands (`FzfLines`, `FzfHistory`), or by having a single command that takes sub-commands (`Fzf lines`, `Fzf history`) similar to `git`, `hg`, etc.

I don't suggest wrapping the default commands in a `if !exists('g:fzf_default_commands')` guard because that's lame. :sweat_smile:

**Comment by junegunn** [comment]
It's a valid request. This repo was intially supposed to be a collection of the commands that I use, take it or leave it (or fork it) kind of stuff. So I haven't paid enough attention to the customizability and I'm still not sure how it should be done. But optional command prefix sounds like a good start. I like both of the approaches you mentioned, but considering command-line completion, the first one should be simpler to implement and easier to use.

**Comment by netei** [comment]
Also agree with that, and I prefer the one word commands (eg FzfLines, FzfHistory)
