### ISSUE TITLE
Reuse previous search/query

### ISSUE THREAD

**Issue by kevintraver** [junegunn/fzf.vim#182]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Unite.vim had functionality to bring up the previous used search/query.

https://github.com/Shougo/unite.vim/blob/06b927532e1a92a948a011a07f4eb799bc8710ba/doc/unite.txt#L352-L359

I was wondering if this or something similar is possible in fzf.vim?

**Comment by junegunn** [comment]
I'm not completely sure what the command of Unite does, but you can enable search history by setting `g:fzf_history_dir`. See the description in https://github.com/junegunn/fzf.vim#global-options

**Comment by kevintraver** [comment]
The command UniteResume would bring up your previous unite command, with the previous search already populated. 

Example:
- `:Ag`
- type in _fasdfasdf_
- hit **enter**

I was looking if there was a way to then bring up `:Ag` with the most recent search (in this case _fasdfasdf_)

**Comment by NovaDev94** [comment]
@kevintraver With `g:fzf_history_dir` you can

* `:Ag`
* type in `something`
* hit *enter*
* `:Ag` again
* `Ctrl+P/N`
* Your most recent search is there

**Comment by NovaDev94** [comment]
@junegunn One small problem (not sure if it's actually a problem) with fzf.vim is I can't use the search history when I'm using some commands like `:Ag my_word_here`. Seem like fzf only stores the query string input in the fzf window, not the one sent as argument to the command.  

Is there anyway to overcome this? I'm having this binding

```vim
nnoremap K :Ag <C-r><C-w><cr>
```

**Comment by junegunn** [comment]
@NovaDev94 

> Seem like fzf only stores the query string input in the fzf window, not the one sent as argument to the command.


Yeah, fzf is a filter and does not know about the command used to populate the list. One workaround is to pass the query string to fzf using `-q` option, so that the string is stored in the history directory.

```vim
command! -nargs=* AgQ call fzf#vim#ag(<q-args>, {'down': '40%', 'options': '-q '.shellescape(<q-args>.' ')})
```

**Comment by NovaDev94** [comment]
Thanks alot @junegunn, you made such a great tool!

**Comment by edi9999** [comment]
This can be closed

**Comment by rohanghige** [comment]
> @kevintraver With `g:fzf_history_dir` you can
> 
> * `:Ag`
> * type in `something`
> * hit _enter_
> * `:Ag` again
> * `Ctrl+P/N`
> * Your most recent search is there

Does it keep uniq entries? or all entries as is?
What is limit on number of entries?
