### ISSUE TITLE
{ 'window': 'enew' } option and ESC

### ISSUE THREAD

**Issue by kyhy** [junegunn/fzf.vim#183]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Enable { 'window': 'enew' } option. Open nvim with a blank page. Use any of command to open fzf. Close fzf via ESC key. Reopen fzf. You receive a message `fzf is already runnning` and doesn't allow you to open fzf again.

However, when pressing ESC in nvim with a file open, everything appears to be fine.

**Comment by junegunn** [comment]
This was an oversight on my part. Fixed it in https://github.com/junegunn/fzf/commit/7cef92fffe4bf020fba08cdc8ad50b137e7b7974. Thanks for the report.
