### ISSUE TITLE
How to enable code preview

### ISSUE THREAD

**Issue by axot** [junegunn/fzf.vim#184]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Code preview works with Files command, and how to enable code preview for other commands, eg: Ag_raw

```
let g:fzf_files_options =
  \ '--preview "(coderay {} || cat {}) 2> /dev/null | head -'.&lines.'"'
```

**Comment by junegunn** [comment]
It's a little more complicated as we have to extract the file name and the line number from the output. This can be a start:

```vim
command! -bang -nargs=* AgRaw call fzf#vim#ag_raw(<q-args>, fzf#wrap('ag-raw',
\ {'options': "--preview 'coderay $(cut -d: -f1 <<< {}) | sed -n $(cut -d: -f2 <<< {}),\\$p | head -".&lines."50 '"}))
```

**Comment by axot** [comment]
Thank you give a hint, I am using this now, works great!

```
autocmd! VimEnter * command! -nargs=* -complete=file Ag :call fzf#vim#ag_raw(<q-args>, fzf#wrap('ag-raw',
\ {'options': "--preview 'coderay $(cut -d: -f1 <<< {}) 2> /dev/null | sed -n $(cut -d: -f2 <<< {}),\\$p | head -".&lines."'"}))
```

**Comment by termosa** [comment]
Preview works, but files are not opening. nvim receive the piece of code instead of file name.
Did you have this problem? Do you know how can it be solved?

**Comment by termosa** [comment]
@junegunn I've spent a night by trying to do the same for GitFiles (I'm not familiar with vimscript, at least a day ago). But the only option I found is to directly edit FZF plugin.
Is it possible to pass options to GitFiles from the .vimrc ? It would be nice to have a preview for all file-type searches (like Locate).

**Comment by junegunn** [comment]
@termosa Something like this?

```vim
call fzf#vim#gitfiles('', fzf#vim#with_preview('right'))
```

**Comment by termosa** [comment]
@junegunn thank you for the support! Have a nice day!

**Comment by guilala** [comment]
I am trying to get preview on marks: call fzf#vim#marks('', fzf#vim#with_preview('right'))
But like this, the preview function doesn't parse the line, column and url correctly resulting in 'File not found'. How can i make it work?

**Comment by CaioBianchi** [comment]
The above solution is no longer working. Thoughts?

**Comment by dylan-chong** [comment]
@junegunn Just wondering, the preview window is really really useful, but the preview window is only enabled for git by default, the normal :Files is does not show the preview window and unless I instead call `call fzf#vim#files('', fzf#vim#with_preview('right'))`

**Comment by lengerrong** [comment]
Use cat for preview is just too plain text, no highlight

let g:fzf_files_options =
  \ '--preview "(coderay {} || cat {}) 2> /dev/null | head -'.&lines.'"'

We can use source-highlight to enhance the preview result on ubuntu.

sudo apt-get install source-highlight
vim ~/.bashrc
# less hightlight
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=" -R "
source ~/.bashrc

let g:fzf_files_options =
  \ '--preview "(coderay {} || less {}) 2> /dev/null | head -'.&lines.'"'

**Comment by devenv** [comment]
So, is there a way to enable preview on `fzf#vim#marks()`?

**Comment by junegunn** [comment]
If you can come up with a command/script that generates preview output for each line of `:marks`, you can pass it to the function like so:

```vim
call fzf#vim#marks({'options': ['--preview', 'echo foo']})
```

**Comment by raducucu** [comment]
Was looking for preview on Marks, thanks for the hint.
I use `'--preview', 'cat -n {-1} | egrep --color=always -C 10 ^[[:space:]]*{2}[[:space:]]'`, does exactly what I need.

**Comment by Glavnokoman** [comment]
> Preview works, but files are not opening. nvim receive the piece of code instead of file name.
> Did you have this problem? Do you know how can it be solved?

have the same issue with nvim. Did you find the solution?

**Comment by raducucu** [comment]
> > Preview works, but files are not opening. nvim receive the piece of code instead of file name.
> > Did you have this problem? Do you know how can it be solved?
> 
> have the same issue with nvim. Did you find the solution?

If current buffer is open, nvim return the line instead of file name. I use something like this:
`(test -f {-1} && echo {-1} || echo ' . expand('%.p') . ') | xargs -I{} '.s:bin['preview'].' {}:{2}`

**Comment by gennaro-tedesco** [comment]
> ```viml
> call fzf#vim#gitfiles('', fzf#vim#with_preview('right'))
> ```

Strangely enough, this does not work for the `GFiles?` version, namely the `git diff` is not shown (the preview buffer is empty instead).

**Comment by fedoranvar** [comment]
Here is preview for marks. (Took from https://github.com/chengzeyi/fzf-preview.vim)

```vim
function! s:fzf_preview_p(bang, ...) abort
    let preview_args = get(g:, 'fzf_preview_window', ['top:50%', 'ctrl-/'])
    if empty(preview_args)
        return { 'options': ['--preview-window', 'hidden'] }
    endif

    " For backward-compatiblity
    if type(preview_args) == type('')
        let preview_args = [preview_args]
    endif
    return call('fzf#vim#with_preview', extend(copy(a:000), preview_args))
endfunction

  command! -bar -bang MP
        \ call fzf#vim#marks(
        \     s:fzf_preview_p(<bang>0, {'placeholder': '$([ -r $(echo {4} | sed "s#^~#$HOME#") ] && echo {4} || echo ' . fzf#shellescape(expand('%')) . '):{2}',
        \               'options': '--preview-window +{2}-/2'}),
        \     <bang>0)

```

**Comment by ChHaeni** [comment]
> Here is preview for marks. (Took from https://github.com/chengzeyi/fzf-preview.vim)
> 

Thx!

Changing the command as below doesn't fail to display marks in the current file on an empty line:

```vim
  command! -bar -bang MP
        \ call fzf#vim#marks(
        \     s:fzf_preview_p(<bang>0, {'placeholder': '$([ -r $(echo {4} | sed "s#^~#$HOME#") ]  && [ -n {4} ] || echo ' . fzf#shellescape(expand('%')) . '):{2}',
        \               'options': '--preview-window +{2}-/2'}),
        \     <bang>0)
