### ISSUE TITLE
Send results to quickfix list from any fzf command

### ISSUE THREAD

**Issue by phcerdan** [junegunn/fzf.vim#185]
- Category
  - [x] Question
  - [ ] Bug
  - [ ] Suggestion
- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Vim
  - [ ] Vim
  - [x] Neovim

Hi, is there any function to copy fzf results to quickfix or location list?

Same functionality than the already implemented `<alt-a>`  [in the wiki examples](https://github.com/junegunn/fzf/wiki/Examples-%28vim%29#narrow-ag-results-within-vim), but extended to any `fzf` command, not only `Ag`.

Is that possible? Thanks!

**Comment by junegunn** [comment]
No, it's currently implemented in each sink function. But I like the idea of making it generally applicable. Would be nice if it can be done by [`fzf#wrap()`](https://github.com/junegunn/fzf#fzfwrap) function which handles `g:fzf_action`. I'll think about it. Thanks.

**Comment by scottgrayson** [comment]
I would be interested in this too. I'm looking for a solution for project wide search and replace. This proposed feature would allow you to use :cdo after doing a search correct? What do others use for project wide search and replace currently?

**Comment by phcerdan** [comment]
@scottgrayson for the search with the fzf `:Ag` command this feature is already implemented. You do the fuzzy search, then `<Alt-a>` to copy all those results to the quickfix list. And then you can `:cdo` to replace every entry.
This PR is about doing the copying to quickfix list, but for all other commands, not only `Ag`.

**Comment by scottgrayson** [comment]
Thanks for the clarification. I am using alt-a for something else is there an easy way to change the shortcut for that?

**Comment by phcerdan** [comment]
I think the shortcut is hard-coded, so not really easy. The recommended way to use this plugin is to fork it, and tweak your preferences, but that's not fast. For your use case (search and replace/refactor) probably you don't really need the fuzzy search, so the faster way would be to use grep, ag, or [ack](https://github.com/mileszs/ack.vim) directly.

**Comment by junegunn** [comment]
> is there an easy way to change the shortcut for that?

Not *easy*, but you can override default key binding using the underlying autoload function for the command.

```vim
autocmd VimEnter * command! -nargs=* Ag
  \ call fzf#vim#ag(<q-args>, {'options': '--bind alt-a:ignore,alt-b:select-all', 'down': '40%'})
```

**Comment by tdroxler** [comment]
Hello, any news about this feature? Would be really neat indeed :+1:

**Comment by junegunn** [comment]
We can start here: https://github.com/junegunn/fzf/commit/2069bbc8b54fa77384e42274ee15af7b397af884

For example,

```vim
" CTRL-A CTRL-Q to select all and build quickfix list

function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

let g:fzf_action = {
  \ 'ctrl-q': function('s:build_quickfix_list'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all'
```

Note that `g:fzf_action` only applies to commands that handle plain file paths (i.e used by `fzf#wrap()` with arguments without explicit sink). In other cases, you'll have to implement your own sink function.

**Comment by tdroxler** [comment]
Awesome, thanks

**Comment by ViRu-ThE-ViRuS** [comment]
> > We can start here: [junegunn/fzf@2069bbc](https://github.com/junegunn/fzf/commit/2069bbc8b54fa77384e42274ee15af7b397af884)
> 
> It appears as of [aedd47b](https://github.com/junegunn/fzf.vim/commit/aedd47be21f08b68b2416e6d05dfafbcb6283609) , this behavior is built-in

how can we use this?

**Comment by allan-simon** [comment]
@vegerot  if it's built-in how does one use it ? (sorry noob question)

**Comment by kunev** [comment]
> @vegerot if it's built-in how does one use it ? (sorry noob question)

Not familiar with the code of `fzf.vim`, but through poking at stuff until it works, if you look at [the first line of the referenced change](https://github.com/junegunn/fzf.vim/commit/aedd47be21f08b68b2416e6d05dfafbcb6283609#diff-30dabdc2bd145ded5073c1a12d6e5dff56db7c8c5919d8c0d2ed402be009261cR261), it defines a function `s:fill_quickfix`.
The way you define `fzf.vim`'s keybindings is through the `g:fzf_action` map, so I added `ctrl-q` to it to point to `fill_quicklist`, the final result looks like this:

```vimL
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'ctrl-q': 'fill_quickfix'}
```

So now when you have some results in a `fzf` split you can `<alt-a>` to select all of them and then `<c-q>` to send them to quickfix.
