### ISSUE TITLE
Customize command output format

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#187]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hey, can I customize command output format somehow?
For example, I want to remove all fields except filename from `Buffers` command output.

**Comment by junegunn** [comment]
No, it's [not possible](https://github.com/junegunn/fzf.vim#rationale) at the moment. You might want to consider writing your own command using `fzf#run()` and `fzf#wrap()`.

https://github.com/junegunn/fzf#usage-as-vim-plugin

**Comment by yevhen-m** [comment]
@junegunn thanx.
