### ISSUE TITLE
How to use commands?

### ISSUE THREAD

**Issue by yqrashawn** [junegunn/fzf.vim#188]
- Category
    - [x ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

 Just don't understand how to use those commands in READEME, like Buffers, Maps.

**Comment by yqrashawn** [comment]
Does it suppose to be used as `:FZF`?
I tried `:Files` `:Buffers` and get "Not an editor command".

**Comment by yqrashawn** [comment]
It's the homebrew issue, works fine now. Sorry to bother.

**Comment by thejspr** [comment]
@yqrashawn Can you expand on what the problem was and how you fixed it? I'm having the same issue :)

**Comment by yqrashawn** [comment]
@thejspr It's been a long time. Can remember what happened. Maybe homebrew didn't link it into /use/local/bin? 
And I'm using emacs now……

**Comment by thejspr** [comment]
No problem @yqrashawn, turncloak! 😄

**Comment by YoungxHelsinki** [comment]
@thejspr: Did you fix this? I have the same issue.

**Comment by thejspr** [comment]
@YoungxHelsinki Turns out I had an issue with `vim-plug` reporting it had installed fzf.vim, but in reality it hadn't. I resolved the issue by removing both `fzf.vim` and `fzf`. Then re-adding them and installing. This made everything work out fine.

My config:

`
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
`

**Comment by YoungxHelsinki** [comment]
@thejspr Thanks for an instant reply. In my case I forgot to run `PlugInstall`. I thought reloading `.vimrc` would install plugins in Vim.
