### ISSUE TITLE
FZF buffers and commits wrong colors

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#189]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

![image](https://cloud.githubusercontent.com/assets/10185058/17960965/b44cfadc-6ab1-11e6-91db-c85e76597f13.png)
![image](https://cloud.githubusercontent.com/assets/10185058/17960993/d94a1edc-6ab1-11e6-876f-f9ec837f5b96.png)

Can you help me fix this black color (buffer number, commit star and time)? I can hardly see it.

It's strange, but other commands work fine.
![image](https://cloud.githubusercontent.com/assets/10185058/17961115/84c15e60-6ab2-11e6-9009-7a5ac9a37435.png)

**Comment by junegunn** [comment]
They're in black foreground color. They look fine on my terminal but I probably shouldn't use black as it's not very readable on some terminal color schemes (http://iterm2colorschemes.com/). I'll change the color and let you know.

**Comment by yevhen-m** [comment]
@junegunn cool, thanx.

**Comment by junegunn** [comment]
By the way, the buffer number is displayed in the color of `Number` highlight group, they're not supposed to be black? What is the output of `:hi number`?

**Comment by yevhen-m** [comment]
`Number         xxx ctermfg=16 guifg=#f99157`

**Comment by junegunn** [comment]
So it's black?

**Comment by yevhen-m** [comment]
16 is orange with my colorscheme.

**Comment by yevhen-m** [comment]
![image](https://cloud.githubusercontent.com/assets/10185058/18033209/a76b8efc-6d25-11e6-8377-db41aa8473d2.png)

**Comment by junegunn** [comment]
https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg

16 is supposed to be black. The orange is from guifg. Clearly, ctermfg and guifg are not in sync. fzf does not support true colors so it has to use ctermfg instead of guifg, but in this case it produces undesirable result. Maybe I should tell fzf.vim not to use the colors from the current color scheme, if termguicolors is set.

**Comment by yevhen-m** [comment]
`echo &termguicolors` produces `0` if it helps you somehow.
I use neovim with base16 colorscheme
```
let base16colorspace=256  " Access colors present in 256 colorspace
colorscheme base16-eighties
```

**Comment by junegunn** [comment]
Do you still see orange if you do `echo -e "\x1b[38;5;16mfoo"` on your terminal?

**Comment by yevhen-m** [comment]
Yes, foo is displayed in orange.

**Comment by junegunn** [comment]
Okay, what if you do it in neovim terminal (`:terminal`)? Still orange? Anyway, I'm not sure if it's appropriate that a terminal color scheme changes the color of `16` to orange. Try changing the color scheme of your terminal, or you might want to check out `:help terminal-emulator-configuration`. And let me know if you still think fzf.vim should handle it differently.

I just pushed the commit that replaces blacks with greens.

**Comment by yevhen-m** [comment]
@junegunn thanx for the green.

**Comment by playtimestudios** [comment]
Hi @junegunn,

Installed fzf over the weekend and having fun learning how to use it. First thing I noticed was how fast it is, fantastic.

I'm having this same problem with the Tomorrow Night theme.

AFAIK I have the latest versions of everything. Installed fzf with Homebrew.

On an aside, is there a way to set up fzf so it picks up colours from the terminal theme? If it's something that's possible but you haven't got around to, I'd be happy to have a go.

Thanks

**Comment by yevhen-m** [comment]
@junegunn by the way, you changed black to green only for `Commits`. Could you please change it for `Buffers` too? 
![screenshot 2016-11-21 14 06 51](https://cloud.githubusercontent.com/assets/10185058/20482172/daa216ea-aff3-11e6-971a-ef974b1d9847.png)

**Comment by junegunn** [comment]
> is there a way to set up fzf so it picks up colours from the terminal theme?

You can pass `--color 16` option so that fzf uses default 16 colors. However, fzf.vim will use addtional colors from the current color scheme.

Regarding the black color, it's because your color scheme does not set `ctermfg` for certain highlight groups. See https://github.com/junegunn/fzf/issues/729.

**Comment by habitullence** [comment]
Thanks @junegunn, the `--color 16` option fixed the colour scheme issue.

I had a look at issue 729. In my scheme `:hi number` returns `Number xxx ctermfg=16 guifg=#fd8b19`, also orange. To fix the blacks I'm not sure if I should update `ctermfg` or the colour should be changed from black to green in fzf, as was done previously for commit messages.

I'm using base16 too, I'll try and figure out what's going on with those.

**Comment by junegunn** [comment]
> Number xxx ctermfg=16 guifg=#fd8b19

fzf does not support 24-bit colors so it uses ctermfg=16 which is indeed black. See https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg

Since the color scheme is designed to provide GUI colors, we probably can't blame it for not properly setting cterm colors. Maybe we should not extract colors from the color scheme if GUI colors are used.

**Comment by habitullence** [comment]
I've not really played with colour schemes before so need to do some research but I think the problem is with base16. `hi Number ctermfg=208` fixed the issue for me and displays as I would expect it to.

**Comment by yevhen-m** [comment]
I've also set `hi Number ctermfg=14`. 
@junegunn thanks for help.
