### ISSUE TITLE
Remove current buffer from Buffers list

### ISSUE THREAD

**Issue by antoyo** [junegunn/fzf.vim#193]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
- Vim
    - [x] Vim
    - [x] Neovim

Hello.
It would be nice to remove the current buffer when using the `:Buffers` command (as the `CtrlP` plugin is doing).
This is useful when a have multiple buffers with the same name, e.g. `src/lib.rs` and `test/lib.rs` (when you type `lib` in the `:Buffers` command), because if the current buffer is in the list, it will be selected by default.

Thanks.

**Comment by junegunn** [comment]
Hi, I applied `--header-lines=1` option to `:Buffers` command to make it impossible to select the current buffer. This assumes that the current buffer is always at the front of the list, which may not be true in older versions of vim without `*reltimefloat`.
