### ISSUE TITLE
how can I find a file inside a dot directory?

### ISSUE THREAD

**Issue by sfwn** [junegunn/fzf.vim#194]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hello, I installed fzf and fzf.vim last night, and I found that's faster than unite. I like it.

But how can I find a file inside a dot directory(such as `~/.m2/settings.xml`) with fzf.vim? If my `CWD` is `~/.m2`, I can find `settings.xml`; But if my `CWD` is `~`, I can't. 

I searched around the doc and issues but found nothing.

Please tell me, thank you.

**Comment by junegunn** [comment]
Try setting up `FZF_DEFAULT_COMMAND`. You can do it either in your shell configuration file or in vimrc. For example this one uses ag command and includes hidden files:

```sh
# in bashrc/zshrc
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
```

```vim
" Or in your vimrc (or init.vim)
let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -g ""'
```

**Comment by sfwn** [comment]
so nice! thank you!

**Comment by dylan-chong** [comment]
Just a note for anyone using `rg`, you can do the same thing as above using

    export FZF_DEFAULT_COMMAND="rg --files-with-matches --hidden '.' --glob '!.git'"
