### ISSUE TITLE
fzf#run removed when including fzf.vim

### ISSUE THREAD

**Issue by lohfu** [junegunn/fzf.vim#199]
Suddenly, if I load the fzf.vim plugin `fzf#run` seems to become undefined. If only load plain fzf plugin i can `:call fzf#run()`. But if i do load both fzf and fzf.vim, the only fzf function i can find is `fzf#complete`. Calling `:Files` gives `Unkown function: fzf#run()` error.

The strange thing is i'm pretty sure i had this running earlier today.

Arch Linux, kernel  4.7.4-1, NVIM 0.1.5

I reduced my `init.vim` to the absolute (conventient) minimum:

```
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" required
set runtimepath^=$HOME/.config/nvim/repos/github.com/Shougo/dein.vim

" required
call dein#begin(expand('$HOME/.config/nvim'))

" Let dein manage dein
" required
call dein#add('Shougo/dein.vim')

call dein#add('junegunn/fzf')
call dein#add('junegunn/fzf.vim')

" required
call dein#end()

" required
filetype plugin indent on

syntax on
```

- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

**Comment by junegunn** [comment]
It's possibly an issue of the plugin manager you use. vim-plug doesn't suffer the problem.

**Comment by lohfu** [comment]
I can confirm it works with vim-plug. I'm now hooked to FZF so i see no option but to switch to your plugin manager. Clever move :wink:

**Comment by junegunn** [comment]
Haha, it was a shameless *plug*. Anyway, you shouldn't have any problem with other plugin managers as well, pathogen, vundle, neobundle, etc. I'm not sure but I think I've heard that dein.vim does some clever tricks like merging plugin files to reduce the startup time, so maybe it's related to the process.
