### ISSUE TITLE
Usage with ripgrep

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/fzf.vim#203]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

So I am trying to set this up with [rg](https://github.com/BurntSushi/ripgrep) which is similar to [ag](https://github.com/ggreer/the_silver_searcher).

While I was using `ag` I had the following command:  

`command! -bang -nargs=* Find call fzf#vim#ag(<q-args>, '--literal --ignore-case --skip-vcs-ignores --depth -1', {'window': 'enew'})`

Now I tried setting `rg` up like this:  

`command! -bang -nargs=* Find call fzf#vim#rg(<q-args>, '--text --fixed-string --ignore-case --no-ignore --hidden --follow', {'window': 'enew'})`

This gives the following error: `Unknown function: fzf#vim#rg` I did not realise the `fzf#vim#ag` was something the `fzf.vim` had added in (sorry my vimscript knowledge is limited).

Can I do this manually or is it something that needs to be added into `fzf.vim` and if so would that be something you would be interested in?

Cheers.

**Comment by junegunn** [comment]
There's a discussion on adding a generalized version of grep function in #36.  I'll let you know of the progress there.
