### ISSUE TITLE
ag_raw not working anymore

### ISSUE THREAD

**Issue by k4nar** [junegunn/fzf.vim#206]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'm using `ag_grep` via the following command:
```
command! -nargs=+ -complete=file AgRaw call fzf#vim#ag_raw(<q-args>)
```

But since the last update, every time I try to use AgRaw I get the following error:
```
Error detected while processing function fzf#vim#ag_raw[1]..fzf#vim#grep[23]..<SNR>106_fzf:
line   12:
E605: Exception not caught: invalid number of arguments
```

**Comment by junegunn** [comment]
Thanks, it was a regression caused by a recent refactoring.

**Comment by junegunn** [comment]
Related: #36
