### ISSUE TITLE
Blank lines in Ag

### ISSUE THREAD

**Issue by peanutandchestnut** [junegunn/fzf.vim#209]
- Category
    - [x] Bug
- OS
     - [x] Linux
- Vim
    - [x] Neovim

Hi Junegunn:

Alt-a in Ag result will select blank lines, this will cause problem in s:ag_to_qf.
Blank lines can be eliminated by adding `--nobreak` to ag command.  But would it be better if Alt-a can filter blank lines?

**Comment by junegunn** [comment]
Can you post a screenshot? I don't see any empty lines, and which version of ag are you running?

**Comment by peanutandchestnut** [comment]
ag version 0.31.0

I'm using fzf#vim#ag_raw with an extra option '--noheading'.
I need this to do  `Ag something %`,  '--noheading' will cause blank lines between file groups if you didn't search in a specific file.

**Comment by junegunn** [comment]
Can you use `--nogroup` instead?

https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L555

**Comment by peanutandchestnut** [comment]
`--nogroup` won't work for single file, `--noheading --nobreak` works.

**Comment by junegunn** [comment]
I see. 3 possible ways to address the problem.

What you can do:
- Make your vim function switch between the two options depending on the number of files
- Append something like ` | sed "/^$/s"` to the argument to filter out empty lines before passing it to fzf

What I can do:
- Update sink function of `fzf#vim#grep` to ignore empty lines. ALT-A will still select empty lines, but fzf.vim will ignore it.

**Comment by junegunn** [comment]
Pushed the fix. Let me know if you still have issues.

**Comment by peanutandchestnut** [comment]
Great work.
