### ISSUE TITLE
Error with fzf#wrap when calling :Files or :GitFiles

### ISSUE THREAD

**Issue by dmix** [junegunn/fzf.vim#210]
After running :PlugUpdate I now get this error whenever I run `:Files` or `:Gitfiles`:
 
    line8:   
    E117: Unknown function: fzf#wrap   
    E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
    line   10: 
    E121: Undefined variable: wrapped  
    E15: Invalid expression: wrapped   
    Error detected while processing function Fuzz[5]..fzf#vim#gitfiles[6]..<SNR>98_fzf[18]..fzf#run[8]..<SNR>49_upgrade:   
    line2: 
    E715: Dictionary required  
    Error detected while processing function Fuzz[5]..fzf#vim#gitfiles:
    line6: 
    E171: Missing :endif   
    Error detected while processing function Fuzz:
    line5:
    E171: Missing :endif  

It works fine after rolling back the plugin repo to before this commit "Refactor code with fzf#wrap": 
https://github.com/junegunn/fzf.vim/commit/6d1916197c24984a649dea0cb82357eb0958ec20

Am I missing something on my end?

**Comment by junegunn** [comment]
It means that you have an outdated version of Vim plugin file from the main fzf repository. Please update it and see how it goes.

https://github.com/junegunn/fzf#upgrading-fzf

**Comment by crypticsymbols** [comment]
I am having the same problem, but I am using the most recent version of fzf.vim and FZF (OSX, homebrew, reinstalled this morning).

**Comment by jketcham** [comment]
I was having this issue before as well, but updating brew and upgrading fzf with `brew upgrade --HEAD fzf`, then running the install script (`/usr/opt/fzf/install` I believe, it comes in brew's post-install messages) seems to have fixed it. Running vim 8.

**Comment by junegunn** [comment]
@crypticsymbols fzf.vim depends on the vim plugin of fzf, and you should make it also available on Vim. Please follow the installation instructions.

**Comment by yeongsheng-tan** [comment]
Confirmed above similar problem solved by
```
brew upgrade --HEAD
```

```
==> Upgrading 1 outdated package, with result:
fzf HEAD
==> Upgrading fzf
==> Installing dependencies for fzf: glide
==> Installing fzf dependency: glide
==> Downloading https://homebrew.bintray.com/bottles/glide-0.13.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glide-0.13.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glide/0.13.0: 6 files, 10.2MB
==> Installing fzf --HEAD
==> Cloning https://github.com/junegunn/fzf.git
Cloning into '/Users/yeongsheng/Library/Caches/Homebrew/fzf--git'...
remote: Counting objects: 93, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 93 (delta 3), reused 24 (delta 2), pack-reused 0
Unpacking objects: 100% (93/93), done.
==> Checking out branch master
==> glide install
==> go build -o /usr/local/Cellar/fzf/HEAD-0b33dc6/bin/fzf -ldflags -X main.revision=brew
==> Caveats
To install useful keybindings and fuzzy completion:
  /usr/local/opt/fzf/install

To use fzf in Vim, add the following line to your .vimrc:
  set rtp+=/usr/local/opt/fzf
==> Summary
🍺  /usr/local/Cellar/fzf/HEAD-0b33dc6: 17 files, 3.2MB, built in 22 seconds
```
Attempted with OSX High Sierra 10.13.0

**Comment by markstos** [comment]
I got this error today using both Vim 8 and the latest NeoVim, using `git` to install FZF and `vim-plug` to install this plugin. I don't seem to have any other version of `fzf.vim` installed.

**Comment by junegunn** [comment]
You need to set up both main fzf repo and fzf.vim in Vim as described on README page. It's actually a common mistake and I should probably update the plugin to print better error messages in that case.

**Comment by yeongsheng-tan** [comment]
Gee. Awesome.

I now have in my ~/.janus dir the following:

1. git@github.com:junegunn/fzf.vim.git
2. sym-link /usr/local/opt/fzf into ~/.janus (fzf installed via Homebrew)

And now my vim is on steriods. Espeically like the :Commits and :Files power! 🕺

**Comment by rxacevedo** [comment]
I know this is closed, but for anyone else who installed `fzf` via Homebrew and `fzf.vim` via git/Pathogen/etc and ended up here, you may need to add this line to `~/.vimrc`:

`set rtp+=/usr/local/opt/fzf`

It's in the [README](https://github.com/junegunn/fzf#as-vim-plugin) for `fzf`.

**Comment by krishicks** [comment]
I installed `fzf` by cloning the repository and running `./install`, but ran into this same error.

It wasn't clear to me that the expectation was that you provide `junegunn/fzf` *as well as* `junegunn/fzf.vim` to vim. I don't use VimPlug or homebrew so the instruction

```
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
```

didn't make sense to me until I realized that `junegunn/fzf` has a `plugin/` directory.

The README-VIM on `junegunn/fzf` just says "If you have set up fzf for Vim, :FZF command will be added.", which I found not to be helpful at all.

So, when using vim-pathogen:

```
git clone https://github.com/junegunn/fzf ~/.vim/bundle/fzf
~/.vim/bundle/fzf/install --bin
git clone https://github.com/junegunn/fzf.vim ~/.vim/bundle/fzf.vim
```

**Comment by rpietro** [comment]
For people installing through Plug, the solution that worked for me is also on the README page:

>  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

works like a charm

**Comment by markstos** [comment]
I think the important thing to address in this issue is to provide a better diagnostic message for people who run into them. Clearly there are solutions to the problem-- it would be helpful if the diagnostic message pointed to one of them.

**Comment by lebyzhao** [comment]
please check the fzf dir you installed, there are mang .go files depends.

**Comment by topke011** [comment]
fzf#wrap function is from junegunn/fzf reposity (https://github.com/junegunn/fzf/blob/6390140539caacfb6fd16729d3e6ba4341815b0e/plugin/fzf.vim).

This plugin is wrapper around above mentioned. So you need above in order to run this plugin.
I did it by cloning above file into my vimfiles/bundle/fzf/autoload/fzf.vim

Then I cloned this repo into vimfiles/bundle which created fzf.vim.

Of course you need fzf.exe in order to run all of this...

**Comment by fpvmorais** [comment]
For those that are on windows and installed fzf via chocolatey:

`
Plug '/c/ProgramData/chocolatey/bin/fzf'
Plug 'junegunn/fzf.vim'
`

**Comment by arbitrarily** [comment]
> I know this is closed, but for anyone else who installed `fzf` via Homebrew and `fzf.vim` via git/Pathogen/etc and ended up here, you may need to add this line to `~/.vimrc`:
> 
> `set rtp+=/usr/local/opt/fzf`
> 
> It's in the [README](https://github.com/junegunn/fzf#as-vim-plugin) for `fzf`.

my man! thank you for this solution
