### ISSUE TITLE
Scroll inside preview?

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf.vim#211]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I noticed that in the examples that you pipe the output to `head` so how can I scroll inside the preview?

**Comment by junegunn** [comment]
The examples with head were written before scrolling was supported.

FYI, https://github.com/junegunn/dotfiles/commit/b4c01bbd8d0678d6ff3b927cb5141b1e363f3561

The head part still makes sense if you don't need to scroll, or if it takes too long for the preview command to finish that the delay is noticeable.

**Comment by ahmedelgabri** [comment]
> The examples with head were written before scrolling was supported.

Does this means that it's supported now?

> The head part still makes sense if you don't need to scroll, or if it takes too long for the preview command to finish that the delay is noticeable

Nice, didn't think about that.

**Comment by junegunn** [comment]
Yep, see https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0152

**Comment by ahmedelgabri** [comment]
Great, thanks

**Comment by rofrol** [comment]
Example binding:

```bash
git-commit-show () 
{
  git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"  | \
   fzf --ansi --no-sort --reverse --tiebreak=index --preview \
   'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1 ; }; f {}' \
   --bind "j:down,k:up,alt-j:preview-down,alt-k:preview-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up,q:abort,ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF" --preview-window=right:60%
}
```

https://gist.github.com/junegunn/f4fca918e937e6bf5bad#gistcomment-2731105
