### ISSUE TITLE
Using ag inside vim

### ISSUE THREAD

**Issue by oskarrough** [junegunn/fzf.vim#212]
Hi, I'm looking to create a vim mapping that runs a command like `ag -g "" | fzf` when I press `<leader>p`.

How would you do that?

If I set these two fzf will use the ag command automatically when I press CTRL+T. This is great. And exactly what I'm looking for inside vim.

```
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

**Comment by junegunn** [comment]
`:Files` command from this repo respects `$FZF_DEFAULT_COMMAND`, so you already have it.

**Comment by oskarrough** [comment]
I tracked it down to my own mistake. Missed the `-gx` argument in my fish config.

```
set -gx FZF_DEFAULT_COMMAND 'ag -g ""'
set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
```

Works perfectly with `:Files` now. Sorry about that - thank you.
