### ISSUE TITLE
API stability/tagged releases questions...

### ISSUE THREAD

**Issue by wadestuart** [junegunn/fzf.vim#213]
- Category
  - [X ] Question
  - [ ] Bug
  - [ ] Suggestion
- OS
  - [ X] Linux
  - [ X] Mac OS X
  - [ X] Windows
  - [ X] Etc.
- Vim
  - [ X] Vim
  - [ X] Neovim

First,  thank you for making FZF and FZF.vim,  they are awesome!  I have noticed reading through the issues that many times when people have offered to extend the feature set (for instance fzf MRU) that the direction given was to create their own projects that create and manage those features.  I totally understand this thought as it allows you to focus on core FZF as well as reducing the overhead of supporting those feature bits.   I am, however,  starting to see a trend where those external feature repos are starting to conflict out with FZF head.   a few times in the last few weeks some of the refactoring and other changes happening in FZF.vim/FZF heads have necessarily broken (by changing) some of the interfaces that those externals rely on.   This of course is natural -- if FZF can't be refactored and updated it becomes stale.   I think the issue is that the vim plugin infrastructure does not have great interfaces to ensure use of public/private interfaces -- and even if it did many of these plugins just would need to jump into internals to accomplish the features they are being created for.    What I am suggesting is that it may be time to rely on releases/taged heads (with stable API) so that the authors of the extensions can rely on most of the plugin manager's default operation to ensure they can match your releases/head more easily.  This would seem to offer the best of both worlds -- where aggressive updating users to FZF can choose to run bleeding edge and the majority of users can choose to run the last release while any extension plugins can target the tagged releases.   

As it stands now,  if a user uses FZF.vim/FZF and one or more of the extension plugins every update is Russian roulette OR they must hand pin known working versions and become stale until they go through a process of working through the commit logs of each repo to try to find a safe overlap applied to the same API.   

I guess I am looking for your take on this stuff and to let you know that this is starting to pop up for users.   I am not sure that tagged releases are the best (or even good) answer here,  but it would be very nice to be able to update all of my vim plugins without breakage (or without heavy pinning) again.  I use a lot of plugins and try to update them weekly which historically means I have run into problems maybe once or twice per year until this point.

**Comment by junegunn** [comment]
Hi, the only stable APIs at the moment are `fzf#run` and `fzf#wrap` functions from the main fzf repo. And I don't think I made any change to them that would break backward compatibility. On the other hand, the autoload functions this project provides are not guaranteed to be backward-compatible [as noted in the README page](https://github.com/junegunn/fzf.vim#rationale). So using them is basically "AYOR".

While I agree with your points, the way I see it is that fzf.vim project has not been developed as or posed as a typical application or a library on which an external code can safely rely on. The purpose of it has been to showcase, to give examples of what fzf and vim are capable of. It is a collection of a wide variety of features – maybe too wide without enough cohesion and consistency – extracted from my own configuration. They don't even have any tests. It will take time and a lot of consideration to come up with stable, consistent API for such diverse set of features with accompanying test cases. And before that happens, I'm reluctant to call this project more than a set of examples.

>  I use a lot of plugins and try to update them weekly which historically means I have run into problems maybe once or twice per year until this point.

6d1916197c24984a649dea0cb82357eb0958ec20 was a big change and it caused some troubles, but except for that occasion, this project has been quite stable I would say. And as far as I remember, there was no breaking change of API except for `fzf#vim#ag_raw`, even though it is stated that backward-compatibility is not guaranteed.

**Comment by andreypopp** [comment]
It would be good if `fzf#run` handled `g:fzf_colors` to re-use theming mechanisms for other plugins.

**Comment by junegunn** [comment]
@andreypopp `fzf#wrap()` does that. https://github.com/junegunn/fzf/commit/37f2d8f7952879bffd1326b88e4f0069ec1188d7
