### ISSUE TITLE
Tags it returns empty results

### ISSUE THREAD

**Issue by mikezaby** [junegunn/fzf.vim#22]
When i run `Tags` even if i have compiled the tags manualy or let the fzf create it, i have no results.

I am using vim in debian testing
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 17 2015 03:37:50)
Included patches: 1-826
```

**Comment by junegunn** [comment]
What is the output of `:echo tagfiles()`?

**Comment by mikezaby** [comment]
The output is `['tags']`

**Comment by junegunn** [comment]
Maybe the file is empty. Can you open it and see if it contains the tags you want?

**Comment by mikezaby** [comment]
I think the tags file is ok.
I create a dummy project for this purpose: https://github.com/mikezaby/fzf-test.
The tag file: https://raw.githubusercontent.com/mikezaby/fzf-test/master/tags

For example: I am in `app/controllers/articles_controller.rb`, if i press `ctrl+}` in line 7 `Article`, it opens correctly the `app/model/article.rb`, but the `:Tags` is empty.

**Comment by junegunn** [comment]
Alright, can you check if this command works? It's what Tags command does internally.

```
perl -ne 'unless (/^!/) { s/^(.*?)\t(.*?)\t/\x1b[33m\1\x1b[m\t\x1b[34m\2\x1b[m\t/; print }' tags
```

**Comment by mikezaby** [comment]
It seems to work, a small sample of the output

```
zip	/home/miza/.rvm/gems/ruby-2.2.0/gems/sass-3.4.18/lib/sass/script/functions.rb	/^    def zip(*lists)$/;"	f
zone	/home/miza/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb	/^    def zone$/;"	f	class:Time
zone	/home/miza/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/time_with_zone.rb	/^    def zone$/;"	f	class:ActiveSupport.TimeWithZone
zone=	/home/miza/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb	/^    def zone=(time_zone)$/;"	f	class:Time
zone_identifiers	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country.rb	/^    def zone_identifiers$/;"	f	class:TZInfo.Country
zone_identifiers	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country_info.rb	/^    def zone_identifiers$/;"	f	class:TZInfo.CountryInfo
zone_identifiers	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/ruby_country_info.rb	/^    def zone_identifiers$/;"	f	class:TZInfo.RubyCountryInfo
zone_identifiers	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_country_info.rb	/^    def zone_identifiers$/;"	f	class:TZInfo.ZoneinfoCountryInfo
zone_info	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country.rb	/^    def zone_info$/;"	f	class:TZInfo.Country
zones	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country.rb	/^    def zones$/;"	f	class:TZInfo.Country
zones	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country_info.rb	/^    def zones$/;"	f	class:TZInfo.CountryInfo
zones	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/ruby_country_info.rb	/^    def zones$/;"	f	class:TZInfo.RubyCountryInfo
zones	/home/miza/.rvm/gems/ruby-2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_country_info.rb	/^    def zones$/;"	f	class:TZInfo.ZoneinfoCountryInfo
zones_map	/home/miza/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb	/^      def zones_map #:nodoc:$/;"	f	class:ActiveSupport.TimeZone
|	/home/miza/.rvm/gems/ruby-2.2.0/gems/json-1.8.3/lib/json/generic_object.rb	/^    def |(other)$/;"	f	class:JSON
```

**Comment by mikezaby** [comment]
I tried also `grep -v '^!' tags` that works

**Comment by junegunn** [comment]
Hmm, which version of fzf do you have? `fzf --version`

**Comment by mikezaby** [comment]
I did a plug update now, and still has the same problem.
fzf version: '0.10.7'
Now if i run `:Tags` and after quit the vim, i saw this error
```
Unknown regexp modifier "/e" at -e line 1, at end of line
Unknown regexp modifier "/v" at -e line 1, at end of line
syntax error at -e line 1, near "/) "
syntax error at -e line 1, near ";}"
Execution of -e aborted due to compilation errors.
```

**Comment by junegunn** [comment]
Ah, I just realized that I see the same error when I run the bang-version, `:Tags!`. Works fine with tmux though. I'll see what I can do.

**Comment by junegunn** [comment]
I think it should be fixed now. Please update and try again.

**Comment by mikezaby** [comment]
Yes, it works now. Thanks

**Comment by micalexander** [comment]
This is also the case for me. :Tags command returns empty results. There is a tags file generated in the root already but I get nothing.

```
0/0
Tags>
```
I am currently running Neovim on Alpine Linux with Python3.

I do not have Perl so the following command is not available in the neovim version I have. I did not think I needed Pearl to run neovim.

perl -ne 'unless (/^!/) { s/^(.*?)\t(.*?)\t/\x1b[33m\1\x1b[m\t\x1b[34m\2\x1b[m\t/; print }' tags

When I run :Files I do get results but it is only when I have FZF_DEFAULT_COMMAND set. I was under the impression that it would give me results even if that Environment variable was not set.

**Comment by junegunn** [comment]
@micalexander

Neovim does not require perl, but Tags command of this plugin requires perl. You can install perl, or send me a pull request that removes perl dependency.

> When I run :Files I do get results but it is only when I have FZF_DEFAULT_COMMAND set. I was under the impression that it would give me results even if that Environment variable was not set.

It should. You might want to test `fzf` on your terminal first. Also check if the default command runs fine on it. https://github.com/junegunn/fzf/blob/master/src/constants.go#L55

**Comment by micalexander** [comment]
@junegunn same thing in the terminal. Running fzf without the FZF_DEFAULT_COMMAND variable set does nothing. Running 

```
find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-
```

Does nothing.

**Comment by junegunn** [comment]
It's a valid command. You'll have to figure out why it doesn't run on your system.

**Comment by micalexander** [comment]
So thanks for your help. The :Tags command was, of course, perl needing to be installed. The issue with the FZF_DEFAULT_COMMAND variable needing to be set explicitly for fzf to work (in the command line and the :Files command in vim), was that alpine linux's version of find is limited so I needed to install the gnu version of find in order for it to work.

```
apk add --update-cache findutils
```
I appreciate your work and look forward to using fzf more, with and without vim.

**Comment by junegunn** [comment]
Thanks, I'll see if I can make fzf print error messages in those cases.

**Comment by junegunn** [comment]
See:
- https://github.com/junegunn/fzf.vim/commit/55f6bc83677235a7f6ffc35496ecae2e2a764417
- https://github.com/junegunn/fzf/commit/07ef2b051ccdc6917b9b65d157df3ebc8f3ff0de

**Comment by micalexander** [comment]
@junegunn Boss! Would be nice to get it added to the readme. But thanks just the same.
