### ISSUE TITLE
Mapping down key to <C-j>?

### ISSUE THREAD

**Issue by rmolin88** [junegunn/fzf.vim#221]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Is there a way to map <c-j> to the down key to navigate through the all the
`fzf.vim` lists? The same way regular fzf cli does it?

Thanks for an awesome plugin

**Comment by junegunn** [comment]
It doesn't work?

**Comment by rmolin88** [comment]
Not under my current configuration. I tried the simplified vimrc
configuration.
My current setup is: rxvt Unicode terminal, with tmux with nvim. You can
see my dot files under my vimrc repo.

Thanks for a great plugin and for the support.

**Comment by rmolin88** [comment]
I have discovered that the problem is the following mapping: `tnoremap <C-j> <C-\><C-n>` in nvim. Is there a way to have a `au filetype` specific way to remap this or something so that it wouldnt conflict?.
