### ISSUE TITLE
Shortcut to include hidden files

### ISSUE THREAD

**Issue by mixedCase** [junegunn/fzf.vim#226]
- Category
  - [ ] Question
  - [ ] Bug
  - [X] Suggestion

All OSes; {Neo,}Vim

Right now we can modify `$FZF_DEFAULT_COMMAND` to include hidden files in every search. However, this is something that I see would be far more convenient (due to the unpredictable nature of how folder structures are specified) to be able to set per-search. Something like pressing `Ctrl+.` or `Ctrl+H`.

**Comment by junegunn** [comment]
You can define a custom command with a custom source command like so (in this case ag command including hidden files)

```vim
command! -bang -nargs=? -complete=dir HFiles
  \ call fzf#vim#files(<q-args>, {'source': 'ag --hidden --ignore .git -g ""'}, <bang>0)
```

Then you can set up a mapping that executes the commands. Makes sense?

**Comment by mixedCase** [comment]
Yes and no. Makes sense for a workaround, which is appreciated, but any chance to see this integrated with the normal FZF command as a shortcut? It really makes sense to be able to restart the search including hidden files, since one of the various points of fuzzy finding file search is to be able to access files whose location you don't exactly remember.

Plus it'd be consistent with file explorers like vim-filer and NERDTree. And at one point it was even ctrlp's default to search dotfiles, only to be hidden behind a variable because of ctrlp's speed; where with fzf even that makes sense.

**Comment by junegunn** [comment]
FZF and Files are designed to respect `$FZF_DEFAULT_COMMAND`, and I'm not going to change that. You'll be able to implement what you want using `--expect` option and custom sink function.

Reference: https://github.com/junegunn/fzf#fzfrun

**Comment by jackielii** [comment]
I tried a bit and found this works for me:

```vim
command! -bang -nargs=? -complete=dir HFiles
  \ call fzf#vim#files(<q-args>, {'source': 'find . \( -not -path "./.git/*" ' .
    \   '-and \( -path "./.*" -or -path "./.*/**" \) ' .
    \   '-and \( -type f -or -type l \) ' .
    \ '\) -print | sed "s:^..::"'}, <bang>0)

map <leader>zh :HFiles<CR>
```

Explanation on the find bit:

1. don't include .git directory
2. include hidden files in this dir: './.*'
3. include normal files in the hidden directories
