### ISSUE TITLE
:Ag produces "illegal option: --ansi"

### ISSUE THREAD

**Issue by rr-** [junegunn/fzf.vim#227]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows (Cygwin)
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I tested with `vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)`.

`:FZF` works fine.
`:Ag` shows brief prompt that `--ansi` is an invalid option and immediately goes back to vim.

**Comment by junegunn** [comment]
The latest version of fzf which is written in Go does not run on Cygwin, and this project requires the latest version. We're currently working on Windows binary (see: https://github.com/junegunn/fzf/issues/147, https://github.com/junegunn/fzf/pull/714), so you can wait for it, or you can switch to Windows Subsystem for Linux where the linux binary works.

**Comment by rr-** [comment]
Alright, thanks
