### ISSUE TITLE
Define custom ALT-A for Ag

### ISSUE THREAD

**Issue by voxsim** [junegunn/fzf.vim#228]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

Is it possible to defin custom ALT-A and ALT-D command for Ag?

Right now I am using ALT-A and CTRL-A for other purposes..

Thanks,
Simon

**Comment by junegunn** [comment]
```vim
" query, ag options, fzf#run options, fullscreen
autocmd VimEnter *
\ command! -bang -nargs=* Ag
\ call fzf#vim#ag(<q-args>, '', { 'options': '--bind ctrl-a:select-all,ctrl-d:deselect-all' }, <bang>0)
```

**Comment by patricknraanes** [comment]
In case anybody's wondering how to get the ctrl bindings to work with `:Rg`  as well. I adapted the above snippet from @junegunn as follows:

```
autocmd VimEnter *
\ command! -bang -nargs=* Rg
\ call fzf#vim#grep(
\   'rg --column --line-number --no-heading --color=always --smart-case -- '.shellescape(<q-args>), 1,
\   {'options': fzf#vim#with_preview()["options"] + ['--bind', 'ctrl-a:select-all,ctrl-d:deselect-all']}, <bang>0)
```

**Comment by junegunn** [comment]
`autocmd VimEnter *` is no longer needed with the current version of fzf.vim.
