### ISSUE TITLE
Append command to history

### ISSUE THREAD

**Issue by teto** [junegunn/fzf.vim#231]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Would it be possible to have commands executed remebered by vim ? for isntance if I change my colorscheme with :Colors, fzf must run at some point ":colorscheme <colorscheme>" but this doesn't appear in vim's history.
I've checked with the minimal configuration.

**Comment by junegunn** [comment]
Excerpt from `:help cmdline-history`:

```
- Only commands that are typed are remembered.  Ones that completely come from
  mappings are not put in the history.
```

`:colorscheme` is invoked inside `:Colors` so Vim does not add it to command history. We can manually add it using `histadd()` function, but I don't think I want to do that; some users may not like it, and if we decide to do so, to what extent should we apply the strategy? Which commands?

I believe you can do it yourself using a wrapper command for `:Colors` or using `autocmd ColorScheme`.

**Comment by teto** [comment]
I see no pb then. Thanks for the detailed explanation.

2016-10-30 4:16 GMT+01:00 Junegunn Choi <notifications@github.com>:
