### ISSUE TITLE
GFiles? turn off preview window?

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#232]
- Category
    - [x] Question
    - [ ] Bug
    - [] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

How can I turn off a preview window, which appears in the right side of the fzf-window, when I use `GFiles?`?

**Comment by junegunn** [comment]
You can use the underlying autoload function directly.

```vim
call fzf#vim#gitfiles('?', {'options': '--no-preview'})
```

Overriding the command:

```vim
autocmd VimEnter * command! -bang -nargs=? GFiles call fzf#vim#gitfiles(<q-args>, {'options': '--no-preview'}, <bang>0)
```

By the way, can you explain why you don't want preview window?

**Comment by yevhen-m** [comment]
Thanks. 

Just want to try using `GFiles?` without this preview window.

**Comment by uri** [comment]
@junegunn I wanted to remove the preview window, as when have my editor set to be around 80 columns, the preview window ends up truncating the end of the filename, making it more difficult to use.

![image](https://user-images.githubusercontent.com/676443/52728638-a6f8f480-2f85-11e9-90dc-d002856a045e.png)

My ideal solution would be to truncate the file names from the left and keep the preview window, but removing it solves my immediate problem.

**Comment by uri** [comment]
By the way, why did you setup the command in an autocmd? Why not just put the command definition inside a config file?

**Comment by junegunn** [comment]
We no longer need autocmd since https://github.com/junegunn/fzf.vim/commit/1bf68a978bfc22fd1685e736fb852e78003fc468

**Comment by nkh** [comment]
![Screenshot_20200328_101642](https://user-images.githubusercontent.com/45409/77819839-3c9a0980-70de-11ea-83b2-09df2dbc931b.png)

Hi,

I have the same problem with file names being elided but I want to have the preview and see  what the file name is, either by removing the preview or line that shows the full name on top

**Comment by betoharres** [comment]
for the owner wondering why disable preview: it's for people that use the 80 column pattern, and then you have more screen real state to work with.

i like preview only for a small set of files on my project, usually files with small text like a file with the variable colors, font sizes, etc... it's a great feature though! But since this problem affects me more times than consulting these files, I'll end up disabling it.

**Comment by ranelpadon** [comment]
On my case, I just use a preview toggler, like the `Ctrl-/` or `Ctrl-_`:
```vim
" Couldn't use the prescribed 'ctrl-/' in Mac,
" so use 'ctrl-_' instead (which is triggered by 'ctrl--' also).
" https://apple.stackexchange.com/questions/24261/how-do-i-send-c-that-is-control-slash-to-the-terminal#24282
let g:fzf_preview_window = ['right:50%', 'ctrl-_']
```

Reference:
https://github.com/junegunn/fzf.vim#preview-window
