### ISSUE TITLE
How do I have a mapping that tries :GFiles, and falls back to :Files if that fails?

### ISSUE THREAD

**Issue by ManiacalAce** [junegunn/fzf.vim#233]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Pardon my lack of vimscript knowledge. I've been fiddling around for an hour or so, but decided it would be easier for me to ask people more familiar with scripting vim.

I currently have fzf mapped to `c-p`, which calls `:GFiles`.
I want my `c-p` behaviour to be such that it shows stuff from the repo root, if i'm somewhere in a git repo. Else it should fall back to `:Files`

I thought I would do a check for `git rev-parse --is-inside-work-tree`, to see if I'm currently in a repo, which would also involve catching some errors that this particular command throws when outside a git repo.

I also wondered if it's simpler (faster?) to somehow just try :GFiles, and notice that it failed, then try :Files. (ie. EAFP principle). I guess it would involve some try-catch mechanism.

Help would be appreciated :)

**Comment by junegunn** [comment]
> just try :GFiles, and notice that it failed, then try :Files.

`:GF` currently does not throw exceptions, so it would be tricky, though not impossible.

> I would do a check for git rev-parse --is-inside-work-tree

Yeah, that would work.

```vim
execute system('git rev-parse --is-inside-work-tree') =~ 'true' ? 'GFiles' : 'Files'
```

You can achieve the same behavior you want from a different layer, i.e. setting `$FZF_DEFAULT_OPTS` and just using `:Files` command.

https://github.com/junegunn/fzf#git-ls-tree-for-fast-traversal
