### ISSUE TITLE
question about adding a custom function

### ISSUE THREAD

**Issue by Alok** [junegunn/fzf.vim#235]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I realized that `fzf` can be used to replace all the [Notational
Velocity](http://notational.net/) (NV) plugins/apps out there.

The basic idea is that NV searches for a string and automatically
creates a file with the search string as the title if no matches are
found. This saves the mental headache of managing filenames when making
notes.

My idea is

- Use the `Ag:` command to search for the string since it searches both the
  filename and its contents, so you can find relevant notes quickly (with exact matching)
- If no matches are found **or** if some hotkey is pressed (`<c-x>` for
  example), create a file in the directory specified by an environment variable
  (I use `$WRITING`) with the `.md` extension.

I don't know Vimscript well, so I'm wondering how to hook into the `Ag:`
function to do this.

**Comment by junegunn** [comment]
Nice idea. I personally use [a shell script](https://gist.github.com/junegunn/402e3d19271bc68de59ce34eb7dc6ae5) that does similar stuff, but I can imagine doing the whole thing inside Vim. It may be easier to write a separate command (or even a plugin) based on `fzf#run()` instead of trying to extend the Ag command provided here. Let me think about that.

Note that the script I mentioned above sorts the files by their modification times like NV while Ag command doesn't.

**Comment by Alok** [comment]
I noticed that you added a preview function, which would make this even more viable as a new plugin based on fzf.vim.

**Comment by Alok** [comment]
So I've figured most of this out, but I have one question:

How would  I add the text the user types as a source? This way, if no search results are found, the user could hit something like `c-x` and open a file with the name they typed.

**Comment by junegunn** [comment]
`--expect` and `--print-query` are the options you need. See `man fzf` for the details. Or take a look at the script I linked above to see how they're used.

**Comment by Alok** [comment]
I got a preliminary version working, though I still have to figure out how to use `:Ag` to search the contents of the files as well as the names, add support for opening multiple files, and add coderay preview.

```vim
function! s:escape(path)
  return escape(a:path, ' $%#''"\')
endfunction

let s:wiki = expand('~/wiki/wikidata')
let s:writing_dir = expand('~/Dropbox/Writing')

function! s:note_handler(lines) abort

  " expect at least 2 elements, query and keypress, which may be empty strings
  let query = a:lines[0]
  let keypress = a:lines[1]
" Don't forget to add spaces for the commands
  let cmd = get({
              \  'ctrl-s': 'split ',
              \  'alt-s': 'split ',
               \ 'ctrl-v': 'vertical split ',
               \ 'alt-v': 'vertical split ',
               \ 'alt-x': 'vertical split ',
               \ 'alt-z': 'vertical split ',
               \ 'ctrl-t': 'tabedit ',
               \ 'alt-t': 'tabedit ',
               \ },
               \ l:keypress, 'edit ')

  if len(a:lines) == 3 | let filename = a:lines[2] | endif

  if l:keypress ==? 'ctrl-x' || l:keypress ==? 'alt-x'
    let candidate = s:escape(s:wiki  . '/' . l:query . '.md')
  elseif l:keypress ==? 'ctrl-z' || l:keypress ==? 'alt-z'
    let candidate = s:escape(s:writing_dir  . '/' . l:query . '.md')
  else
    let candidate = s:escape(l:filename)
  endif

  execute l:cmd . candidate
endfunction

command! -bang NV
      \ call fzf#run(
          \ fzf#wrap({
              \ 'sink*': function('<sid>note_handler'),
              \ 'source': 'find ' . s:wiki . ' ' . s:writing_dir . " -type f -name '*.md' ",
              \ 'dir': s:wiki,
              \ 'options': '--print-query --ansi --tiebreak=length,begin,index --expect=ctrl-x,ctrl-z,ctrl-s,ctrl-v,ctrl-t,alt-s,alt-v,alt-t,alt-x,alt-z',
              \ }
      \ ))
```

**Comment by junegunn** [comment]
Yeah, in my script, I don't use ag but just print out every line in the files and solely use fzf to find the matching line.

**Comment by Alok** [comment]
Got it working.

**Comment by junegunn** [comment]
Cool, good job.

**Comment by Hipomenes** [comment]
@alok, can u share your solution/script?

**Comment by alok** [comment]
https://github.com/alok/notational-fzf-vim
