### ISSUE TITLE
FZF commands in vim change my cursor to `^[[O`

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#236]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hey, I switched to vim from neovim recently and I use your fantastic fzf-vim as always.
So, when I use it in tmux, my vim cursor changes to `^[[O`. I've searched a bit, but no luck. Could you tell me what's the problem and how I can fix it?

**Comment by junegunn** [comment]
I can't reproduce on my machine, but maybe it's related to https://github.com/junegunn/fzf/issues/391#issuecomment-257090266 ?
I fixed the problem but I haven't released a new binary with the fix. I'm planning to release it when https://github.com/junegunn/fzf/pull/714 is ready. Until then you can try building the binary from the source.

**Comment by yevhen-m** [comment]
What TERM value do you have in a terminal, which is in tmux?

**Comment by junegunn** [comment]
screen-256color

**Comment by yevhen-m** [comment]
I have it too. The problem only appears in tmux. I thought it was connected
somehow.

**Comment by junegunn** [comment]
Please update fzf to 0.15.7 and try again.
