### ISSUE TITLE
Limit :Files depth ?

### ISSUE THREAD

**Issue by ctjhoa** [junegunn/fzf.vim#237]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi is there a way to limit the depth of `:Files` command?
Basically I want don't want to get subdirectories results.

**Comment by junegunn** [comment]
`:Files` command uses `$FZF_DEFAULT_COMMAND` if set. You can set it to a command that traverses the directory with depth limit. e.g. find with -depth option.

See https://github.com/junegunn/fzf#environment-variables
