### ISSUE TITLE
Is it possible to edit the results?

### ISSUE THREAD

**Issue by for-coursera** [junegunn/fzf.vim#238]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Let's say we've launched `:History`, searched for `bar` but haven't found `/home/user/project/foo/bar.md` among the results. However, there is `/home/user/project/foo/bar.txt` there. Now, two scenarios would be of interest: either being able to simply edit the selected path, or to open the directory in question `/home/user/project/foo/`.

Is it possible? Or, may be I'm missing something, and this is already implemented?

**Comment by junegunn** [comment]
No, it's not implemented. I'm not sure how I would do that considering that the command allows selecting multiple entries (tab / shift-tab).

**Comment by for-coursera** [comment]
Well... It's just wouldn't work for multiple selections, and that's it :).

**Comment by aleksandersumowski** [comment]
Edit the result functionality would also be useful for History:

**Comment by svenstaro** [comment]
Pretty old issue but I'd just like to show what this same functionality looks like in [ctrlsf](https://github.com/dyng/ctrlsf.vim) and [vim-ags](https://github.com/gabesoft/vim-ags).

**Comment by junegunn** [comment]
> Edit the result functionality would also be useful for History:

```
   :: Press CTRL-E to edit
```
