### ISSUE TITLE
FzfGitFiles suddenly stopped working

### ISSUE THREAD

**Issue by cvlmtg** [junegunn/fzf.vim#241]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I have this mapping in my vimrc:

```
nnoremap <leader>f :<C-u>FzfGitFiles<CR>
```

this morning I updated fzf and fzf.vim and this is what happens now:

```
Error detected while processing function fzf#vim#gitfiles[1]..<SNR>111_get_git_root:
line    2:
E117: Unknown function: fugitive#repo
E15: Invalid expression: fugitive#repo().tree()
Press ENTER or type command to continue
```

I've never had fugitive and FzfGitFiles always worked perfectly. Can this change be reverted please?

**Comment by junegunn** [comment]
Sorry about that. The bug was introduced in #239. It should be fixed now.

**Comment by cvlmtg** [comment]
thanks!
