### ISSUE TITLE
how to delete multiple buffers?

### ISSUE THREAD

**Issue by githubfun** [junegunn/fzf.vim#242]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

is it possible to delete multiple buffers from all open buffers with fzf.vim?  if not how do people do it efficiently?

**Comment by junegunn** [comment]
You can implement the functionality using `fzf#run` function, but there's no ready-made solution for the use case. In my case, I don't delete open buffers, I just leave them open.

**Comment by githubfun** [comment]
> In my case, I don't delete open buffers, I just leave them open.

**Comment by junegunn** [comment]
I just open multiple Vim processes on tmux windows for different projects, so I don't have the problem, but I see your point. The current Buffers command is for jumping to a position in an open buffer so it does not allow you to select multiple buffers at once so it's not a natural fit for the purpose. Try something like the follows:

```vim
function! s:list_buffers()
  redir => buffers
  silent ls
  redir END
  return split(buffers, "\n")
endfunction

function! s:delete_buffers(lines)
  for bufno in map(a:lines, {_, line -> matchstr(line, '[0-9]\+')})
    echom 'Delete buffer '.bufno
    silent! execute 'bd' bufno
  endfor
endfunction

command! -bang DeleteBuffers
  \ call fzf#run(fzf#wrap({'source':  s:list_buffers(),
  \                        'options': '--multi --bind alt-a:select-all',
  \                        'sink*':   {lines -> s:delete_buffers(lines)}}, <bang>0))
```
