### ISSUE TITLE
Question: can :Ag be configured to take a directory argument?

### ISSUE THREAD

**Issue by Alok** [junegunn/fzf.vim#243]
Pretty much the title. I want to open Ag in a specific (set of) directory(ies) (my notes/wiki) and then search as normal. How would I configure it to take one or more directories as sources for files?

**Comment by junegunn** [comment]
Have you tried using `fzf#vim#ag` function?

**Comment by thedanotto** [comment]
@junegunn how would I utilize that function from vim normal mode? (Thanks for all your plugins, they have saved me hours of time)

**Comment by junegunn** [comment]
You would define a mapping or a command that calls the function. Check out the examples in https://github.com/junegunn/fzf.vim#advanced-customization
Note that `fzf#vim#grep` is a generalized version of `fzf#vim#ag` and `fzf#vim#ag` call internally call the function.
