### ISSUE TITLE
Change filtering column in Tags command

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf.vim#244]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I'm using `:Tags` a lot to navigate my source code. My `tags` file contains many fields, e.g.:

```
Storage.load_budget_objects     server/storage.py        /^    def load_budget_objects(self, budget_object_keys):$/;"    m       class:Storage   access:public   s
Storage.load_global_state       server/storage.py        /^    def load_global_state(self, control_server):$/;"  m       class:Storage   access:public   signature
Storage.old_storage_path        server/storage.py        /^    def old_storage_path(self):$/;"   m       class:Storage   access:public   signature:(self)
```
It appears they all are used in filtering. This is not always convenient as way too many hardly related results are reported (especially with fuzzy search). Sometimes it's more convenient to filter by only one column, the first one. For now I've simply hacked `fzf#vim#tags` as follows:
``` vim
\ 'options': copt.'-n1 -m --tiebreak=begin --prompt "Tags> "'.s:q(a:query)}, a:000)
```
I've added `-n1` option.

Could you please think of a way to make it configurable somehow? Maybe there could be a key to change filtering column dynamically, on the go?

**Comment by junegunn** [comment]
You can pass extra `fzf#run` options as the second to last argument. Here I use `autocmd VimEnter` to override the default command which is loaded after .vimrc is processed.

```vim
autocmd VimEnter *
\ command! -bang -nargs=* Tags call fzf#vim#tags(<q-args>, {'options': '-n1'}, <bang>0)
```

**Comment by balta2ar** [comment]
Thank you! Could you please add this case to the README? I think other users may find it useful.
In the meanwhile, I'm closing this issue.
