### ISSUE TITLE
BLines vs regex?

### ISSUE THREAD

**Issue by 097115** [junegunn/fzf.vim#245]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion

It's not possible to use regex with BLines, I presume? And probably, no plans to add such feature, either? :)

**Comment by junegunn** [comment]
Nope. fzf does not support regex as I strongly believe that it's overkill. You might want to check out the following page for search syntax of fzf.

https://github.com/junegunn/fzf#search-syntax

And if you want to use regex on BLines, you should just use `/`-search.
