### ISSUE TITLE
Re-use existing window when using :Buffers command ?

### ISSUE THREAD

**Issue by jon301** [junegunn/fzf.vim#246]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

Hi June,

When using the `:Buffers` command, I was wondering if it is possible to switch to the window where the selected buffer has been opened (if it's still opened), instead of opening the selected buffer in the current window.

That way we can prevent having the same buffer opened multiple times across multiple tabs

Thanks for your help !

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim#command-local-options

**Comment by jon301** [comment]
That was exactly what I was looking for :)
Is it possible to filter only opened buffer by any chance ?

Thanks June !

**Comment by junegunn** [comment]
`:Windows`

**Comment by jon301** [comment]
Hi June,

Sorry to bother you again, I should have been more specific about my needs from the start.
:Windows is almost what I am looking for but it also shows all opened NERDTree windows, Startify etc.
That's why I looked at :Buffers (which don't show NERDTree & Startify windows 👍 ), but it shows all previously closed buffers which I don't want.

What I need is some kind of mix between :Windows and :Buffers :D
If it's not possible, don't worry it's ok.

Thank you again and have a nice day.

**Comment by junegunn** [comment]
Looks like you have an incomplete understanding of how Vim buffers work. I suggest that you thoroughly read `:help buffers`, especially `:help buffer-hidden` section.
