### ISSUE TITLE
Hide unnamed buffers in :Buffers

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#249]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

Hi,

I was wondering if it's possible to add functionality that optionally hides unnamed buffers when using the `:Buffers` command. Currently the buffers show quickfix windows and unnamed files, which I'm not interested in.

**Comment by junegunn** [comment]
I just updated Buffers command to ignore quickfix/location lists. But there's no option to further customize the list. What do you have in mind? Note that I personally do want unnamed buffers to be listed.

**Comment by danihodovic** [comment]
If quickfix/location lists are ignored that's good enough for me :+1: 

Thanks @junegunn !
