### ISSUE TITLE
":Commands" lists vim commands with extra charaters

### ISSUE THREAD

**Issue by walkingsparrow** [junegunn/fzf.vim#25]
I run ":Commands" and get something like

```
â~@~GBCommitsâ~@~G   
```
for all the commands. It seems these are space characters. I am using "urxvt" terminal on Ubuntu. On my mac, it is ok and no such strange characters. I think maybe this is not an issue of fzf.vim, but some of my setting problem of urxvt. But I am not sure.

**Comment by junegunn** [comment]
It's probably due to the difference in the way [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) are displayed in the terminal.

How does the output of the following command look?

```
ruby -e "puts 'NBS: (' + [0x2007].pack('U') + ')'"
```

**Comment by walkingsparrow** [comment]
The output is `NBS: ( )`

**Comment by junegunn** [comment]
Hmm, looks fine. How about these? Do you see bold/yellow text?

```sh
echo -e '\x1b[33;1mHello\x1b[m'

echo -e '\x1b[33;1mHello\x1b[m' | fzf --ansi
```

**Comment by walkingsparrow** [comment]
Yes, the two results are perfectly fine.

**Comment by walkingsparrow** [comment]
All other fzf.vim commands seem OK except this ':Commands"

**Comment by walkingsparrow** [comment]
Actually what I see is
```
> !  @~GAg@~G         *                                      call fzf#vim#ag(<q-args>, s:w(<bang>0))
```
where ">" is purple and "Ag" is bold and yellow. So the color styles are correct.

**Comment by junegunn** [comment]
Oh, I think I know what's going on.
I recently updated the linux binary to correctly support unicode character.
 https://github.com/junegunn/fzf/issues/376
Delete the current binary (`bin/fzf-0.10.8-linux_amd64`) and rerun the install script to download it again.

**Comment by walkingsparrow** [comment]
Thank you so much. This fixes the problem.

**Comment by junegunn** [comment]
Cool, thanks.
