### ISSUE TITLE
Fzf window should auto close when leaving the buffer

### ISSUE THREAD

**Issue by flybayer** [junegunn/fzf.vim#250]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

For whatever reason, I often open the fzf buffer and then switch to another buffer without doing anything with the fzf buffer. When I do that, the fzf buffer stays open. If I switch back to it, it's in normal mode, so I have to go to insert mode then hit ESC.

My current workaround is:
```vim
autocmd BufLeave *#FZF :bd!
```

**Comment by junegunn** [comment]
> switch to another buffer without doing anything with the fzf buffer

Hmm, why don't you just `CTRL-C`? You can *choose* to close fzf or to move to another Window without closing it, so I don't see a problem with it.

**Comment by gmonein** [comment]
Hello,

If I use windows popup mode with fzf, and I C-wj for exemple, the fzf popup stay openned and I can no longer go into it, so I just broke my tab
