### ISSUE TITLE
Jumping to a directory

### ISSUE THREAD

**Issue by nomasprime** [junegunn/fzf.vim#251]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi @junegunn, been working on my NeoVim setup, using a few of your plugins—they're great. You've inspired me to start writing my own VimL.

My question is when you're editing and you want to jump to a directory how would you do that? For example, if you're working on a Rails project and you want to create a new controller.

Hope you don't mind me asking such a general question.

**Comment by junegunn** [comment]
Well, I don't really change directories often in Vim. I use `:Files` and `:Files DIRECTORY_NAME` to open files in different paths, sometimes I use NERDtree to browse the directory hierarchy and create/move files and directories. Or, `:!ranger`. I don't do Rails stuff these days, but doesn't it provide generators for creating modules?

**Comment by habitullence** [comment]
That's pretty much how I do things, apart from I use justinmk/vim-dirvish for browsing directories.

tpope/vim-rails does provide generators, I didn't give the best example: what I'd like is a fuzzy way, i.e., fzf, narrow down on directories rather than files and then open the selected one in dirvish.

I'll start reading through the docs to try and figure it out. If you have any pointers, would be very much appreciated to help get me going.

Will share work when I'm done.

**Comment by wayneashleyberry** [comment]
I'd also like to know if there's a way to do this! I have a [zsh function](https://github.com/wayneashleyberry/dotfiles/blob/cb57cd4a595121235630b408c7e68c655bd1c15e/.zshrc#L38-L43) I use to change directories with FZF and having the same thing in vim would be great :)

**Comment by junegunn** [comment]
You can easily come up with something like this:

```vim
command! -nargs=* -complete=dir Cd call fzf#run(fzf#wrap(
  \ {'source': 'find '.(empty(<f-args>) ? '.' : <f-args>).' -type d',
  \  'sink': 'cd'}))
```
Refer to https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun to learn more about the functions.

**Comment by danielcnorris** [comment]
@junegunn On a related note, I'm trying to create an FZF function to search for a (single) directory, then paste `:e /selected/directory/path/` on Vim's command line with the selected directory. This will allow me to quickly create a new file in a selected directory. I'm stuck on how to paste FZF's output to the command-line. Is this easy to do? 

Thanks!

**Comment by junegunn** [comment]
@danielcnorris You'll have to use `feedkeys()` function. For example,

```vim
function! s:append_dir_with_fzf(line)
  call fzf#run(fzf#wrap({
    \ 'options': ['--prompt', a:line.'> '],
    \ 'source': 'find . -type d',
    \ 'sink': {line -> feedkeys("\<esc>:".a:line.line, 'n')}}))
  return ''
endfunction

cnoremap <expr> <c-x><c-d> <sid>append_dir_with_fzf(getcmdline())
```

**Comment by danielcnorris** [comment]
You're the man! Thanks.

**Comment by GAKINDUSTRIES** [comment]
@

> @danielcnorris You'll have to use `feedkeys()` function. For example,
> 
> ```viml
> function! s:append_dir_with_fzf(line)
>   call fzf#run(fzf#wrap({
>     \ 'options': ['--prompt', a:line.'> '],
>     \ 'source': 'find . -type d',
>     \ 'sink': {line -> feedkeys("\<esc>:".a:line.line, 'n')}}))
>   return ''
> endfunction
> 
> cnoremap <expr> <c-x><c-d> <sid>append_dir_with_fzf(getcmdline())
> ```

@junegunn Sorry for being late here, but can you help me with this function that you suggested. I'm getting an error which I don't know how to fix:

<img width="1440" alt="Screen Shot 2019-12-28 at 19 13 19" src="https://user-images.githubusercontent.com/4645880/71550033-2331d600-29a6-11ea-8f96-4faf84f02ba3.png">

**Comment by ywpkwon** [comment]
> ```viml
> command! -nargs=* -complete=dir Cd call fzf#run(fzf#wrap(
>   \ {'source': 'find '.(empty(<f-args>) ? '.' : <f-args>).' -type d',
>   \  'sink': 'cd'}))
> ```
Thanks! This snippet was very useful.  But There is one issue.
When I do `:Cd` (without any argument) It should trigger `empty(<f-args>)`, but the error message is `E119: Not enough arguments for function: empty`.

I tried to read `:h f-args`, and it says "If no arguments are given <f-args> is remove." I'm not sure if the `empty` function can be used for removed ones. @junegunn, could you please advise on this?

**Comment by RanjitV17** [comment]
@ywpkwon :
I got it working with:
` command! -nargs=* -complete=dir Cd call fzf#run(fzf#wrap(
    \ {'source': 'find .\/'.<f-args>.' -type d',                                                                                                                                            
   \  'sink': 'cd'}))`

**Comment by RanjitV17** [comment]
@ywpkwon  : 
I modified it and got "cd -" functionality also to work. I am new to vim script, I would like to see someone re-write this in a better way.

`let s:cwd = getcwd()     
let s:fwd = getcwd()     
    
function! UpdateCWD()     
    let s:cwd = getcwd()     
endfunction     
    
function! UpdateFWD()     
    let s:fwd = getcwd()     
endfunction     
    
function Dir_with_fzf(line)     
    if a:line == "./-"     
        call fzf#run(fzf#wrap(     
          \ {'source': 'find '.s:cwd.' -type d',    
          \  'sink': 'cd'}))     
    
        let s:cwd = s:fwd     
        call UpdateFWD()     
    else     
        call UpdateCWD()     
    
        call fzf#run(fzf#wrap(     
          \ {'source': 'find .\/'.a:line.' -type d',    
          \  'sink': 'cd'}))     
    
    
        call UpdateFWD()     
    endif     
    
endfunction     
    
    
command! -nargs=* -complete=dir Cd call Dir_with_fzf(<f-args>)    
nnoremap C :Cd ./  `

**Comment by utrumo** [comment]
```
call plug#begin('~/.vim/plugged')
  Plug 'airblade/vim-rooter'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
call plug#end()

let g:rooter_patterns = ['.git']
let g:rooter_manual_only = 1

function! s:processLine(line)
  execute 'cd' a:line
  " execute ':Files'
endfunction

function! s:change_dir(dir)
  "let source = 'find -type d -not \( -name .git -prune -o -name node_modules -prune \)'
  let source = 'find -type d -not \( -name .git -prune \)'
  call fzf#run({
    \ 'dir': a:dir,
    \ 'source': source,
    \ 'sink': {line -> s:processLine(line)}
    \ })
endfunction

nnoremap<silent><Leader>d :call <SID>change_dir('.')<CR>
nnoremap<silent><Leader>D :call <SID>change_dir(FindRootDirectory())<CR>
```

**Comment by patricknraanes** [comment]
@ywpkwon I got it working with the following

    command! -bang -bar -nargs=? -complete=dir Cd
        \ call fzf#run(fzf#wrap(
        \ {'source': 'find '.( empty("<args>") ? ( <bang>0 ? "~" : "." ) : "<args>" ) .' -type d',
        \ 'sink': 'cd'}))

An included improvement is that you can use the `!` (bang) to root the search in home dir instead of the pwd.
