### ISSUE TITLE
Augmenting Ag command using fzf#vim#with_preview function partially works in neovim

### ISSUE THREAD

**Issue by deathmaz** [junegunn/fzf.vim#256]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi @junegunn, i tried this example from readme:
```viml
autocmd VimEnter * command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```
And it works great with `:Ag!` but didn't work with `:Ag`
To make it work i changed this line:
```viml
: fzf#vim#with_preview('right:50%:hidden', '?'),
```
to this:
```viml
: fzf#vim#with_preview('right:50%:hidden', '\?'),
```
Many thanks for your work!

**Comment by junegunn** [comment]
Fixed, thanks.
