### ISSUE TITLE
Feature request: ag for the current/all open buffers

### ISSUE THREAD

**Issue by infokiller** [junegunn/fzf.vim#257]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

**Comment by junegunn** [comment]
`:Lines` comes to my mind.

**Comment by infokiller** [comment]
Yes, there's definitely overlap with `:Lines`, but this is slightly different, because it enables first hard filtering using ag's search syntax, then interactively matching using fzf.

I guess this is not a big enough differentiator to merit this, so I'm closing.

Thanks for looking into it, and for your great projects!

**Comment by junegunn** [comment]
I see. I believe you'll be able to implement the feature using `fzf#vim#grep` function. Check out the examples in https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by infokiller** [comment]
Thanks for the pointer, I'll look into it.
