### ISSUE TITLE
Can't create file in /tmp

### ISSUE THREAD

**Issue by mdsn** [junegunn/fzf.vim#260]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

Coming back to a vim instance opened several days ago, when trying to load the buffers list I get the following error:

```
Error detected while processing function fzf#vim#buffers[2]..<SNR>61_fzf[18]..fzf#run:
line   30:
E482: Can't create file /tmp/vN7GEnh/358
Press ENTER or type command to continue
```

Likely because I haven't come back to this vim instance in a few weeks and now said directory under `/tmp` doesn't exist anymore. No other way to reproduce it that I'm aware of.

**Comment by junegunn** [comment]
Thanks for the heads up. I'll close this as I don't think there's something we can do about it.
