### ISSUE TITLE
--with-preview does not expand ~ path

### ISSUE THREAD

**Issue by davidosomething** [junegunn/fzf.vim#261]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion

Using a source with mixed relative and absolute paths:

```
[
  'README.md',
 ' vendor/nvim/deoplete.nvim/doc/deoplete.txt',
  '~/.dotfiles/README.md',
]
```

the preview does not `expand()` the tilde path so says file not found

**Comment by junegunn** [comment]
Yeah, I can reproduce:

```vim
command! XXX call fzf#run(extend({'source': ['~/.bashrc:50']}, fzf#vim#with_preview()))
```

Let me look into it.

**Comment by junegunn** [comment]
Fixed it, thanks.
