### ISSUE TITLE
Suggestion: Releases with vendored tarballs?

### ISSUE THREAD

**Issue by vext01** [junegunn/fzf.vim#262]
Hi,

I like fzf, but I would prefer if I could install it from my operating system package manager. Would you consider making formal release and bundling up some vendor tarballs so that I can build an OpenBSD port?

The go tool to do the vendoring is called 'govendor'. I tried to make my own vendor tarball but failed, I think because the directory structure would need some changes, but I'm not sure. I don't know the first thing about go ;)

Thanks

**Comment by junegunn** [comment]
Official release tags can be found in https://github.com/junegunn/fzf/releases. Though the versions of the dependent libraries are not explicitly stated in the source code at the moment. I simply forked all the dependent go libraries and use those forks as a means to keep things unchanged currently, but there are obviously better tools for that, so I'll probably switch in the future.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/glide.yaml
