### ISSUE TITLE
Use existing tags file instead of generating one

### ISSUE THREAD

**Issue by fedragon** [junegunn/fzf.vim#263]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hello,
is there any way to configure this plugin to use an existing `tags` file, instead of creating one?
I'm asking because I use another plugin (`sbt-ctags`) to grab all my project's dependencies and create a `tags` file, so I am trying to use `fzf.vim` only to navigate tags...

Thank you for this awesome plugin!

**Comment by junegunn** [comment]
Tags command asks you if it should create a tags file only when it's not found.

https://github.com/junegunn/fzf.vim/blob/42086bee57aee308e23be48c23342c96887d52a2/autoload/fzf/vim.vim#L747

Check out `:help 'tags'` if `tagfiles()` returns an empty array.

**Comment by fedragon** [comment]
oh... thanks!

**Comment by jmgarnier** [comment]
Sorry, I don't understand your reply.

When I run `:Tags`, it starts building `ctags` using `ctags -R` ...

I am a ruby developer and I use a combination of https://github.com/ludovicchabant/vim-gutentags and a  small ruby script to generate ctags:

```vimscript
set tags+=gems.tags
```

```ruby
$ cat /usr/local/bin/ctags_gems                                                   2.4.2
#!/usr/bin/env ruby
require 'bundler'
paths = Bundler.load.specs.map(&:full_gem_path)
```

My goal is to use `fzf` to search into my existing `ctags` when I press `<C-]>`. I had this working out of the box with https://github.com/ivalkeen/vim-ctrlp-tjump 

Could you help with some pointers? I can also open a new issue and delete that comment if you prefer.

---

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

**Comment by jmgarnier** [comment]
To reply to my own question. `fzf.vim` works out of the box with existing ctags. What happened is that I had a lof of trashes in my tags. After I did some clean up, everything works as expected :)
