### ISSUE TITLE
Change FZF director

### ISSUE THREAD

**Issue by oscarmorrison** [junegunn/fzf.vim#267]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

It would be super useful to have FZF to search everything from the project root directory (where the .gitigore file resides) or if one in the FZF window if there was a shortcut to move up a directory.

Thanks

**Comment by junegunn** [comment]
See
- https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795
- #123
