### ISSUE TITLE
Tags or BTags creates an empty buffer

### ISSUE THREAD

**Issue by 0ax1** [junegunn/fzf.vim#269]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Steps to reproduce:
- set autochdir is enabled
- open a file with nvim
- open another file with GFiles 'vsplit'
- then try to jump to a tag with Tags or BTags with 'split' or 'vsplit'

- instead of jumping to the tagged position, a new empty buffer gets opened in the split

**Comment by junegunn** [comment]
I believe the problem should be fixed now. Make sure to update the main fzf repo as well.

**Comment by 0ax1** [comment]
Thanks you for fixing this. fzf and its vim plugin are amazing!
