### ISSUE TITLE
Is there a way to pass a path to :Ag?

### ISSUE THREAD

**Issue by craigp** [junegunn/fzf.vim#27]
This is about the only thing I miss from ag.vim, I used it often to search only sub-paths in my project. I looked at the fzf plugin source, doesn't look like it's there at the moment, would it be very difficult to add this?

One thing I like about this version is that I no longer have to include flags (like `:Ag -Q "blah" web/server`) but as I see it that might make it difficult to pass it a path. Problem is that the search/reduce once the :Ag pane is open doesn't also search against the filename/path 

EDIT: just an edit to say thanks so much for fzf and this plugin, which removed a lot of stuff from my vimrc :)

**Comment by junegunn** [comment]
> One thing I like about this version is that I no longer have to include flags

Yeah, that and we can easily pass pattern with spaces `:Ag foo bar`.

> doesn't also search against the filename/path

I also thought about lifting the restriction. Do you still think you're going to need path argument without the restriction?

**Comment by craigp** [comment]
> I also thought about lifting the restriction. Do you still think you're going to need path argument without the restriction?

Probably not actually, that would be enough

**Comment by junegunn** [comment]
So I changed the `nth` option for `Ag` command to `4..,..` from `4..`, which means fzf first matches without the file/line/col part, but looks at the the whole string if no match is found. It's a way to give more priority to the matches in the file content. The trick has its limitations but let's see how it goes.

**Comment by craigp** [comment]
Thanks!

**Comment by rainerborene** [comment]
This also works for me. Only problem is `:Ag` cannot search hidden files.

**Comment by blueyed** [comment]
It would still be very useful to search in a different path, without having to `:(l)cd` before; while it is useful and worked around for subdirs, the workaround does not work for other dirs (that are not below the current path).
Maybe a separate command could be used, e.g. `:AgIn` or something similar?

**Comment by rainerborene** [comment]
@junegunn what do think about allowing the `ag` command to be changed instead?

```diff
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index 445faa0..eb6a85e 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -403,10 +403,10 @@ endfunction
 function! fzf#vim#ag(query, ...)
   let args = copy(a:000)
   let ag_opts = len(args) > 1 ? remove(args, 0) : ''
+  let cmd = get(g:, 'fzf_ag_command', 'ag --nogroup --column --color %s "%s"')
+
   return s:fzf(fzf#vim#wrap({
-  \ 'source':  printf('ag --nogroup --column --color %s "%s"',
-  \                   ag_opts,
-  \                   escape(empty(a:query) ? '^(?=.)' : a:query, '"\-')),
+  \ 'source':  printf(cmd, ag_opts, escape(empty(a:query) ? '^(?=.)' : a:query, '"\-')),
   \ 'sink*':    s:function('s:ag_handler'),
   \ 'options': '--ansi --delimiter : --nth 4..,.. --prompt "Ag> " '.
   \            '--multi --bind ctrl-a:select-all,ctrl-d:deselect-all '.

```

**Comment by blueyed** [comment]
I think a separate command would provide the benefit of providing completion of paths.

**Comment by junegunn** [comment]
@rainerborene If it's allowed, how would you like it to be?

@blueyed Thanks for the suggestion, but this repo cannot provide every conceivable variation of the command to meet different needs. I would instead suggest the users to define their own custom commands with `fzf#vim#ag` function.

```vim
call fzf#vim#ag('foobar', {'dir': '~/github', 'down': '40%'})
```

**Comment by vito-c** [comment]
`:Ag` seems to search using the path value of `pwd`

Ag itself seems like a compliment to git. I would suggest `:Ag` should search inside the entire git repo that the current file belongs to. If it doesn't belong to a git repo then use `pwd`. 

It's nice not having to add a path but it seems to be a trade off for having to `:cd` where I want to search.

**Comment by vito-c** [comment]
Having a separate command like @blueyed mentioned that takes a path parameter would help cover all the edge cases. `:AgIn "search pattern" /some/path/far/**/away` would have the advantage of completions and glob syntax. 

I honestly don't find myself searching for patterns with spaces very often and there is always `\s` though I guess it might have to be double escaped or something on the `:` command.

**Comment by netei** [comment]
@vito-c you could use https://github.com/airblade/vim-rooter to automatically change your pwd depending on the presence of a `.git` file

**Comment by junegunn** [comment]
It is trivial to write an Ag variant that works on the git root:

```vim
function! s:with_git_root()
  let root = systemlist('git rev-parse --show-toplevel')[0]
  return v:shell_error ? {} : {'dir': root}
endfunction

command! -nargs=* Rag
  \ call fzf#vim#ag(<q-args>, extend(s:with_git_root(), g:fzf#vim#default_layout))
```

My point is that you can easily customize the behavior so there's no point of this plugin trying to satisfy every requirement.

**Comment by junegunn** [comment]
`AgIn` command discussed above:

```vim
function! s:ag_in(...)
  call fzf#vim#ag(join(a:000[1:], ' '), extend({'dir': a:1}, g:fzf#vim#default_layout))
endfunction

command! -nargs=+ -complete=dir AgIn call s:ag_in(<f-args>)
```

**Comment by vito-c** [comment]
```vim 
let root = systemlist('git rev-parse --show-toplevel')[0]
```
The above will still only use `pwd` as the input to `git rev-parse`

```vim
let groot = systemlist('git -C ' . expand('%:p:h') . ' rev-parse --show-toplevel')[0]
```
will use the path of the file in the current buffer.

I do understand the your point about the commands being easy to implement. I was just making a suggestion for out of the box ease of use :)

**Comment by peanutandchestnut** [comment]
I think this is actually the same issue as #92 . There should be a way to use raw ag, just like in terminal.
I also find that i want to do something like
```Vim
Ag something %
```
i don't think {'dir': path } can handle this. So i believe #144 is needed.  Although things will still break if you search in single file, because --nogroup doesn't works with single file. But you can do 
```Vim
Ag --noheading something %
```
And it works again. Maybe we can add --noheading to Ag base command option if you pull #144 
Default behavior is unchanged, for people who like ag in terminal. All you need to do is:
```Vim
let g:fzf_ag_raw =1
```

**Comment by junegunn** [comment]
I see your point, and I can understand that some users can feel more comfortable dealing with the options of ag command directly. However, we can't guarantee that the sink function of `Ag` will work if we give a full control over the underlying command to the users. [`--noheading` requirement you mentioned](https://github.com/junegunn/fzf.vim/issues/27#issuecomment-219589886) is a good example. So I still think it's better to abstract away the low-level details and provide simple commands that do not require the knowledge of the inner-workings of ag itself. (For example, we can extend the `AgIn` command to handle `--noheading` case.)

Anyway, if I'm going to provide the "raw" version of Ag, I'd like to make it clear that it's "advanced-users only" and provide it as an autoload function instead of making it available via `g:` variable. It's the convention of this plugin. Additional benefit of providing it as an autoload function, is that we can have two versions of the command at the same time, without having to toggle the variable on and off.

```vim
" "Raw"-version of Ag.
" Prepend `autocmd VimEnter *` if you want to name it Ag
" and override the default command
command! -nargs=+ -complete=file Rag call fzf#vim#ag_raw(<q-args>)
```

**Comment by hasufell** [comment]
Looking at this old thread again I'm trying to figure out how to make

```vim
function! s:with_git_root()
  let root = systemlist('git rev-parse --show-toplevel')[0]
  return v:shell_error ? {} : {'dir': root}
endfunction

command! -nargs=* Rag
  \ call fzf#vim#ag(<q-args>, extend(s:with_git_root(), g:fzf#vim#default_layout))
```

work again, because it doesn't anymore. Looking at https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L1 I don't really see enough information on what all those things do and what options `fzf#run` accepts. It is mentioned, but not really documented.

**Comment by junegunn** [comment]
The documentation for the basic Vim plugin (`fzf#run` and `fzf#wrap`) can be found on the main repo:

https://github.com/junegunn/fzf/blob/master/README-VIM.md

**Comment by danielo515** [comment]
> ```viml
> function! s:ag_in(...)
>   call fzf#vim#ag(join(a:000[1:], ' '), extend({'dir': a:1}, g:fzf#vim#default_layout))
> endfunction
> 
> command! -nargs=+ -complete=dir AgIn call s:ag_in(<f-args>)
> ```

This no longer seems to be valid because fzf default layout is now scoped to source. You can provide any other layout you have defined (I have a custom one) or you have to provide it inline

**Comment by junegunn** [comment]
Updated versions:

```vim
" "Raw" version of ag; arguments directly passed to ag
"
" e.g.
"   " Search 'foo bar' in ~/projects
"   :Ag "foo bar" ~/projects
"
"   " Start in fullscreen mode
"   :Ag! "foo bar"
command! -bang -nargs=+ -complete=file Ag call fzf#vim#ag_raw(<q-args>, <bang>0)

" Raw version with preview
command! -bang -nargs=+ -complete=file Ag call fzf#vim#ag_raw(<q-args>, fzf#vim#with_preview(), <bang>0)


" AgIn: Start ag in the specified directory
"
" e.g.
"   :AgIn .. foo
function! s:ag_in(bang, ...)
  if !isdirectory(a:1)
    throw 'not a valid directory: ' .. a:1
  endif
  " Press `?' to enable preview window
  call fzf#vim#ag(join(a:000[1:], ' '), fzf#vim#with_preview({'dir': a:1}, 'up:50%:hidden', '?'), a:bang)
endfunction

command! -bang -nargs=+ -complete=dir AgIn call s:ag_in(<bang>0, <f-args>)
```

**Comment by justrajdeep** [comment]
I am using the `Ag` command mentioned above 

I want the popup window but just not the preview window. How can I do that?

![Untitled](https://user-images.githubusercontent.com/3525867/99931980-98c43480-2d24-11eb-81cf-424825ddb680.png)

**Comment by danielo515** [comment]
> I am using the `Ag` command mentioned above
> 
> I want the popup window but just not the preview window. How can I do that?
> 
> ![Untitled](https://user-images.githubusercontent.com/3525867/99931980-98c43480-2d24-11eb-81cf-424825ddb680.png)

Have you tried this?

>   " If you don't want preview option, use this
>  " call fzf#vim#ag(join(a:000[1:], ' '), {'dir': a:1}, a:bang)

**Comment by justrajdeep** [comment]
> > I am using the `Ag` command mentioned above
> > I want the popup window but just not the preview window. How can I do that?
> > ![Untitled](https://user-images.githubusercontent.com/3525867/99931980-98c43480-2d24-11eb-81cf-424825ddb680.png)
> 
> Have you tried this?
> 
> > " If you don't want preview option, use this
> > " call fzf#vim#ag(join(a:000[1:], ' '), {'dir': a:1}, a:bang)

Hi 

I am talking about this

    " Raw version with preview
    command! -bang -nargs=+ -complete=file Ag call fzf#vim#ag_raw(<q-args>, fzf#vim#with_preview(), <bang>0)

**Comment by mb720** [comment]
Thanks for providing the code to make `:AgIn` work! 👍

I wanted to create mappings to search by file name and file content, starting at the current Git repo root:

    " Search by file name
    nmap <leader>R :Files `=GetGitRoot()`<cr>
    " Search by file content
    nmap <leader>O :AgIn  `=GetGitRoot()`<cr>

Where `GetGitRoot` is from @vito-c:

    " Gets the root of the Git repo or submodule, relative to the current buffer
    function! GetGitRoot()
      return systemlist('git -C ' . expand('%:p:h') . ' rev-parse --show-toplevel')[0]
    endfunction

As a small change, I had to call `expand` in `s:ag_in` as defined by @junegunn since `s:ag_in` would try to use "=GetGitRoot()" literally as a path, without evaluating the function (whereas `:Files` would work fine):

    " AgIn: Start ag in the specified directory
    "
    " e.g.
    "   :AgIn .. foo
    function! s:ag_in(bang, ...)
      let start_dir=expand(a:1)

      if !isdirectory(start_dir)
        throw 'not a valid directory: ' .. a:1
      endif
      " Press `?' to enable preview window.
      call fzf#vim#ag(join(a:000[1:], ' '), fzf#vim#with_preview({'dir': start_dir}, 'up:50%:hidden', '?'), a:bang)

    endfunction

    command! -bang -nargs=+ -complete=dir AgIn call s:ag_in(<bang>0, <f-args>)


I'm happy to learn if there's a more elegant way to do this. Thanks again for fzf.vim!
