### ISSUE TITLE
Feature request: find in all files

### ISSUE THREAD

**Issue by trusktr** [junegunn/fzf.vim#272]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

It'd be nice to have a command similar to `Lines`, but that searches in all files of the current (or specified) directory. Suppose it is called `FLines`, then `FLines` searches in current directory, and `FLines ..` would search in parent directory.

**Comment by junegunn** [comment]
`:Ag` without an argument can be used for that purpose, but it traverses the directory recursively so it can quickly become unwieldy. I think you'll be able to implement the feature using `fzf#vim#grep` function.

**Comment by morphheus** [comment]
Here is what I use to grep under my cwd:

`command! -bang FLines call fzf#vim#grep('grep -vnITr --color=always --exclude-dir={".git,".svn"} --exclude=tags --exclude={*\.pyc,*\.exe,*\.dll,*\.zip,*\.gz} "^$"', 0)`

The grep pattern "^$" just gets all empty lines, which is inverted with -v

Note that `--exclude=tags` is there to exclude my ctags files.

**Comment by unphased** [comment]
@morphheus your bind doesn't work: 

```Error detected while processing function fzf#vim#grep[23]..<SNR>126_fzf[18]..fzf#run[68].
.<SNR>21_execute:
line   18:
E484: Can't open file /var/folders/zq/q38qh7112m92fwjy8txqm_gc0000gn/T/vmrtlaq/2```

**Comment by morphheus** [comment]
Can you run the grep command directly in a terminal?  It sounds like you may not have rights to open that file.

**Comment by unphased** [comment]
Yeah that command you pasted has an odd number of `"` characters. Also I'm assuming it only works with GNU grep so my testing on OS X doesnt yield very good results on account of grep not supporting the -T flag among other things.

**Comment by morphheus** [comment]
you're correct, there is a typo. I updated the original comment with the version I currently use

**Comment by Eyenseo** [comment]
I am looking exactly for this! 

Below is my solution/workaround - I'm not good at vimscript, you may want to improve this (and create a pull request?).

```.vim
let s:is_win = has('win32') || has('win64')
function! s:shortpath()
  let short = fnamemodify(getcwd(), ':~:.')
  if !has('win32unix')
    let short = pathshorten(short)
  endif
  let slash = (s:is_win && !&shellslash) ? '\' : '/'
  return empty(short) ? '~'.slash : short . (short =~ escape(slash, '\').'$' ? '' : slash)
endfunction

function! s:line_handler(line)
  let keys = split(a:line, ':')
  execute 'e' keys[0]
endfunction

function! s:fzf_find_lines(dir)
  if !empty(a:dir)
    if !isdirectory(expand(a:dir))
      return s:warn('Invalid directory')
    endif
    let slash = (s:is_win && !&shellslash) ? '\\' : '/'
    let dir = substitute(a:dir, '[/\\]*$', slash, '')
  else
    let dir = getcwd()
  endif

  let command = 'rg --follow --hidden --glob "!.git/*" "" '.shellescape(dir)

  call fzf#run({
        \ 'source': command,
        \ 'sink':   function('s:line_handler'),
        \ 'options': '+m -x +s -d : --nth 2..',
        \ 'down' : '30%'
        \  })
endfunction

command! -nargs=? FLines call s:fzf_find_lines(<q-args>)
```

**Comment by midnio** [comment]
Any improvements, @junegunn ?

**Comment by junegunn** [comment]
I already gave an answer above. Try to learn basic Vimscript and you'll be able to implement any variations of the command. Also see #696.

**Comment by midnio** [comment]
Actually as default feature should be good.
