### ISSUE TITLE
fzf#vim#ag with arguments for ag

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#273]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

``` vim
"   :Ag  - Start fzf with hidden preview window that can be enabled with "?" key
"   :Ag! - Start fzf in fullscreen and display the preview window above
autocmd VimEnter * command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```
I want to use this search technique (form fzf.vim readme). How can I pass arguments to ag itself? For example, I want to search in xml files, so I want to pass `--xml` to ag.

**Comment by davidosomething** [comment]
i do it like this:

```
  " Default options are --nogroup --column --color
  let s:ag_options = ' --one-device --skip-vcs-ignores --smart-case '

  command! -bang -nargs=* Ag
        \ call fzf#vim#ag(
        \   <q-args>,
        \   s:ag_options,
        \  <bang>0 ? fzf#vim#with_preview('up:60%')
        \        : fzf#vim#with_preview('right:50%:hidden', '?'),
        \   <bang>0
        \ )

```

**Comment by yevhen-m** [comment]
@davidosomething how I can pass options from the input line?
I want to do like this: `:Ag! --py myclass`

**Comment by junegunn** [comment]
`fzf#vim#ag` internally calls `fzf#vim#ag_raw` (#17) which in turn calls `fzf#vim#grep` (see #36). So you can use either of the latter two functions. You might want to start with the `:Rg` example in the README page.

**Comment by backdoer** [comment]
> i do it like this:
> 
> ```
>   " Default options are --nogroup --column --color
>   let s:ag_options = ' --one-device --skip-vcs-ignores --smart-case '
> 
>   command! -bang -nargs=* Ag
>         \ call fzf#vim#ag(
>         \   <q-args>,
>         \   s:ag_options,
>         \  <bang>0 ? fzf#vim#with_preview('up:60%')
>         \        : fzf#vim#with_preview('right:50%:hidden', '?'),
>         \   <bang>0
>         \ )
> ```
> the options you pass as the second argument are added to the defaults (
> 
> [fzf.vim/autoload/fzf/vim.vim](https://github.com/junegunn/fzf.vim/blob/abdf894edf5dbbe8eaa734a6a4dce39c9f174e33/autoload/fzf/vim.vim#L614)
> 
> Line 614 in [abdf894](/junegunn/fzf.vim/commit/abdf894edf5dbbe8eaa734a6a4dce39c9f174e33)
> 
>  return call('fzf#vim#grep', extend(['ag --nogroup --column --color '.a:command_suffix, 1], a:000)) 
> )

You are a lifesaver my friend ☝️ I've been looking for this all night @davidosomething

**Comment by mauroporras** [comment]
@backdoer The spaces on both sides of the options don't seem to be necessary. See: https://github.com/junegunn/fzf.vim/issues/92#issuecomment-670986700
