### ISSUE TITLE
In 'VimR' use FZF, often appear "FZF is already runing", cannot use, how should I solve?

### ISSUE THREAD

**Issue by iuunhao** [junegunn/fzf.vim#274]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

In 'VimR' use FZF, often appear "FZF is already runing", cannot use, how should I solve?
![image](https://cloud.githubusercontent.com/assets/7666692/21311314/802f2e5c-c621-11e6-8b31-1e0c82f7ac84.png)

**Comment by iuunhao** [comment]
@qvacua 
I tried to uninstall, reinstall it, get the results are the same, of course, I have tried to restart the operating system, the same error, I do not know is the plug-in caused by the problem? Software caused the problem? I love this plugin, but now I can't use it, I can't find a solution.

**Comment by thedanotto** [comment]
Not sure if this will help, I have `Plug 'junegunn/fzf.vim'` below `Plug 'junegunn/fzf'`

**Comment by iuunhao** [comment]
@thedanotto 
I use your method, the result is the same. Every time I open the VimR will automatically create '~/.local/share/nvim', I do not know if it is related, but I deleted this directory, still can not be used

My profile does not set too much about FZF content.
[https://github.com/iuunhao/dotfiles/blob/dev/vim/vimrc.vim#L61-L63](https://github.com/iuunhao/dotfiles/blob/dev/vim/vimrc.vim#L61-L63)

**Comment by iuunhao** [comment]
I try to find the process of FZF, and want to kill it, but could not find it in the process, I just want to find a solution when it reappeared, can handle it, although the trouble, but does not affect I use it.

**Comment by iuunhao** [comment]
@junegunn  I found a temporary solution, I will [Comment out here](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L238-L241), can use, but I know this is not the fundamental solution.

**Comment by iuunhao** [comment]
@thedanotto thedanotto Close all buffer, restart it, the problem is that I installed a reserved conversation plug-ins caused problems
