### ISSUE TITLE
Don't see colors in preview

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#275]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

When I use `GFiles?` with preview, I don't see text, that is colored.
![image](https://cloud.githubusercontent.com/assets/10185058/21332145/419bd0b8-c64f-11e6-98d4-e833c40f3744.png)

Than's the same diff fragment from my terminal
![image](https://cloud.githubusercontent.com/assets/10185058/21332164/598e9d54-c64f-11e6-9f39-7a92a2cf6bf1.png)

Could you tell me what the problem is?

When I use preview elsewhere, is it supposed to be colored? Cause I have something like this:
![image](https://cloud.githubusercontent.com/assets/10185058/21332245/d7d4fc9e-c64f-11e6-9293-acb577cafab2.png)

**Comment by yevhen-m** [comment]
@junegunn I fixed the issue from the first screenshot, my custom colors in `init.vim` file did that.

But I still want to know if text in preview window is syntax colored.

**Comment by davidosomething** [comment]
do you have highlight or coderay installed? https://github.com/junegunn/fzf.vim/blob/9ce2c2179f5d7fc04bd24ccbb56553e4eaa9dd57/README.md#advanced-customization

**Comment by yevhen-m** [comment]
@davidosomething I have `coderay` installed. `bin/preview.sh preview.sh` outputs non-colored text, `bin/preview.sh preview.rb` outputs non-colored text.

**Comment by junegunn** [comment]
You need ruby. See #259.
