### ISSUE TITLE
Ag-option not applied in $FZF_DEFAULT_COMMAND?

### ISSUE THREAD

**Issue by MrAvantiC** [junegunn/fzf.vim#276]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hello,

first of all, thanks for your amazing plugins!

I have a problem with fzf though. Here is a minimal init.vim I was able to reproduce the problem with:

```
call plug#begin('~/.config/nvim/plugged')

Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

call plug#end()
```

...also I have Ag installed:

```
$ ag --version
ag version 0.33.0
```

**Now the problem is** that I have a project where my colleagues set up the `.gitignore` that is built like this:

```
/*
!/admin
...
````

...so first everything is excluded and then specific parts of the project get included again.
This causes FZF (or more specifically: Ag) to not display any results when I search for a string using `:Ag` inside nvim.
Now this seems to be a known bug in Ag but hasn't been fixed yet apparently, see here: https://github.com/ggreer/the_silver_searcher/issues/168

What I would usually do here is use the option `--skip-vcs-ignores` when searching with ag. For example if I run 
```
$ Ag --skip-vcs-ignores global
```
from the terminal in this directory I get results just fine.

What I tried now was to set the `$FZF_DEFAULT_COMMAND` to use ag with this setting:
```
let $FZF_DEFAULT_COMMAND='ag --skip-vcs-ignores -g ""'
```
...as I understood it I should now be able to do 
```
:Ag global
```
inside nvim and it uses the supplied default-command?

Unfortunately I don't get any results here as it seem that the skip-setting is not being applied when I use FZF inside nvim like that?

Am I doing something wrong here?

Any help would be appreciated. :)

**Comment by junegunn** [comment]
The variable in only used in the following contexts for listing files

- `fzf` in shell
- `:FZF` or `:Files` in Vim

To customize ag command used in `:Ag`, you'll have to use one of the autoload functions. See:
- https://github.com/junegunn/fzf.vim/blob/7460b4382cd9e22651c5fb252471d403cef07aee/autoload/fzf/vim.vim#L606-L624
- https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by junegunn** [comment]
```vim
autocmd VimEnter * command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>, '--skip-vcs-ignores', <bang>0)
```

**Comment by MrAvantiC** [comment]
That works flawlessly, thank you very much!

**Comment by backdoer** [comment]
Is there a way to configure it to allow custom args as shown above ☝️ while still keeping the 
```
command! -bang -nargs=* Ag
			\ call fzf#vim#ag(<q-args>,
			\   <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
			\           : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
			\   <bang>0) "Ag will show file contents with a preview
``` 
configuration?

**Comment by junegunn** [comment]
@backdoer Pass it as the second argument. See https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L678-L679
