### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by ricardoseriani** [junegunn/fzf.vim#277]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Please, there is any way that I can pass a global options (like --reverse) to all commands (tags, buffers, marks, etc).

**Comment by junegunn** [comment]
`$FZF_DEFAULT_OPTS`. See man page of fzf for the details.
