### ISSUE TITLE
Feature request: Combine :BTags and :Lines for easier source code navigation

### ISSUE THREAD

**Issue by stjepang** [junegunn/fzf.vim#279]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [X] macOS
    - [X] Windows
    - [X] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

If I want to look at the list of all functions in a Python file, I don't use tagbar nor `:BTags`.
Instead, I open `:Lines` and then search for "def". This displays a nice condensed view of the source, with proper indentation and full argument lists.

That looks *much* more natural than `:BTags` and tagbar, which are just boring lists of weirdly sorted function names.

Instead of manually entering filters (like "def" or "class"), could FZF perhaps filter all lines with definitions automatically? I'd love to have something like `:Lines`, but displaying only those lines which contain a tag definition.

Emacs can be configured to do that with Helm: http://i.imgur.com/lXdmRwd.png

**Comment by junegunn** [comment]
You can pass an initial query to :Lines or :BLines command, so `:Lines def`.

How about this?
```vim
command! Defs Lines def<space>
```

**Comment by stjepang** [comment]
That works, but I would like to have language aware filtering.

This command displays a list of line numbers that contain tags:
```bash
ctags --fields=+n --sort=no -f - FILENAME | cut -d$'\t' -f5 | cut -d':' -f2
```

Now I'd like to show only those lines from ctags, using a slight modification to `:BLines` ([here](https://github.com/junegunn/fzf.vim/blob/2066643243eddf2ed1f5d3a1a5485d6ff71851a4/autoload/fzf/vim.vim#L342)). That would achieve exactly what I had in mind.

**Comment by stjepang** [comment]
I managed to implement this feature myself:

```vim
function! s:outline_format(lists)
  for list in a:lists
    let linenr = list[2][:len(list[2])-3]
    let line = getline(linenr)
    let idx = stridx(line, list[0])
    let len = len(list[0])
    let list[0] = line[:idx-1] . printf("\x1b[%s%sm%s\x1b[m", 34, '', line[idx:idx+len-1]) . line[idx+len:]
  endfor
  for list in a:lists
    call map(list, "printf('%s', v:val)")
  endfor
  return a:lists
endfunction

function! s:outline_source(tag_cmds)
  if !filereadable(expand('%'))
    throw 'Save the file first'
  endif

  for cmd in a:tag_cmds
    let lines = split(system(cmd), "\n")
    if !v:shell_error
      break
    endif
  endfor
  if v:shell_error
    throw get(lines, 0, 'Failed to extract tags')
  elseif empty(lines)
    throw 'No tags found'
  endif
  return map(s:outline_format(map(lines, 'split(v:val, "\t")')), 'join(v:val, "\t")')
endfunction

function! s:outline_sink(lines)
  if !empty(a:lines)
    let line = a:lines[0]
    execute split(line, "\t")[2]
  endif
endfunction

function! s:outline(...)
  let args = copy(a:000)
  let tag_cmds = [
    \ printf('ctags -f - --sort=no --excmd=number --language-force=%s %s 2>/dev/null', &filetype, expand('%:S')),
    \ printf('ctags -f - --sort=no --excmd=number %s 2>/dev/null', expand('%:S'))]
  return {
    \ 'source':  s:outline_source(tag_cmds),
    \ 'sink*':   function('s:outline_sink'),
    \ 'options': '--reverse +m -d "\t" --with-nth 1 -n 1 --ansi --prompt "Outline> "'}
endfunction

command! -bang Outline call fzf#run(fzf#wrap('outline', s:outline(), <bang>0))
nnoremap <silent> <space>o :Outline<CR>
```

This is what it looks like when navigating a Python file:

![](https://i.imgur.com/dYxm6qg.png)

I'm not that good with vimscript so it's not perfect, but I'm quite happy with this solution :)
For me, it fully replaces tagbar.

**Comment by stjepang** [comment]
By the way, I think this is very similar to https://github.com/Shougo/unite-outline.
Since unite and fzf.vim overlap quite a bit, perhaps it might be a good idea for fzf.vim to include something like `:Outline`.

**Comment by junegunn** [comment]
Cool. Good to hear that you found a solution.

> perhaps it might be a good idea for fzf.vim to include something like :Outline.

Maybe, but ctags only supports a limited set of file types, no support for markdown for example. I would expect more from an "outline" command, and then it's beyond the scope of this repository.

**Comment by hupfdule** [comment]
> ctags only supports a limited set of file types, no support for markdown for example

Just to add some information: universal ctags _does_ support markdown, asciidoc, etc. It doesn't resemble the structure yet, but work is ongoing. See https://github.com/universal-ctags/ctags/issues/2063.
