### ISSUE TITLE
Consider window working directory for commands

### ISSUE THREAD

**Issue by sschaef** [junegunn/fzf.vim#28]
I want that fzf respects my `.gitignore` files, therefore I have the following configured: https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

However, this seems to consider only the `.gitignore` file of the working directory where vim (in my case neovim) is started. When I do a `:lcd` in order to change the working directory in vim and then run `:Files`, the `.gitignore` file of the newly configured working directory is not considered.

**Comment by junegunn** [comment]
I can't seem to reproduce the problem.

**Comment by sschaef** [comment]
You are right, it works fine for me now too. Maybe I accidentally managed to run fzf from a shell where the fzf config was not yet applied.
