### ISSUE TITLE
FZF show all files by default

### ISSUE THREAD

**Issue by matrinox** [junegunn/fzf.vim#280]
- Category
    - [ ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

I'm assuming it uses git ls-files automatically when it's in a repo? It's just a bit annoying and not in the docs. I propose to just show all files, like `git ls-files -oc` for `Files` and `FZF`. Or add options/new command.

**Comment by junegunn** [comment]
> I'm assuming it uses git ls-files automatically when it's in a repo?

No. Please see https://github.com/junegunn/fzf#usage
