### ISSUE TITLE
error when trying to run FZF the second time

### ISSUE THREAD

**Issue by adham90** [junegunn/fzf.vim#282]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

when i try to run :FZF or :Files for the second time i get this error
execvp failed no such file or directory
![error](http://i.imgur.com/bvsrsfu.png)

**Comment by adham90** [comment]
i just fix it i was using `set shell=zsh` on my nvim config file but i'm use fish shell

**Comment by rosshadden** [comment]
Odd.  I get a very similar error, but it happens the first time I run FZF, too.  Also I use zsh, but just in case I tried setting `shell` to `zsh`, as it was `/bin/zsh`.  Neither works for me.
