### ISSUE TITLE
:Ag without a pattern causes freeze 

### ISSUE THREAD

**Issue by eater** [junegunn/fzf.vim#283]
- Category
    - [x] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

1. Start gvim with `gvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)`
2. `:cd` to a directory containing 20 text files, 180K total size, no subdirs
3. `:Ag` 
4. The FZF window opens with a count of 0/0 and doesn't increase. If I don't kill FZF within a few seconds, my entire fast computer becomes unresponsive until I force-power-off the machine.
5. Running `:Ag foo` instead is fast and smooth.

Any idea how to figure this out?

**Comment by junegunn** [comment]
`ag --version` ?

**Comment by eater** [comment]
0.28, which is the current stable version for Ubuntu 15.04.

I just upgraded it to 0.30 and no more problem!
