### ISSUE TITLE
Incompatible with vim-tmux-navigator tmux plugin

### ISSUE THREAD

**Issue by oblitum** [junegunn/fzf.vim#285]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Just moved to fzf after using ctrl-p for many years. Sometimes by accident I press ctrl-k/ctrl-j with the intent of moving out of the fzf window or inside it, but these keys do nothing there. I realize I should use ctrl-p/ctrl-n or closing the window before moving between vim windows (which I do with ctrl-k/ctrl-j). The real problem happens because if I do that by mistake Vim gets stuck, I can't type anything, it keeps outputting "K^", etc in wrong places. I have to press CTRL-C to get out of this stuck mode.

**Comment by junegunn** [comment]
CTRL-J/K are equivalent to CTRL-N/P by default. They work as expected for me inside and outside of Vim. I have no idea why they're not working for you, but have you tried using it on a different terminal emulator?

**Comment by oblitum** [comment]
@junegunn no, I've done the test like suggested, with the provided minimal `.vimrc`, it was the reported behaviour. I use xfce4-terminal-devel + tmux + vim-tmux-navigator, which allows me to move between tmux panes and vim windows using CTRL-J/K with no difference. I will try to disable/enable parts of this setup to check whether any or which of those cause the conflict.

**Comment by junegunn** [comment]
Sounds like a compatibility issue with vim-tmux-navigator.

**Comment by oblitum** [comment]
Yes, it is. Just tested, it's incompatible with the [vim-tmux-navigator tmux plugin](https://github.com/christoomey/vim-tmux-navigator#tpm) (not the vim plugin part as far as I've tested).

**Comment by oblitum** [comment]
In case you are "won't fix" on this one, is there a way to make just CTRL-N/CTRL-P work in the fzf window and simple disable/do-nothing on CTRL-J/CTRL-K? This would at least avoid it from entering the broken state.

**Comment by junegunn** [comment]
You can try adding `--bind 'ctrl-j:ignore,ctrl-k:ignore'` in your `$FZF_DEFAULT_OPTS`.

**Comment by oblitum** [comment]
`export FZF_DEFAULT_OPTS="--bind 'ctrl-j:ignore,ctrl-k:ignore'"` didn't work. In an horizontal tmux pane split, with vim on top with 3 buffers open, `:Buffers` will list them. If CTRL-J is pressed the cursor moves out of the fzf window (leaving it open) down to the inferior tmux pane. I can move back to the fzf window "inside" Vim with CTRL-K. Now if I press CTRL-K in the fzf window the terminal enters a broken state which I can only get out with CTRL-C.

**Comment by oblitum** [comment]
As far as I can see, this has been fixed with time :)

**Comment by oblitum** [comment]
I was once fixed, but it's not anymore :(
