### ISSUE TITLE
:Files displays bare buffer

### ISSUE THREAD

**Issue by subsetpark** [junegunn/fzf.vim#288]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

With a minimal configuration: `:Files` displays a blank `> fzf` buffer. The directory prompt is pointing to the correct directory listing, but there are no files to filter on.

On the other hand, `:GitFiles` works perfectly.

I'm marking this 'question' because I'm sure I'm doing something wrong!

**Comment by junegunn** [comment]
- Do you have `$FZF_DEFAULT_CMD` or `$FZF_DEFAULT_OPTS` defined?
- Does `fzf` work okay outside of vim?

**Comment by subsetpark** [comment]
1) No, and no;
2) I think so. For instance:
     1. I can type `ls /var/ | fzf` 
     2. fzf runs with the contents of my /var directory
     3. I can use the arrow keys to select one of the line and hit <enter>
     4. the line is echoed in my shell.

**Comment by junegunn** [comment]
Probably related to this: https://github.com/junegunn/fzf/issues/797#issuecomment-272223478

fzf uses `$SHELL -c [COMMAND]` to start the process. Uses `sh` if `$SHELL` is not defined.

**Comment by subsetpark** [comment]
Ok, that seems right... I typed `sh '{the default command you listed there}'` and it didn't work. Nor does it work in my shell. I don't fully understand though; does fzf wrap all command strings in double quotes? `$SHELL -c 'seq 100'` produces output, whereas $SHELL -c "seq 100" doesn't.

**Comment by junegunn** [comment]
> $SHELL -c "seq 100"

That sounds broken. This is the code fzf uses:

https://github.com/junegunn/fzf/blob/master/src/util/util_unix.go#L11-L17

I'm closing this as it looks like a problem of your shell.

**Comment by subsetpark** [comment]
Ok, I'm not sure that's the whole story though... for instance, if I set `DEFAULT_FZF_CMD` to `find * -type f`, then `$SHELL -c $DEFAULT_FZF_CMD` works perfectly normally, but `fzf` still opens to a blank buffer.

Anyway, thanks for taking the time to look into it.

**Comment by junegunn** [comment]
Ah, right, it's `FZF_DEFAULT_COMMAND`, not `DEFAULT_FZF_CMD`.

**Comment by subsetpark** [comment]
Ok, thanks!
