### ISSUE TITLE
Cycling between :Files, :History etc

### ISSUE THREAD

**Issue by myitcv** [junegunn/fzf.vim#289]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Firstly, this is an awesome replacement for CtrlP. Thank you for your work on this.

Secondly, a question that I can't find an answer to (as much as anything it's a case of not finding any results for the search queries I'm trying). CtrlP has the key bindings `<c-b>` and `<c-f>` to cycle between the modes of Files, MRU and buffers. I'd like the equivalent in `fzf`. Whilst I can see this may not be supported out the box, I couldn't see how/where to define such a key-binding. 

Ideally I'd like to be able to map `<Leader>t` to `:Files` or `:GFiles` (based on whether I'm in a git directory or not) and then have `<c-f>` and `<c-b` cycle forwards or backwards through the "chain" `(:Files | :GFiles) -> :History -> Buffers ->`

Any pointers much appreciated.

**Comment by myitcv** [comment]
I should note @junegunn's comment [here](https://github.com/junegunn/fzf.vim/issues/233#issuecomment-257158595) about how to achieve the `:GFiles` to `:Files` fallback... so this issue is focussed on the question of how to define the cycling as described above.

**Comment by myitcv** [comment]
Just found the [`--bind` option to `fzf`](https://github.com/junegunn/fzf/blob/a71c47140575b324afeb054a4fbc0e3fa505d4d0/man/man1/fzf.1#L114-L116) via the manpage (doesn't get a real mention in the wiki... worth addressing?) which should give me what I need.... assuming I can do things based on the current state of `fzf`. Will close this issue

**Comment by junegunn** [comment]
Unfortunately I don't think it's going to be that simple. I would use `--expect` option for that purpose on the shell where I can tell the script what to do next based on the first line of the output (the name of the pressed key). You can do the same on Vim if you're going to implement the functions from scratch using `fzf#run`. But using commands in this repository means that you're using a predefined set of sink functions whose behaviors you can't easily customize.

Since you use Neovim, I expected that we can use `tmap` to implement the feature like follows:

```vim
function! s:fzf_next(idx)
  if &filetype == 'fzf'
    close
  endif
  let commands = ['Files', 'Buffers', 'Colors']
  execute commands[a:idx]
  let next = (a:idx + 1) % len(commands)
  execute 'tnoremap <buffer> <silent> <c-f> <c-\><c-n>:call <sid>fzf_next('.next.')<cr>'
endfunction

command! Cycle call <sid>fzf_next(0)
```

However, it doesn't work well, possibly due to a limitation or bug of Neovim.

**Comment by junegunn** [comment]
Possibly related: https://github.com/junegunn/fzf/issues/426

**Comment by myitcv** [comment]
@junegunn thanks very much for the quick response. I've already dropped down to using `fzf#run` so I'll give this a shot via `--expect`

**Comment by ErikLambrechts** [comment]
Should something like this be possible in Vim

**Comment by npearson72** [comment]
@myitcv did you ever figure this out?

**Comment by myitcv** [comment]
No, I did not @npearson72

**Comment by npearson72** [comment]
That's a pity. I'm wondering if there's a way to at least toggle between `:Files` and `:History`. Perhaps using different bindings for each.

**Comment by npearson72** [comment]
@myitcv 

I think I was able to work it out. Can you give this a try:

```
function! s:fzf_next(idx)
  if &filetype == 'fzf'
    close
  endif
  let commands = ['Files', 'History', 'Buffers']
  execute commands[a:idx]
  let next = (a:idx + 1) % len(commands)
  execute 'tnoremap <buffer> <silent> <c-f> <c-\><c-n>:close<cr>:sleep 100m<cr>:call <sid>fzf_next('.next.')<cr>'
endfunction

command! Cycle call <sid>fzf_next(0)
```

**Comment by npearson72** [comment]
The edit I made to @junegunn's example produces the result described in your original post, nothing more.

**Comment by myitcv** [comment]
Sorry, just to clarify, the bit that is "outstanding" in all of this is:

>  and then have <c-f> and <c-b cycle forwards or backwards through the "chain" `(:Files | :GFiles) -> :History -> Buffers ->`

**Comment by npearson72** [comment]
Binding the additional `<c-b>` seems to work for me:

```function! s:fzf_next(idx)
  let commands = ['Files', 'Buffers', 'History']
  execute commands[a:idx]
  let next = (a:idx + 1) % len(commands)
  let previous = (a:idx - 1) % len(commands)
  execute 'tnoremap <buffer> <silent> <c-f> <c-\><c-n>:close<cr>:sleep 100m<cr>:call <sid>fzf_next('.next.')<cr>'
  execute 'tnoremap <buffer> <silent> <c-b> <c-\><c-n>:close<cr>:sleep 100m<cr>:call <sid>fzf_next('.previous.')<cr>'
endfunction
```

**Comment by staticshock** [comment]
Here's a snippet that allows me to switch from `:History` (or any other fzf command) to `:Files` via `<c-f>` and **preserves user input** in the process:

https://github.com/staticshock/dotfiles/blob/1babbc7dc3b9d8debe92758c7069945b3060ed90/.config/nvim/init.vim#L45-L63

**Comment by mangelozzi** [comment]
@staticshock answer looks very nice by did not work for me in Neovim (it would add lots of spaces and surrounding border to the query. I modified it abit to this:

```vim
" Switch from any fzf mode to :Files on the fly and transfer the search query.
function! s:FzfFallback()
    if &filetype != 'FZF'
        return
    endif
    " Extract from first space to cursor position of previous fzf buffer prompt
    let query = getline('.')[stridx(getline('.'), ' ') : col('.') - 1]
    close
    sleep 1m
    call fzf#vim#files('.', {'options': ['-q', query]})
endfunction
tnoremap <c-space> <c-\><c-n>c:call <sid>FzfFallback()<cr>
```
