### ISSUE TITLE
Reopen last search

### ISSUE THREAD

**Issue by hkupty** [junegunn/fzf.vim#290]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

It'd be handy to reopen last search and probably continue from where it left.
Not sure if it's currently possible (didn't find anything about it on the docs) nor if it's implementable (didn't look throught the code), though.

**Comment by junegunn** [comment]
What is "search"?

**Comment by balta2ar** [comment]
@hkupty This question has been brought up several times. I can't recall exact issue, but you can definitely find it using search in this or fzf main repo.

**Comment by maximbaz** [comment]
For those who stumble on this issue, the solution was found in https://github.com/junegunn/fzf/issues/379:

```
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history"
``` 

Works great in terminal and in vim.

**Comment by dre-hh** [comment]
Just crossposting some info found here in other issues.

One can also load the fzf results into quickfix window by selection them all with `alt + a` or selectively with `tab`, then hit enter.
For alt + a not inserting some unicode character but sending the above command the behaviour must be set properly in the used terminal. (ESC+)

For iterm2 see  https://iterm2.com/faq.html 
 `Q: How do I make the option/alt key act like Meta or send escape codes?`

One can cycle withing quickfix window without loosing focus of the search result with :cnext and :cprev which are nicely mapped to ]q and [q with the vim-unimpared plugin.

Once lost focus or closed quickfix window. The last search result can be opened with :copen command.

**Comment by mrbiggfoot** [comment]
@maximbaz unfortunately it's not that great. The exact candidate that was selected previously is lost. Ideally, the history file should contain the search pattern along with selected candidates.

**Comment by maximbaz** [comment]
Completely agree, I wish the selected candidate was focused again when I retrieve an entry from the history (or in case of multiple candidates, the entire selection was restored).

**Comment by mrbiggfoot** [comment]
[This PR](https://github.com/junegunn/fzf/pull/1302) should make life a little easier. Note that the candidates fed to fzf should be exactly the same, or the restored selection will be random.
