### ISSUE TITLE
Feature suggestion: smart ctrl-A, to either select all or go to begining of line

### ISSUE THREAD

**Issue by thalesmello** [junegunn/fzf.vim#291]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

## Context

International Mac OS keyboard users kind of have a problem with the alt key: it's used systemwise to input accented chacaters (alt + e then e yields é), and I'm already used to typing that way.

When using the Ag command in Vim, I know that I can press Alt + A to select all the entries. The problem is that key is clumsy to use in my keyboard, as I have configured to use the left alt for accented characters, and the right alt key as a true alt key, but it's also clumsy to have to press the right key when I want to do that. 

I particularly think Ctrl-a would make the most sense, in my opinion.

I know that I can remap that with bind, the problem is that I also expect that key to go to the beginning of the line when I'm editing text.

## Suggestion

considering this, what if there was a special mode for the **ctrl-a** key, one that:

- if the cursor is in the beginning of the line, it will select all
- if the cursor is at any other position, it will go to the beginning of the line.

Would something like this make sense?

Thank you for your time and have a nice day.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion. The idea is intriguing, but I can't think of a sane way to support complex, composite actions while keeping fzf simple and maintainable in the long run. If we don't draw the line somewhere, we may end up with dozens of `do-something-if-xxx-until-yyy-but-not-when-zzz-then-do-something-else` :) So for now, I'd rather not add actions beyond basic ones.

I suggest that you just use different bindings by overriding :Ag command. See https://github.com/junegunn/fzf.vim/issues/228#issuecomment-256359415
