### ISSUE TITLE
option --height problem

### ISSUE THREAD

**Issue by knon** [junegunn/fzf.vim#292]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hello,
I'm very appreciate for your fzf.vim. It's very helpful. Thank you very much!

I am sorry that I got problem today. I found the option --height not available in fzf 0.15.9. And it causes problem when using fzf.vim. Please fix it!

fzf: 0.15.9
tmux: 2.3
vim: 8.0.197

**Comment by knon** [comment]
I comment the line 307 in the file fzf.vim, and the fzf.vim plugin work now. I can't find a way to assign the variable use_height.

**Comment by knon** [comment]
I just followed the readme and found there is a new fzf.vim plugin now. After installed it, the problem is fixed.

**Comment by junegunn** [comment]
Any reason you can't upgrade fzf to 0.16.1? It's highly recommended.

**Comment by knon** [comment]
Of course not. I just installed fzf from the Linux Repo. I'll change it to git repo
