### ISSUE TITLE
Is it possible to filter by f or v in :BTags?

### ISSUE THREAD

**Issue by rawaludin** [junegunn/fzf.vim#293]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'm using :BTags now to filter for method and variables in current files. It run perfectly. However, is it possible to filter tag showing only with `f` (function) or `v` (variable) type?

I see this things has been done in tagbar, but I can't find a solution how to implement it in fzf.

https://github.com/majutsushi/tagbar/issues/390

**Comment by balta2ar** [comment]
As for **filtering**, see this: https://github.com/junegunn/fzf.vim/issues/244
As for the **showing**, maybe it could help to have an option to control which fields are displayed in Tags and BTags. I miss is too. @junegunn?

On a related note, BTags output is nicely aligned:
![](https://i.imgur.com/1vn0iH1.png)

While Tags is not:
![](https://i.imgur.com/yafaLNG.png)

**Comment by junegunn** [comment]
I believe you can pass `--with-nth` and `--nth` options to achieve it.

As for the alignment, yes, BTags aligns the list because it's highly likely that the list is small and it won't take much time to preprocess the list.

**Comment by balta2ar** [comment]
@junegunn Thanks, `--with-nth` did that!

Is there a way to turn on the alignment anyway in my vimrc? Could you please show an example, if it's possible? My tags are not that big, maybe performance would be tolerable.

**Comment by PezCoder** [comment]
Can anyone please explain on how can we use --with-nth & -n to trigger just a function search in tags.
I've looked into multiple issues & code but only able to figure out this much:
1. **This is how to pass custom options to Btags**
The documentation mentions :BTags [query] which I misunderstood that I can pass the parameter like so `:Btags --with-nth` but that didn't work. Later realised after looking into some of the answers provided by @junegunn on other issues:
```vim
nnoremap <silent> <leader>j :call fzf#vim#buffer_tags('', {'options': ''})<CR>
```
2. By trial & error, if i pass these in options parameter
--with-nth 1 -> Gives everything
--with-nth 2 -> Gives file name
--with-nth 3 -> Gives something weird (semicolons)
--with-nth 4 -> Gives list of type of tags

I'm still not able to figure out the role of -n & how I can combine it with --with-nth to achieve what I need.
Appreciate any help.

**Comment by junegunn** [comment]
Have you read through `man fzf`?

**Comment by junegunn** [comment]
This is not ideal, but it's something you can try:

```vim
call fzf#vim#buffer_tags('', { 'options': ['--nth', '..-2,-1', '--query', '^f$ '] })
```

**Comment by PezCoder** [comment]
Thank you that worked like a charm. It's pretty common for me to quickly goto/search a function inside the buffer i'm in, a live view for that makes it even better.

I foolishly though these options are part of fzf.vim, `man fzf` explains it all really well.

**Comment by JesseLeite** [comment]
Hey @junegunn sorry to bother... In your last example above, is that `^f$` supposed to be [extended search mode syntax](https://github.com/junegunn/fzf#search-syntax)?

Trying to write my own `:BTags`-like command that will ignore namespaces and use aliases, but I'm not having any luck with that example.
