### ISSUE TITLE
Not picking up guifg/guibg

### ISSUE THREAD

**Issue by sliceofcode** [junegunn/fzf.vim#294]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

It looks like fzf.vim is not picking up `guifg`. It ignores it and uses `ctermfg` instead.

![2017-01-21-18 11 52](https://cloud.githubusercontent.com/assets/4206232/22179329/3381c080-e005-11e6-85eb-211b1c732686.png)

In the screenshot, fzf.vim is using `Normal` for the names of files listed. If I change `ctermfg=7` to `ctermfg=0`, it turns black. This means that fzf.vim is using `ctermfg` instead of `guifg`, which is what I want.

**Comment by junegunn** [comment]
Official 24-bit color support is coming. Stay tuned.

https://github.com/junegunn/fzf/issues/818

<img width="1280" alt="screen shot 2017-01-22 at 2 32 59 pm" src="https://cloud.githubusercontent.com/assets/700826/22180306/bfb0cca4-e0af-11e6-8d6b-a0095c0f433c.png">

**Comment by sliceofcode** [comment]
@junegunn Awesome, thank you so much for this. :smile: I'm gonna close this in favor for the issue that you opened.
