### ISSUE TITLE
"FZF is already running!"

### ISSUE THREAD

**Issue by whitecolor** [junegunn/fzf.vim#295]
- Category
    - [ x] Question
- OS
    - [ x ] Windows 10 Ubuntu bash shell
- Vim
    - [ x] Neovim 0.1.7

- AG search is installed

As I type any command (like `:FZF`) I get:
![image](https://cloud.githubusercontent.com/assets/736697/22182920/f97e7544-e0d2-11e6-925a-8e3e03215b94.png)

Nothing else happens.

What should one do in this situation?

**Comment by junegunn** [comment]
https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md

**Comment by whitecolor** [comment]
Ok, I've added details.

**Comment by junegunn** [comment]
Did you test with the command/configuration suggested in the issue template?

**Comment by whitecolor** [comment]
**Resolved now.** The problem was due to buffer exists in saved session.

 "term://.//22123:/bin/bash "/tmp/nvim6dBJaM/2"|"/dein.vim/repos/github.com/junegunn/fzf/bin/fzf"  --multi  --prompt '/m/d/C/bbooks/'  --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvim6dBJaM/1;#FZF" line 0
```
I removed it, it works now. Have to figure out how it is better to work with sessions (I use `vim-startify` for managing sessions)
