### ISSUE TITLE
Inside tmux lines sometimes overlap

### ISSUE THREAD

**Issue by hendricius** [junegunn/fzf.vim#297]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi everyone,

this is probably something related to my Tmux config or so. I usually code in Iterm2 and launch my tmux session. In that one I use VIM.

Now what has been happening is, that the search lines are sometimes overlapping each other. Navigating upwards/downwards with the arrow keys will then clear the lines, revealing the true filename to me.

![image](https://cloud.githubusercontent.com/assets/816859/22298338/71a73ed0-e320-11e6-8fd0-58151ba49567.png)

Have you had a similar problem - what could it be related to?

Thanks!

**Comment by hendricius** [comment]
Addon - sorry. It also happens when I press `ctrl + r` to search through my history outside of vim. We can definitely close this ticket, but maybe someone can help me.

**Comment by junegunn** [comment]
Can it be related to https://github.com/junegunn/fzf/issues/821? Does the line causing the problem contain tab character (or any non-ascii character)?

The issue is fixed and you can download the binary with the fix in advance here: https://github.com/junegunn/fzf-bin/releases/alpha
