### ISSUE TITLE
Is it possible to modify how results are displayed?

### ISSUE THREAD

**Issue by Alok** [junegunn/fzf.vim#299]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion

- Vim
    - [ ] Vim
    - [x] Neovim

I made this ["fzf plugin"](https://github.com/Alok/notational-fzf-vim). It's basically notational velocity for vim. One user had an issue with overly long filepaths like `~/this/is/a/very/deep/path` taking up all the space on a line and making it hard to read.

I'm curious about being able to control the *display* of lines in a way like this:

`~/a/long/path/ text` -> `~/a/l/p text`.

If this isn't something that should be part of `fzf` but an external tool, do you know of any UNIX filter that does something similar?

**Comment by junegunn** [comment]
Formatting the input should be done outside of fzf. But basic transformation is available via `--with-nth`, which is useful when some information is required after the filtering, but you want to hide it in the finder (e.g. `--with-nth=2.. --delimiter="\t"` on `FULLPATH\tSHORTPATH`).

> do you know of any UNIX filter that does something similar?

I'm not aware of such a tool, but `pathshorten({expr})` in Vim does this nicely.

**Comment by pzh2386034** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/9897310/162864261-99adddf7-af86-4f94-875a-e657c748794b.png">
hi, also have such issue, it there any quick method to slove this it?
