### ISSUE TITLE
Introduce search files only command

### ISSUE THREAD

**Issue by sschaef** [junegunn/fzf.vim#30]
This more or less asks for reverting this commit: https://github.com/junegunn/fzf.vim/commit/ee794573e55b9aa0537e40fdc0d6b76ffdf17100

Or at least it would be nice to have a variant of Ag, that searches only the content of the files. Also, I'm not really interested.

Also, it would be nice to shorten the path of the file a little bit. My paths often span 80% of the entire screen. This makes it hard to see if the match is the one I looked for. For me, only showing the name of the file would probably enough.

**Comment by junegunn** [comment]
Thanks for the suggestions. I'll think about the options. By the way, as noted in the readme page this project is not designed to be highly configurable and is strictly based on my own preferences. So it is encouraged that you fork it if you need more customization. This project already has quite a number of features, and it's not easy to satisfy different tastes, so I see this as a example/reference implementation for fzf users.

**Comment by bfgasparin** [comment]
@junegunn :

Can you help me?

A have the following config in my .vimrc 

```vim
function! s:ag_in(...)
  call fzf#vim#ag(join(a:000[1:], ' '),
  \                 extend({'dir': get(a:, 1, '')},
  \                 fzf#vim#with_preview('right:50%:hidden', '?')))
endfunction

" Ag command with path as first argument
command! -nargs=* -complete=dir AgIn call s:ag_in(<f-args>)
```

It allow me to search for patterns using Ag, with an optional dir path` as first  argument, and adds the preview windows to fzf.

But I want to filter only the content of the files, ignoring the filenames. (Like running ag on a shell) 

I see there is an example to do that on the [readme examples of the repo](https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim), but I had difficult to add preview windows to that solution. And I suppose there may be a fancy solution using the functions of this plugin.

Is there an easy way to do that using the `fzf#vim#ag` function?

**Comment by bfgasparin** [comment]
I found a solution.

I changed to the raw ag function version:

```vim
command! -nargs=+ -complete=file Ag call fzf#vim#ag_raw(<q-args>,
\                     fzf#vim#with_preview('right:50%:hidden', '?'))
```
