### ISSUE TITLE
Whitespace follows filenames

### ISSUE THREAD

**Issue by alexanderkron** [junegunn/fzf.vim#300]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Filenames are followed by whitespace that fills the remainder of the line. If vim is set to highlight trailing whitespace this looks not great and is slightly annoying.

![image](https://cloud.githubusercontent.com/assets/12139603/22512789/217a8636-e868-11e6-8b84-b188a34041e5.png)

**Comment by junegunn** [comment]
I'm confused, is it Vim or Neovim?

**Comment by alexanderkron** [comment]
This is in Vim with
```
" show trailing whitespace
match ErrorMsg '\s\+$'
```
in my .vimrc

**Comment by junegunn** [comment]
FZF draws outside Vim window and the highlighting rules of Vim does not apply.

Try this. If you see the same problem, then it confirms that it's not an issue of fzf

```vim
:call system('seq 10 > /dev/tty; sleep 2') | redraw!
```

**Comment by alexanderkron** [comment]
Hm, yeah this doesn't seem to be a FZF problem. Sorry!

**Comment by junegunn** [comment]
Hi, https://github.com/junegunn/fzf/commit/c89ac341e4d9199ff0ca6ca7af29d9b14a1b7fbd might fix your problem.

**Comment by danishprakash** [comment]
> FZF draws outside Vim window and the highlighting rules of Vim do not apply.

Hi, I know this issue is 7 years old but is this still the case? I see the above issue with a particular [theme](https://github.com/danishprakash/vim-yami) that highlights `ErrorMsg` but not others.
