### ISSUE TITLE
Clear/hide the :Files pane/buffer with <esc>?

### ISSUE THREAD

**Issue by megalithic** [junegunn/fzf.vim#301]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

After recent updates to fzf/fzf.vim, i've noticed that my :Files "pane" doesn't hide/disappear with an escape key press any more. It now requires that i exit that "pane"/buffer. Perhaps I missed a setting that was introduced, or this is a bug?

Thanks so much for your awesome tooling you provide and maintain, @junegunn.

**Comment by noahfrederick** [comment]
@megalithic: What does `:verbose tmap <Esc>` say?

**Comment by megalithic** [comment]
@noahfrederick thanks for response, here is the output:
`   <Esc>       * <C-\><C-N>`

**Comment by noahfrederick** [comment]
It looks like you've mapped `<Esc>` to exit terminal mode, so it never reaches `fzf` and you're left in normal mode instead of telling `fzf` to exit. You'll have to choose a different key to map that doesn't conflict or maybe go out of your way to unmap `<Esc>` in FZF buffers (untested):

```vim
autocmd FileType fzf tnoremap <buffer> <Esc> <Esc>
```

**Comment by noahfrederick** [comment]
Yeah, here's your problem:
https://github.com/megalithic/dotfiles/blob/fc369fd47263bc27ce82dbb4c4865e0208613252/config/config.symlink/nvim/keys.vim#L436

**Comment by megalithic** [comment]
hilarious.. @noahfrederick, you sir are a genius, i even looked back and forth through here.. thanks again.
