### ISSUE TITLE
Weird error appears about "--expect=ctrl-v,ctrl-x,ctrl-t --no-height"

### ISSUE THREAD

**Issue by tyrocca** [junegunn/fzf.vim#302]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim
- Other details: 
    - I am using NVIM 0.2.0-dev (I update it frequently - I just followed the install instructions on the neovim site)
    - I am using tmux 1.8

Hi junegunn!

First of all thank you for all of your great contributions to vim / neovim. I use a ton of your plugins! Recently (like over the last week) I have been getting this error sporadically:
**The Error**
`Error running git ls-files |"/home/ty/.fzf/bin/fzf"  -m --prompt "GitFiles> " --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimHUNOth/12`
**Background info**
I launch `:GFiles` with `<C-p>`. The error appears after I close the fzf buffer. I think it happens if do something like hit `<C-[>`, `<C-p>` or when I type `:`  and `enter` when the fzf buffer is open. It's really frustrating because I haven't been able to figure out how to consistently replicate it. I tried with your minimal config, but I wasn't able to reproduce. I just know that it started happening recently... I would appreciate any help you can offer! 

Thank you again for your time and help!
Ty

**Comment by junegunn** [comment]
Does the command `git ls-files |"/home/ty/.fzf/bin/fzf" -m --prompt "GitFiles> " --expect=ctrl-v,ctrl-x,ctrl-t --no-height` consistently work in your terminal? Or do you see errors?

> I tried with your minimal config, but I wasn't able to reproduce.

Hmm, then you'll have to figure out which part of your configuration is interfering with the way fzf works. There's no easy way, comment out most of your config, incrementally uncomment sections until you find the culprit.

**Comment by tyrocca** [comment]
1. Yes, that command seems to consistently work
2. Thank you for your advice. I wasn't sure if there was anything you could make from that error (I get a similar error with `:History`as well). All I know is that after it happens neovim often seg faults if I try to run it again. It's always hard debugging an error when you can't consistently replicated it. Thank you for your help!!

**Comment by junegunn** [comment]
Segfault is the result of some critical bug of Neovim, and it's highly likely that the problem you're having is related to the defect. You might want to check out the issue tracker of Neovim or talk to the guys in their gitter channel. https://gitter.im/neovim/neovim

**Comment by cvlmtg** [comment]
I have a similar problem which appeared today, I suppose due to some of the last commits.

```
Error running ( git ls-files  )|'/Users/matteo/.fzf/bin/fzf'  -m --prompt "GitFiles> " --expect=ctrl
-v,ctrl-x,ctrl-t --no-height > /var/folders/zp/1cddchs97zxgtshn1gmcq0_c0000gn/T/nvimYYMqhd/5
```

I'm using fzf.vim with neovim (compiled from HEAD with homebrew on OSX) and I use the fish shell, so I suspect those parens around `git ls-files` might be the culprit, but I'm just guessing of course.

**Comment by cvlmtg** [comment]
@junegunn sorry, i just made a stupid test. If I run nvim and start `:FzfGitFiles` I have the error I described above, if I ':set shell=bash` and then run fzf again it works, so it's definitely those parens around `git ls-files` which have appeared recently

**Comment by junegunn** [comment]
@cvlmtg What is your default `&shell`? Please comment on https://github.com/junegunn/fzf/pull/1029 instead.

**Comment by junegunn** [comment]
@cvlmtg Looks like I can reproduce the problem with `set shell=fish`, let me look into it.

**Comment by cvlmtg** [comment]
👍

**Comment by junegunn** [comment]
@cvlmtg Actually, I can't. I was running into a different problem. This is basically what the plugin does on Neovim; we temporarily change `shell` to `sh` before starting terminal process. Does this work?

```vim
:try | let oshell = &shell | set shell=sh | call termopen('( git ls-files )') | finally | let &shell = oshell | endtry
```

**Comment by cvlmtg** [comment]
As I wrote in my first comment, I have neovim compiled from HEAD so yes, I have the latest version.

your example seems to work. it opens a readonly buffer with the list of files

**Comment by junegunn** [comment]
@cvlmtg How about the other commands? Does `call fzf#run({'source': 'seq 10 && seq 10'})` work as expected?

**Comment by cvlmtg** [comment]
this other example works ok too. I suppose the only problem are the parens around shell commands because in the fish shell are invalid syntax

**Comment by junegunn** [comment]
fzf#run automatically wraps the command with parens, so `seq 10 && seq 10` becomes `( seq 10 && seq 10 )`, there's no difference. You can check yourself:

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 0f4fc77..934dc52 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -678,6 +678,8 @@ function! s:execute_term(dict, command, temps) abort
     if s:present(a:dict, 'dir')
       execute 'lcd' s:escape(a:dict.dir)
     endif
+    echom a:command
+    return
     call termopen(a:command . ';#FZF', fzf)
   finally
     if s:present(a:dict, 'dir')
```

**Comment by cvlmtg** [comment]
`call fzf#run({'source': 'seq 10 && seq 10'})` works
`call fzf#run({'source': 'git ls-files'})` works
`:FzfGitFiles` doesn't work

**Comment by junegunn** [comment]
This is GFiles in essence:
```vim
call fzf#run(fzf#wrap({'source': 'git ls-files', 'dir': systemlist('git rev-parse --show-toplevel')[0], 'options': '-m --prompt "GitFiles> "'}))
```

**Comment by cvlmtg** [comment]
that one doesn't work, so I suppose the problem lies in `fzf#wrap` rather than in `fzf#run`

**Comment by junegunn** [comment]
Hmm, you can inspect the return value of wrap function to see which part of it is causing the error.

**Comment by cvlmtg** [comment]
you mean like this?

```
:call fzf#run(fzf#wrap({'source': 'seq 10'}))

Error running ( seq 10 )|'/Users/matteo/.fzf/bin/fzf'   --expect=ctrl-v,ctrl-x,ctrl-t --no-height >
/var/folders/zp/1cddchs97zxgtshn1gmcq0_c0000gn/T/nvim4cYilo/4

echo fzf#wrap({'source': 'seq 10'})

{'options': '  --expect=ctrl-v,ctrl-x,ctrl-t', 'source': 'seq 10', 'sink*': function('59'), 'down':
'~40%', '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}}
```

**Comment by cvlmtg** [comment]
`:call fzf#run({'options': '  --expect=ctrl-v,ctrl-x,ctrl-t', 'source': 'seq 10', 'down': '~40%', '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}})`

gives the error. (I had to remove the 'sink*' key because it gave me other errors)

`:call fzf#run({'source': 'seq 10', 'down': '~40%', '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}})`

still gives the error

`:call fzf#run({'source': 'seq 10', 'down': '~40%'})`

still gives the error

`:call fzf#run({'source': 'seq 10'})`

works

`:call fzf#run({'source': 'seq 10', '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}})`

works

`:call fzf#run({'options': '  --expect=ctrl-v,ctrl-x,ctrl-t', 'source': 'seq 10',  '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}})`

works

so it's the 'down' key that gives the problem

**Comment by junegunn** [comment]
Alright, so which version of fzf do you have? That is: `/Users/matteo/.fzf/bin/fzf --version`

**Comment by cvlmtg** [comment]
~ /Users/matteo/.fzf/bin/fzf --version
0.17.0 (e89eebb)

**Comment by cwfparsonson** [comment]
Hi, I haven't made any changes to my init.vim config but am now getting this error pop up whenever I try to launch fuzzy finder. 

My init.vim config:

```
" IMPORT COC CONFIGURATION
source ~/.config/nvim/plugged/coc_conf.vim

" PLUGIN (using vim-plug package manager. Do :PlugInstall to install plugins)
call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdtree'
Plug 'neomake/neomake'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdcommenter'
call plug#end()

" GENERAL CONFIG
set nocompatible            " disable compatibility to old-time vi
set showmatch               " show matching brackets.
set ignorecase              " case insensitive matching
set mouse=a                 " middle-click paste with mouse
set clipboard=unnamed       " enables pasting from default clipboard
set hlsearch                " highlight search results
set tabstop=4               " number of columns occupied by a tab character
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
set expandtab               " converts tabs to white space
set shiftwidth=4            " width for autoindents
set autoindent              " indent a new line the same amount as the line just typed
set number                  " add line numbers
set wildmode=longest,list   " get bash-like tab completions
set cc=80                   " set an 80 column border for good coding style
set nowrap
filetype plugin indent on   " allows auto-indenting depending on file type
syntax on 		            " syntax highlighting
set pastetoggle=<F2>        " switch in and out of paste mode
colorscheme gruvbox
set background=dark         " set gruvbox colorscheme to dark mode
:let g:airline_theme='wombat' " set theme of airline ribbon
let g:neomake_python_enabled_markers = ['pylint'] " set pylint as python code checker
call neomake#configure#automake('nrwi', 500)
nnoremap <C-p> :GFiles<CR>
set relativenumber
set noerrorbells            " disable error sound effects
set smartcase
set noswapfile
set nobackup
set undodir=~/.config/nvim/undodir
set undofile
set incsearch

let g:netrw_browse_split=2
let g:netrw_banner=0
let g:netrw_winsize=25

" TERMINAL EMULATOR CONFIG
tnoremap <Esc> <C-\><C-n>

" MAP LEADER CONFIG
let g:mapleader=' '         " sets mapleader key
nnoremap <leader>s :split<cr>
nnoremap <leader>v :vsplit<cr>
xnoremap p pgvy             " allows for pasting multiple times
nnoremap <Up> <Nop>          " disable arrow keys
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
inoremap  <Up>     <Nop>
inoremap  <Down>   <Nop>
inoremap  <Left>   <Nop>
inoremap  <Right>  <Nop>

" NERD TREE
let g:NERDTreeQuitOnOpen = 1
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>u :UndotreeShow<CR>
map <leader>nt :NERDTreeToggle<CR>
```

**Comment by cwfparsonson** [comment]
> Hi, I haven't made any changes to my init.vim config but am now getting this error pop up whenever I try to launch fuzzy finder.
> 
> My init.vim config:
> 
> ```
> " IMPORT COC CONFIGURATION
> source ~/.config/nvim/plugged/coc_conf.vim
> 
> " PLUGIN (using vim-plug package manager. Do :PlugInstall to install plugins)
> call plug#begin()
> Plug 'morhetz/gruvbox'
> Plug 'vim-airline/vim-airline'
> Plug 'vim-airline/vim-airline-themes'
> Plug 'neoclide/coc.nvim', {'branch': 'release'}
> Plug 'scrooloose/nerdtree'
> Plug 'neomake/neomake'
> Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
> Plug 'junegunn/fzf.vim'
> Plug 'preservim/nerdcommenter'
> call plug#end()
> 
> " GENERAL CONFIG
> set nocompatible            " disable compatibility to old-time vi
> set showmatch               " show matching brackets.
> set ignorecase              " case insensitive matching
> set mouse=a                 " middle-click paste with mouse
> set clipboard=unnamed       " enables pasting from default clipboard
> set hlsearch                " highlight search results
> set tabstop=4               " number of columns occupied by a tab character
> set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
> set expandtab               " converts tabs to white space
> set shiftwidth=4            " width for autoindents
> set autoindent              " indent a new line the same amount as the line just typed
> set number                  " add line numbers
> set wildmode=longest,list   " get bash-like tab completions
> set cc=80                   " set an 80 column border for good coding style
> set nowrap
> filetype plugin indent on   " allows auto-indenting depending on file type
> syntax on 		            " syntax highlighting
> set pastetoggle=<F2>        " switch in and out of paste mode
> colorscheme gruvbox
> set background=dark         " set gruvbox colorscheme to dark mode
> :let g:airline_theme='wombat' " set theme of airline ribbon
> let g:neomake_python_enabled_markers = ['pylint'] " set pylint as python code checker
> call neomake#configure#automake('nrwi', 500)
> nnoremap <C-p> :GFiles<CR>
> set relativenumber
> set noerrorbells            " disable error sound effects
> set smartcase
> set noswapfile
> set nobackup
> set undodir=~/.config/nvim/undodir
> set undofile
> set incsearch
> 
> let g:netrw_browse_split=2
> let g:netrw_banner=0
> let g:netrw_winsize=25
> 
> " TERMINAL EMULATOR CONFIG
> tnoremap <Esc> <C-\><C-n>
> 
> " MAP LEADER CONFIG
> let g:mapleader=' '         " sets mapleader key
> nnoremap <leader>s :split<cr>
> nnoremap <leader>v :vsplit<cr>
> xnoremap p pgvy             " allows for pasting multiple times
> nnoremap <Up> <Nop>          " disable arrow keys
> nnoremap <Down> <Nop>
> nnoremap <Left> <Nop>
> nnoremap <Right> <Nop>
> inoremap  <Up>     <Nop>
> inoremap  <Down>   <Nop>
> inoremap  <Left>   <Nop>
> inoremap  <Right>  <Nop>
> 
> " NERD TREE
> let g:NERDTreeQuitOnOpen = 1
> nnoremap <leader>h :wincmd h<CR>
> nnoremap <leader>j :wincmd j<CR>
> nnoremap <leader>k :wincmd k<CR>
> nnoremap <leader>l :wincmd l<CR>
> nnoremap <leader>u :UndotreeShow<CR>
> map <leader>nt :NERDTreeToggle<CR>
> ```




UPDATE: It turns out that this was being caused by some memory error. I am using some remote servers and there were idle processes using a significant amount of the CPUs (show with ```top -i```). Once I killed these processes, my problems were fixed!
