### ISSUE TITLE
Relative filepath completion

### ISSUE THREAD

**Issue by jonsmithers** [junegunn/fzf.vim#303]
- Category
    - [X] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

I think it'd be awesome to have filepath completion relative to the current buffer. I've seen Deoplete [implement this ability](https://github.com/Shougo/deoplete.nvim/issues/109), and I use it constantly for relative html imports. But being able to fuzzy find a relative import would be much awesomer.

I'd like to either suggest this as a feature, or ask how I might make this work within my own vimrc.

I came _really close_ with the following vimrc code:

    inoremap <expr> <c-x><c-f> CompleteRelativePath()
    func! CompleteRelativePath()
        :cd %:h
        call fzf#vim#complete#path("find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'")
        return ""
    endfu

It even works when you're autocompleting for a parent directory or sibling directory (i.e. `"../../bower_components/<C-X><C-F>`. The only problem is that I need to add `:cd -` to change back to the original working directory, but somehow that stops fzf from using the `%:h` as its working directory, even though the fzf call precedes the `:cd -` call.)

I hope I've effectively explained myself. Any ideas? Or thoughts?

**Comment by junegunn** [comment]
How about doing `fzf#vim#complete#path(printf("cd %s && find ...", shellescape(expand('%:h'))))`?

**Comment by jonsmithers** [comment]
oh....that's nifty. It works for completing within the buffer's current directory (`"./<c-x><c-f>`). 

However, it's somehow broken path completion for child and parent directories. Imagining the following project structure....

```
(project root)/
 ├── parent/
 │   ├── child/
 │   │   ├── c.txt
 │   │   └── d.tx
 │   └── CURRENT_BUFFER.txt
 ├── a.txt
 └── b.txt
```


Opening `CURRENT_BUFFER.txt` and typing `"./child/<c-x><c-f>"` or `"../<c-x><c-f>` will briefly flicker a panel that reads something like "_cd: ./child: no such file or directory_" or "_cd: parent: no such file or directory_".

**Comment by FabioAntunes** [comment]
I was just searching for the same feature, but probably in a different way, I was thinking something like using the regular fuzzy file search, when we select a file, based on our current file create a relative path to that file.

Sometimes I don't know what's the relative path to the file that I want but I do now the name.

```
(project root)/
 ├── parent/
 │   ├── child/
 │   │   ├── c.txt
 │   │   └── d.tx
 │   └── CURRENT_BUFFER.txt
 ├── a.txt
 └── b.txt
```

So if i did a search by .txt,  I would  the regular output, like this: 
```
parent/child/c.txt
parent/child/d.txt
a.txt
b.txt
```

But when I select one of the files it would output the relative path to the current buffer.
I just taking my first steps on the vim world, I don't know if this could be easily achievable creating a custom function

**Comment by jonsmithers** [comment]
@FabioAntunes +1. I think I like your idea better.

**Comment by bannier** [comment]
Hi all. any body achieved that ?
I gave it a try without success : 

```
func! CompleteRelativePath()
  let p = expand('%:p:h')
  let rp = system("realpath --relative-to=".p." /my/project/directory")
  call fzf#vim#complete#path("cd ".p." && find ".rp." -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'")
  return ""
endfu
```
This displays a long list of files but as soon as the file listing is done, the fzf pane is cleared.

I'd like to have a list of all project files relative to current buffer's path (to import relative files) : 

```
- ../some/file
- ../../some/other/file

...
```

**Comment by junegunn** [comment]
Unfortunately `cd` trick won't work at the moment. I'll see what I can do.

**Comment by junegunn** [comment]
Update fzf.vim and see if this works for you:

```vim
inoremap <expr> <c-x><c-f> fzf#vim#complete#path(
    \ "find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'",
    \ fzf#wrap({'dir': expand('%:p:h')}))
```

**Comment by bannier** [comment]
No it doesn't (but thanks for trying). It lists relative path to files in current buffer's directory but relative path not other files from project.

I'm not sure I explained correctly what I'm trying to do. Perhaps it's not the same feature as @jonsmithers and @FabioAntunes.

Given the following projet structure
```
├── .git (= opened neovim here)
└── dir
    ├── other_file
    └── subdir
        ├── CURRENT_BUFFER
        └── other_file_in_same_dir


```
When editing `CURRENT_BUFFER` and trigger autocomplete path 

With your solution I FZF window displays the following list : 
```
CURRENT_BUFFER
other_file_in_same_dir
```

And I would like to list : 
```
../../dir
../../dir/other_file
../../dir/subdir
../../dir/subdir/CURRENT_BUFFER
../../dir/subdir/other_file_in_same_dir
```

In order to insert relative file imports.

**Comment by junegunn** [comment]
It's a different requirement from the initial one in the OP.

Can you come up with a shell command that prints the desired list?

**Comment by jonsmithers** [comment]
I just want to say that @junegunn's solution works beautifully for behavior described in the OP!

**Comment by FabioAntunes** [comment]
@junegunn what about something like (this)[https://unix.stackexchange.com/a/233882/74067]? using realpath? 

Also fzf is built on top of go, another possibility would be using (Rel)[https://golang.org/pkg/path/filepath/#Rel]?

The current solution only works with files that are on the same folder of the current buffer.

Unfortunately my vim script skills are null, or else I would try to come up with something.
But what I would like to do is using `:Files` getting the path for the file, then get the current buffer path and with that generate a relative path..

**Comment by FabioAntunes** [comment]
Well as I said my vim skills are beyond terrible, I did manage to get something but is far from great.
Also my golang skills are terrible, never done any golang before.

I created a small binary in golang to create relative paths:
```
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	path := os.Args[1]
	relative := os.Args[2]
	relPath, err := filepath.Rel(path, relative)
	if err != nil {
		panic(err)
	}
	if !strings.HasPrefix(relPath, "../") {
		relPath = "./" + relPath
	}
	fmt.Println(relPath)
}
```
I have compiled this one, added the bin to my PATH on my shell and I named it `relative-path`

Then on my `.vim` I did this horrible scripting:

```
function! s:make_path(path)
  let bPath = expand('%:p:h')
  let fPath = system("realpath " . join(a:path))
  let relPath = system("relative-path " . bPath . " " . fPath)
  return substitute(relPath, '\n\+$', '', '')
endfunction

inoremap <expr> <c-x><c-s> fzf#complete({
  \ 'source':  'ag -g ""',
  \ 'reducer': function('<sid>make_path')})
```

The only thing is the window for auto-complete takes the entire screen I guess there are some options I could pass

**Comment by junegunn** [comment]
Cool, wrap your dictionary with `fzf#wrap` function. i.e. `fzf#complete(fzf#wrap({ ... }))`


See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

**Comment by tuyenpm9** [comment]
Anyone has solution that work on windows?

**Comment by netoctone** [comment]
@tuyenpm9 something similar to the above PR might work

**Comment by rodhash** [comment]
> Update fzf.vim and see if this works for you:
> 
> ```viml
> inoremap <expr> <c-x><c-f> fzf#vim#complete#path(
>     \ "find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'",
>     \ fzf#wrap({'dir': expand('%:p:h')}))
> ```

Thank you very much, was trying to get this working for quite awhile. As I usually have multiple Buffers opened was really annoying using the simple <c-x><c-f> knowing I had the powerful fzf not being used.

**Comment by firexcy** [comment]
> Update fzf.vim and see if this works for you:
> 
> ```viml
> inoremap <expr> <c-x><c-f> fzf#vim#complete#path(
>     \ "find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'",
>     \ fzf#wrap({'dir': expand('%:p:h')}))
> ```

Thanks for the solution. However, I find it switches vim to normal mode after the completion. Is it possible to stay in insert mode by making some tweaks?

**Comment by junegunn** [comment]
@firexcy That's a bug. I'll see what I can do.

**Comment by junegunn** [comment]
@firexcy d43df0e should fix the problem.

**Comment by firexcy** [comment]
> @firexcy [d43df0e](https://github.com/junegunn/fzf.vim/commit/d43df0ea2f099836c2e3499756101e87bcbd3e25) should fix the problem.

Tried and works like a charm. Thanks for such a quick fix.

**Comment by Cr1m50nr34p3r** [comment]
fzf vim uses the `FZF_DEFAULT_COMMAND` variable which needs to be exported in your `.bashrc` file 
so I set it to 
`export FZF_DEFAULT_COMMAND="find -L -type f -exec readlink -f {} +;"
`
it enables hidden files and also shows full path
