### ISSUE TITLE
`&&` command not support in fish-shell

### ISSUE THREAD

**Issue by hzchirs** [junegunn/fzf.vim#304]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Using `fzf-complete-file-ag` or `fzf-complete-file` in fish-shell is not working, here's the error message:
```
Error running cd '.' && ag -l -g '' | sed 's:^::'|"/Users/user/.fzf/bin/fzf" +m -q '' --prompt './' --query '' --no-height > /var/folders/ly/zntlqm0133ngvbe2bhvxz9v80000gn/T/nvimlvKuZC/5
```
I think it's because fish-shell not support `&&`.  Is there any way to fix this? Thanks.

**Comment by junegunn** [comment]
You can tell Vim to use standard, posix-compliant shell by `set shell=sh`.

**Comment by hzchirs** [comment]
It works. Thanks for your quickly response.
