### ISSUE TITLE
Add Results to Args list of buffers

### ISSUE THREAD

**Issue by scottgrayson** [junegunn/fzf.vim#305]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a keyboard shortcut to load all fzf results into buffers or arglist?

If not, then i suggest it as a feature.

It would be nice to use for search and replace with `:argdo` and `:bufdo` when you only want to run the command on files with a specific filename or content

**Comment by junegunn** [comment]
You can bind a key to `select-all` action which makes fzf select all matches at once. For instance,

```sh
export FZF_DEFAULT_OPTS='--bind alt-a:select-all'
```

Press `ALT-A` then enter to open selected files in Vim. Then you can use `bufdo` with those open buffers. You can even use bind the key to composite action `select-all+accept` so that you don't have to hit enter after `ALT-A`.

**Comment by john-kurkowski** [comment]
And is there a recipe to send those results to the arglist, so I can `argdo`?

**Comment by camspiers** [comment]
@john-kurkowski I figured out something for myself:

```
func s:fnameescape(key, val)
  return fnameescape(a:val)
endfunc

function! s:build_arg_list(lines)
  let arglist = map(a:lines, function('s:fnameescape'))
  execute 'args ' . join(arglist, ' ') 
endfunction

let g:fzf_action = { 'ctrl-l': function('s:build_arg_list') }
```

Hitting `ctrl-l` in this example will populate the arglist with fzf.vim's selected results.

Hope it helps!

**Comment by camspiers** [comment]
@john-kurkowski Bummer, I just realized that the above implementation only works for the files list, not for search results e.g. from Ag or Rg. I'll see if I can get it working for them.

**Comment by yannick-cw** [comment]
I think it is a good idea to leave splitting windows in the fzf_action
```
let g:fzf_action = { 
      \ 'ctrl-l': function('s:populate_arg_list'),
       \ 'ctrl-x': 'split',
       \ 'ctrl-v': 'vsplit' }
```
as you override is otherwise
