### ISSUE TITLE
Vim 8 discards unmatched typeahead going into FZF; NeoVim doesn't

### ISSUE THREAD

**Issue by sunaku** [junegunn/fzf.vim#307]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hello,

FZF.vim behaves differently under Vim 8.0 and NeoVim 0.1.7 when triggered from a [fallback shortcut][plugin], which is a FZF menu triggered by a common prefix that is used by multiple keybindings.  For example:

```vim
:noremap <Space> :Filetypes<CR>
:noremap <Space>ff :Files<CR>
:noremap <Space>fg :GFiles<CR>
```

Given the above mappings, when I type Space followed by `f` and wait for the timeout, both Vim and NeoVim will fall back to the least-common-denominator mapping (the very first one, which runs `:Filetypes`) and trigger an FZF menu.  However, at this point, Vim and NeoVim diverge:

* NeoVim correctly feeds the `f`that I typed into FZF, so that FZF begins filtering for `f` immediately.
* Vim discards the `f` that I typed. :scream:  This requires me to manually re-type the `f` back into FZF. :disappointed:

Is there a way to make Vim behave like NeoVim in this situation?  Because [my shortcut menu system][plugin] relies on the user's unmatched typeahead input to be propagated as-is into FZF rather than being discarded. :sweat:

Thanks for your consideration.

[plugin]: https://github.com/sunaku/vim-shortcut#readme

**Comment by junegunn** [comment]
On Vim, fzf is an external process that does not share typeahead buffer with Vim. You can easily reproduce the problem like follows:

```vim
nnoremap <space>x :!read<cr>
nnoremap <space>xxxxy <nop>
```

The situation is different in Neovim as it starts fzf inside its own terminal emulator.

There's no simple solution to the problem. What we can do is to read typeahead buffer using `getchar(0)` and manually pass it to fzf.

```vim
function! Typeaheads()
  let chars = ''
  while 1
    let c = getchar(0)
    if c == 0
      break
    endif
    let chars .= nr2char(c)
  endwhile
  return chars
endfunction

nnoremap <leader>x :call fzf#vim#files('', {'options': '--query='.shellescape(Typeaheads())})<cr>
nnoremap <leader>xxxxy <nop>
```

But this is convoluted and clunky. I don't know if it's possible to "re-feed" the read chars to tty input.

**Comment by sunaku** [comment]
Thanks Junegunn! :bowing_man:  I have incorporated this workaround into my plugin (only for regular Vim). :joy_cat:
