### ISSUE TITLE
Q: How to deal with `:Ag` and vim-rooter switching project's subdirectories

### ISSUE THREAD

**Issue by aerosol** [junegunn/fzf.vim#308]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, 
first of all, thanks for `fzf`. It's a game changer. ❤️ 
Apologies for potential annoyance, but no idea where to go with this, my vimscript fu is insufficient.
I am using [`vim-rooter`](https://github.com/airblade/vim-rooter) to detect/switch `pwd` to certain project's subdirectories (many apps in a single repo).

I need `fzf` to always start from `.git` root though. With `:Files` it's easy, since I can define the following command:

```vim
command! ProjectFiles exe "Files " . systemlist('git rev-parse --show-toplevel')[0]
```

And it searches through my entire project no what `vim-rooter` set.
However, I am getting trouble getting `:Ag` to work in a similar fashion.

With the following dummy-project structure:

```
testfzf
└── apps
    ├── app1
    │   ├── cwd_switch_trigger
    │   └── thing1.txt
    └── app2
        ├── cwd_switch_trigger
        └── nothing.txt
```

having vim-rooter set to detect/switch cwd based on `cwd_switch_trigger` presence ([using this option](https://github.com/airblade/vim-rooter/blob/master/plugin/rooter.vim#L21-L23)) I am getting a behaviour I don't really grok.

1. Start vim within `testfzf` using `vim .`
2. `:Ag`

<img width="506" alt="image" src="https://cloud.githubusercontent.com/assets/173738/22949366/51f27694-f302-11e6-8dda-db818170825a.png">

3. select thing1.txt
4. `vim-rooter` kicks in, switches cwd to `app1`

<img width="342" alt="image" src="https://cloud.githubusercontent.com/assets/173738/22949384/6917c5d6-f302-11e6-815d-c0ba57bf7fde.png">

5. Switch `pwd` to `.git` root, manually

<img width="323" alt="image" src="https://cloud.githubusercontent.com/assets/173738/22949411/7cb0e14a-f302-11e6-8533-f5aafbe1fee0.png">

6. Fire `:Ag` again. Looks good all files are reachable:

<img width="366" alt="image" src="https://cloud.githubusercontent.com/assets/173738/22949429/90e707d4-f302-11e6-8750-906704500393.png">

7. Select `nothing.txt`, hit `<CR>`. An new (non-existing) file gets opened:

<img width="299" alt="image" src="https://cloud.githubusercontent.com/assets/173738/22949446/a680f7d0-f302-11e6-8272-e9e41086408f.png">

And the `pwd` is still pointing at `app1`.
Expected behaviour: open the existing, non-empty file.

As far as I understand, there is no way for me to point the `:Ag` command at a directory. Any ideas/pointers on how can I overcome this? A million thanks.

**Comment by junegunn** [comment]
I just tried rooter with some repos, but I had no issues.
Please make sure that you can reproduce the problem with the minimal vimrc suggested in the issue template (https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc) (with the Plug statement for rooter).

**Comment by aerosol** [comment]
@junegunn Thank you. Reproducible with the following vimrc: https://gist.github.com/aerosol/f517b2c8cd34b3ccb0c29d076155771e

I have pushed a test repo [here](https://github.com/aerosol/testfzf).

Steps to reproduce:

1. `git clone git@github.com:aerosol/testfzf.git /tmp/testfzf`
2. `cd /tmp && wget https://gist.githubusercontent.com/aerosol/f517b2c8cd34b3ccb0c29d076155771e/raw/e26bace52c6adffae97245cb002e05a0ba69e8cd/testfzf_vimrc`
3. `cd /tmp/testfzf && vim -u /tmp/testfzf_vimrc`
4. `:Ag`, type "`some`", `<CR>`
5. `:cd /tmp/testfzf`
6. `:Ag`, type "`other`", `<CR>`

**Comment by junegunn** [comment]
Still can't reproduce: https://asciinema.org/a/82ue4l1ih9zk5cxjw38vizmi7

**Comment by aerosol** [comment]
holy smokes. at this point I'll try upgrading neovim I suppose. thank you @junegunn

**Comment by junegunn** [comment]
Hmm, maybe it's only reproducible on Neovim, I'll test it with Neovim later in the day. Possibly related: #321

**Comment by junegunn** [comment]
Okay, you forgot to make app1 and app2 separate git repos. After doing `git init` in both directories, I could reproduce the problem on Neovim as expected.

1. FZF window is closed
2. The cursor goes into the original directory
3. Rooter (or autochdir) kicks in, changes the working directory
4. FZF tries to open the selected file in relative path and fails

(In plain Vim, we use `system()` or `:!` command so there's no step 2 and 3.)

I think I can fix this relatively easily.

**Comment by real-or-random** [comment]
This is a problem in the new plain vim, because now we use steps 2 and 3 (as far as I understand).

Everything seems to work for me when I remove the ``has('nvim') &&`` introduced in the above commit, so this is the cause.
