### ISSUE TITLE
`:Commits` outputting slashes

### ISSUE THREAD

**Issue by sodapopcan** [junegunn/fzf.vim#309]
- Category
    - [x] Question
    - [x] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

The output of `:Commits` looks like this on macOS Sierra.

![image](https://cloud.githubusercontent.com/assets/3752792/23025853/3b55df9e-f42d-11e6-999e-b45b044b4237.png)

Alllllso, for some reason, `CTRL-S` in the `:: Press CTRL-S to toggle sort` blinks!  However, this doesn't happen when I get rid of my vimrc so clearly something else is affecting that, but would you happen to know off the top of your head why something would cause it to blink??  I know I can just turn off blinking in iTerm, more just curious.

**Comment by junegunn** [comment]
I'm not sure about blinking, but the backslashes turned out to be a bug of Vim plugin of fzf. Please update the main fzf repo and see if it helps.

**Comment by sodapopcan** [comment]
haha, sorrrrry.  I've updated every few days for the past several weeks and it still stuck around.  Of course the one thing I didn't do was update one last time before I reported this bug.  All good now.

**Comment by junegunn** [comment]
yo, I fixed the backslash issue after seeing your report.

**Comment by sodapopcan** [comment]
Ohhh, haha, I misread.  Thank you very much!
