### ISSUE TITLE
Recommended Way for Combining Several Sources

### ISSUE THREAD

**Issue by hyiltiz** [junegunn/fzf.vim#31]
Given the super powers of `fzf` and your helper configurations here, it would be so great if one could easily combine several relevant sources, for example:

Is it possible to easily filter using `fzf` the outputs from `Buffers`, `History` (this includes buffers already) and `Files`?

**Comment by junegunn** [comment]
That's an interesting idea, but the code in this repo was not written with that in mind, for one thing, most source and sink functions are script-local. Making them public and "combinable" is a big thing and would require some careful design and consideration. (Once the decision is made, it's not easy to take it back) I'll think about it but note that it's not my priority.

You can fork the repo or simply copy the code and try writing your own combined source and sink functions. It should be doable if you know some vimscript.

**Comment by hyiltiz** [comment]
So you are implying that no change to the original go code is necessary for this? That is good. But I know almost nothing about vimscript, so I am afraid if a simple copy-paste lines of code from a to b does not solve this issue, then it is beyond my ability.

**Comment by junegunn** [comment]
> So you are implying that no change to the original go code is necessary for this? 

Correct. It's up to users to provide the right input and to do something with the filtered output.

>  I am afraid if a simple copy-paste lines of code from a to b does not solve this issue

Unfortunately, that's also true. You'll have to know how to handle concat several lists. Each item has to be prepended (or appended) with the name/identifier of the source, so that the sink function can decide which action to take with the selected item.

**Comment by sdhull** [comment]
FWIW I desperately want this as well. Having the buffers prepended to the normal fzf list would be just the coolest thing and improve my workflow a lot. I'm not familiar with vimscript nor do I have the time to devote to becoming familiar with it so I guess I'm out of luck as well. But here's to hoping someone with vimscript skills & similar desires stumbles on this issue and decides to tackle it 🤞
