### ISSUE TITLE
Restore cursor position after exiting fzf buffer

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#310]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I use `fzf.vim` with `let g:fzf_layout = { 'window': 'enew'}` layout. When I close fzf window with either `<esc>` or `<c-c>`, cursor position is not preserved, it gets moved to first column.
Is it possible to fix this minor issue?

**Comment by junegunn** [comment]
`set nostartofline`?

**Comment by yevhen-m** [comment]
@junegunn thanks, it works. I overlooked that I had this option on.
