### ISSUE TITLE
g:fzf_*_options for other commands (to allow for more preview)

### ISSUE THREAD

**Issue by jystic** [junegunn/fzf.vim#311]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I have set up a preview for `:Files` using `g:fzf_files_options` and it works really well. It would be great to be able to do the same for `:Buffers`, `:History` and other commands.

**Comment by junegunn** [comment]
You are advised to use autoload functions with extra options to redefine the commands.

For example:

```vim
command! -bang -nargs=? -complete=buffer Buffers
  \ call fzf#vim#buffers(<q-args>, {'options': '--color bw'}, <bang>0)

command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>, fzf#vim#with_preview('right'), <bang>0)
```

It's more verbose and you may have to read the source code, but it's much more flexible than `g:` variables.

**Comment by jystic** [comment]
Thanks! Verbosity is no problem, this is perfect
