### ISSUE TITLE
how to use fzf.vim to open the file which matches the word under cursor, in a split window?

### ISSUE THREAD

**Issue by githubfun** [junegunn/fzf.vim#312]
Often in java projects, the cursor is on a class name, ClassExample, I need quickly jump to the ClassExample.java. I do :Files commands to find the file, but I am sure there is something better. Thanks!

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

<!--

Before submitting
=================

- Make sure that you have the latest version of fzf and fzf.vim
- Check if your problem is reproducible with a minimal configuration

Start Vim with a minimal configuration
======================================

vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/

**Comment by junegunn** [comment]
Use `:Ag` command, preferably with a mapping like follows.

```vim
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
```

Press CTRL-X / CTRL-V / CTRL-T as in other commands to open the file in different ways.
