### ISSUE TITLE
:Blines prompt always on top

### ISSUE THREAD

**Issue by jameshenr** [junegunn/fzf.vim#314]
- Category
    - [X ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ X] Vim
    - [ ] Neovim

:BLines always seem to open the cursor on bottom of the lines.
![b1](https://cloud.githubusercontent.com/assets/25848908/23073373/9ab6b4f0-f535-11e6-9ac5-f48ec1007f9a.jpg)

Other commands open them below
![o](https://cloud.githubusercontent.com/assets/25848908/23073376/9d56a6de-f535-11e6-85e7-e0896b11da74.jpg)

Is there a way to make :Blines open the prompt at the bottom ?

**Comment by junegunn** [comment]
`BLines` and `BTags` use `--reverse` layout to show entries in the original order (top to bottom), but I can understand that it can feel inconsistent. You can redefine the command using the autoload function like so:

```vim
command! -bang -nargs=* BLines call fzf#vim#buffer_lines(<q-args>, {'options': '--no-reverse'}, <bang>0)
command! -bang -nargs=* BTags  call fzf#vim#buffer_tags(<q-args>, {'options': '--no-reverse'}, <bang>0)
```

(Make sure to update fzf.vim, I just fixed an issue with BTags)
