### ISSUE TITLE
A way to pass PATH to the Ag command

### ISSUE THREAD

**Issue by Asdas91** [junegunn/fzf.vim#316]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hi, is there a way to supply a path to the _Ag_ command like it can be supplied for the _Files_ command?
I am trying to find out myself by reading the code but I am not very good at vimscript.

If the thing I am asking was possible it would be very cool since I usually need to grep/ag the whole project or repo. I used to use denite for this but it is very slow for big repos so I switched to fzf.

**Comment by junegunn** [comment]
> grep/ag the whole project or repo

What you can easily do is `:cd` into the root directory of the repo, then do `:Ag` from there. I usually stay in the root directory the whole time, so it works for me.

But if you use `set autochdir` or like constantly changing working directory, then you can consider redefining `:Ag` or defining a new command using `fzf#vim#ag_raw` function, so you can write `:Ag PATTERN DIR`.

```vim
command! -bang -nargs=+ -complete=dir Ag call fzf#vim#ag_raw(<q-args>, <bang>0)
```

**Comment by Asdas91** [comment]
I see, I actually had no idea that autochdir existed and one could easily turn it off. I just thought that it was a default vim behavior. Thank you for such a fast answer:)
