### ISSUE TITLE
fzf_layout --reverse option shows escape characters from Ag

### ISSUE THREAD

**Issue by NiGhTTraX** [junegunn/fzf.vim#317]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

![image](https://cloud.githubusercontent.com/assets/485061/23155105/69ef05c8-f811-11e6-9c27-1f549b1b3fae.png)

Removing the `--reverse` options displays the search results correctly, but from the bottom to the top. I want that option to make fzf in vim consistent with fzf in the shell.

![image](https://cloud.githubusercontent.com/assets/485061/23155150/a6d61a9e-f811-11e6-92ae-cbedf058f276.png)

**Comment by junegunn** [comment]
Well, `g:fzf_layout` was not designed to hold `options` entry. Allowed keys are `up`, `down`, `left`, `right`, and `window` (for Neovim).

How about using `$FZF_DEFAULT_OPTS` instead? You can do it either in your shell configuration or in Vim configuration.

```vim
let $FZF_DEFAULT_OPTS = '--reverse'
```

**Comment by NiGhTTraX** [comment]
Awesome! Works like a charm. Thank you very much!
