### ISSUE TITLE
Can I fuzzy find wildmenu/autocomplete options?

### ISSUE THREAD

**Issue by alcesleo** [junegunn/fzf.vim#318]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
- Vim
    - [x] Vim
    - [ ] Neovim

Thank you for a fantastic plugin! I'm wondering whether it's possible to use FZF instead of wildmenu/autocomplete - specifically I'm looking to emulate [Helm](https://github.com/emacs-helm/helm)-like behaviour to quickly find the right `:` command. With wildmenu you can press `:<Tab>` and scroll through all possible commands, which is not realistic to do, but with fzf it would actually be really great. Grateful for any feedback :)

**Comment by noahfrederick** [comment]
Have you looked at [the documentation](https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt)? See `:help fzf-vim-commands` and `:help fzf-vim-mappings`.

**Comment by alcesleo** [comment]
D'oh! Was totally searching for the wrong word! Thanks!

**Comment by dbarnett** [comment]
Er, I had the same question about a "wildmode=fzf" workalike and I'm not actually seeing an answer in the help no matter how many times I reread `fzf-vim-commands` and `fzf-vim-mappings`.

For example, I'd want to be able to do:
```vim
:set <Tab>
```
and have a fuzzy-findable listing of available settings. `:set` is just an example; I'm asking about `:cmap`, wildmode, etc. and not about providing yet another standalone command for browsing settings.

**Comment by junegunn** [comment]
I don't think it's possible but patches are welcome if you can find a way to implement it.

**Comment by ayberkydn** [comment]
I think that would be a killer feature for who implements it. I am surprised that I could not be able to find any tool for that.

**Comment by pinpox** [comment]
+1 for this. Pressing <tab> while completing some command like `:set <tab>` or a filepath completion like `:e <tab>` would be great! The additional mappings like `:GFiles` and so on are great, but being able to use it everywhere would be awesome.

**Comment by z0xyz** [comment]
I guess wilder is the only viable option right now! I really didn't to not include any additional plugins especially for fuzzy finding, but there isn't an integrated option with this one.

**Comment by adigitoleo** [comment]
Quite hacky, but this can actually be done (in neovim, for vim8 probably switch `nvim_input` to `feedkeys` or something). Have been using something like this in my config for a while now. This code contains some personal choices (and probbly bugs), please adapt/review before using. I'm currently trying to work out how to port it to lua, but it's a bit painful.

![fuzzycmd](https://github.com/junegunn/fzf.vim/assets/34595875/2f95f7f5-16b6-47a0-9c8b-137f185c3bc8)

```vim
function! s:CmdFeed() abort
    " Get shell command to generate list of (almost) all *vim commands.
    let l:cmdlist = []

    " Get builtin commands from help index (extra arg bypasses wildignore).
    let l:help = expand('$VIMRUNTIME/doc/index.txt', 1)
    for l:line in readfile(l:help)
        if l:line =~ '^|:ex|'  " Exclude redundant and confusing legacy :ex cmd
            continue
        elseif l:line =~ '^|:grep|'  " Exclude braindead :grep (why u no :copen?)
            continue
        elseif l:line =~ '^|:\w\+|'  " Exclude 'special' commands like :! or :/
            let l:cmdlist += [matchstr(l:line, '^|:\zs\w\+\ze|')]
        endif
    endfor

    " Get user/plugin defined commands from `:command`.
    let l:com = split(execute('command'), '\n')[2:]
    for l:line in l:com
        if l:line =~ '^.\{4}\w\+'
            let l:cmdlist += [matchstr(l:line, '^.\{4}\zs\w\+\ze')]
        endif
    endfor
    " Return as shell command to allow async streaming into fzf.
    return has('win32') ? l:cmdlist : 'echo -e "' .. join(l:cmdlist, '\n') .. '"'
endfunction

function! s:FuzzyCmd_accept(fzf_out)
    if len(a:fzf_out) < 2 | return | endif
    let l:query = a:fzf_out[0]
    let l:key = a:fzf_out[1]
    let l:completion = get(a:fzf_out, 2, '')

    if empty(l:key)
        call nvim_input(':' .. l:completion .. '<Cr>')
    elseif l:key ==# ';'
        call nvim_input(':' .. l:query .. '')
    elseif l:key ==# 'space'
        call nvim_input(':' .. l:completion .. ' ')
    else
        call nvim_input(':' .. l:completion .. l:key .. ' ')
    endif
endfunction

command! FuzzyCmd
            \ call fzf#run({
            \   'source': s:CmdFeed(),
            \   'sink*': function('s:FuzzyCmd_accept'),
            \   'window': {
            \       'width': 1, 'height': 0.4, 'xoffset': 0, 'yoffset': 1,
            \       'border': 'top', 'highlight': 'StatusLine',
            \   },
            \   'options': [
            \       '--no-multi',
            \       '--print-query',
            \       '--prompt', ':',
            \       '--color', 'prompt:-1',
            \       '--expect', ';,space,!,|',
            \       '--layout', 'reverse-list',
            \   ]
            \})
```

**Comment by adigitoleo** [comment]
Implementation to get all commands in lua:

```lua
function list_commands()
    local cmdlist = {}
    for _, line in pairs(fn.readfile(fn.expand('$VIMRUNTIME/doc/index.txt', 1))) do
        local match = line:match("^|:(%w+)|")
        if match then table.insert(cmdlist, match) end
    end

    -- Get user/plugin defined commands from `:command`.
    local com = fn.split(fn.execute("command"), "\\n")
    table.remove(com, 1) -- Header line, just says 'command:'.
    table.remove(com, 2) -- Column headers.
    for _, line in pairs(com) do
        local match = line:match("^%s%s%s%s(%w+)%s")
        if match then table.insert(cmdlist, match) end
    end
    return cmdlist  -- Or table.concat(cmdlist, "\\n") to feed to fzf.
end
```
