### ISSUE TITLE
Fzf breaks `tcd` setting

### ISSUE THREAD

**Issue by hkupty** [junegunn/fzf.vim#319]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

Using fzf to open a file messes with `tcd` setting.
Setting a tab-local directory on two tabs and using fzf.vim to change file will mess remove tcd setting by setting it globally with cd instead of tcd.

**Comment by junegunn** [comment]
We use `lcd` instead of `cd` and I can't reproduce the problem.

```vim
nvim +'tcd /tmp' +tabnew +'tcd /usr' +'Files /bin'
```

**Comment by hkupty** [comment]
To reproduce the error, run `Files` on both tabs... They should be pointing to the same directory.

**Comment by junegunn** [comment]
Please provide the exact command that can be used to reproduce the problem like I did above.

**Comment by hkupty** [comment]
When trying to reproduce the error here for proper detailing, it seems the error only happens on git directories..
Here's how to reproduce:
```vim
tcd /opt/code/dir-1 "git directory
tabnew
tcd /opt/code/dir-2 "also a git directory
tabprev
Files
tabprev
Files
tabprev
pwd "now points to /opt/code/dir-2
```

**Comment by junegunn** [comment]
No, I can't reproduce. Make sure that you can reproduce without any other plugins and settings.

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)
```

**Comment by hkupty** [comment]
I found the offending plugin, which has nothing to do with fzf (ludovicchabant/vim-gutentags#117). Sorry for the inconvenience.

**Comment by codeinabox** [comment]
I am having this very problem myself but I don't have vim-gutentags installed
