### ISSUE TITLE
Statusbar background color

### ISSUE THREAD

**Issue by rainerborene** [junegunn/fzf.vim#32]
How do I change the background color of the status bar?

![fzf](https://cloud.githubusercontent.com/assets/101501/10833359/74b4ade6-7e78-11e5-83b8-da3b1b1bb19e.jpg)

By the way, I have just removed `ack.vim` and `ctrlp.vim` plugins. Now I am using `fzf.vim`. Keep the good work!

**Comment by junegunn** [comment]
Currently it's not easily configurable. I'll see what I can do and let you know.

**Comment by junegunn** [comment]
Update both fzf and fzf.vim and follow the instruction here: https://github.com/junegunn/fzf.vim#status-line-neovim
