### ISSUE TITLE
FZF.vim can not be integrated with Ag

### ISSUE THREAD

**Issue by kkurni** [junegunn/fzf.vim#320]
- Category
    - [ X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ X] Vim
    - [ ] Neovim

I have ag.vim setup.
but when i type :Ag, it doesn't integrated with FZF.

How to make this integrated with FZF ? is there any config that I need to override ?

Thanks

**Comment by junegunn** [comment]
I don't use ag.vim. If you don't have a specific reason to use the plugin, just remove it and fzf.vim will define its own Ag command.
