### ISSUE TITLE
FZF and 'autochdir'/'autocmd lcd' aren't playing nice

### ISSUE THREAD

**Issue by fluffywaffles** [junegunn/fzf.vim#321]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

You may be getting tired of all these complaints about `autochdir` and `lcd %:p:h`, but I, too, am having trouble convincing FZF to do "the right thing" when my working directory is involved, and hopefully I can give you enough information you can figure it out! I sure can't.

Here's the minimal configuration:

```vim

function! AutoLcd()
  echom "getcwd() " . getcwd()
  echom "autolcd " . bufname("") . " ... " . expand('%:p:h')
  lcd %:p:h
endfunction
autocmd BufEnter * call AutoLcd()

function! s:fzf_gitag(...)
  silent let git_project_dir = systemlist('git rev-parse --show-toplevel')[0]
  exe "lcd " . git_project_dir
  call call('fzf#vim#ag', a:000)
endfunction
command! -bang -nargs=* GitAg call s:fzf_gitag(<q-args>, <bang>0)

```

Using FZF, I can :GFiles and jump around a bit... for instance, given the following files:

```
a/
|_ b/
|   |_ c    "This is file c."
|   |_ d    "This is file d."
|_ e/
    |_ f    "This is file f."
    |_ g    "This is file g."
```

I can open neovim, then :GFiles and jump to `a/b/c`, let's say. Then, I can :GitAg, search for "file f," find it, and hit enter to jump to `a/e/f`. I'll get a blank buffer.

Now, comment out the third line of "AutoLcd()". Perform the same steps. It'll all work as intended. But now the working directory is, of course, wrong.

I had thought the issue was caused by `lcd`-ing into the FZF buffer, because my logging showed that I was, indeed, `lcd`-ing into a buffer with no name whenever I used :GitAg. This does not appear to be the case. I can avoid this by adding `if bufname("") != "" (etc) endif` inside of `AutoLcd()`, and it makes no difference to the behavior.

What *is* very interesting to me, and smells like a likely suspect for the source of the bug, is that it looks like `AutoLcd()` is getting called again when the FZF split closes on the buffer from which I opened the FZF split. Which means, the cwd is getting changed before my new buffer gets opened... and I don't know how to stop it from doing that.

Another frustrating thing: my cwd doesn't update when opening a new buffer from :GFiles. It remains the same. Once I leave the buffer and re-enter it, the cwd gets set to the correct value. What's frustrating is, from the logging I do, I can tell that my autocmd gets called twice: first when FZF opens the buffer for me, and again when I leave and re-enter it. Only in the second case does the `lcd` appear to have the intended effect.

Thanks in advance for looking into this.

Jordan

---

Side note:

I had originally tried passing 'dir' into `fzf#vim#ag`, but this got me nowhere. If there's a way to do this without using `lcd` inside of the body of `s:fzf_gitag`, I am open to it, because perhaps that could help? Here is what I tried, but it still did not work correctly:

```vim
function! s:fzf_gitag(...)
  silent let git_project_dir = systemlist('git rev-parse --show-toplevel')[0]
  call call('fzf#vim#ag', a:000, { 'dir': git_project_dir })
endfunction
```

**Comment by junegunn** [comment]
Try this:

```vim
command! -bang -nargs=* GitAg
  \ call fzf#vim#ag(<q-args>, {'dir': systemlist('git rev-parse --show-toplevel')[0]}, <bang>0)
```

**Comment by fluffywaffles** [comment]
That worked perfectly, thank you.

**Comment by fluffywaffles** [comment]
If you don't mind my asking:

Why didn't this work? If I manually did the same thing as my AutoLcd autocmd, everything would be fine. Is there some kind of... directory changing race condition at play here, where if I change directories later than FZF would internally, things break?

**Comment by junegunn** [comment]
When fzf window is closed, the cursor immediately enters the previous window which triggers your autocmd and it affects the subsequent actions fzf has to perform. When you pass `dir` to `fzf#run`, it ensures that the actions are performed in the specified directory.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/commit/cd59e5d07b3a69a75f7c0d02efd66b6f04bb13a1#diff-24d9d57e35df5afce7890f2400917919
