### ISSUE TITLE
fzf#vim#grep folder to search as last param 

### ISSUE THREAD

**Issue by neeraavi** [junegunn/fzf.vim#322]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ x] Vim
    - [ ] Neovim

I would like to pass the folder name (eg: src/) to ripgrep as the last parameter.
How should I change my command below to achieve this ?

`command! -bang -nargs=* G call fzf#vim#grep('rg --column --line-number --no-heading  '.shellescape(<q-args>), 1, <bang>0)`

**Comment by neeraavi** [comment]
Usecase: 
I want a keymap to search only in source folders(or project1) and another to search only in unittests(or project2). Currently, I don't know how I can pass the folder name as  aparam to ripgrep through fzf.

**Comment by junegunn** [comment]
You can remove `shellescape` so that you can type in raw arguments to rg.

**Comment by neeraavi** [comment]
command! -bang -nargs=* S call fzf#vim#grep('rg --column  '.shellescape(<q-args>). ' /tmp/vim' , 1, <bang>0)
command! -bang -nargs=* T call fzf#vim#grep('rg --column  '.shellescape(<q-args>). ' /tmp/vim/src' , 1, <bang>0)
