### ISSUE TITLE
cannot check the mappings

### ISSUE THREAD

**Issue by imsuwj** [junegunn/fzf.vim#324]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 14 2017 10:57:50)

![screenshot_20170226_133934](https://cloud.githubusercontent.com/assets/2463831/23337450/17e71aba-fc29-11e6-9f54-7c2f17b25e41.png)

When i using command `:Maps`,it shows me `recently modified /usr/share/vim/vim80/plugin/netrwPlugin.vim`

**Comment by imsuwj** [comment]
And i found it is related to the locale

this is the locale in KDE,Chinese interface
```
LANG=zh_CN.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

Then if set them to `en_US.UTF-8`, the mappings seems normal
```
LANG=en_US.UTF-8`
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8`"
...
```

**Comment by imsuwj** [comment]
But i run `echo $LANG` in vim : `en_US`

**Comment by junegunn** [comment]
Hmm, maybe it's because Maps command parses the output of `verbose nmap`. It looks for `Last set from ...`.

```
n  <Space>ag   * :Ag <C-R><C-W><CR>
        Last set from ~/.vimrc
n  <Space><CR> * :Buffers<CR>
        Last set from ~/.vimrc
```

I guess `Last set from` is printed in Chinese in your case?

**Comment by imsuwj** [comment]
@junegunn yes, then how to solve it

**Comment by junegunn** [comment]
Actually, I have no idea. It looks like it's not possible to dynamically change the locale of the current Vim process.
