### ISSUE TITLE
Background color not set correctly

### ISSUE THREAD

**Issue by neeraavi** [junegunn/fzf.vim#325]
- Category
    - [ ] Question
    - [ x] Bug
    - [ ] Suggestion
- OS
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x ] Vim
    - [ ] Neovim

With fzf :Tags, I notice this problem when there are only a few search results which does not fill the fzf split window height.
![image](https://cloud.githubusercontent.com/assets/4509266/23372161/c7b95196-fd1a-11e6-99ad-5bd0cdcbb596.png)

When there are enough entries, the problem is only seen at the borders.
![image](https://cloud.githubusercontent.com/assets/4509266/23372199/f0e3c2c2-fd1a-11e6-8f4c-5f5b5412eb19.png)

**Comment by junegunn** [comment]
Do you have the same issue outside of Vim?

**Comment by neeraavi** [comment]
No. This is only within vim, and only on together with fzf. 
I also checked similar issue described by https://sunaku.github.io/vim-256color-bce.html.
I have also tried setting "set t_ut=" as described in the above page. Still the problem is present.

**Comment by junegunn** [comment]
Do you have `g:fzf_colors` set?

**Comment by neeraavi** [comment]
No

**Comment by junegunn** [comment]
Actually I was not suggesting that you should have the option set up. fzf should display correctly regardless of it.

I found out what's happening.
- Your vim color scheme has a different background color than your terminal.
- fzf does not clear the whole screen.

I'll see what I can do.

**Comment by neeraavi** [comment]
Thanks for the fix!
