### ISSUE TITLE
Don't open files in specific buffers - NERDtree / Neovim Terminal etc

### ISSUE THREAD

**Issue by brodock** [junegunn/fzf.vim#326]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Ctrlp excludes a few buffers from being the target of opening files, and I think we should do something similar.

A user case:
* As a user my current buffer is NERDTree
* I hit :Files and try to open a specific one
* It is opened on current buffer which is not desired

https://github.com/ctrlpvim/ctrlp.vim/issues/136#issuecomment-270199579 may give some ideas how to deal with it. One note is NERDTree buffer name is "NERD" not 'nofile'

**Comment by junegunn** [comment]
I agree that it's desirable that we don't open files in special sidebar buffers like NERDtree or Tagbar. However, maintaining a list of heuristics for determining which buffer to avoid can be very tedious.
- We don't want to update fzf.vim whenever there's a new plugin
- The code will cease to work when the author of NERDtree decides to change the name of the buffer for some reason. There's no standard API that is universally agreed upon.
- We may not always want to avoid NERDtree buffer. For example, when we're not using it as a sticky sidebar. e.g. `:split .`

For the reasons, I would leave that decision up to the users for now.
FYI, I use the following mapping.

```vim
nnoremap <silent> <expr> <Leader><Leader> (expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '').":Files\<cr>"
```

**Comment by brodock** [comment]
@junegunn I agree, can I suggest to have a configurable list of buffers that are empty by default, but the "heuristic" is hidden by the user, so they can configure all the names in a simple `g:fzf_nosplit` global variable?

**Comment by junegunn** [comment]
I'll think about it. For now, you can do it yourself using some Vim script.

**Comment by izelnakri** [comment]
@junegunn can you reopen this? There are no changes to this behavior yet and it affects many people I think: https://github.com/junegunn/fzf/issues/453
