### ISSUE TITLE
Ansi output in different cases

### ISSUE THREAD

**Issue by dekz** [junegunn/fzf.vim#327]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

## :Files
<img width="700" alt="screen shot 2017-03-02 at 2 38 36 pm" src="https://cloud.githubusercontent.com/assets/27389/23491999/0325e5b8-ff56-11e6-9bed-32ee75459331.png">

## :Buffers

<img width="700" alt="screen shot 2017-03-02 at 2 38 47 pm" src="https://cloud.githubusercontent.com/assets/27389/23492001/0a021c58-ff56-11e6-8dd7-1bd56d5a4121.png">

The output is now coloured and works ok

## :Buffers (Unsupported Ansi)
<img width="700" alt="screen shot 2017-03-02 at 2 40 05 pm" src="https://cloud.githubusercontent.com/assets/27389/23492030/2be3aecc-ff56-11e6-941a-949ebde5df04.png">

Some how I've made ANSI unsupported in my Neovim configuration (since a clean Install works fine using your example in the Github Issue Template)

Is there a global way to disable ansi, :Files seems fine, but :Buffers uses ansi.

**Comment by junegunn** [comment]
`export FZF_DEFAULT_OPTS='--no-color'` should help, although even with the option the current version of fzf does not suppress colored text in the preview window, which should be fixed in the upcoming release.

**Comment by dekz** [comment]
```
λ env | grep FZF
FZF_DEFAULT_OPTS=--no-color
λ env | grep COLOR
λ echo $TERM
xterm
```

<img width="637" alt="screen shot 2017-03-02 at 2 48 04 pm" src="https://cloud.githubusercontent.com/assets/27389/23492226/4a717364-ff57-11e6-9432-d06ae81cff96.png">

**Comment by junegunn** [comment]
Did you properly export the variable?

**Comment by junegunn** [comment]
Works for me fine. The issue I mentioned regarding the preview window will be fixed in the next version.

https://github.com/junegunn/fzf/commit/972fb1a29ddd484c97342cf0e7399bd904ded58d

**Comment by dekz** [comment]
Yep

I've attached an asciicast recording.  

[![asciicast](https://asciinema.org/a/aj1mk1kegivyz8afe02xmeyyi.png)](https://asciinema.org/a/aj1mk1kegivyz8afe02xmeyyi)

**Comment by junegunn** [comment]
I'm pretty sure it's a configuration issue.

**Comment by dekz** [comment]
I am able to reproduce this in a Docker container with Bash + Neovim and only FZF and FZF.vim installed as plugins.

fzf version: 16.5

It is related to setting fzf_options in vimrc. 

```
let g:fzf_layout = { 'up': '~25%', 'options': '--reverse' }
```

Here is an asciicast with the options set and then unset, with the behaviour changing.

[![asciicast](https://asciinema.org/a/6kzkgeitl9guptplqhwkgg17g.png)](https://asciinema.org/a/6kzkgeitl9guptplqhwkgg17g)

**Comment by dekz** [comment]
I now realise adding --ansi to options

```
let g:fzf_layout = { 'up': '~25%', 'options': '--reverse --ansi' }
```

Enables it to display properly for me in this case.

Thanks for your work @junegunn

**Comment by junegunn** [comment]
Oh, you are not supposed to have `options` in `g:fzf_layout`. And that's the reason it's not working as expected. The `options` entry in `g:fzf_layout` overrides the correct set of options used by `:Buffers` command. I'm gonna make fzf throw an error if it's incorrectly used. Is there any blog post that suggests doing so? This seems to be a recurring mistake. https://github.com/junegunn/fzf.vim/issues/317#issuecomment-281287381

**Comment by dekz** [comment]
Ah it could have been, or from someone else's github profile. I'll have a dig around. 

My config had not changed in 6+ months, but I recently upgraded fzf.

I'll use the `let $FZF_DEFAULT_OPTS = '--reverse'` from now on. Thanks!
