### ISSUE TITLE
quotes in query string on Windows

### ISSUE THREAD

**Issue by wontoncc** [junegunn/fzf.vim#328]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Quotes appear in the query string while running `:Lines` or `:Buffers`. Looking into `autoload/fzf/vim.vim` and found that the query string is qutoted with `'` which will fail in Windows. And I added some code the to let the plugin know I'm on Windows and go for `"`:

``` vim
" autoload/fzf/vim.vim

function! s:q1(str)
  if has('windows')
    return '"'.substitute(a:str, '"', '\\\"', 'g').'"'
  endif
  return "'".substitute(a:str, "'"", "'\\\\''", 'g')."'"
endfunction
```

BUT this is such a preliminary workaround that will cause error in some cases like escaped `"` in double-quotes in the querystring (eg. `"test\""`). And I'm afarid there is more but I've not tested much. Maybe we can work on a safer way to quote the query string on Windows, any thoughts?

**Comment by junegunn** [comment]
Maybe we should just use shellescape? Does this work on Windows?

```vim
function! s:q1(str)
  return shellescape(a:str)
endfunction
```

I'm not quite sure why I chose not to use shellescape.

**Comment by wontoncc** [comment]
Ah, I forgot about it. I just did a few test and found `"test\""` or `"test""` fails in a different way. Unlike the workaround I provided which causes `fzf`'s exiting with error in these cases, the `shellescape` way causes the latter quote mismatched and thus other command line arguments will be counted as part of query string:

>   _:Lines test"_
>   Lines> "test --expect=ctrl-v,ctrl-x,ctrl-t

A bit friendlier than just exiting silently, giving a hint to the user. /s

Or just let it be and our users may turn to type the complex search pattern in the `fzf` rather than as a Vim command argument?

**Comment by junegunn** [comment]
So `shellescape` works better in general than the current code except for a few edge cases, right? I'll change the code to use `shellescape` then.

FYI, the examples you gave also work fine on my macbook, it seems like an issue of windows platform. Honestly, I haven't paid any attention to Windows as I'm not a Windows user myself, and I didn't expect fzf.vim to work on Windows at all!

**Comment by junegunn** [comment]
Although the fix is not perfect, I'll close this at this point, as I don't think I can come up with a better solution. Thanks.
