### ISSUE TITLE
Running :Tags matches on function bodies

### ISSUE THREAD

**Issue by darthdeus** [junegunn/fzf.vim#329]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm not sure if this is a problem of the project I'm working on, but I've found that in JS projects the `:Tags` command is very difficult to use since it matches on function bodies.

Another somewhat related issue is that as it matches further to the right, it also shows the portion of the string on which it is matching ... which is great in many cases, but if the ctags line is longer than what can fit on the screen, I can no longer see which tag do I currently have selected.

**Comment by junegunn** [comment]
You can limit the search scope by passing `--nth` option.

```vim
command! -bang -nargs=* Tags call fzf#vim#tags(<q-args>, {'options': '--nth 1'}, <bang>0)
```

**Comment by junegunn** [comment]
FYI, I updated Tags command to use the option by default, so you no longer have to override it.
