### ISSUE TITLE
"fzf" bottom bar colors off

### ISSUE THREAD

**Issue by zackhsi** [junegunn/fzf.vim#330]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi! I have configured fzf colors to [match my color scheme](https://github.com/zackhsi/dotfiles/commit/1e6ba68868628fa8881b3b12df95f74a3779842e). However, I am still seeing a color that does not normally appear. I am wondering if there is a configuration option I am missing?

<img width="730" alt="bottom bar color" src="https://cloud.githubusercontent.com/assets/806101/23665119/7196db56-030c-11e7-8a24-06f63dfe21d0.png">

In particular, the colors in the bar do not match my colorscheme. Any advice?

Thanks!

**Comment by junegunn** [comment]
See:
- https://github.com/junegunn/fzf/issues/861#issuecomment-282663944
- https://github.com/junegunn/fzf.vim#status-line-neovim
