### ISSUE TITLE
:Tags jump for current buffer behaviour bug ? 

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [junegunn/fzf.vim#331]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

i use `:Tags` as tag navigation, but I find `:Tags` can not jump to the tag which defined in current buffer, while `:BTags` can find it and jump to it. `:Tags` can find the tag, i can see the right result in fzf window, but when i press enter, the cursor does not move to the tag position. `:Tags` works fine for tags defined in other files.

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you can reproduce the problem with the following minimal setup?

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)
```

**Comment by FinallyFinancialFreedom** [comment]
sorry, it's my mistake. i can reproduce it with minimal setup,  but the problem is gone when i update the tags file.
