### ISSUE TITLE
No more fzf indexing window when using Ag?

### ISSUE THREAD

**Issue by yifanchen** [junegunn/fzf.vim#333]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

fzf: 0.16.6
fzf.vim: I don't know what version is, but I have run `:PlugUpdate'.

The question might be irrelevant here, but I haven't been able to find proper answers, so I thought  about just posting here, worth a shot. 

So, I used to be able to run `:Ag` with fzf.vim. When I ran it, there would be a window down at the bottom of my Neovim, starting indexing, then I could type any parameters. 

Now, the window doesn't open anymore. Instead, I have to type a parameter right after the `:Ag` command, otherwise it searches all the files in the current `dir`.

Any ideas what's going on?

Thank you.

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal init.vim?

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by yifanchen** [comment]
Just tried the minimal init.vim. It works fine.

**Comment by cosarara97** [comment]
I had a similar problem due to having ag.vim installed ( https://github.com/rking/ag.vim ).

**Comment by yifanchen** [comment]
@cosarara97 hmm, this issue is to fix `:Ag` command. So, yours works now when you disabled ag.vim?

**Comment by cosarara97** [comment]
I guess both plugins provide the same functionality and have some conflict.

**Comment by junegunn** [comment]
Yeah, fzf.vim does not define command if it already exists. Just uninstall ag.vim if you don't really have a reason to use it.

**Comment by yifanchen** [comment]
Good to know, thanks.
