### ISSUE TITLE
Preview window for Ag 

### ISSUE THREAD

**Issue by goozler** [junegunn/fzf.vim#334]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hi! First of all, thank you for plugins that changed my life! :heart:

About the problem, I use the `Ag` command with the hint [described in Readme](https://github.com/junegunn/fzf.vim/blob/master/README.md#advanced-customization) to show a preview window and it worked fine before [the last but one commit](https://github.com/junegunn/fzf.vim/commit/06a8b870c0ba6936935e4a57cc57c3b54d71b2a9). 
Now I have an error: `zsh:1: command not found: preview.sh`. 

As you can see I use zsh, maybe the problem related to it I don't know. A preview for the `Files` command with [these options](https://github.com/junegunn/fzf.vim#command-local-options) still works fine.

**Comment by junegunn** [comment]
Oops, there were missing parentheses. Should be fixed now. My system has Ruby installed, so the code path was never properly tested. Sorry for the troubles.

**Comment by junegunn** [comment]
Also, I would recommend using `fzf#vim#with_preview` for enabling preview window for Files command as well instead of manually building the underlying fzf options.

https://github.com/junegunn/fzf.vim/commit/2eaff049464e7b8304401dd4d79c86a4b0c4ed6c
