### ISSUE TITLE
[Neovim] Change cursor to underscore

### ISSUE THREAD

**Issue by nomasprime** [junegunn/fzf.vim#337]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi,

I've just change my cursor to underscore with cursor line set to underline—it's totally rad, you should try it.

It seems to work everywhere apart from where I trigger fzf, then I get the old block cursor.

I'm not sure if it's a setting I need to change or feature request.

Can someone help?

Thanks 🙂

**Comment by habitullence** [comment]
Looks like this might be a problem with NeoVim terminal mode.

**Comment by nomasprime** [comment]
Actually @junegunn I'm not sure if this is fzf or NeoVim, any ideas?

**Comment by junegunn** [comment]
Is it possible to customize the shape of the cursor on terminal buffer (`:term`) ?

**Comment by nomasprime** [comment]
Sorry for taking so long to reply @junegunn.

Looks like terminal implementation in NeoVim's the [issue](https://github.com/neovim/neovim/issues/2326).
