### ISSUE TITLE
Is there a way to change FZF prompt in vim when one is already opened?

### ISSUE THREAD

**Issue by ephemerr** [junegunn/fzf.vim#340]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I have tried following mappings without any success:
 
```
map <c-a> <Esc>:Ag<CR>
map <c-b> <Esc>:GGrep<CR>
```

**Comment by junegunn** [comment]
No, fzf is an external program that runs outside of Vim window so mappings in Vim do not apply. Theoretically, one can implement such switching with `--expect` option and custom sink functions, but the approach can't be directly applied to the commands this repository provides. I don't have a good answer at the moment but I'll think about it.
