### ISSUE TITLE
fzf#run with actions?

### ISSUE THREAD

**Issue by dragonxlwang** [junegunn/fzf.vim#342]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

This is just a suggestion (or maybe I was not understanding fzf)

I am using source in `fzf#run` to select a few directory to search. 

For example, I only want to narrow down my scope to directory `a, b, c`. I'd like to set `source` as `find a, b, c`

However, one thing that I don't like `fzf#run` is that it no longer work with `default_actions`. For example, by hitting `ctrl-x` it no longer splits anymore.

I wish that `fzf#run` can respect to `default_actions` without the need to manually define `sink`.

Thanks,

**Comment by junegunn** [comment]
See: https://github.com/junegunn/fzf#fzfwrap

**Comment by dragonxlwang** [comment]
That's neat! Thanks!
