### ISSUE TITLE
Disable sorting of Ag results

### ISSUE THREAD

**Issue by leemhenson** [junegunn/fzf.vim#343]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi. Sometimes when I'm doing text searching, I want to see the results sorted by file/line, as I would if I ran `ag` from the terminal. I can't see a way of doing this by configuring fzf.vim. To get the behaviour I want I've had to add an additional `--no-sort` option here:

https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L639

Is there a better way of doing this?

**Comment by leemhenson** [comment]
To clarify, the results are currently sorted by some other algorithm that mixes up files so you can't easily scan through the list to see hits in a particular dir. I've no idea what rules it's applying to sort it.

**Comment by junegunn** [comment]
You can override Ag command (or define another command) using` fzf#vim#ag` with additional options.

```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--no-sort'}, <bang>0)
```

**Comment by junegunn** [comment]
> as I would if I ran ag from the terminal

By the way, it's not clear to me why you can't just `:Ag SOME-PATTERN` and browse the result.

**Comment by leemhenson** [comment]
> By the way, it's not clear to me why you can't just :Ag SOME-PATTERN and browse the result.

Ah, but then I don't get to further filter the list like I can do with fzf. It turns out, your suggestion:

`command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--no-sort'}, <bang>0)`

_almost_ works. It definitely stops `fzf` sorting the `ag` results, but it turns out the `ag` results weren't ordered as I thought they were. Currently, it looks like the only way to get consistent alphabetically-sorted results from `ag` is to pass `--workers=1` like this:

`command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--workers=1', {'options': '--no-sort'}, <bang>0)`

Which I suppose would slow things down on a really big codebase, but it's fine for me.

**Comment by junegunn** [comment]
Cool, thanks for sharing.
