### ISSUE TITLE
Running `:Files ./` occsasionally changes `:pwd` to $HOME

### ISSUE THREAD

**Issue by darthdeus** [junegunn/fzf.vim#344]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm not really sure if this is a problem in fzf.vim itself, or if it's caused by some of my other vim plugins, but it seems to be somewhat timing related. *Sometimes* (around 20-50% of the time) when I run `:Files ./` and select a file, vim will open the file relative to the home directory, and subsequent `:pwd` is just what's in `$HOME`.

I'm not able to reproduce this with the minimal configuration, but at the same time I don't really know how to debug it with my own config, since the issue only manifests itself sometimes. Is is possible that this is an issue caused by `fzf.vim`? I'm using `FZF_DEFAULT_COMMAND='ag -g ""'` if that's of any relevance.

**Comment by junegunn** [comment]
> I'm not able to reproduce this with the minimal configuration

Well then it's not an issue of fzf.vim. You'll have to find the plugin or setting (such as autochdir) that is causing the problem.
