### ISSUE TITLE
Make :Ag not match file names, only the file content

### ISSUE THREAD

**Issue by maximbaz** [junegunn/fzf.vim#346]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Since there is a command `:Files` that can search files by name, I'd like to configure `:Ag` to only look at the file contents, not at the file names. 

I'll demostrate my case below, my question is: can this be achieved today, maybe with some configuration?

-----

To see why this is an annoying issue, create a file called `demo.txt`, put 20 lines each having a random number, and on the 21st line write `demo`. Then use `:Ag demo` to search for this string.

Expected: you find only one occurrence.
Actual: you also find 20 irrelevant occurrences.

![image](https://cloud.githubusercontent.com/assets/1177900/24205485/cdb60acc-0f1b-11e7-94d9-79c098e9b5ee.png)

**Comment by junegunn** [comment]
Try this:

```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

**Comment by maximbaz** [comment]
It looks like magic, but works beautifully, thanks @junegunn! 🎉

**Comment by mbylstra** [comment]
I'm trying to figure out how to run that command on startup. Any tips?

**Comment by backdoer** [comment]
Put it in your .vimrc @mbylstra

**Comment by mbylstra** [comment]
:man_facepalming: I thought I had to prepend it with `autocmd` which wasn't working.

**Comment by vadimshvetsov** [comment]
Is it possible to combine this with my current Ag tweaks?
I have the following:
```vim
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 {'options': '--delimiter : --nth 4..'}, " Can't add this
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)

```

**Comment by vadimshvetsov** [comment]
@junegunn could you please help, is it possible to combine preview options with search only by files with Ag?

**Comment by junegunn** [comment]
```
* fzf#vim#with_preview([[options], preview window, [toggle keys...]])
```

So you have to write

```vim
fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
```

**Comment by vadimshvetsov** [comment]
@junegunn Thank you so much, you've saved my day!

**Comment by jssee** [comment]
@junegunn i used the method you described above but im experiencing some strange behavior.

i want to have 2 options:
1. use the default `:Ag` behavior of searching all file names and content.
2. use Ag to only search the current file contents. 

Im noticing that with my current config, this only works some in some projects, but not others. and on occasion, it will only allow me to use option 2 _once_ in a project, and every time afterwards it goes back to the default behavior. do you have any idea why this is?

here is my config: 
```
nnoremap <Leader>sa :Ag<CR>
nnoremap <Leader>ss :Ag!<CR>

command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```

**Comment by 01abhishekjain** [comment]
> Try this:
> 
> ```viml
> command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
> ```

Thanks for this! Can anyone care to explain (briefly) what this exactly does?

**Comment by aos** [comment]
> > Try this:
> > ```viml
> > command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
> > ```
> 
> Thanks for this! Can anyone care to explain (briefly) what this exactly does?

Basically, the `{'options'...}` part is passed into `fzf`. If you look at the man page for `fzf`, you'll notice you can pass a delimiter to the results, in this case our delimiter is colon `:`. Then we tell it to only show us results from the 4th item onwards... in this case these are the file contents.

If you look at the results of `:Ag`, it uses `:` as the separator for each result.

**Comment by danamkaplan** [comment]
Can anyone help me write the equivalent for Ripgrep? This: 

```
command! -bang -nargs=* Rg call fzf#vim#rg(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
```
Gives me the error
`E117: Unkown function: fzf#vim#rg`

**Comment by fabiomcosta** [comment]
@danamkaplan `fzf#vim#rg` function doesn't exists, as the error message says, so you have to use the `fzf#vim#grep` function.

I got it working with the following command:
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

**Comment by fabiomcosta** [comment]
Oh just noticed this has also been suggested at https://github.com/junegunn/fzf.vim/issues/714#issuecomment-428802659

**Comment by avral** [comment]
Thank's!

**Comment by buschco** [comment]
> Try this:
> 
> ```viml
> command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
> ```

This made my Preview window. How can I bring it back with this options?
