### ISSUE TITLE
Mimic sublime text : and @ behaviour when fuzzy search

### ISSUE THREAD

**Issue by rawaludin** [junegunn/fzf.vim#347]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I learn this feature in sublime text and really love it. The feature goes like this:

1. Do fuzzy search.
2. While still in fuzzy search prompt and found my file, if I press `:` then type some number, preview window is updated to those number. If I press Enter, I open file with that exact line number position.
3. Same happen with `@`, except it will populate fuzzy search prompt with tag from selected file. So, when I found my file, I type `@` then I could fuzzy search tag from selected file. If I press Enter, I go to exact tag location on that file.

Here some picture of it:

<img width="796" alt="step1" src="https://cloud.githubusercontent.com/assets/1274849/24250435/79980a1e-1009-11e7-96a6-e648b2866c7a.png">

<img width="796" alt="step2" src="https://cloud.githubusercontent.com/assets/1274849/24250529/c3444466-1009-11e7-937e-f394f3426d2c.png">

<img width="796" alt="step3" src="https://cloud.githubusercontent.com/assets/1274849/24250557/e13422e8-1009-11e7-89c3-1e0ff7902b47.png">

<img width="796" alt="step4" src="https://cloud.githubusercontent.com/assets/1274849/24250598/08c95314-100a-11e7-9472-5c512cf65401.png">

Is this possible with fzf?

**Comment by junegunn** [comment]
No, it's not possible. fzf is just a unix filter that does not know the context of the search. Text in, text out, that's all it does. Though it would be possible to use `--expect @,:` option to chain several commands (for example, when `@` is pressed start `BTags` command) but it's not possible to dynamically switch the mode inside the same fzf instance like sublime does.

**Comment by FatBoyXPC** [comment]
> Though it would be possible to use --expect @,: option to chain several commands (for example, when @ is pressed start BTags command)

@junegunn, do you mean that once `@` is pressed, it would start looking in that file for tags? If so, as long as used the highlighted/selected file, this is totally fine if you could implement this! Currently I have to open a file then I use ctrlpFunky to get to the function I want!

**Comment by kristijanhusak** [comment]
Here's how i solved this:

```vimL
function! s:goto_def(lines) abort
  silent! exe 'e +BTags '.a:lines[0]
  call timer_start(10, {-> execute('startinsert') })
endfunction
function! s:goto_line(lines) abort
  silent! exe 'e '.a:lines[0]
  call timer_start(10, {-> feedkeys(':') })
endfunction

let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ '@': function('s:goto_def'),
  \ ':': function('s:goto_line')
  \  }
```
It's not exactly as sublime (changing in same instance), but it works in a similar way. If anyone knows the way to improve it (timer part is a bit hackish), let me know.

**Comment by FatBoyXPC** [comment]
So how does this work? Do you press some keys and it opens fzf file picker, then it will automatically load up the `BTags` after some time? This isn't quite what I wanted, unfortunately.

**Comment by kristijanhusak** [comment]
@FatBoyXPC you open up fzf with `:Files`, search for your file, once it get's matched, press `@`. It will load up your file and automatically open up fzf with the buffer tags selector `BTags`. Timer is needed to give it some time to load the fzf, to enter insert mode, since it leaves it in normal mode.

**Comment by FatBoyXPC** [comment]
Oh, neat! I didn't realize `fzf_action` was a thing! That's an interesting solution, I think I'll have to try it!

**Comment by FatBoyXPC** [comment]
That is a thing of beauty! Thank you so much!

**Comment by FatBoyXPC** [comment]
I thought this thing was working, but when I hit enter when `:BTags` opens up it doesn't actually go to that method. Any ideas?

**Comment by kristijanhusak** [comment]
Are you using vim or neovim?
I don't have that issue in neovim.

**Comment by FatBoyXPC** [comment]
Ah, yeah it works in neovim but not vim 8 :(

**Comment by kristijanhusak** [comment]
I don't really see a reason why it would not work. Try increasing timer to a bigger number, or remove timer completely, maybe it will work without it.

**Comment by FatBoyXPC** [comment]
I tried increasing the time to 30, it was noticeably slow and same behavior. I changed the timer value to 0, same behavior but not slow. I removed the timer and just put `execute('startinsert')` and that was slow but the same behavior. I also removed `execute('startinsert')` and it still went into insert mode, but exhibited the same behavior.

**Comment by kristijanhusak** [comment]
Yeah if you don't need the execute part, it definitely behaves differently. Maybe @junegunn can help?
