### ISSUE TITLE
Toggle selection

### ISSUE THREAD

**Issue by rainerborene** [junegunn/fzf.vim#35]
Only thing I miss from `ctrlp.vim` plugin is the toggle selection feature using `CTRL-Z`. Any chances to have that implemented?

**Comment by junegunn** [comment]
I don't know what you mean by that. Maybe it's related to shift-tab / tab keys in fzf that are for selecting multiple entries? (note that shift-tab currently does not work on neovim for some reason)

**Comment by rainerborene** [comment]
fzf does not provide a toggle selection feature, which means using the same keystroke to select and unselect current line.

**Comment by junegunn** [comment]
It is still not clear what you're trying to say. Have you tried `fzf -m` and pressing tab or shift-tab keys?

**Comment by rainerborene** [comment]
Instead of using `Shift-Tab` and `Tab` keys I'd like to use only one keystroke i.e. `C-Z` to select and deselect items (toggle) while keeping the cursor position on the same line. Is it clear now?

**Comment by junegunn** [comment]
Yes, see the `--bind` section of the man page.

**Comment by yevhen-m** [comment]
I use neovim (`shift-tab` doesn't work there). I've managed to fix that setting 
`export FZF_DEFAULT_OPTS='--bind=ctrl-z:toggle-up'`
@junegunn thanks for help.

**Comment by robinovitch61** [comment]
> it looks like there's no toggle-select

It's just called `toggle` it seems
```
   AVAILABLE ACTIONS:
       A key or an event can be bound to one or more of the following actions.

         ACTION:                      DEFAULT BINDINGS (NOTES):`
...
           toggle                       (right-click)
```
