### ISSUE TITLE
[question]Can `:Ag` do not close the window when choose an item?

### ISSUE THREAD

**Issue by jinleileiking** [junegunn/fzf.vim#351]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When  use `:Ag` to grep some lines, It will show a windows which has a lot of lines to choose.

When press enter to choose one line, the window will close.

My question is: can this window do not close automatically?

**Comment by junegunn** [comment]
No, it's not currently possible. fzf is not a native Vim plugin but an external program, so keeping it open and making it communicate with Vim requires extra effort. You can however, select multiple entries (tab, shift-tab, alt-a) to build quickfix list inside Vim.

**Comment by jinleileiking** [comment]
![qq20170515-202325](https://cloud.githubusercontent.com/assets/93968/26057456/5a1b1ac4-39ac-11e7-8f99-2f35a25b3274.jpg)

alt-a seem not work. mac

**Comment by junegunn** [comment]
@jinleileiking https://github.com/junegunn/fzf/search?utf8=%E2%9C%93&q=alt+iterm2&type=Issues

**Comment by jinleileiking** [comment]
thanks.
