### ISSUE TITLE
[question]Can `:Ag` omit some dir?

### ISSUE THREAD

**Issue by jinleileiking** [junegunn/fzf.vim#352]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Can `:Ag` omit some dir?

Not grep things in these dirs.

**Comment by junegunn** [comment]
It's up to ag. `man ag` to see how it can be done. If you need pass extra ag options, use `fzf#vim#ag` function. Examples can be found on the README page some issues.
