### ISSUE TITLE
History command with preview

### ISSUE THREAD

**Issue by meain** [junegunn/fzf.vim#353]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

How to get preview for `:History` like this example given for `:Files` in the readme.
![screenshot](http://i.imgur.com/jfsuO3E.png)

**Comment by junegunn** [comment]
Something like this should work.

```vim
command! -bang -nargs=* MRU call fzf#vim#history(fzf#vim#with_preview())
```

Note that I didn't choose to override `History` as it actually calls one of `fzf#vim#command_history`, `fzf#vim#search_history`, and `fzf#vim#history` depending on the arguments, and it's more complicaed.

**Comment by meain** [comment]
![](http://i64.tinypic.com/1ieh51.png)

Having this issue on linux, what could it be?

**Comment by meain** [comment]
ping @junegunn

**Comment by junegunn** [comment]
Honestly I'm not sure what's happening there and I can't reproduce the problem locally. Please let me know if you find out what's going on under the hood.
