### ISSUE TITLE
Error in macVIm

### ISSUE THREAD

**Issue by zhenyangze** [junegunn/fzf.vim#354]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim
    - [x] MacVim

When execute FZF,then it show:
Error running xterm -T "[fzf]" -bg "\#002b36" -fg "\#839496" -geometry 115x20+341+225 -e bash -ic '"/Users/yangze/.
fzf/bin/fzf" --history /Users/yangze/.local/share/fzf-history/FZF --color=bg+:8,spinner:14,hl:11,header:11,info:9,p
ointer:14,marker:14,prompt:14,hl+:14 --multi  --prompt '"'"'~/'"'"'  --expect=ctrl-v,ctrl-x > /var/folders/bs/y9pw9
_897yv38lbkqbq9w17r0000gn/T/vdIy96u/4'&& osascript -e "tell application \"MacVim\" to activate"

**Comment by junegunn** [comment]
Do you have xterm installed?

**Comment by zhenyangze** [comment]
no, i use iTerm2.

**Comment by zhenyangze** [comment]
two methods, either-or:
1. https://github.com/junegunn/fzf/wiki/On-MacVim-with-iTerm2
2. need to install http://xquartz.macosforge.org/landing/

**Comment by junegunn** [comment]
Yes, correct. Unfortunately fzf doesn't work nicely with GVim as it's an external program for terminal.
