### ISSUE TITLE
Is it possible to make run Ag in current dir?

### ISSUE THREAD

**Issue by yifanchen** [junegunn/fzf.vim#355]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible to make run `:Ag` in current dir?

Also, are there ways to overwrite Ag pane color?  i.e. My Ag pane color is different than fzf pane now.

**Comment by junegunn** [comment]
I don't follow. Ag runs in current directory by default.
For customizing the colors of ag output, refer to `man ag`.

**Comment by yifanchen** [comment]
Updated this morning, it searches in current directory now. Thanks.
