### ISSUE TITLE
Resume support - resume a window in same state

### ISSUE THREAD

**Issue by benbernard** [junegunn/fzf.vim#356]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Unite has a UniteResume feature, sorta discussed in this closed issue on fzf: https://github.com/junegunn/fzf.vim/issues/182

I used to run much of my unite-based workflow around the UniteResume feature, its different from search history.  The important part is that it would restore everything about the window (the current query, the command) most importantly it would restore the current cursor position (i.e. if I had navigated down several files, the cursor would start in the middle of the list).

This lead to a great workflow with a large number of changes / issues...

1. Do the search for a problem issue
2. Enter to open first result
3. Fix issue
4. use Resume to re-open unite
5. hit ctrl-j to drop down one line
6. Fix

Repeat steps 4-6 until you'd been through the whole list of files.

Search history gets us partially there, but without cursor restore it doesn't get the whole way.  Also as noticed in the prior issue, currently not a great way to re-open with the exact same things (have to re-trace steps exactly with like for instance what initial Ag query or directory to use)

Thanks for the great tool! Would love to have this workflow back, but I'm sure you're busy.

**Comment by junegunn** [comment]
fzf is a general-purpose, context-free unix filter for command-line and it's not easy, or even not possible, to provide the same level of integration with Vim as other native Vim plugins provide. Like, you can't pause and resume *grep* or *sed* and the situation with fzf is not very different.

Having said that, there have been related discussions on the issue and I have some ideas, but I haven't really had time to experiment with it. I'll let you know if there's any progress.

- https://github.com/junegunn/fzf/issues/887

Also, I would suggest that you keep Unite if it servers you better, this project was not meant to replace Unite.

**Comment by benbernard** [comment]
Totally get all of that :) thanks for the response.
