### ISSUE TITLE
fzf-complete-buffer-line doesn't work

### ISSUE THREAD

**Issue by pright** [junegunn/fzf.vim#357]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

```
imap <c-x><c-l> <plug>(fzf-complete-buffer-line)
```
Pressing ```<C-x><C-l>```, vim prompts
```
Error detected while processing function fzf#vim#complete#buffer_line:                   
line    1:                                                                               
E117: Unknown function: s:uniq  
```
I tried replacing ```s:uniq``` with ```uniq``` and all goes well.

**Comment by junegunn** [comment]
Yeah, it was a bug and fixed a few hours ago. Thanks.

https://github.com/junegunn/fzf.vim/commit/f3c3646c810968d9494e36c272d8d13ce312416d
