### ISSUE TITLE
Keyboard bindings for scrolling preview window?

### ISSUE THREAD

**Issue by tupton** [junegunn/fzf.vim#358]
The preview window is amazing! Scrolling it works fine with the mouse, but of course I'd like to scroll without taking my hands off of the keyboard. I looked but couldn't find any bindings for scrolling the preview window. Are there any?

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

**Comment by junegunn** [comment]
No default bindings for that. You'll have to set up your own bindings using `--bind` option.  See `man fzf` for details.

**Comment by tupton** [comment]
I found #211 which links to https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0152 which mentions bindable actions.

How do I use these actions?

**Comment by tupton** [comment]
Ah, thanks. That answered my question that I was typing while you responded.

**Comment by junegunn** [comment]
No problem. You can add something like `--bind up:preview-up,down:preview-down` to your `$FZF_DEFAULT_OPTS`.

**Comment by johnmiked15** [comment]
Hate to resurrect an old closed issue, but I think a recent commit broke the ability to scroll around the preview window: junegunn/fzf@f6b19620566a299d8813ee51e02c26d21525d339. It seems like now that the preview is only loaded with text that is the exact size of the window, scrolling no longer has any use.

Is there a way to force the preview to load the entire file so it can be scrolled using these keybindings?

**Comment by johnmiked15** [comment]
Maybe the number of contextual lines loaded around the preview could be configurable somehow? For search results, sometimes it's useful to be able to scroll up from the result, as well as down. grep has the ability to set the number of lines to show before, after, or both around search results.

**Comment by torbatamas** [comment]
for the record: now the default key binding for scrolling the preview window is shift+up and shift+down

**Comment by riteshharjani** [comment]
Shift+up and Shift+down keybinding should be also added to README page of this in SCROLL preview window section.

**Comment by harismuzaffer** [comment]
In you vimrc, set let $FZF_DEFAULT_OPTS. I have done it like so. You can copy some or all of it as required:

$FZF_DEFAULT_OPTS="--preview-window 'right:57%' --preview 'bat --style=numbers --line-range :300 {}'
            \ --bind ctrl-b:preview-page-up,ctrl-f:preview-page-down,ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,
            \shift-up:preview-top,shift-down:preview-bottom,ctrl-y:preview-up,ctrl-e:preview-down"

I am telling fzf to bind keys for scrolling the preview window. e.g. ctrl + b will scroll a page up, similarly, ctrl-y will scroll single line up. Basically i have tried to keep vim like bindings here
