### ISSUE TITLE
how to bind execute in vim

### ISSUE THREAD

**Issue by sudavid4** [junegunn/fzf.vim#359]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim
UPDATE: even better than what I'm asking below, is there a way to scroll the preview window to a certain line number? kind of like `less +122g filename`

I have a little script for the command line that binds ctrl-e to show the current file in less for an ag search (so fzf will remain open). This is for the cases that I would like to see a few more lines than what I can see in the preview window. I've tried to make it work in vim but it's not playing along. can this be done. I'll put here the code for completeness, it's based on the `preview.rb` that I got with fzf.vim

```sh
alias -g F=' | fzf  --ansi --preview '\''$DOTFILES/bin/preview.rb {}'\'' --preview-window '\''top:50%'\'' --bind '\''ctrl-g:toggle-preview,ctrl-e:execute:($DOTFILES/fzf/fhelp.sh {})'\'
```
$DOTFILES/fzf/fhelp.sh {}
```sh
#!/bin/zsh
echo running script
linenum=$(echo $1 | sed -E "s/[^:]*:([^:]*).*/\1/")
filename=$(echo $1 | sed -E "s/([^:]*):.*/\1/")
if [[ $linenum -gt 30 ]]; then
	linenum=$(expr $linenum - 20) 
elif [[ $linenum -gt 25 ]]; then
	linenum=$(expr $linenum - 10)
else
	linenum=0
fi
$DOTFILES/fzf/fhelp.rb $1 | less -N +${linenum}g
```
$DOTFILES/fzf/fhelp.rb
```ruby
#!/usr/bin/env ruby
#
# usage: ./preview.rb [-v] FILENAME[:LINE][:IGNORED]

require 'shellwords'

COMMAND = %[(rougify {} || cat {}) 2> /dev/null]
ANSI    = /\x1b\[[0-9;]*m/
REVERSE = "\x1b[7m"
RESET   = "\x1b[m"

split = ARGV.delete('-v')

def usage
  puts "usage: #$0 [-v] FILENAME[:LINENO][:IGNORED]"
  exit 1
end

usage if ARGV.empty?

file, center = ARGV.first.split(':')
usage unless file

path = File.expand_path(file)
unless File.readable? path
  puts "File not found: #{file}"
  puts "File not found: #{path}"
  exit 1
end

if `file --mime "#{file}"` =~ /binary/
  puts "#{file} is a binary file"
  exit 0
end
# puts "#{center}"
center = (center || 0).to_i

IO.popen(['sh', '-c', COMMAND.gsub('{}', Shellwords.shellescape(path))]) do |io|
  io.each_line.each_with_index do |line, lno|
	if lno == center -1
	  puts REVERSE + line.chomp.gsub(ANSI) { |m| m + REVERSE } + RESET
	else
	  puts line
	end
  end
end
```
this is the one that insists on not working. the preview works, toggling the preview also works, opening in less doesn't.
```vim
     call fzf#vim#ag_raw(' '.join(a:000), {'options': ' --preview-window up:50% --preview "''/Users/davidsu/.dotfiles/config/nvim/plugged/fzf.vim/bin/preview.rb''"\ -v\ {} --bind ''ctrl-e:execute:($DOTFILES/fzf/fhelp.rb {}),ctrl-g:toggle-preview''', 'down': '100%'})
```
by the way, I must say I love your work, you are awesome!!!
one more question, if it isn't too much to ask. I can't figure out where and how this fzf#run function is defined, where is it? thanks

**Comment by junegunn** [comment]
`less` does not start in interactive mode if STDOUT is not a tty device.

```sh
seq 1000 | less | cat
```

This is the case for `fzf#run` as it has to read the output of the process. To workaround, redirect STDOUT to `/dev/tty` like follows.

```vim
:echo fzf#run({'options': '--bind "ctrl-e:execute:less {} > /dev/tty"'})
```

Alternatively, you can pass an array instead of a string as `options` so you don't have to care about escaping issues, if you have [the latest version of fzf plugin](https://github.com/junegunn/fzf/commit/7a11a06cbd03353e7c0c7ddc25cd6e9fe58cef6d).

```vim
:echo fzf#run({'options': ['--bind', 'ctrl-e:execute:less {} > /dev/tty']})
```

> I can't figure out where and how this fzf#run function is defined, where is it?

It's defined in the main repo: https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim

**Comment by sudavid4** [comment]
thank you SO MUCH. I would never have nailed this on my own!
