### ISSUE TITLE
Prefer current directory

### ISSUE THREAD

**Issue by pushcx** [junegunn/fzf.vim#360]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Is it possible to make fzf prefer files in the current directory like ctrl-p does? I'm working on a Django project which has a couple dozen "apps". Each app is a directory, and they all have an `admin.py`, `models.py`, `tasks.py`, etc. Because they often interact, the standard way to use vim is to launch it in the parent directory so you can fuzzy-find down into all the children.

However, if the current buffer is `foo/models.py` and I fuzzy-find for `adm`, about 95% of the time I want `foo/admin.py`. Unfortunately, I always get the `admin.py` of the app with the shortest name. I never noticed ctrl-p was doing this, it "just worked" - when I wanted another dir, I could navigate up/down to it.

I can see this is the `--tiebreak` defaulting to `length`, but none of the other options solve this. I know I could hack together vimscript to search only the directory of the current file, but that'd break the 5% of the time I do actually want the file in another directory.

I've read up and down the man page, but I can't see any way to provide this hint. Is there something I'm missing?

**Comment by junegunn** [comment]
> Is it possible to make fzf prefer files in the current directory like ctrl-p does?

"current directory" usually means "current working directory", but it looks like you are referring to the directory of the current file, right? Anyway, I don't know much about ctrlp, but it doesn't look like it behaves that way. Do you have custom settings?

Since fzf is a general-purpose filter, it does not know the context of the search, what each entry means. So there's no way to tell it to prefer files in a certain directory. One can rearrange the input so that those files appear first and set `--tiebreak=index`.

Alternatively I'd suggest that you define a separate command or mapping for starting `:Files` command with a directory argument like so

```vim
nnoremap <silent> <Leader><Leader> :Files <C-R>=expand('%:h')<CR><CR>
```

**Comment by jonhoo** [comment]
@junegunn's solution sadly doesn't really solve the problem: it just gives a limited-scope fuzzy-find. Specifically, like @pushcx, I don't want to *constrain* the search to the directory of the current file (I may indeed want a file that's located elsewhere), I just want to *prefer* locations that are "closer" to some target directory. Now, @junegunn *is* right that this is probably not something fzf.vim should do directly; it should instead ensure that the file list that gets input to fzf is sorted using something that sorts by proximity to a given path (e.g., by piping the output of `FZF_DEFAULT_COMMAND` through a proximity-sort-program).

I do think there's a decent argument for writing such a program and then having a straightforward way to enable its use by `fzf.vim` though. It leads to a *much* better developer experience, _especially_ in large projects. It *could* even be that this should be implemented as a `tiebreak` option for `fzf` like `--tiebreak proximity=/path`, though I think that's an implementation detail.

**Comment by jonhoo** [comment]
I proposed an addition to `fzf` in junegunn/fzf#1380 which would let us implement this pretty trivially in `fzf.vim` (I think).

**Comment by jonhoo** [comment]
This can now be achieved using [`proximity-sort`](https://github.com/jonhoo/proximity-sort) as a filter before passing files to `fzf` along with `--tiebreak=index`. The `.vimrc` config blurb included in the `proximity-sort` `README` provides exactly the semantics I wanted at least!

**Comment by webberwang** [comment]
`nnoremap <leader>t :call fzf#vim#files(FindRootDirectory())<cr>`

I use the FindRootDirectory() plugin to limit the search scope within the project root. You can configure how project root is defined in the plugin.

**Comment by jonhoo** [comment]
@webberwang That's not quite the same as what this issue was about. OP (and I) wanted a way to _prefer_ files that are close to the current directory, without _limiting_ matches to the current directory.

**Comment by RTS5227** [comment]
I've found a solution to that:
```bash
nnoremap <expr> <silent><leader>lr ":Files<CR>".expand('%:h')
```
Go up to the parent dir using Ctrl-W
```bash
export FZF_DEFAULT_OPTS='--bind "ctrl-w:backward-kill-word"'
```
