### ISSUE TITLE
No highlights on indented lines

### ISSUE THREAD

**Issue by yangmillstheory** [junegunn/fzf.vim#361]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

First of all, thanks so much for your work and projects, you make my life so much easier.

Highlighting on `Ag` results only seems to work for matching lines without any tabs or indentation:

![apr-29-2017 12-06-49](https://cloud.githubusercontent.com/assets/2729079/25558082/61f01068-2cd4-11e7-9e18-f009b7392fff.gif)

**Comment by yangmillstheory** [comment]
Hm, wait, I can scroll through the search results with a mouse and verify that the highlights are there...So maybe the issue is that the search match can be outside of the preview window?

**Comment by yangmillstheory** [comment]
I managed to solve this with the following:

![image](https://cloud.githubusercontent.com/assets/2729079/25558525/960ab674-2cdd-11e7-9788-0284e8b77a0b.png)

The change from `ansi` to `truecolor` is just personal preference, and doesn't matter here. Not sure if this is the best approach though.

**Comment by junegunn** [comment]
Hi, thanks for the report. I realized that preview.rb is not properly calculating the height when `--height` option is used. Let me look into it.

**Comment by junegunn** [comment]
To fix this, we need to update fzf so that it exports the height of the preview window as an environment variable so that the scripts can refer to it. I'll release a new version shortly.

**Comment by junegunn** [comment]
I just released fzf 0.16.7 (not yet on Homebrew) and updated `fzf#vim#with_preview` function to use `$FZF_PREVIEW_HEIGHT` option that is exported by fzf. I believe this fixes the issue you reported, and it also fixes incorrect height calculation when vertical split (e.g. `--preview-window up:60%`). Let me know if you still have the issue, thanks.

**Comment by yangmillstheory** [comment]
Looks like the fix worked. Thanks!
