### ISSUE TITLE
:Files is empty

### ISSUE THREAD

**Issue by tnguyen14** [junegunn/fzf.vim#364]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [x] WSL
- Vim
    - [x] Vim
    - [x] Neovim

For some reason, `:GitFiles` works for my project, but `:Files` is returning `0/0`. Is there a way i could debug this further?

**Comment by junegunn** [comment]
Do you have configured `$FZF_DEFAULT_COMMAND`? Then make sure that the command works normally in your shell.

```sh
$SHELL -c "$FZF_DEFAULT_COMMAND"
```

If you don't have the variable, check if the default command works: https://github.com/junegunn/fzf/blob/master/src/constants_unix.go

**Comment by tnguyen14** [comment]
Thanks.

I used to set `FZF_DEFAULT_COMMAND` in my `.bashrc` to use `rg`, in this new machine, I don't have `rg`, and have commented out this line, but for some reason, `FZF_DEFAULT_COMMAND` is still set to that command.

Explicitly set it to the default value seems to have fixed this. Weird.

Thanks for your help!

**Comment by nomasprime** [comment]
@junegunn default command works in shell and I've checked `FZF_DEFAULT_COMMAND` is set properly in NeoVim but still 0/0 results.

**Comment by junegunn** [comment]
@nomasprime Does it work when you unset the variable?

And when that happens, open a new terminal window and see the command from `ps` output. You should be able to see the full command running fzf. Check the content of the temporary files involved.

**Comment by junegunn** [comment]
@nomasprime And what do you see when you run `:echo &shell` and `:echo $SHELL` on Neovim?

**Comment by jrhorn424** [comment]
I'm having this issue as well. `$SHELL -c "$FZF_DEFAULT_COMMAND"` reported the same error as I occasionally see in `nvim`:

```
% fzf --version
0.16.8 (brew)

% $SHELL --version
zsh 5.3.1-dev-0 (x86_64-apple-darwin16.5.0)

% echo $FZF_DEFAULT_COMMAND
ag -g --nogroup --nocolor ""

% echo $FZF_DEFAULT_OPTS
--color bw

% $SHELL -c "$FZF_DEFAULT_COMMAND"
ERR: Error stat()ing:
ERR: Error opening directory : No such file or directory
```

Both `:echo &shell` and `:echo $SHELL` report `/usr/local/bin/zsh`.

**Comment by junegunn** [comment]
@jrhorn424 `ag -g --nogroup --nocolor ""` doesn't work.

**Comment by JorgeCoock** [comment]
@junegunn Think im having the same problem but only after i set the default command as:
`let $FZF_DEFAULT_COMMAND = 'ag -l -g ""'`

Any ideas ?

**Comment by squeezyphresh** [comment]
I don't have a solution, but I'd like to add that I'm having this problem with cygwin if I set FZF_DEFAULT_COMMAND to anything other than empty either within vim or in my shell's environment. Does anyone have this issue on other platforms?

**Comment by pmkhoa** [comment]
@JorgeCoock Please check to make sure you have silver_search ag is installed. If not, you can install via Homebrew: `brew install the_silver_searcher`

**Comment by vkaracic** [comment]
FWIW, I had the same `0/0` issue when migrating to a new computer, turns out that I forgot to install [RipGrep](https://github.com/BurntSushi/ripgrep#installation).

**Comment by ocohen** [comment]
The problem is that the windows Find is found in the path before the one Commander adds. You can fix this by adding `set "PATH=%GIT_INSTALL_ROOT%\usr\bin;%PATH%"` to `Cmder\config\user-profile.cmd`

See https://superuser.com/questions/1219129/unix-find-command-on-cmder-exe-in-windows for more details
