### ISSUE TITLE
Git grep --ignore-case not working

### ISSUE THREAD

**Issue by tnguyen14** [junegunn/fzf.vim#365]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [x] WSL
- Vim
    - [x] Vim
    - [x] Neovim

I followed the example shown on the READMe to define a `GGrep` command, as shown below:

```
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep('git grep --line-number '.shellescape(<q-args>), 0, <bang>0) 
```

When I added the `--ignore-case` flag, it seemed that the search still did**not** ignore case-sensitivity. I could verify that `--ignore-case` works if I did `git grep --ignore-case` directly on the CLI.

**Comment by junegunn** [comment]
There's no reason that it shouldn't work. But don't be confused; the option only applies to the initial filtering done by `git grep` command:`:GGrep INITIAL_QUERY`, and it has nothing to do with the 2nd level filtering done by fzf. It's a separate process. fzf by default performs "smart-case" matching, that is, it does case-insensitive matching by default, but switches to case-sensitive mode if your query contains an uppercase letter. You can force case-insensitivity by passing `-i` to fzf.

```vim
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep('git grep --line-number --ignore-case '.shellescape(<q-args>), 0, {'options': '-i'}, <bang>0)
```
