### ISSUE TITLE
Option to keep cache of files on exit

### ISSUE THREAD

**Issue by gtklocker** [junegunn/fzf.vim#366]
I ❤️ fzf.vim! However `:FZF` takes a long time to index my files the first time I run it: and that makes sense, I run it on directories with not-so-fast storage and loads of files.

One way I was using CtrlP to combat this was by leveraging the [`clear_cache_on_exit` flag](https://github.com/kien/ctrlp.vim/blob/master/doc/ctrlp.txt#L216-L220).

fzf.vim doesn't seem to provide an analogous option to that unfortunately and I think it'd be a very valuable addition. I'd even be interested in helping implement this, just gauging interest in the idea for now. :)

**Comment by junegunn** [comment]
Thanks for the suggestion.

Caching and cache invalidation is difficult. It's hard to get it right and satisfy all sorts of different requirements. So I would just leave it up to the users. You can write a program or script that traverses the file system under the current directory and caches the result in any language you want and set it as `$FZF_DEFAULT_COMMAND`, then `:FZF` (or `:Files`) will use the program.
