### ISSUE TITLE
History command without current file

### ISSUE THREAD

**Issue by meain** [junegunn/fzf.vim#367]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a way to remove the currently open file from the history command output?

**Comment by oconnor663** [comment]
I just put up a PR that _appears_ to make this change, though I'm a complete beginner at VimL, so who knows what I awoke in the darkness of Khazad-dûm...
