### ISSUE TITLE
Filetype not found if triggered from BufEnter

### ISSUE THREAD

**Issue by aesnyder** [junegunn/fzf.vim#368]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

```
au BufEnter * call s:explore_directory(expand("<amatch>"))
function! s:explore_directory(dir)
  if a:dir != '' && isdirectory(a:dir)
    exe 'Files!'
  endif
endfunction
```

I use the following at the bottom of my vimrc to start `Files!` if running vim in a directory. Unfortunately the filetype (and therefore syntax highlighting) is not detected on the file opened from this first run. If I manually run `Files` in an already running vim and select a file the filetype is correctly identified.

**Comment by aesnyder** [comment]
I tried jumping into the source to fix this but can't figure out where/how `fzf#run` is defined. Mind pointing that out to me?

**Comment by noahfrederick** [comment]
@aesnyder https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L317

**Comment by aesnyder** [comment]
thanks @noahfrederick... I tried poking around but was unable to get it to get the syntax correct on the first file picked.

**Comment by junegunn** [comment]
See if adding `nested` helps, i.e. `au BufEnter * nested`. If it doesn't work because of some conflicting autocmds, you can use `call feedkeys(":Files!\<cr>", 'n')` so that it's triggered after all other autocmds are processed.

**Comment by aesnyder** [comment]
`call feedkeys(":Files!\<cr>", 'n')` worked like a charm. thanks @junegunn
