### ISSUE TITLE
provide an "at exit" hook, called when FZF dismissed

### ISSUE THREAD

**Issue by sunaku** [junegunn/fzf.vim#369]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hello,

Please provide an "at exit" hook that is triggered when FZF is dismissed. :leaves:  This will allow me to programatically (and deterministically) restore the cursor position to what it was before I launched FZF.

In particular, I need such functionality for my [vim-shortcut plugin](https://github.com/sunaku/vim-shortcut) where a user can invoke FZF (either intentionally or through an automatic time-delay fallback) to select an operation to perform. :joy_cat:  Trouble occurs in the case where the user changes their mind :scream_cat: and decides _not_ to perform any action: when they dismiss FZF, I need to restore their cursor position back to what it was before FZF was launched, but without an "at exit" hook, I have no way to deterministically know when I should perform the restore. :disappointed:

See also https://github.com/sunaku/vim-shortcut/issues/3

Thanks for your consideration.

**Comment by junegunn** [comment]
`fzf#run` restores the cursor position on exit whether it's interrupted or not. You can easily test this, `call fzf#run()`, enter, ctrl-c, right? So I'm not really sure what the problem here is. Is the cursor on the right position **before** `fzf#run` call?

**Comment by sunaku** [comment]
You're correct: the cursor was already moved to the beginning of the line before `fzf#run()` was called. 😅
