### ISSUE TITLE
Custom Locate

### ISSUE THREAD

**Issue by kurkale6ka** [junegunn/fzf.vim#37]
Hello,

I want to use a custom *Locate* and I've managed with: `command! -nargs=+ Locate call fzf#run({'source': 'locate -Ai -0 '.<q-args>.' | grep -z -vE "~$"', 'sink': 'e', 'options': '--read0 -0 -1 -m --prompt "Locate> "'})`.

That's fine but I'd also like to be able to use the special `Ctrl-v/x/t` keys. I 've tried copying `s:expect()` and others in `after/plugin/fzf.vim` but without much success. Can you help. :)

Cheers

**Comment by junegunn** [comment]
You can use the new `fzf#vim#wrap` function.

**Comment by kurkale6ka** [comment]
Hello!

I have changed my custom Locate to: `command! -nargs=+ Locate call fzf#run(fzf#vim#wrap({'source': 'locate -Ai -0 '.<q-args>.' | grep -z -vE "~$"', 'sink': 'e', 'options': '--read0 -0 -1 -m --prompt "Locate> "'}))` (in `~/.vim/after/plugin/fzf.vim`)

Now, if I directly press enter, I get:
```Error detected while processing function fzf#run[41]..<SNR>85_execute[13]..<SNR>85_callback:
line   27:
Vim(edit):E32: No file name```

Also, when Locate finds A and B; with A opened in the current buffer, if I use `^v` on B, I get a vertical split on B twice (so `B|B` instead of the correct `A|B`)

**Comment by junegunn** [comment]
You're not supposed to use `sink` because of `--expect` option which will print the name of the pressed key as the first line. Instead, `fzf#vim#wrap` will inject `sink*` to the provided dictionary. Please refer to the updated implementation of `Locate` in this repo.

**Comment by kurkale6ka** [comment]
Awesome!
All works as expected. Thanks
