### ISSUE TITLE
Support multiple sources for a single fzf view

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf.vim#370]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

I'm migrating from ctrlp to fzf due to lake of good maintenance on ctrlp. I postponed this migration several times because I have customized ctrlp a lot. Yesterday I decided to do it anyway. I were able to do most of my customizations in fzf.vim too easily except one. I had to patch ctrlp for this one and now I have patched fzf to achieve this too but I hope we can have it in the repository with your help. I need a shortcut that opens fzf with a combined list. It's a combination of a list generated in vim and results of an external program. One simple solution would be to generate output of the external program in vim, append it to the vim list and call fzf with the result. But it has 2 problems: first I should implement a not trivial code to execute and get results of the external program, second (and the more important one) I think it reduces the performance compare to piping the external program to fzf.
I were able to achieve this with a somehow dirty patch like this: (fzf.vim:355)
```
  if has_key(dict, 'source')
    let source = dict.source
    let type = type(source)
    if type == 1
      let prefix = source.'|'
    elseif type == 3
      let done = 0
      for i in source
        if type(i) == 3
          let sources = []
          for j in source
            let type = type(j)
            if type == 1
              call extend(sources, [j])
            elseif type == 3
              let temps.input = s:fzf_tempname()
              call writefile(j, temps.input)
              call extend(sources, [(s:is_win ? 'type ' : 'cat ').s:shellesc(temps.input)])
            endif
          endfor
          let prefix = '('.join(sources, ';').")|perl -ne '$H{$_}++ or print'|"
          let done = 1
          break
        endif
      endfor
      if !done
        let temps.input = s:fzf_tempname()
        call writefile(source, temps.input)
        let prefix = (s:is_win ? 'type ' : 'cat ').s:shellesc(temps.input).'|'
      endif
    else
      throw 'Invalid source type'
    endif
  else
    let prefix = ''
  endif
```
It checks if any of items in the vim list is a list, and if so it'll generate a command line that concatenates two list, running the external program alongside with catting the file which contains vim list. Can we have it in fzf (I think we need a better implementation, but I'm not that good with vim script, for example maybe we should use `sources` instead of `source` for this special case, etc)

**Comment by junegunn** [comment]
> due to lack of good maintenance on ctrlp.

https://github.com/ctrlpvim/ctrlp.vim seems to be actively maintained.

Anyway, I'm not sure if this is a common requirement, and you can implement it without changing the vim plugin of fzf, right? 1. Create temp files, 2. generate command that concatenates the content of the temp file and the output of some other command, 3. pass the command to `fzf#run` function. If you do this stuff frequently, you can easily define an external function for that purpose.

**Comment by sassanh** [comment]
> https://github.com/ctrlpvim/ctrlp.vim seems to be actively maintained.

No it's not, it just seems to 😄 

Yeah, I can do it the way you described. So I close this.
