### ISSUE TITLE
Core dump when opening mark on top of Neovim terminal

### ISSUE THREAD

**Issue by tpict** [junegunn/fzf.vim#371]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Steps to reproduce:
- start with minimal init.vim
- run `:terminal`
- switch to normal mode and run `:Marks`
- select a mark

Result:
```
Error detected while processing function 3[30]..<SNR>9_callback:                                                                                                                                          
line   33:
Vim(normal):Can't re-enter normal mode from terminal mode
Press ENTER or type command to continuenvim: /build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/src/nvim/strings.c:439: vim_strchr: Assertion `c >= 0' failed.
[1]    7169 abort (core dumped)  nvim
```

This occurs whether opening the mark in the current window/new (v)split/tab

**Comment by junegunn** [comment]
This is a neovim issue, you might want to report it to the Neovim team.

**Comment by tpict** [comment]
Any idea what FZF might be doing that triggers this?

**Comment by junegunn** [comment]
:man_shrugging:

**Comment by justinmk** [comment]
The assertion that led to that crash was removed in https://github.com/neovim/neovim/pull/6707. 

The "Can't re-enter normal mode from terminal mode" message is a known limitation of `:terminal` (can use `feedkeys()` to get around it, though ideally we should remove the limitation).
