### ISSUE TITLE
Error detected while processing function fzf#run[78]..<SNR>27_callback...

### ISSUE THREAD

**Issue by EDalSanto** [junegunn/fzf.vim#373]
- Category
    - [x ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x ] Vim
    - [ ] Neovim

Getting the following error when selection attempting to select a file within VIM:
`
Error detected while processing function fzf#run[78]..<SNR>27_callback:
line   33:
Vim(drop):E319: Sorry, the command is not available in this version: tab drop <path/to/file>
`

**Comment by junegunn** [comment]
As noted in README page, this plugin requires Vim 7.4 or above. Upgrade your vim and see if it helps.

**Comment by EDalSanto** [comment]
I'm using Vim 8. Anything else that it could be?

**Comment by junegunn** [comment]
How did you install Vim 8? And please show me the output of `:version`.

**Comment by EDalSanto** [comment]
With Homebrew. See attached for full output.


thanks

:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 03:55:34)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +dialog_con      +job             +mouse_sgr       +rightleft       +user_commands
+arabic          +diff            +jumplist        -mouse_sysmouse  +ruby            +vertsplit
+autocmd         +digraphs        +keymap          +mouse_urxvt     +scrollbind      +virtualedit
-balloon_eval    -dnd             +lambda          +mouse_xterm     +signs           +visual
-browse          -ebcdic          +langmap         +multi_byte      +smartindent     +visualextra
++builtin_terms  +emacs_tags      +libcall         +multi_lang      +startuptime     +viminfo
+byte_offset     +eval            +linebreak       -mzscheme        +statusline      +vreplace
+channel         +ex_extra        +lispindent      +netbeans_intg   -sun_workshop    +wildignore
+cindent         +extra_search    +listcmds        +num64           +syntax          +wildmenu
-clientserver    +farsi           +localmap        +packages        +tag_binary      +windows
+clipboard       +file_in_path    -lua             +path_extra      +tag_old_static  +writebackup
+cmdline_compl   +find_in_path    +menu            +perl            -tag_any_white   -X11
+cmdline_hist    +float           +mksession       +persistent_undo -tcl             -xfontset
+cmdline_info    +folding         +modify_fname    +postscript      +termguicolors   -xim
+comments        -footer          +mouse           +printer         +terminfo        -xpm
+conceal         +fork()          -mouseshape      +profile         +termresponse    -xsmp
+cryptv          -gettext         +mouse_dec       +python          +textobjects     -xterm_clipboard
+cscope          -hangul_input    -mouse_gpm       -python3         +timers          -xterm_save
+cursorbind      +iconv           -mouse_jsbterm   +quickfix        +title
+cursorshape     +insert_expand   +mouse_netterm   +reltime         -toolbar
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation:
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L
/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-mi
n=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-mu
lti-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc

**Comment by junegunn** [comment]
That's strange. Can you reproduce the problem with the minimal vimrc I provided in the issue template?

https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md

**Comment by EDalSanto** [comment]
still couldn't get it to work. It works with the vim `FZF` command but not
the shortcut.

I've attached my current vimrc

**Comment by junegunn** [comment]
No file.
