### ISSUE TITLE
Typo in btags_source

### ISSUE THREAD

**Issue by aronlurie** [junegunn/fzf.vim#375]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

autoload/fzf/vim.vim line 660 in master should be "if v:shell_error" not "if !v:shell_error". We want to exit the loop on failure. Very simple fix.

**Comment by junegunn** [comment]
Thanks, but no, we want to keep trying until a command succeeds.

**Comment by aronlurie** [comment]
What about the case where the first one "succeeds" but returns no tags? How would you feel about "if !v:shell_error && !empty(lines)"?

**Comment by junegunn** [comment]
> What about the case where the first one "succeeds" but returns no tags?

When does that happen?

**Comment by aronlurie** [comment]
For example, when overriding/replacing a default language spec using a .ctags file. If the language is customizable enough, (think javascript frameworks,) the default spec may return nothing.

**Comment by junegunn** [comment]
I see. Is the issue going to be fixed if we change the code as you suggested?

**Comment by aronlurie** [comment]
I believe so, yes. I have tested the code change locally.

**Comment by junegunn** [comment]
Pushed the fix, thanks.

**Comment by aronlurie** [comment]
Thank you!
