### ISSUE TITLE
Helptags implementation

### ISSUE THREAD

**Issue by janlazo** [junegunn/fzf.vim#376]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [X] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

Can we optimize `globpath` by filtering &rtp prior to running `globpath` or changing the matching expression  to `doc/tags` to reduce duplicates? This is the main bottleneck in Windows. If not, can we pass this task to the shell? We can assume that the user has Git for Windows installed for sh, perl, etc.

With changes in my fork [here](https://github.com/janlazo/fzf.vim/blob/Windows/autoload/fzf/vim.vim#L964-L984), I can run `Helptags` but I have to wait for a long time (30 seconds at least in the initial run) for fzf to run.

**Configuration:**
```dosbath
vim -u NONE
```
```viml
" fzf in ~/.fzf
" fzf.vim in ~/vimfiles/fzf.vim
" enterred manually
set rtp+=~/.fzf
set rtp+=~/vimfiles/fzf.vim
runtime! plugin/fzf.vim
Helptags
```

**Comment by junegunn** [comment]
> changing the matching expression to doc/tags to reduce duplicates

Nice suggestion. It makes `:Helptags` noticeably faster on macOS as well. I'll fix it.

**Comment by janlazo** [comment]
Thanks. I rebased my fork with your changes. Helptags is as fast as other fzf.vim commands now.
