### ISSUE TITLE
Moving with tab / space-tab instead of arrow keys

### ISSUE THREAD

**Issue by sevaho** [junegunn/fzf.vim#377]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi,

Is it possible to go trough the list generated by fzf with tab (to go up) and space tab (to go down) instead of moving with arrow keys?

**Comment by junegunn** [comment]
Yes with `--bind`, but note that by default `tab` and `shift-tab` are assigned for selecting multiple entries when `--multi` option is used, so you'll have to reassign them as well. See `man fzf` for details. Let me know if you still can't figure out how to set it up.
