### ISSUE TITLE
Commands, Maps batch generation

### ISSUE THREAD

**Issue by Ensase** [junegunn/fzf.vim#378]
Commands, Maps etc aren't generating correct batch files. The :Files works well.

When I run :Lines the batch file looked:
`type ^"C:\Users\dmitriy\AppData\Local\Temp\VIDFD5C.tmp^"|C:\Users\user\.fzf/bin/fzf  +m --tiebreak=index --prompt "Lines> " --ansi --extended --nth=2.. --reverse --tabstop=1 --query "" --expect=ctrl-v,ctrl-x,ctrl-t > C:\Users\user\AppData\Local\Temp\VICFD5B.tmp`
And it doesn't work. But if I change the binary path from ".fzf/bin/fzf" to ".fzf\bin\fzf" it works.

However on command :Files batch file looked and worked perfectly:
`C:\Users\user\.fzf/bin/fzf  -m  --prompt "~\A\L\Temp/" --expect=ctrl-v,ctrl-x,ctrl-t > C:\Users\user\AppData\Local\Temp\VIA9420.tmp`

- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

**Comment by Ensase** [comment]
The problem disappeared when I downgraded from fzf 0.16.7 to fzf 0.16.6.

**Comment by junegunn** [comment]
We'll look into it. Note that Windows support is experimental at the moment. @janlazo has been working on it on #372.

**Comment by junegunn** [comment]
I can also confirm that it generates executable path with `/bin/fzf` suffix, but surprisingly, it works, and it's not the reason of the error you encountered.

**Comment by Ensase** [comment]
Thank you for reply. The error encoutered only when executable command have `type ^"` as I understand.

**Comment by janlazo** [comment]
In `s:fzf_exec`, simplify the final return statement to use output of `fzf#shellescape(s:exec)`
```viml
function! s:fzf_exec()
     " if block to resolve s:exec
     return fzf#shellescape(s:exec)
endfunction
```

**Comment by janlazo** [comment]
@junegunn If there's no issues on your end, can you commit my suggested fix? We can escape the fzf executable now with `s:shellesc_cmd` because it works on any Windows filepath.

**Comment by junegunn** [comment]
@janlazo Sure thing.

**Comment by Ensase** [comment]
Thank you for all. I've no problem with the latest versions of fzf and fzf.vim.
