### ISSUE TITLE
Using actions for custom FZF command

### ISSUE THREAD

**Issue by sriramkswamy** [junegunn/fzf.vim#379]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

I have a question on how to use a specific action with a custom FZF command. I have set the following option for `g:fzf_action`

``` vim
" Actions
let g:fzf_action = {
            \ 'ctrl-t': 'tab split',
            \ 'ctrl-x': 'split',
            \ 'ctrl-v': 'vsplit',
            \ 'ctrl-o': '!open'}
```

I have defined the following custom command to search Spotlight on MacOS but the actions do not work on this command.

``` vim
" Search spotlight {{{2
command! -nargs=1 FzfSpotlight call fzf#run({
            \ 'source'  : 'mdfind -onlyin ~ <q-args>',
            \ 'sink'    : 'e',
            \ 'options' : '-m --prompt "Spotlight> "'
            \ })
nnoremap <Space>s :FzfSpotlight <C-R><C-W>
```

Should I be changing the `sink` option? Any help would be appreciated. Thank you!

**Comment by junegunn** [comment]
Wrapping the argument (without sink) with [`fzf#wrap` function](https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap):

```vim
" Search spotlight {{{2
command! -nargs=1 FzfSpotlight call fzf#run(fzf#wrap({
            \ 'source'  : 'mdfind -onlyin ~ <q-args>',
            \ 'options' : '-m --prompt "Spotlight> "'
            \ }))
nnoremap <Space>s :FzfSpotlight <C-R><C-W>
```

Does this work?

**Comment by sriramkswamy** [comment]
Yes, works perfectly. Thank you.

**Comment by liushapku** [comment]
what is the difference of using a sink and an action?
If a sink is executed when we press enter on the selection, and an action is executed when we press other keys on the selection, when shouldn't a sink just be a special action?

**Comment by junegunn** [comment]
`g:fzf_action` is only used by the basic sink function for simple file paths that is injected to the options dictionary by `fzf#wrap`. When you specify a custom sink command or function, the variable is simply ignored. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap for clarification.

**Comment by liushapku** [comment]
@junegunn, thanks very much for your prompt reply. 

Then how can I define extra actions for one specific command?
For example: I want to use "ls *.txt" as source, and let "ctrl-o" to cat the contents (in terminal) and let "ctrl-l" to list the file information using "ls -l", and "ctrl-e" or "enter" to edit the file, what should I do then?

**Comment by junegunn** [comment]
Maybe you can temporarily switch `g:fzf_action` before that particular command, but you might want to consider implementing a special sink function just for that command.

See https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

**Comment by liushapku** [comment]
I actually thought that this should be the correct way to go. But after reading the code and help, I am confused by the parameters passed to the  sink function. 

`:h fzf#run`, it says if a function is provided for `sink`, it is to process each selected item. I think the function should then accept one single parameter which is the selected item from fzf. If a function is provided for `sink*`, then it should take a list of selected items.

But in the example for `:Ag`, the `a:lines` parameter in `function! s:ag_handler(lines)` definitely contains something more magic. What is exactly the `lines` parameter when `sink` or `sink*` is used?

**Comment by junegunn** [comment]
We use `--expect` option to see which key was pressed. The list of selected item(s) comes after the name of the key.

```sh
# See how it works
fzf --expect ctrl-f
```

So we can't process each line individually. The sink function should be given the lines at once, so we use `sink*` instead of `sink`.

**Comment by liushapku** [comment]
I overlooked the output of the fzf with --expect option. I don't know that the key is printed when --expect is provided. My problems are all solved. Thank you for your great patience.
