### ISSUE TITLE
Augment :Buffers to delete a buffer

### ISSUE THREAD

**Issue by vbauerster** [junegunn/fzf.vim#380]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Please advice if it is possible to augment `:Buffers` command, so one can `:bd` selected buffer by pressing let say `ctrl-d` or `alt-d`? Why not to add this feature by default?

**Comment by uri** [comment]
I was looking for this too.

**Comment by junegunn** [comment]
Related #75

**Comment by wreed4** [comment]
@junegunn Any update on this? Doesn't seem like there's any progress or insight on the related ticket you linked.

**Comment by motiko** [comment]
Anything is preventing this from being merged?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/pull/733#issuecomment-559720813
