### ISSUE TITLE
Ag command populates location list, not quickfix list

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#382]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I use location list for all search locations and quickfix list for error locations, produced by linters.
Can you please add a setting for `:Ag` command so it uses location list instead of quickfix list?

**Comment by junegunn** [comment]
No objections on using location list.

**Comment by leiserfg** [comment]
Why is it closed? How can I use the location list?
