### ISSUE TITLE
Default key mapping for `:Windows`

### ISSUE THREAD

**Issue by garyayo** [junegunn/fzf.vim#384]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

 What is the default key vim mapping for `:Windows`? I keep running into an issue/feature where when I go to save a file, by some combination of key presses the the FZF `:Windows` split pops up but I have no idea how I am able to access this feature. I would love to bring up the `:Windows` pane on my own but I can't seem to find any information describing the default key mappings. Would anyone be able to help me out?

Thanks.

**Comment by junegunn** [comment]
Not sure what's going on there. There's no default mappings, only commands. You should define your own maps in your vimrc if you want.

**Comment by garyayo** [comment]
Ohhh ok thanks @junegunn. Sorry about opening up this issue.

So I was able to figure out that `:W` is shorthand notation for `:Windows` which is what I was mistakenly typing and executing in place of `:w` writing/saving.
