### ISSUE TITLE
Using GFiles with fugitive.vim sets git_root for the current buffer, not CWD

### ISSUE THREAD

**Issue by zachwalton** [junegunn/fzf.vim#387]
- Category
    - [ ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

(using the latest version of fzf.vim)

With an open buffer for a file tracked by git:

```
:echo @% 
/Users/zachwalton/git/dotfiles/.vim/plugged/fzf.vim/autoload/fzf/vim.vim
:pwd
/Users/zachwalton/git/dotfiles/.vim/plugged/fzf.vim
```

Then `cd` to another project:

`:cd ../vim-test`

Then call `:GFiles`.

**Expected**: Get a list of files tracked by git for `vim-test`
**Actual**: Get a list of files tracked by git for `fzf.vim`

Problem seems to come down to `fugitive#repo().tree()`. [Removing fugitive integration](https://github.com/zachwalton/fzf.vim/commit/c6c928a2d01896d49992d2a688fb761a26260b81#diff-7274b7c6c87526542ef9087f2e997dfaL454) fixes this.

(practically, this is an issue with `ctrlspace.vim`, which allows you to switch between different projects; if you switch to a new one, it will keep the existing buffer open, which triggers this behavior when trying to load `:GFiles`)

Unfortunately I don't see a way to configure the `fugitive#repo().tree()` behavior in fugitive, so the only way to fix this here would be by removing fugitive integration. Feel free to close if that doesn't make sense.

**Comment by junegunn** [comment]
Thanks for the report. I can easily reproduce the problem and noticed that it's a known issue of fugitive. The use of fugitive function was first introduced in #239, and the contributor simply stated that it's "much faster" without numbers. It should be faster, of course, but the difference may not be really noticeable on modern linux/macos boxes. I'll see what I can do.

**Comment by janlazo** [comment]
If `b:git_dir` is unlet, is fugitive still faster than `git rev-parse --show-toplevel`?

**Comment by junegunn** [comment]
> Performance difference is negligible to me in Windows.

That's good to hear. Let's roll back the change and see if someone complains.

**Comment by zachwalton** [comment]
thank you 👏🏻
