### ISSUE TITLE
FZF vim config

### ISSUE THREAD

**Issue by jrock2004** [junegunn/fzf.vim#388]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

I was reading your readme and it says you can do the following if you installed fzf via homebrew

```
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
```

Well I am on linux and I just clone the fzf project to my home dir. So what I am wondering is if `/usr/local/opt/fzf` is pointing to the fzf execuatable or the fzf folder. So would I do this:

```
Plug '/home/jcostanzo/fzf/bin/fzf' | Plug 'junegunn/fzf.vim'

or

Plug '/home/jcostanzo/fzf' | Plug 'junegunn/fzf.vim'
```

Thanks

**Comment by junegunn** [comment]
It's the latter. It looks for `plugin` directory under the path.

https://github.com/junegunn/fzf#as-vim-plugin

I also would like to mention that writing both Plug statements on the same line is not mandatory. (`|` in vimscript is simply like `;` in other languages)
