### ISSUE TITLE
:Tags, :BTags and gotags?

### ISSUE THREAD

**Issue by deanishe** [junegunn/fzf.vim#389]
- Category
    - [x] Question
- OS
    - [x] Linux
    - [x] macOS
- Vim
    - [x] Neovim

`ctags` doesn't understand Go code. I'm trying to configure `fzf` so that `:Tags` and `:BTags` work for Go via `gotags`.

Does anyone know the correct commands?

I've had partial success with `let g:fzf_tags_command = 'gotags -f tags -R .'`, but only for `:Tags`, not `:BTags`.

**Comment by junegunn** [comment]
Currently there's no option for changing the command for BTags. I could add a new configuration variable, or you could try implementing your own command from scratch using `fzf#run` function, but as [Universal ctags](https://github.com/universal-ctags/ctags) supports golang pretty nicely, I don't think it's necessary.

See http://docs.ctags.io/en/latest/news.html#new-parsers

**Comment by deanishe** [comment]
Thanks for the great tip. I've installed universal ctags and it's working very well.
