### ISSUE TITLE
Style Preview Window

### ISSUE THREAD

**Issue by mike3run** [junegunn/fzf.vim#391]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ x] Neovim

![screen shot 2017-06-19 at 23 49 24](https://user-images.githubusercontent.com/7088511/27317100-f38f3326-5549-11e7-9ac1-843a1bb6891f.png)

Hey there I was wondering if there's any way to style the border of the preview window. Also do I need a special character to render that `$` on the right of the preview window?

Thanks a lot!

**Comment by junegunn** [comment]
You can change the color of the border using `--color` option.

```sh
fzf --color 'border:#ff0000,info:#ffff00' --preview 'seq 1000'
```

> Also do I need a special character to render that $ on the right of the preview window?

You mean that question mark inside diamond figure on the right? No, it looks like a glitch of Neovim terminal.

**Comment by mike3run** [comment]
Thanks a lot that worked perfectly and also got rid of the question diamond 😄

**Comment by sjhgz** [comment]
Hello,how can I change the encoding of preview window? When file encoding with non-utf8 such as gbk, preview window output is garbled.

![11586700824_ pic_hd](https://user-images.githubusercontent.com/26674559/79071331-bb618a00-7d0d-11ea-94be-ea4a4997f34f.jpg)

Can someone help me? Thanks a lot!

**Comment by withrocks** [comment]
@sjhgz If you haven't resolved this yet I recommend that you open a new issue, since this is a comment on an old issue that has been closed.
