### ISSUE TITLE
Ignore buffers in buffer list based on regex

### ISSUE THREAD

**Issue by ashiklom** [junegunn/fzf.vim#393]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

I would like to request the ability to ignore buffers based on a regular expression when using the `Buffer` command.

The implementation seems really straightforward -- just a two-line fix to the `s:buflisted()` function. For instance, to ignore terminal buffers:

```vim
function! s:buflisted()
  return filter(range(1, bufnr('$')), 'buflisted(v:val) && getbufvar(v:val, "&filetype") != "qf" && bufname(v:val) !~ g:fzf_ignore_string')
endfunction
```

...if `g:fzf_ignore_string is set.

**Comment by JoshMcguigan** [comment]
To make it easier for others who might search for this, I was hoping to use this functionality to hide the `!/bin/bash` entry in the buffer list when using the `:terminal`.

**Comment by bit101** [comment]
Very nice. I just hard coded it with `^term:.*` so it will stop showing my terminal buffer in the buffer list. Would be nice to have a way to do this. I will follow the pull request mentioned above. But in the meantime, this solves my current problem.

**Comment by activaigor** [comment]
looks like a good solution for a problem, i wonder why it's not merged yet
