### ISSUE TITLE
FZF Colors Option not working with :Ag

### ISSUE THREAD

**Issue by mike3run** [junegunn/fzf.vim#394]
- Category
    - [x] Question
    - [x] Bug
- OS
    - [x] macOS
- Vim
    - [x] Neovim

I've tweaked a bit the `fzf_colors` global variable to have it match my syntax it works fine with `:Files` `:Commits` `:Snippets`

```vim
  let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
    \ 'bg':      ['bg', 'Clear'],
    \ 'hl':      ['fg', 'Comment'],
    \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
    \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
    \ 'hl+':     ['fg', 'Statement'],
    \ 'info':    ['fg', 'PreProc'],
    \ 'prompt':  ['fg', 'Conditional'],
    \ 'pointer': ['fg', 'Exception'],
    \ 'marker':  ['fg', 'Keyword'],
    \ 'spinner': ['fg', 'Label'],
    \ 'header':  ['fg', 'Comment'] }
```

That looks like this:

![screen shot 2017-06-23 at 11 44 59 am](https://user-images.githubusercontent.com/7088511/27491809-6f78492a-5809-11e7-8fd1-ef14ed9031f8.png)

But when I run `:Ag` the colors look a bit off and also I don't have the `--preview` window is there a way to set this up?

![screen shot 2017-06-23 at 11 45 39 am](https://user-images.githubusercontent.com/7088511/27491866-a5e0a188-5809-11e7-8e36-cdeece3a34c1.png)

Maybe Im not looking in the right place.

Thanks a lot for your time and patience

😄

**Comment by junegunn** [comment]
- Each command in this repository corresponds to an autoload function, and for `:Ag` that's `fzf#vim#ag`.
- To further customize the command you have to redefine the command with the function with some extra parameters.
    - `fzf#vim#ag(query, [[ag options], options, fullscreen])`
- The color of the path in ag output is determined by ag itself. Look for `--color-path` in `man ag` for the details.

- Previewing is enabled via `--preview` option of fzf, for example, `seq 100 | fzf --preview 'echo number is {}'`
- So you need a script for displaying the line in the file when an argument line `filename:12:34:line content` is given, and you write `fzf --preview 'preview-script {}'`.
    - That corresponds to `call fzf#vim#ag('initial-query', '--color-path "1;36"', {'options': '--preview "preview-script {}"'})`
- You can write your own, but fzf.vim provides a script for that purpose: https://github.com/junegunn/fzf.vim/blob/master/bin/preview.rb
- And `fzf#vim#with_preview` is a helper function for easily hooking it up to your options argument.
    - `call fzf#vim#ag('initial-query', '--color-path "1;36"', fzf#vim#with_preview())`

And it all comes down to

```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--color-path "1;36"', fzf#vim#with_preview(), <bang>0)
```

More examples can be found here: https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by DasOhmoff** [comment]
Hallo, I am trying to use `command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--color-match "1;36"', fzf#vim#with_preview(), <bang>0)`, because the matching text is unreadable in my preview window. But no matter what color I choose, it still stays blue. Is there a way to fix this?:
![image](https://user-images.githubusercontent.com/16063186/70147027-bf1c3a80-16a3-11ea-9d6c-049328239850.png)

(By the way I use windows and also get a bash not found error message)
![image](https://user-images.githubusercontent.com/16063186/70147055-cba09300-16a3-11ea-8f31-076a7c365e4b.png)
