### ISSUE TITLE
Prefer current directory instead of git root for :GFiles?

### ISSUE THREAD

**Issue by vincentzhezhang** [junegunn/fzf.vim#395]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I am currently working on a git repo which contains many sub-applications that does not need to reference to each other when working on a specific one. One thing annoys me at times is that when I use `:GFiles` it always uses the git root but not the current diretory. Unlike `Files`, passing a path to `:GFiles` seems been ignored.

Is it possible to make `:GFiles` prefer the current directory instead of git root by default? Which IMHO is a very sensible choice.

The end result is similar to `git ls-files | fzf `.

Even better, if we could make use of https://github.com/airblade/vim-rooter, which can switch current root directory by patterns (e.g. package.json, Gemfile, conda.yaml, etc), it would be perfect.

**Comment by junegunn** [comment]
This is all you need:

```vim
call fzf#run(fzf#wrap({'source': 'git ls-files'}))
```

Refer to https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun to learn more about `fzf#run` function.

**Comment by vincentzhezhang** [comment]
Should've spent more time on the manual, it is so convenient to extend the function to fit my needs. That's just pure awesome, thank you!

**Comment by junegunn** [comment]
No problem.
