### ISSUE TITLE
relativenumber is turned off for buffers opened in a split via fzf

### ISSUE THREAD

**Issue by naps62** [junegunn/fzf.vim#396]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

This seems to happen in neovim (v0.2.0), but not in vim

# Reproducing

1. open a minimal vim setup (taken from the issue template):

```
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`
```

2. set up relative line numbers:

```
:set relativenumber
```

3. open a file via the `:Files` command in a horizontal or vertical split or tab (i.e. search for any file, and press Ctrl-X, Ctrl-V or Ctrl-T)

4. The newly open buffer will not have relative numbers enabled

Doing something such as `autocmd BufEnter * set relativenumber` does not seem to help
Also, opening the new file in the same buffer instead of in a split does not trigger the issue

This issue does not occur with `set number`. only relative numbers seem to be affected

**Comment by junegunn** [comment]
Does this seem related? https://github.com/junegunn/fzf/issues/930

**Comment by naps62** [comment]
@junegunn It seems similar, and could be related, but it's not exactly the same thing. That issues seems to disable vim's relativenumber option as soon as you open an fzf panel.

My issue happens when I open a split via FZF. But if I later open a new split through some other method (nerdtree, or simply `:e`, that buffer will have relativenumber set up as expected.

Also, not sure if relevant, but that issue is marked as happening in both neovim and vim, where mine seems to not happen on my vim installation, and only in neovim

**Comment by junegunn** [comment]
The vim plugin of fzf and fzf.vim do not set or unset `relativenumber` (you can't find the term anywhere in the source code), so I'm pretty sure it's a Neovim issue. If you still have issues with the latest Neovim compiled with https://github.com/neovim/neovim/pull/6796, you might want to contact the Neovim guys.

**Comment by naps62** [comment]
@junegunn I can confirm that building neovim from their master branch fixes the issue. Thanks!

Oh, and thank you for an awesome tool

**Comment by rcorre** [comment]
It seems fixed on neovim master, but the FZF split now has line numbers. Is that expected?

![1500601849](https://user-images.githubusercontent.com/2496231/28445943-9d3d0e58-6d95-11e7-8680-47cdc61c8343.png)

**Comment by junegunn** [comment]
Seems like now terminal windows follow the same default options as other windows. Do you think fzf should override and disable line numbers?

**Comment by junegunn** [comment]
Related: https://github.com/neovim/neovim/issues/6832

**Comment by rcorre** [comment]
> Do you think fzf should override and disable line numbers?

I would like that, and think it is reasonable. Line numbers don't contribute useful information within the FZF pane and just take up space.

Alternatively FZF could instruct users to use [this solution](https://github.com/neovim/neovim/issues/6832#issuecomment-305507194) from the issue you referenced:

```
au TermOpen * setlocal nonumber norelativenumber
```

That disables lines in *all* terminal buffers though, which may not be desirable.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/commit/a2604c0963caf458fdd46fe0f83fcd2cc6388582

Let me know if you run into any issues.

**Comment by rcorre** [comment]
Works for me, thanks!
