### ISSUE TITLE
Request/Question: Ag in Current Buffer

### ISSUE THREAD

**Issue by mike3run** [junegunn/fzf.vim#397]
just thinking this could be a bit useful like the BLines command but a bit more in depth

how could this be approached?

thanks for your kind attention

**Comment by junegunn** [comment]
You can experiment with `fzf#vim#grep` like so

```vim
command! -nargs=+ Bag
  \ call fzf#vim#grep('ag --vimgrep '.shellescape(<q-args>).' '.shellescape(expand('%')), 1)
```
