### ISSUE TITLE
Replace options of fzf#vim#buffer_tags completely.

### ISSUE THREAD

**Issue by peanutandchestnut** [junegunn/fzf.vim#399]
- Category
    - [ ] Question
    - [ ] Bug
    - [x ] Suggestion
- OS
    - [ x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

Hi junegunn:

&nbsp;&nbsp;&nbsp;&nbsp;I'm working with c++, i use quite different tag cmd and options from default one. I found that fzf#vim#buffer_tags options are murged into default one, not replaced. 

```vim

function! fzf#vim#buffer_tags(query, ...)
    ...
    return s:fzf('btags', {
    \ 'source':  s:btags_source(tag_cmds),
    \ 'sink*':   s:function('s:btags_sink'),
    \ 'options': '--reverse -m -d "\t" --with-nth 1,4.. -n 1 --prompt "BTags> "'.s:q(a:query)}, args)
    ...
endfunction

function! s:fzf(name, opts, extra)
  ...
  let merged.options = join(filter([get(merged, 'options', ''), eopts], '!empty(v:val)'))
  return fzf#run(s:wrap(a:name, merged, bang))
endfunction


 ```

My final merged option looks like this:
```vim
--reverse -m -d "\t" --with-nth 1,4.. -n 1 --prompt "BTags> " --query '' -m -d "\t" --tiebreak=begin --with-nth 1,4,5,6 -n 1,3,4 --prompt "Ctags> "
```
It looks weird, but It actually works, except the --reverse part. 
It would be nice to provide a way to replace the options completely.

**Comment by junegunn** [comment]
The additional options passed to the function are appended to the default options so you can't override them if you want like so:

```vim
call fzf#vim#buffer_tags('', {'options': '--no-reverse'})
```

Does this answer your question?

**Comment by peanutandchestnut** [comment]
Yes. It will do.
Thanks for the quick response.
Have a goo day.
