### ISSUE TITLE
fzf.vim and nvr interaction: Neovim becomes unresponsive

### ISSUE THREAD

**Issue by jeosadn** [junegunn/fzf.vim#403]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I don't know whether to file this issue against fzf.vim or mhinz/neovim-remote , but since the error message I have available to go on is fzf's, I'm posting this here.

Reproduction steps:
- Install fzf.vim
- Instal nvr from https://github.com/mhinz/neovim-remote
- Open an nvim instance with "nvr --remote". The following message is displayed before nvim opens:
`[*] Starting new nvim process with address /tmp/nvimsocket`
- Execute :Files
- Do anything that closes the fzf window: Ctrl-C, <CR>, etc. The program will hang
- Killing the nvim process leaves the following message in the terminal:
```
Save changes to "term://.//30930:'fzf'  -m  --prompt '~/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimFH7Fdx/0;#FZF"?
[Y]es, (N)o, (C)ancel:
```

**Comment by junegunn** [comment]
Thanks for the heads up, but it looks like an issue of neovim-remote and I don't think I can be of help.
