### ISSUE TITLE
Working with MATLAB folders with special symbols

### ISSUE THREAD

**Issue by sriramkswamy** [junegunn/fzf.vim#404]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

I have recently had to work a lot on MATLAB codes and MATLAB follows a very weird structure to construct namespaces and classes. To create namespaces, the folder has to be prefixed by the character `+`, like `+foo`, and classes have to be preceded by the character `@`, like `@bar`. When I try to use `:GFiles` to navigate this project (with such special characters in folder names), and access a file such as `+foo/@bar/baz.m`, I get the following error message.

```
Vim:E492: Not an editor command: foo/@bar/baz.m
```

I get the same error when I use `:Files` or even just `:FZF`. I'm not sure how to handle this error. I am able to reproduce this with the minimal configuration. To reproduce you need a file with structure `+foo/@bar/baz.m` under a git controlled repository.

**Comment by junegunn** [comment]
Thanks for the report, it's a bug of vim plugin and is a fairly easy one to fix, except I have to make sure that the fix also works on Windows.

@janlazo Hi, I just realized that we should be using `fnameescape` in this case ("Escape {string} for use as file name command argument."). However I'm not sure if it properly handles backslashes on Windows, and since you know the platform much better than me, so can you check if it works?

Related: https://github.com/vim/vim/issues/541

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 24427be..adb0822 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -149,13 +149,7 @@ function! s:tmux_enabled()
 endfunction
 
 function! s:escape(path)
-  let escaped_chars = '$%#''"'
-
-  if has('unix')
-    let escaped_chars .= ' \'
-  endif
-
-  return escape(a:path, escaped_chars)
+  return fnameescape(a:path)
 endfunction
 
 " Upgrade legacy options
```

**Comment by janlazo** [comment]
`\,/,:,*,?,",<,>,|` cannot be used for filenames in explorer.exe.
Backslashes are okay so far (no issues with relative paths so far via `FZF_DEFAULT_COMMAND`).
`fnameescape($PATH) == '$PATH'` so `execute ':edit' fnameescape($PATH)` fails.

**Comment by junegunn** [comment]
@janlazo Thanks. So that's all we need? Good to know that the solution is simple.
