### ISSUE TITLE
Better documentation for mappings

### ISSUE THREAD

**Issue by jan-warchol** [junegunn/fzf.vim#405]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

Hello,

Thanks for making FZF and this plugin! Could you add some examples to the mappings section and explain what they are supposed to do? I put the snippet from `Usage` in my `.vimrc`, and I have to admit that I don't really understand what I'm seeing when I press `<leader><tab>` :-( I expected that this will set up some default key maps, such as `<leader><tab>f` running `:Files` command etc. 

Did I misunderstand readme?

**Comment by junegunn** [comment]
Everything will make more sense once you've gotten yourself familiar with the basics of Vimscript. I personally think one should not use some plugin settings without understanding what they are for, and a few more lines of comments will not help you much. So what I suggest is that you spend some time learning the syntax of Vimscript, it will definitely pay off.  I can't recommend http://learnvimscriptthehardway.stevelosh.com/ enough.

Also let me clarify that the purpose of the examples on the README page are just to show what options are available, they are not recommended settings one must use and they can't really teach you the syntax of Vimscript.

**Comment by jan-warchol** [comment]
Ok, I've looked inside the plugin and it's clear to me that it does only provide commands, not mappings. It makes sense to me not to have default mappings since people's needs differ, and I'll happily define my own.

I still don't quite understand what the mapping example is doing, but I guess I haven't read enough of Steve's book yet.
