### ISSUE TITLE
Is there a way to Ag only git files?

### ISSUE THREAD

**Issue by joaqo** [junegunn/fzf.vim#406]
In my particular use case the :Ag command inside vim is not really usable as I get a ton of false positives before I get to what I am looking for. Is there a way to restrict it to just look through git files?

My current relevant settings in ~/.bash are:

```
export FZF_DEFAULT_COMMAND='ag -U --ignore "*.pyc" --hidden -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
(Though when looking for file names I look for all files, not only git files as seen in my bashrc)

Thanks for the plugin, its made my usage of vim much more pleasurable!

**Comment by junegunn** [comment]
You can define your own version of the command using `fzf#vim#grep` function.

```vim
call fzf#vim#grep('ag --nogroup --column --color foo',  1)
```

Examples can be found here: https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by joaqo** [comment]
Thanks a lot, I think I got it now. If anyone else is searching for this, this is what I ended up using (just added a preview pane):
`command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%'),
  \   <bang>0)`

Also, one small detail I was wondering, is there a way for the search results to only show the file_name, instead of file_name:match_string? I am currently using the preview pane everywhere, so the match_string is actually redundant and actually hides the file_name. Here is a [picture](http://imgur.com/a/Y8W3a) of what I am saying.

**Comment by junegunn** [comment]
No it's not possible, but you can tell fzf not to scroll to the right by passing `--no-hscroll`:
i.e. `fzf#vim#with_preview({'options': '--no-hscroll'}, 'up:60%')`.

**Comment by joaqo** [comment]
Gotcha, thats absolutely perfect. Thanks again!

**Comment by joaqo** [comment]
Hey @junegunn something just started giving me errors with this, and I hoped maybe you could have some insight on what is happening. I am using this particular function:

```vimscript
nnoremap <C-g>g :GGrep<CR>

command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview({'options': '--no-hscroll'},'up:60%')
  \           : fzf#vim#with_preview({'options': '--no-hscroll'},'right:50%'),
  \   <bang>0)
```

When I open python files using it, the file gets opened, but the line the cursor points at get changed for seemingly no reason.

For example, I open a file and the cursor is initially pointing at a line that reads: `class Session:` but for some reason the line gets instantly changed to `ass Session|lass Session:` when I open the file, if I press `u` it returns to its correct initial state. So opening the file using that function is changing the file. This only happens with that function, the rest of fzf's functionalities are working fine, and it seemingly started happening for no reason.

**Comment by joaqo** [comment]
Ended up fixing it by changing the second argument from `1`, to `0` when calling `fzf#vim#grep`. So the final working function is:

```
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   <bang>0 ? fzf#vim#with_preview({'options': '--no-hscroll'},'up:60%')
  \           : fzf#vim#with_preview({'options': '--no-hscroll'},'right:50%'),
  \   <bang>0)
```

No idea why this fixes it, as I don't really know much vimscript or how the plug in actually works.
