### ISSUE TITLE
:Tags with -1 option still opens quickfix list

### ISSUE THREAD

**Issue by gpanders** [junegunn/fzf.vim#407]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I've modified the `:Tags` function to automatically jump to the tag location if there is only one matching tag (i.e. the `-1` option in FZF). My modification is as such:

```
command! -bang -nargs=* Tags                                                                                        
    \ call fzf#vim#tags(<q-args>, {                                                                                   
    \   'options': '-1'                                                                                               
    \ })
```
This works; however, when there _is_ only one option, the quickfix window still opens for a split second and then closes again. Is there a way to prevent the quickfix window from opening when the `-1` option is present and there is only one matching result?

**Comment by junegunn** [comment]
I don't think you're seeing quickfix windows, but the fzf window (see `:copen` to confirm, it should be empty). In Neovim it's not possible to prevent that, as we first opens split window and starts fzf in there. But you'll have better experience on Vim.
