### ISSUE TITLE
:Tags shows RegEx characters in matches

### ISSUE THREAD

**Issue by gpanders** [junegunn/fzf.vim#408]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

When using the `:Tags` command, the matching text from the source code file contains RegEx characters (`/`, `^`, `$`, etc.) that are not actually present in the source. See screenshot below:

![screenshot from 2017-07-26 10-41-53](https://user-images.githubusercontent.com/8965202/28630396-ca6d6dec-71ef-11e7-9f53-cebb2f942b8e.png)

I am using exuberant ctags to generate my tags file.

**Comment by junegunn** [comment]
It's in your tags file, it's expected. fzf simply reads tags file and allows you to select lines. It doesn't look up the actual source code. You can hide the part with something like `--with-nth ..2`, but the option makes fzf noticeably slower (as fzf has to tokenize and reassemble each line), so I would just keep it there.
