### ISSUE TITLE
Open FZF in current pane

### ISSUE THREAD

**Issue by jamesgecko** [junegunn/fzf.vim#41]
I've noticed a small annoyance with how FZF (and vim fuzzy file selectors in general) work. When I open a file, often I'll be reading the name of the file I want to open from a buffer. I'll split the window into two panes with `Ctrl+w v`, then open FZF. FZF will create a new pane at the bottom of the screen, often pushing the text containing the name of the thing I want to open off the screen. It's not uncommon for me to forget what the last word or phrase of the filename I'm looking for is, close FZF, read the text again, then open FZF again. All the text moving around abruptly makes me go blank sometimes.

Is it possible to open FZF in the active pane, then put the selected buffer into the same pane?

Here's terrible ascii art kinda showing what I'm asking.
```
Initial editor pane state, the same buffer open in each pane, with the cursor in top pane.
+-----+
|1    |
+-----+
|1    |
|     |
|     |
+-----+

Now, I open FZF.

What happens now:
+-----+
|1    |
+-----+
|1    |
+-----|
|FZF  |
+-----+

+-----+
|2    |
+-----+
|1    |
|     |
|     |
+-----+


Desired:
+-----+
|FZF  |
+-----+
|1    |
|     |
|     |
+-----+

+-----+
|2    |
+-----+
|1    |
|     |
|     |
+-----+
```

**Comment by junegunn** [comment]
Neovim?

```vim
let g:fzf_layout = { 'window': 'enew' }
```

**Comment by jamesgecko** [comment]
Yep, Neovim. That config seems to make fzf take up the entire terminal, no matter how many vim panes are open. Here's the command I'm using to run fzf:
```
nnoremap <leader>t :call fzf#run({ 'source': 'ag -g""' })<cr>
```

When I changed my changed to `nnoremap <leader>t :FZF<cr>`, that fzf_layout config didn't seem to change the default behavior of fzf.

**Comment by junegunn** [comment]
Looks like you created the issue on the wrong repository. Neither `fzf#run` nor `:FZF` is provided by `fzf.vim` project. `g:fzf_layout` only applies to the commands this repo provide. Anyway, you can then add the `window` option I suggested above to the dictionary argument of `fzf#run`. See https://github.com/junegunn/fzf#fzfrunoptions for the details.
