### ISSUE TITLE
:Files ../

### ISSUE THREAD

**Issue by jorgeOmurillo** [junegunn/fzf.vim#411]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

On Neovim, when selecting multiple files with 'Tab' from different sources and pressing 'Enter' to open them in a buffer, all files are blank except for the first item you select. I might be using the feature incorrectly:

1. :Files ../
2. foo [Tab]
3. bar [Tab]
4. Enter or Ctrl+V

**Comment by jorgeOmurillo** [comment]
All selected items open as buffers correctly, but Ctrl+T does not open them as tabs.

**Comment by junegunn** [comment]
I believe it's caused by some configuration or plugin you have. Can you reproduce the problem with the minimal vimrc suggested in the issue template?

**Comment by junegunn** [comment]
Hmm, okay, I think I can reproduce the problem with CTRL-T. Will look into it.

**Comment by jorgeOmurillo** [comment]
Also, some times when I `:Files ../foo` a blank buffer opens. This is random and I can't reproduce it accurately.

**Comment by junegunn** [comment]
I can't reproduce the problem anymore, maybe I was confused. Can you check again with the minimal configuration as I suggested above?

**Comment by jorgeOmurillo** [comment]
I tested a minimal .vimrc and it works with no problems:

`source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugins')
Plug '~/.fzf'  " fzf is not just for vim, so it's managed externally
Plug 'junegunn/fzf.vim'
call plug#end()`

I'll review my .vimrc. Thanks.

**Comment by junegunn** [comment]
This may help: https://github.com/junegunn/fzf/commit/462c68b625e30964d24ef0d26b5e82169f506f0c

**Comment by jorgeOmurillo** [comment]
I updated the plug-in, but it didn't work with the autocomand I'm using.

**Comment by junegunn** [comment]
You can use `set acd` instead of that. It does the same thing and fzf will work with the option.

**Comment by jorgeOmurillo** [comment]
That worked perfect. Thanks.
