### ISSUE TITLE
Prerender certain fzf windows

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf.vim#412]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I was thinking it'd be great if we could have an fzf window already rendered and show it only when a certain key is pressed. I guess fzf can't be optimized so much anymore but still it takes ~200ms to show list of buffers for me. If I can launch fzf on `BufEnter` and hide it and then show it when I wanna switch buffers it'll show simultaneously.
Maybe it doesn't need to be a feature of fzf.vim and you can help me achieve this with some vimscript?

**Comment by junegunn** [comment]
200ms doesn't sound like normal. Are you sure that it's not the delay caused by conflicting key maps in Vim? Do you experience the same delay when you run `:Buffers` command directly not using a key map? How many buffers do you have open?

**Comment by sassanh** [comment]
I'm sure it's not because of map conflict (it's not waiting for another key stroke.) It's 200ms with `:Buffers` too. I customized it so that it shows buffers + `git ls` so there's a total of ~1000 lines.

**Comment by sassanh** [comment]
I guess it takes longer because of my customization, I have to write buffers to a file and then feed fzf with:
```
    return '(cat ' . l:path . "&&git ls-files --exclude-standard --recurse-submodules|sed 's/^/\t/')|perl -lne '$e=$_; s/.*?\\t(.*?)(\\t.*$|$)/\\1/; $H{$_}++ or print $e'"
```

(`l:path` is the path of that file)

**Comment by sassanh** [comment]
It was your suggestion: https://github.com/junegunn/fzf.vim/issues/370

**Comment by junegunn** [comment]
> I guess it takes longer because of my customization, I have to write buffers to a file

So I guess most of the time is spent in you function writing the file, Vimscript is slow. I would first see if I can optimize the performance of it. If you can't cut down the time, you can consider pre-generating the file on BufOpen event and make the custom fzf command just look at it.

**Comment by sassanh** [comment]
Good idea. But don't you think after all there are situations that fzf can't load fast and this pre-rendering idea would come handy?

**Comment by junegunn** [comment]
I'm not sure. I personally don't find myself wanting it. But anyway do you have an idea how you would implement that? I use plain Vim and using hidden terminal buffer is not an option.

**Comment by sassanh** [comment]
Well you know VimL much better than me. I'm just curious why hidden terminal buffer is not an option? 
something like `:enew | call termopen('sh') | setlocal nobuflisted | e #`. And then closing this buffer on `BufLeave`. Is it hard/impossible to manage these hidden buffers? Is there a risk for creating dangling buffers?

**Comment by sassanh** [comment]
About generating the file on `BufEnter`, I need to avoid this generation to happen for `fzf` buffer. Currently I have this `autocmd`:
```
    autocmd BufEnter * if &buftype ==# '' | silent! call <sid>generate_buffers_list() | endif
```
But reading fzf's code seems like you create buffer and then run `termopen` in it, so I need another way to detect fzf buffer at `BufEnter`. Is it possible?

**Comment by sassanh** [comment]
OK, it's working alright with changing `autocmd` to:
```
    autocmd BufEnter * silent! call timer_start(100, function('s:generate_buffers_list'))
```
and checking this in front of `s:generate_buffers_list`:
```
    if &buftype ==# 'terminal' || !&buflisted || get(s:, 'generated_for_buffer', '') ==# @%
        return
    endif
    let s:generated_for_buffer = @%
```

and creating the buffer to write buffers list like this:
```
    silent! setlocal buftype=nofile bufhidden=hide noswapfile nobuflisted
```

Now fzf opens simultaneously and I can confirm at this point of time I have all the good things of ctrlp (my customized version) in fzf + all good things fzf offers itself.

I just prefer to avoid hacky solutions as much as possible. It'd be great if I can avoid `timer_start` and detect fzf buffer and my own temp buffer in a clean way.

**Comment by junegunn** [comment]
>  I'm just curious why hidden terminal buffer is not an option?

Because there's no such thing as terminal buffer in Vim, it's a Neovim thing at the moment.

> I need another way to detect fzf buffer at BufEnter. Is it possible?

Hmm, I can't think of a good solution. fzf sets `&filetype` to fzf, so one can set up `FileType fzf` autocmd, but you're right that it's not yet set at `BufEnter`.
