### ISSUE TITLE
How to restring the :Ag search to a specific subfolder

### ISSUE THREAD

**Issue by ggsalas** [junegunn/fzf.vim#413]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, sometimes I would like to restring the :Ag search to a specific subfolder. On man ag I see this example:
``` ag foo /bar/: Find matches for "foo" in path /bar/.```
But on neovim I can't 

![only word](https://i.imgur.com/SYXR0gy.png)
![whith folder](https://i.imgur.com/iRzu4D8.png)

Thanks to [this answer](https://github.com/junegunn/fzf.vim/issues/346#issuecomment-288483704) I have customized Ag for search only on file contents, but I don't know how to add a second optional param:
```
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

Thanks

**Comment by junegunn** [comment]
You can use `fzf#vim#ag_raw` function to pass raw arguments directly to ag command:

https://github.com/junegunn/fzf.vim/blob/d3b9fed9c2415a2682cb1c8604e25a351325c22b/autoload/fzf/vim.vim#L606-L609

```vim
command! -bang -nargs=+ -complete=dir Rag call fzf#vim#ag_raw(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

So you can `:Rag foo ~/my-project`, or `:Rag "foo bar" ~/my-project` (the original Ag command sees the whole arguments as the search query so you don't have to quote `foo bar`, `:Ag foo bar`). 

Note that fzf works as the secondary filter on the result of the initial ag command, it does not restarts ag command as you type. It is [not necessarily impossible](https://github.com/junegunn/fzf/issues/974), but it's not how fzf was designed to be used.

**Comment by ggsalas** [comment]
Hi @junegunn works perfect. Thanks for your answer.
I think would be better start Rag with only a path and then insert the search query: ```:Rag ~/myproject``` and then ```Ag> foo ```. 

This can be done?
I try with ```:Rag "" ~/myproject``` but don't work.
Thanks!

**Comment by junegunn** [comment]
You'll get some ideas from the definition of `fzf#vim#ag` function.

**Comment by JesseLeite** [comment]
@junegunn Thank you for the [code example and explanation above](https://github.com/junegunn/fzf.vim/issues/413#issuecomment-320197362) 👌  Love what you've done with both fzf and fzf.vim!
