### ISSUE TITLE
FZF Colors

### ISSUE THREAD

**Issue by zeraus** [junegunn/fzf.vim#415]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hello, how do I change these hard-to-see colors?

P1: To change `src/main.rs`

﻿﻿﻿![Imgur](http://i.imgur.com/C2f7Os8.png)

P2 & 3: To change 'preview'

![Imgur](http://i.imgur.com/XNWLnir.png)

![Imgur](http://i.imgur.com/N4BCx06.png)

**Comment by junegunn** [comment]
See #76
