### ISSUE TITLE
Filter the list

### ISSUE THREAD

**Issue by iuunhao** [junegunn/fzf.vim#417]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ X] Neovim

Just started using fzf.vim found everything is very good, I understand the function has been filtered, but I do not know how to use it, such as I need to filter `node_modules`, how can I do this time to open Files will filter this file, I am still a novice, want to give help.

**Comment by junegunn** [comment]
I suggest that you read through the README page of fzf to understand more about it before using this plugin.

https://github.com/junegunn/fzf

What you're looking for is `$FZF_DEFAULT_COMMAND` environment variable.

https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

**Comment by zkxjzmswkwl** [comment]
The command's poorly documented and his question was one that hundreds of people will stumble upon while googling the very same thing. 

Wouldn't hurt to just include a snippet.
