### ISSUE TITLE
Default fzf#vim#grep ripgrep command not very flexible

### ISSUE THREAD

**Issue by bpstahlman** [junegunn/fzf.vim#419]
The default ripgrep command...
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```
...uses `shellescape()` to wrap `<q-args>` in double quotes, which turns everything entered on the Vim command line after `:Rg` into a single argument to ripgrep. But this approach precludes specifying useful ripgrep options (e.g., globs with -g), and even search directories.

**Example:** In the shell, I might run...
`rg -g *.lisp -g *.clj some-func ~/`
...to search for "some-func" in lisp and clojure files under my home directory. But entering the equivalent command in Vim with the default fzf grep settings effectively sends the following to the shell...
`rg "'-g' '*.lisp' '-g' '*.clj' 'some-func' '~/'"`
...which tells ripgrep to search under the **_current_** directory for the pattern '-g'...'~/' - obviously not what was intended.

My initial solution was to use shellescape() in a map() over `<f-args>` to produce multiple, quoted arguments to ripgrep. But then it occurred to me that simply using `<q-args>` _without_ shellescape() allows me to enter arguments pretty much as I would at a shell command line, which results in less cognitive load, since I don't have to remember how Vim is quoting the arguments (e.g., double vs single quotes).

The command that works for me is...

```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '
  \ . <q-args>, 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```
Is there a reason for the default approach that I've overlooked?

Thanks,
Brett S.

- Category
    - [x] Question
    - [x] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

**Comment by junegunn** [comment]
No it's just an example, no one's obliged to use the exact version. Thanks for sharing your solution.

The advantage of the version shown in the example is that you can search for phrases with spaces without quotes. e.g. `:Rg function foo`. It's just a personal preference thing. Some might find it more convenient, some might find it limiting. And, it's consistent with `:Ag` provided by this plugin.

**Comment by bpstahlman** [comment]
Ah. Makes sense.
Thanks,
Brett S.

**Comment by bpstahlman** [comment]
FWIW... I think most users would be happy to quote/backslash a phrase containing whitespace if it allowed them to specify globs, constrain the directories searched, etc... Actually, I think that would be more intuitive, since many (if not most) users who wanted to search for a phrase would try `:Rg 'some phrase'` before `:Rg some phrase`, but the former wouldn't work under the default configuration, due to the extra set of quotes. I would probably expect `:Rg some phrase` to mean either...
1. search for either 'some' or 'phrase'
2. search for 'some' under directory 'phrase'

Perhaps a sentence or two in the README would make things easier on users who are surprised by the default behavior, but lack the time or inclination to dig through the plugin code...

Thanks,
Brett S.

**Comment by junegunn** [comment]
Thanks for the comment, I'll think about it.

**Comment by kurdybacha** [comment]
@bpstahlman does the command
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '
  \ . <q-args>, 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```
still work for you? I am just trying it and it shows me empty result list all the time.

**Comment by bpstahlman** [comment]
Yes. It still works for me.
Brett S.

**Comment by pabloariasal** [comment]
@bpstahlman also you might want to use `shellescape` because you want to call RipGrep with an empty string (which matches everything) when no arguments are provided to `:Rg`. If you leave it out, calling `:Rg` will produce an empty list. Using `shellescape` will turn `:Rg` into `:Rg ""`. Hence `shellescape` always add an additional pair of double brakes on top.

@kurdybacha this is you problem, `<q-args>` refers to the arguments of the command `:Rg`, so something like `:Rg -g *.py -e test my_dir` should work with @bpstahlman 's change. Calling just `:Rg` without arguments produces an empty list.

**Comment by pabloariasal** [comment]
@kurdybacha I'm by far not a vimscript expert but this might work better:

```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always ' . (len(<q-args>) > 0 ? <q-args> : '""'), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```

 it transforms `:Rg` into `:Rg ""` (what `shellescape` did), so it produces a populated list. If some arguments are provided like `:Rg --smart-case test`, they are forwarded to RipGrep.

**Comment by briandipalma** [comment]
I found the commands above had issues so I'm using [this advanced ripgrep integration command from the README.md](https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration) instead. It's not perfect but it's better than the previous Rg command for my usecases. Removing the `shellescape` function call though makes no difference so I can't pass in more than one argument to the `rg` command (such as specifying a directory). I'll try and debug it when I have more time and update this comment if I can figure out the issue.

--------------- Original post/issue.

I often have to search for sentences so this new command is fantastic as I can specify spaces.
At least I can when run in command mode but I can't seem to get it to work with the popup.
This is the command I'm using:

```vim
command! Rg2 call fzf#vim#grep(
  \ "rg --column --line-number --no-heading --color=always --smart-case "
  \ . (len(<q-args>) > 0 ? <q-args> : '""'),
  \ 1,
  \ fzf#vim#with_preview(),
  \ <bang>0)
```

And when I type:

```bash
:Rg2 "=This is a sentence in a translations file"
```

I get the few results I expect in the search dialog that pops up, but when I type

```bash
:Rg2
```

to bring up that dialog and type in the text I'm looking for I get the old far less precise behaviour which returns way too many results to be useful in a large monorepo/repo like I'm working in. It looks to me like Rg is only queried once and from then on fzf is the tool doing the searching. I thought given Rg was optimized for text searching it would just it in the `grep` function.
