### ISSUE TITLE
Split-size is not kept

### ISSUE THREAD

**Issue by netei** [junegunn/fzf.vim#42]
When you have 3 splits, layed out like this :

![capture](https://cloud.githubusercontent.com/assets/13066384/11240428/f3b4d6b4-8df2-11e5-87d4-189feadf2cba.PNG)

and you run :FZF to open an other file in the top-left split, the bottom split is moved up.

This happens only on "neovim", but I'm not sure whether it should be implemented correctly by neovim or by fzf.vim

![capture](https://cloud.githubusercontent.com/assets/13066384/11240460/4cae5786-8df3-11e5-81d1-289535dc7347.PNG)

In my case, the bottom split is actually a "quick-fix" split, but the bug also happens with normal buffers.

**Comment by netei** [comment]
maybe @tarruda can comment on this ?

**Comment by tarruda** [comment]
`:terminal` buffers are similar to normal buffers in that you can use whatever window you need to display the terminal. `sp | 10wincmd- | term` for example, will split/resize/spawn. If you just use `:term` it will display in the current window, but should fail if nvim is configured to disallow leaving modified buffers

**Comment by Perlence** [comment]
@junegunn @netei This has something to do with `equalalways`, all the windows are automatically made the same size after splitting or closing a window.
