### ISSUE TITLE
How to write a custom command to implementing paste lines?

### ISSUE THREAD

**Issue by wfxr** [junegunn/fzf.vim#420]
- Category
    - [x] Question

I want to define a custom command, which filtering lines like command  'Lines [QUERY]' and then paste selected lines under cursor line.
Can anyone teach me how to do it?

**Comment by junegunn** [comment]
You should be able to write it without difficulty if you know some Vimscript (http://learnvimscriptthehardway.stevelosh.com/ is the best resource I'm aware of).

FYI, line completion is already provided by this plugin.

```vim
" Lines from all files
imap <c-x><c-l> <plug>(fzf-complete-line)

" Or, lines from the current buffer
imap <c-x><c-l> <plug>(fzf-complete-buffer-line)
```
