### ISSUE TITLE
False positives on Ag and Gitgrep

### ISSUE THREAD

**Issue by joaqo** [junegunn/fzf.vim#421]
Hey, I am using Ag and Gitgrep search on fzf, it works really well. The only detail that I am noticing is that they both sometimes match the file name along with the body of the files. So for example, in my repo I search for 'logger' and [this](http://imgur.com/a/ACZ9l) are the results I get using Gitgrep (I get the same using Ag).

If I scroll up I start getting some correct results, of the word logger in the file content, it even gets highlighted correctly, but still, the first results are just the file name several times, which doesnt make much sense.

This are the Ag and Gitgrep shortcuts I am using btw:

```
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%'),
  \                 <bang>0)

command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   <bang>0 ? fzf#vim#with_preview({'options': '--no-hscroll'},'up:60%')
  \           : fzf#vim#with_preview({'options': '--no-hscroll'},'right:50%'),
  \   <bang>0)
```

Let me know if anyone knows that could be causing this, thanks for the awesome plugin!!

**Comment by junegunn** [comment]
Check out #346

**Comment by junegunn** [comment]
FWIW, I find myself searching for file names using `:Ag` quite often. For example, `java:` can filter lines from the files with `.java` extension. But anyway, `--delimiter : --nth 4..` (match from 4th column) or `--delimiter : --nth 4..,1` (match from 4th column first, then look at first column) should do.

**Comment by joaqo** [comment]
Thanks for the answer @junegunn . Couldn't quite get that java trick to work, searched for `py: logger` and still the first results where just matching logger in the file name as in my previous picture. I am sure I am misunderstanding how I should be using this though.

One final question, I am having trouble plugging in the `--delimiter : --nth 4..` flag along with the preview pane I have setup in: 
```
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%'),
  \                 <bang>0)
```

I understand that the function expects an options dict as its second parameter, but I am not sure how to plug in the conditional call to `fzf#vim#with_preview('up:60%')` inside the dict. I have no knowledge of vimscript regretfully.

**Comment by junegunn** [comment]
Try this: `fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')`.

FYI, you can check the output of `with_preview` function by echoing i.e. `:echo fzf#vim#with_preview(...)`

**Comment by joaqo** [comment]
Thanks a lot for the anwser! If anyone else is looking at this issue, the answer junegunn posted works perfectly for Ag. For GitGrep just change the 4 to a 3 in `{'options': '--delimiter : --nth 4..'}` !
