### ISSUE TITLE
Support for screen (like tmux)

### ISSUE THREAD

**Issue by hyiltiz** [junegunn/fzf.vim#43]
This should be as easy asa simply changing the exec from tmux to screen. Could not find it in the documentation. I'd that supported?

**Comment by junegunn** [comment]
Nope, and no plan for screen support. Sorry.

**Comment by hyiltiz** [comment]
Too bad. Stuck with tmux.

On Sun, Dec 13, 2015, 10:23 Junegunn Choi <notifications@github.com> wrote:

> Nope, and no plan for screen support. Sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junegunn/fzf.vim/issues/43#issuecomment-164267779>.
>
-- 

Sent from Gmail Mobile.

**Comment by junegunn** [comment]
Honestly, I see zero reason to use screen when tmux is available (I used screen for years before I switched to tmux) and do not know why you even consider it.

**Comment by hyiltiz** [comment]
Well, because of the license.

On Sun, Dec 13, 2015, 10:48 Junegunn Choi <notifications@github.com> wrote:

> Honestly, I see zero reason to use screen when tmux is available (I used
> screen for years before I switched to tmux) and do not know why you even
> consider it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junegunn/fzf.vim/issues/43#issuecomment-164269562>.
>
-- 

Sent from Gmail Mobile.
