### ISSUE TITLE
Feature Request. Use :Files when :GFiles fails (you're not in a git repo)

### ISSUE THREAD

**Issue by fission1110** [junegunn/fzf.vim#431]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [X] macOS
    - [X] Windows
    - [X] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

----
Would be really cool if there was a setting to use ```:Files``` if ```:GFiles``` fails (Not in git repo).
That way I could use the same keybinding for each with a preference for GFiles as it's faster and ignores my .gitignore'd garbage.

Shouldn't be too hard to hack together.

If that's not something that anyone else wants, it would also be easy to accomplish with a function in vimrc.

**Comment by fission1110** [comment]
Hacked together a quick function to do this in my vimrc.

I don't know VimL well enough to build the actual feature or I'd submit a pull request.

```
function! GFilesFallback()
  let output = system('git rev-parse --show-toplevel') " Is there a faster way?
  let prefix = get(g:, 'fzf_command_prefix', '')
  if v:shell_error == 0
    exec "normal :" . prefix . "GFiles\<CR>"
  else
    exec "normal :" . prefix . "Files\<CR>"
  endif
  return 0
endfunction

nnoremap <c-p> :call GFilesFallback()<CR>
```

**Comment by junegunn** [comment]
Yes, that how I'd do it. See also #233.

> ignores my .gitignore'd garbage

Many users prefer to use ag or rg as `$FZF_DEFAULT_COMMAND` as they can traverse the file system while respecting gitignore. See https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore
