### ISSUE TITLE
ability to choose qf/location list

### ISSUE THREAD

**Issue by teto** [junegunn/fzf.vim#432]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- Vim
    - [ ] Vim
    - [x] Neovim

I've started to write some functions to be able to choose a quickfix/location list among the ones loaded (visibler through :chistory) but it's not easy dealing with :chistory/:colder/:cnewer . Is there any existing implementation someone would know of ? If no, is that sthg that could make it to fzf.vim ?

**Comment by snoblenet** [comment]
How did you get on? The functions that copy-pasted from someone's public dotfiles ages ago and used successfully since then have spontaneously stopped working.
