### ISSUE TITLE
Scrolling preview lines before and after

### ISSUE THREAD

**Issue by nkgm** [junegunn/fzf.vim#433]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion

I can see how one can override `height` in `preview.rb` but that only covers scrolling down. Is it possible to include lines above the target line so that it's also possible to scroll up?

**Comment by junegunn** [comment]
It's not currently possible. fzf does not support displaying preview content with arbitrary offset, and no plan for that at the moment.
