### ISSUE TITLE
[Feature Request] Ability to leave fzf window open after selecting a result.

### ISSUE THREAD

**Issue by yzhuang** [junegunn/fzf.vim#437]
Example use case: after doing `:Ag pattern<CR>` to search for a pattern, I am usually interested in multiple matching files, not just a single one. 

Pressing `<Enter>` would close the fzf window, and jump to the selected file:line.
Can we add a new shortcut to jump to the selected file:line, but leaving the fzf window open?  This way, I can switch back to the fzf window and jump to other results.  This would be especially useful when working with large repositories when each ag search is expensive.

Thanks!

**Comment by junegunn** [comment]
See #351. It's not currently possible and you'll have to use quickfix window for the purpose.
