### ISSUE TITLE
E117: Unknown function: fzf#shellescape on :Ag

### ISSUE THREAD

**Issue by Ran4** [junegunn/fzf.vim#439]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux (Ubuntu 17.04)
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

When running `:Ag` in either vim or neovim I get this error:

    Error detected while processing function fzf#vim#ag:
    line    7:
    E117: Unknown function: fzf#shellescape
    E15: Invalid expression: ag_opts . ' ' . fzf#shellescape(query)
    line    8:
    E121: Undefined variable: command
    E116: Invalid arguments for function insert
    E116: Invalid arguments for function call
    E15: Invalid expression: call('fzf#vim#ag_raw', insert(args, command, 0))
    Press ENTER or type command to continue

I'm using the latest version of ag, ack, fzf, vim, neovim.

Any idea what this might be?

**Comment by tayiorbeii** [comment]
I had a similar error show up seemingly out of nowhere in OS X with iTerm 2:

```
Error detected while processing function fzf#vim#buffers[3]..<SNR>120_q:
line    1:
E117: Unknown function: fzf#shellescape
E15: Invalid expression: ' --query '.fzf#shellescape(a:query)
Error detected while processing function fzf#vim#buffers[3]..<SNR>120_fzf[22]..<SNR>120_wrap:
line    9:
E117: Unknown function: fzf#wrap
E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
line   10:
E121: Undefined variable: wrapped
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#buffers[3]..<SNR>120_fzf:
line   22:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(s:wrap(a:name, merged, bang))
```

I seem to have fixed it by uninstalling then reinstalling `fzf`, adding `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` to my `.zshrc`, and adding `set rtp+=/usr/local/opt/fzf` to my `nvim/init.vim`.

Not exactly the same setup as yours, but hopefully it will help you.

**Comment by junegunn** [comment]
`fzf#shellescape` is defined in the main fzf repo, you should update it as well.

1. If you installed fzf using homebrew, `brew upgrade fzf`
2. If you installed fzf with manual `git clone`, `git pull` it.
3. If you installed fzf using vim-plug, `:PlugUpdate`.

**Comment by imzoer** [comment]
Had the same problem:
E117: Unknown function: fzf#shellescape

I have already upgrade main fzf to 0.17.3 using brew.

Any idea ?

**Comment by junegunn** [comment]
@imzoer Please read through https://github.com/junegunn/fzf.vim#installation

**Comment by rom1v** [comment]
I encounter the same problem.

I installed the Debian package `fzf` (the binary is in `/usr/bin/fzf`):

```
$ fzf --version
0.18.0
```

I use the "native" plugin loader in Vim 8 (as described [here](https://gist.github.com/manasthakur/ab4cf8d32a28ea38271ac0d07373bb53#managing-plugins-natively-using-vim-8-packages)): I cloned the current `master` into `.vim/pack/plugins/start/fzf.vim`.

When I execute for example `:Ag`:
```
Error detected while processing function fzf#vim#ag:
line    7:
E117: Unknown function: fzf#shellescape
line    8:
E121: Undefined variable: command
E116: Invalid arguments for function insert(args, command, 0))
E116: Invalid arguments for function call('fzf#vim#ag_raw', insert(args, command, 0))
```

**Comment by amustafa** [comment]
I know it's closed but I solved this issue by adjusting the "dir" field in VimPlug. I already had fzf installed in a custom location. Adding this solved my issue:

```
Plug 'junegunn/fzf', { 'dir': '~/opt/fzf' }
Plug 'junegunn/fzf.vim'
```

**Comment by tranduchuy** [comment]
@amustafa Thank so much, that error annoy me

**Comment by Zeioth** [comment]
Any clue about how to do this with pathogen? I'm running vim on termux on android.

**Comment by elquimista** [comment]
Had similar issue and figured out it was because fzf opt path changed due to Homebrew since Homebrew 3.

**Comment by jsit** [comment]
I'm also using Homebrew 3 with Apple Silicon, and I had to change my `rtp` line to:

```vim
set rtp+=/opt/homebrew/Cellar/fzf/0.34.0/
```

I imagine this path will change if fzf is upgraded to a new version, so I'll have to modify this again.

Would love to get an additional note in the readme and a workaround for future version changes @junegunn

**Comment by alexstoick** [comment]
Echoing the above comment; I had `"set rtp+=/opt/homebrew/bin/fzf` - which is had I get from `which fzf`; but that did not seem to play nice. 

Once I updated the path to `set rtp+=/opt/homebrew/Cellar/fzf/0.34.0/` it started working.

**Comment by nikitabobko** [comment]
> I'm also using Homebrew 3 with Apple Silicon, and I had to change my rtp line to:
> ```
> set rtp+=/opt/homebrew/Cellar/fzf/0.34.0/
> ```

You would need to update `rtp` variable each time you update `fzf`. It's better to use `set rtp+=/opt/homebrew/opt/fzf` to avoid this problem.

**Comment by mattmartini** [comment]
On a silicon mac you can use: `set rtp+=/opt/homebrew/opt/fzf` This will avoid having to change the path every time the version number changes.

**Comment by mattmartini** [comment]
On a silicon mac you can use: `set rtp+=/opt/homebrew/opt/fzf` This will avoid having to change the path every time the version number changes.  On an intel mac you can use `set rtp+=/usr/local/opt/fzf`

**Comment by zhuxixi** [comment]
> I know it's closed but I solved this issue by adjusting the "dir" field in the VimPlug command. I already had fzf installed in a custom location. Adding this solved my issue:
> 
> ```
> Plug 'junegunn/fzf', { 'dir': '~/opt/fzf' }
> Plug 'junegunn/fzf.vim'
> ```

you save my life,dude

**Comment by rom1v** [comment]
> [my previous comment in 2019](https://github.com/junegunn/fzf.vim/issues/439#issuecomment-524286284)

I just gave it another try, I still have the same issue:

```
$ fzf --version
0.44.1 (debian)
```

Still using the "native" plugin loader in vim as described in my previous comment (using vim 9.1 now).

```
Error detected while processing function fzf#vim#with_preview[51]..<SNR>53_escape_for_bash:
line    2:
E117: Unknown function: fzf#shellescape
Error detected while processing function fzf#vim#ag:
line    7:
E117: Unknown function: fzf#shellescape
line    8:
E121: Undefined variable: command
E116: Invalid arguments for function insert(args, command, 0))
E116: Invalid arguments for function call('fzf#vim#ag_raw', insert(args, command, 0))
```

Does it mean that fzf could not be loaded with the "native" vim plugin loader (and requires vim-plug for example), or did I do something wrong?

**Comment by junegunn** [comment]
Please read https://github.com/junegunn/fzf.vim#installation carefully. You need to install two plugins.
