### ISSUE TITLE
Ag doesn't work after update on vim 8

### ISSUE THREAD

**Issue by avatarr** [junegunn/fzf.vim#440]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I updated  fzf.vim yesterday and I can't use ":Ag" function to search content on Vim 8.0.946 but before I updated it's work normally. Anyone can help me for this? 

<img width="1137" alt="screen shot 2560-08-31 at 10 07 49 pm" src="https://user-images.githubusercontent.com/1640817/29931286-0277424a-8e9b-11e7-8b30-1f52444ea7a5.png">

Thank you

**Comment by junegunn** [comment]
Have you tried updating fzf and its vim plugin?

**Comment by avatarr** [comment]
I already tried it's dose't work for me

**Comment by junegunn** [comment]
1. Does `call fzf#vim#grep('ag --nogroup --column --color ^', 1)` work?
1. Does `ag --nogroup --column --color ^` work on your command-line?

**Comment by avatarr** [comment]
I tried `ag --nogroup --column --color ^` on commend line I got `zsh: command not found: ag`, So maybe 1 is dosen't work too

**Comment by junegunn** [comment]
So you don't have `ag` installed on your system. Install it, then it will work. I'll update fzf.vim to print error message if `ag` is not found.

**Comment by avatarr** [comment]
I just figure it out, fzf doesn't  install  [ggreer/the_silver_searcher](https://github.com/ggreer/the_silver_searcher) on my machine. To fixed it I install by self add follow the instruction it's worked

**Comment by TrentChou** [comment]
I meet the same problem when I intall Ag with linuxbrew,
when I use Ag, Shell will announce "[1]    31138 segmentation fault  ag"
Same announcement when I us   ag --nogroup --column --color ^  "[1]    31329 segmentation fault  ag --nogroup --column --color ^"
And I am sure I have install the_silver_searcher on my system
