### ISSUE TITLE
Using funcrefs as 'source' returns 'E704: Funcref varibale name must start with a capital: source'

### ISSUE THREAD

**Issue by felipesere** [junegunn/fzf.vim#443]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I've been trying to write my own function to feed the source fzf.vim from my own plugin.
I have below function which returns the right results if I call it with `:echo nvimRecent#cacheContent()`:

```
function! nvimRecent#cacheContent()
  return rpcrequest(s:jobid, 'cached-files')
endfunction
``` 
When I try to use it as a fzf `source` I get the error from the title. 
This is how I have it hooked into fzf:

```
nnoremap <silent> <Leader>r :call fzf#run({
      \ 'down': '40%',
      \ 'source': function("nvimRecent#cacheContent()"),
      \ 'sink': "e",
      \ })<CR>
```
I was expecting my function to return a list, as it does in command mode.

From the error, I gather that it doesn't like the lower-case `source`.  From looking at the fzf.vim code, a type-check is done on the value, but I think it never even gets that far.

If someone could should me the right way to wire in a functio-source I'd gladly help update the wiki.

**Comment by junegunn** [comment]
`funcref` is not supported as `sink`. See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

And you don't need funcref in this case. You can just write ` 'source': nvimRecent#cacheContent()`. It's nore like a macro definition and Vim does not evaluate the expression at the point.

**Comment by felipesere** [comment]
Thanks :)

**Comment by junegunn** [comment]
Also, if your sink is simply `e`, you might want to remove it and wrap the whole dictionary with `fzf#wrap` to get some free goodies. https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

```vim
nnoremap <silent> <Leader>r :call fzf#run(fzf#wrap({
      \ 'source': nvimRecent#cacheContent(),
      \ }))<CR>
```
