### ISSUE TITLE
How to top position results

### ISSUE THREAD

**Issue by 4ice** [junegunn/fzf.vim#445]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

Hello, at the moment I got the following config in my .vimrc,
`let g:fzf_layout = { 'down': '~40%' }`

This make the results for a search only use 40% from the bottom of my screen and it works great.

However, according to the documentation, the fzf_layout also accepts 'up' parameter instead of 'down'. And that I would really like, because I am more comfortable with showing the results at the top of the screen. So I have tried
`let g:fzf_layout = { 'up': '~40%' }`
But that shows the search results in fullscreen instead. How am I supposed to write my config in order for the search results to show from top?

**Comment by junegunn** [comment]
Currently, layouts other than `down` (up, left, right, window) are only supported when you're on tmux (via fzf-tmux script) or you're running Neovim where fzf is started inside its terminal buffer.

Vim 8 recently introduced builtin terminal emulator, and we'll be able to use it to support those extra layouts in the near future.

**Comment by halilim** [comment]
Was this solved already? Or maybe it's only because I'm using MacVim (8.1.2234).

**Comment by junegunn** [comment]
Yes.
