### ISSUE TITLE
Can't use fzf.vim when searching for files using :Files

### ISSUE THREAD

**Issue by alex3165** [junegunn/fzf.vim#446]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi, I am having an issue when I try to use fzf.vim, when I type `:Files` I get the following error:
```
Error detected while processing function fzf#vim#files[15]..<SNR>63_fzf[18]..<SNR>63_wrap:
line    5:
E706: Variable type mismatch for: options
line    7:
E691: Can only compare List with List
E15: Invalid expression: options !~ '--expect' && has_key(opts, 'sink*')
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#files[15]..<SNR>63_fzf[18]..fzf#run[4]..<SNR>37_upgrade:
line    2:
E715: Dictionary required
```

I am expecting fzf.vim to open a new pane with the list of files I can search for like when I use fzf on my terminal
<img width="279" alt="screen shot 2017-09-14 at 09 44 03" src="https://user-images.githubusercontent.com/4259832/30420398-55c68aa0-9931-11e7-948b-d9564fb4863d.png">

What I am trying to achieve is to search for a file in NERDTree and open it in a new pane.

- Vim version: 7.4.8056

(I am beginner with VIM)

**Comment by junegunn** [comment]
The code had an issue on older versions of Vim. Should be fixed now.

**Comment by zamith** [comment]
I have fzf working fine with Neovim (both are the latest versions available on homebrew), but when I `bundle open a_ruby_gem`, then it no longer works, with this exact error. Any idea of what it might be?
