### ISSUE TITLE
Question: Is ctags run automatically for a buffer if BTags is invoked?

### ISSUE THREAD

**Issue by jamischarles** [junegunn/fzf.vim#447]
- Category
    - [x] Question
- OS
    - [x] macOS
- Vim
    - [x] Neovim

Loving fzf. I'm using BTags to show the ctags in the current file, and it works really really well with JS files.

**Question**:
Even if I delete my tags file, BTags still shows me tags from my current file. `Tags` command won't run because it hasn't been created yet (as expected).  Does fzf (with vim plugin) somehow process the tags for the current buffer on the fly?

Is there a way to substitute my own tag generating command for a buffer if that is auto-generated?

**Comment by junegunn** [comment]
> Does fzf (with vim plugin) somehow process the tags for the current buffer on the fly?

Yes.

> Is there a way to substitute my own tag generating command for a buffer if that is auto-generated?

Yes, you can define a custom command using the underlying function for BTags command:

https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L745-L746

Examples using it can be found on this issue tracker.

**Comment by jamischarles** [comment]
Thx!
