### ISSUE TITLE
Switch to existing buffer, à la CtrlP does

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [junegunn/fzf.vim#45]
Just dropping a suggestion to consider.

In CtrlP there is a useful option to navigate to already open buffer when selecting some file from `CtrlPBuffer` (controlled by [`g:ctrlp_switch_buffer`](https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L148) and by cursory look [executed here](https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L1038-L1047))

@junegunn Can you see a use case to have something similar implemented in fzf.vim's `s:bufopen`?

**Comment by danihodovic** [comment]
Isn't that what `:Buffers` does?

**Comment by aleksandrs-ledovskis** [comment]
Selecting list item (`<CR>`) in `:Buffers` opens it in current window. Is there some key combo that switches to already open tab/split, for example (as CtrlP does)?

**Comment by junegunn** [comment]
You might want to try out `:Windows` command, which can be seen as an alternative implementation of `:Buffers` command. But I suppose you want the behavior in `:Files` command, right? The idea is currently not there, but I believe you can modify the command without too much difficulty if you know some Vimscript.

**Comment by aleksandrs-ledovskis** [comment]
`:Windows` is the the one I was looking for!

I really should have checked all available commands in fzf.vim :blush:
