### ISSUE TITLE
Command history without running ?

### ISSUE THREAD

**Issue by bannier** [junegunn/fzf.vim#450]
- Category
    - [x] Question

When using command history, is it possible to just select the command without executing it in order to modify it before execution ?

**Comment by junegunn** [comment]
You seemed to have missed the message ":: Press CTRL-E to edit"

**Comment by bannier** [comment]
I'm very sorry and ashamed I missed it. Thanks for the quick answer.

**Comment by junegunn** [comment]
No worries.
