### ISSUE TITLE
Calling :FZF and :Files with marked text or vim search string

### ISSUE THREAD

**Issue by 4ice** [junegunn/fzf.vim#451]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I have been using :FZF a while, mainly for navigating between files. When I am programming I often see a "new class()". I would like to be able to either mark the classname and then call 
`:Files -q 'markedText'`
Or when I search for a classname inside vim, I would like to use the fzf command like
`:Files -q 'searchbuffer'`
So my question is: Is it possible to use the -q command when using :FZF and :Files?

**Comment by junegunn** [comment]
`:FZF -q 'something'` is allowed, while `:Files` only takes a directory argument. You might want to define your own command or mapping using the underlying functions.

```vim
nnoremap <leader>f
  \ :call fzf#vim#files('.', fzf#vim#with_preview({'options': ['--query', expand('<cword>')]}))<cr>
```
