### ISSUE TITLE
Is it possible to ignore some files

### ISSUE THREAD

**Issue by entropitor** [junegunn/fzf.vim#453]
E.g. to ignore build files in Files, Ag, ...

**Comment by junegunn** [comment]
Yes, https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

**Comment by strikemike2k** [comment]
> Yes, https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

Updated link: https://github.com/junegunn/fzf#respecting-gitignore

**Comment by mrded** [comment]
I suppose the question was not how to respect `.gitignore` but how to ignore some files in Files? 

Can we please reopen this?

**Comment by bendoh** [comment]
@mrded please try this change https://github.com/junegunn/fzf.vim/pull/819 which will allow you to set `g:fzf_files_options.source` to influence the fzf source command (i.e., `rg --files ...`)

**Comment by bendoh** [comment]
The problem with setting `FZF_DEFAULT_COMMAND` is that it requires an environment variable to be set outside of the vim process and it affects _all_ commands run through fzf. #819 will allow a more exact options specification

**Comment by bendoh** [comment]
Guess that wasn't the best way, https://github.com/junegunn/fzf.vim/pull/819#issuecomment-498476100

**Comment by tomskopek** [comment]
The docs are really good and helpful but maybe a bit intimidating to some - at least they were to me, before I played with it a bit more.

 I set FZF to use fd as per the example in the readme. You will need to `brew install fd` if you don't have it already

In my `~/.zshrc`:
```export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'```

This makes fzf use the output of `fd --type f` (same as doing `fd --type f | fzf` in the terminal - try it out!)

Now to exclude folders/files there are actually several ways to do it. One can ignore certain folders with fd by setting up a .fdignore file (see: https://github.com/sharkdp/fd#excluding-specific-files-or-directories)

Then in my repo's root directory, I created a .fdignore file with 'build' in it, and other folders I wanted to ignore.

```$cat .fdignore
mobile/ios
mobile/android
build```

Now if I use FZF inside vim those folders will be ignored.

Hope this helps someone one day!

Thanks junegunn for the excellent work and documentation.

**Comment by fkotsian** [comment]
For ag try (will search individual occurrences, for files I suggest the wonderful `fd` implementation above!):

```
# in ~/.fzf.{bash,zsh}
EXPORT FZF_DEFAULT_COMMAND='alias ag='ag . --path-to-ignore ~/.ignore'  # from: https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage

# in ~/.ignore
node_modules
```

**Comment by abeidahmed** [comment]
For anyone using `fd`, I pasted this in my `.bashrc` file and it worked.
```
export FZF_DEFAULT_COMMAND="fdfind --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build,tmp} --type f"
```

**Comment by tejasvi** [comment]
How to set FZF_DEFAULT_COMMAND for a particular command? For example, I would like to be able ignore non-markdown files while searching for notes but have the ability to search other files with a different mapping as well.

**Comment by erikw** [comment]
If anyone else comes here and have the following setup
* Using fd as default command: `export FZF_DEFAULT_COMMAND='fd --type file --hidden --follow'`
* Using `:Rg` to grep in files

and want to exclude a specific path in a git project say `path/to/exclude` (but that should not be included in `.gitignore`) from both fd and rg as used by fzf.vim,

then the easiest way I found to solve to create ignore files for the respective tool then [ignore this file in the local ](https://stackoverflow.com/a/1753078/265508)git clone (as they are only used by me)

```bash
cd git_proj/
echo "path/to/exclude" > .rgignore
echo "path/to/exclude" > .fdignore
printf ".rgignore\n.fdignore" >> .git/info/exclude
```

**Comment by vitaly-zdanevich** [comment]
Hello, I am trying to write my mapping - sometimes I want to ignore `*_test.go` and folders with `mock` in the name, but do not understand how to do that, currently I have this:

```
nnoremap <leader>e :call fzf#vim#files(systemlist('find ' . getcwd() . ' -type f -not -name \'*_test.go\''), {'options': ['--preview', 'cat {}', '--preview-window=right,70%']}, 1)<CR>
```

Please help :(

**Comment by vitaly-zdanevich** [comment]
Found a solution:

```
nnoremap <leader>e :call SearchWithIgnore()<CR>
" Exclude tests, mocks

function! SearchWithIgnore()
    let c = 'rg --glob "!*_test.go" --glob "!*_mock.go" --glob "!*.gen.go" --glob "!mock/" --glob "!mocks/" --column --line-number --no-heading --color=always --smart-case -- %s || true'
    let reload_command = printf(c, '{q}')
    let spec = {'options': ['--disabled', '--bind', 'change:reload:'.reload_command]}
    let spec = fzf#vim#with_preview(spec, 'right', 'ctrl-/')
    call fzf#vim#grep(c, 1, spec, 1)
endfunction
```

**Comment by vitaly-zdanevich** [comment]
It works for `foo` but not for `foo(`, how to solve it?

**Comment by vitaly-zdanevich** [comment]
I [found](https://github.com/BurntSushi/ripgrep/issues/299#issuecomment-270087955) the solution: add `--fixed-strings` to `rg`.

From the man:

      -F, --fixed-strings
           Treat the pattern as a literal string instead of a regular expression. When this flag is used, special regular expression meta characters such as .(){}*+ do not need to be escaped.

           This flag can be disabled with --no-fixed-strings.

**Comment by mb720** [comment]
Here's a way that allows to specify the excluded directories *per mapping* in Vim when searching with `fd`:

    " Search files in ~/docs, excluding the directories target, .git, and .stversions
    nmap <leader>gd :FilesWithIgnore ~/docs target .git .stversions<cr>

    " Search files in ~/.config, excluding the directories Signal, .git, chromium, BraveSoftware, JetBrains, and libreoffice
    nmap <leader>gc :FilesWithIgnore ~/.config Signal .git chromium BraveSoftware JetBrains libreoffice<cr>

    " Find files by name, starting at startDir and excluding the directories
    " specified in the following arguments (...)
    function! s:FilesWithIgnore(startDir, ...)
      let l:dirsToExclude = a:000
      let l:fzfCommand = 'fd . ' . a:startDir . ' --hidden --no-ignore'
      for l:excludedDir in l:dirsToExclude
        let l:fzfCommand .= ' --exclude ' . l:excludedDir
      endfor
      call fzf#run({'source': l:fzfCommand, 'sink': 'e'})
    endfunction

    " See: https://vimdoc.sourceforge.net/htmldoc/map.html#%3Cf-args%3E
    command! -nargs=+ -complete=dir FilesWithIgnore call s:FilesWithIgnore(<f-args>)

In my case, the directories I want to ignore/exclude depend on the directory I start searching in.

**Comment by rihannarickeminem** [comment]
Please, help with Ag ,  this lin does not work now

> Yes, https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

**Comment by rihannarickeminem** [comment]
> For ag try (will search individual occurrences, for files I suggest the wonderful `fd` implementation above!):
> 
> ```
> # in ~/.fzf.{bash,zsh}
> EXPORT FZF_DEFAULT_COMMAND='alias ag='ag . --path-to-ignore ~/.ignore'  # from: https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage
> 
> # in ~/.ignore
> node_modules
> ```

not working, please help
