### ISSUE TITLE
Custom bash command as fzf.vim input

### ISSUE THREAD

**Issue by pauloromeira** [junegunn/fzf.vim#455]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hello! I'm wondering if there's a way to use the output of a custom bash command as its input. I'm trying to do something like this:
```
command! -bang -nargs=* GFeature
  \ call fzf#vim#grep('git diff --name-only $(git merge-base HEAD develop)', 0)
```

So I can search only the files that are about to be merged with develop branch.
Also It would be awesome if I can pass a branch as argument, and set 'develop' as default, if not passed.

With the command above I can only see the files, but I get an error if I try to open them - btw it would be awesome to preview them too.

Many thanks for one of the best plugins available for Vim!
Cheers!

**Comment by junegunn** [comment]
You might want to read through https://github.com/junegunn/fzf/blob/master/README-VIM.md and see some examples on https://github.com/junegunn/fzf/wiki/Examples-(vim).

For file paths, the following should suffice:

```vim
" Any command that lists files can be used as the source
call fzf#run(fzf#wrap({'source': 'ls -al'}))
```
