### ISSUE TITLE
:Files is not working

### ISSUE THREAD

**Issue by arael** [junegunn/fzf.vim#456]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I cannot use :Files on my setting.

Distro: Ubuntu 17.04
Vim: 8.0
Shell: Zsh 5.2

I have a fresh install of fzf and fzf.vim

The errors occur only in vim. I am able to search from the shell. 

:!fzf in vim works too.

These are the errors: 
```
Error detected while processing function fzf#vim#files[15]..<SNR>52_fzf[18]..<SNR>52_wrap:
line   12:
E117: Unknown function: fzf#wrap
E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#files[15]..<SNR>52_fzf:
line   18:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(s:wrap(a:name, merged, bang))
```

I am using pathogen and the plugin is installed under .vim/bundle/fzf.vim directory.

**Comment by junegunn** [comment]
You also need to install the main fzf repository where `fzf#run` and `fzf#wrap` are defined.

- https://github.com/junegunn/fzf/tree/master/plugin
- https://github.com/junegunn/fzf.vim#installation

**Comment by arael** [comment]
I have both installed. fzf and the vim plugin.
The fzf is availble in my shells. The .fzf.bash and the .fzf.zsh are in my home and are included in .bashrc and .zshrc.

The plugin is under .vim/bundle/fzf.vim directory and :Files command is available in vim. The issue is that every time i start it it doesn't work.

I think the issue is in the fact I am not using vim-plug for the installation. What should I do if am using pathogen and all my plugins are under .vim/bundle directory?

Thank you very much for this tool by the way. Love it.

**Comment by junegunn** [comment]
> The fzf is availble in my shells

But not in your Vim. See https://github.com/junegunn/fzf#as-vim-plugin

**Comment by arael** [comment]
Indeed, you are right. Now it works. Thank you very much!

**Comment by jgillman** [comment]
I was also confused and it took this thread and some trial and error for me to get it. For others who find this and were as lost as me:

# To install fzf with Vundle

Your `.vimrc` should have the following:

```
set rtp+=~/.fzf
Plugin 'junegunn/fzf.vim'
```

The first line should be changed depending on how you installed `fzf` (i.e. Homebrew vs Git).

**Comment by henrik** [comment]
I got caught out by this as well. @junegunn, what are your thoughts on catching this situation and providing an error message that points to the specific issue?

**Comment by henrik** [comment]
If you like me use Git submodules instead of a plugin manager, you need to:

* Add fzf.vim as a submodule like you always would with a plugin
* Also add `source ~/.fzf/plugin/fzf.vim` to `~/.vimrc`.

```
~/.fzf/plugin/fzf.vim
```

**Comment by kreedz** [comment]
This
```
set rtp+=~/.fzf
Plugin 'junegunn/fzf.vim'
```
doesn't work for me, I'm on Windows and using neovim.

I've installed fzf and moved its content to ~/.fzf directory.

So now `echo &rtp` shows long string and in the end of it I can see fzf directory:
`<some other dirs>,C:\Users\<myUserName>\.fzf`.

But I still having errors like `Unknown function: fzf#run` when typing `:Files`:
![fzf](https://user-images.githubusercontent.com/2128965/36541921-49e22d08-1801-11e8-8cfc-2f818521d8ff.png)

**Comment by amigrave** [comment]
Wouldn't be easier to make a single vim plugin repository for fzf ?
Personally I never use install scripts because I take special care of my dotfiles.

Installing fzf for vim manually should be as simple as putting the fzf binary somewhere in the PATH and add a single fzf repository in vimrc using your favorite vim plugin manager (or copying the files yourself if you don't use a plugin manager).

@junegunn if you do that you won't have anymore this kind of installation issues pouring into your project's issue tracker :)

**Comment by terheyden** [comment]
I'm using:
- MacVim
- Vundle
- fzf installed via Homebrew

Here's what worked in my `.vimrc`:
```
" Add homebrew fzf to the vim path:
set rtp+=/usr/local/opt/fzf

" Add the fzf.vim plugin to wrap fzf:
Plugin 'junegunn/fzf.vim'
```
Note that this didn't work at first... I had to reinstall fzf and re-run the bindings! I kept getting the error messages until I did that!

**Comment by pBlasiak** [comment]
in vimrc I added 
 Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
 Plugin 'junegunn/fzf.vim'

then I closed vimrc and rerun it
and then I typed 
:PluginInstall 
and closed vimrc

next in some file I typed
:Files<CR>
and I got info that binary file is not found
and if I want to download it
I confirmed and fzf works

**Comment by bhaveshscp** [comment]
Install `fzf` using `brew install fzf`

Edit `~/.vimrc` file to add

* `Plug 'junegunn/fzf.vim'` in *list of plugins* section and 
* `set rtp+=/usr/local/opt/fzf` at the end of the file

It should look like this:
```
call plug#begin('~/.vim/plugged')
# [Lines removed]
Plug 'junegunn/fzf.vim'
# [Lines removed]
call plug#end()

set rtp+=/usr/local/opt/fzf
```

Open `vim` and type `:Files` and you should be able to see list of files. This solution works for me.

**Comment by juanMarinero** [comment]
> Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

I tried that, actually with `Plug`, not with `Plugin`, still no success, `:Plugupdate` says fzf is installed (and up-to-date), but `:Files` not running. On the other hand, `:FZF` runs smoothly btw.

My configuration:
- I **git**-installed VIM for bash (**Ubuntu** 14.04).
- VIM 8.2 (Included patches: 1-486)
- I use [vim-plug](https://github.com/junegunn/vim-plug) as VIM plug-in manager. 
- List of plug-ins up-to-date (might an incompatibility): nerdtree, fzf, vim-fugitive, vim-colors-solarized, ale, c.vim, vim-airline, taglist.vim, jedi-vim, vim-virtualenv, vim-snippets, coc.nvim
- $ fzf --version # outputs: 0.21.1 (334a4fa)
- $ fd --version # outputs: fd 7.3.0
- $ tmux -V # outputs: tmux 1.8
- ~/.fzf has that install file you reference Sir.

~/.vimrc:
```
call plug#begin('~/.vim/plugged')
     Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
     Plug 'junegunn/fzf'
call plug#end()
```

~/.bashrc (it might be important):
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always {} | head -500" --height 60% --layout=reverse --border'
export FZF_DEFAULT_COMMAND='fd --type f --hidden'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
bind '"\C-h": " \C-e\C-u\C-y\ey\C-u`__fzf_history__`\e\C-e\er\e^"'
bind '"\C-f": "\C-t"' 
```
Thanks in advance!

**Comment by junegunn** [comment]
You need both 'junegunn/fzf' and 'junegunn/fzf.vim'. Please refer to the README page.

**Comment by juanMarinero** [comment]
> You need both 'junegunn/fzf' and 'junegunn/fzf.vim'. Please refer to the README page.

Thanks! It worked! As @junegunn answered, just follow his steps: [https://github.com/junegunn/fzf.vim#using-vim-plug](https://github.com/junegunn/fzf.vim#using-vim-plug)

Final code of ~/.vimrc:
```
call plug#begin('~/.vim/plugged')
     Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
     Plug 'junegunn/fzf.vim'
call plug#end()
```
**PlugClean** is key. Before reinstalling the plug-ins, execute a [:Plugclean](https://github.com/junegunn/vim-plug/wiki/tutorial#removing-plugins):
```
$ vim ~/.vimrc
[ delete Plug-fzf lines ]
:w
:source $MYVIMRC
:PlugClean
[press y[es]]
[insert Plug-fzf lines as shown before]
:w
:source $MYVIMRC
:PlugInstall
:source $MYVIMRC
:Files
```
With :PlugUpdate should also work. Actually so I tried before, but maybe I forgot to souce vimrc :sweat_smile:

Btw, in future for **update** I follow official [steps](https://github.com/junegunn/fzf#upgrading-fzf). Summary for **git** & **vim-plug**:
1º pull fzf-git repo:  `$ git: cd ~/.fzf && git pull && ./install`
2º executing `$ vim ~/.vimrc;` and `:PlugUpdate fzf`

**Comment by davidmaxwaterman** [comment]
FWIW, I thought I'd try to explain how I found myself with this issue.

[This](https://vimawesome.com/plugin/fzf-vim) is the page that confused me.

It seems to indicate just one line needs adding:
```
Plugin 'junegunn/fzf.vim'
```

![screenshot](https://user-images.githubusercontent.com/975698/189373772-dcf8a054-6b25-4292-a428-481f4404b66a.png)

It's silly in retrospect, but because the README refers to 'vim-plug' and I'm using Vundle, and also includes some more complex code (`, { 'do': { -> fzf#install() } }`) than I'm used to seeing, I ignored that.

However, the follow *is* clear, but somehow I still managed to 'default' to the Vundle specific instructions:

```
which means you need to set up both "fzf" and "fzf.vim" on Vim. 
```

[This](https://vi.stackexchange.com/questions/13718/how-to-install-fzf-vim-with-vundle) is what got me past the post, and brought me to this page too :)

**Comment by xavychan** [comment]
For anyone who installed fzf through package manager (homebrew, apt-get, pacman.. etc), you don't need to clone the entire main fzf repo; just create the folder structure in your vim plugin location as below and copy only the fzf.vim file from the plugin folder of this repo like <vim_plugin_loc>/fzf/plugin/fzf.vim

Also, make sure you added fzf binary path in your .vimrc like
set rpt+=/usr/bin/fzf

This will work !!!
