### ISSUE TITLE
Failed to open /dev/tty

### ISSUE THREAD

**Issue by virus-found** [junegunn/fzf.vim#458]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

```
vim 8.0.1155

+termguicolors
+terminal
+terminfo
+termresponse
```
Trying minimal configuration, terminal window layout:
```
let g:fzf_layout = { 'window': '10split enew' }
```
doing command :Files
```
Error running ( /bin/zsh '/var/folders/zx/x93z1bhd5k18n10t6k9y2flm0000gn/T/vYVcZ1h/4' )|'/private/tmp/plugged/fzf/bin/fzf'  '-m' '--prompt' '~/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/zx/x93z1bhd5k18n10t6k9y2flm0000gn/T/vYVcZ1h/3
```
and new terminal split contains only:
```
Failed to open /dev/tty
```

Googling for this failed me, so I can't help but create a bug/question here. Thank you for any advice.

**Comment by sajain** [comment]
I have a similar issue with the latest version of macOS (High Sierra)

**Comment by junegunn** [comment]
You both on High Sierra? And you know that fzf didn't support `window` layout on plain Vim before yesterday (https://github.com/junegunn/fzf/commit/077ae51f0511260ba2d2c793b776582d41fefd6a), right?

**Comment by sajain** [comment]
Yes, I noticed now when you mentioned it. But for me at least, it used to work (and even work now) on vim (in iterm2). It is only in MacVim that it stopped working after the upgrade to High Sierra with an error like this in the screenshot below.

![image](https://user-images.githubusercontent.com/76432/31023451-5d667c7e-a52b-11e7-8501-8cba11946ff0.png)

**Comment by virus-found** [comment]
Yes, on High Sierra too.
Using the very latest fzf (just rebuilt) and fzf.vim
Not working for me in plain vim8, didn't try in MacVim.

**Comment by junegunn** [comment]
https://github.com/vim/vim/issues/2162

**Comment by virus-found** [comment]
now works ok in vim 8.0.1171
thanks
