### ISSUE TITLE
Vim(throw):E730: using List as a String

### ISSUE THREAD

**Issue by liujoey** [junegunn/fzf.vim#46]
Neovim release 0.1.0
Mac OS El Capitan

:BTags command gives this error

```
Vim(throw):E730: using List as a String
```

**Comment by junegunn** [comment]
For some reason, the underlying ctags command seems to fail in your case. Fixed the plugin to give the right error message in that case.

**Comment by cmcaine** [comment]
I get E730 for about a third of the commands added by fzf-vim:

Get E730:
  - Files
  - Buffers
  - Lines
  - BLines
  - History
  - Helptags

These all work:
  - Commands
  - Marks
  - Colors
  - Maps
  - Filetypes
  - History:
  - History/
  - Windows

Not tested:
  - Git ones
  - BTags
  - Locate
  - Ag
  - Snippets

Complete error for `:Files`:

```
Error detected while processing function fzf#vim#files[15
]..<SNR>65_fzf[18]..<SNR>65_wrap[12]..fzf#wrap:
line   35:                                     
E730: using List as a String
E15: Invalid expression: s:defaults() .' '. get(opts, 'op
tions', '')
line   49: 
E734: Wrong variable type for .=
Error detected while processing function fzf#vim#files[15
]..<SNR>65_fzf[18]..fzf#run:
line   64:                  
E734: Wrong variable type for .=
```

**Comment by cmcaine** [comment]
Updating fzf to a git master fixed it. I was previously on fzf 505dc0491b727657569359b3318fe76278530265.
