### ISSUE TITLE
Preview with Commits and BCommits

### ISSUE THREAD

**Issue by yangmillstheory** [junegunn/fzf.vim#461]
- Category
    - [X] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

Is there a way to show the diff of the commit in a preview window while fzf is open in vim?

**Comment by junegunn** [comment]
Added `--preview` option to those commands. Let's see if anyone complains :)

**Comment by ngocphamm** [comment]
I just got to this and... yeah I don't really like it as I have fzf window vertically on the left. With the preview there will be not much space for the git log tree itself. Is there anyway I can have different window position for different commands, `:Buffers`, and `:Commits` for example? Or can I specify somewhere to turn off `--preview` for `:Commits`?

**Comment by junegunn** [comment]
@ngocphamm You can override any command using its autoload function.

```vim
command! -bang Commits call fzf#vim#commits({'options': '--no-preview'}, <bang>0)
```

But I could update fzf.vim to enable preview option only when the width of the screen is wide enough.

**Comment by ngocphamm** [comment]
Sounds awesome! Thanks @junegunn
