### ISSUE TITLE
visual select + \ key opens fzf, how to disable?

### ISSUE THREAD

**Issue by tony** [junegunn/fzf.vim#463]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

What would be the way to disable visual mode + \ key opening fzf? It's overlapping with my tcomment visual selection.

**Comment by tony** [comment]
`xnoremap \ <nop>` will disable TComment and fzf.

I want it to not bind visual mode + `\` to fzf.

**Comment by junegunn** [comment]
fzf does not define any key mappings. You should debug your configuration file.
