### ISSUE TITLE
system's bash completion will be messed up if installed using './install --all' option

### ISSUE THREAD

**Issue by waynez** [junegunn/fzf.vim#464]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Problem Summary:
I installed the fzf plugin using the suggested method, but later I found the original bash completion won't work in some cases.

Installation method:
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf/vim'

Issue:
See details here: https://unix.stackexchange.com/questions/397692/bash-completion-wont-work-if-calling-application-with-the-absolute-path/397874#397874

**Comment by junegunn** [comment]
I can't reproduce the problem, so I presume that you have some conflicting configuration. If you can provide a minimal shell configuration file, preferably less than maybe 10 lines, that can be used to reliably reproduce the issue, I can take a look.

**Comment by waynez** [comment]
I managed to delete all my bash configuration(~/.bashrc), and leave only the system bash configuration there, installed the vim plugin with '--all' option, can still see this issue. My system is a CentOS 6.6, which is managed by the company's IT.

I can try a fresh install of CensOS 6.6 and see if I can still see it.

**Comment by waynez** [comment]
Ok, I've tried a fresh install of CentOS 6.6, and confirmed I cannot see that issue.

I guess it'll have something to do the customizations the system administrator did to my system.

As long as it won't reproduce on another system, I'll close this issue for now.

Thanks for taking a look!

**Comment by junegunn** [comment]
Thanks for looking into it. Please let me know if you happen to find out which configuration caused the conflict.

**Comment by waynez** [comment]
Sure.
