### ISSUE TITLE
I would like to ignore WinName like `NERD_tree_1` with :Windows command

### ISSUE THREAD

**Issue by ktrysmt** [junegunn/fzf.vim#466]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

fzf.vim is awesome!
I always display some NERDTree with NerdTreeTabs. In the case, :Windows output NERD_tree_1 each tab, of course too. I'd like to exclude specific windows by name, would you know you such an option or a mean?

![2017-10-15 23 42 04](https://user-images.githubusercontent.com/6156742/31585874-0cd564b0-b204-11e7-91df-f1af25f7ccd9.png)

**Comment by junegunn** [comment]
No such option exists. Though not ideal, you can set up `--query` option to filter out lines containing `NERD` from start as follows:

```vim
command! -bang Windows call fzf#vim#windows({'options': ['--query', '!NERD ']}, <bang>0)
```

**Comment by ktrysmt** [comment]
Thank you so much!
