### ISSUE TITLE
Ignore node_modules folder

### ISSUE THREAD

**Issue by navdeepio** [junegunn/fzf.vim#469]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I put EXPORT FZF_DEFAULT_COMMAND='ag --nocolor --ignore node_modules -g ""' in my zshrc but it still shows node_modules/files in the fzf dialog.

**Comment by junegunn** [comment]
Works for me (and many other users). Just to be clear, `EXPORT` should be written in lower-case.

**Comment by navdeepio** [comment]
tried echo $FZF_DEFAULT_COMMAND, which sent out the above set option...
any other pointer(s)? I'm using gvim..

**Comment by junegunn** [comment]
Which Vim command are we talking about? `:Files`? Also see if the variable is properly exported to GVim process by checking the output of `:echo $FZF_DEFAULT_COMMAND` inside GVim.

**Comment by navdeepio** [comment]
> Which Vim command are we talking about?

`:Files`

When I try `:Files .`, fzf excludes the node_modules folder.. why? Since the output of `:echo $FZF_DEFAULT_COMMAND` is empty..

**Comment by rstacruz** [comment]
In case anyone stumbles upon here: use `:FZF` instead of `:Files`.

`$FZF_DEFAULT_COMMAND` will only work in `:FZF`. Hope this helps!

**Comment by junegunn** [comment]
@rstacruz No, Files also use that. Maybe you redefined the command in your configuration file?

**Comment by johnmcdowall** [comment]
Can confirm, the `export FZF_DEFAULT_COMMAND` is respected by `:Files`.
