### ISSUE TITLE
ProjectFiles?

### ISSUE THREAD

**Issue by demon386** [junegunn/fzf.vim#47]
Do we have something automatically run "Files" on project root (if it has .git, .svn, etc), and yet act on current directory if it's not under a project.

Unite has a source called "UniteWithProjectDir", and I remember CtrlP has something similar too. Would be very convenient.

**Comment by dani-h** [comment]
:+1:

**Comment by junegunn** [comment]
So is it `:GitFiles` failing back to `:Files` command?

**Comment by dani-h** [comment]
@junegunn Is it possible to list **all** files within the root git repo? For example folders marked in gitignore, such as node_modules?

**Comment by demon386** [comment]
@junegunn It's a kind of if/else command, if one can find a repo, it will use `:Files` from the repo root, else it will use `:Files` on the current directory. I prefer `:Files` on the repo root than `:GitFiles` because it can find new file that is not yet in the repo.

**Comment by junegunn** [comment]
Okay then, this should do the trick. It's pretty simple so I don't think we should add a separate command for it.

```vim
function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction

command! ProjectFiles execute 'Files' s:find_git_root()
```

**Comment by demon386** [comment]
Cool. Thanks

**Comment by netei** [comment]
I personally use https://github.com/airblade/vim-rooter, which makes it work without any configuration

**Comment by drasill** [comment]
My 2 cents : https://gist.github.com/drasill/ff9b94025dc8aa7e404f

**Comment by justjake** [comment]
I use this snippet for integration with NERDTree and git projects:
https://github.com/justjake/Dotfiles/blob/6e14f57d836a970fc45d0a6cdfa79ca09de17842/config/nvim/init.vim#L81-L92

**Comment by DanielAndreasen** [comment]
Inspired by the code above I implemented this:

```vim
function! s:find_files()
    let git_dir = system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
    if git_dir != ''
        execute 'GFiles' git_dir
    else
        execute 'Files'
    endif
endfunction
command! ProjectFiles execute s:find_files()
nnoremap <leader>p :ProjectFiles<CR>
```

This will run `GFiles` on the toplevel git dir, if found, otherwise fallback to `Files` from the current directory.

**Comment by j5shi** [comment]
Use the following command to search from the top git repo if you have nested git repos in your dir.

```vim
function! FindTopGitRoot()

    let l:my_cwd = getcwd()
    let l:git_top_level = '.'

    while 1

        let l:git_top_level_tmp = system('git rev-parse --show-toplevel 2> /dev/null')[:-2]

        if l:git_top_level_tmp != ''
            let l:git_top_level = l:git_top_level_tmp
            exe "lcd " . l:git_top_level_tmp . '/../'
        else
            exe "lcd " . l:my_cwd
            return l:git_top_level
        endif
    endwhile

endfunction
command! FzfProjectFiles execute 'FZF ' FindTopGitRoot()
```
