### ISSUE TITLE
Option to set default buffer mode when opening with FZF

### ISSUE THREAD

**Issue by sebastien** [junegunn/fzf.vim#472]
- Category
    - [X] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

When invoking `:FZF<CR>` and selecting a file, the file's buffer is set in *edit mode* by default. For some reason, this felt really odd to me and I end up accidentally removing/editing content as I'm typing comment (a typical use case would be to do a `/` to search after opening with FZF). Is there a way to specify the default mode in which `fzf.vim` will open a buffer? I tried adding `execute 'visual'` in the `s:bufopen` [line 574](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L574) with no success. Any pointers?

**Comment by alfunx** [comment]
By *edit mode* I suppose you mean *insert mode*. The default behavior is that a file is opened in *normal mode* when using `:FZF`. Do you by any chance override the command anywhere, e.g. in your `.vimrc`?

**Comment by junegunn** [comment]
Sounds like a configuration issue. I'm pretty sure that you won't be able to reproduce the problem with the minimal vimrc presented in the issue template.
