### ISSUE TITLE
Adding Ag command color parameters?

### ISSUE THREAD

**Issue by sigzegv** [junegunn/fzf.vim#475]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

How to implement Ag color parameters (--color-path, --color-line-number, --color-match) in fzf#vim#ag command ? I'm not very familiar with vim scripting so I blindly tried to override Ag command definition with `command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, ['--color-path="0;33"'])'` or `command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {"--color-path": "0;33"})` but neither works..

Is there a solution?

**Comment by sigzegv** [comment]
My workaround is to override the ag_raw function or now. I hope there could be a better way..

```
function! fzf#vim#ag_raw(command_suffix, ...)
 if !executable('ag')
    return s:warn('ag is not found')
  endif
  return call('fzf#vim#grep', extend(['ag --nogroup --column --color --color-path="0;38;5;202" --color-line-number="0" --color-match="1;33" '.a:command_suffix, 1], a:000))
endfunction
```

**Comment by junegunn** [comment]
You're doing it wrong. Simply pass additional command line arguments to ag_raw function along with the query string. No need for override.

**Comment by sigzegv** [comment]
Can you show me an example because I'm not sure to write it correctly (not really familiar with vim scripting)

**Comment by junegunn** [comment]
```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--color-path="0;33"', <bang>0)
```
