### ISSUE TITLE
:History sort order

### ISSUE THREAD

**Issue by wcpines** [junegunn/fzf.vim#478]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

#### TL;DR: How is `:History` sorted?  Is sort order alterable? 

Context: I've been getting the hang of fzf.vim after switching from CtrlP, but I still have some lingering confusion. I've read some of the past issues and it sounds like implementing MRU sort is up to users. Before I go down that path (and try to learn me some VimL), I first want to check if I'm missing anything. 

First, how is the sort order of `:History` determined?

Right now, here's what I expect. 

1.  Open some files, A, B, C, D.
2. While on file A, close the buffer (`bd`), moving to file B.  
3. Toggle :History
=>
**Expected behavior:** first/highlighted entry is file A
**Actual behavior:**  a seemingly random, though recently accessed file, is shown. 

- Is there a sort logic that I'm missing?
- If so, is it possible to change it? 
- Can you point me in the right direction to getting started attempting to implement MRU?

I'm guessing [here](https://github.com/kien/ctrlp.vim/blob/master/autoload/ctrlp/mrufiles.vim) and [here](https://github.com/Shougo/neomru.vim/blob/master/plugin/neomru.vim).

Thanks so much!

CP

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim/blob/5c6cee878a71ed27b137aafa7993624a357c0b82/autoload/fzf/vim.vim#L434-L440

So basically, it's a combination of open buffers sorted by the last time you accessed (i.e put cursor on), and `v:oldfiles` provided by Vim. I'm not sure how Vim manages the order of `v:oldfiles`.

You might want to check these out:

https://github.com/search?utf8=%E2%9C%93&q=fzf-mru&type=

**Comment by alextrastero** [comment]
https://github.com/lvht/mru

**Comment by alextrastero** [comment]
Hey @wcpines, I know this was a looong time ago but did you manage to solve this? Which package did you use?

**Comment by wcpines** [comment]
@alextrastero I've mainly been living with it. Instead of toggling the last accessed buffer via `:History` (i.e. `<leader>m<cr>`) I use `<C-^>` which I have mapped to `<C-b>`. There's a sample MRU function you can view [here](https://github.com/junegunn/fzf/wiki/Examples-(vim)#simple-mru-search) as well.  The sort order _seems_ to be better?
