### ISSUE TITLE
Customizing fzf options for different commands?

### ISSUE THREAD

**Issue by infokiller** [junegunn/fzf.vim#48]
What's the best way to use different options for the different commands? for example, I want to use extended search in `Lines` but fuzzy search in `Commands`.

Thanks for this great tool! I love it!

**Comment by infokiller** [comment]
Just to clarify, I want to override a subset of the options but use the default for others.

**Comment by junegunn** [comment]
It's currently not possible so you'll need to fork if you want per-command customization at the moment. By the way, `extended search mode` is on by default since 0.10.9. Maybe you meant `--exact` option?

**Comment by infokiller** [comment]
Thanks for your response!
I know `extended` is now the default, but I meant that if I will override the default search mode to be fuzzy (via the env variable for example), this will affect all fzf commands that won't specify the search mode explicitly from the command line, right?

**Comment by junegunn** [comment]
> I will override the default search mode to be fuzzy 

What do you mean by that? Which option do you have in mind? Extended-search mode is "fuzzy" by default; e.g. `fb` will match `foobar`.

> this will affect all fzf commands that won't specify the search mode explicitly from the command line, right?

Correct. No per-command customization at the moment.

**Comment by infokiller** [comment]
Yes, you're correct, sorry for the confusion on my part, I actually meant exact.
Just to clarify my motivation for the different search modes: when the list input to fzf is small, I find extended non-exact mode to be the best. Usually I can just use 2 or 3 characters that will do fuzzy matching. However, when the list is large (for example, when searching my global persistent command line history from all sessions), exact matching works better for me.

**Comment by junegunn** [comment]
I see. Just to be sure, you know you can perform exact match in normal extended-search mode by prepending `'` to the search term, right?

I haven't really thought about how we should allow per-command customization. But you can try writing a custom command that switches the env var during the execution.

```vim
function! s:with_exact(cmd)
  let orig = $FZF_DEFAULT_OPTS
  try
    let $FZF_DEFAULT_OPTS .= ' --exact'
    execute a:cmd
  finally
    let $FZF_DEFAULT_OPTS = orig
  endtry
endfunction

command! -bang ECommands call s:with_exact('Commands<bang>')
command! -bang ELines call s:with_exact('Lines<bang>')
```

**Comment by infokiller** [comment]
Many thanks for your detailed answer, I appreciate it.
Yes, I'm aware of `'`. I will use the function you suggested , thanks a lot!

**Comment by for-coursera** [comment]
@junegunn Thanks for that function, it's very handy. However, if I define, let's say, EFiles in the same manner:

    command! -bang EFiles call s:with_exact('Files<bang>')

it fails then to run for a specific directory, like `EFiles ~/foo/bar` (vim is reporting `E488: Trailing characters`).

Thus, my question is if it's possible to modify that `s:with_exact` somehow to make that achievable, too?

Thanks again!

**Comment by junegunn** [comment]
```vim
command! -bang -nargs=* EFiles call s:with_exact('Files<bang> '.<q-args>)
```

**Comment by for-coursera** [comment]
Thanks!
