### ISSUE TITLE
Is it possible to select multiple files at once (like CtrlP with <Ctrl>-z option)?

### ISSUE THREAD

**Issue by Integralist** [junegunn/fzf.vim#483]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Just moved to fzf (coming from CtrlP) and I liked CtrlP's ability to select multiple files at once (using <Ctrl>z) is that possible with this plugin?

Thanks

**Comment by Integralist** [comment]
Nevermind. Just bothered myself to actually RTFM and turns out you just hit Shift-Tab. Apologies

**Comment by dsifford** [comment]
@Integralist Where is this located in the manual? I spent waaaaaaaaaaayy too long trying to figure this out and this issue is the only thing that helped me.

**Comment by Integralist** [comment]
@dsifford hmm, I can't remember exactly, but I think I came to the realization that if this plugin is for controlling fzf, then maybe I should read the fzf docs (link at top of this repo's readme). 

It might have specifically have been this section:

https://github.com/junegunn/fzf/blob/master/README.md#using-the-finder

But I can't recall if maybe I found it out somewhere else. 

Hope that helps though.

**Comment by dideler** [comment]
Worth pointing out that multi-mode needs to be enabled.

```
ls | fzf -m
```
or
```
ls | fzf --multi
```

Then use <kbd>Tab</kbd> or <kbd>Shift</kbd><kbd>Tab</kbd> to mark multiple items.

**Comment by deeheem23** [comment]
Any idea how multi-select can be made the default behaviour instead of enabling it through the `-m` flag in each command?

**Comment by Zebradil** [comment]
It can be enabled by default via `FZF_DEFAULT_OPTS`.
That's what I have in my `~/.zshrc`:

```sh
export FZF_DEFAULT_OPTS='--multi --no-height --extended'
```

**Comment by KUGA2** [comment]
Is there a way to like _force_ multi mode? 
- ENTER not quit but select
- use SHIFT+ENTER to quit

Well not force but more like nudging the user into knowing that you are supposed to select multiple here (e.g. for git add)
