### ISSUE TITLE
Prompt type and colors in Windows

### ISSUE THREAD

**Issue by electric-ladyland** [junegunn/fzf.vim#486]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm thrilled fzf and fzf.vim is coming to Windows (thank you). I have two machines (both Windows 10 64) and using Vim 8 (gVim). On one machine fzf.vim (e.g. :Files) opens an external command prompt, on the other it opens some kind of embedded prompt inside gVim. What is causing this difference (is it vim version or some OS setting?) Or some vim setting for this?

In either case, can I disable the colors used in the prompts? So far fzf.vim works great functionally but the colors are making it unusable. In the external command (cmd.exe) blue against black background is barely visible. In the embedded prompt, the yellows against white background are barely visible (see screenshot). I see `g:fzf_colors` but it's not clear how to use it or if it's what I need.
![2017-10-29 14_14_30-gvim](https://user-images.githubusercontent.com/32247136/32146803-9aa19a84-bcb3-11e7-8a3b-8a09128bda24.png)

**Comment by electric-ladyland** [comment]
I now realize this is because of new vim8 :terminal feature. Upgraded my vim and so both systems use embedded cmd.exe. Now tweaking g:fzf_colors resolves the issue. So there was no problem.

**Comment by cliffcrosland** [comment]
The solution above did not work for me because I use Neovim. However, you can edit the colorscheme of the FZF terminal by manually changing the `g:terminal_color_*` settings.

Here is how I changed that illegible yellow highlight line to a perfectly readable blue color:
```vim
let g:terminal_color_11 = '#0000ff'
```
