### ISSUE TITLE
Losing history order when applying `--query` flag in option

### ISSUE THREAD

**Issue by meain** [junegunn/fzf.vim#487]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

```vim
command! -bang History call fzf#vim#history( {'options': ['--query', '!.git/ !.vim/ ']}, <bang>0)
```

Using this command will result in the output not being sorted based on time.

**Comment by junegunn** [comment]
Although not ideal, you can add `--no-sort` to `options` so that fzf doesn't sort the result according to its scoring system.
