### ISSUE TITLE
Better way to do this?

### ISSUE THREAD

**Issue by ngocphamm** [junegunn/fzf.vim#490]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

This is really just a question.

I spent some time today to figure out how to add a new command to open FZF with a list of all files, including hidden, ignoring VCS ignore patterns, and below is how I did it.

So I have the default FZF command utilizing ripgrep.

```
export FZF_DEFAULT_COMMAND='rg --color never --files --hidden -g "" 2> /dev/null'
```

In neovim, however, sometimes I want all the files excluded by VCS ignore file, so I have this in `.config/neovim/init.vim`

```
command! -bang -nargs=* AFiles
  \ call fzf#run({'source': 'rg --files --hidden --no-ignore-vcs --glob "!.git/*" ', 'left': '~30%', 'sink': 'e'})
```

So far so good, with the only catch (I can see so far) is that I cannot use the `Ctrl-t/x/v` on selected item to open in in tab split/split/vsplit like I normally can with `:Files`. I'm not familiar at all with VimL, so I think there would be a better way to do this.

Anyone has a nicer solution, please let me know.

Much appreciated!

**Comment by junegunn** [comment]
Wrap the dictionary with `fzf#wrap` and you're all set.

```vim
fzf#run(fzf#wrap({'source': ... }))
```

See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

**Comment by ngocphamm** [comment]
Too good to be true! Thanks @junegunn
