### ISSUE TITLE
Weird characters shown on the first found entry of fzf.

### ISSUE THREAD

**Issue by jameshuynh** [junegunn/fzf.vim#491]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I am having an issue with Vim & Neovim on macOS High Sierra. When searching with fzf, it always come out with the first found entry shown with the encoded command and when I select that entry, it comes out a blank file. You can see the screenshot. Before this, I only use default fzf command but because I want to ignore files in .gitignore, hence I have added this line in my zshrc. I also tried with other export FZF_DEFAULT_COMMAND and even put this command inside vimrc or init.vim itself but still has the same issue.

```
export FZF_DEFAULT_COMMAND='ag -g ""'
```

Without this line, fzf.vim works perfectly fine but with this line it shows as my attached photo. 

![image](https://user-images.githubusercontent.com/29207/32362375-c1aa4902-c0a3-11e7-983e-05a6b3036eb4.png)

Another point is that when I run fzf from the command line, it works perfectly fine, i.e. it does not have the weird characters shown with the first found entry.

Really appreciate if anyone can help to tell me what I am doing wrong. Thanks.

**Comment by junegunn** [comment]
No idea what's happening. Can you reproduce the problem with the minimal Vim configuration suggested in the issue template?

**Comment by jameshuynh** [comment]
@junegunn I deleted all my plugins and setup a bare minimum .vimrc

```bash
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

set rtp+=/usr/local/bin/fzf
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'

call vundle#end()

map <c-p> :Files<cr>
let $FZF_DEFAULT_COMMAND='ag -g ""'
``` 

Yet, it still has the same issue. I think I only start to have this issue on High Sierra.

**Comment by junegunn** [comment]
Can you try it without FZF_DEFAULT_COMMAND and FZF_DEFAULT_OPTS?

By the way, you don't need both of these lines, either one should suffice.

```vim
set rtp+=/usr/local/bin/fzf
Plugin 'junegunn/fzf'
```

**Comment by jameshuynh** [comment]
Thanks @junegunn. It turns out this pure prompt https://github.com/sindresorhus/pure#install is the culprit. I turned off this and fzf is working perfectly now. Thank you so much for your prompt reply.
