### ISSUE TITLE
Add instruction with vundle

### ISSUE THREAD

**Issue by mickeyandkaka** [junegunn/fzf.vim#494]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm using spf13vim, and it uses vundle to manager the vim plugs.
Now I have install the fzf and insert it to my $PATH

however , when I install fzf.vim it doesn't work with my local fzf, I have to install the fzf in the vundle again , thus making it work.

How can I avoid it?

**Comment by junegunn** [comment]
fzf.vim currently requires the core vim plugin from the main fzf repository. Having fzf in $PATH is not enough.
https://github.com/junegunn/fzf#as-vim-plugin
