### ISSUE TITLE
How can I ignore certain paths for the :Files command?

### ISSUE THREAD

**Issue by danijar** [junegunn/fzf.vim#495]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I would like to exclude `.*/.git/.*` and `.*/__pycache__/.*` paths from `:Files`. Is this possible?

**Comment by stellarhoof** [comment]
#469, #453 should help

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#respecting-gitignore
