### ISSUE TITLE
Can :Files give preference to files relative to Vim's current working directory?

### ISSUE THREAD

**Issue by danijar** [junegunn/fzf.vim#496]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I would like to see local files listed first, especially before typing any characters to restrict the search. The list should still include external files as well.

**Comment by junegunn** [comment]
`:Files` command uses `$FZF_DEFAULT_COMMAND` to generate the list when it's defined, so if you have a command or script that lists files in the order you want, you can use it as the default command.

FYI: https://github.com/junegunn/fzf#respecting-gitignore
