### ISSUE TITLE
FZF window not appearing until keypress in Neovim in Docker when using shortcut

### ISSUE THREAD

**Issue by PhilT** [junegunn/fzf.vim#497]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'm putting together a docker image for my development environment as my base machine is Windows 10 and LSW is still too slow. Docker (for Windows, not toolbox) seems like quite a nice solution especially to easily run multiple projects. My Dockerfile is in this repo: https://github.com/PhilT/docker-neodev. It builds FZF and Neovim from master. I've also tried with the Alpine package.

The problem I have is pretty odd. When I run `:FZF` and press Enter the FZF terminal window shows up as expected. However, if I assign it to a key such as `nnoremap <C-p> :FZF<CR>` the terminal window does not appear until I press another key. I'm not sure this is really an FZF issue but thought I'd start here. I've tried with the minimal config and I get the same results.

**Comment by junegunn** [comment]
https://stackoverflow.com/questions/20828657/docker-change-ctrlp-to-something-else

This should answer your question.

**Comment by PhilT** [comment]
So sorry! I was sure I'd tried a different key mapping. Thank you, fixed now.
