### ISSUE TITLE
is it possible to use this plugin without a plugin manager

### ISSUE THREAD

**Issue by xxyxyx** [junegunn/fzf.vim#498]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi, I don't use plugin managers but I would still like to use your plugin.  I have installed the latest (0.17.1) fzf by downloading the binary.  I then downloaded the latest fzf.vim from the /plugin directory of the fzf project.  I placed that file in ~/.vim/plugin/fzf/fzf.vim.  After those two steps, ":FZF" works fine in vim.

I next try to install the other fzf.vim -- from this project -- by downloading the latest fzf.vim from the /plugin directory and placing it in ~/.vim/plugin/fzfvim/fzf.vim.  Now, when I try to use the ":File" command I get the following error:

Ambiguous use of user-defined command

And when I try to use the ":Lines" command I get the following error:

Unknown function: #fzf#vim#lines

Please if you don't mind provide some guidance.  I really want to use this plugin but I really don't want to have to use a plugin manager.

**Comment by junegunn** [comment]
Yes, it's totally possible, but I'd just use a plugin manager if I don't have enough knowledge on how Vim plugin system works. If you decided not to rely on a plugin manager - I believe you have a good reason - you just can't avoid studying how to set things up properly.

**Comment by eoporto** [comment]
To install without plugin manager

Tested date:  Nov 16 2019

##Install FZF in your home directory
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

##add fzf.vim to vim
git clone git@github.com:junegunn/fzf.vim.git ~/.vim/bundle/fzf.vim

##add to .vimrc
set runtimepath^=~/.fzf
set runtimepath^=~/.vim/bundle/fzf.vim

**Comment by cmstoddard** [comment]
> To install without plugin manager
> 
> Tested date: Nov 16 2019
> Vim version: 7.4
> 
> ##Install FZF in your home directory
> 
> ```
> git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
> ~/.fzf/install
> ```
> 
> ##add fzf.vim to vim
> `git clone git@github.com:junegunn/fzf.vim.git ~/.vim/bundle/fzf.vim`
> 
> ##add to .vimrc
> 
> ```
> set runtimepath^=~/.fzf
> set runtimepath^=~/.vim/bundle/fzf.vim
> ```
> 
> And in vim use command:
> `:Files`

hey, I know this is from 2 years in the future, but this was super helpful. Thanks!

**Comment by caseycronyn** [comment]
With the native vim 8 package system, you can clone the fzf.vim repo to a folder located at `~/.vim/pack/junegunn/start` (or similar), then add `set rtp+=/opt/homebrew/opt/fzf` (or wherever your fzf is located) to your .vimrc and it should work fine.
