### ISSUE TITLE
Use Ag with arguments and preview

### ISSUE THREAD

**Issue by cryptomaniac512** [junegunn/fzf.vim#499]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I [found](https://github.com/junegunn/fzf.vim/issues/92#issuecomment-229883364) cool function that allows me passing arguments to `Ag` command, but it does not work with preview function [described](https://github.com/junegunn/fzf.vim#advanced-customization) in README.
How can I make it works? I have no great experience with VimL and don't know how to make it works :(

**Comment by cryptomaniac512** [comment]
I am about [this](https://github.com/junegunn/fzf.vim/issues/92#issuecomment-191248596) function
```VimL
function! s:ag_with_opts(arg, bang)
  let tokens  = split(a:arg)
  let ag_opts = join(filter(copy(tokens), 'v:val =~ "^-"'))
  let query   = join(filter(copy(tokens), 'v:val !~ "^-"'))
  call fzf#vim#ag(query, ag_opts, a:bang ? {} : {'down': '40%'})
endfunction

autocmd VimEnter * command! -nargs=* -bang Ag call s:ag_with_opts(<q-args>, <bang>0)
```
and [this](https://github.com/junegunn/fzf.vim#advanced-customization)
```VimL
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```

I do not have a good knowledge of VimL... Help me, how to use both of these features?

**Comment by junegunn** [comment]
I suggest that you just use `fzf#vim#grep` function instead of `fzf#vim#ag` with escapes options.

You can adjust the `:Rg` example in the following link to use `ag` instead.

https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by cryptomaniac512** [comment]
@junegunn, like this?
```viml
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(
  \   '',
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```
