### ISSUE TITLE
Problem with :Tags

### ISSUE THREAD

**Issue by akarl818** [junegunn/fzf.vim#5]
The only output I get is `Binary file (standard input) matches`.

I have hunted the issue to [this line](https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L382).

I get the same issue when I run it in my terminal though, so it might be a perl issue.

**Comment by junegunn** [comment]
The output is from `grep`. Looks like your tags file is recognized as a binary file, what's the output of `tagfiles()` and is the file a correct ctags file?

**Comment by akarl818** [comment]
the output is `['tags', '/Users/andreas/.virtualenvs/api/lib/python2.7/site-packages/tags']` and it just chooses the first one. I can cat the file without problem and vim can read the files.

**Comment by junegunn** [comment]
`cat tags | grep -v "^!"`?

**Comment by akarl818** [comment]
Yep `Binary file (standard input) matches`

**Comment by junegunn** [comment]
Ah okay, so we need this:

```
     -a, --text
             Treat all files as ASCII text.  Normally grep will simply print ``Binary file ... matches'' if files contain binary characters.  Use of this option forces grep to output lines matching the specified pattern.
```

**Comment by akarl818** [comment]
Hmm, alright. It was something wrong with my tags file, I regenerated it and now it works fine.

But another thing, should it not use all the tags files?

**Comment by junegunn** [comment]
I was going to add the `-a` switch to the grep command but I was busy with something else. And since you said that the problem is gone after regeneration, maybe I shouldn't?

> But another thing, should it not use all the tags files?

Yeah, that was my initial idea. The file paths in tags file are given in relative paths, so both sink and source options should be updated to do some extra work to figure out the actual path.

**Comment by akarl818** [comment]
> I was going to add the -a switch to the grep command but I was busy with something else. And since you said that the problem is gone after regeneration, maybe I shouldn't?

No I think the problem was my fault.

> Yeah, that was my initial idea. The file paths in tags file are given in relative paths, so both sink and source options should be updated to do some extra work to figure out the actual path.

Yea, I see. That complicates it I guess.
