### ISSUE TITLE
Fzf with arg or with word under cursor

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#50]
Is it possible to call fzf or fzf#tags with the word under the cursor or pass an argument to fzf.vim so that it expands fzf with the argument?  If not, how difficult would this be to implement?

**Comment by danihodovic** [comment]
Seems like the plugin is pretty extensible. I got it to work with

```
fu! FzfTagsCurrWord()
  let currWord = expand('<cword>')
  if len(currWord) > 0
    call fzf#vim#tags({'options': '-q ' . currWord})
  else
    execute ':Tags'
  endif
endfu
```

**Comment by junegunn** [comment]
Nice, you can further simplify the code like follows, no need for if-else branch:

```vim
call fzf#vim#tags({'options': '-q '.shellescape(expand('<cword>'))})
```
Note that `:Tags` command passes layout option as well.

```vim
call fzf#vim#tags({'options': '-q '.shellescape(expand('<cword>')), 'down': '~40%'})
```

Is there anything else you want to know?

**Comment by danihodovic** [comment]
Cool!

Is it possible to do this with :Ag too? Provide the word under cursor or a visual selection?

**Comment by junegunn** [comment]
This is what I have in my .vimrc.
```vim
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
```
Looks like we can now close the issue.

**Comment by danihodovic** [comment]
:+1:

**Comment by cj** [comment]
@junegunn when I try your solution in nvim I get this error ![](http://image.prntscr.com/image/3e69025300dc4e14902d92bbe118c4cc.png)

**Comment by junegunn** [comment]
@cj Right, the function signature was changed in https://github.com/junegunn/fzf.vim/commit/b9285c87db7273a3a8c700c29c5e7910868392dd

So you can now simply do this:

```vim
call fzf#vim#tags(expand('<cword>'))
```

**Comment by cj** [comment]
@junegunn ah, there we go.  thank you!

**Comment by tuyenpm9** [comment]
@junegunn : it's beautiful.

**Comment by xarthna** [comment]
Taking cues from this thread, I mapped over `<c-]>` to act like `:tjump` to jump to the tag if a single match or open it with FZF otherwise:

```vim
function! FzfTagsCurrentWord()
  let l:word = expand('<cword>')
  let l:list = taglist(l:word)
  if len(l:list) == 1
    execute ':tag ' . l:word
  else
    call fzf#vim#tags(l:word)
  endif
endfunction

noremap <c-]> :call FzfTagsCurrentWord()<cr>
```

**Comment by shaypal5** [comment]
Just adding for those preferring to search the current word in `:Ag`:

```vim
" map <Leader>+F to search in ag the word under the cursor
map <Leader>F :call fzf#vim#ag(expand('<cword>'))<kEnter>
```

**Comment by martinklepsch** [comment]
This is pretty awesome! Is there a way to have it show the preview like `:Ag` does as well?

**Comment by shaypal5** [comment]
Awesome! I stole your version! Why `Rg` and not `Ag`, though?

**Comment by nornagon** [comment]
Here's what I ended up with to ripgrep for the _token_ under the cursor (i.e. the whole word, not as a substring of another token):

```vim
nnoremap <silent>+ :call fzf#vim#grep(
  \ "rg --column --line-number --no-heading --color=always --smart-case -- "
  \ . fzf#shellescape('\b'.expand('<cword>').'\b'),
  \ fzf#vim#with_preview(), 0)<cr>
```

(it's too bad there's no `fzf#vim#rg` like there is `fzf#vim#ag`, that would have made this snippet a lot shorter! As it is, this is copied from the definition of `:Rg`, as below)

https://github.com/junegunn/fzf.vim/blob/1e054c1d075d87903647db9320116d360eb8b024/plugin/fzf.vim#L63
