### ISSUE TITLE
Change theme or use no colours with g:fzf_colors?

### ISSUE THREAD

**Issue by umayr** [junegunn/fzf.vim#502]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible to change theme (or use no colour option `bw`) using `g:fzf_colors`? Currently I have an alias set, which works fine in my case whenever I try to invoke it directly, but there are other plugins that utilises fzf and they try to set colours within (using `fg`, `bg` etc). I'm trying to find out a way to override this behaviour.

**Comment by junegunn** [comment]
Adding `--no-color` to `$FZF_DEFAULT_OPTS` will prevent any further overrides.

```sh
fzf --no-color --color bg:#ff9900
export FZF_DEFAULT_OPTS='--no-color'
fzf --color bg:#ff9900
```
