### ISSUE TITLE
Error: "Can't find directory" when invoke :Tags

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf.vim#504]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I got this error when try to go to a tag in other file,[ pic](https://imgur.com/a/NqzGl)  
With `>gvim -u NORC` I got error link [this](https://imgur.com/a/xlxKq) when try to trigger `:Tags`

**Comment by tuyenpm9** [comment]
gvim also freezed right after go to a tag.

**Comment by janlazo** [comment]
For first error, did you generate the tags file before running `Tags`?
For second error, `set nocp` is required before sourcing a file in `autoload/`

**Comment by tuyenpm9** [comment]
@janlazo : Yes, I generated tags with `:Tags`. Actually the tagged file is opened but it also echoes the error message - open file by seconds, it's really slow.

**Comment by tuyenpm9** [comment]
For more: under homeuser I try `gvim.exe -u NONE --cmd "set nocp | set rtp+=~/vimfiles/pack/plugins/start/fzf,~/vimfiles/pack/plugins/start/fzf.vim | runtime! plugin/fzf.vim"`  
Then trigger `:Tags` on project that tagged with `:Tags` command before, go to a tagged file some files is  freezed when try to open - not responding but some others opened immediately. Even run `:Tags` command take some times, it shows `293/293` - I assume this is number of tagged objects.

**Comment by janlazo** [comment]
Thanks. It failed on lcd because of the extra double slashes but the tags file does not have extra slashes.

**Comment by janlazo** [comment]
Porting https://github.com/junegunn/fzf/commit/7727ad43afb57cb325439590a9a6bad94601a720#diff-24d9d57e35df5afce7890f2400917919 for `Tags` should fix it.

**Comment by tuyenpm9** [comment]
No error messages now when run with fzf, fzf.vim plugin but still slow/not responded when run `:Tags` or open some files - even with file < 20 lines of code. I believe it happens randomly.  
Weird that if I run with full vimrc I still got the error message:  
`Vim(cd): E344: Can't find directory XXXX in cdpath`  
and one more mesg:
`E472: Command failed`

**Comment by junegunn** [comment]
@tuyenpm9 Did you manually apply the patch before I merged it?

**Comment by tuyenpm9** [comment]
Yes, I have below lines in  `plugin/fzf.vim`:  
```
  let path = fnameescape(a:path)
  return s:is_win ? escape(path, '$') : path
```  
fzf binary is up-to-date.

**Comment by junegunn** [comment]
I asked you because you commented before I merged @janlazo's pull request. You can now just pull fzf.vim repo.

So it doesn't fix your problem?

**Comment by tuyenpm9** [comment]
You're right, I've missed that. Work perfect now. Thanks all.
