### ISSUE TITLE
How to have fuzzy matching vim normal commands with fzf.vim

### ISSUE THREAD

**Issue by sadid** [junegunn/fzf.vim#507]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

How can I have fuzzy match for vim commands in normal mode? Is this possible? I mean something like spacemacs/helm which you just type part of the command then <tab> and finally you shown possible commands in normal mode to execute. 

For example consider I want to issue `:TableModeEnable` in the vim. I just type 'table' or 'mode' and press tab or some other key binding and then relevant options be shown. Currently I've to exactly type the `:Table` to see relevant results.

**Comment by junegunn** [comment]
`:Commands` command is the closest.
