### ISSUE TITLE
only one record in macOS

### ISSUE THREAD

**Issue by sijad** [junegunn/fzf.vim#508]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

in https://github.com/junegunn/fzf.vim/blob/004af251507ade4e86e308a58ca9d69229a0dcec/autoload/fzf/vim.vim#L514 `s:is_win` is false in my environment so `| uniq` will add to `source`, but  `git ls-files -z` output is only one line.

* `| uniq` should be removed
* or all `\0` should replaced with `\n` in output and then pipe to `| uniq`

**Comment by junegunn** [comment]
It was my oversight, I reverted the commit.
