### ISSUE TITLE
Supply additional arguments to :Ag

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#51]
Is it possible to supply additional arguments to `:Ag` such as `-Q` and `-t` in order to search .gitignored files?  I'm guessing that the `source` dict key decides the source of `:Ag` and that can't be modified.
https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L404-L405

**Comment by junegunn** [comment]
Sounds like a reasonable suggestion. Currently `:Ag -Q foobar` will search for `-Q foobar` as the query. If we make `:Ag` command take command-line options, it will be impossible to support queries that start with a dash without escaping of it. e.g.`:Ag --foobar`

**Comment by junegunn** [comment]
```patch
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index a38a4b9..2ccb63e 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -400,9 +400,19 @@ function! s:ag_handler(lines)
 endfunction
 
 function! fzf#vim#ag(query, ...)
+  let ag_opts = ''
+  let query = ''
+  for token in split(a:query, '\s\+\zs')
+    if empty(query) && token =~ '^-'
+      let ag_opts .= token
+    else
+      let query .= token
+    endif
+  endfor
+
   return s:fzf(fzf#vim#wrap({
-  \ 'source':  printf('ag --nogroup --column --color "%s"',
-  \                   escape(empty(a:query) ? '^(?=.)' : a:query, '"\-')),
+  \ 'source':  printf('ag --nogroup --column --color %s "%s"',
+  \                   ag_opts, empty(query) ? '^(?=.)' : query),
   \ 'sink*':    s:function('s:ag_handler'),
   \ 'options': '--ansi --delimiter : --nth 4..,.. --prompt "Ag> " '.
   \            '--multi --bind ctrl-a:select-all,ctrl-d:deselect-all '.
```

This is something we can try. With this, one will have to escape queries starting with a dash, e.g. `:Ag \--foobar`, or it will be passed as an ag option. One issue I noticed with the change is you can't use `:Ag -Q`, since in that case the dummy regular expression we use to match every line no longer works.

**Comment by danihodovic** [comment]
A cleaner solution may be to provide additional arguments to the `fzf#vim#ag`query that will be the `ag` options. But if this is in line with the rest of the plugin functions and if it solves the majority of the use cases I'm ok with this solution too.

**Comment by junegunn** [comment]
Yep, it's cleaner and more explicit. I just figured that one would usually want to apply the options dynamically instead of having to define a set of commands for different combinations of options.

**Comment by danihodovic** [comment]
Whatever floats the boat and solves the majority of the use cases. If dynamically parsing the arguments doesn't solve the problem I guess you could always resort to calling `s:fzf`?

**Comment by danihodovic** [comment]
I managed to get a solution going by providing a dict with the `source` key to `fzf#vim#ag`. It's hardcoded, but solves my problem.

```vimscript
fu! FzfAgCustom(mode)
  if a:mode ==# 'n' || a:mode ==# 'v'
    if a:mode ==# 'n'
      let query = escape('^(?=.)', '"\-')
    elseif a:mode ==# 'v'
      let query = escape(Get_visual_selection(), '"\-')
    endif

    let ag_opts = 'ag --nogroup --column --color -t "%s"'
    let source = printf(ag_opts, query)
    call fzf#vim#ag('', {'source': source})
  endif
endfu
```

Interestingly it caused a segfault for very large directories
![fzf-segfault](https://cloud.githubusercontent.com/assets/5557301/11615737/58ac3fba-9c69-11e5-8357-0633ed9eafa7.png)

**Comment by junegunn** [comment]
Hmm, considering that the majority of the users are just okay with the default options, I think it's a reasonable decision that we leave `:Ag` command unchanged, but add an additional argument to `fzf#vim#ag` function, so that ones with some vim script knowledge can customize to their needs.

The segmentation fault should be a bug of ag.

**Comment by init-random** [comment]
This can be done with just a new command. Below is what I use for a [G]lob[G]rep.
```
command! -bang -nargs=* GG
  \ call fzf#vim#grep(
  \   'rg --column --line-number --smart-case --no-heading --type-not jupyter --type-not gzip --color=always -g ' . <q-args> . ' ' . shellescape(''), 1,
  \   <bang>1 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?')
  \           : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%'),
  \   <bang>1)
```
The interesting part here is the `. <q-args> . ' ' . shellescape('')`. In the case above, this puts of the argument of `GG` in the `rg` command and the search text sent to `fzf` is `''`, which is the default search text. 

So the use case here is 
`:GG *.tex`
press enter and fzf searches within just `*.tex` files. 

The idea here is to leverage `<q-args>` as parameters for the grep command, send in an empty string as an initial search, and then use fzf to find what you are looking for.

By changing this slightly you could add various parameters of your choice to the grep command.
