### ISSUE TITLE
Error when attempting to open file via fzf when current buffer has unsaved changes

### ISSUE THREAD

**Issue by simon-bigsofa** [junegunn/fzf.vim#510]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim (0.2.1)

`Error detected while processing function 21[30]..<SNR>32_callback:`
`line   33:`
`Vim(edit):E37: No write since last change (add ! to override)`

I would expect to see the `Vim(edit):E37...` line but also getting the `Error detected while processing function...` message.

**Comment by junegunn** [comment]
It's not easy to fix the message, you'll have to just deal with it, or you can `set hidden` and never see the message again.

**Comment by dagadbm** [comment]
even after set hidden this still happens sometimes... i have to save the file to be able to change. no idea why
