### ISSUE TITLE
Pass multiple directories to `:Files`?

### ISSUE THREAD

**Issue by anhari** [junegunn/fzf.vim#511]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ x] Neovim

Is it possible to pass multiple directories to `:Files`?  I work in a few different frameworks that mostly follow the MVC pattern, but they have different directory structures.  I'd like to pass multiple directories to `:Files` so I can setup a single leader key for looking up similar files in multiple directories.

For example, I'd like to bind `<leader>ft<cr>` to look up test files in all of the following:
- `spec/`
- `test/`
- `tests/`

**Comment by junegunn** [comment]
It's not supported, but you can easily define your own custom commands using fzf#run and fzf#wrap functions. For example,

```vim
command! -bang MyFoo call fzf#run(fzf#wrap({ 'source': 'echo foo'}, <bang>0))
```

See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun for details.

**Comment by seb-mueller** [comment]
Also for the record another useful approach is to save a list file directories externally in a shell variable:
```sh
export MYPATHS="~/dotfiles ~/code ~/more/files"
```

Then pass it on in vim (using `ripgrep --files` here):
```
command! -bang MyFoo call fzf#run(fzf#wrap({ 'source': 'rg --files ' . $MYPATHS, 'sink': 'e'}, <bang>0))
```
This way the list of dirs can be easily changed  without having to change the vimrc.
