### ISSUE TITLE
how do I exclude files from fzf leader-t command?

### ISSUE THREAD

**Issue by barkanido** [junegunn/fzf.vim#514]
I mean the :Files command. 

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

**Comment by junegunn** [comment]
`:Files` command uses `FZF_DEFAULT_COMMAND` when it's defined. Check out https://github.com/junegunn/fzf#respecting-gitignore
