### ISSUE TITLE
Open search in buffers?

### ISSUE THREAD

**Issue by drapergeek** [junegunn/fzf.vim#515]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I apologize if this is documented. I tried searching and couldn't find anything. Is there anyway to move from `:Ag <something>` to having those in buffers? I'd like to open my ag search and traverse the entire list.

Thanks in advance, I'm loving this plugin!

**Comment by danihodovic** [comment]
Alt+a, Enter should select all items and open them in buffers.

**Comment by drapergeek** [comment]
@danihodovic thank you so much!
