### ISSUE TITLE
Copying commit sha-1 from fzf :Commits output

### ISSUE THREAD

**Issue by amalbuquerque** [junegunn/fzf.vim#516]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Let me start by thanking you for fzf and fzf.vim, it's incredible! One thing I miss is the possibility of copying the commit sha-1 of the highlighted commit. I've seen fzf has the `C-y` default action binded to yank, but it doesn't work (at least inside Vim).
How can I extend those :BCommits and :Commits commands to yank that commit sha-1 with `C-y`?
Or alternatively, how can one add a new custom action which, when triggered, would receive as input the current highlighted line (or all the selected lines, if that's the case)?

If you can just put me in the right direction, I can try to implement this by myself.

Thanks in advance!

**Comment by junegunn** [comment]
> fzf has the C-y default action binded to yank

That "yank" is not related to Vim, it's a readline binding used inside fzf. e.g. `CTRL-W` to delete a word, `CTRL-Y` to paste the deleted word.

So you want to copy the commit hash (multiple hashes when multiple lines selected with tab or shift-tab) to the register of Vim, right? This is something I can do:

```diff
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index 9f83e6c..6c70eda 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -1043,16 +1043,29 @@ endfunction
 " ------------------------------------------------------------------
 " Commits / BCommits
 " ------------------------------------------------------------------
+function! s:yank_to_register(data)
+  let @" = a:data
+  silent! let @* = a:data
+  silent! let @+ = a:data
+endfunction
+
 function! s:commits_sink(lines)
   if len(a:lines) < 2
     return
   endif
 
+  let pat = '[0-9a-f]\{7,9}'
+
+  if a:lines[0] == 'ctrl-y'
+    let hashes = join(filter(map(a:lines[1:], 'matchstr(v:val, pat)'), 'len(v:val)'))
+    return s:yank_to_register(hashes)
+  end
+
   let diff = a:lines[0] == 'ctrl-d'
   let cmd = s:action_for(a:lines[0], 'e')
   let buf = bufnr('')
   for idx in range(1, len(a:lines) - 1)
-    let sha = matchstr(a:lines[idx], '[0-9a-f]\{7,9}')
+    let sha = matchstr(a:lines[idx], pat)
     if !empty(sha)
       if diff
         if idx > 1
@@ -1098,8 +1111,8 @@ function! s:commits(buffer_local, args)
   \ 'sink*':   s:function('s:commits_sink'),
   \ 'options': ['--ansi', '--multi', '--tiebreak=index', '--reverse',
   \   '--inline-info', '--prompt', command.'> ', '--bind=ctrl-s:toggle-sort',
-  \   '--header', ':: Press '.s:magenta('CTRL-S', 'Special').' to toggle sort',
-  \   '--expect='.expect_keys]
+  \   '--header', ':: Press '.s:magenta('CTRL-S', 'Special').' to toggle sort, '.s:magenta('CTRL-Y', 'Special').' to copy commit hashes',
+  \   '--expect=ctrl-y,'.expect_keys]
   \ }
 
   if a:buffer_local
```

**Comment by amalbuquerque** [comment]
Thanks for the quick reply, it's exactly that! Many thanks!
