### ISSUE TITLE
Lines command not working

### ISSUE THREAD

**Issue by klingberg** [junegunn/fzf.vim#52]
It seems like the "Lines" and "BLines" commands has stopped working properly (see screenshot)?
Tested with the latest version of Neovim.

Everything else works like a charm! :)

![fzf](https://cloud.githubusercontent.com/assets/1440293/11715767/e1d069a0-9f44-11e5-80e3-063029bdc870.png)

**Comment by junegunn** [comment]
```
unknown option: --tabstop=4
```
`--tabstop` option was added in fzf 0.11.1, you must be using an old version.

**Comment by klingberg** [comment]
Yes, you are right! I have the latest Homebrew version which is 0.10.9.
Then I just have to wait for a bit :)
Sorry for the trouble!

**Comment by junegunn** [comment]
> Then I just have to wait for a bit

Or you can send a PR to update the Homebrew registry :)

e.g. https://github.com/Homebrew/homebrew/pull/45720
