### ISSUE TITLE
`History:` and `History/` seem to run synchronously

### ISSUE THREAD

**Issue by Alok** [junegunn/fzf.vim#520]
My vim command line history has about 6200 lines and my search history has almost the same amount. I've noticed that `History/` and `History:` both seem to wait until all 6000 lines are loaded before opening up the curses interface, which leads to a definite pause that none of the other fzf commands I use seem to have.

**Comment by junegunn** [comment]
Yes, they are synchronous, so are Lines, BLines, Commands, Map, etc, because we use Vimscript to generate the input list for those commands. We can make them asynchronous if we can come up with external command that can be used instead.

**Comment by justinyhuang** [comment]
Sorry for commenting on a closed topic, but i am thinking about using an external command, maybe like "cat" in shell, to feed the source with the file content of current buffer?
If it is possible could you shed some light on how to call fzf#run with 'source' set to 'cat <current file>'?

Thanks!
