### ISSUE TITLE
Fzf freezes using Neovim appimage

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#521]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

A detailed bug report can be found here: https://github.com/neovim/neovim/issues/7620

**Comment by stsewd** [comment]
I'm having the same problem.

I think this is a duplicate of #505

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/8104 was fixed in Nvim 0.3.1 (prerelease).
