### ISSUE TITLE
Ripgrep support in addition to Silver Searcher (Ag)

### ISSUE THREAD

**Issue by wakatara** [junegunn/fzf.vim#523]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

Would be awesome if :Rg was supported in the vim plugin in much the same way as Ag. Faster, simpler, more grep-y.

**Comment by junegunn** [comment]
You can define your own commands using `fzf#vim#grep` function. (I'm not interested in adding more commands to this repository)

https://github.com/junegunn/fzf.vim#advanced-customization
