### ISSUE TITLE
:Directories command

### ISSUE THREAD

**Issue by micalexander** [junegunn/fzf.vim#525]
- Category
    - [ x] Question
    - [ ] Bug
    - [x ] Suggestion
- OS
    - [ x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

Would be nice if there were a `:Directories` command. Use case would be the ability to fuzzy search through directories to open in Netrw.

Any help with this would be greatly appreciated.

**Comment by mcmillion** [comment]
This would be awesome! One of my patterns is to navigate to a folder via netrw to create or rename files. This would be awesome to fuzzyfind that folder and pop open a netrw window!

**Comment by thornycrackers** [comment]
:+1:  I would also be interested in this. I know you can pipe `find -type d | fzf` I just don't know how to do it with this plugin.

**Comment by unphased** [comment]
Tried my hand ```command! -bang Directories call fzf#vim#grep("find -type d", 0, {'options': '--prompt "Directories> "'}) ``` Doesn't work. 😕

**Comment by junegunn** [comment]
```vim
call fzf#run(fzf#wrap({'source': 'find * -type d'}))
```

Guys, please read the manual here: https://github.com/junegunn/fzf/blob/master/README-VIM.md

**Comment by thornycrackers** [comment]
@junegunn Thank you!
