### ISSUE TITLE
Configure Ag highlight color

### ISSUE THREAD

**Issue by jakecraige** [junegunn/fzf.vim#526]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm wondering if there's a way to configure the fzf highlight color when selecting from Ag output. 

I've attached three images showing what I see, one with default ag colors and one with them configured to make it more readable, last with fzf colors configured to a green. 

The issue is that when I have one of them selected with fzf, it is a dark grey and I can't read the filename anymore. I'm wondering how I can configure this.

For testing, I attempted setting every color to a known green in the config, but that didn't change the highlight color of the file name. Here's the config I used:

```vim
      let g:fzf_colors =
            \ { 'fg':      ['fg', 'Include'],
            \ 'bg':      ['bg', 'Include'],
            \ 'hl':      ['fg', 'Include'],
            \ 'fg+':     ['fg', 'Include', 'Include', 'Include'],
            \ 'bg+':     ['bg', 'Include', 'Include'],
            \ 'hl+':     ['fg', 'Include'],
            \ 'info':    ['fg', 'Include'],
            \ 'border':  ['fg', 'Include'],
            \ 'prompt':  ['fg', 'Include'],
            \ 'pointer': ['fg', 'Include'],
            \ 'marker':  ['fg', 'Include'],
            \ 'spinner': ['fg', 'Include'],
            \ 'header':  ['fg', 'Include'] }
```

Here's the gist I used for testing including my custom Ag command, though likely irrelevant to this issue: https://gist.github.com/jakecraige/6bc72778abd1210c43ac23b373332021.

<img width="139" alt="screen shot 2017-11-27 at 1 47 06 pm" src="https://user-images.githubusercontent.com/3799709/33291316-446581a2-d37a-11e7-976b-356799eff04b.png">

![screen shot 2017-11-27 at 1 47 49 pm](https://user-images.githubusercontent.com/3799709/33291324-4b4f3530-d37a-11e7-95bb-014ca18267d1.png)

![screen shot 2017-11-27 at 1 42 15 pm](https://user-images.githubusercontent.com/3799709/33291329-51a34548-d37a-11e7-94d1-5123a3e86b5a.png)

**Comment by tuyenpm9** [comment]
You may try to `:hi` to find out its colorcode. It's from colorscheme.

**Comment by tuyenpm9** [comment]
I couldn't change any colors in fzf_colors dict:
```
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
``` 
fzf_colors is called here https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L254-L255  
@junegunn : Could you have a comment on this?

What I've tried:
```  " let g:fzf_colors =
" \ { 'fg':      ['#ffffea'],
  " \ 'bg':      ['#ffffea'],
  " \ 'hl':      ['#ffffea'],
  " \ 'fg+':     ['#ffffea', '#ffffea', '#ffffea'],
  " \ 'bg+':     ['#ffffea', '#ffffea'],
  " \ 'hl+':     ['#ffffea'],
  " \ 'info':    ['#ffffea'],
  " \ 'border':  ['#ffffea'],
  " \ 'prompt':  ['#ffffea'],
  " \ 'pointer': ['#ffffea'],
  " \ 'spinner': ['#ffffea'],
  " \ 'header':  ['#ffffea'] }

  " let g:fzf_colors =
" \ { 'fg':      ['Comment'],
  " \ 'bg':      ['Comment'],
  " \ 'hl':      ['Comment'],
  " \ 'fg+':     ['Comment', '#ffffea', '#ffffea'],
  " \ 'bg+':     ['Comment', '#ffffea'],
  " \ 'hl+':     ['Comment'],
  " \ 'info':    ['Comment'],
  " \ 'border':  ['Comment'],
  " \ 'prompt':  ['Comment'],
  " \ 'pointer': ['Comment'],
  " \ 'spinner': ['Comment'],
  " \ 'header':  ['Comment'] } ```

**Comment by rickywu** [comment]
I have the same issue, how should I define colors for gvim?

**Comment by kyoz** [comment]
Is this issue have support now ?. I have fzf colors config in my [purify theme](https://github.com/kyoz/purify) too. But it seem doesn't completely apply with Ag result:

Here's the config:

```
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'String'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'info':    ['fg', 'Keyword'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Statement'],
  \ 'pointer': ['fg', 'Statement'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

This is the result of `:Files`:
![pic-selected-191007-1324-55](https://user-images.githubusercontent.com/29815830/66289049-ae4e8300-e905-11e9-8524-13aba8fed142.png)

And this is the result of `:Ag`:
![pic-selected-191007-1325-20](https://user-images.githubusercontent.com/29815830/66289059-b4446400-e905-11e9-9064-2aaabecaf587.png)

**Comment by michael-angelozzi** [comment]
This is my work around, select a term color from a [colour table](https://vimawesome.com/plugin/xterm-color-table-vim)

For example to set the normal foreground to white (#15) and background to dark red (#88):
- PS the guifg / guibg is not used, just fore ref/future

```
hi _FzfNormal guifg=#FFFFFF guibg=#330000 ctermfg=15 ctermbg=88

let g:fzf_colors =
            \ { 'fg':    ['fg', '_FzfNormal'],
            \ 'bg':      ['bg', '_FzfNormal'],
            ....
            \ 'header':  ['fg', '_FzfHeader']}
```

**Comment by junegunn** [comment]
Those colors are determined by ag. Excerpt from `man ag`:

```
       --color-line-number
              Color codes for line numbers. Default is 1;33.

       --color-match
              Color codes for result match numbers. Default is 30;43.

       --color-path
              Color codes for path names. Default is 1;32.
```

There's no easy way to pass these arguments to ag. You'll have to experiment with `ag_raw` function

```vim
command! -bang -nargs=+ -complete=file Ag call fzf#vim#ag_raw('--color-path "1;31" '.shellescape(<q-args>), <bang>0)
```

**Comment by flybayer** [comment]
@junegunn where do we need to put that `command!` string?

I've tried many things, and I'm still unable to change the Fzf results.

As a workaround I'd be happy to totally disable colors in the fzf results, but I can't figure out how to do this either.
