### ISSUE TITLE
:Files new file

### ISSUE THREAD

**Issue by Yamakaky** [junegunn/fzf.vim#53]
Is it possible, while using `:Files`, to create a new file ?

**Comment by vasspilka** [comment]
Why not use :e instead?

**Comment by junegunn** [comment]
Sorry for the late reply, I lost track of the issue for some reason. We can make commands perform extra action using `--expect` option of fzf, but I don't see how we can integrate file creation into `:Files` command in a straightforward way.

**Comment by haberdashPI** [comment]
I understand why this might be hard to implement, and not really part of the design, however, there are plenty of fuzzy file finding interfaces that *do* accomplish this. See CtrlP for vim or Ivy for emacs. 

The basic way this works is that you use the fuzzy behavior to select a specific *directory* quickly, and then specify a new file name.
