### ISSUE TITLE
Use fzf with :split commands?

### ISSUE THREAD

**Issue by navdeepio** [junegunn/fzf.vim#530]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Any way to do it?

**Comment by junegunn** [comment]
It's not possible to use it directly with those commands. You can, however, use `window` option to specify a custom layout based on Vim commands.

```vim
call fzf#run(fzf#wrap({'window': '15split'}))
```
