### ISSUE TITLE
Question regarding `:Tag` and `call cursor` in tags file

### ISSUE THREAD

**Issue by pjrt** [junegunn/fzf.vim#531]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hi, I'm the creator of Stags (https://github.com/pjrt/stags), which is a tags generator for Scala and I'm having issues getting `:Tag` working correctly with the tags Stags creates. 

When it generates tags it doesn't use the `/some-search/` command to move to where the tag is (which is the common way a lot of tags generators do it). Instead it uses `call cursor` like so: `https://github.com/pjrt/stags/blob/master/stags/src/main/scala/co/pjrt/stags/Tag.scala#L68.

The reason I'm using that is because with `call cursor` I can get both line and column positions. Vim/Neovim understand this just fine (and move the cursor to the correct place) but for some reason `:Tag` only partly understand it. 

When I run `:Tag` with such a tag file and select a tag, it takes me to the correct file, but it does not take me to the correct line-column (it just drops the cursor at the top of the file). 

Any idea why this is? Here's an example tag file generated with this tool. 

```
generatePackageScope	../stags/src/main/scala/co/pjrt/stags/TagGenerator.scala	call cursor(53, 15)"	file:	language:scala
generateTags	../stags/src/main/scala/co/pjrt/stags/TagGenerator.scala	call cursor(14, 7)"	language:scala
generateTagsForFile	../stags/src/main/scala/co/pjrt/stags/TagGenerator.scala	call cursor(17, 7)"	language:scala
generateTagsForFileName	../stags/src/main/scala/co/pjrt/stags/TagGenerator.scala	call cursor(33, 7)"	language:scala
generateValues	external-lib-src/com.lihaoyi.fastparse-utils_2.12:0.4.3/fastparse/utils/ElemSetHelper.scala	call cursor(8, 7)"	language:scala
generateValues	external-lib-src/com.lihaoyi.fastparse-utils_2.12:0.4.3/fastparse/utils/ElemSetHelper.scala	call cursor(17, 9)"	language:scala
Generator	external-lib-src/org.scalameta.trees_2.12:1.8.0/scala/meta/Trees.scala	call cursor(502, 14)"	language:scala
generator	external-lib-src/org.scalameta.parsers_2.12:1.8.0/scala/meta/internal/parsers/ScalametaParser.scala	call cursor(2258, 7)"	language:scala
Generator	external-lib-src/org.scalatest.scalatest_2.12:3.0.1/org/scalatest/prop/Generator.scala	call cursor(21, 21)"	language:scala
```

**Comment by junegunn** [comment]
Does it even work? The current code expects `;"` at the end of a command (I don't know if required by the spec, it's just a pattern I noticed when examining tags files generated using ctags)

https://github.com/junegunn/fzf.vim/blob/45d39f571154af856ebba8f77b818d714fcb4a2a/autoload/fzf/vim.vim#L787

**Comment by pjrt** [comment]
It does work (I've been using stags for almost a year now). That pattern is
there in order for tag files to be backwards compatible with vi. Stags
doesn't try to be backwards compatible with vi however (I don't think vi
even has a `call cursor`)

Though the spec is a bit weird. I tried to put the ; on the cursor command
but that didn't work (it complained about trailing characters). So I think
the documentation for that pattern is wrong (or at least badly worded).

**Comment by junegunn** [comment]
I was asking if `:Tags` command here works with tags files generated using your tool because it looks for a pattern that stags output does not have (`;"`). I edited a line in tags file generated with ctags as below

```
<Plug>(-fzf-complete-trigger)	autoload/fzf/vim.vim	call cursor(10, 20);"	m
```

and `:Tags` brings me to the exact position.

**Comment by pjrt** [comment]
Well yes, that does work with with `:Tags` but not with `:tag`. It returns a "trailing characters" error. 

The confusing thing is that `call cursor` (no `;"`) also doesn't work with `:tag` *even though `:h tags-file-format` says it should*. 

The ONLY way that I've gotten it to work with `:tag` is with `"` (no `;`). So I think vim's doc is wrong (or I'm reading it wrong). 

Now back to `:Tags`, I'm actually quite surprised that `call cursor(10, 20);"` works with `:Tags` but not with `:tag`

**Comment by junegunn** [comment]
Since now I know that the semicolon is not really required, I can easily make `:Tags` work with tags that do not have it.

**Comment by pjrt** [comment]
I made an issue against Vim to try to clear up the doc: https://github.com/vim/vim/issues/2402

**Comment by pjrt** [comment]
Tested 76926aa and it works. Thanks!
