### ISSUE TITLE
Simplify advanced customization with global variables

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf.vim#532]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion

Currently, if you need to configure any command prompt or reverse order you have to do something like this:

```vim
command! -bar -bang Commits :call fzf#vim#commits({'options': '--no-reverse'}, <bang>0)
```

This could be achieved much more easily if you can specify options for a specific command:

```vim
let g:fzf_commits_options = ['--no-reverse']
```

Custom user options must have the highest priority when merge with defaults.

**Comment by dtcyganok** [comment]
Is there now a simple way to customize the options (prompt, reverse) for fzf#vim#grep ?

**Comment by junegunn** [comment]
Thanks for the suggestion. Using global variables can be easier to use, but it's less flexible than using autoload functions. Moreover, introducing tens of variables is going to be a maintenance nightmare for me. So I don't want to go that route.

**Comment by dtcyganok** [comment]
Ok, it will be hard to maintain. Maybe add optional argument to all functions in `fzf#vim` scope?
