### ISSUE TITLE
Commands History: and History/ works slowly

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf.vim#535]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

The invocation of History(:/) commands takes several seconds before display list if command/search history contains few thousands lines. Is there any way to improve performance?

**Comment by junegunn** [comment]
It's inherently slow because we use Vimscript to generate the list. If we could come up with external commands that can be used instead, the performance will vastly improve, but I don't know if it's possible. Patches are welcome.

**Comment by dtcyganok** [comment]
Native vim command `:history` works fast. Maybe use something like this?
```vim
let hist = ""
redir => hist
history
redir END
```
And then parse string in hist variable

**Comment by kevinhwang91** [comment]
```log
FUNCTION  <SNR>128_ansi()
    Defined: ~/.config/nvim/plugged/fzf.vim/autoload/fzf/vim.vim:254
Called 6293 times
Total time:   1.238686
 Self time:   0.318529

count  total (s)   self (s)
 6293   0.424022   0.074264   let fg = s:get_color('fg', a:group)
 6293   0.489385   0.083420   let bg = s:get_color('bg', a:group)
 6293   0.277577   0.113143   let color = (empty(fg) ? s:ansi[a:default] : s:csi(fg, 1)) . (empty(bg) ? '' : ';'.s:csi(bg, 0))
 6293              0.038251   return printf("\x1b[%s%sm%s\x1b[m", color, a:0 ? ';1' : '', a:str)

```

Other plugins are faster than fzf.vim because of hard code color.

**Comment by junegunn** [comment]
@kevinhwang91 Thanks. I was able to make the commands much faster with the info you provided.

See fcb1e6ebeceb961f2fa5225ce380b1c68248015d

**Comment by kevinhwang91** [comment]
Your action is so fast!
