### ISSUE TITLE
How to populate `GitFiles` / `call fzf#vim#gitfiles(...)` search?

### ISSUE THREAD

**Issue by AnthonyAstige** [junegunn/fzf.vim#538]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

How can I call something like `:GitFiles filter` to have the filter pre-populated with 'filter'. Like:

![image](https://user-images.githubusercontent.com/236039/33526438-80f9893a-d7f6-11e7-9fb0-0e1804e10d10.png)

I've played with `:call fzf#vim#gitfiles(...)` but I can't get the parameters right.

### Background

Ultimately I'm working on getting a visual mode shortcut to pre-populate the search with the current visual selection.

**Comment by junegunn** [comment]
```vim
call fzf#vim#gitfiles('.', {'options': ['--query', 'foo']})
```

To learn more about the options you can pass to the Vim plugin of fzf, see https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

**Comment by AnthonyAstige** [comment]
Works~

Thanks for the answer, the doc ref, and the awesome fuzzy finder!
