### ISSUE TITLE
Option to use keys other than CTRL-A/CTRL-D for select/deselect with Ag?

### ISSUE THREAD

**Issue by chaoren** [junegunn/fzf.vim#54]
I use CTRL-D to exit prompts by habit.

**Comment by junegunn** [comment]
Yeah, in my case I was constantly annoyed by `CTRL-A` not moving my cursor to the front, which I do frequently to prepend `'` to the query. The keys are not currently configurable, but I'm just going to change them to `ALT-A` and `ALT-D`.

**Comment by chaoren** [comment]
Cool, thanks!

**Comment by rainerborene** [comment]
`ALT-A` and `ALT-D` generates áã characters respectively. Any ideas?

**Comment by chaoren** [comment]
Do alt keys work in your terminal at all (e.g., `ALT-C`)? Check your
terminal settings, there should be a setting for sending meta keys.

**Comment by junegunn** [comment]
https://github.com/neovim/neovim/issues/2440

It's a known issue of neovim and it doesn't look like it's going to be fixed soon-ish. Hmm, maybe I should make the keys configurable for nvim users.

**Comment by rainerborene** [comment]
Yes, that is a neovim issue indeed. Most options on `fzf#vim` functions are hardcoded, even for `ag` and `fzf` itself. How can we make those options configurable?

**Comment by junegunn** [comment]
Excerpt from README:

> This repository is a bundle of fzf-based commands and mappings extracted from my .vimrc to address such needs. They are not designed to be flexible or configurable, and there's no guarantee of backward-compatibility.

:)

This repository simply provides *too many* features and trying to make every aspect of it configurable will inevitably make it a big mess. I currently encourage the users to fork it and bend it to their needs. But I do know many users are not familiar with Vimscript, so I'll think about the options.

**Comment by junegunn** [comment]
By the way, you can already override the default options as each function will *append* the extra options provided to the default set of options:

```
call fzf#vim#ag('query', {'options': '--bind ctrl-a:select-all,ctrl-d:deselect-all'})
```

**Comment by rainerborene** [comment]
I agree with you. But at least explain users how they should override current behavior i.e.

```VimL
command! Search call fzf#vim#ag(<-qargs>, {
  \ 'ag_command': 'ag --hidden %s',
  \ 'fzf_command': 'fzf -m'
  \ })
```
Better defaults and more flexible overriding instead of a bunch of options.

**Comment by junegunn** [comment]
`fzf#vim#ag` in particular takes a variable number of arguments, and ag options can be also given as follows:

```vim
call fzf#vim#ag('query', '--hidden', {'options': '--bind ctrl-a:select-all,ctrl-d:deselect-all'})
```

Note that overriding some default options can break the feature as they may affect the sink implementation.

**Comment by rainerborene** [comment]
I see. Only problem of `fzf#vim#ag` function is that escapes the `<q-args>` by default. If there were an option to disable that it would solve issue #27

**Comment by rainerborene** [comment]
Nevermind. I'll use your [`:Grep`](https://github.com/junegunn/fzf.vim/pull/36#issuecomment-156105067) command ;)

**Comment by wwwdata** [comment]
If anybody else still has this problem and is using iTerm2 and neovim. You can also configure iTerm2 to send an escape sequence, then `alt+a` and `alt+d` will also work, see my screenshot! That's how I did it 😄 

![screen shot 2016-07-26 at 16 14 17](https://cloud.githubusercontent.com/assets/818880/17141347/09a7da60-534c-11e6-9926-65d6e5f2dc26.png)

**Comment by junegunn** [comment]
<img width="1016" alt="screen shot 2017-12-09 at 11 25 34 am" src="https://user-images.githubusercontent.com/700826/33791717-b2192098-dcd3-11e7-9a0a-69d600b11cd6.png">

**Comment by Abdullah-F** [comment]
> <img alt="screen shot 2017-12-09 at 11 25 34 am" width="1016" src="https://user-images.githubusercontent.com/700826/33791717-b2192098-dcd3-11e7-9a0a-69d600b11cd6.png">
> 
> * `Esc+`

It is not working `macOS 11.5`, I opened the key settings in iterm2 profiles, then checked the two `Esc+` buttons but still `Alt-a` does not select all when running `Rg query`

**Comment by Abdullah-F** [comment]
> > <img alt="screen shot 2017-12-09 at 11 25 34 am" width="1016" src="https://user-images.githubusercontent.com/700826/33791717-b2192098-dcd3-11e7-9a0a-69d600b11cd6.png">
> > 
> > * `Esc+`
> 
> It is not working `macOS 11.5`, I opened the key settings in iterm2 profiles, then checked the two `Esc+` buttons but still `Alt-a` does not select all when running `Rg query`

`let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all,ctrl-d:deselect-all'` doing this made it work  with `ctrl` key binding, but the option key is not working.

**Comment by panosl** [comment]
> <img alt="screen shot 2017-12-09 at 11 25 34 am" width="1016" src="https://user-images.githubusercontent.com/700826/33791717-b2192098-dcd3-11e7-9a0a-69d600b11cd6.png">
> 
>     * `Esc+`

I enabled this and still `opt+a` don't seem to be working for `:Rg` select all. Has anyone found a workaround?

**Comment by thoughtsunificator** [comment]
Why has this turned into a promotional ad for Apple? Please provide a solution that works everywhere, not just on macOS.
