### ISSUE TITLE
Indexing files for faster search

### ISSUE THREAD

**Issue by navdeepio** [junegunn/fzf.vim#540]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Is there a way to index all the files so that the process doesn't repeat every time fzf is launched? FZF can maybe scan for changes in the meantime?

**Comment by junegunn** [comment]
fzf is just a filter. I believe you can implement your own indexing service and make fzf simply read the built index. I personally have never needed it since fzf is already fast enough for me.

> index all the files

All files on your file system? You might want to check out `man locate`.
