### ISSUE TITLE
Use <C-j> and <C-k> in place of <C-n> and <C-p>

### ISSUE THREAD

**Issue by randre03** [junegunn/fzf.vim#542]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible in fzf.vim to use `<C-j>` and `<C-k>` to move up and down through search results like you can with `<C-n>` and `<C-p>`?

**Comment by junegunn** [comment]
fzf already does that: https://github.com/junegunn/fzf#using-the-finder

**Comment by randre03** [comment]
The I guess I should change from 'suggestion' to 'bug' as it is not working for me.

When the fzf buffer opens I am able to move up/down through the selections with `C-n` and `C-p`. When I try to do the same with `C-j` and `C-k`, the contents of the buffer 'freeze' and becomes a 'normal' vim buffer, no longer offering the functionality fzf.vim offers.

I use neovim (see details below) on iTerm 3.1.5 on a mac running macOS High Sierra 10.13.1.
This happens whether I use tmux or not.

Here is how neovim is configured:
```
NVIM v0.2.3-5-g7d24a95b4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171120-64796-a4ihko/build/config -I/tmp/neovim-20171120-64796-a4ihko/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171120-64796-a4ihko/build/src/nvim/auto -I/tmp/neovim-20171120-64796-a4ihko/build/include

Features: +acl +iconv +jemalloc +tui
```
I also have the neovim python, ruby and npm packages.

**Comment by junegunn** [comment]
Sounds like a configuration issue to me. Check if the problem is reproducible with the minimal config as suggested in the issue template.

**Comment by randre03** [comment]
It appears to be a config issue. If I figure out what is causing it and it appears to be something others might encounter, I'll post here. Thanks - this really is a fantastic plugin! Closing for now.

**Comment by junegunn** [comment]
vim-tmux-navigator? I don't recall the exact name, is one plugin that is known to bind those keys.
