### ISSUE TITLE
Command to cancel FZF?

### ISSUE THREAD

**Issue by lsund** [junegunn/fzf.vim#544]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, I've been trying to figure out how to exit the FZF buffer. I need a local binding to a command for killing the FZF buffer. Have been through the documentation but did not find this. Thank you for you time.

**Comment by junegunn** [comment]
Escape, ctrl-c, ctrl-g, and ctrl-q can be used to terminate fzf.

https://github.com/junegunn/fzf#using-the-finder

They work just fine on Neovim as well. If it's not working for you, it's probably a configuration issue.

**Comment by nwallace** [comment]
Sorry to necro-bump this thread, but I had the same issue and figured out the problem and a solution.

I also use neovim. I had this mapping configured in my .vimrc:

```
if has("nvim")
  tnoremap <Esc> <c-\><c-n>
endif
```

This mapping is what was interfering with FZF's `<Esc>` handling. So I changed it to this:

```
if has("nvim")
  au TermOpen * tnoremap <Esc> <c-\><c-n>
  au FileType fzf tunmap <Esc>
endif
```

...and now it works as expected: I can continue to use the old binding in other terminals, but with FZF terminals, `<Esc>` kills the buffer, as expected

**Comment by darthdeus** [comment]
@nwallace Thank you for this! I thought something was broken and it was driving me insane. I've looked everywhere in the config and couldn't find what was happening, and since I just added that `tnoremap` almost without thinking, I never suspected it. Thank you for saving my sanity!

How did you figure out the cause btw?

**Comment by nwallace** [comment]
@darthdeus Glad to help!

> How did you figure out the cause btw?

I figured out when I learned that the FZF buffer was implemented with the neovim terminal. Then when I re-read that line in my vimrc I was pretty sure that was the cause (obviously if I'm overwriting what ESC does, it won't do what FZF is trying to make it do).

This fix is probably worth mentioning in the README. I'd guess this is a really common config, since it's mentioned in the neovim docs: `:help terminal-input`

**Comment by pLesur** [comment]
The solution presented above wasn't working quite well for me (the mapping would sometimes not be set back for terminal buffers, forcing me to use ctrl \ ctrl n).
This one below doesn't rely on changing shortcuts but buffers, but performs a check on an `Esc` keypress. Note that the mapping is done in terminal mode only so it shouldn't interfere with other plugins or whatnot.

```vimscript
tnoremap <expr> <Esc> (&filetype == "fzf") ? "<Esc>" : "<c-\><c-n>"
```

**Comment by still-dreaming-1** [comment]
Here is another alternative/tweak to @nwallace solution that I think should fix the issue reported by @pLesur 
```
if has("nvim")
  au TermOpen * tnoremap <buffer> <Esc> <c-\><c-n>
  au FileType fzf tunmap <buffer> <Esc>
endif
```
These only map and unmap for the current terminal buffer instead of all terminal buffers.

**Comment by dagadbm** [comment]
oh my god i can't believe i had this problem for so long 😂 hurray!

**Comment by kristher1619** [comment]
I'm going nuts because of this. Thanks, I'm going full pledge vim now!

**Comment by ricardokl** [comment]
The autocommands are really healpful!
I had one weird behavior: after sourcing my keybindings file a second time, all fzf windows would start in normal mode.  

Works fine if I add a bang:

```
if has("nvim")
  au! TermOpen * tnoremap <buffer> <Esc> <c-\><c-n>
  au! FileType fzf tunmap <buffer> <Esc>
endif
```

Now I can source as many times as I want :)

**Comment by expipiplus1** [comment]
For anyone searching: I was bumping into

```
Error detected while processing FileType Autocommands for "fzf":
E31: No such mapping
```

with 

```vim
if has("nvim")
  au TermOpen * tnoremap <Esc> <c-\><c-n>
  au FileType fzf tunmap <Esc>
endif
```

This mapping fixed things: `tnoremap <expr> <Esc> (&filetype == "fzf") ? "<Esc>" : "<c-\><c-n>"`

**Comment by fftyjw** [comment]
Try this:

au TerminalOpen * set ft=terminal
au FileType fzf silent! tunmap <buffer> <Esc>
au FileType terminal tnoremap <buffer> <Esc> <c-w>N

**Comment by osamuaoki** [comment]
>> fftyjw

Not quite.  If I use this with FZF.VIM functions such as `:Maps<CR>`, it overwrites current editor buffer ft value and now I lost syntax highlight.

I am now doing this
```
""" This avoid crashing fzf menu running in terminal
""" <Esc><Esc> is just in case impatient for slow keycode delay
"""   https://vi.stackexchange.com/questions/2614/why-does-this-esc-normal-mode-mapping-affect-startup
"""   https://vi.stackexchange.com/questions/24925/usage-of-timeoutlen-and-ttimeoutlen
fun! RemapTerminalEsc()
    " Don't strip on these filetypes
    if &ft =~ 'fzf'
      silent! tunmap <buffer> <Esc>
    else
      tnoremap <buffer> <Esc> <c-\><c-n>
      tnoremap <buffer> <Esc><Esc> <c-\><c-n>
    endif
endfun
au FileType fzf silent! call RemapTerminalEsc()

```

**Comment by mvsrgc** [comment]
For people using init.lua:

```lua
local function t(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

function _G.toggle_term()
  local filetype = vim.api.nvim_buf_get_option(0, 'filetype')
  if filetype == 'fzf' then
    return t"<Esc>"
  else
    return t"<C-\\><C-n>"
  end
end

vim.api.nvim_set_keymap('t', '<Esc>', 'v:lua.toggle_term()', { expr = true, silent = true })
```

Reference: [nanotee/nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide)

**Comment by osamuaoki** [comment]
Yes, correct.

FYI: Since then, I have migrated to use mapping "<esc><esc>"  in terminal mode to"<c-\\><c-w>" to avoid this complication.  So non-fzf program can use <esc>.   LazyVim which I started to use also use this "<esc><esc>" trick.
