### ISSUE TITLE
Can't select all on macOS

### ISSUE THREAD

**Issue by ericandrewlewis** [junegunn/fzf.vim#545]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When I'm in a fzf window in Vim, either via `:Files` or looking at results from `:Ag`, I can't select all with `Alt-a`. `Alt-a` is mapped to input an alernate character on macOS (`å`), and so inputs that character into the fuzzy search input.

See also [Operating System Keyboard Shortcuts](https://docs.google.com/spreadsheets/d/12iEbCdv07RegN8_yRdD9UDUpXIDDf7r4ikN2Fa1gDIo/edit#gid=1478273275).

**Comment by junegunn** [comment]
See #54. You can either configure key bindings by defining a custom command or set up alt key on iterm2 to send escape (I recommend the latter).
