### ISSUE TITLE
Is it possible to integrate with fasd?

### ISSUE THREAD

**Issue by rawaludin** [junegunn/fzf.vim#546]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I found fasd really helpful when switching folder in terminal.

I map fasd to

```
z='fasd_cd -d'
```

In terminal, when I type `z go<tab>` it will give me this result:

<img width="1009" alt="screen shot 2017-12-12 at 4 45 15 pm" src="https://user-images.githubusercontent.com/1274849/33877754-e20f0d5a-df5b-11e7-8ed8-5b788ac1c28e.png">

Sorted by frecency (frequent and recent). Then I press tab if I want to pick one (if the first not satisfy me).

I found this script which integrate vim quite helpful https://github.com/clvv/fasd/wiki/Vim-Integration
But, this script missing file chooser as fzf have. 

So my goal is to change folder as that script does (cd to folder) but show those folder with fzf first. Is it possible? Thanks.

**Comment by yangmillstheory** [comment]
Would love this as well, happy to receive any pointers from @junegunn on implementation.

**Comment by junegunn** [comment]
For starter,

```vim
call fzf#run(fzf#wrap({'source': 'fasd -d -R', 'sink': { line -> execute('cd '.split(line)[-1]) }}))
```

Please read through the following pages to learn how to implement stuff:
- https://github.com/junegunn/fzf/blob/master/README-VIM.md
- https://github.com/junegunn/fzf/wiki/Examples-(vim)

**Comment by yangmillstheory** [comment]
Based on that, I came up with:

```vim
function! s:Fasd(cmd)
  let cmd = a:cmd
  function! Sink(line) closure
    execute(cmd . ' ' . split(a:line)[-1])
  endfunction
  return funcref('Sink')
endfunction
command! -bang -nargs=* FzfFasdFile
\ call fzf#run(fzf#wrap({'source': 'fasd -f -R '. shellescape(<q-args>), 'sink': s:Fasd('e')}))
command! -bang -nargs=* FzfFasdDir
\ call fzf#run(fzf#wrap({'source': 'fasd -d -R '. shellescape(<q-args>), 'sink': s:Fasd('NERDTree')}))
```

Thanks!
