### ISSUE TITLE
Command from `History:` does not get executed

### ISSUE THREAD

**Issue by stellarhoof** [junegunn/fzf.vim#549]
- Category
    - [ ] Question
    - [X ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X ] Neovim

Minimal `.vimrc`:

```vim
nnoremap , :
vnoremap , :
nnoremap : ,
vnoremap : ,

let g:python_host_prog = '/usr/local/bin/python2'
let g:python3_host_prog = '/usr/local/bin/python3'
let g:confdir = expand($HOME) . '/.config/nvim'
let g:plugdir = expand($HOME) . '/.local/share/nvim/plugins'

call plug#begin(g:plugdir)
Plug 'https://github.com/junegunn/fzf.vim.git'
Plug '/usr/local/opt/fzf'
call plug#end()
```

Selecting an entry from `:History:` doesn't execute the corresponding command.

**Comment by kidonchu** [comment]
@stellarhoof I'm experiencing the same issue. Have you found any workaround?

**Comment by stellarhoof** [comment]
No

**Comment by vimeitor** [comment]
```
nnoremap : ,
vnoremap : ,
```
There's your issue.

**Comment by kidonchu** [comment]
@vimeitor thanks for pointing that out. That was my issue as well since I had mapped `;` to `:` and `:` to `;`. Modifying https://github.com/junegunn/fzf.vim/blob/ce82e10630830bc37a50f706cc3b7216d24e5009/autoload/fzf/vim.vim#L462 to use `normal!` proves that `:` mapping is what causes the issue

**Comment by igorepst** [comment]
I noted, however, that on the regular vim and without these mappings, `:messages` isn't get executed from `:History:`, although other commands I tried (a very small quantity) work fine
