### ISSUE TITLE
Not in git repo

### ISSUE THREAD

**Issue by mfiano** [junegunn/fzf.vim#551]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'm trying fzf in vim out for the first time (been using it in terminal for about a year perfectly), and :Commits or :GitFiles results in `Not in git repo`. Is there something I must do besides view a git-tracked file?

**Comment by junegunn** [comment]
Those commands require that your current working directory is managed by git, in other words, `:!git rev-parse --show-toplevel` should success. `:cd` to a git project directory and they will work.

**Comment by swapnildinkar** [comment]
I start up my vim from the parent dir, where I have multiple repos, would be great if fzf could identify the top git dir of a file, and execute Git commands within that dir

**Comment by Frederick888** [comment]
+1 for this. I've got a parent dummy project for a few repos. They have dependencies between each other and this way I can jump between repos / debug more easily.

Currently I put this in my `.exrc` to work around this issue:

```vim
autocmd BufRead,BufNewFile,BufEnter,BufWinEnter /path/to/parent/child1/** cd /path/to/parent/child1
autocmd BufRead,BufNewFile,BufEnter,BufWinEnter /path/to/parent/child2/** cd /path/to/parent/child2

function! s:parent_dir_files()
  cd /path/to/parent
  Files
endfunction
command! ParentFiles :call <SID>parent_dir_files()
```

This worked out fine most of time, except when I need to edit something in the parent directory, where I need to `:cd ..` first. It'd be great if fzf.vim can handle this out of the box like vim-fugitive does.
