### ISSUE TITLE
Tags on Windows

### ISSUE THREAD

**Issue by zokeefe** [junegunn/fzf.vim#553]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

First - wow! Can't believe how much faster this is then ctrlp. Even indexing ~500k files, then matching, is still faster! Great job!

Now, so I can remove my dependency on ctrlp, need to get this working with ctags! Can't seem to get it working though..

- Have fzf and fzf.vim installed - both working, for example, with :Files
- Windows 10, vim 8 with +terminal
- Have perl installed
- Typing :Tags opens %USERPROFILE%\vimfiles\bundle\fzf.vim\bin\tags.pl   (??!)
- Don't know enough Vimscript to know how to use fzf#vim#tags()
- Have a tags ctags file in the current directory

**Comment by janlazo** [comment]
`perl.exe` is not associated with `*.pl` files on your system so Windows defaults to notepad.

**Comment by janlazo** [comment]
For `Tags` source (https://github.com/junegunn/fzf.vim/commit/1e40de4f2d5655b76ca4b5b1e387e1034d1815fa#diff-7274b7c6c87526542ef9087f2e997dfaR811), explicitly running tags.pl on perl should fix the issue.
