### ISSUE TITLE
how to fix the ugly blue line when i using  nord theme ?

### ISSUE THREAD

**Issue by rinetd** [junegunn/fzf.vim#555]
![default](https://user-images.githubusercontent.com/15907353/34373243-00dbeff4-eb15-11e7-89cb-47e98dffb982.png)

**Comment by stsewd** [comment]
I changed to nova theme because of this. and I liked it.

**Comment by trevordmiller** [comment]
Related: https://github.com/junegunn/fzf.vim/issues/581
