### ISSUE TITLE
Pass a query to `:Files`

### ISSUE THREAD

**Issue by sankhesh** [junegunn/fzf.vim#556]
---

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

---
I'm trying to create a mapping to be able to pass a query to `:Files` or `fzf#vim#files`. The query I'm interested in is the word under the cursor.

So far, I've tried the following options:

  ```vim
  nmap <leader>cp :call fzf#vim#files(expand('<cword>'))<CR>
  ```
This gives me an `Invalid directory` error.

   ```vim
   nmap <leader>cp :Files <C-R><C-W><CR>
   ```
Again the same error

What's the correct way to do this? 
Thanks in advance for the help.

**Comment by janlazo** [comment]
https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L288-L290

```viml
    if !isdirectory(expand(a:dir))
      return s:warn('Invalid directory')
    endif
```

If you change `expand(a:dir)` to `fnamemodify(a:dir, ':p')`, does it work?

**Comment by sankhesh** [comment]
@dedowsdi's suggestion works.

Thanks!

**Comment by dagadbm** [comment]
even better user <cfile> .

even better than <cfile> would be to just make vim actually open the file from the fzf result but i have no idea how to do this. any thoughts ? @dedowsdi 
then I would just remap gf and actually have a working gf ALL THE TIME. amazing :D

**Comment by sitaramc** [comment]
I know it's closed but FWIW...

    " remap 'gf' to pick up files anywhere inside current directory rather than just the literal <cfile>
    " when you want the same for some *other* directory, you put your cursor on the filename and type `:GF other-dir`
    function! GF(...)
        call fzf#run({'dir': a:1, 'source': 'find . -type f', 'options':['-1', '--query', expand('<cfile>')], 'sink': 'e'})
    endfunction
    command! -nargs=* GF :call GF(<f-args>)
    nnoremap gf :GF .<CR>
