### ISSUE TITLE
C-u + C-d to navigate up and down in the fzf window

### ISSUE THREAD

**Issue by danihodovic** [junegunn/fzf.vim#56]
Currently we can move up and down in the fzf window linewise by using `<C-j>` and `<C-k>`. Is it possible to add mappings so that you can move in larger chunks upwards or downwards?

**Comment by junegunn** [comment]
Yes, page-wise movement is available. Check out `--bind` section of the man page.

**Comment by danihodovic** [comment]
Alright, thanks. So I take it there are no plans on integrating this in the existing vim fzf commands?

**Comment by junegunn** [comment]
We don't need to since users can freely set up their key bindings with `$FZF_DEFAULT_OPTS`. In fact we shouldn't. Both `ctrl-u` and `ctrl-d` are mapped to different actions by default and the users who already use those key bindings, myself included, will not appreciate the change. Related #54.

**Comment by danihodovic** [comment]
:+1:
