### ISSUE TITLE
Ag customization: Match whole words only

### ISSUE THREAD

**Issue by Manu343726** [junegunn/fzf.vim#560]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi,

I'm trying to customize the Ag command to match whole words, but unfortunately I have almost no experience with VimL, so after searching for old issues asking for Ag customizations (Like #316) I had no success passing the ag `--word-regexp` to your `fzf#vim#ag`/`fzf#vim#raw_ag` functions.

What is the correct way to pass extra arguments to the ag cli tool?

Thanks in advance.

**Comment by junegunn** [comment]
```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--word-regexp', <bang>0)
```

**Comment by eshinn** [comment]
Just as a note, I noticed that if you have the following setup from the README:
```
" Augmenting Ag command using fzf#vim#with_preview function
"   * fzf#vim#with_preview([[options], [preview window], [toggle keys...]])
"     * For syntax-highlighting, Ruby and any of the following tools are required:
"       - Bat: https://github.com/sharkdp/bat
"       - Highlight: http://www.andre-simon.de/doku/highlight/en/highlight.php
"       - CodeRay: http://coderay.rubychan.de/
"       - Rouge: https://github.com/jneen/rouge
"
"   :Ag  - Start fzf with hidden preview window that can be enabled with "?" key
"   :Ag! - Start fzf in fullscreen and display the preview window above
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```

... you can type in the words you _need_ to be regexp words in the first command and then follow up w/ fuzzy searches to narrow down after words. Like so:
- `:Ag this|that` will search full word (`this` or `that`)
- Hit enter to see results
- Narrow results further w/ fuzzy search by typing whatever
- Can also hit `?` key to show preview

**Comment by Manu343726** [comment]
Thanks for pointing out @eshinn
