### ISSUE TITLE
Ag with -L option doesn't work

### ISSUE THREAD

**Issue by peanutandchestnut** [junegunn/fzf.vim#562]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi junejunn:

I'm using Ag(ag_raw)  with -L option
```vim
Ag -L  'include\s*"common.h"' -G .*\.cpp 
```
There is no line or column info in the result, so it can not be converted to quickfix.
All i want is just filename, so i add an extra action to fzf_action:
```vim
'ctrl-a' : 'argadd',
```
But this doesn't work either. I dig a little and found that ag_handler always convert result lines to quick fix,
```vim
function! s:ag_handler(lines, with_column)
  ...
  let list = map(filter(a:lines[1:], 'len(v:val)'), 's:ag_to_qf(v:val, a:with_column)')
  ...
  try
    call s:open(cmd, first.filename)
    ...
  catch
  endtry
   ...
endfunction

```
s:ag_to_qf  will cause problem if a:lines has no line and column information.
May be it should just do the custom action and return.

**Comment by junegunn** [comment]
If the command prints plain file names, you should probably use basic `fzf#run` along with `fzf#wrap` instead of any ag-related functions in here.

```vim
call fzf#run(fzf#wrap({ 'source': 'ag -L zzz' }))
```

See https://github.com/junegunn/fzf/blob/master/README-VIM.md to learn more about the options.

**Comment by peanutandchestnut** [comment]
That's exactly what i want.
Thank you.
