### ISSUE TITLE
No default mappings?

### ISSUE THREAD

**Issue by alextes** [junegunn/fzf.vim#563]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

After 10min of searching I'm pretty confident there are no default mappings set.
> This repository is a bundle of fzf-based commands and mappings extracted from my .vimrc to address such needs.

Threw me off a little because your `.vimrc` does include useful mappings. Adding a single sentence could save a bunch of people time here. Either in the introduction or in the mapping section.

What do you think?

Awesome wrapper 😄 !

**Comment by junegunn** [comment]
Technically, this plugin does provide a bunch of mappings, but they're "unbound" by default.

https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L126-L141

README describes how you can realize those mappings by binding them. See https://github.com/junegunn/fzf.vim#mappings

**Comment by alextes** [comment]
@junegunn sorry, I was unaware the correct terminology was _bindings_. I'll update the title. I can understand you don't want to update the docs because one person couldn't figure it out.

We can have people 👍 my initial comment and update the docs if enough people do. Does that sound fair?

It would be helpful if you left the issue open for a month or so because GitHub by default filters on open issues.

Final question, could you at least link to the section explaining how to do the bindings for others that find this issue? You linked the mappings, I was looking for suggesting how to bind the commands, or that you had to bind them yourself in order to use this plugin.

**Comment by junegunn** [comment]
> how to bind the commands

It's not specific to a single plugin. We don't want to repeat what `:help map.txt` already tells you.

**Comment by alextes** [comment]
@junegunn that is totally understandable! Yet, what to bind where is plugin specific and most plugins either have default bindings they detail, or specifically mention that if you actually want to use the plugin you have to do that bit yourself.

I just noticed the _Usage_ section is actually a subsection of _Mappings_, which now that I know is not _bindings_ has no business explaining how to _use_ `fzf.vim` 😓 .

Let's leave it. If more people show up here we can always discuss adding a sentence somewhere that tells you to bind stuff yourself 😄 .

**Comment by jsatk** [comment]
@junegunn @alextes I'm curious if there is a commonly-used/popular vim binding for fzf that the community uses? I used to use CtrlP plugin before fzf, but I'd like to stop using `<C-p>` as my mapping for fuzzy finding since it is also useful for auto-complete. 

Any thoughts or suggestions? What do y'all use?

**Comment by alextes** [comment]
My keybindings 😚 
```rc
" Fzf
nnoremap <leader><leader> :GFiles<CR>
nnoremap <leader>fi       :Files<CR>
nnoremap <leader>C        :Colors<CR>
nnoremap <leader><CR>     :Buffers<CR>
nnoremap <leader>fl       :Lines<CR>
nnoremap <leader>ag       :Ag! <C-R><C-W><CR>
nnoremap <leader>m        :History<CR>
```

**Comment by jsatk** [comment]
Thanks @alextes. I might steal some of these.
