### ISSUE TITLE
Usable with minimal configuration but failing in my normal setup

### ISSUE THREAD

**Issue by jleeothon** [junegunn/fzf.vim#565]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

fzf.vim seems to work with the minimal configuration, but otherwise I get an error message if I type e.g. `:Files` (other commands e.g. `:History` produce a similar error).

Note: I'm a total newbie to vim+plugins+etc, so apologies if I fail to be more specific.

The error message is:

```
Error detected while processing function fzf#vim#files[15]..<SNR>25_fzf[18]..<SNR>25_wrap:
line   12:
E117: Unknown function: fzf#wrap
E15: Invalid expression: fzf#wrap(a:name, opts, a:bang)
line   14:
E121: Undefined variable: wrapped
E15: Invalid expression: wrapped
Error detected while processing function fzf#vim#files[15]..<SNR>25_fzf:
line   18:
E117: Unknown function: fzf#run
E15: Invalid expression: fzf#run(s:wrap(a:name, merged, bang))
```

Is there something obviously wrong in my setup? Or what kind of information can I further provide?

**Comment by shmup** [comment]
I've had fzf, but just cloned down fzf.vim and am running it via vim 8's plugin `/start` dir. 

MacOS as well, and I'm getting _the exact same error_.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim#installation. You need both fzf and fzf.vim configured in Vim.

**Comment by junegunn** [comment]
Also #456

**Comment by jleeothon** [comment]
Thanks!

**Comment by shmup** [comment]
To those reading this who have the problem of not reading things entirely before you ask questions, arrive here, and maybe are still confused:

The problem is: there is `fzf`, there is `fzf.vim`, and there is also a single vim plugin file in the fzf project:

https://github.com/junegunn/fzf/tree/master/plugin
