### ISSUE TITLE
Buffers maybe should use :sbuffer instead of implementing own buffer switching logic?

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf.vim#569]
- Category
    - [x] Question
    - [x] Bug
    - [x] Suggestion

Suppose I have files open like this

Tab 1
Window a.txt
Window b.txt

Tab 2
Window c.txt

- I have c.txt open (tab 2 is focused).
- I use :Buffers and select a.txt. 

WHAT HAPPENS

Tab 2 now has a.txt open and c.txt is no longer open

WHAT I WANT

Vim should just switch over to Tab 1 window 1 where a.txt is already open.

Vim already has a `:sbuffer` which does the right thing. I actually really want `:Buffers` to simply drive `:sbuffer`.

Addendum: When a buffer which is not "open" (but is loaded) is selected, then personally I like `:sbuffer`'s behavior as well, it will open a split right where you are, which leads to maximum clarity about where things have gone. others may prefer it to open the buffer specified over the current window, or to open it in a new tab, in fact the ctrl+t or ctrl+s or such binds could be used to specify how that works.

Further addendum: I would overload :Buffer with :FZF so that there is one single entrypoint. I want when I specify a given file to open via fzf, to attempt to open the loaded buffer of that file if it is open, and otherwise do the regular opening logic based on my key combo there (whether to split or tab it).

Hopefully these thoughts make sense. I will probably fork this project and implement that last paragraph into :FZF and see how it comes out working.

**Comment by junegunn** [comment]
Have you tried setting `let g:fzf_buffers_jump = 1` as the README suggests?

Buffers accepts CTRL-T, CTRL-X, and CTRL-V in addition to simple Enter, so it's more sophisticated than `:sbuffer`

**Comment by unphased** [comment]
I will test. Thank you, sorry for not reading it closely.

**Comment by unphased** [comment]
Is it possible to make Enter open it in a split by default (or switch to if already open)?

**Comment by junegunn** [comment]
Buffers and many of the commands in fzf.vim respect `g:fzf_action` (because they call `fzf#wrap()`). See https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration

**Comment by unphased** [comment]
I do customize fzf_action. This works well. 

However, setting `g:fzf_buffers_jump=1` in my vimrc has made no change in behavior that I can see.

**Comment by unphased** [comment]
Looking at this again now, it seems to work. I'm really excited! 

Not sure what was causing it not to work previously.
