### ISSUE TITLE
Ag string in current git repo

### ISSUE THREAD

**Issue by apinio** [junegunn/fzf.vim#570]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi, how can I combine [https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim](url) with [https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795](url) so as to obtain a command to ag a string in current git repo (and not only in the current repo directory where vim was launched and its subdirectories recursively)?

Say, I think that I have to append the path of the repo root (which I can get using the function described in [https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795](url)) to the fzf#run source descripted in [https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim](url), but I'm not a vimscript expert.

THX

**Comment by apinio** [comment]
Code snippet `Augmenting Ag command using fzf#vim#with_preview function` descripted in [https://github.com/junegunn/fzf.vim#advanced-customization](url) does the job.

**Comment by gkoo** [comment]
The link above is actually linked to the wrong URL. Correct link for the lazy: https://github.com/junegunn/fzf.vim#advanced-customization
