### ISSUE TITLE
fzf#vim#grep with rg modifies target files

### ISSUE THREAD

**Issue by vbrinnel** [junegunn/fzf.vim#571]
- Category
    - [] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi,

when using Rg to match files in VimR (or nvim from terminal), the selected files are modified: 

![fzf-rg-issue](https://user-images.githubusercontent.com/17532220/35480784-4ffe85c8-0416-11e8-945e-45c7fce9edf4.gif)

my init.vim contains the following entry:

command! -bang -nargs=* Find
      \ call fzf#vim#grep('rg --line-number --no-heading --fixed-strings --ignore-case --color "always" -g "*.{js,json,html,config,py    ,cpp,c,java,conf}" ' .shellescape(<q-args>), 1,
      \   <bang>0 ? fzf#vim#with_preview('up:60%')
      \           : fzf#vim#with_preview('right:50%:hidden', '?'),
      \   <bang>0)
map \<Leader\>F :Find<CR>

I end up automatically calling undo when I use this functionality. 
Any idea how to fix this ?

Thanks

Versions:

$ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

$ fzf --version
0.17.3 (brew)

fzf.vim $ git rev-parse HEAD
17d24ae31d119f8bdd88a5149a831ca35baf726c

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/1199

**Comment by vbrinnel** [comment]
Both suggestions fix the issue, I ended up changing 1 to 0.
Many thanks!

> Your rg command does not print column number, but you're setting the second parameter of fzf#vim#grep to 1 (expects column number). Either add --column to rg command, or change 1 to 0.
