### ISSUE TITLE
Error on opening History

### ISSUE THREAD

**Issue by Seybo** [junegunn/fzf.vim#573]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Have lastest fzf and fzf.vim versions and the problem stays with the minimal configuration.

Yestarday (after playing with vim fugitive but i'm not suggesting it's necessarily related) I started to have this error after `:History`:
```
Error detected while processing function <SNR>54_history[7]..fzf#vim#history[1]..<SNR>165_all_files:                                              
line    1:                                                                                                                                        
E16: Invalid range                                                                                                                                
E16: Invalid range
```
Then I press whatever key and I can use History normally. But it's annoying.

When I checked this on the minimal configuration it showed me a bit different error text:
```
Error detected while processing function <SNR>33_history[7]..fzf#vim#history[1]..<SNR>34_all_files:                                    
line    1:                          
E16: Invalid range                  
E16: Invalid range
```

Tried removing plugin folder and installing it again. Fruitless.

Have a guess that it might be related to these strange lines in History that appeared after playing with fugitive.
`term://.//10541:git add --patch -- my/path/to/file.rb`

**Comment by jetpackpony** [comment]
I'm having the same issue on macOS in Neovim as well

**Comment by haakenlid** [comment]
I have the same issue. I think it's because I'm using buffergator. One of the values in `v:oldfiles` is `[[buffergator-buffers]]` which seems to mess up `expand()`. 

    :call expand('[[buffergator-buffers]]')

raises this (I'm using neovim)

    E16: Invalid range

I don't know why. Maybe `[...r-b...]` looks like a regex range?

I was able to make the bug go away by changing the `s:all_files` function in fzf-vim. But I don't really understand why this works, and what the purpose of `expand` is here, so I'm not going to submit a pull request. But maybe someone else can figure this out and reproduce the bug?

```
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -433,7 +433,7 @@ function! s:all_files()
   return fzf#vim#_uniq(map(
     \ filter([expand('%')], 'len(v:val)')
     \   + filter(map(s:buflisted_sorted(), 'bufname(v:val)'), 'len(v:val)')
-    \   + filter(copy(v:oldfiles), "filereadable(expand(v:val))"),
+    \   + filter(copy(v:oldfiles), "filereadable(v:val)"),
     \ 'fnamemodify(v:val, ":~:.")'))
 endfunction
```

**Comment by junegunn** [comment]
```diff
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index 6066a15..8f7b0ab 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -433,7 +433,7 @@ function! s:all_files()
   return fzf#vim#_uniq(map(
     \ filter([expand('%')], 'len(v:val)')
     \   + filter(map(s:buflisted_sorted(), 'bufname(v:val)'), 'len(v:val)')
-    \   + filter(copy(v:oldfiles), "filereadable(expand(v:val))"),
+    \   + filter(copy(v:oldfiles), "filereadable(fnamemodify(v:val, ':p'))"),
     \ 'fnamemodify(v:val, ":~:.")'))
 endfunction
 ```

Does this help?

**Comment by junegunn** [comment]
So here's why `expand` was needed:

```vim
:echo filereadable('~/.vimrc')
0
:echo filereadable(expand('~/.vimrc'))
1
```
But it looks like `echo filereadable(fnamemodify('~/.vimrc', ':p'))` is a safer option.

**Comment by Seybo** [comment]
I don't know why. But I can't reproduce this now. I'm also still using buffergator though

**Comment by haakenlid** [comment]
@junegunn Yes. `filereadable(fnamemodify(v:val, ':p'))` fixes it.
