### ISSUE TITLE
Can  it support GUI color scheme

### ISSUE THREAD

**Issue by rickywu** [junegunn/fzf.vim#574]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I test set color as help doc, but it seems use the terminal color scheme
Can I use color scheme of GUI?

**Comment by junegunn** [comment]
Yep.

**Comment by rickywu** [comment]
vim config:

let $FZF_DEFAULT_OPTS=' 
            \ --color=fg:#2e3436,bg:#eeeeec,hl:#fcaf3e
            \ --color=fg+:#ffffff,bg+:#8ae234,hl+:#f57900
            \ --color=info:#afaf87,prompt:#d7005f,pointer:#cc0000
            \ --color=marker:#ef2929,spinner:#af5fff,header:#729fcf'

Windows env var:

FZF_DEFAULT_OPTS=--color=fg:#2e3436,bg:#eeeeec,hl:#fcaf3e --color=fg+:#ffffff,bg+:#8ae234,hl+:#f57900 --color=info:#afaf87,prompt:#d7005f,pointer:#cc0000 --color=marker:#ef2929,spinner:#af5fff,header:#729fcf

Still has different behavior, cmd run fzf.exe
![image](https://user-images.githubusercontent.com/442398/81132329-94028380-8f80-11ea-8e3b-61b205a6e6fe.png)

Call FZFMru:
![image](https://user-images.githubusercontent.com/442398/81132335-9f55af00-8f80-11ea-8053-4c8afe6f9161.png)
