### ISSUE TITLE
[Question] Ag doesn't use .gitignore?

### ISSUE THREAD

**Issue by Industrial** [junegunn/fzf.vim#576]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi.

I have this in my .zshrc:
```
export FZF_DEFAULT_COMMAND="ag -U -f -g \"\""
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

The `-U` option is supposed to make ag look at the .gitignore file, but it doesn't do that. The .gitignore is placed in the directory I started vim in, and there are also more in deeper dirs.

I still get `node_modules` results.

When I add `--ignore node_modules` then it will work for `:Files` but not for `:Ag` (which I use on a `<C-f>` map to search in files).

**Comment by stsewd** [comment]
This works for me `export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'`

**Comment by Industrial** [comment]
That would imply i need to pass lots of --ignore and it cant be project
(.gitignore file) specific.

**Comment by stsewd** [comment]
@Industrial this respect the `.gitignore` file

**Comment by Industrial** [comment]
Ok thank you, i will try 🤐

**Comment by bthallion** [comment]
This isn't working for me, is this just looking at the global gitignore file?

**Comment by stsewd** [comment]
Make sure to open vim/nvim in your project root, maybe that's the problem?

**Comment by bthallion** [comment]
This is very close to what my problem was, thank you. I was searching from
my git project root, but there are multiple subdirectories each with their
own gitignore file. The root dir doesn't contain a gitignore file. Is there
a way where I could search over all these directories, and respect multiple
git ignore files?

**Comment by coindegen** [comment]
I know this is old, but ag has a `--path-to-ignore` flag:

```
 -p --path-to-ignore STRING
                          Use .ignore file at STRING
```

As an example here is my FZF_DEFAULT_COMMAND:

`export FZF_DEFAULT_COMMAND="ag --nobreak --nocolor --noheading --hidden --ignore 'node_modules' --ignore '.git' --path-to-ignore ~/.ignore -g ''"`
