### ISSUE TITLE
Avoid closing terminal in fzf#vim#grep/ag_raw etc.

### ISSUE THREAD

**Issue by osa1** [junegunn/fzf.vim#577]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I'm using this command for running ag with fzf:

```
command! -nargs=+ Ag call fzf#vim#ag_raw(<q-args>)
```

It works great, but one problem one sometimes I want to look at multiple items in the result list, but after I select one the terminal closes so I have to run the search again, which does redundant work but also reorders the result list so I don't know where I was before. Is there a parameter etc. to open the item in a buffer but leaving the terminal open so that I can return back to it and open another item from the list?

**Comment by junegunn** [comment]
No, but you can select the items using tab, shift-tab, or alt-a to bring them into the quickfix list of Vim.

**Comment by kevindashgit** [comment]
I had the same question as @osa1 and this answer totally answers it - but was wondering - is this really the best approach? Like is this what folks like to use to analyze a result after grepping through their code?
