### ISSUE TITLE
Proposal: different layouts

### ISSUE THREAD

**Issue by michaelfresco** [junegunn/fzf.vim#578]
## Different layouts for some commands
The `:BCommits` is a very useful command. Like all of fzf.vim really. But you do need some extra space to properly show the commit changes. It would be nice if we could set the `fzf_layout` for different commands. With most commands you wanna small screen. (~20%) But with some commands, like the git related ones, you want a big screen. (~60%)

### Suggested implementation
Have a default layout setting (say ~20%), which you could overwrite for some commands, like `:BCommits`.

**Comment by michaelfresco** [comment]
Already [possible](https://github.com/junegunn/fzf.vim#advanced-customization).

Apologies for spam.

**Comment by junegunn** [comment]
Also note that all commands in fzf.vim can be started in fullscreen mode just by appending `!`. e.g. `BCommits!`
