### ISSUE TITLE
Yanking from fzf results

### ISSUE THREAD

**Issue by akinh** [junegunn/fzf.vim#580]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a way to yank from fzf results ? I am use :Files and list a bunch of files, just want to yank the selected filename and paste it to somewhere else.

**Comment by mars90226** [comment]
Or you can also add this to your `.vimrc` file.
```
function! s:copy_results(lines)
  let joined_lines = join(a:lines, "\n")
  if len(a:lines) > 1
    let joined_lines .= "\n"
  endif
  let @+ = joined_lines
endfunction
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'ctrl-o': function('s:copy_results'),
  \ }
```
When pressing `ctrl-o` in the fzf window, it will copy the selected filenames to `+` register which is likely your system clipboard.

**Comment by gandalf0151** [comment]
How to copy file contents into clipboard or paste in current buffer ?
any kind of help would be greatly appreciated

**Comment by gandalf0151** [comment]
I was able to implement that with the following fzf_action
```    \ 'ctrl-y': ':%w !xclip -selection clipboard', ```
Thanks
