### ISSUE TITLE
Question: how to use ag for :Ag

### ISSUE THREAD

**Issue by trevordmiller** [junegunn/fzf.vim#582]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I have latest Vim + fzf + fzf.vim. I'm trying to figure out how to always have fzf commands use my ag config (so that hidden files are searched and my global `.ignore` is used). I have the following in my `.bash_profile`:
```
alias ag='ag --path-to-ignore ~/.ignore --hidden'
export FZF_DEFAULT_COMMAND='ag --path-to-ignore ~/.ignore --hidden -g ""'
```

This works for `ag` from the shell and the `:FZF`, but it doesn't work for the `:Ag` command. Do I need some more config to get the fzf.vim `:Ag` command to use my `ag --path-to-ignore ~/.ignore --hidden` config?

Thank you! FZF is wonderful and I appreciate your work :)

**Comment by junegunn** [comment]
For configuring ag options, see https://github.com/junegunn/fzf.vim/issues/475#issuecomment-339979974

**Comment by trevordmiller** [comment]
@junegunn I'm not sure I understand. So are you saying to use `:Ag` in the same way I use it on the command line (`ag --path-to-ignore ~/.ignore --hidden`), I would do add this to my `.vimrc`:

```vim
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--path-to-ignore ~/.ignore --hidden', <bang>0)
```

Is that right?

Is `:Ag` actually using the silver searcher then, the `ag` package?
If so, it would be cool if it just used the `ag` command directly so my alias worked without extra config.
