### ISSUE TITLE
Question: how to use  FZF_DEFAULT_COMMAND in .vimrc

### ISSUE THREAD

**Issue by trevordmiller** [junegunn/fzf.vim#583]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Is it possible to define ` FZF_DEFAULT_COMMAND` in a `.vimrc` instead of in my shell config? I only use FZF in vim so I'd like to keep it with my other vim settings instead of as a side effect in my `.bash_profile`.

p.s. thank you for the fantastic plugin!

**Comment by junegunn** [comment]
`let $FZF_DEFAULT_COMMAND = 'echo foo'`

**Comment by trevordmiller** [comment]
@junegunn Thank you!

**Comment by justrajdeep** [comment]
Thanks
