### ISSUE TITLE
Respect Vim colorscheme

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf.vim#59]
It would be possible to change the colors of fzf according to the current color scheme.

**Comment by junegunn** [comment]
```vim
function! s:update_fzf_colors()
  let rules =
  \ { 'fg':      [['Normal',       'fg']],
    \ 'bg':      [['Normal',       'bg']],
    \ 'hl':      [['Comment',      'fg']],
    \ 'fg+':     [['CursorColumn', 'fg'], ['Normal', 'fg']],
    \ 'bg+':     [['CursorColumn', 'bg']],
    \ 'hl+':     [['Statement',    'fg']],
    \ 'info':    [['PreProc',      'fg']],
    \ 'prompt':  [['Conditional',  'fg']],
    \ 'pointer': [['Exception',    'fg']],
    \ 'marker':  [['Keyword',      'fg']],
    \ 'spinner': [['Label',        'fg']],
    \ 'header':  [['Comment',      'fg']] }
  let cols = []
  for [name, pairs] in items(rules)
    for pair in pairs
      let code = synIDattr(synIDtrans(hlID(pair[0])), pair[1])
      if !empty(name) && code > 0
        call add(cols, name.':'.code)
        break
      endif
    endfor
  endfor
  let s:orig_fzf_default_opts = get(s:, 'orig_fzf_default_opts', $FZF_DEFAULT_OPTS)
  let $FZF_DEFAULT_OPTS = s:orig_fzf_default_opts .
        \ empty(cols) ? '' : (' --color='.join(cols, ','))
endfunction

augroup _fzf
  autocmd!
  autocmd ColorScheme * call <sid>update_fzf_colors()
augroup END
```

**Comment by nhooyr** [comment]
Added this to my fork, works well.

**Comment by nhooyr** [comment]
I'm gonna try and make the rest of the code respect the colorscheme as well.

**Comment by statico** [comment]
If anyone else finds this super-useful snippet, note that this has since been integrated into fzf.vim with [the `g:fzf_colors` setting](https://github.com/junegunn/fzf.vim#global-options).

Also note that in the script above, the `code` will/might be a hex color like `#aabbcc`, so the `code > 0` might need to be `code != ''` instead.

**Comment by atav32** [comment]
does this work in the preview window too?

**Comment by simlei** [comment]
Hi, I would second that question whether that works in Preview. For me, it does not seem like it.

I have enabled the default XTERM palette, the [Papercolor](https://github.com/NLKNguyen/papercolor-theme) theme, and the color options from https://github.com/junegunn/fzf.vim#global-options.

I have read and tried several variants of the fix suggested in https://github.com/junegunn/fzf.vim/issues/76 for the command that opends the preview window - but I don't see how that would help in any way, just for completeness.

it looks like this:
![image](https://user-images.githubusercontent.com/982379/39751300-04e9db8c-52b8-11e8-849e-7bd91eb0d4c6.png)

**Comment by simlei** [comment]
I guess dealing with terminal must be the worst, so please do take my highest congratulations to fzf as a tool and vim Plugin. It really is something special :)

**Comment by junegunn** [comment]
fzf has no control over the colors in the preview window. Those colors are from the tools that generate the preview contents.

**Comment by simlei** [comment]
Mh. From the doc, I have already read: 'highlight|coderay|rouge' are the three tools that are supported, all ruby. ``which`` shows thez have no executables on the PATH. Maz be I have installed one of those three some time ago. In any case: how would I pass different coloring to one of those tools, would you be so kind to provide an exemplary vimscript line?

**Comment by atav32** [comment]
@junegunn what tool is that again?

**Comment by simlei** [comment]
Quoted from the readme:
```
Augmenting Ag command using fzf#vim#with_preview function
"   * fzf#vim#with_preview([[options], preview window, [toggle keys...]])
"     * For syntax-highlighting, Ruby and any of the following tools are required:
"       - Highlight: http://www.andre-simon.de/doku/highlight/en/highlight.php
"       - CodeRay: http://coderay.rubychan.de/
"       - Rouge: https://github.com/jneen/rouge
"
"   :Ag  - Start fzf with hidden preview window that can be enabled with "?" key
"   :Ag! - Start fzf in fullscreen and display the preview window above
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```
I took those examples and they work up to the coloring. What I would love is a pointer where to configure the preview tool. Ideally to configure the tool and with that, it's options. Right now I cant even tell, though, which of them I have installed in the past. I know - not a very strong show. I can just tell that I read the fzf.vim help files cover to cover and found nothing about the preview tool config options.

Therefore, I would really appreciate a pointer on how to proceed. I would be most thankful :)

**Comment by simlei** [comment]
Well, as it seems, the three names highlighte4rs are currently hardwired -- just as the doc suggests. dependen on whether ruby is installed, ``bin/preview.sh`` or ``bin/preview.rb`` is used. I have not found an option to adapt the receiving end of the default preview binary - correct me if I am wrong, please.

In the ``bin/preview.rb`` the three ruby-based highlighters are hard-wired as one can easily observe. No options are passed. Either, one adapts those bin scripts, are uses a hacky approach (like me, to keep that repo untouched). In my ~/.local/bin (must be on the PATH ofc.) I created the following rougify adapter script whiches fixes the theme I want to pass:

```
#!/bin/bash
localRougify="/home/simon/installations/rouge/bin/rougify"
: ${FZF_ROUGIFY_PREV_THEME:="pastie"}
if [[ $# == 1 ]]; then
    "$localRougify" highlight -t "$FZF_ROUGIFY_PREV_THEME" "$1"
else
    "$localRougify" "$@"
fi
```
Where that path in the 2nd line points to where I have cloned rouge to.

I would like to see a more easy way though to do this and still use the original /bin files of the fzf.vim repo. In the meantime, I'm good with this hack :)

**Comment by fabriziobertoglio1987** [comment]
@junegunn can you please re-open this issue. Is affecting me. Thanks

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim#dependencies

> For syntax-highlighted preview, install bat

`man bat` and look for `BAT_THEME`.

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot. I appreciate the feedback and I tried to implement those suggestions (adding env variable to BAT_THEME and event creating an alias for bat that uses the correct theme)... but I also tested the command

```
fzf --preview="bat --theme='ansi-light' --color=always ./fzf.vim"
```

<image src="https://user-images.githubusercontent.com/24992535/107523834-6f91a280-6bb5-11eb-8ec3-f4f93ca1845e.png" width="500" />

I searched your repo and I would probably have to build this from source and changing 

https://github.com/junegunn/fzf.vim/blob/68ab6455743066165caa2e0f39e607e9c94b0bba/bin/preview.sh#L66

somehow I ended up stashing those changes and going back using normal :Rg with the package https://github.com/jremmen/vim-ripgrep 

hopefully one day in my free time I'll be able to fork this and fix this, but right now using `vim-grep` in combination with binding 

```
nnoremap <silent><C-n> :cn<cr>
nnoremap <silent><C-p> :cp<cr>
```
I'll set it up as a TODO for my weekends when I'll be little bit more relaxed
works great .. Thanks and sorry I couldn't help more :peace_symbol:  :pray:
