### ISSUE TITLE
Tags and folding

### ISSUE THREAD

**Issue by mdi** [junegunn/fzf.vim#591]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a way unfold a folded block of text automatically when navigating via Tags/BTags? Other vim navigation commands do this, but fzf.vim doesn't seem to support it.

**Comment by junegunn** [comment]
Oh, I don't use folds so I wasn't aware of the issue. You can try configuring `foldopen` option (see `:help 'foldopen'`). `set foldopen=all` seems to do the trick but I don't know if it's the right option for you.

**Comment by mdi** [comment]
That seems to work. Thanks!

**Comment by mdi** [comment]
Actually, setting `foldopen=all` doesn't seem like a great solution as it causes folds to open whenever you move across a fold. The default value of `block,hor,insert,jump,mark,percent,quickfix,search,tag,undo` works for other navigation commands except fzf using `Tags` or `BTags`.

**Comment by oldsouless** [comment]
had this same issue and it bugged me to no end; this is hacky and breaks on every fzf.vim update but until Junegunn closes; attached is my fix for anyone who needs.
[fixes_591.txt](https://github.com/junegunn/fzf.vim/files/2620746/fixes_591.txt)

**Comment by junegunn** [comment]
Please consider opening a pull request (see related change: https://github.com/junegunn/fzf.vim/commit/c3954d294a0f6c4fb5a46a1839cd42ec26767dea)
Is `zM` required?

**Comment by oldsouless** [comment]
no I just defaulted to that since I use it in other fold related functions to focus and unfold; zvzz would probably suffice since you're probably already handling focus.

**Comment by syphar** [comment]
@junegunn after https://github.com/junegunn/fzf.vim/pull/1133 is merged we can close this issue, right? 

Or am I forgetting something?
