### ISSUE TITLE
Allow Rg/Ag commands to take arguments

### ISSUE THREAD

**Issue by RobertBuhren** [junegunn/fzf.vim#596]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x]] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

The current implementation of Rg/Ag does not take any arguments. It would be nice to be able to specifiy the target directory: "Rg ../foobar" and/or arguments to Rg/Ag

**Comment by junegunn** [comment]
Define your own search command with `fzf#vim#grep` as shown in https://github.com/junegunn/fzf.vim#advanced-customization, but without `shellescape`.

**Comment by kurdybacha** [comment]
@junegunn you suggestion with dropping `shwllescape` does not work. Rg does not return any results. Is it anything else that I might be missing?

**Comment by nickjj** [comment]
I'm having the same problem too. I tried without `shellescape` but there's no output.

Ideally I would like to be able input `:Rg foo --glob *.md` to limit search to only Markdown files, or also have the option to pass in other `rg` flags after the search term.

**Comment by dkvasnicka** [comment]
You can work around this by using https://github.com/dyng/ctrlsf.vim#example -- I have it installed along `fzf.vim` anyway, because of the well done interactive multi-file search and replace. So it's not like you'd be installing the thing just because you need `rg` args support.

**Comment by tinova** [comment]
For reference, this is what worked for me (I'm a vimscript noob, so any feedback is appreciated):

`  \   'rg --column --line-number --no-heading --color=always --smart-case '.(<q-args>),`

**Comment by eL0ck** [comment]
Hi @tinova, have you tried choosing a few (`<TAB>` ) and sending them to the quickfix window (`<ENTER>` )?

Using your code I get the following error:
```
Error detected while processing function fzf#vim#grep[22]..<SNR>148_fzf[18]..fzf#run[69]..<SNR>20_callback:
line   21:
Vim(let):E728: Using a Dictionary as a Number
Press ENTER or type command to continue
```
However this fixes it:
```
  \   'rg --column --line-number --no-heading --color=always --smart-case '.(<q-args>), 1,
```

Full function re-definition:
```
"Redefine Rg command to allow rg arguments to pass through
" such as `-tyaml` for yaml files or `-F` for literal strings
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```

**Comment by tinova** [comment]
Hi @eL0ck! I'm sure I'm missing something, but isn't it the same line?

**Comment by eL0ck** [comment]
`, 1,` at the end of the line @tinova ;)

**Comment by tinova** [comment]
blind as a bat 🦇 . Thanks @eL0ck !

**Comment by benfrain** [comment]
Tried the above but couldn't get it working. I'm a vimscript dunce so if anyone could point me in the direction of how I amend the following to allow me pass in arguments e.g. `:Rg data-thing --tts` (to search for "data-thing" in "*.ts" files for example):

```
" ripgrep if we have it
if executable('rg')
    let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!.git/*"'
endif


 function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)
```

**Comment by moorecode** [comment]
I've been using keybinds to toggle some options, for example `ctrl-p` to only search python files, `ctrl-a` to switch back to searching all files - I'm sure you can extend this to support whatever else you want:
```vimscript
function! RipgrepFzf(query, fullscreen)
    let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
    let initial_command = printf(command_fmt, shellescape(a:query))
    let reload_command = printf(command_fmt, '{q}')
    let reload_command_py = printf(command_fmt, '-t py {q}')
    let spec = {'options': ['--phony', '--query', a:query,
                \ '--bind', 'change:reload:'.reload_command,
                \ '--bind', 'ctrl-a:change-prompt(Rg>)+reload('.reload_command.')+rebind(change)',
                \ '--bind', 'change:reload:'.reload_command,
                \ '--bind', 'ctrl-p:change-prompt(Rg py>)+reload('.reload_command_py.')+rebind(change)',
                \ '--bind', 'change:reload:'.reload_command_py ]}
    call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction
command! -nargs=* -bang Rg call RipgrepFzf(<q-args>, <bang>0)
```

**Comment by SmilingJack1** [comment]
> Tried the above but couldn't get it working. I'm a vimscript dunce so if anyone could point me in the direction of how I amend the following to allow me pass in arguments e.g. `:Rg data-thing --tts` (to search for "data-thing" in "*.ts" files for example):

For the record, should perhaps use `fzf#shellescape(a:query)` instead of `shellescape(a:query)`. But I don't know if that's the cause
