### ISSUE TITLE
Support funcref in fzf#run source

### ISSUE THREAD

**Issue by timgreen** [junegunn/fzf.vim#597]
Currently `source` only support 
* string,  External command to generate input to fzf
* list, Vim list as input to fzf 

My case is I need call a plugin function to retrieve the list. Is that possible to support funcref for source as well.

---

- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

**Comment by junegunn** [comment]
You don't need it.

```vim
function! Foo()
  return [1, 2, 3]
endfunction

" Foo() is evaluated when the command or the mapping is executed
command! FOO call fzf#run({'source': Foo()})
nnoremap <leader>FOO :call fzf#run({'source': Foo()})<cr>
```
