### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by kevintraver** [junegunn/fzf.vim#6]
It would be nice to search the command line mode history.

Thanks!

**Comment by mttbrstn** [comment]
I bodged this together for myself. It works, but it might be terrible since I don't know vimscript and am a neophyte in general.

    "FZF Command History

    function! s:mycommand_sink(cmd)
        let cmd = substitute(a:cmd, '\d..', '', 'g') 
        execute cmd
    endfunction

    function! s:commands(bang)
      redir => history
      silent history
      redir END
      let list = split(history, '\n')
        call fzf#run({
                    \ 'source':  reverse(extend(list[0:0], map(list[2:], 's:format_cmd(v:val)'))),
                    \ 'sink':    function('s:mycommand_sink'),
                    \ 'options': '--ansi -x --prompt "Commands> " ',
                    \ 'window': 'aboveleft 20new'}, a:bang)
    endfunction

    command! -bang Cmds call s:commands(<bang>0)

**Comment by kevintraver** [comment]
Awesome. Thanks!

**Comment by junegunn** [comment]
@mttbrstn Looks okay, though `fzf#run` takes only a single parameter and `a:bang` you passed is simply ignored.

I'll consider adding the command to the repo.

**Comment by mttbrstn** [comment]
Thanks for the clarification! Feel free to add/use as you wish.

**Comment by kevintraver** [comment]
👍
