### ISSUE TITLE
:Ag just match the content not the file/directory name

### ISSUE THREAD

**Issue by jezeniel** [junegunn/fzf.vim#602]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi, is there a way for `:Ag` command to just match the code and not the filename? When I am searching for a piece of code it also matches a directory/file name?

**Comment by someneat** [comment]
https://github.com/junegunn/fzf.vim/issues/346.
