### ISSUE TITLE
Command to checkout git branches

### ISSUE THREAD

**Issue by stsewd** [junegunn/fzf.vim#603]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Would be nice if there is a fzf command to checkout git branches, some times I work with a project with a lot of branches.

**Comment by stsewd** [comment]
This is what I did, it's not perfect but it works :)

```vim
function! s:open_branch_fzf(line)
  let l:parser = split(a:line)
  let l:branch = l:parser[0]
  if l:branch ==? '*'
    let l:branch = l:parser[1]
  endif
  execute '!git checkout ' . l:branch
endfunction

command! -bang -nargs=0 GCheckout
  \ call fzf#vim#grep(
  \   'git branch -v', 0,
  \   {
  \     'sink': function('s:open_branch_fzf')
  \   },
  \   <bang>0
  \ )

```

**Comment by danielo515** [comment]
Any idea to merge this suggestion into the plugin?

**Comment by junegunn** [comment]
@danielo515 Nope. You can just put it in your Vim configuration file and customize it however you want.

**Comment by danielo515** [comment]
And that is what I did, but I thought it was common enough to be included on the plug-in.
Anyway, thanks

**Comment by srijanshetty** [comment]
@danielo515: You should take a look at https://github.com/tpope/vim-fugitive which has git wrappers for most use-cases.

**Comment by danielo515** [comment]
> @danielo515: You should take a look at https://github.com/tpope/vim-fugitive which has git wrappers for most use-cases.

Yes, I have vim fugitive installed, but as far as I know it does not integrate with fzf.vim. In any case, the provided solution here is good enough for me

**Comment by danielo515** [comment]
By the way @stsewd, why you used `l:` for the  variable names ? Aren't they locally scoped by default?

**Comment by stsewd** [comment]
@danielo515 I use vimlint https://github.com/syngan/vim-vimlint (it recommends being explicit with local vars)

Also, I have improved the above script. Now it shows the current branch (I've only tested it in neovim)

https://github.com/stsewd/dotfiles/blob/7a9a8972c8a994abf42d87814980dc92cdce9a22/config/nvim/init.vim#L419-L432

![Screenshot from 2020-03-02 19-59-11](https://user-images.githubusercontent.com/4975310/75732503-a16d6a00-5cc0-11ea-9374-0841dae24779.png)

**Comment by danielo515** [comment]
> @danielo515 I use vimlint https://github.com/syngan/vim-vimlint (it recommends being explicit with local vars)
> 
> Also, I have improved the above script. Now it shows the current branch (I've only tested it in neovim)
> 
> https://github.com/stsewd/dotfiles/blob/7a9a8972c8a994abf42d87814980dc92cdce9a22/config/nvim/init.vim#L419-L434
> 
> ![Screenshot from 2020-03-02 19-59-11](https://user-images.githubusercontent.com/4975310/75732503-a16d6a00-5cc0-11ea-9374-0841dae24779.png)

That is awesome!! Thank you very much. learnt something new 😄

**Comment by Shatur95** [comment]
> Also, I have improved the above script. Now it shows the current branch (I've only tested it in neovim)
https://github.com/stsewd/dotfiles/blob/7a9a8972c8a994abf42d87814980dc92cdce9a22/config/nvim/init.vim#L419-L434

Thank you a lot for it!
I also replaced `sort -u` with `--sort=-committerdate` to sort by last commit.

**Comment by stsewd** [comment]
btw, I ended up making a plugin https://github.com/stsewd/fzf-checkout.vim same thing, but we some improvements and nicer listing

>  I also replaced sort -u with git's --sort=-committerdate to sort by last commit.

That looks like a good setting to add :)

**Comment by Shatur95** [comment]
@stsewd, looks very cool, I will switch to it.

**Comment by danielo515** [comment]
Awesome @stsewd, I'll give it a try

**Comment by rodhash** [comment]
> This is what I did, it's not perfect but it works :)
> 
> ```viml
> function! s:open_branch_fzf(line)
>   let l:parser = split(a:line)
>   let l:branch = l:parser[0]
>   if l:branch ==? '*'
>     let l:branch = l:parser[1]
>   endif
>   execute '!git checkout ' . l:branch
> endfunction
> 
> command! -bang -nargs=0 GCheckout
>   \ call fzf#vim#grep(
>   \   'git branch -v', 0,
>   \   {
>   \     'sink': function('s:open_branch_fzf')
>   \   },
>   \   <bang>0
>   \ )
> ```
> 
> edit: I just did a small plugin https://github.com/stsewd/fzf-checkout.vim

Awesome .. thank you sir!

I added a "sil" before the checkout just to avoid that annoying confirmation message .. I never had errors while switching branches so I suspect that "sil" won't hurt much

**Comment by GopherJ** [comment]
I like git commit more

```
nnoremap ;g  : GCheckout<CR>
function! s:open_commit_fzf(line)
  let l:parser = split(a:line)
  let l:branch = l:parser[0]
  if l:branch ==? '*'
    let l:branch = l:parser[1]
  endif
  silent! execute '!git checkout ' . l:branch
endfunction

command! -bang -nargs=0 GCheckout
  \ call fzf#vim#grep(
  \   'git log --pretty=oneline --reverse --all', 0,
  \   {
  \     'sink': function('s:open_commit_fzf')
  \   },
  \   <bang>0
  \ )


```
