### ISSUE TITLE
Add :Args to quickly switch to different file in arglist

### ISSUE THREAD

**Issue by kiryph** [junegunn/fzf.vim#605]
What about adding fuzzy completion for items in the arglist e.g. with a command called `:Args`?

A similar idea has already applied to CtrlP: https://github.com/kshenoy/vim-ctrlp-args

### Background

I recently suggested on the vim issue tracker https://github.com/vim/vim/issues/2706 to add cmdline-completion support for the command `:argu[ment] {item in arglist}`.

However, Bram was not in favour of adding this, because right now the command `:argu` only accepts a number specifying the entry on the arglist. Changing this to accept also filenames would lead to an ambiguity if a filename is a simple number. This problem already exists for the `:buffer` command:

> Changing :argument to accept a buffer name is tricky: what if an argument is a number?
I know for buffer names we already have this confusion.

However, cmdline-completion support for `:argdelete` has been added and general support for arglist completion: https://github.com/vim/vim/commit/cd43effecab02c6c28b1c4a3a14f91b8c3f26c0d

Note, there are following arglist related vim functions
- `argc()`,
- `argidx()`,
- `arglistid([{winnr} [, {tabnr}]])`, and
- `argv([{nr}])`.

With the recent commit a user can define his own command with cmdline-completion for the arglist via `-complete=arglist` and evaluate a pattern match with the arglist via `getcompletion({pat}, 'arglist' [, {filtered}])`.

**Comment by junegunn** [comment]
Thanks for the suggestion but for the moment I'm not interested in adding more commands to this repository, especially the ones that I'm not going to use often.

But you can still implement any command using `fzf#run` and `fzf#wrap` if you know VimScript.
See https://github.com/junegunn/fzf/blob/master/README-VIM.md

 I'll leave this open to see if anyone's interested in contributing.

**Comment by kiryph** [comment]
Thanks for your thoughts.

If I understand you correctly, you would also not accept a PR for this except several users raise their voice.

### User customization

A quick first custom command:
```viml
command! -bang Args call fzf#run(fzf#wrap('args',
    \ {'source': argv()}, <bang>0))
```

A non-elegant solution to put the active item from the arglist up front:

```viml
command! -bang Args call fzf#run(fzf#wrap('args',
    \ {'source': map([argidx()]+(argidx()==0?[]:range(argc())[0:argidx()-1])+range(argc())[argidx()+1:], 'argv(v:val)')}, <bang>0))
```

Do you know a more elegant solution to achieve this?

**Comment by junegunn** [comment]
Looks good, nothing inelegant about your solution.

So the code is pretty simple and I don't see much point in adding it to fzf.vim. You know, it's hard to get motivated for maintaining, debugging, and improving a feature that I don't use.

**Comment by kiryph** [comment]
I certainly understand you.

My code sample could be improved to support `:Args <arglistid>` and something like `:Largs` to operate on a local arglist which I do not use myself. A polished and comprehensive experience would need more work which one would only do if one uses it.

I use the arglist on very few occasions myself and then only a single list.

I think if I improve the user experience of the arglist, I would use it in more situations.
Therefore I have already configured the statusline to show the number of items in the arglist, use vim-unimpaired for `[a`, `]a`, `[A`, and `]A`, and now have a fuzzy completion navigation.

I still miss `:argu <C-d>` to see the arglist, but I did not manage to convince Bram to support this.

For explanations when you can use the the arglist see:

- http://vimcasts.org/episodes/meet-the-arglist/
- http://vimcasts.org/episodes/populating-the-arglist/
- http://vimcasts.org/episodes/using-argdo-to-change-multiple-files/
- [Practical Vim – Tip 38 Group Buffers into a Collection with the Argument List by D. Neil]( https://books.google.de/books?id=LA9QDwAAQBAJ&pg=PT166&lpg=PT166&dq=vim+arglist&source=bl&ots=3LwS_6hLYk&sig=WKDMlyGHVmKaKbQZEPMLigNx2S4&hl=de&sa=X&ved=0ahUKEwj_mcuYxZPaAhXRC-wKHf_jBnQ4FBDoAQgnMAA#v=onepage&q=vim%20arglist&f=false)
