### ISSUE TITLE
:Ag with part of filename is useless - possible to exclude filenames from search?

### ISSUE THREAD

**Issue by Ploppz** [junegunn/fzf.vim#609]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

If you run `:Ag` in (n)vim and type some text which coincides with part of some file name, the fzf window will first and foremost show unrelated (short) lines of that file. Example:
![screenshot](https://i.imgur.com/umEOphb.png)

Is it possible to make `ag` ignore filenames?

**Comment by Ploppz** [comment]
The suggested `command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)` worked well, thanks!

I still think this would be a sane default though.

**Comment by flyrry** [comment]
Same is possible for ripgrep:
`command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)   `
