### ISSUE TITLE
:Files search files vim start directory ?

### ISSUE THREAD

**Issue by tthanh** [junegunn/fzf.vim#61]
I start vim in ~/.dotfiles
use :Files to open script in ~/.dotfiles/bin/
then if I use :Files again, it only search in ~/.dotfiles/bin
Anyway to make :Files search all files in ~/.dotfiles ?

I use neovim and don't have set audo_cd in config

**Comment by junegunn** [comment]
This: https://github.com/tthanh/dotfiles/blob/master/config/nvim/init.vim#L311

**Comment by tthanh** [comment]
Thank you so much. I forgot I had that line in my config

**Comment by zhimsel** [comment]
I seem to be experiencing the same behavior, but I don't have a similiar `au` as @tthanh did, nor is `autochdir` set... Any ideas?

**Comment by zhimsel** [comment]
To be specific, when opening a file from `:Files`, it `cd`'s to the directory of the file I go to, instead of staying at the same dir.

**Comment by zhimsel** [comment]
Never mind... found the culprit: https://github.com/zhimsel/dotfiles/commit/6759659e8ccb5abdde2a6df8fde6e3266ba97b7b

**Comment by zhimsel** [comment]
@junegunn scratch that... that wasn't the cause. Any ideas?

**Comment by junegunn** [comment]
@zhimsel No idea, probably some plugin you have is getting in the way.

**Comment by unr** [comment]
Had a similar issue with a nearly-fresh setup, was going insane.

To solve this problem, I discovered that (vim-startify](https://github.com/mhinz/vim-startify) would auto change my directory when opening a file.

[In the docs](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L301), and an how I fixed:

```bash
 let g:startify_change_to_dir = 0
```
