### ISSUE TITLE
Ag lags before opening a file in MacVim

### ISSUE THREAD

**Issue by AmaruCoder** [junegunn/fzf.vim#610]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] MacVim
    - [ ] Neovim

When I use the command Ag to select a file, everything works blazingly fast, which is great. But when I press enter to open the selected file, the search window goes blank (see below), and there is a lag of two or three seconds before the file is open.

<img width="780" alt="screen shot 2018-04-04 at 6 44 11 pm" src="https://user-images.githubusercontent.com/2724075/38343371-6c8741c0-3838-11e8-8bf8-184b0a18f988.png">

**Comment by junegunn** [comment]
See https://github.com/macvim-dev/macvim/issues/685
