### ISSUE TITLE
vim as preview window

### ISSUE THREAD

**Issue by razic** [junegunn/fzf.vim#612]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'd like to use a Vim buffer itself as the preview. This way I can keep my syntax highlighting. I tried using Pygments but the tokenization is different than my Vim syntax highlighting, so even using the same colors, it looks odd. Any ideas? What are you using?

**Comment by junegunn** [comment]
I use [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.html). I don't care too much about the difference in highlighting, but yeah, it would be nice if we could use actual Vim for getting the highlighted text, but I haven't found a solution. But even if it works, I presume that it'll be much slower than highlight and such, so it may not be a good fit for previewing.

**Comment by goolord** [comment]
some examples of fuzzy finder plugins which can use vim buffers for their preview windows:

- https://github.com/liuchengxu/vim-clap
- https://github.com/nvim-telescope/telescope.nvim

they can all use fzf as their fuzzy finding backend

**Comment by junegunn** [comment]
They are native Vim plugins using Vim buffers. On the other hand, fzf is a separate command-line program that renders its own screen, so Vim highlighting is not available to it.

In 2021, [`bat`](https://github.com/sharkdp/bat) is the recommended program to use with fzf.vim for preview highlighting. You can configure its color theme via `$BAT_THEME` environment variable.

- https://github.com/junegunn/fzf.vim#dependencies
