### ISSUE TITLE
Vim plugin don't create ~/.fzf

### ISSUE THREAD

**Issue by toblerone1963** [junegunn/fzf.vim#614]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi,

I install FZF with Vundle, it works perfectly, but `Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }` seems to not install anything in ~/.fzf (or create the folder if missing). I try to clean and reinstall the plugin, but it remain the same (and everything is up to date). It's actually only a problem because I wanted to change the FZF_DEFAULT_COMMAND to add Ripgrep or ag. So maybe it's not that big of a problem if we can modify it by keeping fzf only as a vim plugin.

Thanks for everything (fzf change my life!)

**Comment by junegunn** [comment]
`dir` and `do` options are not supported by Vundle. You'll have to run it manually.
