### ISSUE TITLE
fzf ag broke?

### ISSUE THREAD

**Issue by vito-c** [junegunn/fzf.vim#615]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

I have a custom command that calls fzf ag (below) the result of groot is just the git root for that specific file.

```
command! -nargs=* Rag
  \ call fzf#vim#ag(<q-args>, extend(g:rc#git#groot(), g:fzf_layout))
```

I am getting the following error:
```
Error detected while processing function fzf#vim#ag[8]..fzf#vim#ag_raw[4]..fzf#vim#grep[22]..<SNR>184_fzf[18]..fzf#run[64]..<SNR>87_execute_term:
```

I'm on a362bc5 of fzf.vim

**Comment by giftig** [comment]
![fwrj5kd0_400x400](https://user-images.githubusercontent.com/2862039/40332018-5273619c-5d4a-11e8-89c9-f6a3d7ad6923.jpeg)

**Comment by vito-c** [comment]
@giftig you've been defined. I called it `groot` because it's my git root and because ... groot
```viml
function! rc#git#groot() " {{{
    let groot = systemlist('git -C ' . expand('%:p:h') . ' rev-parse --show-toplevel')[0]
    let pwd = expand('%:p:h')
    return v:shell_error ? {'dir': pwd } : {'dir': groot}
endfunction " }}}
```

**Comment by vito-c** [comment]
I think this was fixed though 👍
