### ISSUE TITLE
Can fzf.vim create cache path for tags?

### ISSUE THREAD

**Issue by hackingcat** [junegunn/fzf.vim#623]
- Category
    - [ ] Question
    - [ ] Bug
    - [ x] Suggestion
- OS
    - [ x] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ x] Neovim

I think fzf.vim can make a collaboration with ludovicchabant/vim-gutentags on Tags function.Just like Yggdroot/LeaderF,

            if !isdirectory(s:vim_tags)
            silent! call mkdir(s:vim_tags, 'p')
            endif

            let s:vim_tags = expand('~/.cache/tags')
            let g:gutentags_cache_dir = s:vim_tags
            
            let g:Lf_CacheDirectory = expand('~/.vim/cache')

**Comment by junegunn** [comment]
I don't use vim-gutentags.
