### ISSUE TITLE
Go up to parent dir if :FZF

### ISSUE THREAD

**Issue by phaazon** [junegunn/fzf.vim#624]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [x] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a way to go up to the parent directory (keybinding, whatever)? It’s very frustrating to be at almost the leaf of my tree and not being able to search other files.

**Comment by atav32** [comment]
You could use `git grep`. From the advanced customization section,

```
" Command for git grep
" - fzf#vim#grep(command, with_column, [options], [fullscreen])
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   { 'dir': systemlist('git rev-parse --show-toplevel')[0] }, <bang>0)
```

**Comment by phaazon** [comment]
I’ve found a partial solution to that: `:cd`. It’s not the _right solution_ I expected but it’s an easy workaround. I guess I could use a keybinding to `:cd ..`?

**Comment by junegunn** [comment]
You can pass a directory to the command, i.e. `:FZF ..` or `:FZF ../..`, etc.

Also, you might want to check out `fzf#run` function if you're interested in defining your own commands using Vimscript. See: https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

```vim
call fzf#run(fzf#wrap({'dir': '~'}))
```

**Comment by xarthurx** [comment]
I've also encountered this question as a newbie for vim-fzf.
However, I found it very convenient to map it to `M-<backspace>`, as I previously used in other plugins.

Maybe thing similar to this can be considered to add as a default?

**Comment by c02y** [comment]
@xarthurx How can I map `M-<backspace>` to `:FZF ..` only when I'm using fzf functions such as `:Files`?

**Comment by xarthurx** [comment]
@c02y  I haven't done. That's what was possible in Emacs.

**Comment by fx500ms** [comment]
My workaround:
```
nnoremap <silent><leader>lr :Files %:p:h<cr>
nnoremap <silent><leader>l0 :Files %:p:h<cr>
nnoremap <silent><leader>l1 :Files %:p:h:h<cr>
nnoremap <silent><leader>l2 :Files %:p:h:h:h<cr>
nnoremap <silent><leader>l3 :Files %:p:h:h:h:h<cr>
```

**Comment by gmelodie** [comment]
I came here wanting something a bit different: 
1. Type `:Files`
2. Type: `../../`
3. I want it to show me the list of files on that directory (two above)

Is there a way to do this?
