### ISSUE TITLE
Cannot searching file with fzf

### ISSUE THREAD

**Issue by emaniacs** [junegunn/fzf.vim#63]
I cant searching file with my vim

When i press :FZF nothing happen

https://asciinema.org/a/d437p3kav94kuqznp88bgqg2k

**Comment by junegunn** [comment]
Hi, please post your vimrc.

**Comment by emaniacs** [comment]
This is my vimrc
https://github.com/emaniacs/my-dot-config/blob/master/dot-vimrc

**Comment by junegunn** [comment]
Do you still have the issue when you start with the bare minimum? Try this:

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/3cc41081204aac73c5fe/raw/7100401648b0041a2d2c7576eebf055e72cd53be/gistfile1.txt)
```

**Comment by emaniacs** [comment]
Its work with bare minimum config, i gonna try to remove another plugin and try it.

Thanks. :)

**Comment by junegunn** [comment]
Alright, let me know if you find the conflicting configuration.
