### ISSUE TITLE
vim-plug bug 

### ISSUE THREAD

**Issue by HQupgradeHQ** [junegunn/fzf.vim#631]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Using choco , tried to get plugin working , but with no success. 
The problem was in my [plugin manager](https://github.com/junegunn/vim-plug) where I have to activate `Fzf` in init.vim _explicitly_ , e.g 
`Plug 'junegunn/fzf' ,{'on':'Fzf'}
Plug 'junegunn/fzf.vim',{'on':'Fzf'}
`

**Comment by HQupgradeHQ** [comment]
Another possible solution is to point loading this script manually on Windows, in my init.vim this is done by adding those lines 
`autocmd VimEnter * source C:\Users\upgrade\AppData\Local\nvim\plugged\fzf\plugin\fzf.vim
autocmd VimEnter * source C:\Users\upgrade\AppData\Local\nvim\plugged\fzf.vim\plugin\fzf.vim
autocmd VimEnter * source C:\Users\upgrade\AppData\Local\nvim\plugged\fzf.vim\autoload\fzf\vim.vim
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim', {'on':'Fzf'}
`
:grey_exclamation:

**Comment by janlazo** [comment]
You want to use on-demand loading with the `Fzf` user command? This repo suggests `Fzf` as a command prefix so it is not defined as a command. Question is why you want to use on-demand loading for fzf.vim when fzf.vim uses `autoload/` for built-in lazy loading.

**Comment by junegunn** [comment]
> The problem was in my plugin manager where I have to activate Fzf in init.vim explicitly

No, you don't. And `{'on':'Fzf'}` is completely unnecessary and it's really not how it's supposed to be used. Please make sure that you have configured vim-plug correctly. One common mistake is missing `call plug#end()` at the end.
