### ISSUE TITLE
dynamically  adjust window size

### ISSUE THREAD

**Issue by ilAYAli** [junegunn/fzf.vim#632]
- Category
    - [ ] Question
    - [ ] Bug
    - [ X] Suggestion
- OS
    - [ X] Linux
    - [ X] macOS
    - [ X] Windows
    - [ X] Etc.
- Vim
    - [X ] Vim
    - [ X] Neovim

I would like the ability to dynamically shrink the fzf window if the number of candidates are less than some predefined max height.

pseudo code of what I want to achieve:

`au FileType fzf dynamically_shrink_window_if_less_than_one_quarter_of_the_screen_height(min(&lines / 4, len(getqflist())) wincmd_`

Is that somehow doable?

**Comment by junegunn** [comment]
If the source option for `fzf#run` is a Vim list (so we know the exact size of it) and the layout option is `down` or `up` starting with `~`, fzf can start a smaller window.

```vim
call fzf#run({'source': [1, 2, 3], 'down': '~40%'}))

" fzf#wrap injects 'down': '~40%' by default, so
call fzf#run(fzf#wrap({'source': [1, 2, 3]}))
```

But dynamic resize is not supported.

**Comment by hakunin** [comment]
Can you share your solution if this was solved? I'd like to have it resize as well. Thanks!
