### ISSUE TITLE
Files with  unignore in .gitignore

### ISSUE THREAD

**Issue by theFool32** [junegunn/fzf.vim#633]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

It seems fzf can't handle with unignore in .gitignore
For example, if I have a .gitignore like below:
```
*.*
!*.py
```
to track only python scripts, `:Files` will give empty result.

**Comment by junegunn** [comment]
`:Files` command internally starts fzf without explicit source, which means it gives the same result as you simply start `fzf` on your shell without stdin pipe. Which also means that it respects `$FZF_DEFAULT_COMMAND`.

See https://github.com/junegunn/fzf#respecting-gitignore

**Comment by junegunn** [comment]
So what I'm saying is that you should look into your `$FZF_DEFAULT_COMMAND`.

**Comment by theFool32** [comment]
```
> echo $FZF_DEFAULT_COMMAND
ag --hidden --ignore .git -g ""
```
and run `ag --hidden --ignore .git -g ""` resulting in nothing.
It should be a problem with `ag`

Thanks a lot.
