### ISSUE TITLE
Pass `--no-sort` option to fzf for `:History` command

### ISSUE THREAD

**Issue by Frydac** [junegunn/fzf.vim#634]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Hi,

I would like to pass the `--no-sort` option to fzf when using the `:History` command (and probably its variants, but haven't gotten used to using them yet).
I already have the following in my `.vimrc` to show the preview window for the `:History` command.
```
command! -bang -nargs=* History call fzf#vim#history(fzf#vim#with_preview())
```
Is it possible to add this extra option here? I don't seem to understand how the arguments are passed/parsed.

I've managed to get it to do what I want by editing
`fzf.vim/autoload/fzf/vim.vim`
```
function! fzf#vim#history(...)
  return s:fzf('history-files', {
  \ 'source':  s:all_files(),
  \ 'options': ['--no-sort', '-m', '--header-lines', !empty(expand('%')), '--prompt', 'Hist> ']
  \}, a:000)
endfunction
```

**Comment by junegunn** [comment]
You can try this:

```vim
command! -bang -nargs=* History call fzf#vim#history(fzf#vim#with_preview({'options': '--no-sort'}))
```

**Comment by Frydac** [comment]
That works! Thx!
