### ISSUE TITLE
Freezes when selecting file

### ISSUE THREAD

**Issue by voider1** [junegunn/fzf.vim#635]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hey, FZF used to work amazingly well. But today I installed it on a new machine and it just froze. I thought it was a problem with my config, but my friend which doesn't have any FZF configuration tried installing it and he had the exact same problem. If I can provide any more information, tell me how I could do that.

**Comment by cassava** [comment]
What version and Neovim setup do you have?
For my part, this happens with Neovim 0.3 in the AppImage form.
It certainly didn't happen from the PPA 0.2.2 version of Neovim.

**Comment by junegunn** [comment]
Sounds like an issue of Neovim. Check out #505 and report to Neovim team if it's a regression.
