### ISSUE TITLE
Can :Tags command match only symbol not file path

### ISSUE THREAD

**Issue by zxbuaa** [junegunn/fzf.vim#641]
:Tags [QUERY] command does fuzzy match both the symbol and file path within ctag, is it possible to match symbol only? If I want to search file there is :Files command already.

- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

**Comment by rperryng** [comment]
Hey, looks like a duplicate of https://github.com/junegunn/fzf.vim/issues/346

This should get you started:

```
command! -bang -nargs=* Tags call fzf#vim#tags(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

**Comment by zxbuaa** [comment]
Thanks @rperryng just change it a bit which works perfect!
```
command! -bang -nargs=* Tags call fzf#vim#tags(<q-args>, {'options': '--nth 1'}, <bang>0)
```
