### ISSUE TITLE
Switch ctags to universal ctags

### ISSUE THREAD

**Issue by PezCoder** [junegunn/fzf.vim#646]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I've recently switched to [universal-ctags](https://github.com/universal-ctags/ctags), as it is very well maintained & up to date & support many other languages. My current setup has universal ctags install by the name `uctags`

I generally use fzf.vim's `:BTags` & would like fzf.vim to utilise `uctags` if possible for just this command.

I can see where it's happening: 
https://github.com/junegunn/fzf.vim/blob/88595ebbaa33485cd1a4474701bd0e5809643520/autoload/fzf/vim.vim#L748-L750

& I tried replacing ctags with uctags in the library's code & it just works. I understand that this is something that we mayn't be able to put as a default in fzf.vim but Is there a way to make it easily switchable by supplying a parameter.

According to current settings, I think I might need to pass this same array strings to `fzf#vim#buffer_tags` with ctags replaced with uctags.

Looking for a cleaner solution. Appreciate any help. :)

**Comment by bedax** [comment]
I also use universal-ctags, and when I installed it from source, it installed its binary as `ctags`. Did you install it with a package manager or something? Either way, you could always create a symlink for it: `ln -s $(which uctags) /usr/local/bin/ctags`

**Comment by PezCoder** [comment]
@bedax Thanks for the tip.. ! 
I actually reinstalled universal ctags without a prefix & that worked just fine 🎉 

I was quite afraid of doing that before because `ctags` is something that comes preinstalled in mac & didn't want to mess something else up that might be depending on it. But I guess that's the easiest solution to the problem.
