### ISSUE TITLE
Feature request: yank history

### ISSUE THREAD

**Issue by bedax** [junegunn/fzf.vim#647]
It seems to me that this would be an excellent feature: A `:Yanks` command which would, through integration with yankstack or similar, list the yank history in fzf's usual way, and on selecting an entry, would then yank the content of that entry.

My vimscript abilities aren't the best, so it's unlikely I'd be able to implement this myself. Perhaps someone else with more skill thinks this would be useful too?

Either way, thank you for this excellent plugin.

**Comment by ultrox** [comment]
this is good idea

**Comment by junegunn** [comment]
Vim does not provide an API for retrieving the yank history, so it should be manually maintained. I'm not interested in implementing it in fzf.vim, but there are plugins for that and you should be able to integrate them with fzf. See #108

**Comment by fszymanski** [comment]
@bedax Simple example (if you're still interested)
```
function! s:get_registers() abort
  redir => l:regs
  silent registers
  redir END

  return split(l:regs, '\n')[1:]
endfunction

function! s:registers(...) abort
  let l:opts = {
        \ 'source': s:get_registers(),
        \ 'sink': {x -> feedkeys(matchstr(x, '\v^\S+\ze.*') . (a:1 ? 'P' : 'p'), 'x')},
        \ 'options': '--prompt="Reg> "'
        \ }
  return fzf#run(fzf#wrap(l:opts))
endfunction

command! -bang Registers call s:registers('<bang>' ==# '!')
```

**Comment by 00sapo** [comment]
> @bedax Simple example (if you're still interested)
> 
> ```
> function! s:get_registers() abort
>   redir => l:regs
>   silent registers
>   redir END
> 
>   return split(l:regs, '\n')[1:]
> endfunction
> 
> function! s:registers(...) abort
>   let l:opts = {
>         \ 'source': s:get_registers(),
>         \ 'sink': {x -> feedkeys(matchstr(x, '\v^\S+\ze.*') . (a:1 ? 'P' : 'p'), 'x')},
>         \ 'options': '--prompt="Reg> "'
>         \ }
>   call fzf#run(fzf#wrap(l:opts))
> endfunction
> 
> command! -bang Registers call s:registers('<bang>' ==# '!')
> ```

Hey, this looks amazing, but it desn't work for me: when I press enter, it just puts the last register. Also, what does `a:1` mean?

**Comment by tracyone** [comment]
> > @bedax Simple example (if you're still interested)
> > ```
> > function! s:get_registers() abort
> >   redir => l:regs
> >   silent registers
> >   redir END
> > 
> >   return split(l:regs, '\n')[1:]
> > endfunction
> > 
> > function! s:registers(...) abort
> >   let l:opts = {
> >         \ 'source': s:get_registers(),
> >         \ 'sink': {x -> feedkeys(matchstr(x, '\v^\S+\ze.*') . (a:1 ? 'P' : 'p'), 'x')},
> >         \ 'options': '--prompt="Reg> "'
> >         \ }
> >   call fzf#run(fzf#wrap(l:opts))
> > endfunction
> > 
> > command! -bang Registers call s:registers('<bang>' ==# '!')
> > ```
> 
> Hey, this looks amazing, but it desn't work for me: when I press enter, it just puts the last register. Also, what does `a:1` mean?

function need by fzf/reg.vim
https://github.com/tracyone/vinux/blob/120325705dd3d87dd92fbfb342121cf89e1af6fa/autoload/te/utils.vim#L690-L701

fzf setting for floating window:

https://github.com/tracyone/vinux/blob/master/rc/fzf.vim

reg.vim:

https://github.com/tracyone/vinux/blob/master/autoload/te/fzf/reg.vim

mapping:

https://github.com/tracyone/vinux/blob/120325705dd3d87dd92fbfb342121cf89e1af6fa/rc/fzf.vim#L36-L38


I make something similar you can try it

**Comment by jinleileiking** [comment]
https://github.com/svermeulen/vim-yoink/issues/32
