### ISSUE TITLE
Rebind keyes for one action only

### ISSUE THREAD

**Issue by promisedlandt** [junegunn/fzf.vim#648]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hello junegunn,

I have an FZF / vim setup that works great for me except for one issue:
I have Enter bound to open in a botright split, but for one specific action (`BTags`), I want it bound to edit.
My first try was to overwrite the sink for buffer_tags (`call fzf#vim#buffer_tags('', {'sink': 'e'}) `), but of course the the results are not processed by `s:btags_sink`, and it tries to open the wrong file (but at least in the same split).

Next I tried to overwrite "expect" in the options (`fzf#vim#buffer_tags('', {'options': '--expect enter'})`) but that did nothing. No big surprise, I was only guessing there.

Do you have any hints how I can rebind keys for specific actions only? I would like for it to respect `g:fzf_layout` and `g:fzf_colors`.

Also would be great if I could pass in `--reverse` there.

**Comment by 097115** [comment]
@promisedlandt, Any luck there? Found a workaround may be?

**Comment by mattmolo** [comment]
Here is something that worked for me:
```
let g:fzf_action = {'enter': 'vsplit'}

nnoremap <Leader>p :Files <CR>
function FZFBufferTags()
    let g:fzf_action = {'enter': 'edit'}
    :BTags
    let g:fzf_action = {'enter': 'vsplit'}
endfunction

nnoremap <Leader>o :call FZFBufferTags() <CR>
```

Basically instead of calling `:BTags`, we call a function which modifies the fzf action, calls btags, then resets it. Maybe you could save the fzf action into a variable and restore that way, but this is good enough for me.

**Comment by 097115** [comment]
That's clever :) Thanks.

**Comment by promisedlandt** [comment]
Makes me ashamed as a developer to not have thought of it myself :)

Changed the implementation to the following:

```
let l:fzf_old_action = g:fzf_action
let g:fzf_action = { "enter": "edit" }
:BTags
let g:fzf_action = l:fzf_old_action
```

So we don't have to copy `g:action` in our vimrcs.
