### ISSUE TITLE
Error when running :Files

### ISSUE THREAD

**Issue by engelju** [junegunn/fzf.vim#65]
After a fresh install as described in the README, I tried running ':Files'.

This was the output that I got in vim after running the command:

```
Error running xterm -T "[fzf]" -bg "\#2a2b2f" -fg "\#e1e0e5" -geometry 178x19+1062+768 -e bash -ic 'fzf -m --prompt '"'"'/U/jeng'"'"'/ --expect=ctrl-v,ctrl-x,ctrl-t > /var/
folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vd9k2an/0'&& osascript -e "tell application \"MacVim\" to activate" 
```

**Comment by junegunn** [comment]
So you're running mvim? fzf works best on terminal Vim and you may not like the experience on GVim. But anyway, it is probably because `xterm` is not installed on your system. Try `which xterm` to confirm that. Once it is confirmed, install XQuartz project (http://www.xquartz.org/), log out, log in, and try again.

**Comment by engelju** [comment]
Hey, I was indeed using fzf within mvim and did not have xterm installed.

Installing xterm via XQuartz as you pointed out indeed got fzf on terminal vim working, thanks!
However usage with mvim is broken. Maybe that should be stated somewhere. :-)

**Comment by junegunn** [comment]
> Installing xterm via XQuartz as you pointed out indeed got fzf on terminal vim working, thanks!

Hmm, no. Terminal vim does not require XQuartz. Only mvim does. And fzf works just fine on mvim with XQuartz for me.

**Comment by engelju** [comment]
Ah, right. I got that wrong. I thought it XQuartz was what got it working, but it turned out I didn't test terminal vim usage *before* installing XQuartz (only mvim).

And mvim usage certainly is usable, but imo it breaks the worklfow by opening an external xterm. However I have read why that is the case, so I'll just settle for terminal fzf usage.

Thanks for your very fast help though!

**Comment by junegunn** [comment]
No problem.
