### ISSUE TITLE
Index contents of cwd in background

### ISSUE THREAD

**Issue by navxio** [junegunn/fzf.vim#653]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Fzf.vim is fast, but there's a slight lag when I launch `:execute 'Locate' getcwd()`, which I'm guessing is because it starts indexing the files at that precise moment. It'd be cool if fzf were to index the contents of the cwd in the background..

**Comment by junegunn** [comment]
Any kind of caching or pre-fetching of the list is beyond the scope of the project. It's up to the users to build their own solution.
