### ISSUE TITLE
fzf with tmux

### ISSUE THREAD

**Issue by vimeitor** [junegunn/fzf.vim#654]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

Hi,

Is there a way to force fzf to run on tmux? I can't seem to make it work. `let g:fzf_prefer_tmux = 1` doesn't seem to do anything (together with `let g:fzf_layout = { 'up': '~40%' }`).

The biggest issue I have right now is, on one side, that placing it at the top means using the vim terminal, which overrides `ctrl-w`; furthermore, it seems like `let g:fzf_layout = { 'up': '~40%' }` only applies to `:FZF`, but not to commands like `:Buffers`; that is, if the amount of entries is smaller than the maximum height, `:FZF` stays at that height, while `:Buffers` is reduced to the smallest height that contains all the entries.

Thanks

**Comment by junegunn** [comment]
`let g:fzf_prefer_tmux = 1` works for me.

`:Buffers` is an exception here, it does not grow the height of the window more than needed. We can do it because we know the exact number of buffers before starting fzf. I see this as an improvement.
