### ISSUE TITLE
Ripgrep support

### ISSUE THREAD

**Issue by ksantr** [junegunn/fzf.vim#657]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [x] Windows
    - [x] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

For me ag is working very strangely, for really big project it's very slow. I prefer to use ctags, but I'm not sure that ctags in fzf regenerates new tags after updates. What about ripgrep? It's incredibly fast.

**Comment by junegunn** [comment]
See `:Rg` example in https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by devth** [comment]
How do you use `rg` for `:Files` though? I can't seem to find the right `rg` options to make it work.

Tried:

```
export FZF_DEFAULT_COMMAND='rg --line-number --color never --no-heading ""'
```

**Comment by thepenguinthatwants** [comment]
let $FZF_DEFAULT_COMMAND='rg --files'
Not sure if it really uses rg but I am using this.

**Comment by thepenguinthatwants** [comment]
> How do you use `rg` for `:Files` though? I can't seem to find the right `rg` options to make it work.
> 
> Tried:
> 
> ```
> export FZF_DEFAULT_COMMAND='rg --line-number --color never --no-heading ""'
> ```

let $FZF_DEFAULT_COMMAND='rg --files'
Not sure if it really uses rg but I am using this.
