### ISSUE TITLE
How to completely disable tmux usage

### ISSUE THREAD

**Issue by jackfranklin** [junegunn/fzf.vim#66]
Hey,

Firstly, thank you so much for all your hard work on fzf and other repos - my experience with Vim is hugely improved thanks to you!

I'm using fzf.vim and wondering if it's possible to entirely turn off fzf using tmux at all? I'd like all the commands to just run in the current window and not create a new tmux pane.

I know I can use `:Files!` and the like, but how can I do that for all the `<plug>` commands too?

I tried adding `export FZF_TMUX=0` to my `zshrc` but that hasn't had any affect on the fzf.vim plugin.

Thanks :)

**Comment by junegunn** [comment]
This looks hacky, but does what you want :)

```vim
let g:fzf_layout = {}
```

(FYI, the default layout for non-bang commands is `{'down': '~40%'}`)
