### ISSUE TITLE
Floating Windows Support From Neovim

### ISSUE THREAD

**Issue by Piping** [junegunn/fzf.vim#664]
Hi @junegunn 

Neovim patch from @bfredl has a working version of floating windows implementation now.

Is it possible to add a `split direction` like `float` and then open fzf inside floating windows.

Here is a [reference](https://github.com/neovim/neovim/pull/6619#issuecomment-401582250)

**Comment by junegunn** [comment]
You can pass an arbitrary command as `window` option.

```vim
function! Foo()
  tabnew
  " or whatever
endfunction

call fzf#run({'window': 'call Foo()'})
```

See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun for details.

**Comment by Piping** [comment]
@junegunn  Thanks a bunch

**Comment by Piping** [comment]
```vim

function! Foo()
     if exists('*nvim_open_float_win')
         let b = nvim_create_buf(v:false)
         call nvim_buf_set_option(b, "buftype", "nofile")
         call nvim_buf_set_lines(b,0,-1,v:true,["test"])
         let opts = {'x':100, 'y':5, 'anchor': 'NE'}
         let w =  nvim_open_float_win(b,v:false,60,20,opts)
         hi Floating guibg=#000000
         call setwinvar(w, '&winhl', 'Normal:Floating')
         call setwinvar(w, '&number', 0)
     endif
 endfunction
 call fzf#run({'window': 'call Foo()'})

```
I tried the following script, but fzf windows is not opened inside the floating windows, any idea?

**Comment by junegunn** [comment]
It opens in the "current" window where your cursor is positioned.

**Comment by bfredl** [comment]
@piping change v:false to v:true in the open float call.

**Comment by Piping** [comment]
@bfredl Thanks! 

This is what I got! 

![root local-vm - secure shell extension 0 8 43 7_3_2018 11_04_24 pm](https://user-images.githubusercontent.com/12042284/42259484-81914f24-7f15-11e8-85d6-10292fd97c9b.png)
@junegunn 
Awesome.

Although if I adjust the gui terminal size, the nvim crashed. 
`nvim: ../src/nvim/ui_compositor.c:226: compose_line: Assertion `until <= default_grid.Columns' failed.`

**Comment by kassio** [comment]
I got a nice result with the following:
```viml
let g:fzf_layout = { 'window': 'call FloatingFZF()' }
function! FloatingFZF()
  let buf = nvim_create_buf(v:false, v:true)
  call setbufvar(buf, '&signcolumn', 'no')

  let winheight = winheight(0)
  let winwidth = winwidth(0)

  let width = float2nr(winwidth-(winwidth*2/10))

  let opts = {
        \ 'relative': 'editor',
        \ 'row': &lines - 3,
        \ 'col': float2nr((winwidth-width)/2),
        \ 'width': width,
        \ 'height': &lines - 3
        \ }

  call nvim_open_win(buf, v:true, opts)
endfunction
```

<img width="840" alt="_o-height____var_folders_kl_p5p1p0gd0lx7zjcvmn59b8s00000gp_T_nvimPW0pDR_3__FZF" src="https://user-images.githubusercontent.com/120483/54935390-f88a8c80-4efe-11e9-9b9f-841d7c8c0560.png">


I was trying to achieve a different visual with the "input" in the top and the list of files in a top-down layout, but with the current fzf customization tools I didn't find a way to do it.

**Comment by kassio** [comment]
little change to keep the floating window centralized horizontally, regardless of any vertical splits.

```viml
function! FloatingFZF()
  let buf = nvim_create_buf(v:false, v:true)
  call setbufvar(buf, '&signcolumn', 'no')

  let width = float2nr(&columns - (&columns * 2 / 10))
  let height = &lines - 3
  let y = &lines - 3
  let x = float2nr((&columns - width) / 2)

  let opts = {
        \ 'relative': 'editor',
        \ 'row': y,
        \ 'col': x,
        \ 'width': width,
        \ 'height': height
        \ }

  call nvim_open_win(buf, v:true, opts)
endfunction
```

**Comment by junegunn** [comment]
>  a different visual with the "input" in the top and the list of files in a top-down layout

See `Layout` section in the man page.

**Comment by kassio** [comment]
Thanks @junegunn, I got the visual that I wanted:

<img width="679" alt="_folders_kl_p5p1p0gd0lx7zjcvmn59b8s00000gp_T_nvime4Ibru_3__FZF" src="https://user-images.githubusercontent.com/120483/54964931-1e3e8280-4f4d-11e9-91ed-86665d6bbae6.png">


```viml
let $FZF_DEFAULT_OPTS='--layout=reverse'
let g:fzf_layout = { 'window': 'call FloatingFZF()' }

function! FloatingFZF()
  let buf = nvim_create_buf(v:false, v:true)
  call setbufvar(buf, '&signcolumn', 'no')

  let height = &lines - 3
  let width = float2nr(&columns - (&columns * 2 / 10))
  let col = float2nr((&columns - width) / 2)

  let opts = {
        \ 'relative': 'editor',
        \ 'row': 1,
        \ 'col': col,
        \ 'width': width,
        \ 'height': height
        \ }

  call nvim_open_win(buf, v:true, opts)
endfunction
```

**Comment by taigacute** [comment]
@kassio  hi i use this function， how to hide line number in float window？`setlocal nonumber `? where it should be  write

**Comment by sassanh** [comment]
@kassio change
```
call nvim_open_win(buf, v:true, opts)
```
to
```
let win = nvim_open_win(buf, v:true, opts)
call setwinvar(win, '&number', 0)
```

**Comment by taigacute** [comment]
@sassanh  nothing change.

**Comment by sassanh** [comment]
It's working for me:
```
    let win = nvim_open_win(l:buf, v:true, l:opts)
    call timer_start(0, {-> execute(':call setwinvar(' . l:win . ', "&number", 1)')})
```

**Comment by taigacute** [comment]
@sassanh  hmm maybe i  got something wrong . you can see this gif. 
![go](https://user-images.githubusercontent.com/41671631/55067583-e7867a80-50ba-11e9-970f-5de0817e3bbb.gif)

**Comment by kassio** [comment]
You can use:
```viml
  au FileType fzf set nonu nornu
```

**Comment by taigacute** [comment]
@kassio  @sassanh   add this `  call setwinvar(win, '&relativenumber', 0)`,works well

**Comment by sassanh** [comment]
Put this at the end of your `init.vim` (or just after color scheme is set in your `init.vim`)
```
highlight NormalFloat cterm=reverse ctermfg=14 ctermbg=0 gui=NONE guifg=#93a1a1 guibg=#002931
```

**Comment by taigacute** [comment]
@sassanh   I don't know that this  bg is fzf or  floatwindow ? this float window's bg color same as my colorscheme .now i want set some color make it different colorscheme.
![1](https://user-images.githubusercontent.com/41671631/55070150-97121b80-50c0-11e9-9a2e-0b599cbbbad8.png)

**Comment by AhmedAbdulrahman** [comment]
Hi @kassio Thanks for the cool tips, do you know how can I get ride of that annoying Flashing background color when I open fzf ?
![Kapture 2019-10-13 at 7 12 46](https://user-images.githubusercontent.com/10485129/66711288-3c54be80-ed89-11e9-8f9f-333dc1303582.gif)

**Comment by dagadbm** [comment]
```
" floating fzf
if has('nvim') && exists('&winblend') && &termguicolors
  set winblend=20

  let $FZF_DEFAULT_OPTS .= ' --layout=reverse'

  function! FloatingFZF()
    let buf = nvim_create_buf(v:false, v:true)
    call setbufvar(buf, '&signcolumn', 'no')

    let height = float2nr(&lines - 5)
    let width = float2nr(&columns - (&columns * 2 / 10))
    let col = float2nr((&columns - width) / 2)
    let row = 1
    let opts = { 'relative': 'editor',
               \ 'row': row,
               \ 'col': col,
               \ 'width': width,
               \ 'height': height }

    let win = nvim_open_win(buf, v:true, opts)
    call setwinvar(win, '&winhighlight', 'NormalFloat:Normal')
  endfunction

  let g:fzf_layout = { 'window': 'call FloatingFZF()' }
endif
```

this is a mix from junegunn dotfiles and a comment from this thread. 
although i have no idea what this does exactly but it seems to work

**Comment by Karmenzind** [comment]
` call setwinvar(win, '&winhl', 'NormalFloat:TabLine')` will be better @dagadbm

**Comment by kassio** [comment]
@AhmedAbdulrahman is that still happening? For me, it's not happening. 🤷‍♂

**Comment by dagadbm** [comment]
> ` call setwinvar(win, '&winhl', 'NormalFloat:TabLine')` will be better @dagadbm

changed it!

why is it better?

**Comment by alfunx** [comment]
You usually don't need the `setlocal` stuff anymore if you set the `minimal` stile in `opts`, e.g.

```vim
" floating fzf
if has('nvim')
  let $FZF_DEFAULT_OPTS .= ' --layout=reverse'

  function! FloatingFZF()
    let buf = nvim_create_buf(v:false, v:true)

   " here be dragoons
    let height = &lines
    let width = float2nr(&columns - (&columns * 2 / 10))
    let col = float2nr((&columns - width) / 2)
    let col_offset = &columns / 10
    let opts = {
          \ 'relative': 'editor',
          \ 'row': 1,
          \ 'col': col + col_offset,
          \ 'width': width * 2 / 1,
          \ 'height': height / 2,
          \ 'style': 'minimal'
          \ }

    let win = nvim_open_win(buf, v:true, opts)
    call setwinvar(win, '&winhl', 'NormalFloat:TabLine')
  endfunction

  let g:fzf_layout = { 'window': 'call FloatingFZF()' }
endif
```

**Comment by iamme9182** [comment]
Is there any way to close this floating window automatically if I move out of it?  using the above if I hit ESC and move to another window the floating sticks around and I am not sure how to get back into it to close it.

**Comment by nstetter** [comment]
How would I change the background color for the FloatWindow in @alfunx example?

**Comment by marcov** [comment]
> How would I change the background color for the FloatWindow in @alfunx example?

@nstetter use `highlight TabLine ctermbg=<code>`

**Comment by alfunx** [comment]
@nstetter If you want to change the color for all floating windows and just use that color, set the `NormalFloat` group and remove the following line:

```vim
call setwinvar(win, '&winhl', 'NormalFloat:TabLine')
```

If you want to use a different colors for that specific floating window (while leaving the other ones as they are now), exchange `Tabline` with some other highlighting group, e.g.:

```vim
call setwinvar(win, '&winhl', 'NormalFloat:Error')
```

You can also define a highlighting group yourself and then use that, e.g.

```vim
highlight SpecificFloat ctermbg=... ctermfg=...
```

**Comment by nstetter** [comment]
Thanks for the explanation.
I found it more applicable to change the background color using the `minimal style` option and the `FZF_DEFAULT_OPTS` variable.

One thing I am still having issues with is the layout option. I set `--layout=reverse`
But it does not get respected, as can be seen in the screenshot:
![image](https://user-images.githubusercontent.com/21746115/71079947-7e84ec80-218c-11ea-9fc8-3ec17c25cac5.png)

My whole config is:
```
    " Using floating windows of Neovim to start fzf
    if has('nvim-0.4.0')
      let $FZF_DEFAULT_OPTS .= '--color=bg:#20242C --border --layout=reverse'
      function! FloatingFZF()
	let width = float2nr(&columns * 0.9)
	let height = float2nr(&lines * 0.6)
	let opts = { 'relative': 'editor',
		   \ 'row': (&lines - height) / 2,
		   \ 'col': (&columns - width) / 2,
		   \ 'width': width,
		   \ 'height': height,
		   \ 'style': 'minimal'
		   \}

	let win = nvim_open_win(nvim_create_buf(v:false, v:true), v:true, opts)
	call setwinvar(win, '&winhighlight', 'NormalFloat:TabLine')
      endfunction

      let g:fzf_layout = { 'window': 'call FloatingFZF()' }
    endif
```

When echoing `$FZF_DEFAULT_OPTS` inside vim I get:

```
--multi
--color=dark
--color=fg:-1,bg:-1,hl:#c678dd,fg+:#ffffff,bg+:#4b5263,hl+:#d858fe
--color=info:#98c379,prompt:#61afef,pointer:#be5046,marker:#e5c07b,spinner:#61afef,header:#61afef
--color=bg:#20242C --border --layout=reverse
```

Any idea why the reverse layout does not work like that?

**Comment by junegunn** [comment]
@nstetter :point_right: https://github.com/junegunn/fzf.vim/issues/916

**Comment by yutakatay** [comment]
https://github.com/yuki-ycino/fzf-preview.vim
