### ISSUE TITLE
:Files and :FZF show 0/0 files.

### ISSUE THREAD

**Issue by typhooncamel** [junegunn/fzf.vim#667]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

With a completely bare configuration (witih just fzf enabled), and having uninstalled and newly installed fzf and fzf.vim, the commands `:Files` and `:FZF` come up with 0/0 files, regardless of the directory I'm in. All other commands work fine (`:Lines`, `:History`, `:Tags`, etc.), and commands in the shell (zsh) such as `<ctrl>T` work fine too. Running `$FZF_DEFAULT_COMMAND` works fine too. I'm using neovim v0.3.1 in Ubuntu 18.04. I realise it's most likely a problem on my end, but have not been able to figure out what. Thanks!

**Comment by junegunn** [comment]
You might want to check if they work when `$FZF_DEFAULT_COMMAND` is unset.

**Comment by liranp** [comment]
Same issue here. Works fine when `$FZF_DEFAULT_COMMAND` is unset.

**Comment by typhooncamel** [comment]
Thanks for the quick response @junegunn. I have no idea what was going on, but restarting made things magically work again. Sorry for the premature opening of an issue.

**Comment by liranp** [comment]
@junegunn I'm still experiencing this issue. Not sure why.

This is the `$FZF_DEFAULT_COMMAND` that I'm using: ```export FZF_DEFAULT_COMMAND='rg --files --hidden --smartcase --glob "!{.git,node_modules,vendor}/*"'```. 

Any ideas?

**Comment by hendricius** [comment]
Just FYI for anyone else having the issue. I had the same issue on a new setup using homebrew.

```
echo $FZF_DEFAULT_COMMAND
=> fd --type f
```
Afterwards I just did `brew install fd` and it worked. Not sure why `fd` was not automatically installed as a dependency by homebrew.

**Comment by junegunn** [comment]
There is no dependency between fzf and fd.

**Comment by alextooter** [comment]
Yes, I meet the same problem. In my case, I set export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*" --glob "!node_modules/*"',but I delete rg,so FZF get nothing from FZF_DEFAULT_COMMAND.
After fix FZF_DEFAULT_COMMAND(by install rg),fzf work again.
