### ISSUE TITLE
How can I set to open a file in the current window, once I map return key to "tab split"?

### ISSUE THREAD

**Issue by YOnoda** [junegunn/fzf.vim#670]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

Hi, forgive me for asking a somewhat dumb question, but how can I swap the return key and Ctrl-n to open files?

I write the following as I usually want to open a file in a new tab, but then I want to set Ctrl-n to open a file in the current tab. 

```
let g:fzf_action = {
  \ 'return': 'tab split', 
  \ 'ctrl-j': 'split',
  \ 'ctrl-k': 'vsplit' }

```

But what is the value of opening the file in the current window (default)? And also, can I see the list of available values on the `g:fzf_action`?

**Comment by junegunn** [comment]
`e`, just like you would open a file with `:e filename` in Vim. These are just Vim commands.
