### ISSUE TITLE
BTags not returning any results with universal-ctags

### ISSUE THREAD

**Issue by kristijanhusak** [junegunn/fzf.vim#671]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

This was working properly, and for some reason it stopped.
I get an error `No tags found`.

When i do `:Tags` i get proper list of all tags, and i find the tag for the current buffer.

steps to reproduce:
1. create file `test.js`
2. Add this content to it:
```javascript
class MyClass {
  execute() {
    console.log('EXECUTE');
  }
}

module.exports = MyClass;
```
3. install universal-ctags and run `ctags -R .` in the folder where `test.js` file is.
4. open `test.js` in neovim (with minimal configuration provided), run `:BTags`, you get an error
5. Try running `:Tags`, you get 2 results, MyClass and Execute.

Neovim version:
NVIM v0.3.1-dev
Build type: RelWithDebInfo
Lua 5.1

OS: Linux mint cinnamon 19

**Comment by junegunn** [comment]
I use universal-ctags and it works for me. BTags command, unlike Tags, generates tags on-the-fly using the following command:

```sh
ctags -f - --sort=yes --excmd=number test.js
```

Does this command work on your system?

**Comment by kristijanhusak** [comment]
Yeah, looks fine:
![screenshot](https://i.imgur.com/45cJ02O.png)

**Comment by mg979** [comment]
I found out it's https://github.com/w0rp/ale.
If I disable it, BTags and my command work again.

**Comment by kristijanhusak** [comment]
Strange, i tried with minimal vimrc provided in issue template and it did not work.

**Comment by mg979** [comment]
And does it work now (with ALE disabled)? Here it works

**Comment by mg979** [comment]
Yes I know. So you're sure. Btw here it didn't work, and now it does. Maybe your problem is different than mine.

**Comment by kristijanhusak** [comment]
@mg979 you're right, it's because of Ale. Minimal vimrc didn't work for me because i'm using native packages with minpac package manager, and i didn't remove any of those before using minimal vimrc, and vim automatically loaded everything up.

@junegunn should I report this to Ale, or you think the issue is in fzf?

**Comment by mg979** [comment]
I reported it already at https://github.com/w0rp/ale/issues/1726, his suggested fix is [here](https://github.com/w0rp/ale/issues/1726#issuecomment-405081219) (working for me)

I have the impression he didn't take it too seriously, maybe he wants more people complaining :)

**Comment by kristijanhusak** [comment]
It works for me also. Thanks.
I'll wait and see his response why this happens.

**Comment by w0rp** [comment]
ALE didn't break anything, it stopped fixing a problem on your system. The problem is that you can't create temporary files because `tempname()` needs your `TMPDIR` environment variable to be set to something. So set it. ALE stopped tampering with it because it breaks `:!mktemp -p` in versions of CentOS where setting `TMPDIR` to anything changes the output of the command. If the environment variable isn't set, do this in your vimrc file.

```vim
if has('unix') && empty($TMPDIR)
    let $TMPDIR = '/tmp'
endif
```

**Comment by w0rp** [comment]
ALE does this to handle TMPDIR not being set now.

```vim
function! ale#util#Tempname() abort
    let l:clear_tempdir = 0

    if has('unix') && empty($TMPDIR)
        let l:clear_tempdir = 1
        let $TMPDIR = '/tmp'
    endif

    try
        let l:name = tempname() " no-custom-checks
    finally
        if l:clear_tempdir
            let $TMPDIR = ''
        endif
    endtry

    return l:name
endfunction
```

I recommend doing something similar where TMPDIR needs to be set to something.

**Comment by mg979** [comment]
Not for the sake of complaining, but the point (imho) is that even if TMPDIR isn't set (mine wasn't), commands that use it work without ALE, and don't work with it. This happened with ctags, but maybe it can happen with whatever shell command that uses a temp dir (and break other commands as well). If Ale makes some changes that require that variable to be set to something, it should set it by itself to prevent this kind of issues. Imho.

**Comment by mg979** [comment]
Or, if it is need for somebody's trouble, maybe tied to an option that they have to activate themselves.

**Comment by w0rp** [comment]
You don't understand. I have removed environment variable tampering from ALE. Your problem is that on your system, you need to set it to something. You need to set an environment variable for some other plugins to work. A previous version of ALE was fixing this problem for you by setting `TMPDIR` so it defaults to `'/tmp'`, and now it no longer does that.

**Comment by mg979** [comment]
Yes I don't understand how is it that plugins worked without that variable *and* without ale, if I *need* that variable set to something. In the cli ctags doesn't complaing because that variable isn't set, either.
Btw sorry about this, if it's fine for you it's fine for me.

**Comment by w0rp** [comment]
Before: ALE set `$TMPDIR` for you, and this made your other plugins work.
After: ALE no longer sets that variable, so your other plugins stopped working.
What to do: Put those lines in `vimrc`, forget about it, be happy.

That's it.

**Comment by mg979** [comment]
Now, but looking at that function, here you set the variable

```vim
    if has('unix') && empty($TMPDIR)
        let l:clear_tempdir = 1
        let $TMPDIR = '/tmp'
    endif
```

and here you clear it 100% of the times, why?

```vim
    finally
        if l:clear_tempdir
            let $TMPDIR = ''
        endif
    endtry
```

**Comment by kristijanhusak** [comment]
@w0rp this issue is not happening when ale is **not installed**, so this statement is not correct
> After: ALE no longer sets that variable, so your other plugins stopped working.

**Comment by mg979** [comment]
By the way (and with this I'm finished), if you replace

```vim
        if l:clear_tempdir
            let $TMPDIR = ''
        endif
```

with

```vim
        if l:clear_tempdir
            unlet $TMPDIR
        endif
```

it works again, without adding anything to the vimrc.

Maybe for vim it's different if the variable doesn't exist at all, or if it's set to an empty string.

**Comment by w0rp** [comment]
Your example code doesn't work because you can't use `unlet` with environment variables. If there's a genuine issue which ALE causes, open an issue with steps for repeating the bug. What you're saying about the environment variable is nonsense. There could be some other issue I'm not aware of.

**Comment by mg979** [comment]
I wouldn't have written it if I hadn't verified it. All I know is that it works. From vim help:

```
:unl[et] ${env-name} ...                        :unlet-environment :unlet-$                                                  280 function! ale#util#Tempname() abort                                   
                        Remove environment variable {env-name}.                                                              281     let l:clear_tempdir = 0                                           
                        Can mix {name} and ${env-name} in one :unlet command.                                                282                                                                       
                        No error message is given for a non-existing                                                         283     if has('unix') && empty($TMPDIR)                                  
                        variable, also without !.                                                                            284         let l:clear_tempdir = 1                                       
                        If the system does not support deleting an environment                                               285         let $TMPDIR = '/tmp'                                          
                        variable, it is made emtpy.
```

**Comment by w0rp** [comment]
Yes, in _newer versions of Vim that support it_. Not in the versions of Vim which ALE supports.

**Comment by w0rp** [comment]
I'll add `:slient! unlet! $TMPDIR` too, but it shouldn't be an issue.

**Comment by mg979** [comment]
Ok... then I don't know. But the problem seems to be exactly that (setting $TMPDIR to an empty string).

**Comment by mg979** [comment]
And about environmental variables, just for the record:

http://vim.1045645.n5.nabble.com/Clear-an-environment-variable-tp1190117p1190125.html

**Comment by kristijanhusak** [comment]
@w0rp i see that you added that `:silent! unlet! $TMPDIR`, but unfortunately that doesn't work with neovim.
@mg979 if this works for you in vim 8.*, i guess we can close this, because i don't think it can be fixed more than this.

**Comment by w0rp** [comment]
I pushed a commit now to only temporarily replace `$TMPDIR` if it's defined to be empty. `exists('$TMPDIR') && empty($TMPDIR)`. This should only be true in Vim. That way it can't change from being undefined to being defined to be empty.

It is pretty ridiculous that any library should fail because `TMPDIR` is defined as an empty string, but I'm not surprised.

**Comment by kristijanhusak** [comment]
@w0rp Thanks, that fixes the issue.

**Comment by mg979** [comment]
> I pushed a commit now to only temporarily replace $TMPDIR if it's defined to be empty. exists('$TMPDIR') && empty($TMPDIR). This should only be true in Vim. That way it can't change from being undefined to being defined to be empty.

I wonder if it won't break again what you were trying to fix with this function, but it fixes the ctags issues for me too.

**Comment by w0rp** [comment]
Cool, sorry about all the confusion.

**Comment by misraelson** [comment]
I was running into this same issue with Vim on MacOS (intel). Fixed by brew installing universal ctags:
`brew install --HEAD universal-ctags/universal-ctags/universal-ctags`
