### ISSUE TITLE
Respect vim colorscheme inside the preview window?

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf.vim#673]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Is it possible that the preview window can respect vim colorsceheme or not?

**Comment by junegunn** [comment]
Not possible. You probably should use the matching terminal color scheme.
