### ISSUE TITLE
:Commits integration with fugitive no longer works

### ISSUE THREAD

**Issue by griffingarland** [junegunn/fzf.vim#674]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

(Probaby cross-platform, I only run Linux though)

This was after an update this week in fugitive. I filed an bug with fugitive:

https://github.com/tpope/vim-fugitive/issues/1060

Tim Pope said 
> Oh, I just noticed your screenshot has a 7 character SHA rather the full 40. That's never been officially supported. What are you doing to get a buffer name like that? I suppose fzf might be generating those filenames?"

It seems that fzf.vim is relying on unsupported behaviour.

**Comment by tpope** [comment]
This has drawn my attention to the need for an API to generate buffer names. I just pushed an implementation of `FugitiveGenerate(revision, git_dir)` which I recommend using when available going forward to avoid further issues of this nature.

**Comment by junegunn** [comment]
@tpope Thanks, that really helps!

**Comment by griffingarland** [comment]
Confirming that it's working for me now. Thanks guys.

**Comment by tpope** [comment]
FYI, `FugitiveGenerate()` without a second argument defaults to the Git repository for the current file, while fzf.vim's implementation appears to use the current working directory, so this will produce incorrect results if the two don't line up.
