### ISSUE TITLE
Lines and Blines Commands don't work

### ISSUE THREAD

**Issue by blayz3r** [junegunn/fzf.vim#679]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [X] Windows 10
    - [ ] Etc.
- Vim
    - [X] Gvim
    - [ ] Neovim

 Lines and Blines Commands don't work and cause vim to crash

**Comment by janlazo** [comment]
Did you check https://github.com/junegunn/fzf/wiki/Windows#fzf-outputs-character-set-not-supported-when-term-environment-variable-is-set? Post output of `gvim --version` and contents of minimal vimrc to reproduce the problem.

**Comment by junegunn** [comment]
You may be using an older version of fzf binary. Install the latest version which supports `--layout=reverse-list`.

But by the way, are you sure that Vim "crashes"?

**Comment by blayz3r** [comment]
Sorry I mean't vim the fzf-vim crashes . I updated the binary and it worked. Thanks for that. I'll update the binary first next time before I open an issue.
