### ISSUE TITLE
Disable key mappings

### ISSUE THREAD

**Issue by eldamir** [junegunn/fzf.vim#68]
The keymappings that this plugin adds conflict with my setup. I use ctrl + hjkl to move between windows, but now `<C-K>` has been bound to `:History`. How can I change this? My bindings are defined at the bottom of my .vimrc, but the fzf.vim mappings overwrite mine

**Comment by netei** [comment]
They are no mappings shipped with this repository, you probably have this setup at some place in your .vimrc or by another plugin.

Try doing `:map <C-K>` to see who is responsible for this.

**Comment by eldamir** [comment]
You are right, ofcourse. It was my own making. Sorry for disturbing
