### ISSUE TITLE
Unknown function: FugitiveGenerate

### ISSUE THREAD

**Issue by liushapku** [junegunn/fzf.vim#680]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

When I use BCommits to open a commit, I get the error `Unknown function: FugitiveGenerate`
Search the code base I found only one occurrence of this word [here](https://github.com/junegunn/fzf.vim/search?q=fugitivegenerate&unscoped_q=fugitivegenerate).
It is not defined in [`fugitive`](https://github.com/tpope/vim-fugitive/search?q=fugitvegenerate&unscoped_q=fugitvegenerate) either.

What should I do to fix this.

**Comment by junegunn** [comment]
You have to update fugitive.
