### ISSUE TITLE
:Ag does not search through $PWD

### ISSUE THREAD

**Issue by Industrial** [junegunn/fzf.vim#681]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi. When I do a `:Ag` then the results returned are all from `backup/*`.

With `:map <c-p> :files $PWD<cr>` I can get it to search only through the current project directory.
With `:map <c-f> :Ag $PWD<cr>` no results are returned.

How do I pass a directory argument to ag?

**Comment by lionize** [comment]
Having the same issue here. As an example, if I use `:Files` from `~/.config/nvim`, this is what fzf shows:

![image](https://user-images.githubusercontent.com/1954752/44630806-6e128800-a931-11e8-8933-0546825cc7bd.png)

**Comment by hmngwy** [comment]
@lionize when you `cat /private/var/folders/98/n49s3j_d6ssf695dd4v8fmtn52mj74/T/nvimMoxGad/3` you'd see the `ag` command. 

Still not sure what's going on here as I'm not sure how fzf runs these commands.

**Comment by Industrial** [comment]
This seems to have been fixed, at least it works for me.
