### ISSUE TITLE
Howto change color of left panel?

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf.vim#682]
- Category
    - [x] Question
- OS
    - [x] Linux
- Vim
    - [x] Vim

I tried to modify all options in `fzf_colors`, none of them works. Here I want to change the color of left panel as picture below:
![pic](https://image.ibb.co/gJnKyU/fzf.png)

**Comment by junegunn** [comment]
`bg+`, for example,
```sh
let g:fzf_colors = { 'bg+': ['bg', 'ErrorMsg'] }
```

This may not work if your color scheme does not set background color for `ErrorMsg`, but you get the idea.

**Comment by tuyenpm9** [comment]
@junegunn : But why `README.md` mentioned `  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],`?

**Comment by junegunn** [comment]
That is just an example. The one above is another. You should find the configuration that you like the most.

**Comment by tuyenpm9** [comment]
Oh, I see, super cool, so `bg+` is for the choosing line in fzf.

So I assum `\ 'bg+': ['bg', 'CursorLine', 'CursorColumn'],`, first try `CursorLine`, if not set fallback to `CursorColumn`, Is that correct? @junegunn

**Comment by junegunn** [comment]
> Is that correct?

Yes.

> Another non related-question, the color of fzf that display when using fzf command in a shell, how can I tweak it?

**Please read through `man fzf` before asking questions here.**

`g:fzf_colors` is only useful if you frequently switch color schemes inside Vim and you want the colors of fzf to adapt. If that's not the case, you're better off setting `--color` option in your `$FZF_DEFAULT_OPTS`. See https://github.com/junegunn/fzf/wiki/Color-schemes

fzf also supports 24-bit colors, so this is also possible:

```sh
fzf --color='bg+:#1c1c1c,bg:#080808,border:#80a0ff,spinner:#42cf89,hl:#ae81ff,fg:#b2b2b2,header:#80a0ff,info:#42cf89,pointer:#f74782,marker:#f09479,fg+:#c6c6c6,prompt:#87afff,hl+:#ae81ff'
```

**Comment by tuyenpm9** [comment]
@junegunn : Thanks.

I've just checked against this pattern:
```
export FZF_DEFAULT_OPTS='
  --color fg:15,bg:15,hl:15,fg+:15,bg+:15,hl+:15
  --color info:15,prompt:15,spinner:15,pointer:15,marker:15
'
```
Somehow `substring` still gets highlighted despite of above settings that dumped all colors to `white`. And I really need to change `substring` color because in my terminal it's in high undistinguishable contrast  color.
