### ISSUE TITLE
Howto change color of matched substring?

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf.vim#685]
- Category
    - [x] Question
- OS
    - [x] Linux
- Vim
    - [x] Vim

![fzf_color_issue](https://i.imgur.com/sAz6AyI.png)

I seem can't find a way to change color of this matched string of fzf under vim. Is it hardcoded? If yes, can you give option to change it?

**Comment by morphheus** [comment]
The hl+ color should be affecting the substring highlight. It works for BLines,  Files, Buffers, etc, but not for commands that rely on `fzf#vim#grep`.

**Comment by morphheus** [comment]
I think I found it:

https://github.com/junegunn/fzf.vim/blob/822441681302fd2ed1736d618709b8138929101b/autoload/fzf/vim.vim#L690-L696

Debug code got left in place?

**Comment by morphheus** [comment]
After searching a bit, you can find a fix in [this issue](https://github.com/junegunn/fzf.vim/pull/454#issuecomment-416801264)

**Comment by tuyenpm9** [comment]
@morphheus : Silly question: How would I inject `--color` into this snipet?

```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

```

**Comment by morphheus** [comment]
Here is an example of my vimrc, where I call fzf grep directly:

```
command! -bang FLines call fzf#vim#grep(
    \'grep -vnITr --color=always --exclude-dir=".git" --exclude-dir=".svn" --exclude-dir="env" --exclude=*\.pyc "^$"',
   \ 0, 
   \ {'options': '--reverse --prompt "FLines> " --color hl:45,hl+:51 '})
```
Note: this command loads all the non-empty lines under the CWD into FZF. My codebase is small enough that FZF doesn't explode when I do that :)

**Comment by tuyenpm9** [comment]
Somehow I patched colorscheme a lot and fzf fallback to very good-looking color or maybe it's fixed in the latest update but noted with thanks.
