### ISSUE TITLE
Set location list when using BTags

### ISSUE THREAD

**Issue by SageEx** [junegunn/fzf.vim#69]
Hi, 
I was using BTags and tried Ctrl-o/Ctrl-i but, it turns out it did not update the location list on jumping to the tag.
Could you suggest a way to update the location list when jumping around using BTags ?
Btw, thanks for this awesome plugin.

**Comment by junegunn** [comment]
Thanks, I updated the commands to update jumplist.

**Comment by SageEx** [comment]
Thanks a lot !!
