### ISSUE TITLE
:Ag does not obey the g:fzf_colors (also, where if fzf_colors actually used?)

### ISSUE THREAD

**Issue by MarkGreeny** [junegunn/fzf.vim#691]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

If we have

```vim
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'EndOfBuffer'] }
```

Than when we call `:Files`, the coloring is correct, hl+ is the color of statement, hl is the color of comment. But when we call `:Ag`, than the highlight colors are the same as in the terminal (if we call FZF from the terminal).

Why is this so, and how can we make a custom function, that will obey the fzf_colors variable? For example the relevant code from [this](https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim) example

```vim
command! -nargs=* Ag call fzf#run({
\ 'source':  printf('ag --nogroup --column --color "%s"',
\                   escape(empty(<q-args>) ? '^(?=.)' : <q-args>, '"\')),
\ 'sink*':    function('<sid>ag_handler'),
\ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
\            '--multi --bind=ctrl-a:select-all,ctrl-d:deselect-all '.
\            '--color hl:68,hl+:110',
\ 'down':    '50%'
\ })
```

How can we call it, so that the coloring will obey the `g:fzf_colors` variable.

### Edit

Also, is there a way to get the parameters into which the `g:fzf_colors` is turned, when calling FZF, so that i could use those same parameters in my config file in the terminal. I hope my wording makes sense.

**Comment by junegunn** [comment]
See the previous discussions in #454 and #581. The colors are hard-coded and I have no plan to change it but you can override it if you want. Also note that we now use the base blue colors, 4 and 12, instead of 68 and 110.

> is there a way to get the parameters into which the g:fzf_colors is turned

`g:fzf_colors` is handled by [`fzf#wrap` function](https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap), so you can simply look at the return value of it.

```vim
:echo fzf#wrap()

:echo fzf#wrap({'options': '--color=hl:#FF9900'})

:call fzf#run(fzf#wrap({'options': '--color=hl+:#FF9900'}))
```

**Comment by 097115** [comment]
`:Maps` still seems not to obey `g:fzf_colors` :)
