### ISSUE TITLE
BLines throws error E687 (Less targets than List items)

### ISSUE THREAD

**Issue by gbrlsnchs** [junegunn/fzf.vim#699]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When using `:BLines`, after selecting a matched line in fzf.vim window, Vim throws the following error:
```
Error detected while processing function fzf#vim#buffer_lines[3]..<SNR>145_fzf[18]..fzf#run[69]..<SNR>25_callback:
line   21:
Vim(let):E687: Less targets than List items
``` 
I tried with the minimal configuration and it still throws that error. I'm not sure exactly about under what conditions it throws such error, but it seems that it doesn't error when finding text on very small files.

**Comment by jiajunhuang** [comment]
👍 +1: screen shot: 
![image](https://user-images.githubusercontent.com/5924269/45876675-dd16bb80-bdcd-11e8-95f2-f56b084ba8a1.png)

**Comment by peter50216** [comment]
The problem is on the line `let [ln, ltxt] = split(line, "\t")` in autoload/fzf/vim.vim.
This breaks when the selected line contains `"\t"`. Also vim seems to match consecutive spaces as `"\t"` too.
