### ISSUE TITLE
AckFromSearch equivalent

### ISSUE THREAD

**Issue by asymmetric** [junegunn/fzf.vim#705]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

`ack.vim` has a useful feature called [`AckFromSearch`](https://github.com/mileszs/ack.vim/blob/36e40f9ec91bdbf6f1adf408522a73a6925c3042/autoload/ack.vim#L68-L73), that runs `ack` on the last searched string.

This way, one can search through a file with `*`/`#`, and keep on searching through the rest of the filesystem with just one command.

How would one replicate this feature with `fzf.vim`?

Thanks! :heart:

**Comment by taneliang** [comment]
Here's a slight adaptation of [`AckFromSearch`](https://github.com/mileszs/ack.vim/blob/36e40f9ec91bdbf6f1adf408522a73a6925c3042/autoload/ack.vim#L68-73) that you linked. It's not yet battle tested as I've only just added it to my Neovim config, but it seems to work fine.

```vim
function FzfAgFromSearch()
    let search = getreg('/')
    " translate vim regular expression to perl regular expression.
    let search = substitute(search, '\(\\<\|\\>\)', '\\b', 'g')
    call fzf#vim#ag(search)
endfunction

" Previously nnoremap <Leader>acs :AckFromSearch<CR>
nnoremap <Leader>acs :call FzfAgFromSearch()<CR>
```

**Comment by asymmetric** [comment]
Wanna make a PR? :)

**Comment by junegunn** [comment]
You can add it to your configuration file. PR is not needed.

**Comment by jfelchner** [comment]
@junegunn there's a ton of stuff you can add to your configuration files.  I could literally put this entire plugin in my configuration files.

Adding it to the plugin means that there's one version of the code and if there are bugs, it can be fixed for everyone at the same time.  This is a use case that most people need and want and therefore is a reasonable addition to the plugin.

**Comment by asymmetric** [comment]
I've implemented this for ripgrep so:

```vim
function FzfAgFromSearch()
    let search = getreg('/')
    " translate vim regular expression to perl regular expression.
    let search = substitute(search, '\(\\<\|\\>\)', '\\b', 'g')
    " TODO ideally i would call Rg, which calls fzf#vim#grep
    " :Rg(search)
    call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(search), 1)
endfunction
```

It would be better not to repeat the invocation to `fzf#vim#grep`, and instead call `:Rg`, so that there's no risk of drift between the two ways of calling ripgrep, but I couldn't find a way to do that.
