### ISSUE TITLE
Rg does not respect color values

### ISSUE THREAD

**Issue by cmcginty** [junegunn/fzf.vim#706]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ x] Vim
    - [ ] Neovim

For some reason `:Rg` does not respect the color values that `:Files` uses. Is there a workaround.
Notice that the highlight color is different in the two versions.

![image](https://user-images.githubusercontent.com/277249/46193489-36da2280-c2b3-11e8-8b45-a9a9608373ea.png)
![image](https://user-images.githubusercontent.com/277249/46193524-4fe2d380-c2b3-11e8-9623-16f5722deaa0.png)

**Comment by drozdowsky** [comment]
$ man rg
rg --colors ...
Basically change the command that gets executed

**Comment by junegunn** [comment]
@drozdowsky Thanks.

@cmcginty You might want to check out https://github.com/BurntSushi/ripgrep/pull/772
