### ISSUE TITLE
Redraw / update issue inside neovim (inside tmux)

### ISSUE THREAD

**Issue by benbarbour** [junegunn/fzf.vim#71]
When I run `:Files .` from neovim v0.1.1 running inside tmux 2.2 the split pane is not opened right away; it can take ~5 seconds for anything to show up. If I press a key it updates immediately. Similarly sometimes when I press up or down or start searching the pane doesn't redraw. However, if I press return to open a file at any time it opens what I would expect. Let me explain with an example.

Given the these files in the directory:

* myfile.txt
* myotherfile.txt
* chicken.txt

If I run `:Files .` from neovim inside of it and type 'm' I will get no visual feedback. If I press enter at this point then myfile.txt is opened. If I type 'myo' the pane will update to show myfile.txt and myotherfile.txt (as if I hadn't typed the 'o'), but if I press enter myotherfile.txt will open. In short, the rendering always appears to be a character behind.

My TERM is `screen-256color`. This does not happen when I'm not running inside tmux, but it also doesn't happen with any other neovim split I've found (terminal or otherwise) so I really don't know where the problem lies. :confused:

**Comment by junegunn** [comment]
Can you post some screenshots?

> This does not happen when I'm not running inside tmux

This is strange. tmux should not affect the behavior since in neovim the commands will start in neovim terminal buffer instead of in tmux split pane.

https://github.com/junegunn/fzf/blob/d635b3fd/plugin/fzf.vim#L139-L144

**Comment by benbarbour** [comment]
This is strange; I installed my setup identically on another computer (same tmux, neovim, and terminal) and the problem didn't exist. So, I reinstalled neovim on my first machine and the problem went away.

Thanks for your response though, and sorry for the bother. I'll close this.
