### ISSUE TITLE
Rg matches patterns in file names as well as in file content

### ISSUE THREAD

**Issue by halas** [junegunn/fzf.vim#714]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When I use `:Rg` command I'd expect it to look for given string only in files content (as it behaves when I invoke it outside vim), but for some reason it matches file names as well, which is confusing and obfuscates results. 
Can I use some flag/configuration to make Rg search only through file content? 

Output of `Rg` in `:Commands`: 
`call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellscape(<q-args>), 1, <bang>0)`

Thanks for this astonishing piece of software, btw!

**Comment by wookayin** [comment]
Use `:Rg <query>`. `<query>` won't match file name.

**Comment by junegunn** [comment]
The same approach as the one shown in #346, redefining the command with `--delimiter` and `--nth`:

```vim
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
```

You should always try to provide an initial query to rg or ag and use fzf only as the secondary filter as it's much more efficient that way especially when your project is large.

```vim
" Rg current word
nnoremap <silent> <Leader>rg :Rg <C-R><C-W><CR>
```

FYI, I frequently match against file names in the result of Ag/Rg to only select matches in a certain file type. e.g. `.h:`, `.cc:`, etc.

**Comment by simonLeary42** [comment]
Using `:RG` instead of `:Rg` also fixes this for me
