### ISSUE TITLE
Please add support for bat or add options to customize highlight command in preview.rb

### ISSUE THREAD

**Issue by mars90226** [junegunn/fzf.vim#719]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

[bat](https://github.com/sharkdp/bat) is a great syntax highlighting tool. It would be great to add support in preview.rb like `COMMAND = %[(bat --color=always --decorations=never {} || highlight -O ansi -l {} || coderay {} || rougify {} || cat {}) 2> /dev/null]
` or add a new `fzf.vim` option to customize highlight command in `preview.rb`. Thank You!

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf.vim/pull/707#issuecomment-432494703

**Comment by mars90226** [comment]
Oh, sorry for not searching for the related issues. I'll read those issues. Thanks!

**Comment by mars90226** [comment]
Thanks for supporting bat!
