### ISSUE TITLE
:GFiles fallback (question)

### ISSUE THREAD

**Issue by mitchellwrosen** [junegunn/fzf.vim#721]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hello folks, I currently have two bindings for opening git files, or all files:

```
nn <Space>o :GFiles<CR>
nn <Space>O :Files<CR>
```

However, I'd much prefer to have only one hotkey, which tries `:GFiles`, but falls back on `:Files` if we're not in a git repo. I'd appreciate any help in figuring out how to do this with vimscript :) Cheers.

**Comment by junegunn** [comment]
This should work.

```vim
nnoremap <expr> <space>o (len(system('git rev-parse')) ? ':Files' : ':GFiles')."\<cr>"
```

**Comment by mitchellwrosen** [comment]
Thank you sir

**Comment by paulodiovani** [comment]
My choice:

```vim
" list files/git files
command! Ctrlp execute (exists("*fugitive#head") && len(fugitive#head())) ? 'GFiles' : 'Files'
map <C-p> :Ctrlp<CR>

**Comment by hnspn** [comment]
> My choice:
> 
> ```viml
> " list files/git files
> command! Ctrlp execute (exists("*fugitive#head") && len(fugitive#head())) ? 'GFiles' : 'Files'
> map <C-p> :Ctrlp<CR>
> ```

This also works
```vim
command! Ctrlp execute (len(system('git rev-parse'))) ? ':Files' : ':GFiles'
nnoremap <C-p> :Ctrlp<CR>
```

**Comment by chris542** [comment]
For me 
```
command! Ctrlp execute (len(system('git rev-parse'))) ? ':Files' : ':GFiles'
nnoremap <C-p> :Ctrlp<CR>
```
does not work.

```
command! Ctrlp execute (exists("*fugitive#head") && len(fugitive#head())) ? 'GFiles' : 'Files'
map <C-p> :Ctrlp<CR>
```
works perfectly though.
