### ISSUE TITLE
Rename fzf.vim to something else to play nicely with dein.

### ISSUE THREAD

**Issue by KareemErgawy** [junegunn/fzf.vim#722]
It might be a good idea to rename `plugin/fzf.vim` to something else; say `plugin/fzf_vim.vim`.

This is so that `junegunn/fzf` and `junegunn/fzf.vim` can be simultaneously installed using `dein.vim`. It's not a problem with fzf itself but with how dein caches plugin source files. The way this happens is that dein stores ALL *.vim files from ALL installed plugins in the same directory, under: `~/.cache/dein/.cache/init.vim/.dein/plugin`. This results in `junegunn/fzf/plugin/fzf.vim` to be replaced by `junegunn/fzf.vim/plugin/fzf.vim`. You get the idea :).

If you like the idea I can create a PR with my changes here: https://github.com/KareemErgawy/fzf.vim/blob/master/plugin/fzf_vim.vim

**Comment by junegunn** [comment]
Thanks for the heads up but I don't want to change the structure of my projects because of a plugin manager I don't use. Follow the instruction in the issue below.

https://github.com/Shougo/dein.vim/issues/74

**Comment by leycec** [comment]
> ...I don't want to change the structure of my projects because of a plugin manager I don't use.

`¯\_(ツ)_/¯`

While you specifically may not use `dein`, a sizeable portion of your userbase does. When the needs of a userbase conflict with the wants of a developer, the former should ideally take precedence – especially for GitHub-hosted volunteerism, where the omnipresent threat of a community fork is but a button press away.

None of this should come as any surprise, @junegunn. `fzf` is the most subjectively hardcore fuzzy finder; `dein` is the most subjectively hardcore Vim plugin manager. The two communities have a natural overlap and tend to attract a similar breed of command-line devotee.

If you fail to resolve this issue, the community ultimately will. Although [@januaryjp's workaround](https://github.com/Shougo/dein.vim/issues/74#issuecomment-237198717) *does* superficially suffice, it does so only be instructing `dein` to *not* cache `fzf` – which defeats the entire purpose of using `dein` in the first place. @KareemErgawy graciously documented and volunteered to resolve the *real* underlying issue (i.e., a trivial namespace clash) with a presumably trivial pull request.

Consider reopening this unresolved issue.

**Comment by melissanoelle** [comment]
Forks aren't very friendly though, imo. +1 for wishing this would be solved without workarounds.

**Comment by junegunn** [comment]
Please ask the author of dein to fix it, in my opinion this is clearly an issue of the plugin manager. No other plugin managers have the problem.

**Comment by NightMachinary** [comment]
@junegunn Please at least add a warning in the readme. It wastes a lot of time trying to understand why a simple plugin install isn't working. I know `dein` is in the wrong here, but this isn't about who's to blame, but simple usability.

BTW, I didn't even know I was using `dein`, as I was using `Spacevim`'s infrastructure.
