### ISSUE TITLE
Is it possible to show preview for all commands?

### ISSUE THREAD

**Issue by ondrejsevcik** [junegunn/fzf.vim#724]
- Category
    - [x ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x ] Vim
    - [ ] Neovim

Hi, is it possible to enable for each command that when I type `?` it will toggle preview window? I've seen an example that's for `Ag`, but I would love to have this feature for all fzf commands.

Also, it would be great to have this by default for all bang commands. Is that possible? 

Thanks for help

**Comment by burgessa23** [comment]
having this for `Buffers` would be fantastic.. i currently have: 

```sh
command! -bang -nargs=? -complete=dir Buffs
  \ call fzf#vim#buffers(<q-args>, fzf#vim#with_preview(), <bang>0)
``` but it fails to render previews if any buffers have `~` in the path as it doesn't expand

**Comment by ondrejsevcik** [comment]
Great job 👏  thank you for the effort
