### ISSUE TITLE
:Ag searching only current file not working

### ISSUE THREAD

**Issue by jssee** [junegunn/fzf.vim#725]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

---
my init.vim:
```vim
nnoremap <Leader>sa :Ag<CR>
nnoremap <Leader>ss :Ag!<CR>

command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```

i used the method you described in #346  but im experiencing some strange behavior.

i want to have 2 options:

1. use the default :Ag behavior of searching all file names and content.
2. use Ag to only search the current file contents.

this does not work as expected, it doesnt matter which command i use. please let me know if theres something i need to change

**Comment by ZigaSajovic** [comment]
This is from my vimrc, uses silver searcher on the current file only. Hope it helps.

```vim
function! s:ag_to_qf(line)
  let parts = split(a:line, ':')
  return {'filename': parts[0], 'lnum': parts[1], 'col': parts[2],
        \ 'text': join(parts[3:], ':')}
endfunction

function! s:ag_handler(lines)
  if len(a:lines) < 2 | return | endif

  let cmd = get({'ctrl-x': 'split',
               \ 'ctrl-v': 'vertical split',
               \ 'ctrl-t': 'tabe'}, a:lines[0], 'e')
  let list = map(a:lines[1:], 's:ag_to_qf(v:val)')

  let first = list[0]
  execute cmd escape(first.filename, ' %#\')
  execute first.lnum
  execute 'normal!' first.col.'|zz'

  if len(list) > 1
    call setqflist(list)
    copen
    wincmd p
  endif
endfunction

command! -nargs=* Agc call fzf#run({
\ 'source':  printf('ag --nogroup --column --color -G %s "%s"',
\                   expand('%'),
\                   escape(empty(<q-args>) ? '^(?=.)' : <q-args>, '"\')),
\ 'sink*':    function('<sid>ag_handler'),
\ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
\            '--multi --bind=alt-a:select-all,alt-d:deselect-all '.
\             '--prompt "Agc> "',
\ 'down':    '~30%'
\ })
```

**Comment by juanMarinero** [comment]
Hi @jssee , since you closed this, can you explain how you solved it?
The @ZigaSajovic solution outputs [me] all recursive files (directory depth not 0), but you asked for  

> use Ag to only search the current file contents.

Thanks in advance!

**Comment by ZigaSajovic** [comment]
@juanMarinero I forgot to think about the case, where the file of the same name could be found deeper in the hierarchy. You should add the depth parameter.

```vim
function! s:ag_to_qfC(line)
  let parts = split(a:line, ':')
  return {'filename': expand('%'), 'lnum': parts[0], 'col': parts[1],
        \ 'text': join(parts[3:], ':')}
endfunction

function! s:ag_handlerC(lines)
  if len(a:lines) < 2 | return | endif

  let cmd = get({'ctrl-x': 'split',
               \ 'ctrl-v': 'vertical split',
               \ 'ctrl-t': 'tabe'}, a:lines[0], 'e')
  let list = map(a:lines[1:], 's:ag_to_qfC(v:val)')

  let first = list[0]
  execute cmd escape(first.filename, ' %#\')
  execute first.lnum
  execute 'normal!' first.col.'|zz'

  if len(list) > 1
    call setqflist(list)
    copen
    wincmd p
  endif
endfunction

command! -nargs=* Agc call fzf#run({
\ 'source':  printf('ag --nogroup --depth 0 --column --color -G "%s" "%s" "%s"',
\                   expand('%:t'),
\                   escape(empty(<q-args>) ? '^(?=.)' : <q-args>, '"\'),
\                   expand('%:p')),
\ 'sink*':    function('<sid>ag_handlerC'),
\ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
\            '--multi --bind=alt-a:select-all,alt-d:deselect-all '.
\             '--prompt "Agc> "',
\ 'down':    '~30%'
\ })

```

**Comment by juanMarinero** [comment]
Thank you @ZigaSajovic !! It runs smoothly

If anyone might help, I visually explain it. Suppose a project with this tree:
 .
├── a.txt
├── b.txt
└── fol01
    ├── a.txt
    └── b.txt
If your active file is ./a.txt (not ./fol01/a.txt), then you can search:
- with `Agc` in just current file
![currentFileOnly_Agc](https://user-images.githubusercontent.com/40007751/81837073-9ea2b700-9544-11ea-9025-c79fe609f81b.png)
- in whole project with `Ag`
![PWD_and_recursive_Ag](https://user-images.githubusercontent.com/40007751/81837075-9f3b4d80-9544-11ea-842e-073db821c217.png)

 I recommend `Agc` over ` :vimgrep /pattern/ %` because Ag-fzf is interactive.

**Comment by juanMarinero** [comment]
@ZigaSajovic may you give a hint please? how to make depth a variable

Try 1:
```
command! -nargs=* Agc call fzf#run({
\ 'source':  printf('ag --nogroup --depth "%s" --column --color -G "%s" "%s" "%s"',
\                   escape(empty(split(<q-args>, ' ')[0]) ? '0'      : <q-args>, ' ')[0], '"\'),
\                   expand('%:t'),
\                   escape(empty(split(<q-args>, ' ')[1]) ? '^(?=.)' : <q-args>, ' ')[1], '"\'),
\                   expand('%:p')),
\ 'sink*':    function('<sid>ag_handlerC'),
\ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
\            '--multi --bind=alt-a:select-all,alt-d:deselect-all '.
\             '--prompt "Agc> "',
\ 'down':    '~30%'
\ })
```
Try 2:
```
command! -nargs=+ Agc call Sub(<f-args>)
function! Sub( ... )
    execute fzf#run({
\ 'source':  printf('ag --nogroup --depth "%s" --column --color -G "%s" "%s" "%s"',
\                   escape(empty(a:1) ? '0' : a:1, '"\'),
\                   expand('%:t'),
\                   escape(empty(a:2) ? '^(?=.)' : a:2, '"\'),
\                   expand('%:p')),
\ 'sink*':    function('<sid>ag_handlerC'),
\ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
\            '--multi --bind=alt-a:select-all,alt-d:deselect-all '.
\             '--prompt "Agc> "',
\ 'down':    '~30%'
\ })
endfunction
```

**Comment by Folling** [comment]
FWIW here is my way:

`command! -bang -nargs=* Agc call fzf#vim#grep('ag  --nogroup --column --filename --color -- '.shellescape(empty(<q-args>) ? '^(?=.)' : <q-args>) .. ' ' .. shellescape(expand('%:p')) .. ' /dev/null 2>/dev/null', fzf#vim#with_preview(), <bang>0)`

The `/dev/null` is a trick to make `ag` display the filename (which is required for the sink, used for the preview) which it doesn't natively (even with `--filename`) when only one file is searched. There's no performance impact from this as `ag` doesn't support reading from blockdevices like /dev/null.

and for `rg`:

`command! -bang -nargs=* Rgc call fzf#vim#grep('rg  --column --line-number --no-heading --color=always --smart-case --with-filename -- '.shellescape(<q-args>) .. ' ' .. shellescape(expand('%:p')), fzf#vim#with_preview(), <bang>0)`

I'm relatively new to vim, so my lua approach simply wraps this using `vim.api.nvim_exec` in case someone requires this from lua.
