### ISSUE TITLE
Limit the output while query is empty

### ISSUE THREAD

**Issue by hulucc** [junegunn/fzf.vim#727]
With so many things to filter, typing is lag. How can i limit the output before anything typed.
![image](https://user-images.githubusercontent.com/4343900/47954453-34ab6800-dfc5-11e8-88a8-1b67ebe8102c.png)

**Comment by junegunn** [comment]
There's no such option.

Using Rg or Ag without any argument is not recommended. It's much more efficient to use fzf only as the secondary filter, so try to specify an initial query string (e.g. `:Rg foo`).
