### ISSUE TITLE
Preview not working after update

### ISSUE THREAD

**Issue by blayz3r** [junegunn/fzf.vim#734]
- Category
    - [ ] Question
    - [X ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [X ] Windows
    - [ ] Etc.
- Vim
    - [X ] Vim
    - [ ] Neovim

![image](https://user-images.githubusercontent.com/12205650/48305538-73c44680-e4fa-11e8-8160-23f9bdbb5e70.png)

**Comment by junegunn** [comment]
They both do the same thing now but Ruby version is considerably slower to start. Is the situation different on Windows?

**Comment by blayz3r** [comment]
I have no lags the with ruby script on both my machines. The bash script sometimes doesn't work with WSL turned on. But am ok with either method.

**Comment by blayz3r** [comment]
@junegunn Is it possible to add an option that chooses the ruby script. WSL isn't cooperating with the bash script
