### ISSUE TITLE
:Helptags displays results in non-optimal order

### ISSUE THREAD

**Issue by 852e** [junegunn/fzf.vim#735]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

## Expected Behaviour
The `:Helptags` command should prioritise `searched-tag` before `searched-tag-and-other-stuff` when displaying results. (This is how `fzf` behaves when called directly from the command-line, and when invoking `:Files` from within Neovim.)

### Command-line
![easymotion-terminal](https://user-images.githubusercontent.com/44935928/48308523-ff6fbe80-e55e-11e8-86ac-324b8905746b.png)

### Calling :Files withing Neovim
![easymotion-vim-files](https://user-images.githubusercontent.com/44935928/48308524-039bdc00-e55f-11e8-9c69-e0e54b6a7f0b.png)

## Actual Behaviour
`:Helptags` positions `searched-tag` in the middle of a list of results where `searched-tag` is a prefix. Adding an escaped space `\ ` does prioritise the exact match.

### Before scrolling up
![easymotion-vim-helptags-1](https://user-images.githubusercontent.com/44935928/48308534-42319680-e55f-11e8-8ca6-31e0dd5d8fac.png)

### Result in the middle of the list
![easymotion-vim-helptags-2](https://user-images.githubusercontent.com/44935928/48308536-478ee100-e55f-11e8-8d38-109f83441685.png)

[This example is 26th in the list which is otherwise sorted alphabetically. There are 17 similar matches - i.e. `easymotion` is the exact prefix - above so not in median position either.]

### Adding an escaped space
![easymotion-vim-escaped-space](https://user-images.githubusercontent.com/44935928/48308816-eddce580-e563-11e8-936d-bf7c2b34186a.png)

## Comments
- The pictured examples don't make use of `fzf`'s fuzzy matching. I get the same results when searching with a term that would be fuzzy matched. Using the exact term just makes the example clearer.
- The pictured example shows results for `easymotion` which are added with the [easymotion plugin](https://github.com/easymotion/vim-easymotion). I get the same results when searching for terms that are included in the base distribution (e.g. "help").
- Note that the results of `:Files` (and terminal use) are sorted reverse-alphabetically by default; aside from the bug itself, `:Helptags` sort results alphabetically.

**Comment by 852e** [comment]
Switched from fzf.vim to [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim). Thanks Junegunn for all your hard work on fzf.

**Comment by astier** [comment]
Helptags as it is right now is useless. There's also https://github.com/ibhagwan/fzf-lua
