### ISSUE TITLE
It is possible to exclude directories searched by FZF ONLY within vim?

### ISSUE THREAD

**Issue by aly006** [junegunn/fzf.vim#74]
For example, if I invoke FZF on the command line I would like it to search all files, but if invoked in vim, exclude certain directories that I specify.  I read through the documentation and didn't see an easy way to accomplish this.

**Comment by junegunn** [comment]
You can either write your own command using `fzf#run()` function (see https://github.com/junegunn/fzf#fzfrunoptions), or set up `$FZF_DEFAULT_COMMAND` only in your .vimrc like follows:

```vim
let $FZF_DEFAULT_COMMAND= 'ag -g ""'
```

**Comment by aly006** [comment]
for some reason, this doesnt work for me in vim.  
If I do 
`ag -g "" | fzf `
in the command line I get the correct output that respects my agignore
but setting the default command like you did above breaks fzf (i get 0 file results)

**Comment by junegunn** [comment]
No, it works for me.

- `which ag`
- `type ag`
- What about other commands, like `seq 100`?

**Comment by aly006** [comment]
which ag and type ag both are `/usr/bin/ag` as expected.
running things like `seq 100 | fzf` or `echo foobar` work as well.

running the `:Ag` command provided by fzf.vim also does not work. (i get 0 results)

I'll close this for now since the default configuration is fast enough for me even though there are a lot of unignored files that clutter the output.

**Comment by junegunn** [comment]
So setting `$FZF_DEFAULT_COMMAND` to `seq 100` works? Then it seems like your ag installation has some problems. Consider reinstalling a newer version of ag if possible.

**Comment by betovidal** [comment]
Sorry to reply to an old issue, but is it possible to find a solution to this for both Windows and Linux?
