### ISSUE TITLE
Possible to use fzf#vim#ag_raw with preview?

### ISSUE THREAD

**Issue by esn89** [junegunn/fzf.vim#741]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I have a function which I stole from here (issues thread):
```command! -bang -nargs=+ -complete=dir Rag call fzf#vim#ag_raw(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)```

This allows me to pass a directory for my Ag as a :Rag call which is fine, however I lose the preview window like the one from my original :Ag call:

```command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```

My question is, if it is possible to combine the best of both worlds?  I do not need any fancy Ag arguments, just a way to pass a directory in there (maybe even by default, since I only ever look inside of one main directory) and to see previews? 

Thanks in advance.

**Comment by junegunn** [comment]
Simply wrap your options dictionary with `fzf#vim#with_preview`:

```vim
" fzf#vim#with_preview([options], [preview window], [toggle keys...])
command! -bang -nargs=+ -complete=dir Rag call fzf#vim#ag_raw(<q-args>, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}), <bang>0)
```

It's a function that takes a dictionary and returns a copy of it with preview options attached. You can see what it does by examining the return value. i.e. `:echo fzf#vim#with_preview({'options': '--no-color'})`

**Comment by esn89** [comment]
One thing I am not sure of, is the fact that "ag" to pass a directory does not require a flag.
As ag is done via:  `ag "search term" /path/to/dir`

I have tried your example and simply put in:  
```
command! -bang -nargs=+ -complete=dir Rag call fzf#vim#ag_raw(<q-args>, fzf#vim#with_preview({'~/Documents/Projects/'}), <bang>0)```

And it gave me this: https://i.imgur.com/nl2ige2.png
