### ISSUE TITLE
Close buffer while scrolling the list

### ISSUE THREAD

**Issue by dalizard** [junegunn/fzf.vim#75]
Hello everyone,

First of all, @junegunn you've done amazing work! Thank you! :heart: I have a question, which has already been asked [here](https://www.reddit.com/r/neovim/comments/3oeko4/post_your_fzfvim_configurations/cw0c97g) but I am not sure if it is indeed doable. Basically, is it possible to close/delete a buffer while looking at the list of open buffers?

**Comment by junegunn** [comment]
Since fzf is not a native Vim plugin but an external program running as a different process, we need a way for it to send commands to the neovim process. I haven't tried yet but we might be able to use msgpack API.

**Comment by majjoha** [comment]
I'd be happy to see this supported as well.

**Comment by githubfun** [comment]
found this when searching how to close buffer in fzf. I'd be happy to see this supported as well:)

**Comment by vito-c** [comment]
would be fun to see this implemented.

**Comment by CrashyBang** [comment]
:+1:

**Comment by phcerdan** [comment]
:+1:

**Comment by goschevski** [comment]
👍

**Comment by artursmirnov** [comment]
👍

**Comment by gpanders** [comment]
Any update on this?

**Comment by zhamlin** [comment]
```vim
function! s:fzf_format_buffer(b)
    let l:name = bufname(a:b.bufnr)
    let l:name = empty(name) ? '[No Name]' : fnamemodify(name, ":~:.")
    let l:number = s:red(a:b.bufnr, "Number")
    let l:modified = getbufvar(a:b.bufnr, '&modified') ? s:red(' [+]', 'Exception') : ''
    let l:readonly = getbufvar(a:b.bufnr, '&modifiable') ? '' : s:green(' [RO]', 'Constant')
    let l:extra = join(filter([l:modified, l:readonly], '!empty(v:val)'), '')
    let l:flag = a:b.bufnr == bufnr('')  ? s:blue('%', 'Conditional') :
        \ (a:b.bufnr == bufnr('#') ? s:agenta('#', 'Special') : ' ')
    return printf("[%s] %s\t%s\t%s", l:number, l:flag, name, l:extra)
endfunction

function! s:fzf_buflist()
    let buffers = copy(getbufinfo({'buflisted': 1}))
    let l:fzf_bufs = []
    let l:current_buffer = ""

    for buf in l:buffers
        let l:bufstr = s:fzf_format_buffer(buf)
        " don't add current buffer to list, do it at end so
        " it won't be selectable using --header-line=1
        if bufnr('') ==# buf.bufnr
            let l:current_buffer = l:bufstr
        else
            let l:fzf_bufs = insert(l:fzf_bufs, l:bufstr)
        endif
    endfor

    " hide any blank buffers, like help, qf, etc
    return filter(insert(l:fzf_bufs, l:current_buffer), "v:val != ''")
endfunction

function! s:fzf_buffer_handler(input)
    let l:cmd = get({'ctrl-d': 'Bclose', 'ctrl-v': 'vert sb', 'ctrl-x': 'sb'}, a:input[0], 'buffer')
    let l:buffers = a:input[1:]
    for l:buf in l:buffers
        execute printf('%s %d', l:cmd, str2nr(matchstr(l:buf, '\[\zs[0-9]*\ze\]')))
    endfor
endfunction

nnoremap <silent> <c-b> :call fzf#run(fzf#wrap("buffers", {
\   'source':  <sid>fzf_buflist(),
\   'sink*':   function('<sid>fzf_buffer_handler'),
\   'options': '--ansi -m --header-lines=1 --tiebreak=index -d "\t" -n 2,1..2 --expect=ctrl-d,ctrl-v,ctrl-x --prompt "Buf> "',
\   'down':    len(<sid>buflist()) + 2
\ }), 0)<CR>
```

This works for me, able to delete buffers using ctrl-d, you'll need to replace the `s:color` calls in `fzf_format_buffer` with just the string, unless you add this as well
```vim
" taken from https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim
let s:ansi = {'black': 30, 'red': 31, 'green': 32, 'yellow': 33, 'blue': 34, 'magenta': 35, 'cyan': 36}

function! s:csi(color, fg)
  let prefix = a:fg ? '38;' : '48;'
  if a:color[0] == '#'
    return prefix.'2;'.join(map([a:color[1:2], a:color[3:4], a:color[5:6]], 'str2nr(v:val, 16)'), ';')
  endif
  return prefix.'5;'.a:color
endfunction

function! s:ansi(str, group, default, ...)
  let fg = s:get_color('fg', a:group)
  let bg = s:get_color('bg', a:group)
  let color = s:csi(empty(fg) ? s:ansi[a:default] : fg, 1) .
        \ (empty(bg) ? '' : s:csi(bg, 0))
  return printf("\x1b[%s%sm%s\x1b[m", color, a:0 ? ';1' : '', a:str)
endfunction

for s:color_name in keys(s:ansi)
  execute "function! s:".s:color_name."(str, ...)\n"
        \ "  return s:ansi(a:str, get(a:, 1, ''), '".s:color_name."')\n"
        \ "endfunction"
endfor
```

**Comment by bfgasparin** [comment]
👍

**Comment by janlazo** [comment]
Is this possible with the Vim terminal instead?

**Comment by junegunn** [comment]
I don't want to overcomplicate this. Define a separate command that lists buffers with `--multi` enabled, select buffers you want to delete with tab/shift-tab, press enter, and its sink function deletes the selected buffers. You can optionally restart the command if you want to repeat the process with the updated list.

**Comment by zaferot** [comment]
@junegunn Continuing your suggestion. Is it possible to define a variant of `Buffers` with `--multi` and a separate key mapping to close selected buffers (e.g. `c-d`) instead of enter? So, one can be able to go to a buffer or close it.  Will that work?

**Comment by matthewgrossman** [comment]
this isn't the greatest, but here's perhaps a stop gap for some people:

```
let g:fzf_action = {
    \ 'ctrl-q': 'wall | bdelete',
    \ 'ctrl-t': 'tab split',
    \ 'ctrl-x': 'split',
    \ 'ctrl-v': 'vsplit' }
```
this will save all the buffers (stopping an unwritten buffer error), then delete the buffer. I combined this with my own custom function that has `--multi` to be able to delete multiple buffers

```
command! FZFMulti call fzf#run(fzf#wrap({
            \'source': 'ag -l',
            \'options': ['--multi'],
            \}))
```

`:FZFMulti` will run it

**Comment by bradens** [comment]
Is there any update on this?

**Comment by wreed4** [comment]
@junegunn Any comment on @zaferot 's comment from last October? I've been trying to figure out how to implement this and simply setting `bdelete` in `g:fzf_action` seems to not work. It always closes the _current_ buffer before switching to the one that was selected in the first place.

**Comment by kovasap** [comment]
Any updates on this?  Interested in seeing the feature!

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/pull/733#issuecomment-559720813

**Comment by junegunn** [comment]
31e338e3143eddd6dbc424870899af28d987d30f
