### ISSUE TITLE
Error detected while processing Dirchanged 

### ISSUE THREAD

**Issue by kdurant** [junegunn/fzf.vim#750]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

1. `GFiles  `
2. select `xxx.file' and run `ctrl-v` to vsplit it.
3. `:close`
4. 
![qq 20181223111420](https://user-images.githubusercontent.com/2704364/50380504-08969400-06a4-11e9-9b0a-0a12c5764465.png)

**Comment by junegunn** [comment]
Pretty sure that it's an issue of another plugin you have, not fzf.vim.
