### ISSUE TITLE
Content is cut off with fzf#vim#with_preview

### ISSUE THREAD

**Issue by npearson72** [junegunn/fzf.vim#751]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'm using the following configs:

```
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync

" Below is what I've added to my configs:
nnoremap <c-p> :Files<cr>
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('right:50%', 'ctrl-p'), <bang>0)
```

After invoking `Ctrl`+`p` I'm presented with a list of my files with a preview window. However the lines of content in the preview is limited to ~19, when in actuality the files have more lines.

![kapture 2019-01-07 at 10 23 59](https://user-images.githubusercontent.com/1323414/50783025-dd48a300-1266-11e9-86ea-a24513b0e72c.gif)

**Comment by lan-nguyen91** [comment]
I got same behavior on Mac with vim8, did you find a fix yet @npearson72 ?

**Comment by npearson72** [comment]
@lan-nguyen91 afraid not.

**Comment by lan-nguyen91** [comment]
@junegunn, do you happen to know if vim default config hide stuff on preview window, right now the first 30 lines show on my set up, but as I scrolled, it is all blank. :(

**Comment by junegunn** [comment]
The behavior is intentional and is not configurable: https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh#L50-L54

For now, I suggest that you fork the repository and change it to your needs since I'm not planning to add more configuration options for the time being.

**Comment by lan-nguyen91** [comment]
@junegunn thanks for the direction, @npearson72 I followed June direction, and removed this condition `&& NR <= $LAST` in the line above, i'm not sure it is ideal but works for me right now. Cheers 😀

**Comment by npearson72** [comment]
Works like a charm. Thanks guys!

**Comment by ogirginc** [comment]
Removing `&& NR <= $LAST` from `preview.sh` [file](https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/bin/preview.sh#L59) does not seem to work anymore.

I ended up with these changes:

- Commented out this [`if`](https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/bin/preview.sh#L49-L53).
```vim
# if [ -z "$FZF_PREVIEW_COMMAND" ] && command -v bat > /dev/null; then
#   bat --style=numbers --color=always --pager=never \
#       --line-range=$FIRST:$LAST --highlight-line=$CENTER "$FILE"
#   exit $?
# fi
```

- Add [`bat`](https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/bin/preview.sh#L55) back.
```vim
DEFAULT_COMMAND="bat --style=numbers --color=always {} || highlight -O ansi -l {} || coderay {} || rougify {} || cat {}"
CMD=${FZF_PREVIEW_COMMAND:-$DEFAULT_COMMAND}
CMD=${CMD//{\}/$(printf %q "$FILE")}
```

- Remove [`&& NR <= $LAST`](https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/bin/preview.sh#L59) like it was mentioned before.
```vim
eval "$CMD" 2> /dev/null | awk "NR >= $FIRST { \
    if (NR == $CENTER) \
        { gsub(/\x1b[[0-9;]*m/, \"&$REVERSE\"); printf(\"$REVERSE%s\n$RESET\", \$0); } \
    else printf(\"$RESET%s\n\", \$0); \
    }"
```

**Comment by kuntau** [comment]
How do you scroll the preview pane? 🤔

**Comment by her** [comment]
Easiest way for me to hack around this was to set 

```
FIRST=0
LAST=1000000
```

@junegunn Why do we limit the file preview?

**Comment by Rodrigo-Barros** [comment]
> How do you scroll the preview pane? thinking

just use shift + down or shift +up

**Comment by her** [comment]
@Rodrigo-Barros the content is not all there though, it's cut off. Preview a large file and scroll, you'll see you only have a small subsection of the file, rather than all the contents.

**Comment by 123subhadeep** [comment]
@ogirginc @Rodrigo-Barros 

Do any of you know how I can keep the highlighted line in the preview in the middle by default. Right now, it always shows 5 lines above the highlighted line, which isn't helpful to get context before the highlighted line.  https://github.com/junegunn/fzf.vim/issues/1092 has a screenshot with an example.

Another question for you guys, I saw that Shift + Up/Down works great with scrolling, is it possible to rebind those keys ? Arrow keys are harder to reach (Would prefer something like Ctrl -j/k). 

Looking forward to hearing from you. Thanks in advance.

**Comment by Rodrigo-Barros** [comment]
@123subhadeep as said in you can install [bat](https://github.com/sharkdp/bat) it's an optional dependency that enables
