### ISSUE TITLE
Show code block as a single line

### ISSUE THREAD

**Issue by usernamepickedalready** [junegunn/fzf.vim#755]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

FZF command :Lines and :BLines searches pattern in a single line.
But there are also situations where I look for a pattern within a multi-lined code block.
For example:

**Data**

```
[
fruit: bananas
color: yellow
calories: 100
]
[
fruit: apples
color: green
calories: 60
]
```

**Default behavior BLines:**

```
> "no results"

BLines > fruit yellow <
```
**Desired behavior:**

```
> [,fuit: bananas, color: yellow, calories: 100,]

BLines > fruit yell <
```
_1. BLines shows found results within a block as one line._
_2. Selected search result moves the cursor to the beginning of the code block of the found pattern._
Nice to have:
_a. Long code blocks are shown wrapped in the search results_
_b. Found pattern are highlighted in the editor_

**What is the relevance of this behavior**
It finds and shows more quickly the context of the related data in one line, which makes searching more easyer and faster.

**Comment by junegunn** [comment]
The current implementation is strictly line-based. Identifying and squashing code blocks is beyond the scope of this project.
