### ISSUE TITLE
Wrong colors in preview window

### ISSUE THREAD

**Issue by chevysniff** [junegunn/fzf.vim#756]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

Hi,
I can't get fzf.vim preview window to work with my vim/bat theme settings.

The problem is that code that is displayed in the preview window seems like it uses only 16 terminal colors. Please look at below screenshot. One the left it is a neovim with preview window, on the right you can see fzf in term with the desired color scheme. The preview colors are fine in console fzf but in neovim it seems like the theme is used only with 16 colors (not 256).
![2019-01-27-211157_2540x1387_scrot](https://user-images.githubusercontent.com/4434640/51806354-52f9ca80-2279-11e9-93eb-5912a1013b3d.png)

However when I did a test with vim 8 (not neovim) the colors in preview window are identical to the console version of fzf.
![2019-01-27-212439_2547x1385_scrot](https://user-images.githubusercontent.com/4434640/51806417-0662bf00-227a-11e9-94a7-a00c551c5ca3.png)

**Comment by fuadsaud** [comment]
I can second that. Also, `bin/preview.sh` display correct colors. I'm currently using a True Color colorscheme in neovim, not sure if that's any useful information.

**Comment by junegunn** [comment]
Open up `:terminal`, run bat command and see if the colors are correct there.

**Comment by itsNikolay** [comment]
I change fzf background color from black to grey through `guibg=#1b1b24`:
```vim
:hi Terminal ctermbg=lightgrey ctermfg=blue guibg=#1b1b24 guifg=blue
```

**Comment by fuadsaud** [comment]
@junegunn interesting. running `:terminal` opens up a pane with bad colors. Apparently nvim doesn't know how to handle true colors in terminal panes. Thanks!

**Comment by junegunn** [comment]
See https://github.com/neovim/neovim/issues/2897#issuecomment-115464516
