### ISSUE TITLE
Configure color of the path output in Ag command

### ISSUE THREAD

**Issue by majjoha** [junegunn/fzf.vim#76]
First of all, thank you for a great plugin.

Is it in any way possible to configure the color of the path in the output of the `Ag` command? As shown in the image below, it can be somewhat difficult to see the path (which is often convenient for providing context).

<img width="1162" alt="screen shot 2016-01-22 at 22 34 23" src="https://cloud.githubusercontent.com/assets/233988/12523632/5e386774-c158-11e5-9862-abd7f3f1e4ad.png">

It would be extremely useful if this was somehow configurable.

**Comment by junegunn** [comment]
You seem to have a weird terminal color scheme :)

This can be done with `--color-path` option of ag. The question is how we can customize the options to ag. This was discussed before in #51, but we haven't found an ideal solution. (Not a fan of adding a bunch of configuration variables.) Currently, you have to redefine `:Ag` command with the underlying `fzf#vim#ag` function.

```vim
" Redefine :Ag command
autocmd VimEnter * command! -nargs=* Ag
      \ call fzf#vim#ag(<q-args>, '--color-path "33;1"', fzf#vim#default_layout)
```

Please note that the API is still undocumented, and I make no guarantee about its backward compatibility.

**Comment by majjoha** [comment]
It is basically just Base16 in its Ocean variation, but thank you so much for your quick reply. It works like a charm!

**Comment by ahmedelgabri** [comment]
I don't know if this related but I have a similar issue
<img width="1680" alt="screen shot 2016-02-06 at 15 07 33" src="https://cloud.githubusercontent.com/assets/63876/12867076/dd21a15e-cce3-11e5-91a3-80bd398c7229.png">

I'm using neovim, zsh and tmux, my `$TERM` is `xterm-256color-italic` and inside tmux it's `tmux-256color` which is taken from here https://github.com/tmux/tmux/issues/194#issuecomment-156952428

**Comment by junegunn** [comment]
@ahmedelgabri The colors are currently hard-coded in the code. It looks like follows on my terminal:
<img width="1280" alt="screen shot 2016-02-07 at 12 31 23 am" src="https://cloud.githubusercontent.com/assets/700826/12867476/37768518-cd32-11e5-8e46-2891abd6e9fc.png">

**Comment by ahmedelgabri** [comment]
@junegunn so there is no way to change it currently I assume?

**Comment by junegunn** [comment]
@ahmedelgabri Correct. At the moment the only way is to fork the repository and change the code to your liking, which is actually doable since I'm not actively adding stuff. This plugin has many number of features, and providing consistent interface for configuring them requires much thought.

**Comment by ahmedelgabri** [comment]
@junegunn Ok, thanks

**Comment by sfahlberg** [comment]
+1 for a fix on the colors in ag

**Comment by ahmedelgabri** [comment]
@sfahlberg Have you tried setting `g:fzf_colors` like in the readme? https://github.com/junegunn/fzf.vim#global-options

**Comment by sfahlberg** [comment]
this is what it looks like when I set options like that. I'm using the gruvbox theme
<img width="723" alt="screen shot 2016-11-17 at 11 25 48 am" src="https://cloud.githubusercontent.com/assets/5889293/20404230/e736a31e-acb8-11e6-932e-8791f816612d.png">

**Comment by ahmedelgabri** [comment]
Ok then I don't really know, because I don't use Ag through fzf _(blame my muscle memory)_

**Comment by junegunn** [comment]
@sfahlberg Like I mentioned above, you can change the color using `--color-path` option of ag. If you don't know how to use the option, ask the author of ag.

**Comment by sfahlberg** [comment]
thanks! this fixed it for me: `autocmd VimEnter * command! -nargs=* Ag call fzf#vim#ag(<q-args>, '--color-path 400 --color-line-number 400', fzf#vim#default_layout)`

**Comment by sfahlberg** [comment]
@junegunn this works (above), except for when I do a `source ~/.init.vim` after which it reverts to the original. Any thoughts on how to fix that?

**Comment by junegunn** [comment]
@sfahlberg We no longer need `autocmd VimEnter *` since 1bf68a978bfc22fd1685e736fb852e78003fc468. Remove it and see if it helps.
