### ISSUE TITLE
Commands like :BCommits and :Commits fail

### ISSUE THREAD

**Issue by osa1** [junegunn/fzf.vim#763]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Tried with latest versions of fzf and fzf.vim and latest versions of neovim and vim, all cloned and installed from their git repos.

When I do `:BCommits` or `:Commits` I get error messages like this: (this is from `:Commits` in latest vim)

```
Error running ( git log --color=always '--format=%C(auto)%h%d %s %C(green)%cr' --graph )|'/home/omer/.fzf/bin/fzf' --color=bg+:#282A36,bg:#28
2A36,spinner:#FF79C6,hl:#50FA7B,fg:#F8F8F2,header:#6272A4,info:#BD93F9,pointer:#FF79C6,marker:#FF79C6,fg+:#F8F8F2,prompt:#50FA7B,hl+:#FFB86C
'--ansi' '--multi' '--tiebreak=index' '--layout=reverse-list' '--inline-info' '--prompt' 'Commits> ' '--bind=ctrl-s:toggle-sort' '--header' '
:: Press ^[[38;2;255;121;198mCTRL-S^[[m to toggle sort, ^[[38;2;255;121;198mCTRL-Y^[[m to yank commit hashes' '--expect=ctrl-y,ctrl-v,ctrl-x,
ctrl-t' '--preview' 'echo {} | grep -o "[a-f0-9]\{7,\}" | head -1 | xargs git show --format=format: --color=always | head -200' --no-height >
 /tmp/nvimhqCmS9/8
```

I also briefly see a `Failed to read /dev/tty` message in the new split for `:Commits`/`:BCommits`. When I check I see that I have a file `/dev/tty`, I don't know why fzf.vim can't read it.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/1486. You should wait for the Kernel fix, which should be coming pretty soon, or roll back to an older Kernel.
