### ISSUE TITLE
fzf-vim fails when running with fzf_action

### ISSUE THREAD

**Issue by hzfmer** [junegunn/fzf.vim#765]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Everything in FZF works except when I tried to set `let g:fzf_action`, which makes fzf throws an weird error:
> Error running ( /bin/zsh '/var/folders/ct/8z0w3p7n6fnc5mhfbqkg4r38001rdv/T/vIBCLzw/12' )| '\~/.fzf/bin/fzf' --history '\~/.local/share/fzf-history/files' --color=hl:#8a8a8a,header:#8a8a8a
 '-m' '--prompt' '\~/' --expect=crtl-v,crtl-x --height=19 > /var/folders/ct/8z0w3p7n6fnc5mhfbqkg4r38001rdv/T/vIBCLzw/14

My fzf_action is copies from the tutorial:
>let g:fzf_action = {
     \ 'crtl-x': 'split',
     \ 'crtl-v': 'vsplit' }

It doesn't really matter how fzf_action looks like (one or more actions defined). As soon as I delete it , since actually they are the same as the default actions, the error disappears.

**Comment by junegunn** [comment]
`crtl` to `ctrl`
