### ISSUE TITLE
[Question] How to exclude unwanted directory in fzf search?

### ISSUE THREAD

**Issue by junhyeokahn** [junegunn/fzf.vim#767]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hello.
First of all I really appreciate you maintaining this awesome libraries.
I mostly use this in my root directory in my git project with the following key map.
```
nnoremap <silent> <c-p> :FZF<CR>
```
When I turn on my fzf with ```ctrl-p```, I see some irrelevant files generated in compilation process and want to exclude a irrelevant directory in fzf.
This might be done with easy option but I could not find.

How can I exclude unwanted directory in fzf searching?

**Comment by junegunn** [comment]
`:FZF` command simply starts fzf process without explicit STDIN source, so it respects `$FZF_DEFAULT_COMMAND`. This might help you out: https://github.com/junegunn/fzf#respecting-gitignore
