### ISSUE TITLE
enew buffers not closed with "{ 'window': 'split enew' }"

### ISSUE THREAD

**Issue by hanschen** [junegunn/fzf.vim#769]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

**Description of problem**

When using `let g:fzf_layout = { 'window': 'split enew' }` and using a fzf command (e.g. `Files`), an empty `enew` buffer is created and persists even when fzf is closed.

This does not happen with `let g:fzf_layout = { 'window': 'enew' }`.

**How to reproduce**

With this .vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()
let g:fzf_layout = { 'window': 'split enew' }
```
1. In a new vim session, issue an fzf command, e.g. `:Files`.
2. Press `Escape` to close the fzf split (the same thing happens if you hit `Enter`).
3. `:buffers` now shows a new `"enew"` buffer.

**Expected behavior**

There should be no new `"enew"` buffer.

**Additional information**

Tested with Vim 8.1 compiled by Arch Linux.

**Comment by junegunn** [comment]
Try `:split enew` on Vim. You'll see a new buffer called `enew`, which means it's not the command you should be using. Just use `split` or `vsplit`.

**Comment by hanschen** [comment]
Ah, I see. So I guess the README should be updated then? That's where I got the idea to use `'split enew'` from:

```
" In Neovim, you can set up fzf window using a Vim command
let g:fzf_layout = { 'window': 'enew' }
let g:fzf_layout = { 'window': '-tabnew' }
let g:fzf_layout = { 'window': '10split enew' }
```

It's also part of the docs.

**Comment by junegunn** [comment]
Oh, that needs to be fixed. Will do. Thanks.

**Comment by hanschen** [comment]
Thanks for the fast answer and fix!
