### ISSUE TITLE
File not found in preview when using :History

### ISSUE THREAD

**Issue by sdemura** [junegunn/fzf.vim#771]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

![image](https://user-images.githubusercontent.com/11758459/53248961-dfcf5280-3684-11e9-8a74-0fd71e23395b.png)

Using `command! -bang -nargs=* History call fzf#vim#history(fzf#vim#with_preview({'options': '--no-sort'}))` results in 'File not found' error if the file is not in the current working dir.

Additionally, on files it can find, its using `bat` although I have not configured FZF to use bat.

![image](https://user-images.githubusercontent.com/11758459/53249096-481e3400-3685-11e9-9561-7f49874fafa4.png)

fwiw, :Files and :GFiles work as expected.

**Comment by sdemura** [comment]
If I comment out https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh#L20-L23, then :History with preview works as expected.

I'm not sure though why this is happening.

I also see an undocumented `FZF_PREVIEW_COMMAND` variable that I can use to set command I want.

But why must I set this when I have the preview command set in FZF_DEFAULT OPTS:

```export FZF_DEFAULT_OPTS="--no-mouse --cycle --bind 'ctrl-j:ignore,ctrl-k:ignore' --ansi --preview 'bat {}'"
```

For :Files and :GFiles i do not need `FZF_PREVIEW_COMMAND` set to work as expected, but with :History I do.

**Comment by sdemura** [comment]
Something must have been buggy with tmux. I killed my tmux server and now i do not need to comment the code linked above.

However, `FZF_PREVIEW_COMMAND` should be documented.

**Comment by samiralajmovic** [comment]
@sdemura how does your FZF_PREVIEW_COMMAND look like? Im having the same issue.

**Comment by daturkel** [comment]
I've got the same issue and would like to know more about your solution @sdemura as I'm not using tmux at all.

**Comment by junegunn** [comment]
See #774.

I must mention that setting `--preview` option in FZF_DEFAULT_OPTS is a bad idea because fzf is a context-free text filter than a file selector. The command will fail whenever you use fzf with things that aren't files.

```sh
ps -ef | fzf
history | fzf
seq 100 | fzf
fzf < /usr/share/dict/words
```
