### ISSUE TITLE
Calling fzf#run requires stream to complete before exiting

### ISSUE THREAD

**Issue by mitchmcdee** [junegunn/fzf.vim#776]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm writing a plugin and am calling `fzf#run` and whenever I attempt an exit (i.e. by pressing enter or just ctrl+c) the fzf window goes blank and requires an additional ctrl+c to exit. Any idea what could cause this? I have confirmed the issue remains on a minimal configuration.

Interestingly, passing `--no-clear` through options successfully prevents clearing. To me this suggests that fzf is exiting however the terminal buffer isn't closing, is there anyway I can force it to close? Or any ideas what could be causing this?

**Comment by mitchmcdee** [comment]
aha! I think this has something to do with the streaming input source-- it only goes to blank screen (i.e. hangs) when their is still more streaming input. Once complete however, or if it was complete before an attempt to exit was made, it exits just fine in one <Ctrl+C>

Any ideas on how to fix? Either on my end or within the plugin or within fzf?

**Comment by junegunn** [comment]
Your source program should handle SIGPIPE and terminate itself. Otherwise, it will keep running even after fzf finishes. See https://github.com/junegunn/fzf/issues/398#issuecomment-152370884
