### ISSUE TITLE
Opening files with :Rg hangs until rg has finished

### ISSUE THREAD

**Issue by ckoehler** [junegunn/fzf.vim#778]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

FZF 0.17.5
fzf.vim latest (with vim-plug)
ripgrep latest 0.10.0

I tested this in the minimal configuration, with a large source tree. Doing :Rg<enter>, finding some string, and then hitting 'enter' to open that file, hangs until rg is done running. This is similar to #287 (comment by abarax). Once rg has counted everything it counts (the '5049384/5049384' progress spinner at the bottom), it works fairly quickly, but not before.

**Comment by GuillaumeLagrange** [comment]
Same problem here, when I am using :Rg, it hangs for sometimes a very long time (on large code bases somthing like one minute).
:Ag does not seem to have the problem.
Ubuntu 18.04 LTS, rg installed via cargo (0.10.0)

**Comment by junegunn** [comment]
Not sure, but it could be an issue of ripgrep. I use ag, which is fast enough for me, and don't have any issue.

By the way, running `:Ag` or `:Rg` without a keyword is probably not a good idea especially you're working on a large codebase, because they are much more efficient than fzf for initial filtering. These are the mappings I use frequently.

```vim
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
xnoremap <silent> <Leader>ag y:Ag <C-R>"<CR>
```

**Comment by ckoehler** [comment]
Thanks, I installed Ag and am also using those mappings now with both Rg and Ag. They are a lot faster, so I'll try it like this for a bit.

**Comment by andys8** [comment]
@junegunn I like this, but I'm searching for a solution, that works the also if there is no word under the cursor. I want to avoid this.
> E348: No string under cursor

Do you have ideas?

**Comment by junegunn** [comment]
Similarly, `:execute 'Rg' expand('<cword>')`
