### ISSUE TITLE
:Files not opening file

### ISSUE THREAD

**Issue by xanderio** [junegunn/fzf.vim#779]
- Category
    - [ ] Question
    - [x ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [x ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

https://asciinema.org/a/OdOBNyklHfF8qHFphgo98mwlY

Other commands such as :Buffers work fine

**Comment by scotts777** [comment]
This is occurring to me also.  :Buffers work fine.  I am running on Windows 10, NVIM v0.4.0-450-g2d50bf349,  fzf works fine in the powershell.  When issuing the command :Files, nvim opens a terminal window split and I can fuzzy find the file I want.  Hitting enter does not open the file; ctrl-t, ctrl-v, ctrl-t do nothing as well.

**Comment by hecerinc** [comment]
I'm also having this issue 😢

**Comment by beanstalkblue** [comment]
I'm having this issue in vim 8.1, but not in nvim 0.3.5.

Both with exact same minimal config file.
