### ISSUE TITLE
Multi-select is broken

### ISSUE THREAD

**Issue by zackhsi** [junegunn/fzf.vim#78]
Ctrl+a then enter used to open all results in the quickfix window. I recently updated, and it doesn't work anymore. Are there logs or a --bind or something that I can do to help fix this?

https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

**Comment by zackhsi** [comment]
Ahh, just saw this: https://github.com/junegunn/fzf.vim/issues/54.

Seems escape + a does it for me now. (option+a inserts å).

**Comment by junegunn** [comment]
These mappings help.

```vim
if has('nvim')
  tnoremap <a-a> <esc>a
  tnoremap <a-b> <esc>b
  tnoremap <a-d> <esc>d
  tnoremap <a-f> <esc>f
endif
```

**Comment by zackhsi** [comment]
Thanks
