### ISSUE TITLE
How do I change the colors on Rg output?

### ISSUE THREAD

**Issue by tambourine-man** [junegunn/fzf.vim#780]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

I tried everything, but fzf.vim doesn't seem to respect rg "--colors" settings.  

There seems to be a hardcoded color here:
fzf.vim/autoload/fzf/vim.vim#715
`\             '--color', 'hl:4,hl+:12']`

But that only changes the matched string, not file path and line number.

Ideally there should be a way to config it without overwriting core files, but I've been banging my head against this for so long that I'm already willing to do that.

Thanks a lot

**Comment by junegunn** [comment]
Have you tried reading the source code? You can pass any fzf options to `fzf#vim#grep` function.

**Comment by tambourine-man** [comment]
Hi Junegunn,

I did, but couldn't figure it out. Vimscript is not my forte.
How can add these options to the proper argument in this example from the documentation?

`command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)`

Thanks

**Comment by tambourine-man** [comment]
This works by removing the color completly:

```command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --colors match:fg:yellow --smart-case '.shellescape(<q-args>), 1, { 'options': '--no-color' }, 0)```

but what I wanted was for fzf.vim to respect the `--colors match:fg:yellow` that I'm passing to rg.

**Comment by junegunn** [comment]
`--no-color` disables color altogether, so it's not the option you want.

> fzf.vim to respect the --colors match:fg:yellow that I'm passing to rg.

It does preserve the original colors from ripgrep. You passed an argument to `:Rg`, right? i.e. `:Rg foo`, then ripgrep will color `foo` yellow. Now then, fzf works as the secondary filter, and the overlay color applied is unrelated to the ripgrep options. You'll have to override `--color` option of fzf, `{ 'options': '--color hl+:9' }` for example.

**Comment by tambourine-man** [comment]
>You passed an argument to :Rg, right?
No I was just invoking :Rg and typing afterwards

I got it now. For future Googlers, this works:
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --colors "path:fg:190,220,255" --colors "line:fg:128,128,128" --smart-case '.shellescape(<q-args>), 1, { 'options': '--color hl+:10' }, 0)
```
Thanks a lot for fzf in general. It's extremely adictive (in a good way). 
z (bash jump) + fzf is pure joy.

**Comment by tambourine-man** [comment]
Hi Junegunn, same issue with :Lines command
Blue is barely readable.

fzf.vim/autoload/fzf/vim.vim#362
`let linefmt = s:blue("%2d\t", "TabLine")."%s".s:yellow("\t%4d ", "LineNr")."\t%s"`

Is there a way to pass options to it?

**Comment by junegunn** [comment]
No, consider changing your color scheme to one that sets TabLine to a different color or set it yourself.
