### ISSUE TITLE
:Files to new tab breaks the cwd, if this has been changed

### ISSUE THREAD

**Issue by mg979** [junegunn/fzf.vim#783]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

It seems to me that fzf `:Files` command changes the working directory before actually leaving the tab, not after it enters the new one. This leads to the following problems. Also, this doesn't happen with `:Buffers` or `:History` commands.

To reproduce with fzf alone (minimal vimrc you provided):
* load a file (`vim some_file`)
* `tabedit` some other file, placed in a different directory, so that you have 2 tabs
* add these autocommands:
```vim
        au TabLeave * let t:cwd = getcwd()
        au TabEnter * if exists('t:cwd') | cd `=t:cwd` | endif
```
* go to tab 1 and do `:cd %:h`
* go to tab 2 and do `:cd %:h`
* `:pw` should echo different directories when you change tabs (autocommands change the cwd)
-----

Now run `:Files another_different_directory` and press `ctrl-t` to open the file in a new tab, the working directories for the tabs get messed up:
* the old tab's `cwd` becomes the directory of the `Files` command
* the new tab's `cwd` will become the old working directory

So I'd like `Files` to behave just like `History` and `Buffers`, it's very disruptive to have the cwd changed without being aware of it.

**Comment by junegunn** [comment]
Please check if this patch (for the main fzf repo) helps:

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 5eca120..f0993af 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -459,7 +459,7 @@ function! s:pushd(dict)
     \   'command': haslocaldir() ? 'lcd' : (exists(':tcd') && haslocaldir(-1) ? 'tcd' : 'cd'),
     \   'origin': cwd
     \ }
-    execute 'lcd' s:escape(a:dict.dir)
+    execute 'noautocmd lcd' s:escape(a:dict.dir)
     let cwd = s:fzf_getcwd()
     let w:fzf_pushd.dir = cwd
     let a:dict.pushd = w:fzf_pushd
@@ -494,7 +494,7 @@ function! s:dopopd()
   " change the directory to 'dir'. In that case, the user will have an
   " unexpected result.
   if s:fzf_getcwd() ==# w:fzf_pushd.dir
-    execute w:fzf_pushd.command s:escape(w:fzf_pushd.origin)
+    execute 'noautocmd' w:fzf_pushd.command s:escape(w:fzf_pushd.origin)
   endif
   unlet w:fzf_pushd
 endfunction
```

**Comment by junegunn** [comment]
Ah you have autocmd on TabLeave and TabEnter. It probably won't help.

**Comment by mg979** [comment]
Just tried and it's still happening...

**Comment by mg979** [comment]
Is there a specific reason why the working directory should be changed? Isn't it more normal if this is left to vim, or the user to set if needed?

**Comment by mg979** [comment]
I found a sort of workaround by checking:
```vim
au TabLeave * if !exists('w:fzf_pushd') | let t:cwd = getcwd() | endif
```

It's better than nothing, I can close the issue if there's no better way for now.

**Comment by junegunn** [comment]
`:Files /tmp` should run the find command inside `/tmp`, and the sink function (implemented in VimScript) should be able to handle relative file paths. For that to work, we switch directories during the process. Switching may not be necessary if you don't pass a directory argument to the command, but we're doing it anyway to keep things simple. Unfortunately, the whole code has become quite complicated and I'm not confident if I can clean it up without breaking someone's workflow. But feel free to send a pull request if you know a better way to handle that.

**Comment by mg979** [comment]
Ok thanks, at least I could understand what the issue was and could find some sort of workaround. If I think of something better I'll post again.
