### ISSUE TITLE
Support neovim float window

### ISSUE THREAD

**Issue by taigacute** [junegunn/fzf.vim#786]
- Category
    - [ ] Question
    - [ ] Bug
    - [ x] Suggestion
- OS
    - [ ] Linux
    - [x ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ x] Neovim

 is Fzf support neovim float window?

**Comment by tfmoraes** [comment]
@taigacute take a look at this https://github.com/junegunn/fzf.vim/issues/664#issuecomment-476438294

**Comment by taigacute** [comment]
> @taigacute take a look at this [#664 (comment)](https://github.com/junegunn/fzf.vim/issues/664#issuecomment-476438294)

thaks for your reply, i saw this issue, its old, neovim change a new api for floatwindow.

**Comment by tfmoraes** [comment]
I'm using the command from the last comment of kassio and it's working correctly. I'm using neovim from the [unstable PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable)

**Comment by taigacute** [comment]
@tfmoraes  thanks  i will try it

**Comment by tfmoraes** [comment]
@taigacute it worked? just curious ...

**Comment by taigacute** [comment]
@tfmoraes  it works  but the window size  has some problem, i need fix it.
![1](https://user-images.githubusercontent.com/41671631/55007016-aa1de080-5019-11e9-923e-e3eb89f43506.png)
