### ISSUE TITLE
Order results by distance from current file

### ISSUE THREAD

**Issue by rcywongaa** [junegunn/fzf.vim#788]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When using the `:Files` command to search for a file name, the order at which the files appear seem somewhat arbitrary (correct me if I'm wrong).

Is there a way to make the files appear in order of increasing distance from the current opened file? i.e. the first choice (bottom) file should be "nearest" to the current opened file

Thanks in advance!

**Comment by junegunn** [comment]
Can you write a script that generates the list in the desired order?

If so, you can use it as the source to fzf.

```vim
command! BetterFiles call fzf#run(fzf#wrap({'source': 'my-traversal-script '.expand('%:S')}))
```

I haven't tried this, but you might want to check out https://github.com/jonhoo/proximity-sort.
