### ISSUE TITLE
List changed files/files with diffs

### ISSUE THREAD

**Issue by GuillaumeRochat** [junegunn/fzf.vim#790]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is there a way to list only the files that have changes? Considering the GFiles and Commits commands, there is already an integration with git, so could there also be a way to only list files with diffs?

The use case would be to review changes quickly before a commit and do last minute tweaks, instead of going in another shell and back to vim/nvim if last minute tweaks are required.

**EDIT:** I found the vim.fugitive command `:Gstatus` that does something along the lines of what I'm looking for. I can't fuzzy find the filenames but I get the list to review.

**Comment by junegunn** [comment]
`GF?`

**Comment by GuillaumeRochat** [comment]
Ah! I didn't understand that documentation part at all. Thanks!
