### ISSUE TITLE
fzf.vim should use $FZF_DEFAULT_COMMAND

### ISSUE THREAD

**Issue by zackhsi** [junegunn/fzf.vim#80]
fzf.vim should use $FZF_DEFAULT_COMMAND instead of [ag -l -g ''](https://github.com/junegunn/fzf.vim/blob/7ebf708505d2e8313fe44327ecc0920243bef465/plugin/fzf.vim#L118) if it's available.

**Comment by junegunn** [comment]
`:Files` command uses $FZF_DEFAULT_COMMAND if it's defined.

The line you linked is only used for file completion (that is not enabled by default and has to be set up by the user) and is explicitly named `(fzf-complete-file-ag)` so it's no wonder that it's using `ag`.

And for the other ones, the documentation correctly states that they use `find` command.

https://github.com/junegunn/fzf.vim#mappings

If you want to use `$FZF_DEFAULT_COMMAND` for completion, you can directly use `fzf#vim#complete#path()` and pass it as the argument though the function is currently undocumented.

Do you think `<plug>(fzf-complete-file)` should check if `$FZF_DEFAULT_COMMAND` is defined?

**Comment by zackhsi** [comment]
Hmmm, so the problem I'm trying to fix is that :Ag doesn't search all my files because it ignore vcs ignored files. I've overridden $FZF_DEFAULT_COMMAND to pass the -U option to ag, and now it does what I want. I'm having a hard time figuring out what function :Ag hooks up to.

But yes, I think all the [commands that use `find`](https://github.com/junegunn/fzf.vim/blob/7ebf708505d2e8313fe44327ecc0920243bef465/plugin/fzf.vim#L116-L117) should check if ag is installed and the default command has been exported.

**Comment by zackhsi** [comment]
Yeah, where is vim's `:Ag` defined? Here's my [vimrc](https://github.com/zackhsi/dotfiles/blob/master/vimrc#L175)...

**Comment by junegunn** [comment]
$FZF_DEFAULT_COMMAND has nothing to do with `:Ag`, I think you're confused somehow.

For customizing ag options, refer to #76 or #51.

**Comment by zackhsi** [comment]
Thanks, added https://github.com/zackhsi/dotfiles/commit/05ffd17fe957604fa745f787e9e4985dca30a5d4.
