### ISSUE TITLE
Preview window for Tags command

### ISSUE THREAD

**Issue by samiralajmovic** [junegunn/fzf.vim#800]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

How do we enable preview for `Tags` method? I'm currently getting the preview window but it shows a error message `File not found`. Any tips on how to solve it? Currently using:

```
command! -bang -nargs=? -complete=dir Tags
  \ call fzf#vim#tags(<q-args>, fzf#vim#with_preview(), <bang>0)
```

**Comment by junegunn** [comment]
[Preview script](https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh) used by `fzf#vim#with_preview` only works if each line starts with an absolute file path, and that is not the case for `:Tags`. If you can write a custom preview script tailored for tags files, you can use it like so:

```vim
command! -bang -nargs=? -complete=dir Tags
  \ call fzf#vim#tags(<q-args>, {'options': '--preview "my-preview-script-for-tags {}"'}, <bang>0)
```

**Comment by thenewvu** [comment]
To save some time for the rest of the world:

```vim
command! -bang BTags
  \ call fzf#vim#buffer_tags('', {
  \     'down': '40%',
  \     'options': '--with-nth 1 
  \                 --reverse 
  \                 --prompt "> " 
  \                 --preview-window="80%" 
  \                 --preview "tail 
  \                     -n +\$(echo {} | cut -f3 | tr -d \";\\\"\") 
  \                     \$(echo {} | cut -f2)"'
  \ })
```
![Screen Shot 2019-09-21 at 21 18 08](https://user-images.githubusercontent.com/6092585/65374560-6862af80-dcb5-11e9-9bf5-0f53da4ebd69.png)

**Comment by lazamar** [comment]
The preview script has the benefit of highlighting the important line and using the `FZF_PREVIEW_COMMAND` variable.

Here is a setup to use it with the `Tags` command.

``` vim
" Add your path here.
let plugins_dir='path/to/plugins' 

" Send file address and line number to fzf.vim's preview script
let preview_file = plugins_dir . "/fzf.vim/bin/preview.sh"
let show_preview = 'FILE=;LINE=;F={};for word in $F;do if [ -n "$word" ] & [ "$word" -eq "$word" ] 2>/dev/null;then LINE=$word;break;fi;FILE=$word;done;echo $FILE:$LINE | xargs -I {} ' . preview_file . '  {}'

command! -bang -nargs=* Tags
  \ call fzf#vim#tags(<q-args>, {
  \      'down': '40%',
  \      'options': '--with-nth 1
  \                  --preview-window="70%"
  \                  --preview ''' . show_preview . ''''
  \ }, <bang>0)
```

**Comment by fenetikm** [comment]
I've gone with:

```vim
let preview_file = '/Users/mjw/.config/preview/preview.sh'
command! -bang -nargs=* Tags
  \ call fzf#vim#tags(<q-args>, {
  \      'window': 'call FloatingFZF()',
  \      'options': '
  \         --with-nth 1,2
  \         --prompt "=> "
  \         --preview-window="50%"
  \         --preview ''' . preview_file . ' {}'''
  \ }, <bang>0)
```

And my `preview.sh` looks like this:

```bash
#!/usr/bin/env bash

METHOD=$(echo "$1" | cut -f 1)
FILENAME=$(echo "$1" | cut -f 2 | gsed -r 's/\.\./\./g')
LINE=$(echo "$1" | cut -f 5 | gsed -r 's/line://g')
PREV_COMMAND=$FZF_PREVIEW_COMMAND
FZF_PREVIEW_COMMAND="cat {}"
export FZF_PREVIEW_COMMAND
/Users/mjw/.config/nvim/plugged/fzf.vim/bin/preview.sh "$FILENAME":"$LINE"
FZF_PREVIEW_COMMAND=$PREV_COMMAND
export FZF_PREVIEW_COMMAND
```

**Comment by antoniovillavicencio** [comment]
If everyone has problems with these solutions, be sure that you generate your ctags with `--excmd=number`

**Comment by donkeymoto** [comment]
> The preview script has the benefit of highlighting the important line and using the `FZF_PREVIEW_COMMAND` variable.
> 
> Here is a setup to use it with the `Tags` command.
> 
> ```viml
> " Add your path here.
> let plugins_dir='path/to/plugins' 
> let preview_file = plugins_dir . "/fzf.vim/bin/preview.sh"
> 
> command! -bang -nargs=* Tags
>   \ call fzf#vim#tags(<q-args>, {
>   \      'down': '40%',
>   \      'options': '
>   \         --with-nth 1,2
>   \         --preview-window="top:70%"
>   \         --preview ''' . preview_file . ' {2}:$(echo {3} | cut -d ";" -f 1)'''
>   \ }, <bang>0)
> ```

I used your above configuration, and when Tags command was triggered, a preview window may display the correct file, but file number did not work.
My tags file format like below:
xSemaphoreCreateCounting        /path/and/file/name     226;"
I think your script have extracted correct line number. But the preview do not jump to the specific line.

I also test fzf.vim/bin/preview.sh on a terminal:
fzf.vim/bin/preview.sh   foo.txt:50
The result is the same, file displayed, but line dont jump to.

Could you please give me some suggestion on the issue?
thanks.

**Comment by fabriziobertoglio1987** [comment]
@donkeymoto @junegunn I also have the same issue, the preview works (with colors) but not moving to the correct line :cry:

**Comment by junegunn** [comment]
This is an outdated issue. Tag preview is builtin since #1223 and you don't need any customization.

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot. This plugin is amazing ... Really helps me to index this many tags :pray: :heart: 
I can search with fzf.vim tags from:
- android open source project .java methods
- expo project .java methods
- react-native project .java methods
- jetpack .java methods
Really incredible project, in my use case more effective then coc-tsserver or similar language servers that do not allow me to navigate the sourcecode and allways send me to type definition which does not include any info. So I'm thankful and I will try to help with this .. 

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<image src="https://user-images.githubusercontent.com/24992535/112140915-ecf8fb80-8bd4-11eb-8ed1-56f79636427b.png" width="700" height="" />

</p>
</details>

**Comment by donkeymoto** [comment]
Thanks a lot.
This is one of greatest vim plugin I have ever experienced.

**Comment by jessezbj** [comment]
Does scrolling work in the "Tags" command's preview window?

**Comment by junegunn** [comment]
Correct. In order to scroll to a certain line of the preview content, fzf needs to know the exact line number in advance, but each line in "Tags" doesn't have the information.
