### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by dareenzo** [junegunn/fzf.vim#803]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

When searching for files through `:Files` I get duplicate entries, the difference I noticed between them is that some are prefixed with `git` and others with `-`, as seen in the image below:

![Screenshot from 2019-04-23 15-09-32](https://user-images.githubusercontent.com/6130991/56585568-61d4ec80-65de-11e9-97fa-22ab4903f2de.png)

I wish only one entry would show up.

Thanks

**Comment by junegunn** [comment]
You need to fix your `$FZF_DEFAULT_COMMAND`.
