### ISSUE TITLE
rigrep inside fzf#vim#grep treats special symbols as literals

### ISSUE THREAD

**Issue by PovelikinRostislav** [junegunn/fzf.vim#806]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi, 

I'm trying to integrate rigrep into vim using FZF and I've met a problem regarding the patterns.
I want to use full regexp mechanism, but I can't and don't know why.
My config is:
```
command! -bang -nargs=* Find
  \ call fzf#vim#grep('rg --column --line-number --no-heading
  \ --no-fixed-strings --ignore-case --no-ignore --hidden --follow
  \ --glob "!.git/*" --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1,
  \ fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:40%'), <bang>0)
```
and the problem is that classical regexp doesn't work for me.
E.g.:
I want to use a `class.*shared_ptr` regexp to match `class _LIBCPP_TEMPLATE_VIS shared_ptr`.
![image](https://user-images.githubusercontent.com/20692004/56836995-8997af00-6881-11e9-9630-6178a177a5d4.png)
But the Rg understands `.*` as literals:
![image](https://user-images.githubusercontent.com/20692004/56836946-6240e200-6881-11e9-9772-959489f27597.png)

I tried to fix it in rigrep settings and pass `--no-fixed-strings` parameter which is responsible for treating `.` and `*` as literatls, but it didn't work for me.

Thanks in advance

**Comment by junegunn** [comment]
In this case, you are not rerunning ripgrep as you type on fzf. ripgrep process starts only once with the initial query and fzf works as the secondary filter with [its own search syntax](https://github.com/junegunn/fzf#search-syntax).

Try `:File class.*shared_ptr`.
