### ISSUE TITLE
Rg sometimes causes Vim to freeze

### ISSUE THREAD

**Issue by joeltaylor** [junegunn/fzf.vim#807]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim (8.1)
    - [ ] Neovim

I've recently switiched my setup to use Rg instead of Ag and occasionally run into Vim freezing up for close to a minute. I've been able to reproduce this bug in a local project using the minimal configuration by following these steps:

- vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
- :Rg some_regex_for_a_file
- Enter to select file
- Vim freezes

Here's the profile log: https://gist.github.com/joeltaylor/c3edc7bd974ab98898ea38ff7dcd732f

And here's a relevant snippet:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1  81.112117   0.000102  fzf#vim#grep()
    1  81.112015   0.000077  <SNR>26_fzf()
    1  81.111401   0.000429  fzf#run()
    1  80.958798   0.002345  <SNR>11_execute()
    1   0.151906   0.000083  <SNR>11_callback()
    1   0.151660   0.000211  <SNR>26_ag_handler()
    1   0.151378   0.002606  <SNR>26_open()
```

It appears like this may be due to `return fzf#run(s:wrap(a:name, merged, bang))` but I'm not certain. 

If this seems more like a RipGrep issue I'm happy to close this and pursue that route.

**Comment by keis** [comment]
I've started to see the same thing after an upgrade of my system (to fedora 30), or at least something very similar. if I pick something with fzf while it's still loading the output of the rg command it freezes for a while (until it finishes).

This is on neovim 0.3.4

**Comment by junegunn** [comment]
Does `rg SOME_REGEX | head -1` command (outside of vim) finish immediately?

**Comment by joeltaylor** [comment]
@junegunn yeah, it finishes up immediately for me. 

I know this sort of bug is difficult to debug. My vimscript isn't too strong, but I'll be digging into what may be going on if you have any pointers.

**Comment by junegunn** [comment]
Hmm okay, can you reproduce the delay outside of vim? (`rg SOME_REGEX | fzf` and select one)

**Comment by joeltaylor** [comment]
@junegunn Nope, that's also a fairly snappy command.

**Comment by joeltaylor** [comment]
What's interesting is that it's a project specific bug for me and only happens in one repository. Going to see if I can add some logging to see if it's getting stuck in some loop or something.

**Comment by keis** [comment]
same for me fwiw with both pipe to head and fzf returning quickly. Is the behaviour you are seeing a complete freeze or does it return eventually?

**Comment by joeltaylor** [comment]
@keis Mine freezes for over a minute but eventually comes around.

**Comment by fabiomcosta** [comment]
@joeltaylor I've noticed the same thing.
For me when I was running the `:Rg` command provided by fzf.vim it was taking about 4 seconds to start showing me any results.

I noticed that this doesn't happen when I run rg + fzf on the command line, so my guess was that `fzf#vim#grep()` was the reason.

I managed to create my own `:Rg` command by adding the following on my vimrc:

```viml
function! s:open(cmd, target)
  if stridx('edit', a:cmd) == 0 && fnamemodify(a:target, ':p') ==# expand('%:p')
    return
  endif
  execute a:cmd fnameescape(a:target)
endfunction

function! s:fzf_rg_to_qf(line)
  let parts = split(a:line, '[^:]\zs:\ze[^:]')
  let text = join(parts[3:], ':')
  let dict = {'filename': &acd ? fnamemodify(parts[0], ':p') : parts[0], 'lnum': parts[1], 'text': text}
  let dict.col = parts[2]
  return dict
endfunction

function! s:fzf_rg_handler(lines)
  let list = map(filter(a:lines, 'len(v:val)'), 's:fzf_rg_to_qf(v:val)')
  if empty(list)
    return
  endif
  let first = list[0]
  call s:open('e', first.filename)
  execute first.lnum
  execute 'normal!' first.col.'|'
  normal! zz
endfunction

" Adds Rg command to search on file content, with a nice preview window to the right.
" command! -bang -nargs=* Rgc call fzf#vim#grep('rg --column --line-number --no-heading --color=never --smart-case '.shellescape(<q-args>), 1, fzf#vim#with_preview({'options': '--exact --delimiter : --nth 4..'}, 'right:50%'), <bang>0)
command! -bang -nargs=* Rg call  fzf#run(fzf#wrap(fzf#vim#with_preview({'source': 'rg --column --line-number --no-heading --color=never --smart-case '.shellescape(<q-args>), 'options': '--exact --delimiter : --nth 4..', 'sink*': function('s:fzf_rg_handler') }, 'right:50%')))
```

It shows results instantaneously on my current ~2k files project even without an initial string to filter from.

**Comment by alvaroclementev** [comment]
I've had this exact same behavior for some time, and just stumbled upon this issue.
After using the method described by @joeltaylor in the original post for minimal set of repro steps:
> I've recently switched my setup to use Rg instead of Ag and occasionally run into Vim freezing up for close to a minute. I've been able to reproduce this bug in a local project using the minimal configuration by following these steps:

> -  vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
> - :Rg some_regex_for_a_file
> -  Enter to select file
> -  Vim freezes

I realized that I couldn't repro with that setup. 
Turns out that updating FZF (the binary, not the plugin) manually using git solved the issue for me.

I haven't seen any direct mention to this issue being solved in any of the updates, but maybe that's something worth trying if you still have the issue.

**Comment by joeltaylor** [comment]
Issues seems to have resolved with updated binary for me as well.
