### ISSUE TITLE
Keep search result window open

### ISSUE THREAD

**Issue by comatory** [junegunn/fzf.vim#808]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

This plugin in combination with FZF is very quick. However the actual usability once I get the result is not so great. It would be neat if we could keep the search window opened while switching to new tab or window, or at least have an ability to "dock" it somewhere.

I've read about the trick with quickfix window. I see few issues with this:

- on MacOS, the shortcut ALT+A does not work unless you set up the terminal correctly
- even when you do select all results and open them in quickfix window, in my codebase I'm basically moving 6000 search results for a single term and recreating them in new window. This takes up around 1 or 2 seconds for quickfix window to appear, not so quick

Also the navigation in the search window does not work great  for me. I can't use CTRL+U or CTRL+D to move between pages, instead I have to rely on PgUp, PgD, Home and End which are under modifier keys on my keyboard.

There is other stuff, like I haven't figured out how to paste from buffer into search window etc.

**Comment by atsman** [comment]
I would love to be able to keep the search window open and be able to jump between the opened file and search buffer. 

Are there any options right now ?

**Comment by pgib** [comment]
Would also love this. When I need to find a bunch of files to update, it's easier if I don't have to search again for each matching file I want to open.

**Comment by eL0ck** [comment]
The author talks about this in a number of other issues. The difficulty is in taking input into fzf for further search term refinement.   

The intended usage is to 1) Start the fuzzy search, 2) continue to refine the list of results 3) select the results to take to quickfix (select individual with TAB or select all) then finally 4) Hit ENTER to populate the quickfix with the list.

I find it to work excellently as is.

**Comment by comatory** [comment]
Yes I've read somewhere else that it's difficult or maybe even impossible to implement this. But I wanted to bring up the point specifically.
It works well for me as well, it's very quick and easy to use. However if you read my first post, you can get the idea why your approach does not work well for me.

**Comment by comatory** [comment]
Maybe what would make this a bit more usable would be to invoke fzf with previous search term if I close the window. Maybe this could be already done with some scripting and assigning it to a shortcut. (Downside is it won't remember the position of the selection)

**Comment by pgib** [comment]
> The intended usage is to 1) Start the fuzzy search, 2) continue to refine the list of results 3) select the results to take to quickfix (select individual with TAB or select all) then finally 4) Hit ENTER to populate the quickfix with the list.

I didn't realize you can tag matches and open in bulk. That's perfect! 🙏

**Comment by atsman** [comment]
@eL0ck thank you for an explanation!

**Comment by NullVoxPopuli** [comment]
is there a way to keep the search results for a `:Files` or `:Ag` search?

**Comment by junegunn** [comment]
fzf is an external terminal program rather than a native Vim plugin, so **there is no direct way for Vim to communicate with it while having it open**. While there might be some creative ways (hacks) to workaround the limitation, I'd just say that this is not the kind of job fzf can do well. You might want to look for some native Vim plugins that are particularly designed for this kind of requirement.

**Comment by TamaMcGlinn** [comment]
For non-fuzzy searches, the [Cntrlsf plugin](https://github.com/dyng/ctrlsf.vim) fills this need; it creates its own buffer type and communicates with Ag, allowing very fast project searches; editing inside the search results buffer and then saving it will write to all the files affected. Since it's a regular buffer, you can move it around, keep it open, open several of them, etc.

**Comment by obaranovskyi** [comment]
> For non-fuzzy searches, the [Cntrlsf plugin](https://github.com/dyng/ctrlsf.vim) fills this need; it creates its own buffer type and communicates with Ag, allowing very fast project searches; editing inside the search results buffer and then saving it will write to all the files affected. Since it's a regular buffer, you can move it around, keep it open, open several of them, etc.

Works great, thanks!
