### ISSUE TITLE
<plug>(fzf-complete-file-ag) wrong insertion

### ISSUE THREAD

**Issue by vbauerster** [junegunn/fzf.vim#81]
I've following mapping:
```imap <c-z><c-p> <plug>(fzf-complete-file-ag)```

Below pipe character '|' denotes cursor position
"|"
After invoking the map, the result is:
some-file.txt""
Expected result:
"some-file.txt"

Please, advice if it is expected behaviour?

**Comment by junegunn** [comment]
It was a bug. Please update and let me know if it's fixed. Thanks.

**Comment by vbauerster** [comment]
Yes, it is working now. Thanks!
