### ISSUE TITLE
[Question] How to add my own autoload function?

### ISSUE THREAD

**Issue by TC72** [junegunn/fzf.vim#817]
I've modified the History command so it only shows files under the current directory. First I made a modified version of the s:all_files function:
```
function! s:all_files_cwd()
  let current_file=filter([expand('%')], 'len(v:val)')
  let alternate_file=filter([expand('#')], 'len(v:val)')
  let buffers_list=filter(map(s:buflisted_sorted(), 'bufname(v:val)'), 'len(v:val)')
  let buffers_list_fullpath=map(copy(buffers_list),'fnamemodify(v:val, ":p")')
  let readable_buffers_list=filter(copy(buffers_list_fullpath),"filereadable(v:val)")
  let filtered_buffers_list=filter(copy(readable_buffers_list),'v:val =~ getcwd()')
  let oldfile_list=filter(filter(copy(v:oldfiles), "filereadable(fnamemodify(v:val, ':p'))"), 'v:val =~ getcwd()')
  let full_list = current_file + alternate_file + filtered_buffers_list + oldfile_list
  return fzf#vim#_uniq(map( full_list, 'fnamemodify(v:val, ":~:.")'))
endfunction
```
I've probably gone over the top with the variables, but I found it easier to understand what's happening. I also added the alternate file as the first item you can switch to. I have this command tied to \\?, so I can just type \\?return to switch files quickly.

I wrote a new function to use this called fzf#vim#history_cwd(), cwd for current working directory, very similar to fzf#vim#history:
```
function! fzf#vim#history_cwd(...)
  return s:fzf('history-cwd', {
  \ 'source':  s:all_files_cwd(),
  \ 'options': ['-m', '--header-lines', !empty(expand('%')), '--prompt', fnamemodify(getcwd(), ':t') . '> ']
  \}, a:000)
endfunction

```
Finally I edited plugin/fzf.vim to add another else statement so my function is called using 'History;':
```
  elseif a:arg[0] == ';'
    call fzf#vim#history_cwd(bang)
```

How can I add this to my own setup without adding it to files in fzf.vim which will be overwritten when it gets updated? I know this may be a simple thing to fix but after 30 years of using vi I just decided to try writing some vimscript ;-)

**Comment by junegunn** [comment]
You don't have to define autoload functions to implement your own command. You just need to know how to use `fzf#run` function. Please read through `fzf#run` and `fzf#wrap` sections in README-VIM.md.

- https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

```vim
function! s:all_files_cwd()
  " Put your implementation here
  return [1, 2, 3]
endfunction

call fzf#run(fzf#wrap('history-cwd', {'source': s:all_files_cwd(), 'options': ['--prompt', 'HistCwd> ']}))
```
