### ISSUE TITLE
Helptags does not respect default actions

### ISSUE THREAD

**Issue by adaszko** [junegunn/fzf.vim#818]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [X] macOS
    - [X] Windows
    - [X] Etc.
- Vim
    - [X] Vim
    - [X] Neovim

Thanks for a lovely Vim plugin!

The issue is that keys like CTRL-V, CTRL-T, CTRL-S do are not usable with `:Helptags`.  As far as I can see in the implementation, they're not handled https://github.com/junegunn/fzf.vim/blob/5c87ab86c0e7b0ec8a5edd39a4ce5500bb9e9333/autoload/fzf/vim.vim#L991-L1008

**Comment by junegunn** [comment]
`Helptags` command simply executes `:help foo` to open help window. The split keys are not supported.

**Comment by AlxHnr** [comment]
Why can't those be added? That would make it consistent with other commands like `:Tags`.

`:help ...` itself can be prefixed by `:vertical` and `:horizontal`.

**Comment by junegunn** [comment]
Pull requests welcome.
