### ISSUE TITLE
Preview does not work on Windows

### ISSUE THREAD

**Issue by ribtoks** [junegunn/fzf.vim#822]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I'm trying to configure fzf.vim on Windows 10. Currently preview of search results produces an error "bash is not recognized as an internal or external command ...". I understand that `bash` is not in `PATH` on Windows, but can that be somehow worked around or fixed?

**Comment by ribtoks** [comment]
So far I hacked it like this `let s:bin.preview = escape('c:\PROGRA~1\Git\bin\bash.exe', '\').' '.escape(s:bin.preview, '\')` in file `vim.vim` but I truly hope there's a better way.

**Comment by janlazo** [comment]
You can set `PATH` in a powershell profile, registry via `setx` binary, or the control panel. Powershell profile is easiest if you can live with spawning powershell to run git and bash from `PATH`.

**Comment by MartyLake** [comment]
For future me that still find the error after a spurious reinstall of my system, @ribtoks tip works very good, thanks a lot !
