### ISSUE TITLE
With :Rg the column number of all results is always 1 

### ISSUE THREAD

**Issue by desmap** [junegunn/fzf.vim#824]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

- fzf, v8
- tested on minimal version
- rg is installed

When using :Rg the column number for all results is always 1, in the quicklist it's always 1 and when going to the results it stays at 1 despite results are not at column number 1
Edit: I just tested :Ag as well and shows the same behavior.

**Comment by junegunn** [comment]
`:Rg` or `:Ag` commands are designed to be used with a query string. i.e. `:Rg foo`

If you don't pass one, the underlying rg or ag process will match the beginning of every line, hence column number 1, and fzf will simply filter through that static list.

fzf is like grep, it's a text filter. rg starts only once at the beginning. fzf, in this case, works as the secondary filter. It doesn't dynamically restart rg process.

```sh
# The query you type in on fzf finder doesn't affect the initial result produced by rg process
rg --column --line-number foo | fzf
```

**Comment by desmap** [comment]
This means if space maps to Rg:, after hitting space, rg gives fzf all lines of all files and fzf greps through all given lines? And fzf can't get column numbers because grep doesn't provide them right?

So, there is no way to get column numbers through an mapping?!

And this means, that with a mapping FZF or actually grep is doing the search and not ag or rg, right?

**Comment by junegunn** [comment]
> And this means, that with a mapping fzf or actually grep is doing the search and not ag or rg, right?

I didn't say that fzf is grep, or it uses grep. What I meant is that fzf is in the same category as grep, that it's a simple text filter. Text in, text out.

And yes, if you do that, ag and rg will just dump out all lines in all files, which is unfortunate because you're not taking advantage of true powers of them. Unlike ag or rg, fzf, being an interactive program, has to keep every line in memory to be able to deal with changing user input. And this can be pretty inefficient if there are millions of lines.

There are mappings I use; search for the word under the cursor, or string currently selected.

```vim
nnoremap <silent> <Leader>ag       :Ag <C-R><C-W><CR>
xnoremap <silent> <Leader>ag       y:Ag <C-R>"<CR>
```

**Comment by desmap** [comment]
@junegunn ok, now I get it, thx. Yesterday, I was going crazy on Reddit because I thought I found the god mapping for fast navigation through code with many uses cases mapped to just one key: https://www.reddit.com/r/vim/comments/bxrhds/today_i_was_heavily_procrastinating_and_found/

But with this background in mind, my Reddit post doesn't make sense at all. I mean for small code bases it seems to work well but still.

However, from an architectural perspective it's impossible to have an interactive fzf-finder-like interface to a grep entity like rg? Could fzf or rg could be bend to get into this direction? Or do I need to get some proper full-text-search like Algolia on-board with constant index generation? 

From an UI-perspective (check the use cases I outlined in the Reddit post), this tap-to-go-anywhere would be a key UI feature and I just wondering how this could be technically tackled.

Do you have any ideas?

**Comment by junegunn** [comment]
> I mean for small code bases it seems to work well but still.

You should have no issue for small to medium sized projects with that approach. fzf can easily handle millions of entries. So if it works for most of the projects you work on, and you like the approach, then why not.

fzf has its [own search syntax](https://github.com/junegunn/fzf#search-syntax) which is not compatible to the regular expression ripgrep takes as the argument. So passing fzf query directly to ripgrep doesn't make much sense. And if we do that, fzf degenerates to an interactive UI program without actual search functionality, and fzf, a Unix filter, was not designed for that purpose.

I don't see how providing an initial search query to `:Ag` or `:Rg` is a big problem. We use those commands to search for some string we already have in mind. The only difference is that you type in the keyword before starting fzf.

```vim
" Just press enter or type in an initial query and press enter
nnoremap <space> :Rg<space>
```

Having said that, I actually experimented with the idea a couple of years ago, not by changing fzf implementation, but by writing a script that repeatedly restarts ag and fzf. I've never used it as I don't see much point, but you can find it here:
https://gist.github.com/junegunn/4963bab6ace453f7f529d2d0e01b1d85

**Comment by desmap** [comment]
@junegunn I tried your suggested `<space> :Rg<space>` mapping and while it does deliver it doesn't feel as satisfying as getting right away into fzf-finder and you need one enter press more. BUT I took your ag-change script, changed it to rg and it's AWESOME. Check it yourself: https://gist.github.com/desmap/b81e526728465f2d8e08fb5cab1d9e2f

All three solutions compared re responsiveness, tested with a folder with dozen sub-projects:

1. **FZF only:** highest responsiveness, instant, no flicker (but no grep of course)
2. **FZF with an empty :Rg search in neovim (my Reddit-mapping):** no flicker, no lag when typing but results need a bit, no flicker
3. **ag-change:** fast, but typing is slightly laggy, distinct flicker
4. **rg-change:** fast, responsive, typing feels lag-free, slight flicker, this is def. slower than 1 but I have the feeling it's faster than 2 and 3; it feels quite good tbh

What do you think, I could totally live with rg-change. Or are there any drawbacks with some edge cases?

Moreover, just thought about writing an integration for rg-change into neovim, so I checked how fzf.vim's codebase integrates fzf: Do I really need all that stuff or could I just open a terminal window and run the rg-change?

**Comment by junegunn** [comment]
@desmap 

Rerunning ripgrep without restarting fzf is not possible with the new `reload` action. See

- https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration
- https://github.com/junegunn/fzf/issues/1750
