### ISSUE TITLE
Including `--column` in custom rg search causes results to run as vim commands

### ISSUE THREAD

**Issue by JediLuke** [junegunn/fzf.vim#825]
- Category
    - [ ] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim

When I have this custom fzf search:

`command! -bang -nargs=* FzfFind call fzf#vim#grep( 'rg --line-number --no-heading --fixed-strings --ignore-case --hidden --follow --color "always" '.shellescape(<q-args>), 1, fzf#vim#with_preview(), <bang>0)`

My search displays a strange behaviour. The search part works as normal, but when I press enter instead of just going to the line in the file it seems to trigger the letters in the result as vim commands. If I find a string that starts with `Logger.info "blah"`, I will see

`gger.info "blah blah"|`

at the end of my file. The first 2 letters - `L` goes to last line of file, and then `o` opens a new line, then the rest of the text gets typed in. I dont know where the `|` at the end is coming from.

Through trial and error I have isolated that including `--column` in the string makes the error go away and the search behave as it should. All seems to work fine with this command

`command! -bang -nargs=* FzfFind call fzf#vim#grep( 'rg --column --line-number --no-heading --fixed-strings --ignore-case --hidden --follow --color "always" '.shellescape(<q-args>), 1, fzf#vim#with_preview(), <bang>0)`

Can confirm this is happening with latest fzf & latest ripgrep `ripgrep-11.0.1.high_sierra.bottle.tar.gz`

**Comment by junegunn** [comment]
This is the function signature of `fzf#vim#grep`:
```vim
fzf#vim#grep(command, with_column, [options], [fullscreen])
```
And you should set `with_column` to `1` or `0` depending on your command.
