### ISSUE TITLE
Suffix-exact-match not working with Rg

### ISSUE THREAD

**Issue by sansbrina** [junegunn/fzf.vim#827]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim (v0.3.7)

### Reproduction steps
1. Search `:Rg <Pattern>`
2. Attempt to filter the result based on file suffix. 
  - This was mostly tested with ruby files, so an example is `.rb$` which filtered everything out. It was reproduced with different file extensions, and it looks as though all of the other [search syntaxes](https://github.com/junegunn/fzf#search-syntax) work as expected.

Running `:Files` command doesn't have this issue, nor does using fzf in the terminal with ripgrep.

**Comment by junegunn** [comment]
`$` matches the end of a line, but `.rb` is not at the end.

```
foo_bar.rb:100:200:  def foo
```

So, in this case, you might want to type in `.rb:` instead.
