### ISSUE TITLE
Any Options list of `with_preview` ?

### ISSUE THREAD

**Issue by kamillle** [junegunn/fzf.vim#828]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

---
Let me ask a question.
Do you have a list that teach me how to use `with_preview's` options, if so give me that link.

**Comment by vedantroy** [comment]
Where is `with_preview`? I would like to have a code preview window for my search results, but I was not aware that was a feature of fzf.vim

**Comment by kamillle** [comment]
For instance, like this code. this is in my toml file. 
https://github.com/kamillle/dotfiles/blob/bc334b2a037531d9ef9515500e70c8b5d68b9296/neovim/toml/lazy.toml#L118. 
Is This function not from fzf.vim?

**Comment by henrebotha** [comment]
It's mentioned in the source:
```
[[options to wrap], [preview window expression], [toggle-preview keys...]]
```
The code will take a map of options and return a map of options. For instance, if I call it as `fzf#vim#with_preview({'options': ['+m'], 'source': 'foo'})` I get this:
```
{'options': ['+m', '--preview-window', 'right', '--preview', '''/home/hbotha/.vim/plugged/fzf.vim/bin/preview.sh'' {}'], 'source': 'foo'}
```
But I'm not sure what "preview window expression" is. "Toggle-preview keys" is clearly the key combinations you want to use to turn the preview on & off.

**Comment by junegunn** [comment]
> But I'm not sure what "preview window expression" is.

See the description of `--preview-window` in the man page (`man fzf`).
