### ISSUE TITLE
:Buffers scrolling

### ISSUE THREAD

**Issue by rishindoshi** [junegunn/fzf.vim#829]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi! I can't seem to figure out how to navigate the list of buffers that's created when executing :Buffers inside vim. I keep wanting to scroll through the options like I can when running :Files

**Comment by junegunn** [comment]
You can navigate the list just fine. The only difference is that the first item, which is the current buffer,  cannot be selected, because selecting it is pointless.
