### ISSUE TITLE
Overriding the Ag command

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf.vim#83]
First, thanks so much for all your Vim work. It improved my Vim experience a lot!

I use `Ag` a lot to search for snippets of code in my codebase and I don't like the `Ag` command behaviour and the fact that I can't pass CLI options to it so how I can disable/override it to use the normal `Ag` command?

**Comment by junegunn** [comment]
> use the normal Ag command?
What is "normal Ag" command?

**Comment by junegunn** [comment]
If it means Ag command from another plugin, and you use plugin managers like vim-plug, you can adjust the order of `Plug` lines of two plugins so that one is loaded after the another.

**Comment by ahmedelgabri** [comment]
I have `ag.vim` installed but when I run `:Ag --js "foo"` in the command line it opens fzf Ag window (with zero results) because we can't pass arguments, which is not what I want.

And if simply I tried to do `:Ag<cr>` in the command line it opens fzf Ag window to type and filter stuff, which is also not what I want. 

I want `:Ag` to run using `ag.vim` not `fzf.vim`

**Comment by junegunn** [comment]
Okay, then I already answered your question.

**Comment by ahmedelgabri** [comment]
```viml
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install --all' }
Plug 'junegunn/fzf.vim'
Plug 'rking/ag.vim', { 'on':  ['Ag'] } " this was the problem, lazy loading it.
```

When I removed the `{ 'on':  ['Ag'] }` it worked. Thanks

**Comment by junegunn** [comment]
Yeah, in this case `:Ag` command vim-plug set up for loading ag.vim is overwritten by the one from fzf.vim because plugins are loaded after vimrc.

**Comment by benhartley** [comment]
Sorry to bump an old thread but this issue is one of the first search results and this might help other people who have a similar issue.

I got around the same issue using:

``` VimL
let g:fzf_command_prefix = 'Fzf'
```

So then FZF Ag behaviour is still available using `:FzfAg` and ag.vim uses the normal `:Ag`
