### ISSUE TITLE
Toggling fzf default command

### ISSUE THREAD

**Issue by amiralies** [junegunn/fzf.vim#830]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Im using `ag` as defaut fzf command to respet gitignore, but i want it to apply only on my ctrlp map not `:Files` or `:GFiles`
so im doing something like this
```vim
function Ctrlp()
        let $FZF_DEFAULT_COMMAND = 'ag -g ""'
        :FZF
        let $FZF_DEFAULT_COMMAND = ''
endfunction
nnoremap <C-p> :call Ctrlp()<CR>
```
Does it have any effect on performance? is there a better way to achive this behaviour?

**Comment by junegunn** [comment]
Instead of using the environment variable, you can pass the command directly to `fzf#run` function like so:

```vim
call fzf#run(fzf#wrap({'source': 'ag -g ""'}))
```

See https://github.com/junegunn/fzf/blob/master/README-VIM.md for details.
