### ISSUE TITLE
Feature request: support find next

### ISSUE THREAD

**Issue by eyalk5** [junegunn/fzf.vim#832]
- Category
    - [ ] Question
    - [ ] Bug
    - [X] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

It would be nice to have `n` act as to bring the next candidate for the search,just like in usual search. I use BLines for searching by default. At least to have the last search string updated.

```
      let @/ = search_exp 
        call histadd('search', search_exp)
```

**Comment by desmap** [comment]
BLines is awesome and yeah, it would be great to get n and p supported.

**Comment by junegunn** [comment]
Thanks for the suggestion, but the search syntax of fzf is not compatible with that of Vim. Setting `@/` to `^foo fzzy 'exact bar$ !baz` doesn't really make sense.
