### ISSUE TITLE
how to pass arguments to ripgrep

### ISSUE THREAD

**Issue by rezzovskij** [junegunn/fzf.vim#838]
- Category
    - [ ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Rg user_id -tjs  ---- this does not work

**Comment by junegunn** [comment]
You can define your own version of the command using the underlying `fzf#vim#grep` function. The following example removes `shellescape` around `<q-args>` so that each argument are passed directly to rg process.

```vim
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".<q-args>, 1, <bang>0)
```

**Comment by PovelikinRostislav** [comment]
@junegunn, I'm wondering if there's a way to do similar thing for advanced version of ripgrep usage [here](https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration). I see that you have set there ` rg -- %s` to take only the query and do not allow any flags. Note, other people also ask about passing additional arguments to query, e.g. [here](https://github.com/junegunn/fzf.vim/issues/596#issuecomment-620016183)

I have tried to do a lot of stuff with the initial one definition of this function, but I stuck with `{q}` expansion. fzf gives single quoted string as `{q}`, thus additional options would be escaped too and mean a little bit different.
E.g. passing `mxm\( -g '*.hpp'` is going to expand into `'mxm\( -g '\''*.hpp'\'''`

By the way, I tried to apply vim function `strtrans()` to translate the query from literal to ordinary string. But I didn't get where to apply this function from the execution flow perspective. Also tried to apply bash function in the final command like `$(echo({q}))` but I see that this is not really a bash command executed by fzf.

How do you see the solution?
What about `{Q}` option which returns pure query which user actually typed in?

**Comment by hovissimo** [comment]
@junegunn Your whole fzf-vim project and this issue response in particular is dragging me kicking and screaming into a deeper understanding of Vim internals and I love it.

**Comment by s-u-d-o-e-r** [comment]
@PovelikinRostislav  have you found some solution?

**Comment by seanmorton-afs** [comment]
FYI if anyone noticed they lost their preview window after the suggested change here, you need to add back the preview function in the second argument to `fzf#vim#grep`:
```
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".<q-args>, fzf#vim#with_preview(), <bang>0)
```

I figured this out by looking at the default `Rg` function from the `:command` output.
