### ISSUE TITLE
Search for files in a root directory that is relative to the location of the active buffer.

### ISSUE THREAD

**Issue by vedantroy** [junegunn/fzf.vim#840]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
   - All
- Vim
    - [X ] Vim
    - [X ] Neovim

This code segment https://github.com/junegunn/fzf/issues/369#issuecomment-146053423 allows fzf to search for files in a root directory relative to the current working directory.

Would it be possible to modify this code segment to search for files in a root directory relative to the directory of the currently active buffer? This is what CtrlP does.

I tried modifying the call to `finddir` to: `let dir = finddir(vcs.'/..', expand('%').';')`, in order to start at the location of the currently active buffer, but that just breaks the entire thing.

**Comment by vedantroy** [comment]
Turns out the solution is:

```
function! s:find_root()
  for vcs in ['.git', '.svn', '.hg']
    let dir = finddir(vcs.'/..', expand('%').';')
    if !empty(dir)
      execute 'FZF' dir
      return
    endif
  endfor
  FZF
endfunction
```

**Comment by vedantroy** [comment]
I needed to modify the `finddir` call to `let dir = finddir(vcs.'/..', expand('%:p:h').';')`

**Comment by SamHH** [comment]
For anyone who finds this later and wants to be able to search for files with fzf from the directory of the active buffer, [here's](https://github.com/SamHH/dotfiles/commit/18974da75e155d8360e8ed52829d3196a88c1961) how I did it.
