### ISSUE TITLE
shooting star: colorscheme preview

### ISSUE THREAD

**Issue by teto** [junegunn/fzf.vim#843]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion

This is a bit of a shooting star but it would be cool if in `:Colors`, the currently selected colorscheme would be loaded. On cancelling, the original one would be reloaded.

**Comment by wimstefan** [comment]
I was about to open an issue for exactly this suggestion!
Thanks for having done that already :)
Are there any updates yet?

**Comment by teto** [comment]
not from me, I was waiting for a stupid dancer to do it :D 
but seriously I am not sure how it would work: one could launch a job that reads the line where the cursor is positioned after the events CursorHold / CursorMoved. Seems a tad complex.

**Comment by wimstefan** [comment]
Yes - certainly too complex for me ;-)
I hope there's a brighter mind outside that finds interest in that idea.

**Comment by joecabezas** [comment]
what a coincidence I wanted this behavior last night and see this now, I will try to code it and make my first contribution :)

**Comment by teto** [comment]
@joecabezas did your test prove successful :p ?
