### ISSUE TITLE
How can I navigate back a folder when executing FZF inside vim? 

### ISSUE THREAD

**Issue by alexmeise** [junegunn/fzf.vim#845]
- Category
    - [ X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X ] Vim
    - [ ] Neovim

<!--
How can I navigate back a folder when I execute fzf inside vim. 

For example I have open a vertical split with :vs and then hit ";" (map ; :Files<CR>)

If I started vim for example inside my home folder ... How can I open a file that is at a lower level? for example inside /etc/ .. is there any shortcut to navigate back? 
THanks!

**Comment by alexmeise** [comment]
I have a map ; :Files<CR>

I open vim in my home folder and hit ;
How can I open something that is in a lower level folder (for example /etc/) 

Is there any shortcut for navigation down folders? 

Thanks.

**Comment by junegunn** [comment]
> Is there any shortcut for navigatind up/down folders?

No. You can pass a directory to `:Files` command. `:Files /etc`
