### ISSUE TITLE
Error when installing with VimPlug

### ISSUE THREAD

**Issue by krisleech** [junegunn/fzf.vim#85]
I installed fzf with `brew`. In `init.vim` (NeoVim lastest HEAD) I have:

```
Plug 'junegunn/fzf', { 'dir': '/usr/local/opt/fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
```

On doing `:PluginInstall` I get:

```
x fzf:
Invalid URI: https://github.com/Homebrew/homebrew.git
Expected:    https://github.com/junegunn/fzf.git
PlugClean required.
```

Do the entries in `init.vim` look correct?

**Comment by netei** [comment]
This happens when for some reason, the git repository was not cloned properly (it usually happens on my machines when I'm behind a proxy).

Make sure that you have your proxies correctly configured, then open vim, and run `:PlugClean`, and then, `:PlugInstall`

**Comment by junegunn** [comment]
### Option 1

Use vim-plug to install both fzf *and* fzf.vim.

```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
```

Then you don't want to keep fzf from homebrew, `brew uninstall fzf`

### Option 2

Use homebrew to install fzf, vim-plug to install fzf.vim.

```vim
set rtp+=/usr/local/opt/fzf
Plug 'junegunn/fzf.vim'
```
