### ISSUE TITLE
Keyboard scrolling for :Commits and :BCommits

### ISSUE THREAD

**Issue by narimiran** [junegunn/fzf.vim#851]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

If this is already possible, I didn't find the way to do it:
When selecting a commit in `:Commits` or `:BCommits`, is there a way to scroll the diff preview with the keyboard? Scrolling with mouse is slow (it doesn't use my `map <ScrollWheelDown> 12<C-E>` setting) and impractical.

If it is not yet possible, then this is a feature request for that.

(I've seen other issues, like https://github.com/junegunn/fzf.vim/issues/802 and https://github.com/junegunn/fzf.vim/issues/482, which would put the current file in `:BCommits` at the top, which would also help with reducing the need for scrolling)

**Comment by junegunn** [comment]
You can set up an appropriate `--bind` option (e.g. preview-down, preview-up, etc) in your `FZF_DEFAULT_OPTS`. See `man fzf` for details.

**Comment by narimiran** [comment]
If somebody else stumbles on this issue: I just realized there already exist `shift+down` and `shift+up` for `preview-down` and `preview-up` respectively.
