### ISSUE TITLE
Remapping to open quickfix candidate with o

### ISSUE THREAD

**Issue by kyoz** [junegunn/fzf.vim#854]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

===

Is there a way i can use <kbd>o</kbd> to open cadidates in quickfix window (instead of <kbd>enter</kbd>

**Comment by kyoz** [comment]
For now i have to map this
```vim
autocmd BufReadPost quickfix nnoremap <buffer> o <CR>
```

**Comment by junegunn** [comment]
Seems unrelated to fzf.vim.
