### ISSUE TITLE
Scrolling `:GFiles?`

### ISSUE THREAD

**Issue by Integralist** [junegunn/fzf.vim#857]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I understand `:GFiles?` to be the equivalent of previewing `git status` but I'm not sure how to scroll the preview window, as the preview window shows there are multiple lines (e.g. `1/283` << see below screenshot image), but I can't view the truncated lines of the preview window. 

Should it not be possible to scroll through the preview window or not?

![Screenshot 2019-08-13 at 12 19 23](https://user-images.githubusercontent.com/180050/62937469-a4f0e080-bdc4-11e9-9522-c6781953fb0a.png)

**Comment by junegunn** [comment]
1. You can use your mouse wheel to scroll the area.
2. Shift-up and shift-down are bound to `preview-up` and `preview-down` by default. See `KEY BINDINGS` section of man page for details.

**Comment by Integralist** [comment]
OK Cool. I mean the mouse scroll works but pressing Shift with either the up or down arrow doesn't work and I'm not overriding the defaults so maybe there's an OS/implentation bug there?

I tried it using fzf from outside of vim...

```
bind -x '"\C-f": fzf --preview="cat {}" --preview-window=top:50%:wrap | pbcopy'
```

Which is a binding I have for doing `<Ctrl-f>` and letting me preview a file I'm searching for and copying its path.

But adding `--bind=shift-down:preview-down` didnt' change the behaviour (I could still only scroll by mouse)
