### ISSUE TITLE
Automatic Columns

### ISSUE THREAD

**Issue by bigH** [junegunn/fzf.vim#859]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I recently installed [fzf-tags](https://github.com/zackhsi/fzf-tags) and was pleasantly surprised by the columnized output. I find myself wanting that as an fzf.vim feature when I'm building custom fuzzy-finding especially if there are clearly defined columns (e.g. tab-separated).

Can `fzf#...` methods provide a declarative way to configure columnization of the displayed data?

**Comment by junegunn** [comment]
`fzf#run` only provides low-level fzf integration. Formatting of the input should be done by the user.

To learn more about `fzf#run` and `fzf#wrap`, see https://github.com/junegunn/fzf/blob/master/README-VIM.md
