### ISSUE TITLE
Lines command doesn't search in multiple buffers

### ISSUE THREAD

**Issue by pdavydov108** [junegunn/fzf.vim#86]
Hello @junegunn ! Thanks for brilliant fzf tool and this awesome plugin. I have a small issue with ':Lines' command. If I understand the README correctly, it is supposed to search lines in buffers that are now openned, so it is similar to ctrlp's 'lines' mode. However, it doesn't work for me this way. For example, I open two buffers, first has 'assert(...);' line somewhere in it, another doesn't. If I execute Lines in the first buffer, and type 'assert' it shows the line with assert, that's fine, but if I switch to the second buffer and do the same, nothing is found. It looks like Lines and BLines commands do just the same for me. Is it supposed to work this way, or is it a bug, or I'm doing something wrong?

**Comment by netei** [comment]
It works fine for me, maybe you have some other parts of your vimrc that have some influence on that ?

**Comment by pdavydov108** [comment]
@netei I tried to comment out other plugins, without luck. However, later I realized that Lines can search in two files if I open them in two different tabs, but it doesn't work with just buffers. Is it the same for you?

**Comment by netei** [comment]
Indeed, it seems that it works if both buffers are currently shown (in two vsplits for example)

Here is a minimal vimrc to test : 

```
set nocompatible     
set rtp+=~/.fzf
call plug#begin()
Plug 'junegunn/fzf.vim'
call plug#end()
```

and then running 

`vim file1 file2` 
and inside vim: 

`:Lines`

Only the content of the first buffer is shown.

**Comment by pdavydov108** [comment]
@netei Yes, two vsplits case works for me also. I'm not sure, is it a bug, or Lines is supposed to work like this?

**Comment by junegunn** [comment]
It's because the command uses `getbufline()` function which only returns the lines from the loaded buffers.

```
		This function works only for loaded buffers.  For unloaded and
		non-existing buffers, an empty |List| is returned.

		Example: >
			:let lines = getbufline(bufnr("myfile"), 1, "$")
```

- `$ vim foo bar`
    - `foo` is displayed, `bar` is not. `bar` is not yet loaded.
    - `:Lines` will only show the lines from foo
- `:bn`
    - Loads `bar`
    - `:Lines` will then show the lines from both `foo` `bar`

I can change the implementation to fall back to `readfile()` for unloaded buffers.

**Comment by pdavydov108** [comment]
@junegunn Thanks for super quick fix, it works just fine now!
