### ISSUE TITLE
:Buffers window not opening fast enough in gvim

### ISSUE THREAD

**Issue by eduardoarandah** [junegunn/fzf.vim#864]
- Category
    - [ ] Question
    - [ ] Bug
    - [ x ] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ x ] Windows
    - [ ] Etc.
- Vim
    - [ x ] Vim (GVim)
    - [ ] Neovim

I was just comparing CtrlP and fzf (to make the switch to fzf) 

and noticed that when executing `:Buffers` the split that shows below lags a little longer thatn CtrlP `:CtrlPBuffer`

Same thing happens with `:History` and `:CtrlPMRUFiles`

CtrlP shows in like 50ms and fzf appears in around 150ms. 

I tested in 

- Gvim windows
- Vim in powershell windows
- Vim in cmd windows
- In linux, the speed is the same, tested in ubuntu WSL (windows)

My suggestion is checking how CtrlP makes the split render so fast

**Comment by junegunn** [comment]
It's probably because fzf is an external process unlike CtrlP and it's slow to start an external process on Windows. Not sure if there's a way to avoid the delay. I'd suggest that you just use CtrlP for that purpose on Windows.
