### ISSUE TITLE
Custom Rg command

### ISSUE THREAD

**Issue by Gee19** [junegunn/fzf.vim#866]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

While trying to follow the solution for #837 I ran into an issue.

vimrc:
```
command! -bang -nargs=* PRg                                                                                             
        \ call fzf#vim#grep('rg --column --no-heading --line-number --color=always '.shellescape(<q-args>),               
        \ 1,                                                                                                              
        \ {'dir': system('git rev-parse --show-toplevel 2> /dev/null')[:-2]},                                             
        \ fzf#vim#with_preview(),                                                                                         
        \ <bang>0)

nnoremap <leader><S-f> :PRg<Cr>
```

Seems I cannot pass in a `dir` while also using `with_preview`.

Trace:
```
Error detected while processing function fzf#vim#grep[22]..<SNR>80_fzf:
line   12:
E605: Exception not caught: invalid number of arguments
```

**Comment by junegunn** [comment]
> E605: Exception not caught: invalid number of arguments

The error message is pretty straightforward. Instead of passing an options dictionary (`{'dir': ... }`) and another dictionary returned by `fzf#vim#with_preview()`, pass `fzf#vim#with_preview({'dir': ...})`.
