### ISSUE TITLE
Is it possible to get Rg/Ag to only match contents?

### ISSUE THREAD

**Issue by adamyonk** [junegunn/fzf.vim#868]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible to get Rg/Ag to only match contents (and not also file paths)?
<img width="307" alt="image" src="https://user-images.githubusercontent.com/33258/64455018-1d8c4980-d0b2-11e9-80ea-1de9a28040ac.png">

**Comment by NicholasAsimov** [comment]
Add this to your vimrc: https://github.com/junegunn/fzf.vim/pull/704#issuecomment-450655634.

**Comment by adamyonk** [comment]
Thank you! 🙇

**Comment by hector-sab** [comment]
JFR. Solution for my issue is here: https://github.com/junegunn/fzf.vim/issues/1101

```vim
command! -bang -nargs=* Rg
    \ call fzf#vim#grep('rg --column --line-number --no-heading --color=always --smart-case '
    \ . (len(<q-args>) > 0 ? <q-args> : '""'), 0,
    \ fzf#vim#with_preview({'options': ['--delimiter=:', '--nth=2..', '--layout=reverse', '--info=inline']}), <bang>0)
```

**Comment by ranelpadon** [comment]
I usually use `rg` like this also, that is by searching file contents and not including the file paths for matches, and have various shell aliases for it. So, w/ Vim `fzf`, I implemented these (which could be extended for other use cases like for JS, HTML, etc). This is also removes the fuzzy matches/behavior since most of the time they're just noises:
```vim
function! RgHelper(query, fullscreen, command_fmt)
    let command_fmt = a:command_fmt . ' --no-heading --line-number --color=always --smart-case -- %s || true' 
    let initial_command = printf(command_fmt, shellescape(a:query))
    let reload_command = printf(command_fmt, '{q}')
    let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
    call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

" Search Python Files
function! RgPyFzf(query, fullscreen)
    let command_fmt = 'rg --type py'
    call RgHelper(a:query, a:fullscreen, command_fmt)
endfunction
command! -nargs=* -bang RgPy call RgPyFzf(<q-args>, <bang>0)
noremap <Leader>rp :RgPy<CR>

" Search Python/Django Unit Test Files
function! RgPyTFzf(query, fullscreen)
    let command_fmt = 'rg --type py --glob "**/tests/**"'
    call RgHelper(a:query, a:fullscreen, command_fmt)
endfunction
command! -nargs=* -bang RgPyT call RgPyTFzf(<q-args>, <bang>0)
noremap <Leader>rt :RgPyT<CR>
```
