### ISSUE TITLE
Is the :Files works in vim's mode? If so, what's that mode?

### ISSUE THREAD

**Issue by qc1iu** [junegunn/fzf.vim#869]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

I wondered if `fzf` worked in vim mode? Since I want to map some shortcut to exit `fzf` quick enough, just like vim which can change mode from `insert` to `normal` by map `jk`, but I don't know what exact mode `fzf` work with.

**Comment by stsewd** [comment]
On neovim it's on the terminal mode. You can use this to add a mapping only for fzf

```vim
autocmd! FileType fzf tnoremap <buffer> jk <cmd>bdelete!<CR>
```

**Comment by qc1iu** [comment]
> On neovim it's on the terminal mode. You can use this to add a mapping only for fzf
> 
> ```viml
> autocmd! FileType fzf tnoremap <buffer> jk <cmd>bdelete!<CR>
> ```

I think in vim8.0, fzf not work in terminal mode. Any tnoremap can't work in `:Buffers` or `:Files`

**Comment by junegunn** [comment]
It's outputting to raw terminal outside/beneath Vim. To force fzf to use a terminal buffer instead, set up `g:fzf_layout` with `window` key like so:

```vim
" 20 lines
let g:fzf_layout = { 'window': 'bot20new' }

" 40% of screen estate
let g:fzf_layout = { 'window': 'bot'.float2nr(&lines * 0.4).'new' }
```

**Comment by qc1iu** [comment]
> It's outputting to raw terminal outside/beneath Vim. To force fzf to use a terminal buffer instead, set up `g:fzf_layout` with `window` key like so:
> 
> ```viml
> " 20 lines
> let g:fzf_layout = { 'window': 'bot20new' }
> 
> " 40% of screen estate
> let g:fzf_layout = { 'window': 'bot'.float2nr(&lines * 0.4).'new' }
> ```

This solved my problem.

Thks!

**Comment by qc1iu** [comment]
Just wondering. Is there any reason to use raw terminal instead of terminal buffer by default ?
