### ISSUE TITLE
Render issues after Neovim 0.4 update

### ISSUE THREAD

**Issue by outaTiME** [junegunn/fzf.vim#871]
Hi guys, 
today i update to neovim 0.4.x and im getting wired messages and render issues, take a look:

<img width="1742" alt="image" src="https://user-images.githubusercontent.com/140472/64972749-32ba6280-d880-11e9-9243-0bc9d9f00394.png">

Any advice?

Here my config:

https://github.com/outaTiME/dotfiles/blob/master/.config/nvim/init.vim

Thanks !!!

**Comment by mnarrell** [comment]
I see this as well and had to revert to the 0.3.x branch.

https://github.com/mnarrell/dotfiles/blob/master/fzf/env.zsh
https://github.com/mnarrell/dotfiles/blob/master/nvim/after/plugin/fzf.vim

**Comment by outaTiME** [comment]
Im using homebrew and I try to revert using the following way usign the v0.3.8 version of neovim tap:

$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d6c952d1dbf93d44a88cc911f3b6c0b11c7bb4ae/Formula/neovim.rb

but now im getting wired red color as background:

<img width="1742" alt="image" src="https://user-images.githubusercontent.com/140472/64977304-83828900-d889-11e9-94ec-f333c666557b.png">

**Comment by mnarrell** [comment]
I had to download the 0.3.8 artifact from GitHub and symlinked.  I've never had luck with downgrading to an unavailable release via Homebrew.

I don't see any difference with this approach.

**Comment by dfontenot** [comment]
Seeing this as well. Versions: fzf 0.18.0, neovim 0.4.2.

**Comment by junegunn** [comment]
Sounds like an issue of Neovim terminal emulator. Please report the issue to Neovim team.

**Comment by KillTheMule** [comment]
It's a problem with the homebrew build, see https://github.com/neovim/neovim/issues/11031. Use the official binary, or update libvterm (one user on gitter said a system update will have that effect).

**Comment by Gee19** [comment]
> It's a problem with the homebrew build, see [neovim/neovim#11031](https://github.com/neovim/neovim/issues/11031). Use the official binary, or update libvterm (one user on gitter said a system update will have that effect).

Thank you 👍

**Comment by jlowgren** [comment]
It's fixed now.
