### ISSUE TITLE
colors broken after upgrading to Mac OS X Catalina and related software

### ISSUE THREAD

**Issue by snoblenet** [junegunn/fzf.vim#879]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Since upgrading to Mac OS X Catalina (and updating Neovim, Pip3, etc to keep up), every line in a FZFVim window has a red background, except for the currently selected line, which has a magenta background.

The only way to stop this is to unset `termguicolors`, but that breaks all my other highlighting.

My shell is zsh. `$TERM` is set to `xterm-256color`. Tmux is determined to have me set its `default-terminal` to `screen-256color` or `tmux-256color`, both of which make Neovim's `checkhealth` complain about the mismatch with `$TERM`.

I am using the latest fzf and fzf.vim.

I can reproduce the problem by running:
- `nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)` 
- `:set termguicolors`
- `:Files`

I have not changed any relevant settings in Neovim, ZSH or elsewhere since upgrading but I have auto-upgraded many related CLI tools etc.

**Comment by asethwright** [comment]
I think this was an issue with NeoVIM...

You are probably on nvim 0.3.7. There is a new stable version now (0.4.2).

`brew upgrade nvim` fixed this for me

**Comment by snoblenet** [comment]
Thanks that fixed it.
