### ISSUE TITLE
:GFiles and enter does not populate quickfix list

### ISSUE THREAD

**Issue by kolman** [junegunn/fzf.vim#884]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Reproducible with minimal configuration.

1. :GFiles
2. Select some files with Tab
3. Hit Enter. Quickfix list is unmodified.

Works for :Ag and :Rg, does not work for :GFiles.

fzf.vim installed with vim-plug, on commit 359a80e
fzf 0.18.0 (ff95134)
NVIM v0.4.2

I am 100% sure it worked few months ago.

**Comment by junegunn** [comment]
Only search commands based on `fzf#vim#grep()` modify the quickfix list. `:GFiles` doesn't do it. Instead, it opens them all. `:ls` to confirm.
