### ISSUE TITLE
Neovim new fzf spawn from fzf instance starts in normal mode

### ISSUE THREAD

**Issue by monkoose** [junegunn/fzf.vim#886]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Not sure if it is fzf or neovim. I have such function to 'respawn' fzf with query as argument to the same command. For preview look at this simple ls
```vim
function! s:ls_handler(lines) abort
  " exit if empty
  if a:lines == [] || a:lines == ['','','']
      return
  endif

  " Expect at least 2 elements, `query` and `keypress`, which may be empty strings.
  let query    = a:lines[0]
  let keypress = a:lines[1]
  if keypress ==? 'enter'
    let new_search = 'FzfLs ' . query
    execute new_search
  endif
endfunction

command! -nargs=* -bang FzfLs
    \ call fzf#run(fzf#wrap('ls', {
            \ 'sink*': function('s:ls_handler'),
            \ 'source': 'ls ' . <q-args> . " 2> /dev/null ",
            \ 'options': [
                  \ '--print-query',
                  \ '--expect=enter',
                  \ '--ansi',
                  \ '--exact',
                  \ '--inline-info',
                  \ '--header', ':: Press `enter` to research with current query',
                  \ ]
            \ }, <bang>0))

```
When invoke this command with `:FzfLs` it starts neovim terminal with fzf in insert mode, then when i type some query and hit `enter` it respawns neovim terminal with fzf with command and query i need but in normal mode for some reason. Had tried to add `startinsert` in various autocmds like `WinEnter` or `TermOpen` nothing helps. 
Any help? Thank you.

**Comment by monkoose** [comment]
Actually seems like it neovim related. Because it works in vim.

Does fzf spawn neovim terminal and vim terminal differently?

**Comment by junegunn** [comment]
I have no idea why they act differently, but `feedkeys` is known to help.

See https://github.com/junegunn/fzf/issues/1566#issuecomment-495041470

**Comment by monkoose** [comment]
@junegunn Thank you. It works as workaround.
I know that you don't have that much time recently to fix all the problems of fzf and fzf.vim. I will look at this problem if i can find solution without this hack.
