### ISSUE TITLE
<plug>(fzf-complete-path) and hidden files

### ISSUE THREAD

**Issue by ghetto-ch** [junegunn/fzf.vim#887]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, I,m using `<c-x><c-f> <plug>(fzf-complete-path)` and works great, but I'd like to have hidden dir/files included as well. Should this use FZF_DEFAULT_CMD? Because in shell is already setup to include hidden files.
Is there a way to do it?

**Comment by monkoose** [comment]
You need to call custom `fzf#vim#complete#path()` function, not default one that mapped to `<plug>(fzf-complete-path).
Default is `fzf#vim#complete#path("find . -path '*/\.*' -prune -o -print \| sed '1d;s:^..::'")`

**Comment by ghetto-ch** [comment]
Awesome, I will try as you suggest. Thank you @monkoose
