### ISSUE TITLE
Creating new file if there is no match?

### ISSUE THREAD

**Issue by skrobul** [junegunn/fzf.vim#89]
I am migrating from CtrlP and looking for a way to emulate `Ctrl-Y` behavior. The idea is that when I search for `foo/bar/test.txt` and there is no match, then I press `<C-y>` it will create `foo/bar/` directories if they are not present, then create new file `foo/bar/test.txt` in new buffer. Is this possible?

**Comment by junegunn** [comment]
I'm not quite sure how it makes sense for a fuzzy finder. Since fzf is a fuzzy finder, you don't type in the exact path `foo/bar/test.txt` but something like `fobtxt` or `f//tx`. Yeah, we can just make it create `f//tx`, but I don't think I like the idea.

**Comment by skrobul** [comment]
You are right, I got so used to it in CtrlP that I didn't think too much if it was the right place for it and it doesn't look like it is.


For now, I have found suitable workaround for those few times when I want all transient directories to be created automatically. Here it is for future reference if google points anyone here:

```viml
" create file with subdirectories if needed :E
function s:MKDir(...)
    if         !a:0
           \|| stridx('`+', a:1[0])!=-1
           \|| a:1=~#'\v\\@<![ *?[%#]'
           \|| isdirectory(a:1)
           \|| filereadable(a:1)
           \|| isdirectory(fnamemodify(a:1, ':p:h'))
        return
    endif
    return mkdir(fnamemodify(a:1, ':p:h'), 'p')
endfunction
command -bang -bar -nargs=? -complete=file E :call s:MKDir(<f-args>) | e<bang> <args>
```
