### ISSUE TITLE
Preview fails for `History` when path contains ~/

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf.vim#890]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I have a mapping that calls `call fzf#vim#history(fzf#vim#with_preview('right:60%'))`, i.e. displaying history of files used with preview enabled. Sometimes, the HOME part of the path is replaced with ~/. In this case the preview does not display the file.

I think the replacement is done by the plugin, and that maybe `preview.sh` gets a quoted version of the result. At least `preview.sh` fails with if I try to run it with `preview.sh "~/path/to/file"`.

**Comment by junegunn** [comment]
#774 addresses this, but the author hasn't responded to my last request. You might want to open a new pull request.

**Comment by ptzz** [comment]
#892 opened.
