### ISSUE TITLE
Paste list of files into new buffer

### ISSUE THREAD

**Issue by giddie** [junegunn/fzf.vim#893]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I'd really love the ability to select multiple files using FZF, then populate a new buffer with the list of files. If you're wondering about the usecase, I'm planning to use this in combination with the Dirvish plugin to build an arglist on which I can ultimately use an `argdo` command.

**Comment by junegunn** [comment]
I believe you can easily implement the feature.
Read https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun to learn how to write custom fzf commands.
