### ISSUE TITLE
Open FZF in virtual text mode

### ISSUE THREAD

**Issue by phaazon** [junegunn/fzf.vim#895]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hey 👋 ,

Do you think it’s possible to add a `layout` that supports virtual text? I would LOVE to see fzf.vim works a bit like what vim-clap does.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/README-VIM.md#starting-fzf-in-a-popup-window

**Comment by phaazon** [comment]
![Screenshot from 2020-03-16 16-26-45](https://user-images.githubusercontent.com/506592/76773565-f621e200-67a2-11ea-9eca-9f8c26b13ef1.png)

Doesn’t work @junegunn

**Comment by junegunn** [comment]
Update fzf.

**Comment by phaazon** [comment]
I am right now. Thanks. Sorry for the noise.
