### ISSUE TITLE
FZF and MacVim rendering issue

### ISSUE THREAD

**Issue by yar00001** [junegunn/fzf.vim#897]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim
    - [x] gvim

Similar to [this issue](https://github.com/macvim-dev/macvim/issues/579#issuecomment-549131319):

I am having the problem with rendering FZF in gvim (I am using MacVim too).
(this config works just fine for normal Vim)

![Screen Shot 2019-11-05 at 1 05 07 PM](https://user-images.githubusercontent.com/2102983/68246129-1065db00-ffcd-11e9-81cf-2838ec7ec5f2.png)

```
❯ gvim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
```

**Comment by junegunn** [comment]
I'm not sure what the problem is. Anyway, fzf works fine on Macvim for me, so it's probably a configuration issue. See if you can reproduce the problem with a minimal configuration.

https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw
