### ISSUE TITLE
Git blame all the way back for current line

### ISSUE THREAD

**Issue by kkoomen** [junegunn/fzf.vim#898]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Sometimes I use git blame to see who created this line, but since I updated the line later with a better version it displays my name. It's possible to [git blame all the way back](https://medium.com/@drdmason/git-blame-all-the-way-back-62957f8407). Can you create a `Bcommits` equivalent command that would be `Lblame` (abbr. for LineBlame) that would show all history commits changes and users (those who did the changes) of the current line I'm currently focusing?

Maybe this structure: `<commit-hash> <commit-msg> <user-name>`.

**Comment by amenl** [comment]
I like your suggestion!

**Comment by anhpt379** [comment]
I created `:LCommits` (https://github.com/junegunn/fzf.vim/pull/1288) for this.

You can add a mapping something like this:

```
vnoremap gl :LCommits<CR>
```

and then use `vgl` to trigger `LCommits` for the current line.

**Comment by junegunn** [comment]
@anhpt379 Thanks.

Now you can run `:BCommits` (or `:Commits`) with a line range to track the changes in the range. (`:Commits` with a range will be automatically translated to `:BCommits`)

FWIW, I use https://github.com/junegunn/gv.vim instead of `:BCommits` and `:Commits` for this purpose.
