### ISSUE TITLE
tjump for fzf?

### ISSUE THREAD

**Issue by cj** [junegunn/fzf.vim#90]
First off, thank you for fzf!

Has anyone made the equivalent for fzf?  https://github.com/ivalkeen/vim-ctrlp-tjump

**Comment by netei** [comment]
Is :Tags what you mean ?

**Comment by junegunn** [comment]
I updated Tags and BTags command to take an optional argument for the default query, which means you can do something like the following:

```vim
nnoremap <leader>t :Tags <c-r><c-w><cr>
```

Does this help?

**Comment by cj** [comment]
@junegunn Perfect!  Thank you :smile:

p.s. is it possible to add a `'` before the word it inserts?  I know this doesn't work, but something like this `nnoremap <leader>t :Tags <c-r>'<c-w><cr>`.

**Comment by junegunn** [comment]
You should put it before `<c-r><c-w>` which expands to the word under the cursor.
```vim
nnoremap <leader>t :Tags '<c-r><c-w><cr>
```

**Comment by cj** [comment]
Wups, of course!  Thank you again :smile:
