### ISSUE TITLE
Name of one file always prefixed with '[1 q'

### ISSUE THREAD

**Issue by axel22** [junegunn/fzf.vim#902]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When I use the `:FZF` command, one of the files in the current directory is always prefixed with `[1 q` in the list of results. Selecting it does not find that file. Screenshot below:

![screenshot-14-35-29](https://user-images.githubusercontent.com/151774/68591263-9633cb80-0490-11ea-8f2c-fbfd2a9ef5b8.png)

This does not happen with the minimal configuration.
Any ideas what could be the reason for this?

**Comment by junegunn** [comment]
No idea. You'll have to find out what's causing that in your Vim configuration.
