### ISSUE TITLE
Ag is not finding any file at start

### ISSUE THREAD

**Issue by okkan** [junegunn/fzf.vim#903]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Ag is working on my terminal with `ag -a blabla .` but in vim or neovim :Ag command opens its buffer but found files are 0/0.

![Screen Shot 2019-11-11 at 16 51 47](https://user-images.githubusercontent.com/6130890/68592236-98ebec00-04a3-11ea-8e2f-7dc9d9d67510.png)

**Comment by junegunn** [comment]
Make sure that you have the latest version of ag, and it works inside vim as well

`:!ag --version`

**Comment by okkan** [comment]
> Make sure that you have the latest version of ag, and it works inside vim as well
> 
> `:!ag --version`

it is 2.2.0 which means latest version.
<img width="422" alt="Screen Shot 2019-11-13 at 13 28 51" src="https://user-images.githubusercontent.com/6130890/68755460-91e6ea00-0619-11ea-9985-babec6aecf55.png">

**Comment by okkan** [comment]
by the way, i reinstalled ag and fzf.vim it is not solving this issue.

**Comment by okkan** [comment]
I found what is wrong, ag obeys ~/.gitignore even in other paths, and in my ~/.gitignore's content is `*`
