### ISSUE TITLE
ctrl+t will open a new tab for the same file

### ISSUE THREAD

**Issue by pbesedm** [junegunn/fzf.vim#904]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Use vim edit /a/b/c.txt, then i run :FZF，select /a/b/c.txt and ctrl+t，fzf.vim will open a new tab for c.txt.
I'm wondering, is this necessary to open a new tab for c.txt?

**Comment by junegunn** [comment]
Well, it depends on the intention and the workflow of the user. If you don't like the behavior for some reason, you can customize it by setting `g:fzf_action`.

See https://github.com/junegunn/fzf/blob/master/README-VIM.md#examples
