### ISSUE TITLE
Traversing Ag results

### ISSUE THREAD

**Issue by adamgajzlerowicz** [junegunn/fzf.vim#905]
- Category
    - [X] Question
- OS
    - [X] Linux
- Vim
    - [X] Neovim

When using Ag is it possible to traverse down and up the list with <c-k> or any other key shortcut? Arrows are way too far to reach.

Thanks

**Comment by junegunn** [comment]
CTRL-N/P or CTRL-J/K

You should really read `man fzf` first, because fzf.vim is just a wrapper around the tool.

**Comment by adamgajzlerowicz** [comment]
I will - thank you
