### ISSUE TITLE
Is there a way to customize the fzf prompt?

### ISSUE THREAD

**Issue by micalexander** [junegunn/fzf.vim#906]
- Category
    - [ x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ x] Neovim

Im wondering if there is a way to customize what the prompt looks like. In the first photo (:Files command) it is the path to the directory that I am in. In the second photo (:Buffers command) it is the word Buf>. I would like the :Files command to simply have the word Files> and the :Buffers command to simply say Buffers>

![image](https://user-images.githubusercontent.com/1943736/68875810-a9c57900-06c0-11ea-9dd5-5809f5713b69.png)

![image](https://user-images.githubusercontent.com/1943736/68875842-b6e26800-06c0-11ea-9ca0-0d26c5c2658e.png)

**Comment by micalexander** [comment]
Ahhh found it. Simply needed to pass a prompt flag

Files example:
```
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'dir': '', 'options': '--reverse --prompt Files'}), <bang>0)
```

**Comment by junegunn** [comment]
`'dir': ''` part can be removed as the argument you pass to the command (`<q-args>`) will override the value anyway.

**Comment by micalexander** [comment]
Cool, yeah I realized that.

**Comment by backpropper** [comment]
I tried using this but the options I set in $FZF_DEFAULT_OPTS and $FZF_DEFAULT_COMMAND are no longer in use. How can I make a custom prompt while still be able to use $FZF_DEFAULT_OPTS?
