### ISSUE TITLE
History command is filtering out any path with 'git/' in it

### ISSUE THREAD

**Issue by bartels** [junegunn/fzf.vim#91]
I noticed when running the `:History` command, some of my files were not showing up. I tracked the issue down the the filter string used in the `all_files` function. [Line 277](https://github.com/junegunn/fzf.vim/blob/b9285c87db7273a3a8c700c29c5e7910868392dd/autoload/fzf/vim.vim#L277)

```
 \ "v:val !~ 'fugitive:\\|__Tagbar__\\|NERD_tree\\|^/tmp/\\|.git/'"),
```

The expression  `.git/` since it's a regular expression, is filtering out paths with any character (.) and  'git/' in it, so removes any items that happen to have `git/` as part of their file path. In my case I have project directories that have a git/ folders in them, and these get removed from the results.

I think the intention is only to filter `.git/` paths exclusively. Backslashing the `.`  as `\\.git/` seems to fix it.

```
 \ "v:val !~ 'fugitive:\\|__Tagbar__\\|NERD_tree\\|^/tmp/\\|\\.git/'"),
```

**Comment by junegunn** [comment]
Fixed it. Thanks!
