### ISSUE TITLE
Cannot change fzf colors (In Ag).

### ISSUE THREAD

**Issue by DasOhmoff** [junegunn/fzf.vim#913]
Hallo, I am trying to use `command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--color-match "1;36"', fzf#vim#with_preview(), <bang>0)`, because the matching text is unreadable in my preview window. But no matter what color I choose, it still stays blue. Is there a way to fix this?:
![image](https://user-images.githubusercontent.com/16063186/70147027-bf1c3a80-16a3-11ea-9d6c-049328239850.png)

(By the way I use windows and also get a bash not found error message)
![image](https://user-images.githubusercontent.com/16063186/70147055-cba09300-16a3-11ea-8f31-076a7c365e4b.png)

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/issues/526#issuecomment-616633196
