### ISSUE TITLE
Segment fault on nvim

### ISSUE THREAD

**Issue by lourenci** [junegunn/fzf.vim#915]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi, thanks for the plugin. Fzf is one of my must-haves...

I don't know how to reproduce that nor if here is the correct place to post that, but I need some help to figure out how to resolve this.

Every now and then I get a `Segment fault` error hard quitting `nvim`, thus losing all my unsaved buffers.

Is there some way to get more details about this error to get to some point?

My config:
* `nvim 0.4.3`
* `zsh 5.7.1`
* `Mac Os`

![image](https://user-images.githubusercontent.com/2339362/70673714-45b3b780-1c62-11ea-9909-76461a98a373.png)

**Comment by junegunn** [comment]
It's an issue of Neovim, please report this to Neovim issue tracker instead.

**Comment by john-kurkowski** [comment]
(OP reported to Neovim in neovim/neovim#11548)
