### ISSUE TITLE
Vim plugin: layout inconsistency between sources

### ISSUE THREAD

**Issue by inside** [junegunn/fzf.vim#916]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

In the fzf vim plugin, I've noticed 4 sources are overwriting the layout with
`--layout=reverse-list`. This leads to inconsistency with others sources. If
there's no particular reason for this, I think it's better to let the user
choose his layout for a better developer experience.

If you agree with me, would the fix be to remove `--layout=reverse-list` from
the options? If that's the case I'd be happy to open a PR.

Please have a look at the incriminated functions:

```
~/.vim/bundle/fzf.vim/autoload/fzf/vim.vim
function! fzf#vim#lines(...)
function! fzf#vim#buffer_lines(...)
function! fzf#vim#buffer_tags(query, ...)
function! s:commits(buffer_local, args)
```

This is my configuration:

```
# ~/.zshrc
...
export FZF_DEFAULT_OPTS="--extended --layout=reverse --cycle"
...
```
```
" ~/.vimrc
...
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --no-bash' }
Plug 'junegunn/fzf.vim'
let g:fzf_layout = { 'up': '~50%' }
...
```

**Comment by junegunn** [comment]
As you can see in https://github.com/junegunn/fzf.vim#rationale, I wrote these commands for myself based on my own preferences. So you should understand that they're inherently opinionated.

If you have `--layout=reverse` in your `$FZF_DEFAULT_OPTS`, I can understand these commands overriding it with `--layout=reverse-list` is not desirable. But I don't have it in my default, so for me, it's nice that they automatically set `--layout=reverse-list`, so I'm not going to remove it.

Two options:
1. You can redefine those commands in your .vimrc with any options.
    - See https://github.com/junegunn/fzf.vim#advanced-customization
2. We can consider making those commands set up `--layout` only when `FZF_DEFAULT_OPTS` doesn't contain `reverse`.

**Comment by inside** [comment]
Thank you for pointing me to the rationale and I understand your point.

About the two options:

1. For example, the `BLines` command depends on several other functions. This would probably lead to boilerplate code in the `~/.vimrc`, but anyway feasible. :+1: 

2. Are there more people interested in this? I guess they can let us know here

Regards,

**Comment by nstetter** [comment]
I would love to see option 2 implemented

**Comment by inside** [comment]
Awesome, thanks a lot! :+1:
