### ISSUE TITLE
Reversed layout only when in floating window

### ISSUE THREAD

**Issue by Gee19** [junegunn/fzf.vim#917]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Is it possible to use `--layout=reverse` only when using a floating window? Maybe something along the lines of appending the appropriate layout to a temporary variable and passing it into the relevant fzf command. Sorry if this is a stupid question I'm pretty terrible at vimscript.

My use case is I use `:Rg!` for full screen grepping with preview where reversed layout doesn't make much sense but when it is a floating window, reversed layout is much nicer.

Examples from my dotfiles:
https://github.com/Gee19/dotfiles/commit/3cbea95835a288bc6e52cb0168487617e8541294
https://github.com/Gee19/dotfiles/blob/master/vimrc#L360-L379

Thanks!

**Comment by junegunn** [comment]
https://github.com/Gee19/dotfiles/blob/a97aefc6fb628974596b9de1879ff3cc84c594fc/vimrc#L116-L121

You can conditionally add layout option in your code like so:

```vim
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --no-heading --line-number --glob "!{.git,node_modules,static_common,*.xml,*.txt,*.csv,*.nessus,*.json,*.html}" --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview({'dir': system('git rev-parse --show-toplevel 2> /dev/null')[:-2], 'options': '--layout=default'}, 'up:60%')
  \           : fzf#vim#with_preview({'dir': system('git rev-parse --show-toplevel 2> /dev/null')[:-2]}, 'right:50%:hidden', '?'),
  \ <bang>0)
```

**Comment by Gee19** [comment]
Thanks
