### ISSUE TITLE
passing options to `:Ag`

### ISSUE THREAD

**Issue by ninrod** [junegunn/fzf.vim#92]
skimming through the source, I was positively sure that I could do `:Ag foo --hidden` and the `--hidden` option would be passed down to the ag command. But it is not working. 

Maybe this is a bug?

**Comment by junegunn** [comment]
No, it's how it's supposed to work currently. You'll have to define your own command using `fzf#vim#ag(...)` function. See #51 for the previous discussion on the topic. I'll probably provide a sample implementation as the question seems to crop up frequently.

**Comment by ninrod** [comment]
Ok. Perhaps I'm missing something. I understand that [this snippet][1] will grab `--hidden` if I ex command call `:Ag foo --hidden` and put it inside variable `ag_opts`. Then `ag_opts` gets passed down to the `printf` construct on line `424` which should produce an `ag` call with the `--hidden` option. What am I overlooking here?

[1]: <https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L419-L425>

**Comment by junegunn** [comment]
The actual command that calls the function:
https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L52

**Comment by ninrod** [comment]
I see. I understand that I'm suppose to rewrite the [fzf#vim#ag][1] function in my vimrc. Is that correct?

[1]: <https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L419-L430>

**Comment by junegunn** [comment]
Not exactly, you can do that, but it'll be much easier to just use it in your command.

```vim
function! s:ag_with_opts(arg, bang)
  let tokens  = split(a:arg)
  let ag_opts = join(filter(copy(tokens), 'v:val =~ "^-"'))
  let query   = join(filter(copy(tokens), 'v:val !~ "^-"'))
  call fzf#vim#ag(query, ag_opts, a:bang ? {} : {'down': '40%'})
endfunction

autocmd VimEnter * command! -nargs=* -bang Ag call s:ag_with_opts(<q-args>, <bang>0)
```

**Comment by caneta** [comment]
I don't know VimL, but I've modified the `ag_with_opts` function you provided above, adding a default argument `--java` and a different dir:
```
function! s:ag_with_opts(arg, bang)
  let tokens  = split(a:arg)
  call insert(tokens, '--java')
  let ag_opts = join(filter(copy(tokens), 'v:val =~ "^-"'))
  let query   = join(filter(copy(tokens), 'v:val !~ "^-"'))
  call fzf#vim#ag(query, ag_opts, extend({'dir': '~/myJavaRepo/src/'}, a:bang ? {} : {'down': '40%'}))
endfunction

" AgC: Custom Ag call
autocmd VimEnter * command! -nargs=* -bang AgC call s:ag_with_opts(<q-args>, <bang>0)
```
Of course it can be improved and cleaned up, but it works: hope to be helpful.

**Comment by junegunn** [comment]
@caneta Thanks. We now have `fzf#vim#ag_raw` function that does interpret the given argument and simply pass it to the underlying ag command. You might want to take a look at it.

**Comment by ninrod** [comment]
@junegunn maybe we ought to close this then?

**Comment by caneta** [comment]
Where can I found this new `ag_raw` function? Is it alreadey in the fzf codebase?
Updating fzf and fzf.vim, I cannot find it.
An example of its usage would be nice, thanks.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L530-L547

Something like this: `call fzf#vim#ag_raw('foo ~')`

**Comment by caneta** [comment]
I'm not able to make the new function work, I've tried the following attempts, without success:
```
autocmd VimEnter * command! -nargs=* -bang AgC call fzf#vim#ag_raw('--java ~/myJavaRepo/src/')
autocmd VimEnter * command! -nargs=* AgC call fzf#vim#ag_raw('--java ~/myJavaRepo/src/')
autocmd VimEnter * command! AgC call fzf#vim#ag_raw('--java ~/myJavaRepo/src/')
```
None of the reported above work: the terminal freezes.

How to have the same result reported [in this comment](https://github.com/junegunn/fzf.vim/issues/92#issuecomment-229883364), so adding a --java flag and specifying a custom directory?

**Comment by peanutandchestnut** [comment]
You need to try your desired ag command at shell first, make sure it works before you try it with this plugin.  And i think it's a bad idea to create some command to search in specific directory,  this should be done with symbolic link,  you can also view third lib files easily if you use symbolic link.

**Comment by caneta** [comment]
@peanutandchestnut:
1. If it works? But it's in the codebase already, I suppose it has been tested before pushing it.
2. Ag provide the [PATH] optional argument, so why to drop this possibility in fzf command which relies on it? Your idea is to create a symlink in every project i work on, pointing to an external directory I'm interested to? It seems not very comfortable...

**Comment by peanutandchestnut** [comment]
@caneta 
Sorry for my poor English.<br>
What i said is to try your desired ag command in linux shell first,  fzf#vim#ag_raw works fine for me.<br>
Different projects depend on different third libs,  i think it's natural to create a dependencies directory for it.  If you need to ignore dependencies from git, you might found it useful to create a small viml func to convert relative path(which is dependencies/someLib) to absolute path before sent to fzf#vim#ag_raw.<br>

**Comment by caneta** [comment]
@peanutandchestnut don't worry, english is a problem for me too! ;-)

Could you report the lines of code you used to test ag_raw function, please? How you make it callable from bash? How you call it and what parameters are you using?

I don't get the point of the git/viml function.
My use case is the following:
1. I open nvim on my current project code
2. I want to run Ag through fzf in a complete different directory, **unrelated** from my current nvim working dir
3. how to do that with the ag_raw func? I achieved that goal [here](https://github.com/junegunn/fzf.vim/issues/92#issuecomment-229883364) with ag_with_opts function, but I would like not to use a custom function now that I have something in the code base...I don't know Viml, so I need some code line examples...

**Comment by peanutandchestnut** [comment]
@caneta
All my settings related to fzf. Ignore Ae if you feel uncomfortable to create extra dependencies for each project.

```viml
"fzf------------------------------------------------------------
let g:fzf_action = {
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit',
      \ 'ctrl-a': 'argedit',
      \ 'ctrl-o': '!gvfs-open'
      \ }
let g:fzf_layout = {"up":'~40%'}
nnoremap <c-p><c-p> :Files<CR>
nnoremap <c-p><c-f> :call <SID>fzf('find -L . -type f ! -path "*.hg/*" ! -path "*.git/*"', ':Files') <CR>
nnoremap <c-p><c-a> :call <SID>fzf('find -L . -type f', ':Files') <CR>
nnoremap <c-p><c-g> :GitFiles<CR>
"nnoremap <c-p><c-g>? :GitFiles?<CR>
nnoremap <c-p><c-b> :Buffers<CR>
"nnoremap <c-p><c-c> :Colors<CR>
"nnoremap <c-p><c-a> :Ag<CR>
"nnoremap <c-p><c-l> :Lines<CR>
nnoremap <c-p><c-l> :BLines<CR>
nnoremap <c-p><c-t> :Tags<CR>
nnoremap <c-p><c-j> :BTags<CR>
autocmd! FileType cpp  nnoremap <buffer> <c-p><c-j> : call <SID>fzf_cpp_tags()<CR>
"nnoremap <c-p><c-j> :BTags<CR>
"nnoremap <c-p><c-m> :Marks<CR>
nnoremap <c-p><c-w> :Windows<CR>
"nnoremap <c-p><c-l> :Locate<CR>
nnoremap <c-p><c-h> :History<CR>
"nnoremap <c-p><c-;> :History:<CR>
"nnoremap <c-p><c-/> :History/<CR>
nnoremap <c-p><c-s> :Snippets<CR>
"nnoremap <c-p><c-c> :Commits<CR>
"nnoremap <c-p><c-b>c :BCommits<CR>
nnoremap <c-p><c-c> :Commands<CR>
nnoremap <c-p><c-m> :Maps<CR>
command! -nargs=* -complete=file Ae :call s:fzf_ag_expand(<q-args>)

"nnoremap <c-p>h :Helptags<CR>
"nnoremap <c-p>f :Filetypes<CR>

"command! -nargs=* -complete=file AA :call s:fzf_ag_raw(<q-args>)
autocmd! VimEnter * command! -nargs=* -complete=file Ag :call s:fzf_ag_raw(<q-args>)

let s:fzf_btags_cmd = 'ctags -f - --sort=no --excmd=number --c++-kinds=+p '
let s:fzf_btags_options = {'options' : '--reverse -m -d "\t" --with-nth 1,4.. -n 1,-1 --prompt "BTags> "'}
function! s:fzf_cpp_tags()
call fzf#vim#buffer_tags(
      \ "",[s:fzf_btags_cmd . expand('%:S')],
      \ extend(copy(g:fzf_layout), s:fzf_btags_options))
endfunction

function! s:fzf(fzf_default_cmd, cmd)
  let oldcmds = $FZF_DEFAULT_COMMAND | try
    let $FZF_DEFAULT_COMMAND = a:fzf_default_cmd
    execute a:cmd
  finally | let $FZF_DEFAULT_COMMAND = oldcmds | endtry
endfunction

function! s:fzf_ag_raw(cmd)
  call fzf#vim#ag_raw('--noheading '. a:cmd)
endfunction

" some path is ignored by git or hg, i need to use absolute path to avoid that.
function! s:fzf_ag_expand(cmd)
  let matches = matchlist(a:cmd, '\v(.{-})(\S*)\s*$')
  " readlink, remove trailing linebreak
  let ecmd = matches[1] . system("readlink -f " . matches[2])[0:-2]
  call s:fzf_ag_raw(ecmd)
endfunction
```

**Comment by caneta** [comment]
Thank you @peanutandchestnut: after a lot of attempts I got a working one:
```
autocmd! VimEnter * command! -nargs=* -complete=file AgC :call fzf#vim#ag_raw('--java '. <q-args> .' ~/myJavaRepo/src/')
```
This line in my neovim configuration file allows me to search for java files only inside `~/myJavaRepo/src/` directory

**Comment by dhilst** [comment]
Simpler `alias ag='ag --your-fancy-option` before start vim

**Comment by nadim** [comment]
Goal:
Open files containing a specific string.

Command:
`:Ag -l myStringToSearch`

The results pop up correctly, however when I hit select all or try to open a specific result I get:
```
Error detected while processing function 316[30]..<SNR>16_callback:
line   21:
Vim(let):E684: list index out of range: 1
```

I don't know what this line 21 refers to. 

Is this something that can be fixed? Is there a better way to accomplish the same thing?

**Comment by Zarathustra2** [comment]
@nadim 
Based on a previous anwser by junegunn & others in another issue try this:

```vim
function! s:find_git_root()  
   return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction

 command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'dir':s:find_git_root(),'options': '--delimiter : --nth 4..'}, <bang>0)
```

**Comment by codingedward** [comment]
I finally got mine to work:
```vim
command! -bang -nargs=* FzfAg                              
  \ call fzf#vim#ag(<q-args>,
  \                 '--ignore "node_modules"',  " <--- any options here
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
```
