### ISSUE TITLE
Search files from the nearest ancestor of current file that contains .git, etc

### ISSUE THREAD

**Issue by juniway** [junegunn/fzf.vim#920]
* Category
  * [ ]  Question
  * [ ]  Bug
  * [x]  Suggestion

* OS
  * [x]  Linux
  * [x]  macOS
  * [x]  Windows
  * [x]  Etc.

* Vim
  * [x]  Vim
  * [x]  Neovim

Assume I have a project whose structural is like:

```
└── proj/
    ├── .git/
    ├── a/
    │   ├── a1.txt
    │   └── a2.txt
    ├── b/
    │   ├── b0.txt
    │   ├── b1.txt
    │   ├── b2.txt
    │   └── e/
    │       ├── e1.txt
    │       └── g/
    │           ├── g1.txt
    │           ├── g2.txt
    │           └── g3.txt
    └── c
        └── d
            └── e
                └── f
                    ├── f1.txt
                    ├── f2.txt
                    └── f3.txt
```

somehow I cded into directory f, a very deep inner directory, and I happen to need to fix a bug in g2.txt, so I type `vim $(fzf)` with filename matching g2.txt, and start to edit it in vim, then I find that I need to modify some variables which maybe located in b1.txt or g1.txt (or some other files out of the current directory, which is f) , then I enter :Files but since I am in f, it limits me only to search files in f, or I have to cd into the root directory of the project, which is probably cumbersome. 

Now comes the feature I want, would it be possible for fzf to recognize that I am actually in a git project (with .git in it's root directory) and at anytime I am in any sub-directory I can search file for the whole project? In another word, I can just stay in f and still able to search for the whole project, not just files in f.

Actually, I am migrating from [CtrlP](https://github.com/kien/ctrlp.vim), it has accomplished this feature and more, I think it really helps me a lot.

<img width="863" alt="nearest_ancestor_directory" src="https://user-images.githubusercontent.com/3980841/71141506-4eeae880-224f-11ea-9423-8cfcc1693930.png">

**Comment by junegunn** [comment]
For some reason, you have filled in an outdated version of the issue template. Please update the template.

**Comment by juniway** [comment]
template fixed

**Comment by junegunn** [comment]
No, this is the one: https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md

**Comment by juniway** [comment]
I've searched all through these readmes and issues, nerve found the feature I want, did I miss something?

**Comment by junegunn** [comment]
I'm just asking you to follow the rules. You should properly fill in the "right" issue template, not the outdated one.

And you can find the answers in

- #47
- #123
- #267
- #465

**Comment by juniway** [comment]
well, I implemented it by myself, looks like I just need to learn some vim script language~

```viml
function! s:findRoot()
  let result = system('git rev-parse --show-toplevel')
  if v:shell_error == 0
    return substitute(result, '\n*$', '', 'g')
  endif
  return "."
endfunction

function! fzf#vim#files(dir, ...)
  let dir = s:findRoot()
  let args = {}
  let args.options = ['-m', '--prompt', strwidth(dir) < &columns / 2 - 20 ? dir : '> ']
  call s:merge_opts(args, get(g:, 'fzf_files_options', []))
  return s:fzf('files', args, a:000)
endfunction

```

**Comment by juniway** [comment]
sorry for the buzz

**Comment by juniway** [comment]
I suggest make it a plugin provided command make a explanation in the README file, because we can't assume every people know vimscript and has to find a solution from the ISSUEs section when they want, or confused about that functionality.

**Comment by junegunn** [comment]
This repository isn't for "every people", and I'm not interested in using my time to make it for every people. It is stated in [Rationale](https://github.com/junegunn/fzf.vim#rationale) section.

And it looks like you skipped over [the relevant section in the README page](https://github.com/junegunn/fzf.vim#example-customizing-files-command), you don't redefine `fzf#vim#files` in this plugin, you "use it" to define variations of the command in your configuration file.

**Comment by junegunn** [comment]
And I should mention that we also have `GFiles` and `GFiles?`.

**Comment by juniway** [comment]
That's not my final version, just some experiments. But I got it, your comments are helpful and thanks a lot for you work.
