### ISSUE TITLE
How to search case sensitive with Ag?

### ISSUE THREAD

**Issue by lazamar** [junegunn/fzf.vim#921]
If I'm searching for `client` for example, I would not like to have matches like `Client`.

I'm currently doing 
```
:Ag client
```

With `ag` the `-s` flag makes it case sensitive. But this didn't work.
```
:Ag -s client
```

What is the correct way to pass the case sensitivity flag to Ag?

**Comment by junegunn** [comment]
Please fill in the issue template.

**Comment by timmyjose** [comment]
@lazamar This works for me in version 2.2.0. Perhaps this can be confirmed and closed?

**Comment by Jasha10** [comment]
I am having a similar issue with a very recent version of fzf.vim.
The main question is: is there a convenient way to pass command-line flags to the :Ag command (or other similar commands).

**Comment by Jasha10** [comment]
Cross-link to a related post by junegunn that would seem to answer this question: https://github.com/junegunn/fzf.vim/issues/838#issuecomment-509902575

Basically, the answer is to define a new command.

**Comment by lukelbd** [comment]
@Jasha10 Thanks for the cross-post. Looks like that answer comes from [these lines in the `fzf.vim` plugin file](https://github.com/junegunn/fzf.vim/blob/5d87ac1fe8d729f116bda2f90a7211ad309ddf5a/plugin/fzf.vim#L56-L58). To figure out an `ag` solution I used [these lines in the `fzf.vim` autoload file](https://github.com/junegunn/fzf.vim/blob/5d87ac1fe8d729f116bda2f90a7211ad309ddf5a/autoload/fzf/vim.vim#L831-L848). 

The solution is a little different: It seems that unlike `fzf#vim#grep()`, `fzf#vim#ag()` does accept user flags, but they have to be passed as string arguments before other default arguments. The below seems to work:

```vim
# Original Ag command
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, fzf#vim#with_preview(), <bang>0)

# New Ag command
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--case-sensitive', fzf#vim#with_preview(), <bang>0)
```

**Comment by junegunn** [comment]
Yes. And there is also `ag_raw` function in case you want to pass all arguments directly to ag.

https://github.com/edwinst/fzf.vim/blob/c1c65bfbe690b85e3966467e0c19a3e7d9098c1f/autoload/fzf/vim.vim#L830-L848
