### ISSUE TITLE
Large delay when dismissing fzf window using escape

### ISSUE THREAD

**Issue by cespare** [junegunn/fzf.vim#923]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

This is essentially the same issue as #248, which is closed. However, the issue is definitely not fixed.

There is a noticeable, annoying delay when hitting escape to dismiss the fzf window. [This code](https://github.com/junegunn/fzf/blob/d4ad4a25db5fd314de355c1a2a8ee9dd209d54c0/src/tui/light.go#L23) suggests that there is an intentional delay of 100ms; however, the actual delay is much longer than that (it's a little hard to measure but I think it's around 700ms). Furthermore, setting `ESCDELAY=10` has no perceivable effect. Setting `ESCDELAY=1000` makes the delay significantly longer. Therefore, I believe that the actual delay is coming from somewhere else other than the intended "escape delay".

**Comment by junegunn** [comment]
Is the problem reproducible outside Vim? If it isn't so, you might want to check your Vim configuration, such as terminal buffer maps.

**Comment by junegunn** [comment]
Note that if you're on tmux, `escape-time` setting of tmux (which defaults to 500ms) also affects the delay.

**Comment by cespare** [comment]
> Note that if you're on tmux, `escape-time` setting of tmux (which defaults to 500ms) also affects the delay.

Ah! Yes, this is what I'm seeing. I didn't think to try to repro without tmux. Thanks!
