### ISSUE TITLE
Vim failed execute :Files and other directions.

### ISSUE THREAD

**Issue by Joxos** [junegunn/fzf.vim#930]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

![image](https://user-images.githubusercontent.com/37507136/72198672-0c8e8300-346c-11ea-91df-16e3417d92bb.png)
Have downloaded the latest version now. But the plugin is still not work. Please help me.

**Comment by junegunn** [comment]
Follow the instruction in the error message (`Download fzf binary ...`) and it'll work.
