### ISSUE TITLE
select lines and append to [fuzzy find] file

### ISSUE THREAD

**Issue by sjhogerzeil** [junegunn/fzf.vim#935]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I would like to write a vim command that allows me to:

1. from the current vim buffer cut a selection of lines
2. **with fzf select a target file**
3. append the selection of lines to the target file
4. continue working in current buffer

I tried to write a variant of 
- `:'<,'> :w >> /foo/target` towards the form
- `:'<,'> :w >> FZF' etc, but got nowhere

My question is: **how can I call FZF** in this "**select | fuzzy-find | append**" sequence to select my target file for appending?

**Comment by junegunn** [comment]
No easy way to do it. You probably need to write some VimScript. 

https://github.com/junegunn/fzf/blob/master/README-VIM.md
