### ISSUE TITLE
Where is fzf#run defined?

### ISSUE THREAD

**Issue by dhilst** [junegunn/fzf.vim#936]
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

Hi, I'm beginning with vimscript, I have a small plugin for running ansible tasks from vim, put it's using `!command`, I wan't it to run on a terminal as fzf.vim does.

I was trying to read fzf source but can't locate fzf#run anywhere, what I'm missing?

Regards and thanks for bringing fzf to us 

I search by running this `grep -rn fzf#run ~/.vim/plugged/fzf.vim/`
output:
``` 
/home/dhilst/.vim/plugged/fzf.vim/README.md:260:of options is pretty much identical to that for `fzf#run` only with the
/home/dhilst/.vim/plugged/fzf.vim/autoload/fzf/vim.vim:218:  return fzf#run(s:wrap(a:name, merged, bang))
/home/dhilst/.vim/plugged/fzf.vim/autoload/fzf/vim.vim:1229:  call fzf#run(opts)
/home/dhilst/.vim/plugged/fzf.vim/doc/fzf-vim.txt:306:of options is pretty much identical to that for `fzf#run` only with the
```

I can't find `fzf#run` anywhere, how does this works?

**Comment by junegunn** [comment]
Please properly fill in the issue template.

**Comment by dhilst** [comment]
I edited the issue

**Comment by dhilst** [comment]
Okay, I found it, it's on another project

**Comment by DZ84** [comment]
You can find it with something like [profile](https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow)

For me it's in /usr/share/vim/vimfiles/plugin
