### ISSUE TITLE
is it possible to change the colors of the bottom line

### ISSUE THREAD

**Issue by joe23rep** [junegunn/fzf.vim#938]
- [ x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

this is more of a question than an issue

as u can maybe see on my screenshot i like to tweak my vim / desktop quite a bit. i read threw lots and lots of other issues and read your read.me's but couldnt figure out.

is it possible to configure the line with just the > and fzf in it? just changing its colors would be enough. further customisation like adding different nerd font glyps instead of the > would be the cherry on top. but most importantly its just the color. 

![2020-01-25-053609_526x490_scrot](https://user-images.githubusercontent.com/59401314/73116549-5f6e3d00-3f38-11ea-9c77-81fd69668ac7.png)

**Comment by junegunn** [comment]
The answer is on https://github.com/junegunn/fzf.vim/blob/master/README.md#status-line-of-terminal-buffer
