### ISSUE TITLE
How about :Toc for markdown?

### ISSUE THREAD

**Issue by rawaludin** [junegunn/fzf.vim#94]
I really like fzf. Is it possible to list toc of markdown heading in fzf too?
Maybe add `:Toc` command.. :)

**Comment by rahmatawaludin** [comment]
Actually I see this feature in plasticboy/vim-markdown. But, its not as easy to navigate on the Toc as using fzf. You might want to see this https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L298

**Comment by noahfrederick** [comment]
I adapted the `:Blines` command for a more [generalized solution](https://github.com/noahfrederick/dots/blob/6e105e7fb8983d83ea2059e2b60e4d4d27eafb3d/vim/autoload/nox/fzf.vim#L248-L279). You can set `b:interesting_lines_filter` to a regex for a given file type such as Markdown (e.g., `^#\+\s`) to see only matching lines. Of course, it's not particularly sophisticated (won't work on non-ATX-style headings).

**Comment by junegunn** [comment]
Would be nice if vim-markdown provides an API so that we can use it to implement the feature.

**Comment by rahmatawaludin** [comment]
Ok, I made the issue on the vim markdown repo. Let see whether its possible.. :)

https://github.com/plasticboy/vim-markdown/issues/270

**Comment by rahmatawaludin** [comment]
Anyway, this line seems to be the one used to filter heading lines..
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L318

````
let l:line = substitute(l:lineraw, "#", "\\\#", "g")
````
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L336

````
if l:line =~ '^#\+' || (l:l1 =~ '^=\+\s*$' || l:l1 =~ '^-\+\s*$') && l:line =~ '^\S'
````

**Comment by shirosaki** [comment]
This patch with vim-markdown works for me.

`:call fzf#vim#toc()` shows heading.

```patch
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index cbb5eb5..2ebfe09 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -216,6 +216,24 @@ function! fzf#vim#lines(...)
   \}), a:000)
 endfunction

+function! fzf#vim#toc(...)
+  try
+    :Toc
+  catch /^Vim\%((\a\+)\)\=:E492/
+    " No :Toc command
+    return
+  endtry
+  let loclist = getloclist(0)
+  :lclose
+  let lines = map(loclist,
+    \ 'printf("[%s]\t%s:\t%s", s:blue(v:val["bufnr"]), s:yellow(v:val["lnum"]), v:val["text"])')
+  return s:fzf(fzf#vim#wrap({
+  \ 'source':  lines,
+  \ 'sink*':   s:function('s:line_handler'),
+  \ 'options': '+m --tiebreak=index --prompt "Toc> " --ansi --extended --nth=3.. --reverse --tabstop='.&tabstop
+  \}), a:000)
+endfunction
+
 " ------------------------------------------------------------------
 " BLines
 " ------------------------------------------------------------------
```

**Comment by junegunn** [comment]
Thanks for the input. It's nice that the plugin exports the result as location list. It makes me think that it's better that fzf.vim should provide a command for location list instead. I'll think about it.

**Comment by junegunn** [comment]
#64
