### ISSUE TITLE
Non-popup floating/overlay support?

### ISSUE THREAD

**Issue by jesseleite** [junegunn/fzf.vim#942]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Now that we have [floating popup window support](https://github.com/junegunn/fzf.vim/issues/821) (thank you! 🎉), I'm wondering if it's possible to add a floating option to the default non-floating-window mode.  What I mean by this is, I still prefer everything about how the default non-floating-window looks (position, border, etc.), but have always disliked how it pushes buffer content up off the top of the screen, ie)

![Screen Capture on 2020-02-04 at 09-21-18](https://user-images.githubusercontent.com/5187394/73752918-c5747480-472f-11ea-815d-ead516253d55.gif)

Given the recent popup window improvements, would it now be possible to have fzf float/overlay the buffer content at the bottom of a window, without pushing it up?

**Comment by junegunn** [comment]
Added `xoffset` (0 ~ 1), `yoffset` (0 ~ 1), and `border` (`rounded` | `sharp` | `horizontal`) options.

```vim
let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.4, 'yoffset': 1, 'border': 'horizontal' } }
```

**Comment by jesseleite** [comment]
@junegunn wicked, this is wonderful, thank you 🎉

Now I'm wondering about some sort of `top` only border option?  Would be nice to remove the bottom border line completely, moving the fzf results down one line, if that makes sense... 

![Screen Shot 2020-02-06 at 09 35 17](https://user-images.githubusercontent.com/5187394/73946515-07ceba80-48c4-11ea-98f9-18c84c6189e5.png)

What are your thoughts on this?

**Comment by junegunn** [comment]
Well, I'd not like to end up with too many options. Can you try it for a while and see if you can get used to it?

**Comment by jesseleite** [comment]
@junegunn totally trying it out.  I just think on a bottom panel, a bottom border is a wasted line, and doesn't really make sense.  Like if you use some sort of side panel like NerdTree, TagBar, or even your Peekaboo plugin, there will be a border on the inside edge, but not on the outside edge.  Nawmean?

**Comment by junegunn** [comment]
I realized more options can be useful when you want to launch fzf as a sidebar. So here it is: https://github.com/junegunn/fzf/commit/4fb410a93c6567cfae1a72e1581a3bd193cd307a

**Comment by jesseleite** [comment]
Yassssss.  This is 🔥, thank you so much @junegunn ❤️

**Comment by reportaman** [comment]
@junegunn Is it possible to open a fzf window in current split? It doesn't matter if it is floating or not...

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/commit/8b0e1f941a419258b0877d9a5f71373d76472043

**Comment by reportaman** [comment]
@junegunn I get some weird error (happens only with neovim), whenever I run FZF from a split. It does not happen with vim.

```
Error detected while processing function <SNR>84_dopopd:
line   20:
E716: Key not present in Dictionary: "dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))"
Press ENTER or type command to continue
Error detected while processing function <SNR>84_dopopd:
line   20:
E15: Invalid expression: s:fzf_getcwd() ==# w:fzf_pushd.dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))
Press ENTER or type command to continue
Error detected while processing function 25[29]..<SNR>84_pushd:
line   10:
E121: Undefined variable: w:fzf_pushd
Press ENTER or type command to continue
Error detected while processing function 25[29]..<SNR>84_pushd:
line   11:
E121: Undefined variable: w:fzf_pushd
Press ENTER or type command to continue
Error detected while processing function 25[29]..<SNR>84_pushd:
line   11:
E15: Invalid expression: w:fzf_pushd
Press ENTER or type command to continue
```
