### ISSUE TITLE
E278 "Cannot put a terminal buffer in a popup window"

### ISSUE THREAD

**Issue by Blake-LeBlanc** [junegunn/fzf.vim#943]
- [ X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [ X] I have searched through the existing issues

Trying to get the new fzf popup display to work with VIm 8.2.

Set up .vimrc per the readme with the following: 

`let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }`

Whenever I then try to launch fzf, I receive the following error messages: 

```
Error detected while processing function <SNR>54_vmd[15]..fzf#run[64]..<SNR>54_execute_term[3]..<SNR>54_split[10]..<SNR>54_popup[19]..<SNR>54_create_popup: 

line 3: 

E278: Cannot put a terminal buffer in a popup window
```

It then proceeds to display a blank popup window. 

Whenever I quit vim, the following warning displays:

`Kill job in "!sh"? Y/N/C:`

Any ideas what I did wrong?

Thanks again for such a great plugin! :)

**Comment by blayz3r** [comment]
Do you have the latest vim??

**Comment by Blake-LeBlanc** [comment]
Hello @blayz3r ! I'm on 8.2

**Comment by blayz3r** [comment]
> Hello @blayz3r ! I'm on 8.2

Yes, but the change was added in the last couple of days patch 8.2.0191

**Comment by Blake-LeBlanc** [comment]
Oh, thanks for the heads-up @blayz3r, I'll rebuild from source, give it another shot, then report back!

**Comment by Blake-LeBlanc** [comment]
That did the trick, thank you @blayz3r !
