### ISSUE TITLE
Invalid arguments for function term_start(&shell, #{hidden: 1})

### ISSUE THREAD

**Issue by naknode** [junegunn/fzf.vim#944]
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I am trying to get the new window option to work like so:

```
nmap <leader>f :GFiles<cr>" fuzzy find files in the working directory (where you launched Vim from)
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

And when I do the "ctrl+f", I get the error below.

I use VimPlugin and have already updated via `PluginUpdate`. 

I have VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40.

> Error detected while processing function fzf#vim#gitfiles[6]..<SNR>113_fzf[18]..fzf#run[64]..<SNR>26_execute_term[3]..<SNR>26_split[10]..<SNR>26_popup[16]..<SNR>26_create_popup:
> line    2:
> E116: Invalid arguments for function term_start(&shell, #{hidden: 1})
> Error detected while processing function fzf#vim#gitfiles:
> line    6:
> E171: Missing :endif
>

**Comment by ApplicationDeveloper** [comment]
![image](https://user-images.githubusercontent.com/10027925/73802092-73972180-47f7-11ea-9e39-895d64f2d54f.png)

Did you check vim --version if you have +popupwin feature?
I would recommend upgrading to vim 8.2

**Comment by naknode** [comment]
@ApplicationDeveloper That was it. Thanks.
