### ISSUE TITLE
bind change:reload for vim functions

### ISSUE THREAD

**Issue by antoinemadec** [junegunn/fzf.vim#948]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

First, thanks a lot for this great plugin :smiley: 
I would like to know if the ```change:reload``` could be extended to **vim functions**. Here is what I have tried:
```vim
  let reload_command = printf('function(s:get_symbols(%s))', '{q}')
  let l:opts = {
        \ 'source': s:get_symbols(''),
        \ 'sink*': function('s:symbol_handler'),
        \ 'options': ['--multi','--expect='.expect_keys, '--bind', 'change:reload:'.reload_command,
        \ '--layout=reverse-list', '--ansi', '--prompt=' . s:prompt],
        \ }
  call fzf#run(fzf#wrap(l:opts))
```
```s:get_symbols``` uses ```CocAction('getWorkspaceSymbols', a:query)``` from **coc.nvim**.
I am currently in the process of writing [coc-fzf](https://github.com/antoinemadec/coc-fzf) and this feature would help me add the ```CocList symbols``` functionality.

**Would 'bind change:reload for vim functions' be a feature that could be implemented?**

Thanks a lot!
Antoine

**Comment by junegunn** [comment]
No, `reload` expects a shell command. fzf is an external program running outside of vim, so there's no direct way for it to access Vim functions. You'll have to come up with a command that can interact with Vim/Neovim (using some kind of RPC/IPC mechanism if there's any) or COC process (if it provides APIs).

Please let me know if you find a way to do it. Thanks.

**Comment by antoinemadec** [comment]
@junegunn , here is how I implemented it:
[get_workspace_symbols.py](https://github.com/antoinemadec/coc-fzf/blob/master/script/get_workspace_symbols.py) is using ```pynvim``` to call a vim function kindly provided by ```coc.nvim```.
Here is how the call to this script looks like: [symbols.vim](https://github.com/antoinemadec/coc-fzf/blob/master/autoload/coc_fzf/symbols.vim#L6)

Maybe the ```--bind change:reload:vim_function``` could be implemented using a temporary script under the hood? Might be a bit hacky though...

Thanks a lot for the great plugin anyway :smiley:

**Comment by myitcv** [comment]
Just to add a quick note of thanks here. In the [`govim`](https://github.com/govim/govim) project we have just [implemented functionality to use `--bind change:reload:..`](https://github.com/govim/govim/issues/795) and the discussion here helped massively. So thank you!
