### ISSUE TITLE
MRU Buffers

### ISSUE THREAD

**Issue by vito-c** [junegunn/fzf.vim#95]
Would be great if there was a way to have an MRU sorting on the buffers option (but still be able to select buffers by number of course).

Most Recently Used buffer would be your first selection. Then typing in the filter would still maintain the MRU sorting... 

I would also like to see a toggle command to be able to sort by buffer name, buffer number, or MRU.

Thanks!

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/474
Implementing MRU requires extra bookeeping and I'm not interested in adding that to this repository.

**Comment by junegunn** [comment]
So, basically, you should be able to define your own command using `fzf#run` function if some MRU plugin offers a public API that exposes the list.
