### ISSUE TITLE
Suggestion: like :Buffers but delete (multiple)

### ISSUE THREAD

**Issue by amenl** [junegunn/fzf.vim#950]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Please, ask for clarification if necessary.

Should I hack this myself? I never felt the urge to enter vimscript, though...

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf.vim/pull/733#issuecomment-559720813
