### ISSUE TITLE
Suggestion: like BLines but show only certain markdown level headings

### ISSUE THREAD

**Issue by amenl** [junegunn/fzf.vim#951]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

This seems easy to me, because I can emulate it by filtering :BLines with "^#". However I'd like fzf.vim to show only 1st level headings and advance by the press of a button to lower level headings. Is this possible? Do I need to learn vimscript? :monkey:

**Comment by junegunn** [comment]
> Do I need to learn vimscript? 

Yes, because I don't need it and I won't implement it myself :)
