### ISSUE TITLE
:Buffers + preview displays: 

### ISSUE THREAD

**Issue by esn89** [junegunn/fzf.vim#955]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Using fzf + fzf.vim + kitty terminal on Mac OSX

Whenever I try to bring up my buffers with preview, I get something say that the file is not found: 

https://i.imgur.com/LNgUHgY.png

**Comment by junegunn** [comment]
This section should answer your question. You should remove `--preview` option from your FZF_DEFAULT_OPTS.

https://github.com/junegunn/fzf#preview-window

**Comment by esn89** [comment]
@junegunn 
Hmm, no luck.  These are my current settings for the environment variables of FZF:
```
export FZF_DEFAULT_COMMAND="rg --files --iglob '!*.m4a' --iglob '!*.mp3' --iglob '!*.flac' --iglob '!*.pdf' --iglob '!*.jgp' --iglob '!*.JPG' --iglob '!*.png' --iglob '!*.zip' --iglob '!*.jpeg' --iglob '!*.m4a' --iglob '!~/Library/*'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND --iglob '!~/Library/*'"
export FZF_CTRL_T_OPTS="--height 100% -e --inline-info --preview '(highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'"
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
```

I have since removed the --preview from FZF_DEFAULT_OPTS

**Comment by sushovannits** [comment]
Hi has this been solved? Facing the same thing.
