### ISSUE TITLE
Is there a way to change format of the buffer list?

### ISSUE THREAD

**Issue by npearson72** [junegunn/fzf.vim#956]
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

When executing `:Buffer`, the list shows a path, ex:

`[1] lib/some/path/to/file.rb`

I would like to format it where the filename is first, ex:

`[1] file.rb - lib/some/path/to`

Is this possible?

**Comment by junegunn** [comment]
No, customization of the format is not supported. (https://github.com/junegunn/fzf.vim#rationale)
