### ISSUE TITLE
Toggle fzf

### ISSUE THREAD

**Issue by vito-c** [junegunn/fzf.vim#96]
I use a mapping to look at open buffers <leader>l most of the time I want to select a buffer from the list sometimes I change my mind. There should be a way to have most of these fuzzy finder commands toggle. So that the user can pass a flag to the command and if the window is already open it will close it. That way I can just set the flag on the ones I want to toggle.

**Comment by junegunn** [comment]
I'm not sure if I follow, what do you mean by "toggle"?

> sometimes I change my mind.

Closing fzf with CTRL-C or ESC won't do?

**Comment by vito-c** [comment]
I usually use `CTRL-D` to close the fzf terminal buffer. I have most "helper buffers" setup to toggle on a single leader mapping. So for example `<leader>oq` opens the quickfix window then I can close the quickfix window with the same command `<leader>oq`

I could probably figure out the buffer name and add it to my plugins just though I'd create the issue though incase others found it useful.

**Comment by junegunn** [comment]
Maybe you can try setting up tnoremap like follows:
```
autocmd! FileType fzf tnoremap <buffer> <leader>q <c-c>
```
