### ISSUE TITLE
Keyboard scrolling in :Rg result buffer

### ISSUE THREAD

**Issue by ChangWanHong** [junegunn/fzf.vim#961]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I found kind of this: https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0152, but it doesn't work. I assign ctrl-b and ctrl-f to preview-up and preview-down each into fzf_action, but it make escaping from Rg result buffer. How can I fix this?

**Comment by junegunn** [comment]
You should post your code when you submit an issue or I can't help.
