### ISSUE TITLE
Is it possible to make `:Files` give less priority the index.js files?

### ISSUE THREAD

**Issue by chris-fran** [junegunn/fzf.vim#966]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

### Description

I follow the `index.js` pattern on my project, where you put an index file that reexports the main module, so that you can import it by referencing the enclosing directory

```
src/component/MyComponent/MyComponent.js
src/component/MyComponent/index.js

// consumer.js
import MyComponent from './src/component/MyComponent';
```
The problem is that when I do `:Files<cr>MyComp`, the `index.js` file is always the first selection, unless I do `:Files<cr>MyComp.js` (type an extra `.js`).

Since the`index.js` is just a re-export, 99% of the time I use `:Files` I don't intend to open it. Is there a way we can force so that it's not the first highlighted option?

**Comment by junegunn** [comment]
`:Files` is equivalent to running fzf without standard input pipe (see https://github.com/junegunn/fzf#respecting-gitignore). So the list is determined by the result of `$FZF_DEFAULT_COMMAND`, so customize your `$FZF_DEFAULT_COMMAND` as desired.

Alternatively, you can write a custom command with a custom source as described in:
- https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun
