### ISSUE TITLE
FZF Preview Window Colors

### ISSUE THREAD

**Issue by ldelossa** [junegunn/fzf.vim#969]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x ] I have searched through the existing issues

Hello there. 

I manage a vim theme here: https://github.com/ldelossa/vimdark
I recently upgraded fzf and found a preview window is now present. 
I'm looking to change the colors of the text in this preview window to align with my theme. Currently they are off. 

![Screenshot from 2020-03-25 12-45-36](https://user-images.githubusercontent.com/5642902/77565231-4f240100-6e9a-11ea-83e3-adb9fa9b6fe6.png)

**Comment by jessemillar** [comment]
Just figured this out myself. Seems like the preview window colors are determined by the `bat` theme you have selected.

Also, if you're in Neovim, you'll need to enable truecolor support via `set termguicolors` in your `init.vim` and setting `COLORTERM="truecolor"` in your shell: https://github.com/junegunn/fzf.vim/issues/756

**Comment by ldelossa** [comment]
@jessemillar nice! thanks! let me see if I can find a suitable bat theme.

**Comment by WhyNotHugo** [comment]
I'd also like to configure the colours of the preview window, but I'm not using `bat`, just plain old fzf-vim.

Not sure if I should open a separate issue for that, any hints?

**Comment by junegunn** [comment]
> preview inside Vim can share the same colour scheme as Vim

fzf is an external program so it's simply not possible. Using bat and setting BAT_THEME is the best and the simplest way available to achieve customizable syntax highlighting inside fzf.

**Comment by WhyNotHugo** [comment]
Oh, it's `fzf` that does the preview rendering? I didn't know that part!

Why not use something like vimpager for the previews though? It seems odd that a plugin for a file-editor would use a _separate_ file viewer. It's kinda like a Firefox plugin using chrome to render HTML.

Having to install a separate tool that does what Vim already does for a Vim plugin is just... odd.

**Comment by pvonmoradi** [comment]
@WhyNotHugo  @ldelossa 
For a temporary workaround, I used this snippet in my vimrc:  
```vim
set background="light"
" handling setting and unsetting BAT_THEME for fzf.vim
augroup update_bat_theme
    autocmd!
    autocmd colorscheme * call ToggleBatEnvVar()
augroup end
function ToggleBatEnvVar()
    if (&background == "light")
        let $BAT_THEME='Monokai Extended Light'
    else
        let $BAT_THEME=''
    endif
endfunction
```  
- If you like, do a `bat --list-themes` and grab a light theme instead of that `Monokai Extended Light`
- The original `$BAT_THEME` of the terminal from which vim is invoked from, would not be mutated.

**Comment by ldelossa** [comment]
Thanks! Thats exactly what i did.

**Comment by jeanlucthumm** [comment]
@pvonmoradi for some reason setting the env variable within vim is not working for me: 

In the shell I have:
```
$ echo $BATH_THEME
Solarized (light)
```
Then in my [vim config](https://github.com/jeanlucthumm/dotfiles/blob/master/.config/nvim/init.vim#L121) I have:
```
let $BAT_THEME='gruvbox'                                                                                                                                                                               
colorscheme gruvbox
```
And I can confirm that it's set correctly in vim:
```
:echo $BAT_THEME
gruvbox
```
And yet still, the preview window has solarized colors. (although it's solarized dark instead of light)

**Comment by pvonmoradi** [comment]
@jeanlucthumm 
I just tested these lines from your vimrc:  
```vim
function! GruvboxTheme()
  let g:gruvbox_italic=1
  let g:gruvbox_bold=1
  let g:airline_theme='gruvbox'
  let $BAT_THEME='gruvbox'
  colorscheme gruvbox
endfunction

set background=dark
call GruvboxTheme()
```
The env var is set properly and fzf preview window theme is gruvbox. (tested with `bat 0.17.1`, `fzf 0.24.4 (00a3610)`, `vim 8.2`)

Just to be clear, there is no vimrc in your source dir, and `echo $BAT_THEME` prints valid result *just before* testing fzf preview, right?
How are you testing fzf preview? Is it also problematic with `:History` (fzf.vim plugin function not coc-fzf)?
