### ISSUE TITLE
Allow for global option?

### ISSUE THREAD

**Issue by lotabout** [junegunn/fzf.vim#97]
FZF now allows `g:fzf_action`, is there any plan of adding global option?

I was intended to change the key binding for `toggle` from `TAB` to `ctrl-f` and that means I should pass `--bind ctrl-f:toggle` to 'options'.

But currently there is no way to set the option for all commands that FZF supports, just like `g:fzf_action`.

**Comment by junegunn** [comment]
That should go into `$FZF_DEFAULT_OPTS`.
You can either set it in your shell configuration file (`export FZF_DEFAULT_OPTS='...'`) or in your vimrc (`let $FZF_DEFAULT_OPTS = '...'`).

**Comment by lotabout** [comment]
Thank you for quick response. That works! Sorry for miss that.
