### ISSUE TITLE
Showing unlisted buffers

### ISSUE THREAD

**Issue by ayroblu** [junegunn/fzf.vim#971]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi just wondering how to show unlisted buffers with `:Buffers`. I know you can do it with `:buffers!` or `:ls!`, so I'm wondering if there's an equivalent in fzf?

The main reason I care is cause coc.vim uses them when refactoring a variable and based on: https://github.com/neoclide/coc.nvim/issues/1691 it looks like that's desired behaviour.

Thanks so much, really love your new work!

**Comment by junegunn** [comment]
No, it only shows listed buffers. I'm not going to add an option for it as it's a niche use case. I suggest that you consider editing the source code or write your own command for that case.

(e.g. https://github.com/junegunn/fzf.vim/pull/733#issuecomment-559720813)

**Comment by ayroblu** [comment]
Thanks for this, I had a look at the source code, and because fzf implements `buflisted` and `bufnr` which have no unlisted counterparts, it lacks native vim support even for a PR. Will try use the referenced fzf#run code. Thanks!

**Comment by mgarort** [comment]
Hi @ayroblu , do you think you could share your code for the new `Buffers` function that shows unlisted buffers? I have taken a look at your dotfiles but haven't been able to find it. Thanks! :)

**Comment by ayroblu** [comment]
I didn't want to maintain a fork, and I can't use this for work so it's been a while. I believe what I did was delete the check [here](https://github.com/junegunn/fzf.vim/blob/711fb41e39e2ad3abec1ec9720782acbac6fb6b4/autoload/fzf/vim.vim#L285) for `buflisted(v:val) &&`

**Comment by riteshharjani** [comment]
For now I modified it to this in my "vim/plugged/fzf.vim/autoload/fzf/vim.vim" 

```
function! s:buflisted()
  return filter(range(1, bufnr('$')), 'bufexists(v:val) && getbufvar(v:val, "&filetype") != "qf"')
endfunction
```
