### ISSUE TITLE
Incompatibility with coc.nvim completions

### ISSUE THREAD

**Issue by aasutossh** [junegunn/fzf.vim#974]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

It's really confusing. So if I open a file with `:Files` the `coc.nvim` completions sometimes doesn't work. Completions meaning `snippets` and `Intellisense completions`. Where as if I use other programs such as `ctrlp` or `:e` to open file, then it always works.

I thought it may be `fzf`'s issue. If not feel free to close.

**Comment by junegunn** [comment]
It's not. I use coc.nvim and fzf.vim with no problems.

**Comment by aasutossh** [comment]
Thanks for clearing it.

I am gonna try to debug it if I can.
