### ISSUE TITLE
Help needed: GGrep open prompt only 

### ISSUE THREAD

**Issue by vpshastry** [junegunn/fzf.vim#977]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I copied the GGrep command from the readme of the project. If no arguments given, it passes no arguments to git grep making it search with an empty string. This takes huge amount of time. If I then start typing my search query, there is a short delay until it starts searching my query. 

I've my shortcut set to GGrep (<leader>gg). With this short cut I want the git grep fzf prompt to just open but search nothing. But then I start typing my search query which should then be the beginning of searching. This can benefit in two ways,
1. No unneccessary search on the empty string
2. Save time on the delay between searching everything and searching my query.

Can somebody help building this query?

**Comment by junegunn** [comment]
I haven't tried, but you might want to experiment with `reload` action similarly to

https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration
