### ISSUE TITLE
[ERROR] I can't use bat to preview. (error: Found argument '--pager' which wasn't expected)

### ISSUE THREAD

**Issue by GGCristo** [junegunn/fzf.vim#978]
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

I got this annoying message:
![Screenshot_20200408_000452](https://user-images.githubusercontent.com/58046649/78727693-49fc9280-792d-11ea-8fc8-31ad9c9c7c5b.png)
This is my configuration in my .vimrc
```
set rtp+=~/.fzf
let g:fzf_buffers_jump = 1
let g:fzf_preview_window = 'right:60%'
command! -bang -nargs=? -complete=dir Files
   \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)
```
Note: It works if I use it with cat.
```
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)
```

**Comment by junegunn** [comment]
Have you tried upgrading bat?

**Comment by GGCristo** [comment]
Using sudo tells me I am in the newer version (0.8.0) I think. Anyway I installed it a couple of months ago, so I don't think that is the problem.

**Comment by junegunn** [comment]
You need at least 0.9.0 which was released in November 2018.

https://github.com/sharkdp/bat/releases/tag/v0.9.0

**Comment by GGCristo** [comment]
Thanks, already fixed. Sometimes I forget Ubuntu has old packages.
