### ISSUE TITLE
Jump to existing window/tab when using :Buffers

### ISSUE THREAD

**Issue by jjbruno** [junegunn/fzf.vim#98]
I remember CtrlP has a option(g:ctrlp_switch_buffer) which instead of opening the buffer in the current window, it will jump to the window/tab where the buffer is open.
So, in fzf, using :Buffers, it will always open the buffer in the current window, even it is already open somewhere. There such a option to make :Buffers jump to where the buffers is open instead to opening it in the current window?
I tried the vim 'drop' and 'sbuffer' commands but no success
```
  let g:fzf_action = {
    \  ...
    \ 'ctrl-t': 'drop',
    \ 'ctrl-v': 'sbuffer',
    \  ... }
```

**Comment by junegunn** [comment]
There's `:Windows` command, but you seem to want a hybrid of `:Buffers` and `:Windows`?

**Comment by jjbruno** [comment]
Thank's for the response. That is exactly, a hybrid of :Buffers and :Windows

**Comment by junegunn** [comment]
Added `g:fzf_buffers_jump` variable you can set.

**Comment by GGCristo** [comment]
Hi, it is too much to ask if you can do the same with :Files ?

**Comment by GGCristo** [comment]
Hi, it is too much to ask if you can do the same with :Lines ?

**Comment by l13rb4git** [comment]
> Hi, it is too much to ask if you can do the same with :Lines ?

I would like to request the same.

**Comment by unphased** [comment]
I would like to request the same for :Files...

**Comment by GGCristo** [comment]
@unphased 
```
let g:fzf_action = {
      \ 'enter': drop,
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }
```

**Comment by unphased** [comment]
@GGCristo Much appreciated, I learned about `:tab drop` today, and finally found the documentation for `:tab drop`, it's under the `:drop` documentation!

Meanwhile I have already banged out a solution that gives me the granular control that I want, even though I realize now I might be more or less satisfied with the config you've provided.

Here it is:

```
" custom fzf handling lets me implement always jumping to the chosen file if already open somewhere
function! s:open_with_fzf(files)
	let x = split(execute('ls a'), "[\n\r]")
	let alreadyOpened = []
	for l:line in x
		" these are open ("active") filenames
		let filename = split(l:line, '"')[1]
		let index = index(a:files, filename)
		if index != -1
			call add(alreadyOpened, [index, filename])
		endif
	endfor

	" if multiple requested files are already opened, we end up going to the earliest one in the 
	" buffer list
	if len(alreadyOpened) > 0
		execute("tab drop ".alreadyOpened[0][1])
	else
		" split (my personal perference), unless in empty buffer in which case replaces
		if @% == ""
			" was in empty buffer
			" echom 'empty buf, making new'
			let last = a:files->remove(-1)
			execute("e ".last)
		endif
		" if greater than 3 items, open them all as tabs
		for l:fileToOpen in a:files
			if (len(a:files) > 3)
				echom 'tabe '.l:fileToOpen
				execute("tabe ".l:fileToOpen)
			else
				execute("split ".l:fileToOpen)
			endif
		endfor
	endif
endfunction

" add ctrlq to default maps
let g:fzf_action = {
  \ 'enter': function('s:open_with_fzf'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit' }

```
