### ISSUE TITLE
FZF Opens Buffer Selector on Save

### ISSUE THREAD

**Issue by ldelossa** [junegunn/fzf.vim#981]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hello, 

For some reason fzf-vim seems to open a buffer selector when writing to the only buffer open. I am trying to figure out if this is expected behaviour and if I can disable this? Attaching screen shot below.

This seems to happen some what intermittently. When I have a single buffer open and write `:w` fzf seems to intercept this and shows me a buffer selection. When I select that buffer, I must write once again `:w`. This is not ideal. 

![Screenshot from 2020-04-13 11-52-20](https://user-images.githubusercontent.com/5642902/79135760-d966d300-7d7d-11ea-8a05-7e3adca7c487.png)

I can avoid this problem by disabling fzf-vim so I have narrowed it down to this plugin.

**Comment by ldelossa** [comment]
I can actually reproduce this now, it seems like it happens after about 4 ":w" commands in quick succession.

**Comment by junegunn** [comment]
Sounds like a configuration issue. Have you tested with the minimal config?

https://raw.githubusercontent.com/junegunn/fzf.vim/master/.github/ISSUE_TEMPLATE.md

**Comment by ldelossa** [comment]
happened first try on minimal vim config. 

![Screenshot from 2020-04-13 13-30-04](https://user-images.githubusercontent.com/5642902/79143273-f2c24c00-7d8a-11ea-8847-75315a93c219.png)

**Comment by ldelossa** [comment]
issue is also not present if `: wa` is used instead of `:w`

**Comment by junegunn** [comment]
Looks like you mistyped `:W`  (uppercase) and Vim automatically recognized it as `:Windows` because there's no other command that starts with `:W`. You'll have the same result when you type in `:Wi`, `:Win`, `:Wind`, ..., etc.

**Comment by ldelossa** [comment]
wow... you are totally right. Thanks for that! re-mapped `:W` to `:w` and no longer a problem. Sorry about that!
