### ISSUE TITLE
Add setlocal filetype=fzf when opening a terminal buffer

### ISSUE THREAD

**Issue by kdheepak** [junegunn/fzf.vim#982]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Right now if I have the following in my .vimrc:

```
tnoremap <silent> <c-h> <c-\><c-n>:TmuxNavigateLeft<cr>
tnoremap <silent> <c-j> <c-\><c-n>:TmuxNavigateDown<cr>
tnoremap <silent> <c-k> <c-\><c-n>:TmuxNavigateUp<cr>
tnoremap <silent> <c-l> <c-\><c-n>:TmuxNavigateRight<cr>
```

then I'm unable to navigate the fzf candidates.

If you add `setlocal filetype=fzf` when opening a terminal buffer, then users can do something like this:

```
function s:AddTerminalNavigation()

    if &filetype ==# ''
        tnoremap <buffer> <silent> <c-h> <c-\><c-n>:TmuxNavigateLeft<cr>
        tnoremap <buffer> <silent> <c-j> <c-\><c-n>:TmuxNavigateDown<cr>
        tnoremap <buffer> <silent> <c-k> <c-\><c-n>:TmuxNavigateUp<cr>
        tnoremap <buffer> <silent> <c-l> <c-\><c-n>:TmuxNavigateRight<cr>
    endif

endfunction

augroup TerminalNavigation
    autocmd!
    autocmd TermOpen * call s:AddTerminalNavigation()
augroup END
```

If there's another way to achieve this, please advice. I'd like to use `c-<h,j,k,l>` to navigate between terminal buffers and vim buffers (and tmux buffers) but I'd also like to use `c-<j,k>` to move between candidates in a fzf terminal buffer.

See this issue discussion for more context: https://github.com/christoomey/vim-tmux-navigator/pull/172#issuecomment-612219227

**Comment by junegunn** [comment]
We already do that:

https://github.com/junegunn/fzf/blob/dea206b023a695b75540f642a0b19a3ba1e38eec/plugin/fzf.vim#L764

However, fzf currently does not open in a terminal buffer iff

1. You use regular Vim rather than Neovim
2. And you use the default layout (opens at the bottom of the screen)

If you want to force fzf to open in a terminal buffer, set up `window` layout as described in the following page.

https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration

**Comment by kdheepak** [comment]
Thanks, that is perfect!

**Comment by kdheepak** [comment]
Hi @junegunn, I tested this out and it still does not work as intended. I believe this is because `setf fzf` is called after the terminal is created, and hence if I add a autocommand to `TermOpen` the filetype is still empty string at that point. Would it be possible to move `setf fzf` to _before_ calling `termopen`?

**Comment by junegunn** [comment]
No, changing it will break user scripts. Just set up `autocmd FileType fzf` that does the same.

**Comment by kdheepak** [comment]
Thanks for the quick reply. I don't follow your suggestion exactly. I need to add an autocmd for all terminals except fzf, ranger and other tools. How would I do this would `autocmd FileType fzf`? Are you suggesting adding a autocommand that does a `tnoremap <C-j> <nop>`?
