### ISSUE TITLE
How can I jump to the next or previous  file in result list

### ISSUE THREAD

**Issue by sunliang711** [junegunn/fzf.vim#986]
Hello, recently I find an amazing tool: fzf, I very love it. But I have a problem when using it: when I enter fzf.vim Files or Rg or Ag window,enter some word,then fzf shows some results that match what I entered，then I choose an item(file), press enter to jump to that file to edit, after doing some work on the file,I want to jump the next or previous item of the last results of fzf found. 
So, how could I do to achieve the goal ?Thanks in advance.

**Comment by milushov** [comment]
I wondering the same
