### ISSUE TITLE
Helptags doesn't work (windows)

### ISSUE THREAD

**Issue by habamax** [junegunn/fzf.vim#987]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

* OS: windows 10
* vim version: 8.2.582
* nvim version: 0.5.0-330

If I try `:Helptags` right after vim has started (default working dir is the one where vim is installed):

![image](https://user-images.githubusercontent.com/234774/79538521-2eac2880-808d-11ea-943f-a74fa452f91b.png)

Start typing -- no errors, no data:

![image](https://user-images.githubusercontent.com/234774/79538564-48e60680-808d-11ea-8c28-a835c366e271.png)

If I open my config file (working dir is also changed to `~/vimfiles`), number of items is different (but still nothing is showing):

![image](https://user-images.githubusercontent.com/234774/79538885-df1a2c80-808d-11ea-8d08-165c86104595.png)

Start typing, I get:

![image](https://user-images.githubusercontent.com/234774/79539143-6c5d8100-808e-11ea-887e-edf04390c376.png)

**Comment by habamax** [comment]
Didn't know it requires perl and grep, but fortunately both are installed and available on my win box.

Although I am not sure what perl magic is written to a temp file to be executed in `s:fzf`

**Comment by dseeni** [comment]
same here, strawberry perl and grep installed via scoop.. anyone know how to get this to work on windows?

**Comment by dseeni** [comment]
> Didn't know it requires perl and grep, but fortunately both are installed and available on my win box.
> 
> Although I am not sure what perl magic is written to a temp file to be executed in `s:fzf`

Hey habamax,
Were you able to get this working on windows? 
I

**Comment by habamax** [comment]
@dseeni nope, I didn't have time to look into it closer (and I don't speak perl, so for me it would be not an easy thing to do)

**Comment by habamax** [comment]
Well I figure it out, partly.

https://github.com/junegunn/fzf.vim/blob/a74605b81d0dc2b28d35d9a1ab414dbdcbe3f45b/autoload/fzf/vim.vim#L1027

On my windows box I don't thing this linux like piping would work. So if I remove it:

```
  return s:fzf('helptags', {
  \ 'source':  'grep -H ".*" '.join(map(tags, 'fzf#shellescape(v:val)')),
  \ 'sink':    s:function('s:helptag_sink'),
  \ 'options': ['--ansi', '+m', '--tiebreak=begin', '--with-nth', '..-2']}, a:000)
```

Then it kind of works -- I can see help, and looks like perl script removes that long filenames?

![image](https://user-images.githubusercontent.com/234774/82649715-5198a200-9c22-11ea-94d7-762adb42e8b2.png)

**Comment by habamax** [comment]
Or it is just perl script is windows strawberry perl incompatible.

**Comment by habamax** [comment]
and here is the fix:

this line:
https://github.com/junegunn/fzf.vim/blob/a74605b81d0dc2b28d35d9a1ab414dbdcbe3f45b/autoload/fzf/vim.vim#L1024

should be changed to:

```
  call writefile(['/('.(s:is_win ? '^[A-Z]:[\/\\].*?[^:]' : '.*?').'):(.*?)\t(.*?)\t/; printf(qq('.s:green('%-40s', 'Label').'\t%s\t%s\n), $2, $3, $1)'], s:helptags_script)
```

It incorrectly detects windows file path assuming it is forward slash `/`. Which is not always the case, so fix is to check forward and backward slashes.

**Comment by habamax** [comment]
@junegunn, @ladevieq should I create PR or for this trivial fix this is not needed?

**Comment by habamax** [comment]
@janlazo could you also check this?

**Comment by dseeni** [comment]
wow thank you a bunch habamax! awesome fix. Yeah these sort of things come up a lot it seems when you're working on windows (pathing issues, escaping properly etc)
