### ISSUE TITLE
Preview doesn't work on Windows

### ISSUE THREAD

**Issue by habamax** [junegunn/fzf.vim#988]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Instead of a file preview I get `/bin/bash: .... no such

![image](https://user-images.githubusercontent.com/234774/79543533-4dfb8380-8096-11ea-9d6c-cee8890ee5ab.png)

**Comment by habamax** [comment]
Looks like bash on windows can't use absolute paths?

![image](https://user-images.githubusercontent.com/234774/79544325-851e6480-8097-11ea-9b0b-d8f107059ed8.png)

**Comment by habamax** [comment]
BTW, I saw a closed issue which suggests that preview would use ruby script if ruby is available.

I have it available and still fzf tries to use bash

**Comment by michael-angelozzi** [comment]
I have the same issue, except for me the preview always says:
```
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore 
```

**Comment by janlazo** [comment]
@michael-angelozzi That is WSL bash, not git bash.

**Comment by michael-angelozzi** [comment]
@janlazo  On my machine:
```
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
```
The topic "Preview doesn't work on Windows" is the same issue for me, that's why I posted in this thread instead of starting a new.

**Comment by janlazo** [comment]
It finds WSL bash first so adjust your `PATH` environment variable so that cmd.exe or vim/nvim finds git bash or any working bash executable (ie. busybox) first in PATH.

I suppose fzf and fzf.vim can fail early if this happens but that won't close the issue.

**Comment by GasparVardanyan** [comment]
Nothing helped me so I've launched cmd as administrator and deleted C:\System32\bash.exe :d
Now vim-fzf works in my nvim !!
