### ISSUE TITLE
Neovim compatibility issue. 

### ISSUE THREAD

**Issue by changs** [junegunn/fzf.vim#99]
Hi. 
The `:FZF` command works as expected but I have problem with custom commands. When I try to use some of the commands from fzf.vim or my own like 
```
nnoremap <silent> <Leader>m :call fzf#run({ 'source': 'modified.sh', 'sink': 'e', 'options': '-m', 'down': '50%'})<CR>
```
it opens an empty split, and then I need to press `<ESC>` to have some results there. I assume that this is because `fzf#run` is asynchronous in neovim, but since the original `:FZF` command works well, there is probably a way to make also custom commands work. I found in the documentation that I should use `sink or sink*` to make it work, but I'd love to see some examples of that.

Thanks!

**Comment by junegunn** [comment]
```vim
" ls instead of your modified.sh
nnoremap <silent> <Leader>m :call fzf#run({'source': 'ls', 'sink': 'e', 'options': '-m', 'down': '50%'})<CR>
```

works just fine both in vim and neovim for me. I don't know about your `modified.sh` but if it's in `$PATH` and it works (check the output of `:echo system('modified.sh')`), then I don't think you'll have any problem with that. If you still have the issue, try testing it with a minimal Vim configuration without any other settings and plugins that might interfere.

**Comment by changs** [comment]
I've been able to find the offending line in my config.
```let g:fzf_nvim_statusline = 0```
so the problem is already mentioned here https://github.com/junegunn/fzf.vim/issues/84
My bad that I didn't found that issue earlier. 
Thanks for help, you've been doing a great work!
