### ISSUE TITLE
How to use Vim's default 'complete' option with fzf

### ISSUE THREAD

**Issue by vkrajacic89** [junegunn/fzf.vim#992]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi,
Is there a way to pipe Control-N results to fzf and offer filtered results in the same default popup window? Basically, I want to add fzf to Vim's existing 'complete' system.

Thanks,
Vjekoslav

**Comment by junegunn** [comment]
It's not currently possible.
