### ISSUE TITLE
How can I use fzfvim with Vim 8 Plugin Manager

### ISSUE THREAD

**Issue by bugb** [junegunn/fzf.vim#994]
- [o] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [o] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [o] I have read through the manual page of fzf (`man fzf`)
- [o] I have searched through the existing issues
- [o] FZF work but FZF Vim does not work

I tried to install fzfvim with Vim 8 by following command:

```
git clone git@github.com:junegunn/fzf.vim.git ~/.vim/pack/vendor/start/fz
```

But it seems does not work, when I try to use `Files` command, I got this

![image](https://user-images.githubusercontent.com/9280412/79960446-9ad4c500-84af-11ea-927e-bd0ce2d6609b.png)

**Comment by junegunn** [comment]
Excerpt from https://github.com/junegunn/fzf.vim#installation

>  you need to set up both "fzf" and "fzf.vim"

**Comment by bugb** [comment]
Sorry but I already have fzf anf fzf.vim

![image](https://user-images.githubusercontent.com/9280412/79974618-da0d1100-84c3-11ea-984d-426ec3df3313.png)

**Comment by junegunn** [comment]
> you need to set up both "fzf" and "fzf.vim" **on Vim**

**Comment by bugb** [comment]
Yes, it helps
