### ISSUE TITLE
configuration to exclude some tag files

### ISSUE THREAD

**Issue by nkcfan** [junegunn/fzf.vim#995]
- [ ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I am using ctags in vim8 for C++ development. To be able to access standard library headers, I added a system tag file.
```
:echo tagfiles()
['tags', '/home/nkcfan/.vim/systags']
```
The systags is generated from '/usr/include', '/usr/local/include'.

Using FZF `Tags` command, I want to only search project `tags` file and ignore the `systag`. I read the code and found it is using `tagfiles()`. Is it possible to add a configuration to exclude some tag files?

**Comment by junegunn** [comment]
`:help tagfiles()` shows that you can customize the output with `:help 'tags'`. You might want to experiment with it.
